{{ config(materialized='view', tags=['ExtAppCclAppChlApp']) }}

WITH JoinSrcSortReject AS (
	SELECT
		{{ ref('XfmCheckNulls__OutCheckNullsSorted') }}.APP_ID,
		{{ ref('XfmCheckNulls__OutCheckNullsSorted') }}.APP_APP_ID,
		{{ ref('XfmCheckNulls__OutCheckNullsSorted') }}.APP_SUBTYPE_CODE,
		{{ ref('XfmCheckNulls__OutCheckNullsSorted') }}.APP_APP_NO,
		{{ ref('XfmCheckNulls__OutCheckNullsSorted') }}.APP_CREATED_DATE,
		{{ ref('XfmCheckNulls__OutCheckNullsSorted') }}.APP_CREATED_BY_STAFF_NUMBER,
		{{ ref('XfmCheckNulls__OutCheckNullsSorted') }}.APP_OWNED_BY_STAFF_NUMBER,
		{{ ref('XfmCheckNulls__OutCheckNullsSorted') }}.APP_CHANNEL_CAT_ID,
		{{ ref('XfmCheckNulls__OutCheckNullsSorted') }}.APP_LODGEMENT_BRANCH_ID,
		{{ ref('XfmCheckNulls__OutCheckNullsSorted') }}.APP_SM_CASE_ID,
		{{ ref('XfmCheckNulls__OutCheckNullsSorted') }}.CCL_APP_CCL_APP_ID,
		{{ ref('XfmCheckNulls__OutCheckNullsSorted') }}.CCL_APP_CCL_APP_CAT_ID,
		{{ ref('XfmCheckNulls__OutCheckNullsSorted') }}.CCL_APP_CCL_FORM_CAT_ID,
		{{ ref('XfmCheckNulls__OutCheckNullsSorted') }}.CCL_APP_TOT_PERSONAL_FAC_AMT,
		{{ ref('XfmCheckNulls__OutCheckNullsSorted') }}.CCL_APP_TOT_EQUIPFIN_FAC_AMT,
		{{ ref('XfmCheckNulls__OutCheckNullsSorted') }}.CCL_APP_TOT_COMMERCIAL_FAC_AMT,
		{{ ref('XfmCheckNulls__OutCheckNullsSorted') }}.CCL_APP_TOPUP_APP_ID,
		{{ ref('XfmCheckNulls__OutCheckNullsSorted') }}.CCL_APP_AF_PRIMARY_INDUSTRY_ID,
		{{ ref('XfmCheckNulls__OutCheckNullsSorted') }}.CCL_APP_AD_TUC_AMT,
		{{ ref('XfmCheckNulls__OutCheckNullsSorted') }}.CCL_APP_COMMISSION_AMT,
		{{ ref('XfmCheckNulls__OutCheckNullsSorted') }}.CCL_APP_BROKER_REFERAL_FLAG,
		{{ ref('XfmCheckNulls__OutCheckNullsSorted') }}.CHL_APP_HL_APP_ID,
		{{ ref('XfmCheckNulls__OutCheckNullsSorted') }}.CHL_APP_HL_PACKAGE_CAT_ID,
		{{ ref('XfmCheckNulls__OutCheckNullsSorted') }}.CHL_APP_LPC_OFFICE,
		{{ ref('XfmCheckNulls__OutCheckNullsSorted') }}.CHL_APP_STATUS_TRACKER_ID,
		{{ ref('XfmCheckNulls__OutCheckNullsSorted') }}.APP_FOUND_FLAG,
		{{ ref('XfmCheckNulls__OutCheckNullsSorted') }}.CCL_APP_FOUND_FLAG,
		{{ ref('XfmCheckNulls__OutCheckNullsSorted') }}.CHL_APP_FOUND_FLAG,
		{{ ref('XfmCheckNulls__OutCheckNullsSorted') }}.CHL_TPB_HL_APP_ID,
		{{ ref('XfmCheckNulls__OutCheckNullsSorted') }}.CHL_TPB_SUBTYPE_CODE,
		{{ ref('XfmCheckNulls__OutCheckNullsSorted') }}.REL_MANAGER_STATE_ID,
		{{ ref('XfmCheckNulls__OutCheckNullsSorted') }}.DATE_RECEIVED,
		{{ ref('XfmCheckNulls__OutCheckNullsSorted') }}.CHL_APP_PCD_EXT_SYS_CAT_ID,
		{{ ref('XfmCheckNulls__OutCheckNullsSorted') }}.CHL_TPB_FOUND_FLAG,
		{{ ref('Transformer_216') }}.APP_ID AS APP_ID_R,
		{{ ref('Transformer_216') }}.APP_APP_ID_R,
		{{ ref('Transformer_216') }}.APP_SUBTYPE_CODE_R,
		{{ ref('Transformer_216') }}.APP_APP_NO_R,
		{{ ref('Transformer_216') }}.APP_CREATED_DATE_R,
		{{ ref('Transformer_216') }}.APP_CREATED_BY_STAFF_NUMBER_R,
		{{ ref('Transformer_216') }}.APP_OWNED_BY_STAFF_NUMBER_R,
		{{ ref('Transformer_216') }}.APP_CHANNEL_CAT_ID_R,
		{{ ref('Transformer_216') }}.APP_LODGEMENT_BRANCH_ID_R,
		{{ ref('Transformer_216') }}.APP_SM_CASE_ID_R,
		{{ ref('Transformer_216') }}.CCL_APP_CCL_APP_ID_R,
		{{ ref('Transformer_216') }}.CCL_APP_CCL_APP_CAT_ID_R,
		{{ ref('Transformer_216') }}.CCL_APP_CCL_FORM_CAT_ID_R,
		{{ ref('Transformer_216') }}.CCL_APP_TOT_PERSONAL_FAC_AMT_R,
		{{ ref('Transformer_216') }}.CCL_APP_TOT_EQUIPFIN_FAC_AMT_R,
		{{ ref('Transformer_216') }}.CCL_APP_TOT_COMMERCIAL_FAC_AMT_R,
		{{ ref('Transformer_216') }}.CCL_APP_TOPUP_APP_ID_R,
		{{ ref('Transformer_216') }}.CCL_APP_AF_PRIMARY_INDUSTRY_ID_R,
		{{ ref('Transformer_216') }}.CCL_APP_AD_TUC_AMT_R,
		{{ ref('Transformer_216') }}.CCL_APP_COMMISSION_AMT_R,
		{{ ref('Transformer_216') }}.CCL_APP_BROKER_REFERAL_FLAG_R,
		{{ ref('Transformer_216') }}.CHL_APP_HL_APP_ID_R,
		{{ ref('Transformer_216') }}.CHL_APP_HL_PACKAGE_CAT_ID_R,
		{{ ref('Transformer_216') }}.CHL_APP_LPC_OFFICE_R,
		{{ ref('Transformer_216') }}.CHL_APP_STATUS_TRACKER_ID_R,
		{{ ref('Transformer_216') }}.APP_FOUND_FLAG_R,
		{{ ref('Transformer_216') }}.CCL_APP_FOUND_FLAG_R,
		{{ ref('Transformer_216') }}.CHL_APP_FOUND_FLAG_R,
		{{ ref('Transformer_216') }}.ORIG_ETL_D_R,
		{{ ref('Transformer_216') }}.CHL_TPB_HL_APP_ID_R,
		{{ ref('Transformer_216') }}.CHL_TPB_SUBTYPE_CODE_R,
		{{ ref('Transformer_216') }}.REL_MANAGER_STATE_ID_R,
		{{ ref('Transformer_216') }}.DATE_RECEIVED_R,
		{{ ref('Transformer_216') }}.CHL_APP_PCD_EXT_SYS_CAT_ID_R,
		{{ ref('Transformer_216') }}.CHL_TPB_FOUND_FLAG_R,
		{{ ref('XfmCheckNulls__OutCheckNullsSorted') }}.HLM_APP_TYPE_CAT_ID,
		{{ ref('XfmCheckNulls__OutCheckNullsSorted') }}.HLM_APP_PROD_ID,
		{{ ref('XfmCheckNulls__OutCheckNullsSorted') }}.HLM_APP_DISCHARGE_REASON_ID,
		{{ ref('XfmCheckNulls__OutCheckNullsSorted') }}.HLM_APP_CRIS_PRODUCT_ID,
		{{ ref('XfmCheckNulls__OutCheckNullsSorted') }}.HLM_APP_ACCOUNT_NUMBER,
		{{ ref('XfmCheckNulls__OutCheckNullsSorted') }}.HLM_APP_FOUND_FLAG,
		{{ ref('Transformer_216') }}.HLM_APP_TYPE_CAT_ID_R,
		{{ ref('Transformer_216') }}.HLM_APP_PROD_ID_R,
		{{ ref('Transformer_216') }}.HLM_APP_DISCHARGE_REASON_ID_R,
		{{ ref('Transformer_216') }}.HLM_APP_CRIS_PRODUCT_ID_R,
		{{ ref('Transformer_216') }}.HLM_APP_ACCOUNT_NUMBER_R,
		{{ ref('Transformer_216') }}.HLM_APP_FOUND_FLAG_R,
		{{ ref('XfmCheckNulls__OutCheckNullsSorted') }}.HL_BUSN_CHNL_CAT_I,
		{{ ref('Transformer_216') }}.HL_BUSN_CHNL_CAT_I_R,
		{{ ref('XfmCheckNulls__OutCheckNullsSorted') }}.CCC_APP_CC_APP_CAT_ID,
		{{ ref('XfmCheckNulls__OutCheckNullsSorted') }}.CCC_APP_FOUND_FLAG,
		{{ ref('Transformer_216') }}.CCC_APP_CC_APP_CAT_ID_R,
		{{ ref('Transformer_216') }}.CCC_APP_FOUND_FLAG_R
	FROM {{ ref('XfmCheckNulls__OutCheckNullsSorted') }}
	OUTER JOIN {{ ref('Transformer_216') }} ON {{ ref('XfmCheckNulls__OutCheckNullsSorted') }}.APP_ID = {{ ref('Transformer_216') }}.APP_ID
)

SELECT * FROM JoinSrcSortReject