{{ config(materialized='view', tags=['ExtAppCclAppChlApp']) }}

WITH XfmSeparateRejectWithoutSourceAndTheRest__InRejectWithoutSourceRec AS (
	SELECT
		-- *SRC*: \(20)If (Len(Trim(( IF IsNotNull((XfmSeparateRejects.APP_ID)) THEN (XfmSeparateRejects.APP_ID) ELSE ""))) = 0) Then 'R' Else 'S',
		IFF(LEN(TRIM(IFF({{ ref('JoinSrcSortReject') }}.APP_ID IS NOT NULL, {{ ref('JoinSrcSortReject') }}.APP_ID, ''))) = 0, 'R', 'S') AS DeltaFlag,
		{{ ref('JoinSrcSortReject') }}.APP_ID_R AS APP_ID,
		{{ ref('JoinSrcSortReject') }}.APP_APP_ID_R AS APP_APP_ID,
		{{ ref('JoinSrcSortReject') }}.APP_SUBTYPE_CODE_R AS APP_SUBTYPE_CODE,
		{{ ref('JoinSrcSortReject') }}.APP_APP_NO_R AS APP_APP_NO,
		{{ ref('JoinSrcSortReject') }}.APP_CREATED_DATE_R AS APP_CREATED_DATE,
		{{ ref('JoinSrcSortReject') }}.APP_CREATED_BY_STAFF_NUMBER_R AS APP_CREATED_BY_STAFF_NUMBER,
		{{ ref('JoinSrcSortReject') }}.APP_OWNED_BY_STAFF_NUMBER_R AS APP_OWNED_BY_STAFF_NUMBER,
		{{ ref('JoinSrcSortReject') }}.APP_CHANNEL_CAT_ID_R AS APP_CHANNEL_CAT_ID,
		{{ ref('JoinSrcSortReject') }}.APP_LODGEMENT_BRANCH_ID_R AS APP_LODGEMENT_BRANCH_ID,
		{{ ref('JoinSrcSortReject') }}.APP_SM_CASE_ID_R AS APP_SM_CASE_ID,
		{{ ref('JoinSrcSortReject') }}.CCL_APP_CCL_APP_ID_R AS CCL_APP_CCL_APP_ID,
		{{ ref('JoinSrcSortReject') }}.CCL_APP_CCL_APP_CAT_ID_R AS CCL_APP_CCL_APP_CAT_ID,
		{{ ref('JoinSrcSortReject') }}.CCL_APP_CCL_FORM_CAT_ID_R AS CCL_APP_CCL_FORM_CAT_ID,
		{{ ref('JoinSrcSortReject') }}.CCL_APP_TOT_PERSONAL_FAC_AMT_R AS CCL_APP_TOT_PERSONAL_FAC_AMT,
		{{ ref('JoinSrcSortReject') }}.CCL_APP_TOT_EQUIPFIN_FAC_AMT_R AS CCL_APP_TOT_EQUIPFIN_FAC_AMT,
		{{ ref('JoinSrcSortReject') }}.CCL_APP_TOT_COMMERCIAL_FAC_AMT_R AS CCL_APP_TOT_COMMERCIAL_FAC_AMT,
		{{ ref('JoinSrcSortReject') }}.CCL_APP_TOPUP_APP_ID_R AS CCL_APP_TOPUP_APP_ID,
		{{ ref('JoinSrcSortReject') }}.CCL_APP_AF_PRIMARY_INDUSTRY_ID_R AS CCL_APP_AF_PRIMARY_INDUSTRY_ID,
		{{ ref('JoinSrcSortReject') }}.CCL_APP_AD_TUC_AMT_R AS CCL_APP_AD_TUC_AMT,
		{{ ref('JoinSrcSortReject') }}.CCL_APP_COMMISSION_AMT_R AS CCL_APP_COMMISSION_AMT,
		{{ ref('JoinSrcSortReject') }}.CCL_APP_BROKER_REFERAL_FLAG_R AS CCL_APP_BROKER_REFERAL_FLAG,
		{{ ref('JoinSrcSortReject') }}.CHL_APP_HL_APP_ID_R AS CHL_APP_HL_APP_ID,
		{{ ref('JoinSrcSortReject') }}.CHL_APP_HL_PACKAGE_CAT_ID_R AS CHL_APP_HL_PACKAGE_CAT_ID,
		{{ ref('JoinSrcSortReject') }}.CHL_APP_LPC_OFFICE_R AS CHL_APP_LPC_OFFICE,
		{{ ref('JoinSrcSortReject') }}.CHL_APP_STATUS_TRACKER_ID_R AS CHL_APP_STATUS_TRACKER_ID,
		{{ ref('JoinSrcSortReject') }}.APP_FOUND_FLAG_R AS APP_FOUND_FLAG,
		{{ ref('JoinSrcSortReject') }}.CCL_APP_FOUND_FLAG_R AS CCL_APP_FOUND_FLAG,
		{{ ref('JoinSrcSortReject') }}.CHL_APP_FOUND_FLAG_R AS CHL_APP_FOUND_FLAG,
		{{ ref('JoinSrcSortReject') }}.CHL_TPB_HL_APP_ID_R AS CHL_TPB_HL_APP_ID,
		{{ ref('JoinSrcSortReject') }}.CHL_TPB_SUBTYPE_CODE_R AS CHL_TPB_SUBTYPE_CODE,
		{{ ref('JoinSrcSortReject') }}.REL_MANAGER_STATE_ID_R AS REL_MANAGER_STATE_ID,
		{{ ref('JoinSrcSortReject') }}.DATE_RECEIVED_R AS DATE_RECEIVED,
		{{ ref('JoinSrcSortReject') }}.CHL_APP_PCD_EXT_SYS_CAT_ID_R AS CHL_APP_PCD_EXT_SYS_CAT_ID,
		{{ ref('JoinSrcSortReject') }}.CHL_TPB_FOUND_FLAG_R AS CHL_TPB_FOUND_FLAG,
		{{ ref('JoinSrcSortReject') }}.ORIG_ETL_D_R AS ORIG_ETL_D,
		{{ ref('JoinSrcSortReject') }}.HLM_APP_TYPE_CAT_ID_R AS HLM_APP_TYPE_CAT_ID,
		{{ ref('JoinSrcSortReject') }}.HLM_APP_PROD_ID_R AS HLM_APP_PROD_ID,
		{{ ref('JoinSrcSortReject') }}.HLM_APP_DISCHARGE_REASON_ID_R AS HLM_APP_DISCHARGE_REASON_ID,
		{{ ref('JoinSrcSortReject') }}.HLM_APP_CRIS_PRODUCT_ID_R AS HLM_APP_CRIS_PRODUCT_ID,
		{{ ref('JoinSrcSortReject') }}.HLM_APP_ACCOUNT_NUMBER_R AS HLM_APP_ACCOUNT_NUMBER,
		{{ ref('JoinSrcSortReject') }}.HLM_APP_FOUND_FLAG_R AS HLM_APP_FOUND_FLAG,
		{{ ref('JoinSrcSortReject') }}.HL_BUSN_CHNL_CAT_I_R AS HL_BUSN_CHNL_CAT_I,
		{{ ref('JoinSrcSortReject') }}.CCC_APP_CC_APP_CAT_ID_R AS CCC_APP_CC_APP_CAT_ID,
		{{ ref('JoinSrcSortReject') }}.CCC_APP_FOUND_FLAG_R AS CCC_APP_FOUND_FLAG
	FROM {{ ref('JoinSrcSortReject') }}
	WHERE DeltaFlag = 'R'
)

SELECT * FROM XfmSeparateRejectWithoutSourceAndTheRest__InRejectWithoutSourceRec