{{ config(materialized='view', tags=['DltINT_GRUP_UNID_PATYFrmTMP_FA_PROP_CLNT']) }}

WITH CpyFAPropClnt AS (
	SELECT
		INT_GRUP_I,
		SRCE_SYST_PATY_I,
		UNID_PATY_M,
		PATY_TYPE_C,
		{{ ref('SrcTmpFAPropClnt') }}.OLD_INT_GRUP_I AS INT_GRUP_I,
		{{ ref('SrcTmpFAPropClnt') }}.OLD_SRCE_SYST_PATY_I AS SRCE_SYST_PATY_I,
		{{ ref('SrcTmpFAPropClnt') }}.OLD_UNID_PATY_M AS UNID_PATY_M,
		{{ ref('SrcTmpFAPropClnt') }}.OLD_PATY_TYPE_C AS PATY_TYPE_C,
		ORIG_SRCE_SYST_PATY_I,
		SRCE_SYST_C,
		CHNG_CODE,
		OLD_INT_GRUP_I,
		OLD_SRCE_SYST_PATY_I,
		OLD_ORIG_SRCE_SYST_PATY_I,
		OLD_UNID_PATY_M,
		OLD_PATY_TYPE_C,
		OLD_EFFT_D
	FROM {{ ref('SrcTmpFAPropClnt') }}
)

SELECT * FROM CpyFAPropClnt