{{ config(materialized='view', tags=['DltINT_GRUP_UNID_PATYFrmTMP_FA_PROP_CLNT']) }}

WITH 
tmp_fa_prop_clnt AS (
	SELECT
	*
	FROM {{ ref("tmp_fa_prop_clnt")  }}),
int_grup_unid_paty AS (
	SELECT
	*
	FROM {{ ref("int_grup_unid_paty")  }}),
SrcTmpFAPropClnt AS (SELECT a.INT_GRUP_I, a.SRCE_SYST_PATY_I, a.ORIG_SRCE_SYST_PATY_I, a.UNID_PATY_M, a.PATY_TYPE_C, a.SRCE_SYST_C, a.CHNG_CODE, b.INT_GRUP_I AS OLD_INT_GRUP_I, b.SRCE_SYST_PATY_I AS OLD_SRCE_SYST_PATY_I, b.ORIG_SRCE_SYST_PATY_I AS OLD_ORIG_SRCE_SYST_PATY_I, b.UNID_PATY_M AS OLD_UNID_PATY_M, b.PATY_TYPE_C AS OLD_PATY_TYPE_C, b.EFFT_D AS OLD_EFFT_D FROM TMP_FA_PROP_CLNT LEFT OUTER JOIN INT_GRUP_UNID_PATY ON TRIM(a.INT_GRUP_I) = TRIM(b.INT_GRUP_I) AND TRIM(a.SRCE_SYST_PATY_I) = TRIM(b.SRCE_SYST_PATY_I) AND b.EXPY_D = '9999-12-31')


SELECT * FROM SrcTmpFAPropClnt