{{ config(materialized='view', tags=['XfmHL_APPFrmExt_NEW']) }}

WITH DeDup_CseApptGnrcDate AS (
	SELECT APPT_I, DATE_ROLE_C, EFFT_D, GNRC_ROLE_S, GNRC_ROLE_D, GNRC_ROLE_T, EXPY_D, PROS_KEY_EFFT_I, PROS_KEY_EXPY_I, EROR_SEQN_I, MODF_S, MODF_D, MODF_T, USER_I, CHNG_REAS_TYPE_C 
	FROM (
		SELECT APPT_I, DATE_ROLE_C, EFFT_D, GNRC_ROLE_S, GNRC_ROLE_D, GNRC_ROLE_T, EXPY_D, PROS_KEY_EFFT_I, PROS_KEY_EXPY_I, EROR_SEQN_I, MODF_S, MODF_D, MODF_T, USER_I, CHNG_REAS_TYPE_C,
		 ROW_NUMBER() OVER (PARTITION BY APPT_I ORDER BY 1 ASC) AS ROW_NUM 
		FROM {{ ref('XfmBusinessRules__OutTmpCseApptGnrcDate') }}
	) AS DeDup_CseApptGnrcDate_TEMP
	WHERE ROW_NUM = 1
)

SELECT * FROM DeDup_CseApptGnrcDate