{{ config(materialized='view', tags=['DltPATY_INT_GRUPFrmTMP_FA_CLIENT_UNDERTAKING']) }}

WITH 
paty_int_grup AS (
	SELECT
	*
	FROM {{ ref("paty_int_grup")  }}),
tmp_fa_clnt_utak AS (
	SELECT
	*
	FROM {{ ref("tmp_fa_clnt_utak")  }}),
SrcTmpFAClientUndertakingTera AS (SELECT a.INT_GRUP_I, a.REL_I, a.SRCE_SYST_PATY_INT_GRUP_I, a.ORIG_SRCE_SYST_PATY_I, a.ORIG_SRCE_SYST_PATY_TYPE_C, a.PRIM_CLNT_F, a.PATY_I, a.SRCE_SYST_C, b.INT_GRUP_I AS OLD_INT_GRUP_I, b.REL_I AS OLD_REL_I, b.SRCE_SYST_PATY_INT_GRUP_I AS OLD_SRCE_SYST_PATY_INT_GRUP_I, b.ORIG_SRCE_SYST_PATY_I AS OLD_ORIG_SRCE_SYST_PATY_I, b.ORIG_SRCE_SYST_PATY_TYPE_C AS OLD_ORIG_SRCE_SYST_PATY_TYPE_C, b.PATY_I AS OLD_PATY_I, b.EFFT_D AS OLD_EFFT_D, b.PRIM_CLNT_F AS OLD_PRIM_CLNT_F, b.SRCE_SYST_C AS OLD_SRCE_SYST_C FROM TMP_FA_CLNT_UTAK LEFT OUTER JOIN PATY_INT_GRUP ON TRIM(a.INT_GRUP_I) = TRIM(b.INT_GRUP_I) AND TRIM(a.SRCE_SYST_PATY_INT_GRUP_I) = TRIM(b.SRCE_SYST_PATY_INT_GRUP_I) AND b.EXPY_D = '9999-12-31' WHERE a.PATY_INT_GRUP_F = 'Y')


SELECT * FROM SrcTmpFAClientUndertakingTera