{{ config(materialized='view', tags=['XfmChlBusPrtyAdrs']) }}

WITH dedup_aset AS (
	SELECT ASET_I, SECU_CODE_C, SECU_CATG_C, SRCE_SYST_ASET_I, SRCE_SYST_C, ASET_C, ORIG_SRCE_SYST_ASET_I, ORIG_SRCE_SYST_C, ENVT_F, ASET_X, ASET_LIBL_C, AL_CATG_C, DUPL_ASET_F, EFFT_D, EXPY_D, RUN_STRM 
	FROM (
		SELECT ASET_I, SECU_CODE_C, SECU_CATG_C, SRCE_SYST_ASET_I, SRCE_SYST_C, ASET_C, ORIG_SRCE_SYST_ASET_I, ORIG_SRCE_SYST_C, ENVT_F, ASET_X, ASET_LIBL_C, AL_CATG_C, DUPL_ASET_F, EFFT_D, EXPY_D, RUN_STRM,
		 ROW_NUMBER() OVER (PARTITION BY ASET_I ORDER BY 1 ASC) AS ROW_NUM 
		FROM {{ ref('XfmBusinessRules__OutAsetDS') }}
	) AS dedup_aset_TEMP
	WHERE ROW_NUM = 1
)

SELECT * FROM dedup_aset