{{ config(materialized='view', tags=['DltAPPTFrmTMP_APPT']) }}

WITH 
appt AS (
	SELECT
	*
	FROM {{ ref("appt")  }}),
tmp_appt AS (
	SELECT
	*
	FROM {{ ref("tmp_appt")  }}),
SrcTmpApptTera AS (SELECT a.APPT_I AS NEW_APPT_I, a.APPT_C AS NEW_APPT_C, a.APPT_FORM_C AS NEW_APPT_FORM_C, a.APPT_QLFY_C AS NEW_APPT_QLFY_C, a.STUS_TRAK_I AS NEW_STUS_TRAK_I, a.APPT_ORIG_C AS NEW_APPT_ORIG_C, a.APPT_N AS NEW_APPT_N, a.SRCE_SYST_C AS NEW_SRCE_SYST_C, a.SRCE_SYST_APPT_I AS NEW_SRCE_SYST_APPT_I, a.APPT_CRAT_D AS NEW_APPT_CRAT_D, a.RATE_SEEK_F AS NEW_RATE_SEEK_F, b.APPT_I AS OLD_APPT_I, b.APPT_C AS OLD_APPT_C, b.APPT_FORM_C AS OLD_APPT_FORM_C, b.STUS_TRAK_I AS OLD_STUS_TRAK_I, b.APPT_ORIG_C AS OLD_APPT_ORIG_C, b.RATE_SEEK_F AS OLD_RATE_SEEK_F FROM TMP_APPT LEFT OUTER JOIN APPT ON TRIM(a.APPT_I) = TRIM(b.APPT_I) WHERE a.RUN_STRM = '{{ var("RUN_STREAM") }}')


SELECT * FROM SrcTmpApptTera