.RUN FILE=%%BTEQ_LOGON_SCRIPT%%

.IF ERRORLEVEL <> 0 THEN .GOTO EXITERR

.SET QUIET OFF
.SET ECHOREQ ON
.SET FORMAT OFF
.SET WIDTH 120

------------------------------------------------------------------------------
-- Object Name             :  DERV_ACCT_PATY_99_DROP_WORK_TABL.sql
-- Object Type             :  BTEQ

--                           
-- Description             :  Drop work/staging tables that were used in this stream  
--                          
------------------------------------------------------------------------------
-- Modification History
-- Date               Author           Version     Version Description
-- 04/06/2013         Helen Zak        1.0         Initial Version
-- 08/08/2013         Helen Zak        1.1         C0714578  - post-implementation fixes
--                                                 drop new staging tables 
-- 21/08/2013         Helen Zak        1.2         C0726912 -post-implementation fix
--                                                 Remove redundant tables 
-- 02/09/2013         Helen Zak        1.3         C0737261-post-implementation fix
--                                                 Drop new staging tables 
-- 11/09/2013         Helen Zak        1.4         C0746488-post-implementation fix
--                                                 Drop new staging tables 
-- 27/03/2025		  Sourabh Kath	   1.5		   Drop 2 new staging tables created for
--												   Preferred Party Changes
------------------------------------------------------------------------------

-- Drop all work tables if we are in PROD

SEL 1 FROM 
(SEL CASE WHEN '%%ENV_C%%' = 'PROD' THEN 1 ELSE 0 END AS ENV) T1 
WHERE T1.ENV = 1;

.IF ERRORCODE <> 0 THEN .GOTO EXITERR

-- if no row returned - we are in DEV. Do not drop the tables. 
-- Complete the process successfully.

.IF ACTIVITYCOUNT = 0 THEN .GOTO EXITOK

DROP TABLE %%DDSTG%%.ACCT_PATY_REL_THA;

.IF ERRORCODE = 3807 THEN .GOTO NEXT1
.IF ERRORCODE = 0    THEN .GOTO NEXT1
.QUIT ERRORCODE

.LABEL NEXT1

DROP TABLE %%DDSTG%%.ACCT_PATY_THA_NEW_RNGE;

.IF ERRORCODE = 3807 THEN .GOTO NEXT2
.IF ERRORCODE = 0    THEN .GOTO NEXT2
.QUIT ERRORCODE

.LABEL NEXT2



DROP TABLE %%DDSTG%%.DERV_ACCT_PATY_CURR;

.IF ERRORCODE = 3807 THEN .GOTO NEXT3
.IF ERRORCODE = 0    THEN .GOTO NEXT3
.QUIT ERRORCODE

.LABEL NEXT3

DROP TABLE %%DDSTG%%.DERV_PRTF_ACCT_STAG;
.IF ERRORCODE = 3807 THEN .GOTO NEXT4
.IF ERRORCODE = 0    THEN .GOTO NEXT4
.QUIT ERRORCODE

.LABEL NEXT4

DROP TABLE %%DDSTG%%.DERV_PRTF_PATY_STAG;
.IF ERRORCODE = 3807 THEN .GOTO NEXT5
.IF ERRORCODE = 0    THEN .GOTO NEXT5
.QUIT ERRORCODE

.LABEL NEXT5

DROP TABLE %%DDSTG%%.DERV_PRTF_ACCT_PATY_STAG;
.IF ERRORCODE = 3807 THEN .GOTO NEXT6
.IF ERRORCODE = 0    THEN .GOTO NEXT6
.QUIT ERRORCODE

.LABEL NEXT6


DROP  TABLE %%DDSTG%%.DERV_ACCT_PATY_RM;
.IF ERRORCODE = 3807 THEN .GOTO NEXT7
.IF ERRORCODE = 0    THEN .GOTO NEXT7
.QUIT ERRORCODE

.LABEL NEXT7



DROP TABLE %%DDSTG%%.DERV_ACCT_PATY_ADD;
.IF ERRORCODE = 3807 THEN .GOTO NEXT8
.IF ERRORCODE = 0    THEN .GOTO NEXT8
.QUIT ERRORCODE

.LABEL NEXT8

DROP TABLE %%DDSTG%%.DERV_ACCT_PATY_CHG;
.IF ERRORCODE = 3807 THEN .GOTO NEXT9
.IF ERRORCODE = 0    THEN .GOTO NEXT9
.QUIT ERRORCODE

.LABEL NEXT9

DROP TABLE %%DDSTG%%.DERV_ACCT_PATY_FLAG;
.IF ERRORCODE = 3807 THEN .GOTO NEXT10
.IF ERRORCODE = 0    THEN .GOTO NEXT10
.QUIT ERRORCODE

.LABEL NEXT10


DROP TABLE %%DDSTG%%.ACCT_PATY_REL_WSS;
.IF ERRORCODE = 3807 THEN .GOTO NEXT11
.IF ERRORCODE = 0    THEN .GOTO NEXT11
.QUIT ERRORCODE

.LABEL NEXT11


DROP TABLE %%DDSTG%%.ACCT_REL_WSS_DITPS;
.IF ERRORCODE = 3807 THEN .GOTO NEXT12
.IF ERRORCODE = 0    THEN .GOTO NEXT12
.QUIT ERRORCODE

.LABEL NEXT12




DROP TABLE %%DDSTG%%.GRD_GNRC_MAP_DERV_PATY_HOLD;
.IF ERRORCODE = 3807 THEN .GOTO NEXT13
.IF ERRORCODE = 0    THEN .GOTO NEXT13
.QUIT ERRORCODE

.LABEL NEXT13

DROP TABLE %%DDSTG%%.GRD_GNRC_MAP_DERV_UNID_PATY;
.IF ERRORCODE = 3807 THEN .GOTO NEXT14
.IF ERRORCODE = 0    THEN .GOTO NEXT14
.QUIT ERRORCODE

.LABEL NEXT14

DROP TABLE %%DDSTG%%.GRD_GNRC_MAP_DERV_PATY_REL;
.IF ERRORCODE = 3807 THEN .GOTO NEXT15
.IF ERRORCODE = 0    THEN .GOTO NEXT15
.QUIT ERRORCODE

.LABEL NEXT15

DROP TABLE %%DDSTG%%.DERV_ACCT_PATY_DEL;
.IF ERRORCODE = 3807 THEN .GOTO NEXT16
.IF ERRORCODE = 0    THEN .GOTO NEXT16
.QUIT ERRORCODE

.LABEL NEXT16


DROP TABLE %%DDSTG%%.ACCT_PATY_DEDUP;

.IF ERRORCODE = 3807 THEN .GOTO NEXT17
.IF ERRORCODE = 0    THEN .GOTO NEXT17
.QUIT ERRORCODE

.LABEL NEXT17

DROP TABLE %%DDSTG%%.DERV_PRTF_ACCT_PATY_PSST;

.IF ERRORCODE = 3807 THEN .GOTO NEXT18
.IF ERRORCODE = 0    THEN .GOTO NEXT18
.QUIT ERRORCODE

.LABEL NEXT18

DROP  TABLE %%DDSTG%%.DERV_ACCT_PATY_NON_RM;
.IF ERRORCODE = 3807 THEN .GOTO NEXT19
.IF ERRORCODE = 0    THEN .GOTO NEXT19
.QUIT ERRORCODE

.LABEL NEXT19

DROP  TABLE %%DDSTG%%.DERV_ACCT_PATY_ROW_SECU_FIX;
.IF ERRORCODE = 3807 THEN .GOTO NEXT20
.IF ERRORCODE = 0    THEN .GOTO NEXT20
.QUIT ERRORCODE

.LABEL NEXT20


DROP  TABLE %%DDSTG%%.GRD_GNRC_MAP_PATY_HOLD_PRTY;
.IF ERRORCODE = 3807 THEN .GOTO NEXT21
.IF ERRORCODE = 0    THEN .GOTO NEXT21
.QUIT ERRORCODE

.LABEL NEXT21


DROP  TABLE %%DDSTG%%.GRD_GNRC_MAP_BUSN_SEGM_PRTY;
.IF ERRORCODE = 3807 THEN .GOTO NEXT22
.IF ERRORCODE = 0    THEN .GOTO NEXT22
.QUIT ERRORCODE

.LABEL NEXT22

.LABEL EXITOK
.QUIT 0

-- $LastChangedBy: zakhe $
-- $LastChangedDate: 2013-09-11 15:36:32 +1000 (Wed, 11 Sep 2013) $
-- $LastChangedRevision: 12624 $

.LABEL EXITERR
.QUIT 4
