{{ config(materialized='view', tags=['MergeTMP_DELETED']) }}

WITH fnlDeleted AS (
	SELECT
		TGT_TBL_NAME as TGT_TBL_NAME,
		SRC_TBL_NAME as SRC_TBL_NAME,
		DLTD_TABL_NAME as DLTD_TABL_NAME,
		DLTD_KEY1 as DLTD_KEY1,
		DLTD_KEY1_VALU as DLTD_KEY1_VALU,
		DLTD_KEY2 as DLTD_KEY2,
		DLTD_KEY2_VALU as DLTD_KEY2_VALU,
		DLTD_KEY3 as DLTD_KEY3,
		DLTD_KEY3_VALU as DLTD_KEY3_VALU,
		DLTD_KEY4 as DLTD_KEY4,
		DLTD_KEY4_VALU as DLTD_KEY4_VALU,
		DLTD_KEY5 as DLTD_KEY5,
		DLTD_KEY5_VALU as DLTD_KEY5_VALU
	FROM {{ ref('AddCol1') }}
	UNION ALL
	SELECT
		TGT_TBL_NAME,
		SRC_TBL_NAME,
		DLTD_TABL_NAME,
		DLTD_KEY1,
		DLTD_KEY1_VALU,
		DLTD_KEY2,
		DLTD_KEY2_VALU,
		DLTD_KEY3,
		DLTD_KEY3_VALU,
		DLTD_KEY4,
		DLTD_KEY4_VALU,
		DLTD_KEY5,
		DLTD_KEY5_VALU
	FROM {{ ref('AddCol2') }}
	UNION ALL
	SELECT
		TGT_TBL_NAME,
		SRC_TBL_NAME,
		DLTD_TABL_NAME,
		DLTD_KEY1,
		DLTD_KEY1_VALU,
		DLTD_KEY2,
		DLTD_KEY2_VALU,
		DLTD_KEY3,
		DLTD_KEY3_VALU,
		DLTD_KEY4,
		DLTD_KEY4_VALU,
		DLTD_KEY5,
		DLTD_KEY5_VALU
	FROM {{ ref('AddCol3') }}
	UNION ALL
	SELECT
		TGT_TBL_NAME,
		SRC_TBL_NAME,
		DLTD_TABL_NAME,
		DLTD_KEY1,
		DLTD_KEY1_VALU,
		DLTD_KEY2,
		DLTD_KEY2_VALU,
		DLTD_KEY3,
		DLTD_KEY3_VALU,
		DLTD_KEY4,
		DLTD_KEY4_VALU,
		DLTD_KEY5,
		DLTD_KEY5_VALU
	FROM {{ ref('AddCol4') }}
	UNION ALL
	SELECT
		TGT_TBL_NAME,
		SRC_TBL_NAME,
		DLTD_TABL_NAME,
		DLTD_KEY1,
		DLTD_KEY1_VALU,
		DLTD_KEY2,
		DLTD_KEY2_VALU,
		DLTD_KEY3,
		DLTD_KEY3_VALU,
		DLTD_KEY4,
		DLTD_KEY4_VALU,
		DLTD_KEY5,
		DLTD_KEY5_VALU
	FROM {{ ref('AddCol5') }}
	UNION ALL
	SELECT
		TGT_TBL_NAME,
		SRC_TBL_NAME,
		DLTD_TABL_NAME,
		DLTD_KEY1,
		DLTD_KEY1_VALU,
		DLTD_KEY2,
		DLTD_KEY2_VALU,
		DLTD_KEY3,
		DLTD_KEY3_VALU,
		DLTD_KEY4,
		DLTD_KEY4_VALU,
		DLTD_KEY5,
		DLTD_KEY5_VALU
	FROM {{ ref('AddCol6') }}
	UNION ALL
	SELECT
		TGT_TBL_NAME,
		SRC_TBL_NAME,
		DLTD_TABL_NAME,
		DLTD_KEY1,
		DLTD_KEY1_VALU,
		DLTD_KEY2,
		DLTD_KEY2_VALU,
		DLTD_KEY3,
		DLTD_KEY3_VALU,
		DLTD_KEY4,
		DLTD_KEY4_VALU,
		DLTD_KEY5,
		DLTD_KEY5_VALU
	FROM {{ ref('AddCol7') }}
	UNION ALL
	SELECT
		TGT_TBL_NAME,
		SRC_TBL_NAME,
		DLTD_TABL_NAME,
		DLTD_KEY1,
		DLTD_KEY1_VALU,
		DLTD_KEY2,
		DLTD_KEY2_VALU,
		DLTD_KEY3,
		DLTD_KEY3_VALU,
		DLTD_KEY4,
		DLTD_KEY4_VALU,
		DLTD_KEY5,
		DLTD_KEY5_VALU
	FROM {{ ref('AddCol8') }}
	UNION ALL
	SELECT
		TGT_TBL_NAME,
		SRC_TBL_NAME,
		DLTD_TABL_NAME,
		DLTD_KEY1,
		DLTD_KEY1_VALU,
		DLTD_KEY2,
		DLTD_KEY2_VALU,
		DLTD_KEY3,
		DLTD_KEY3_VALU,
		DLTD_KEY4,
		DLTD_KEY4_VALU,
		DLTD_KEY5,
		DLTD_KEY5_VALU
	FROM {{ ref('AddCol9') }}
	UNION ALL
	SELECT
		TGT_TBL_NAME,
		SRC_TBL_NAME,
		DLTD_TABL_NAME,
		DLTD_KEY1,
		DLTD_KEY1_VALU,
		DLTD_KEY2,
		DLTD_KEY2_VALU,
		DLTD_KEY3,
		DLTD_KEY3_VALU,
		DLTD_KEY4,
		DLTD_KEY4_VALU,
		DLTD_KEY5,
		DLTD_KEY5_VALU
	FROM {{ ref('AddCol10') }}
)

SELECT * FROM fnlDeleted