{{ config(materialized='view', tags=['DltAppt_Pdct_PurpfrmTMP_tran']) }}

WITH 
tmp_appt_pdct_purp AS (
	SELECT
	*
	FROM {{ ref("tmp_appt_pdct_purp")  }}),
appt_pdct_purp AS (
	SELECT
	*
	FROM {{ ref("appt_pdct_purp")  }}),
SrcTmpApptPdctPurpTera AS (SELECT a.APPT_PDCT_I AS NEW_APPT_PDCT_I, a.SRCE_SYST_APPT_PDCT_PURP_I AS NEW_SRCE_SYST_APPT_PDCT_PURP_I, a.PURP_TYPE_C AS NEW_PURP_TYPE_C, a.PURP_CLAS_C AS NEW_PURP_CLAS_C, a.SRCE_SYST_C AS NEW_SRCE_SYST_C, a.PURP_A AS NEW_PURP_A, a.CNCY_C AS NEW_CNCY_C, a.MAIN_PURP_F AS NEW_MAIN_PURP_F, b.APPT_PDCT_I AS OLD_APPT_PDCT_I, b.SRCE_SYST_APPT_PDCT_PURP_I AS OLD_SRCE_SYST_APPT_PDCT_PURP_I, b.PURP_TYPE_C AS OLD_PURP_TYPE_C, b.PURP_CLAS_C AS OLD_PURP_CLAS_C, b.SRCE_SYST_C AS OLD_SRCE_SYST_C, b.PURP_A AS OLD_PURP_A, b.CNCY_C AS OLD_CNCY_C, b.MAIN_PURP_F AS OLD_MAIN_PURP_F, b.EFFT_D AS OLD_EFFT_D FROM TMP_APPT_PDCT_PURP LEFT OUTER JOIN APPT_PDCT_PURP ON TRIM(a.APPT_PDCT_I) = TRIM(b.APPT_PDCT_I) AND b.EXPY_D = '9999-12-31' AND b.SRCE_SYST_C = 'CSE' WHERE a.RUN_STRM = '{{ var("RUN_STREAM") }}')


SELECT * FROM SrcTmpApptPdctPurpTera