{{ config(materialized='view', tags=['DltApptGnrcDateCCL']) }}

WITH RemDup AS (
	SELECT APPT_I, DATE_ROLE_C, EFFT_D, GNRC_ROLE_S, GNRC_ROLE_D, GNRC_ROLE_T, EXPY_D, PROS_KEY_EFFT_I, PROS_KEY_EXPY_I, EROR_SEQN_I, MODF_S, MODF_D, MODF_T, USER_I, CHNG_REAS_TYPE_C 
	FROM (
		SELECT APPT_I, DATE_ROLE_C, EFFT_D, GNRC_ROLE_S, GNRC_ROLE_D, GNRC_ROLE_T, EXPY_D, PROS_KEY_EFFT_I, PROS_KEY_EXPY_I, EROR_SEQN_I, MODF_S, MODF_D, MODF_T, USER_I, CHNG_REAS_TYPE_C,
		 ROW_NUMBER() OVER (PARTITION BY APPT_I, DATE_ROLE_C, EFFT_D, GNRC_ROLE_D, GNRC_ROLE_S, GNRC_ROLE_T, PROS_KEY_EFFT_I, EROR_SEQN_I, MODF_S, MODF_D, MODF_T, USER_I, CHNG_REAS_TYPE_C, EXPY_D, PROS_KEY_EXPY_I ORDER BY 1 ASC) AS ROW_NUM 
		FROM {{ ref('DetermineChange__ToRemDup') }}
	) AS RemDup_TEMP
	WHERE ROW_NUM = 1
)

SELECT * FROM RemDup