{{ config(materialized='view', tags=['LdREJT_XS_APP_ANS']) }}

SELECT
	APP_ID
	QA_QUESTION_ID
	QA_ANSWER_ID
	TEXT_ANSWER
	CIF_CODE
	CBA_STAFF_NUMBER
	LODGEMENT_BRANCH_ID
	SBTY_CODE
	ETL_D
	ORIG_ETL_D
	EROR_C 
FROM {{ ref('ModConversions') }}