
create iceberg table NPD_D12_DMN_GDWMIG_IBRG.PDSRCCS.PLAN_BALN_SEGM_MSTR_NPW (
	CORP_IDNN STRING NOT NULL COMMENT 'Corporation Identification',
	ACCT_I STRING NOT NULL COMMENT 'Account Identifier',
	PLAN_IDNN STRING NOT NULL COMMENT 'Plan Identification',
	PLAN_SQNO DECIMAL(3,0) COMMENT 'Plan Sequence Number',
	SRCE_SYST_ACCT_NUMB STRING COMMENT 'Source System Account Number',
	STOR_IDNN STRING COMMENT 'Store Identification',
	ORIG_STAT STRING COMMENT 'Original State',
	PLAN_TYPE STRING COMMENT 'Plan Type',
	PLAN_CATG STRING COMMENT 'Plan Category',
	POST_PUR_STUS STRING COMMENT 'Post Purchase Status',
	TERM_STUS STRING COMMENT 'Terms Status',
	INT_DEFR_STUS STRING COMMENT 'Interest Defer Status',
	PAYT_DEFR_STUS STRING COMMENT 'Payment Defer Status',
	TIME_BILL DECIMAL(3,0) COMMENT 'Times Billed',
	SPEC_TERM_CYCL DECIMAL(3,0) COMMENT 'Special Terms Cycle',
	INT_DEFR_CYCL DECIMAL(3,0) COMMENT 'Interest Defer Cycle',
	PAYT_DEFR_CYCL DECIMAL(3,0) COMMENT 'Payment Defer Cycle',
	DATE_SPEC_TERM_END DATE COMMENT 'Date Special Terms End',
	DATE_INT_DEFR_END DATE COMMENT 'Date Interest Defer End',
	DATE_PAYT_DEFR_END DATE COMMENT 'Date Payment Defer End',
	DATE_FRST_TRAN DATE COMMENT 'Date First Transaction',
	DATE_PAID_OFF DATE COMMENT 'Date Paid Off',
	DATE_LAST_PAYT DATE COMMENT 'Date Last Payment',
	DATE_LAST_MNTN DATE COMMENT 'Date Last Maintenance',
	LFTD_HIGH_BALN DECIMAL(13,2) COMMENT 'Life To Date High Balance',
	PAYT_TABL_HIGH_BALN DECIMAL(13,2) COMMENT 'Payment Table High Balance',
	LFTD_ICHG DECIMAL(13,2) COMMENT 'Life to Date Interest Charged',
	LFTD_INT_WAVR DECIMAL(13,2) COMMENT 'Life to Date Interest Waived',
	FIX_PAYT_AMT DECIMAL(13,2) COMMENT 'Fixed Payment Amount',
	FIX_PACY DECIMAL(3,0) COMMENT 'Fixed Payment Cycle',
	LAST_IRTE DECIMAL(7,2) COMMENT 'Last Interest Rate',
	LAST_RATE_CODE STRING COMMENT 'Last Rate Code',
	LAST_RATE_CODE_SEQN DECIMAL(4,0) COMMENT 'Last Rate Code Sequence',
	LAST_MIN_PAYT_CODE STRING COMMENT 'Last Minimum Payment Code',
	LAST_MIN_PAYT_CODE_SEQN DECIMAL(4,0) COMMENT 'Last Minimum Payment Code Sequence',
	LAST_MIN_PAYT_AMT DECIMAL(13,2) COMMENT 'Last Minimum Payment Amount',
	CURR_MIN_PAYT_DUE DECIMAL(13,2) COMMENT 'Current Minimum Payment Due',
	MIN_PAYT_PAST_DUE DECIMAL(13,2) COMMENT 'Minimum Payment Past Due',
	LAST_APPY_PAYT_AMT DECIMAL(13,2) COMMENT 'Last Applied Payment Amount',
	PAYT_BFOR_GRCE DECIMAL(13,2) COMMENT 'Payments Before Grace',
	ORIG_BALN DECIMAL(13,2) COMMENT 'Original Balance',
	INT_SAVE_RATE DECIMAL(2,2) COMMENT 'Interest Saver Rate',
	PLAN_DUE_DATE DATE COMMENT 'Plan Due Date',
	INT_FEE_END_DATE DATE COMMENT 'Interest Fee End Date',
	INT_FREE_BALN DECIMAL(13,2) COMMENT 'Interest Free Balance',
	OPEN_BALN_CURR_CYCL DECIMAL(13,2) COMMENT 'Opening Balance Current Cycle',
	CTD_SALE_TRAN DECIMAL(13,2) COMMENT 'Cycle To Date Sales Transactions',
	CTD_DR_TRAN DECIMAL(13,2) COMMENT 'Cycle To Date Debit Transactions',
	CTD_CR_TRAN DECIMAL(13,2) COMMENT 'Cycle To Date Credit Transactions',
	CTD_PAYT_TRAN DECIMAL(13,2) COMMENT 'Cycle To Date Payment Transactions',
	INT_UNPD_OPEN_NOT_ACRL_BALN DECIMAL(13,2) COMMENT 'Interest Unpaid Opening Not Accrued Balance',
	INT_UNPD_CTD_NOT_ACRL_BALN DECIMAL(13,2) COMMENT 'Interest Unpaid Cycle To Date Not Accrued Balance',
	INT_UNPD_CURR_CYCL_BALN DECIMAL(13,2) COMMENT 'Interest Unpaid Current Cycle Balance',
	INT_UNPD_1_CYCL_AGO_BALN DECIMAL(13,2) COMMENT 'Interest Unpaid 1 Cycle AGO Balance',
	INT_UNPD_2_CYCL_AGO_BALN DECIMAL(13,2) COMMENT 'Interest Unpaid 2 Cycle AGO Balance',
	FEE_UNPD_OPEN_NOT_ACRL_BALN DECIMAL(13,2) COMMENT 'Fees Unpaid Opening Not Accrued Balance',
	FEE_UNPD_CTD_NOT_ACRL_BALN DECIMAL(13,2) COMMENT 'Fees Unpaid Cycle To Date Not Accrued Balance',
	FEE_UNPD_CURR_CYCL_BALN DECIMAL(13,2) COMMENT 'Fees Unpaid Current Cycle Balance',
	FEE_UNPD_1_CYCL_AGO_BALN DECIMAL(13,2) COMMENT 'Fees Unpaid 1 Cycle AGO Balance',
	FEE_UNPD_2_CYCL_AGO_BALN DECIMAL(13,2) COMMENT 'Fees Unpaid 2 Cycle AGO Balance',
	AMF_UNPD_OPEN_NOT_ACRL_BALN DECIMAL(13,2) COMMENT 'Annual Membership Fee Unpaid Opening Not Accrued Balance',
	AMF_UNPD_CTD_NOT_ACRL_BALN DECIMAL(13,2) COMMENT 'Annual Membership Fee Unpaid Cycle To Date Not Accrued Balan',
	AMF_UNPD_CURR_CYCL_BALN DECIMAL(13,2) COMMENT 'Annual Membership Fee Unpaid Current Cycle Balance',
	AMF_UNPD_1_CYCL_AGO_BALN DECIMAL(13,2) COMMENT 'Annual Membership Fee Unpaid 1 Cycle AGO Balance',
	AMF_UNPD_2_CYCL_AGO_BALN DECIMAL(13,2) COMMENT 'Annual Membership Fee Unpaid 2 Cycle AGO Balance',
	INSR_UNPD_OPEN_NOT_ACRL_BALN DECIMAL(13,2) COMMENT 'Insurance Unpaid Opening Not Accrued Balance',
	INSR_UNPD_CTD_NOT_ACRL_BALN DECIMAL(13,2) COMMENT 'Insurance Unpaid Cycle To Date Not Accrued Balance',
	INSR_UNPD_CURR_CYCL_BALN DECIMAL(13,2) COMMENT 'Insurance Unpaid Current Cycle Balance',
	INSR_UNPD_1_CYCL_AGO_BALN DECIMAL(13,2) COMMENT 'Insurance Unpaid 1 Cycle AGO Balance',
	INSR_UNPD_2_CYCL_AGO_BALN DECIMAL(13,2) COMMENT 'Insurance Unpaid 2 Cycle AGO Balance',
	PRIN_UNPD_OPEN_NOT_ACRL_BALN DECIMAL(13,2) COMMENT 'Principal Unpaid Opening Not Accrued Balance',
	PRIN_UNPD_CTD_NOT_ACRL_BALN DECIMAL(13,2) COMMENT 'Principal Unpaid Cycle To Date Not Accrued Balance',
	PRIN_UNPD_CURR_CYCL_BALN DECIMAL(13,2) COMMENT 'Principal Unpaid Current Cycle Balance',
	PRIN_UNPD_1_CYCL_AGO_BALN DECIMAL(13,2) COMMENT 'Principal Unpaid 1 Cycle AGO Balance',
	PRIN_UNPD_2_CYCL_AGO_BALN DECIMAL(13,2) COMMENT 'Principal Unpaid 2 Cycle AGO Balance',
	AGGR_CURR_CYCL_BALN DECIMAL(15,2) COMMENT 'Aggregate Current Cycle Balance',
	AGGR_1_CYCL_AGO_BALN DECIMAL(15,2) COMMENT 'Aggregate 1 Cycle AGO Balance',
	AGGR_2_CYCL_AGO_BALN DECIMAL(15,2) COMMENT 'Aggregate 2 Cycle AGO Balance',
	AGGR_DLAY_BALN DECIMAL(15,2) COMMENT 'Aggregate Delay Balance',
	DLAY_DAY_QNTY DECIMAL(3,0) COMMENT 'Delayed Day Quantity',
	CTD_CSAD_FEE_AMT DECIMAL(13,2) COMMENT 'Cycle To Date Cash Advance Fee Amount',
	CTD_SYST_GENR_CSAD_FEE_AMT DECIMAL(13,2) COMMENT 'Cycle To Date System Generated Cash Advance Fee Amount',
	INT_DEFR_DAY_QNTY DECIMAL(3,0) COMMENT 'Interest Deferred Days Quantity',
	INT_DEFR_AMT DECIMAL(13,2) COMMENT 'Interest Deferred Amount',
	INT_DEFR_AGGR_CURR_BALN DECIMAL(15,2) COMMENT 'Interest Deferred Aggregate Current Balance',
	USER_CODE STRING COMMENT 'User Code',
	MIGR_TO_PLAN_IDNN STRING COMMENT 'Migrate To Plan Identification',
	MIGR_TO_PLAN_SQNO DECIMAL(3,0) COMMENT 'Migrate To Plan Sequence Number',
	DATE_MIGR DATE COMMENT 'Date Migrate',
	DSPT_AMT DECIMAL(13,2) COMMENT 'Disputed Amount',
	EXCL_DSPT_AMT DECIMAL(13,2) COMMENT 'Excluded Disputed Amount',
	ACRL_DSPT_AMT DECIMAL(13,2) COMMENT 'Accrued Disputed Amount',
	FRNT_LOAD_ISMT_BILL DECIMAL(3,0) COMMENT 'Front Load Install Billed',
	FRNT_LOAD_LAST_ISMT_DATE DATE COMMENT 'Front Load Last Install Date',
	FRNT_LOAD_ORIG_INT_AMT DECIMAL(13,2) COMMENT 'Front Load Original Interest Amount',
	FRNT_LOAD_EARN_INT_AMT DECIMAL(13,2) COMMENT 'Front Load Earned Interest Amount',
	FRNT_LOAD_REBT_INT_AMT DECIMAL(13,2) COMMENT 'Front Load Rebate Interest Amount',
	FRNT_LOAD_IRTE DECIMAL(6,6) COMMENT 'Front Load Interest Rate',
	FRNT_LOAD_ORIG_INSR_AMT DECIMAL(13,2) COMMENT 'Front Load Original Insurance Amount',
	FRNT_LOAD_EARN_INSR_AMT DECIMAL(13,2) COMMENT 'Front Load Earned Insurance Amount',
	FRNT_LOAD_UPFR_INSR_AMT DECIMAL(13,2) COMMENT 'Front Load Up Front Insurance Amount',
	FRNT_LOAD_REBT_INSR_AMT DECIMAL(13,2) COMMENT 'Front Load Rebate Insurance Amount',
	SCHE_PAYF_DATE DATE COMMENT 'Scheduled Payoff Date',
	SCHE_PAYF_AMT DECIMAL(13,2) COMMENT 'Scheduled Payoff Amount',
	SCHE_PAYF_FEE DECIMAL(13,2) COMMENT 'Scheduled Payoff Fee',
	SCHE_PAYF_REAS STRING COMMENT 'Scheduled Payoff Reason',
	ACTL_PAYF_DATE DATE COMMENT 'Actual Payoff Date',
	ACTL_PAYF_AMT DECIMAL(13,2) COMMENT 'Actual Payoff Amount',
	FRNT_LOAD_INSR_PAID DECIMAL(13,2) COMMENT 'Front Load Insurance Paid',
	FRNT_LOAD_REBT_INSR_PAID DECIMAL(13,2) COMMENT 'Front Load Rebate Insurance Paid',
	GOVT_CHRG_NOT_ACRL_OPEN_AMT DECIMAL(13,2) COMMENT 'Government Charges Unpaid Non Accruing Open Amount',
	GOVT_CHRG_NOT_ACRL_CTD_AMT DECIMAL(13,2) COMMENT 'Government Charges Non-Accruing Cycle-To-Date Amount',
	GOVT_CHRG_CURR_CYCL_AMT DECIMAL(13,2) COMMENT 'Government Charges Current Cycle Amount',
	GOVT_CHRG_1_CYCL_AGO_AMT DECIMAL(13,2) COMMENT 'Government Charges 1 Cycle Ago Amount',
	GOVT_CHRG_2_CYCL_AGO_AMT DECIMAL(13,2) COMMENT 'Government Charges 2 Cycle Ago Amount',
	CTD_FNCL_CHRG_REV DECIMAL(7,2) COMMENT 'Cycle To Date Finance Charge Reversals',
	ISMT_QNTY DECIMAL(3,0) COMMENT 'Number Of Installments',
	ISMT_PREV_QNTY DECIMAL(3,0) COMMENT 'Previous Number Of Installments',
	DATE_ISMT_TERM_CHNG DATE COMMENT 'Date Instalment Term Changed',
	PREV_MIN_PAYT_AMT DECIMAL(13,2) COMMENT 'Previous Minimum Payment Amount',
	ORIG_LOAN_BALN DECIMAL(13,2) COMMENT 'Original Loan Balance',
	LFTD_ALL_CR DECIMAL(13,2) COMMENT 'Life To Date All Credits',
	LFTD_INT_SAVE DECIMAL(13,2) COMMENT 'Life To Date Interest Saved',
	PREV_CYCL_INT_SAVE DECIMAL(13,2) COMMENT 'Previous Cycle Interest Saved',
	DATE_LOAN_PAID_OUT DATE COMMENT 'Date Loan Paid Out',
	PRJC_PAY_OFF_DATE DATE COMMENT 'Projected Pay-Off Date',
	DSPT_QNTY DECIMAL(3,0) COMMENT 'Disputed Quantity',
	DSPT_OLD_DATE DATE COMMENT 'Disputed Old Date',
	TERM DECIMAL(13,2) COMMENT 'Term',
	ROW_I NUMBER(38,0) COMMENT 'Row Identifier',
	EFFT_S TIMESTAMP_NTZ(6) NOT NULL COMMENT 'Effective Timestamp',
	-- FORMAT 'YYYY-MM-DDBHH:MI:SSDS(6)' - FORMAT IN TABLE PDSRCCS.PLAN_BALN_SEGM_MSTR NOT SUPPORTED EFFT_D DATE NOT NULL COMMENT 'Effective Date',
	EFFT_T TIME(6) COMMENT 'Effective Time',
	-- FORMAT 'HH:MI:SSDS(6)' - FORMAT IN TABLE PDSRCCS.PLAN_BALN_SEGM_MSTR NOT SUPPORTED PROS_KEY_EFFT_I NUMBER(38,0) NOT NULL COMMENT 'Process Key Effective Identifier',
	ROW_SECU_ACCS_C NUMBER(38,0) NOT NULL COMMENT 'Row Security Access Code'
)COMMENT='{ \"origin\": \"sf_sc\", \"name\": \"snowconvert\", \"version\": {  \"major\": 1,  \"minor\": 11,  \"patch\": \"0.0\" }, \"attributes\": {  \"component\": \"teradata\",  \"convertedOn\": \"07/11/2025\",  \"domain\": \"snowflake\" }}'
;