{{ config(materialized='view', tags=['XfmAppProdCclAppProdPlAppProdFrmExt']) }}

WITH LkpReferences AS (
	SELECT
		{{ ref('CpyRename') }}.APP_PROD_ID,
		{{ ref('CpyRename') }}.CLP_JOB_FAMILY_CAT_ID,
		{{ ref('Outmap_CSE_JOB_Comm_CatgLks') }}.JOB_COMM_CATG_C,
		{{ ref('CpyRename') }}.CCL_APP_PROD_ID,
		{{ ref('CpyRename') }}.CCL_PARENT_CCL_APP_PROD_ID,
		{{ ref('CpyRename') }}.CCL_ACCOUNT_NUMBER,
		{{ ref('CpyRename') }}.CCL_ACTUAL_RATE,
		{{ ref('CpyRename') }}.CCL_BALLOON_PAY_AMT,
		{{ ref('CpyRename') }}.CCL_BASIS_TYPE_CAT_ID,
		{{ ref('CpyRename') }}.CCL_INTEREST_RATE_MARGIN,
		{{ ref('CpyRename') }}.CCL_LOAN_TERM_MTH_NUM,
		{{ ref('CpyRename') }}.CCL_CURRENT_LIMIT,
		{{ ref('CpyRename') }}.CCL_INC_DEC_AMT,
		{{ ref('CpyRename') }}.CCL_POST_APP_AMT,
		{{ ref('CpyRename') }}.CCL_NEW_PROD_FLAG,
		{{ ref('CpyRename') }}.CCL_INDEX_RATE,
		{{ ref('CpyRename') }}.CCL_INTEREST_ADV_FLAG,
		{{ ref('CpyRename') }}.CCL_INTERESTONLY_TERM_MTH_NUM,
		{{ ref('CpyRename') }}.CCL_CAPPED_TERM_MTH_NUM,
		{{ ref('CpyRename') }}.CCL_CAPPED_RATE,
		{{ ref('CpyRename') }}.CCL_CRIS_PRODUCT_ID,
		{{ ref('CpyRename') }}.CCL_CCL_LOAN_PURPOSE_ID,
		{{ ref('CpyRename') }}.CCL_NEW_PROD_SUBTYPE_FLAG,
		{{ ref('CpyRename') }}.CCL_TEMP_EXCESS_MTHS,
		{{ ref('CpyRename') }}.CCL_LOAN_PURPOSE_CLASS_CODE,
		{{ ref('CpyRename') }}.CCL_CCL_INTEREST_RATE_CAT_ID,
		{{ ref('CpyRename') }}.CCL_CRR,
		{{ ref('CpyRename') }}.CCL_AD_TUC_INC_AMT,
		{{ ref('CpyRename') }}.CCL_CCL_RATE_TYPE_CAT_ID,
		{{ ref('CpyRename') }}.CCL_LINK_CCL_APP_ID,
		{{ ref('CpyRename') }}.CCL_LINK_CCL_APP_PROD_ID,
		{{ ref('CpyRename') }}.CCL_CHL_LMI_AMT,
		{{ ref('CpyRename') }}.CCL_USED_IN_EXPOSURE_VIEW_FLAG,
		{{ ref('CpyRename') }}.CCL_CCL_APP_BROKER_CIF_CODE,
		{{ ref('CpyRename') }}.CCL_APP_ID,
		{{ ref('CpyRename') }}.CCL_FIXED_INT_START_DATE,
		{{ ref('CpyRename') }}.CCL_CHILD_PDCT_LEVEL_CAT_ID,
		{{ ref('CpyRename') }}.CCL_PARENT_PDCT_LEVEL_CAT_ID,
		{{ ref('CpyRename') }}.CPL_APP_PROD_ID,
		{{ ref('CpyRename') }}.PL_TARG_CAT_ID,
		{{ ref('CpyRename') }}.CPL_REPAY_APPROX_AMT,
		{{ ref('CpyRename') }}.CPL_REPAY_FREQUENCY_ID,
		{{ ref('CpyRename') }}.CPL_PL_APP_PROD_REPAY_CAT_ID,
		{{ ref('CpyRename') }}.CPL_PL_PROD_TERM_CAT_ID,
		{{ ref('CpyRename') }}.PL_CMPN_CAT_ID,
		{{ ref('CpyRename') }}.CPL_AD_HOC_CAMPAIGN_DESC,
		{{ ref('CpyRename') }}.CPL_CAR_SEEKER_FLAG,
		{{ ref('CpyRename') }}.CPL_PL_PROD_TARGET_CAT_ID,
		{{ ref('CpyRename') }}.PL_MRKT_SRCE_CAT_ID,
		{{ ref('CpyRename') }}.CPL_HLS_ACCT_NO,
		{{ ref('CpyRename') }}.CPL_TOTAL_INTEREST_AMT,
		{{ ref('CpyRename') }}.CPL_APP_PROD_AMT,
		{{ ref('CpyRename') }}.CPL_TP_BROKER_ID,
		{{ ref('CpyRename') }}.CPL_TP_BROKER_FIRST_NAME,
		{{ ref('CpyRename') }}.CPL_TP_BROKER_LAST_NAME,
		{{ ref('CpyRename') }}.CPL_TP_BROKER_GROUP_CAT_ID,
		{{ ref('CpyRename') }}.COM_APP_PROD_ID,
		{{ ref('CpyRename') }}.SBTY_CODE,
		{{ ref('CpyRename') }}.COM_APP_ID,
		{{ ref('CpyRename') }}.COM_PRODUCT_TYPE_ID,
		{{ ref('CpyRename') }}.COM_SM_CASE_ID,
		{{ ref('CpyRename') }}.COM_FOUND_FLAG,
		{{ ref('CpyRename') }}.CPL_FOUND_FLAG,
		{{ ref('CpyRename') }}.CCL_FOUND_FLAG,
		{{ ref('CpyRename') }}.CLP_FOUND_FLAG,
		{{ ref('CpyRename') }}.CC_FOUND_FLAG,
		{{ ref('CpyRename') }}.CC_APP_PROD_ID,
		{{ ref('CpyRename') }}.CCHL_APP_PROD_ID,
		{{ ref('CpyRename') }}.ABN,
		{{ ref('CpyRename') }}.BUSINESS_NAME,
		{{ ref('CpyRename') }}.SIMPLE_APP_FLAG,
		{{ ref('CpyRename') }}.CHL_FOUND_FLAG,
		{{ ref('CpyRename') }}.ORIG_ETL_D,
		{{ ref('SrcMAP_CSE_APPT_QLFYLks') }}.APPT_QLFY_C,
		{{ ref('SrcMAP_CSE_LOAN_FNDD_METHLks') }}.LOAN_FNDD_METH_C,
		{{ ref('SrcMAP_CSE_APPT_ACQR_SRCELks') }}.ACQR_SRCE_C,
		{{ ref('SrcMAP_CSE_PL_ACQR_TYPELks') }}.ACQR_TYPE_C,
		{{ ref('CpyRename') }}.CHL_CR_DATE,
		{{ ref('CpyRename') }}.CHL_ASSESSMENT_DATE,
		{{ ref('CpyRename') }}.CHL_NCPR_FLAG
	FROM {{ ref('CpyRename') }}
	LEFT JOIN {{ ref('SrcMAP_CSE_APPT_QLFYLks') }} ON 
	LEFT JOIN {{ ref('SrcMAP_CSE_LOAN_FNDD_METHLks') }} ON 
	LEFT JOIN {{ ref('SrcMAP_CSE_APPT_ACQR_SRCELks') }} ON 
	LEFT JOIN {{ ref('SrcMAP_CSE_PL_ACQR_TYPELks') }} ON 
	LEFT JOIN {{ ref('Outmap_CSE_JOB_Comm_CatgLks') }} ON 
)

SELECT * FROM LkpReferences