{{ config(materialized='view', tags=['XfmHL_FEATURE_ATTRFrmExt']) }}

WITH CpyRename AS (
	SELECT
		HL_FEATURE_ATTR_ID,
		HL_FEATURE_TERM,
		HL_FEATURE_AMOUNT,
		HL_FEATURE_BALANCE,
		HL_FEATURE_FEE,
		HL_FEATURE_SPEC_REPAY,
		HL_FEATURE_EST_INT_AMT,
		HL_FEATURE_DATE,
		HL_FEATURE_COMMENT,
		{{ ref('SrcHlFeatureAttrPremapDS') }}.HL_FEATURE_CAT_ID AS SRCE_CHAR_1_C,
		HL_APP_PROD_ID,
		ORIG_ETL_D
	FROM {{ ref('SrcHlFeatureAttrPremapDS') }}
)

SELECT * FROM CpyRename