{{ config(materialized='view', tags=['XfmDelFlagAPPT_PDCT']) }}

WITH XfmRename AS (
	SELECT
		DLTD_TABL_NAME,
		DLTD_KEY1_VALU,
		{{ ref('TMP_DELETED') }}.DLTD_KEY1_VALU AS APP_PROD_ID,
		'CSE_COM_BUS_APP_PROD_CCL_PL_APP_PROD_APPT_PDCT' AS CONV_M,
		APPT_PDCT_I,
		APPT_I
	FROM {{ ref('TMP_DELETED') }}
	WHERE 
)

SELECT * FROM XfmRename