-- FRAUMD Warehouse Analysis Queries
-- Filtered for specific FRAUMD warehouses
call pst.svcs.sp_set_account_context (50973,'AU');
USE DATABASE PST;
USE SCHEMA PST.SVCS;


SELECT 
    TO_VARCHAR(START_TIME   , 'yyyy-MM') DATE, 
    WAREHOUSE_NAME,
    SUM(CREDITS_USED_COMPUTE) AS CREDITS
  FROM WAREHOUSE_METERING_HISTORY
 WHERE warehouse_name IN ('WH_USR_PRD_P01_FRAUMD_001', 'WH_USR_PRD_P01_FRAUMD_LABMLFRD_001', 'WH_USR_PRD_P01_FRAUMD_LABMLFRD_002', 'WH_USR_PRD_P01_FRAUMD_LABMLFRD_003') AND START_TIME >= DATEADD(YEAR, -1, CURRENT_TIMESTAMP())  // Past 7 days
 GROUP BY ALL
 ORDER BY 1, 2 DESC
;