{{ config(materialized='view', tags=['DltAPPTAttrClasAsscFrmTMP_APPT_ATTR_CLAS_ASSC']) }}

WITH FnFhbFoin AS (
	SELECT
		APPT_I as APPT_I,
		APPT_ATTR_CLAS_C as APPT_ATTR_CLAS_C,
		APPT_ATTR_CLAS_VALU_C as APPT_ATTR_CLAS_VALU_C,
		EFFT_D as EFFT_D,
		SRCE_SYST_C as SRCE_SYST_C,
		EXPY_D as EXPY_D,
		PROS_KEY_EFFT_I as PROS_KEY_EFFT_I,
		PROS_KEY_EXPY_I as PROS_KEY_EXPY_I,
		ROW_SECU_ACCS_C as ROW_SECU_ACCS_C
	FROM {{ ref('xfm_fhb_foin__outFHBins') }}
	UNION ALL
	SELECT
		APPT_I,
		APPT_ATTR_CLAS_C,
		APPT_ATTR_CLAS_VALU_C,
		EFFT_D,
		SRCE_SYST_C,
		EXPY_D,
		PROS_KEY_EFFT_I,
		PROS_KEY_EXPY_I,
		ROW_SECU_ACCS_C
	FROM {{ ref('xfm_fhb_foin__outFOIN_ins') }}
)

SELECT * FROM FnFhbFoin