{{ config(materialized='view', tags=['DltAPPT_PDCT_CHKLFrmTMP_APPT_PDCT_CHKL']) }}

WITH 
tmp_appt_pdct_chkl_ccc AS (
	SELECT
	*
	FROM {{ source("tdcseld","tmp_appt_pdct_chkl_ccc")  }}),
appt_pdct_chkl AS (
	SELECT
	*
	FROM {{ ref("appt_pdct_chkl")  }}),
SrcTmpApptPdctChklTera AS (SELECT A.APPT_PDCT_I AS NEW_APPT_PDCT_I, A.CHKL_ITEM_C AS NEW_CHKL_ITEM_C, A.STUS_D AS NEW_STUS_D, A.STUS_C AS NEW_STUS_C, A.SRCE_SYST_C AS NEW_SRCE_SYST_C, A.CHKL_ITEM_X AS NEW_CHKL_ITEM_X, B.APPT_PDCT_I AS OLD_APPT_PDCT_I, B.CHKL_ITEM_C AS OLD_CHKL_ITEM_C, B.STUS_D AS OLD_STUS_D, B.STUS_C AS OLD_STUS_C, B.SRCE_SYST_C AS OLD_SRCE_SYST_C, B.CHKL_ITEM_X AS OLD_CHKL_ITEM_X, B.EFFT_D AS OLD_EFFT_D, 'I' AS INSERT_UPDATE_FLAG FROM TMP_APPT_PDCT_CHKL_CCC LEFT OUTER JOIN APPT_PDCT_CHKL ON A.APPT_PDCT_I = B.APPT_PDCT_I AND A.CHKL_ITEM_C = B.CHKL_ITEM_C AND A.SRCE_SYST_C = B.SRCE_SYST_C AND b.EXPY_D = '9999-12-31' WHERE A.RUN_STRM = '{{ var("RUN_STREAM") }}' AND OLD_APPT_PDCT_I IS NULL UNION ALL SELECT A.APPT_PDCT_I AS NEW_APPT_PDCT_I, A.CHKL_ITEM_C AS NEW_CHKL_ITEM_C, A.STUS_D AS NEW_STUS_D, A.STUS_C AS NEW_STUS_C, A.SRCE_SYST_C AS NEW_SRCE_SYST_C, A.CHKL_ITEM_X AS NEW_CHKL_ITEM_X, B.APPT_PDCT_I AS OLD_APPT_PDCT_I, B.CHKL_ITEM_C AS OLD_CHKL_ITEM_C, B.STUS_D AS OLD_STUS_D, B.STUS_C AS OLD_STUS_C, B.SRCE_SYST_C AS OLD_SRCE_SYST_C, B.CHKL_ITEM_X AS OLD_CHKL_ITEM_X, B.EFFT_D AS OLD_EFFT_D, 'U' AS INSERT_UPDATE_FLAG FROM TMP_APPT_PDCT_CHKL_CCC LEFT OUTER JOIN APPT_PDCT_CHKL ON a.APPT_PDCT_I = b.APPT_PDCT_I AND A.CHKL_ITEM_C = B.CHKL_ITEM_C AND A.SRCE_SYST_C = B.SRCE_SYST_C AND b.EXPY_D = '9999-12-31' WHERE A.RUN_STRM = '{{ var("RUN_STREAM") }}' AND NOT OLD_APPT_PDCT_I IS NULL AND NOT OLD_CHKL_ITEM_C IS NULL AND NOT OLD_SRCE_SYST_C IS NULL AND (TRIM(NEW_STUS_C) <> TRIM(OLD_STUS_C) OR TRIM(NEW_CHKL_ITEM_X) <> TRIM(OLD_CHKL_ITEM_X) OR NEW_STUS_D <> OLD_STUS_D))


SELECT * FROM SrcTmpApptPdctChklTera