{{ config(materialized='view', tags=['XfmHL_FEATURE_ATTRFrmExt']) }}

WITH ModNullHandling AS (
	SELECT 
	--Manual
	--TARG_CHAR_C_LKP1: string[max=255]= handle_null (TARG_CHAR_C_LKP1, '9999')
	--TARG_CHAR_C_LKP2: string[max=255]= handle_null (TARG_CHAR_C_LKP2, '9999')
	--HL_FEATURE_DATE: string[max=25]= handle_null (HL_FEATURE_DATE, '9999')
	HL_FEATURE_ATTR_ID, HL_FEATURE_TERM, HL_FEATURE_AMOUNT, HL_FEATURE_BALANCE, HL_FEATURE_FEE, HL_FEATURE_SPEC_REPAY, HL_FEATURE_EST_INT_AMT, HL_FEATURE_DATE, HL_FEATURE_COMMENT, HL_FEATURE_CAT_ID, HL_APP_PROD_ID, ORIG_ETL_D, TARG_CHAR_C_LKP1, TARG_CHAR_C_LKP2 
	FROM {{ ref('LkpReferences2') }}
)

SELECT * FROM ModNullHandling