{{ config(materialized='view', tags=['DltPHYS_ADRSFrmTMP_PHYS_ADRS']) }}

WITH 
phys_adrs AS (
	SELECT
	*
	FROM {{ ref("phys_adrs")  }}),
tmp_phys_adrs AS (
	SELECT
	*
	FROM {{ source("tdcbdstg","tmp_phys_adrs")  }}),
SrcTmpPhysAdrsTera AS (SELECT A.ADRS_I AS NEW_ADRS_I, A.PHYS_ADRS_TYPE_C AS NEW_PHYS_ADRS_TYPE_C, A.ADRS_LINE_1_X AS NEW_ADRS_LINE_1_X, A.ADRS_LINE_2_X AS NEW_ADRS_LINE_2_X, A.SURB_X AS NEW_SURB_X, A.CITY_X AS NEW_CITY_X, A.PCOD_C AS NEW_PCOD_C, A.STAT_C AS NEW_STAT_C, A.ISO_CNTY_C AS NEW_ISO_CNTY_C, B.ADRS_I AS OLD_ADRS_I, B.PHYS_ADRS_TYPE_C AS OLD_PHYS_ADRS_TYPE_C, B.ADRS_LINE_1_X AS OLD_ADRS_LINE_1_X, B.ADRS_LINE_2_X AS OLD_ADRS_LINE_2_X, B.SURB_X AS OLD_SURB_X, B.CITY_X AS OLD_CITY_X, B.PCOD_C AS OLD_PCOD_C, B.STAT_C AS OLD_STAT_C, B.ISO_CNTY_C AS OLD_ISO_CNTY_C, B.EFFT_D AS OLD_EFFT_D FROM TMP_PHYS_ADRS LEFT OUTER JOIN PHYS_ADRS ON a.ADRS_I = b.ADRS_I AND b.EXPY_D = '9999-12-31' AND b.SRCE_SYST_C = 'CSE' WHERE a.RUN_STRM = '{{ var("RUN_STREAM") }}')


SELECT * FROM SrcTmpPhysAdrsTera