{{ config(materialized='view', tags=['ExtHL_APP_Adhoc']) }}

WITH XfmBusinessRules__PexatoTmpApptPdctFeat AS (
	SELECT
		-- *SRC*: \(20)If (Trim(( IF IsNotNull((InLkpFeatValucode.HL_APP_PROD_ID)) THEN (InLkpFeatValucode.HL_APP_PROD_ID) ELSE 0)) = 0) Then 'N' else  if Trim(InLkpFeatValucode.HL_APP_PROD_ID) = '' Then 'N' else  if num(InLkpFeatValucode.HL_APP_PROD_ID) then ( if (StringToDecimal(TRIM(InLkpFeatValucode.HL_APP_PROD_ID)) = 0) Then 'N' else 'Y') else 'Y',
		IFF(TRIM(IFF({{ ref('LkpReferences') }}.HL_APP_PROD_ID IS NOT NULL, {{ ref('LkpReferences') }}.HL_APP_PROD_ID, 0)) = 0, 'N', IFF(TRIM({{ ref('LkpReferences') }}.HL_APP_PROD_ID) = '', 'N', IFF(NUM({{ ref('LkpReferences') }}.HL_APP_PROD_ID), IFF(STRINGTODECIMAL(TRIM({{ ref('LkpReferences') }}.HL_APP_PROD_ID)) = 0, 'N', 'Y'), 'Y'))) AS svApptPdctIdChk,
		-- *SRC*: \(20)If (Trim(( IF IsNotNull((InLkpFeatValucode.PEXA_FLAG)) THEN (InLkpFeatValucode.PEXA_FLAG) ELSE 0)) = 0) Then 'N' else  if Trim(InLkpFeatValucode.PEXA_FLAG) = '' Then 'N' else  if num(InLkpFeatValucode.PEXA_FLAG) then ( if (StringToDecimal(TRIM(InLkpFeatValucode.PEXA_FLAG)) = 0) Then 'N' else 'Y') else 'Y',
		IFF(TRIM(IFF({{ ref('LkpReferences') }}.PEXA_FLAG IS NOT NULL, {{ ref('LkpReferences') }}.PEXA_FLAG, 0)) = 0, 'N', IFF(TRIM({{ ref('LkpReferences') }}.PEXA_FLAG) = '', 'N', IFF(NUM({{ ref('LkpReferences') }}.PEXA_FLAG), IFF(STRINGTODECIMAL(TRIM({{ ref('LkpReferences') }}.PEXA_FLAG)) = 0, 'N', 'Y'), 'Y'))) AS svPexaFlagChk,
		-- *SRC*: "CSEHL" : InLkpFeatValucode.HL_APP_PROD_ID,
		CONCAT('CSEHL', {{ ref('LkpReferences') }}.HL_APP_PROD_ID) AS APPT_PDCT_I,
		'2789' AS FEAT_I,
		'NOT APPLICABLE' AS SRCE_SYST_APPT_FEAT_I,
		-- *SRC*: StringToDate(ETL_PROCESS_DT, '%yyyy%mm%dd'),
		STRINGTODATE(ETL_PROCESS_DT, '%yyyy%mm%dd') AS EFFT_D,
		'CSE' AS SRCE_SYST_C,
		-- *SRC*: SetNull(),
		SETNULL() AS SRCE_SYST_APPT_OVRD_I,
		-- *SRC*: SetNull(),
		SETNULL() AS OVRD_FEAT_I,
		-- *SRC*: SetNull(),
		SETNULL() AS SRCE_SYST_STND_VALU_Q,
		-- *SRC*: SetNull(),
		SETNULL() AS SRCE_SYST_STND_VALU_R,
		-- *SRC*: SetNull(),
		SETNULL() AS SRCE_SYST_STND_VALU_A,
		-- *SRC*: SetNull(),
		SETNULL() AS CNCY_C,
		-- *SRC*: SetNull(),
		SETNULL() AS ACTL_VALU_Q,
		-- *SRC*: SetNull(),
		SETNULL() AS ACTL_VALU_R,
		-- *SRC*: SetNull(),
		SETNULL() AS ACTL_VALU_A,
		-- *SRC*: SetNull(),
		SETNULL() AS FEAT_SEQN_N,
		-- *SRC*: SetNull(),
		SETNULL() AS FEAT_STRT_D,
		-- *SRC*: SetNull(),
		SETNULL() AS FEE_CHRG_D,
		-- *SRC*: SetNull(),
		SETNULL() AS OVRD_REAS_C,
		-- *SRC*: SetNull(),
		SETNULL() AS FEE_ADD_TO_TOTL_F,
		-- *SRC*: SetNull(),
		SETNULL() AS FEE_CAPL_F,
		'9999-12-31' AS EXPY_D,
		0 AS PROS_KEY_EFFT_I,
		-- *SRC*: SetNull(),
		SETNULL() AS PROS_KEY_EXPY_I,
		-- *SRC*: SetNull(),
		SETNULL() AS EROR_SEQN_I,
		0 AS ROW_SECU_ACCS_C,
		PEXA_FLAG,
		FEAT_VALU_C
	FROM {{ ref('LkpReferences') }}
	WHERE svApptPdctIdChk = 'Y' AND svPexaFlagChk = 'Y' AND TRIMLEADINGTRAILING(IFF({{ ref('LkpReferences') }}.PEXA_FLAG IS NOT NULL, {{ ref('LkpReferences') }}.PEXA_FLAG, '')) = 'N'
)

SELECT * FROM XfmBusinessRules__PexatoTmpApptPdctFeat