use role r_dev_npd_d12_gdwmig;

use database npd_d12_dmn_gdwmig;

use warehouse wh_usr_npd_d12_gdwmig_001;

use schema iceberg_migrator;



-- Table 1: PDCBODS.ACCT_MSTR_CYT_DATA
call NPD_D12_DMN_GDWMIG.ICEBERG_MIGRATOR.MIGRATE_TABLE_TO_ICEBERG_MH(
   1,--"TABLE_INSTANCE_ID" ,
   1,--"RUN_ID",
   'NPD_D12_DMN_GDWMIG',--"TABLE_CATALOG",
   'PDCBODS',--"TABLE_SCHEMA",
   'ACCT_MSTR_CYT_DATA',--"TABLE_NAME",
   'NPD_D12_DMN_GDWMIG_IBRG', --"TARGET_TABLE_CATALOG",
   'PDCBODS', --"TARGET_TABLE_SCHEMA",
   parse_json('null') --"TABLE_CONFIGURATION"
);

-- Table 2: PDCBODS.BUSN_PTNR
call NPD_D12_DMN_GDWMIG.ICEBERG_MIGRATOR.MIGRATE_TABLE_TO_ICEBERG_MH(
   2,--"TABLE_INSTANCE_ID" ,
   1,--"RUN_ID",
   'NPD_D12_DMN_GDWMIG',--"TABLE_CATALOG",
   'PDCBODS',--"TABLE_SCHEMA",
   'BUSN_PTNR',--"TABLE_NAME",
   'NPD_D12_DMN_GDWMIG_IBRG', --"TARGET_TABLE_CATALOG",
   'PDCBODS', --"TARGET_TABLE_SCHEMA",
   parse_json('null') --"TABLE_CONFIGURATION"
);

-- Table 3: PDCBODS.CBA_FNCL_SERV_GL_DATA
call NPD_D12_DMN_GDWMIG.ICEBERG_MIGRATOR.MIGRATE_TABLE_TO_ICEBERG_MH(
   3,--"TABLE_INSTANCE_ID" ,
   1,--"RUN_ID",
   'NPD_D12_DMN_GDWMIG',--"TABLE_CATALOG",
   'PDCBODS',--"TABLE_SCHEMA",
   'CBA_FNCL_SERV_GL_DATA',--"TABLE_NAME",
   'NPD_D12_DMN_GDWMIG_IBRG', --"TARGET_TABLE_CATALOG",
   'PDCBODS', --"TARGET_TABLE_SCHEMA",
   parse_json('null') --"TABLE_CONFIGURATION"
);

-- Table 4: PDCBODS.MSTR_CNCT_BALN_TRNF_PRTP
call NPD_D12_DMN_GDWMIG.ICEBERG_MIGRATOR.MIGRATE_TABLE_TO_ICEBERG_MH(
   4,--"TABLE_INSTANCE_ID" ,
   1,--"RUN_ID",
   'NPD_D12_DMN_GDWMIG',--"TABLE_CATALOG",
   'PDCBODS',--"TABLE_SCHEMA",
   'MSTR_CNCT_BALN_TRNF_PRTP',--"TABLE_NAME",
   'NPD_D12_DMN_GDWMIG_IBRG', --"TARGET_TABLE_CATALOG",
   'PDCBODS', --"TARGET_TABLE_SCHEMA",
   parse_json('null') --"TABLE_CONFIGURATION"
);

-- Table 5: PDCBODS.MSTR_CNCT_MSTR_DATA_GENL
call NPD_D12_DMN_GDWMIG.ICEBERG_MIGRATOR.MIGRATE_TABLE_TO_ICEBERG_MH(
   5,--"TABLE_INSTANCE_ID" ,
   1,--"RUN_ID",
   'NPD_D12_DMN_GDWMIG',--"TABLE_CATALOG",
   'PDCBODS',--"TABLE_SCHEMA",
   'MSTR_CNCT_MSTR_DATA_GENL',--"TABLE_NAME",
   'NPD_D12_DMN_GDWMIG_IBRG', --"TARGET_TABLE_CATALOG",
   'PDCBODS', --"TARGET_TABLE_SCHEMA",
   parse_json('null') --"TABLE_CONFIGURATION"
);

-- Table 6: PDCBODS.MSTR_CNCT_PRXY_ACCT
call NPD_D12_DMN_GDWMIG.ICEBERG_MIGRATOR.MIGRATE_TABLE_TO_ICEBERG_MH(
   6,--"TABLE_INSTANCE_ID" ,
   1,--"RUN_ID",
   'NPD_D12_DMN_GDWMIG',--"TABLE_CATALOG",
   'PDCBODS',--"TABLE_SCHEMA",
   'MSTR_CNCT_PRXY_ACCT',--"TABLE_NAME",
   'NPD_D12_DMN_GDWMIG_IBRG', --"TARGET_TABLE_CATALOG",
   'PDCBODS', --"TARGET_TABLE_SCHEMA",
   parse_json('null') --"TABLE_CONFIGURATION"
);

-- Table 7: PDSECURITY.ROW_LEVL_SECU_USER_PRFL
call NPD_D12_DMN_GDWMIG.ICEBERG_MIGRATOR.MIGRATE_TABLE_TO_ICEBERG_MH(
   7,--"TABLE_INSTANCE_ID" ,
   1,--"RUN_ID",
   'NPD_D12_DMN_GDWMIG',--"TABLE_CATALOG",
   'PDSECURITY',--"TABLE_SCHEMA",
   'ROW_LEVL_SECU_USER_PRFL',--"TABLE_NAME",
   'NPD_D12_DMN_GDWMIG_IBRG', --"TARGET_TABLE_CATALOG",
   'PDSECURITY', --"TARGET_TABLE_SCHEMA",
   parse_json('null') --"TABLE_CONFIGURATION"
);

-- Table 8: STAR_CAD_PROD_DATA.DERV_PRTF_PATY_PSST
call NPD_D12_DMN_GDWMIG.ICEBERG_MIGRATOR.MIGRATE_TABLE_TO_ICEBERG_MH(
   8,--"TABLE_INSTANCE_ID" ,
   1,--"RUN_ID",
   'NPD_D12_DMN_GDWMIG',--"TABLE_CATALOG",
   'STAR_CAD_PROD_DATA',--"TABLE_SCHEMA",
   'DERV_PRTF_PATY_PSST',--"TABLE_NAME",
   'NPD_D12_DMN_GDWMIG_IBRG', --"TARGET_TABLE_CATALOG",
   'STARCADPRODDATA', --"TARGET_TABLE_SCHEMA",
   parse_json('null') --"TABLE_CONFIGURATION"
);

-- Table 9: PDGRD.GRD_RPRT_CALR_FNYR
call NPD_D12_DMN_GDWMIG.ICEBERG_MIGRATOR.MIGRATE_TABLE_TO_ICEBERG_MH(
   9,--"TABLE_INSTANCE_ID" ,
   1,--"RUN_ID",
   'NPD_D12_DMN_GDWMIG',--"TABLE_CATALOG",
   'PDGRD',--"TABLE_SCHEMA",
   'GRD_RPRT_CALR_FNYR',--"TABLE_NAME",
   'NPD_D12_DMN_GDWMIG_IBRG', --"TARGET_TABLE_CATALOG",
   'PDGRD', --"TARGET_TABLE_SCHEMA",
   parse_json('null') --"TABLE_CONFIGURATION"
);

-- Table 10: STAR_CAD_PROD_DATA.MAP_SAP_INVL_PDCT
call NPD_D12_DMN_GDWMIG.ICEBERG_MIGRATOR.MIGRATE_TABLE_TO_ICEBERG_MH(
   10,--"TABLE_INSTANCE_ID" ,
   1,--"RUN_ID",
   'NPD_D12_DMN_GDWMIG',--"TABLE_CATALOG",
   'STAR_CAD_PROD_DATA',--"TABLE_SCHEMA",
   'MAP_SAP_INVL_PDCT',--"TABLE_NAME",
   'NPD_D12_DMN_GDWMIG_IBRG', --"TARGET_TABLE_CATALOG",
   'STARCADPRODDATA', --"TARGET_TABLE_SCHEMA",
   parse_json('null') --"TABLE_CONFIGURATION"
);

-- Table 11: STAR_CAD_PROD_DATA.DERV_PRTF_ACCT_REL
call NPD_D12_DMN_GDWMIG.ICEBERG_MIGRATOR.MIGRATE_TABLE_TO_ICEBERG_MH(
   11,--"TABLE_INSTANCE_ID" ,
   1,--"RUN_ID",
   'NPD_D12_DMN_GDWMIG',--"TABLE_CATALOG",
   'STAR_CAD_PROD_DATA',--"TABLE_SCHEMA",
   'DERV_PRTF_ACCT_REL',--"TABLE_NAME",
   'NPD_D12_DMN_GDWMIG_IBRG', --"TARGET_TABLE_CATALOG",
   'STARCADPRODDATA', --"TARGET_TABLE_SCHEMA",
   parse_json('null') --"TABLE_CONFIGURATION"
);

-- Table 12: STAR_CAD_PROD_DATA.ACCT_PDCT
call NPD_D12_DMN_GDWMIG.ICEBERG_MIGRATOR.MIGRATE_TABLE_TO_ICEBERG_MH(
   12,--"TABLE_INSTANCE_ID" ,
   1,--"RUN_ID",
   'NPD_D12_DMN_GDWMIG',--"TABLE_CATALOG",
   'STAR_CAD_PROD_DATA',--"TABLE_SCHEMA",
   'ACCT_PDCT',--"TABLE_NAME",
   'NPD_D12_DMN_GDWMIG_IBRG', --"TARGET_TABLE_CATALOG",
   'STARCADPRODDATA', --"TARGET_TABLE_SCHEMA",
   parse_json('null') --"TABLE_CONFIGURATION"
);

-- Table 13: PDPATY.ACCT_PATY
call NPD_D12_DMN_GDWMIG.ICEBERG_MIGRATOR.MIGRATE_TABLE_TO_ICEBERG_MH(
   13,--"TABLE_INSTANCE_ID" ,
   1,--"RUN_ID",
   'NPD_D12_DMN_GDWMIG',--"TABLE_CATALOG",
   'PDPATY',--"TABLE_SCHEMA",
   'ACCT_PATY',--"TABLE_NAME",
   'NPD_D12_DMN_GDWMIG_IBRG', --"TARGET_TABLE_CATALOG",
   'PDPATY', --"TARGET_TABLE_SCHEMA",
   parse_json('null') --"TABLE_CONFIGURATION"
);

-- Table 14: STAR_CAD_PROD_DATA.ACCT_OFFR
call NPD_D12_DMN_GDWMIG.ICEBERG_MIGRATOR.MIGRATE_TABLE_TO_ICEBERG_MH(
   14,--"TABLE_INSTANCE_ID" ,
   1,--"RUN_ID",
   'NPD_D12_DMN_GDWMIG',--"TABLE_CATALOG",
   'STAR_CAD_PROD_DATA',--"TABLE_SCHEMA",
   'ACCT_OFFR',--"TABLE_NAME",
   'NPD_D12_DMN_GDWMIG_IBRG', --"TARGET_TABLE_CATALOG",
   'STARCADPRODDATA', --"TARGET_TABLE_SCHEMA",
   parse_json('null') --"TABLE_CONFIGURATION"
);

-- Table 15: STAR_CAD_PROD_DATA.ACCT_BASE
call NPD_D12_DMN_GDWMIG.ICEBERG_MIGRATOR.MIGRATE_TABLE_TO_ICEBERG_MH(
   15,--"TABLE_INSTANCE_ID" ,
   1,--"RUN_ID",
   'NPD_D12_DMN_GDWMIG',--"TABLE_CATALOG",
   'STAR_CAD_PROD_DATA',--"TABLE_SCHEMA",
   'ACCT_BASE',--"TABLE_NAME",
   'NPD_D12_DMN_GDWMIG_IBRG', --"TARGET_TABLE_CATALOG",
   'STARCADPRODDATA', --"TARGET_TABLE_SCHEMA",
   parse_json('null') --"TABLE_CONFIGURATION"
);
