use role ACCOUNTADMIN;
USE DATABASE NPD_D12_DMN_GDWMIG_IBRG_V;

-- Create schema if not exists
CREATE SCHEMA IF NOT EXISTS NPD_D12_DMN_GDWMIG_IBRG_V.PDDSTG;

-- Drop table if exists before creating
DROP TABLE IF EXISTS NPD_D12_DMN_GDWMIG_IBRG_V.PDDSTG.ACCT_BALN_BKDT_ADJ_RULE;

--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE NPD_D12_DMN_GDWMIG_IBRG_V.PDDSTG.ACCT_BALN_BKDT_ADJ_RULE (
    ACCT_I STRING NOT NULL,
    SRCE_SYST_C STRING,
    BALN_TYPE_C STRING,
    CALC_FUNC_C STRING,
    TIME_PERD_C STRING,
    ADJ_FROM_D DATE NOT NULL,
    BKDT_ADJ_FROM_D DATE NOT NULL,
    ADJ_TO_D DATE NOT NULL,
    ADJ_A DECIMAL(38,2),
    EFFT_D DATE,
    Gl_RECN_F STRING,
    PROS_KEY_EFFT_I DECIMAL(10,0)
); 