use role ACCOUNTADMIN;
USE DATABASE PS_CLD_RW;

CREATE SCHEMA IF NOT EXISTS PS_CLD_RW.PDCBSTG;

-- CREATE SCHEMA IF NOT EXISTS PS_CLD_RW.PDDSTG;
-- CREATE SCHEMA IF NOT EXISTS PS_CLD_RW.PDGRD;
CREATE SCHEMA IF NOT EXISTS PS_CLD_RW.PTEMP;
CREATE SCHEMA IF NOT EXISTS PS_CLD_RW.PP01STARCADPRODDATA;
-- CREATE SCHEMA IF NOT EXISTS PS_CLD_RW.STARCADPRODDATA;
CREATE SCHEMA IF NOT EXISTS PS_CLD_RW.UDTDWRK;


DROP TABLE IF EXISTS PS_CLD_RW.PP01STARCADPRODDATA.ACCT_INT_GRUP;
DROP TABLE IF EXISTS PS_CLD_RW.PDGRD.GRD_PRTF_TYPE_ENHC_HIST_PSST;
DROP TABLE IF EXISTS PS_CLD_RW.PDGRD.GRD_PRTF_TYPE_ENHC_PSST;
DROP TABLE IF EXISTS PS_CLD_RW.PDDSTG.ACCT_BALN_BKDT_STG;
DROP TABLE IF EXISTS PS_CLD_RW.PDCBSTG.ACCT_REL_HLS_REME;
DROP TABLE IF EXISTS PS_CLD_RW.PDCBSTG.ACCT_REL_HLS_REME_HIST;
DROP TABLE IF EXISTS PS_CLD_RW.PDCBSTG.UTIL_PROS_SAP_RUN;
DROP TABLE IF EXISTS PS_CLD_RW.STARCADPRODDATA.ACCT_BALN_BKDT;
DROP TABLE IF EXISTS PS_CLD_RW.STARCADPRODDATA.ACCT_BALN_BKDT_RECN;
DROP TABLE IF EXISTS PS_CLD_RW.STARCADPRODDATA.ACCT_INT_GRUP;
DROP TABLE IF EXISTS PS_CLD_RW.UDTDWRK.DERV_PRTF_ACCT_HIST_PSST;
DROP TABLE IF EXISTS PS_CLD_RW.STARCADPRODDATA.DERV_PRTF_ACCT_HIST_PSST;
DROP TABLE IF EXISTS PS_CLD_RW.STARCADPRODDATA.DERV_PRTF_ACCT_INT_GRUP_PSST;
DROP TABLE IF EXISTS PS_CLD_RW.STARCADPRODDATA.DERV_PRTF_ACCT_PSST;
DROP TABLE IF EXISTS PS_CLD_RW.STARCADPRODDATA.DERV_PRTF_INT_GRUP_ENHC_PSST;
DROP TABLE IF EXISTS PS_CLD_RW.STARCADPRODDATA.DERV_PRTF_INT_GRUP_OWN_PSST;
DROP TABLE IF EXISTS PS_CLD_RW.STARCADPRODDATA.DERV_PRTF_INT_HIST_PSST;
DROP TABLE IF EXISTS PS_CLD_RW.STARCADPRODDATA.DERV_PRTF_INT_PSST;
DROP TABLE IF EXISTS PS_CLD_RW.PTEMP.DERV_PRTF_INT_PSST;
DROP TABLE IF EXISTS PS_CLD_RW.STARCADPRODDATA.DERV_PRTF_OWN_HIST_PSST;
DROP TABLE IF EXISTS PS_CLD_RW.STARCADPRODDATA.DERV_PRTF_OWN_PSST;
DROP TABLE IF EXISTS PS_CLD_RW.STARCADPRODDATA.DERV_PRTF_PATY_HIST_PSST;
DROP TABLE IF EXISTS PS_CLD_RW.STARCADPRODDATA.DERV_PRTF_PATY_INT_GRUP_PSST;
DROP TABLE IF EXISTS PS_CLD_RW.STARCADPRODDATA.ACCT_BALN_BKDT_AUDT;
DROP TABLE IF EXISTS PS_CLD_RW.STARCADPRODDATA.ACCT_PATY_TAX_INSS;
DROP TABLE IF EXISTS PS_CLD_RW.STARCADPRODDATA.DERV_PRTF_ACCT_OWN_REL;
DROP TABLE IF EXISTS PS_CLD_RW.STARCADPRODDATA.DERV_PRTF_PATY_OWN_REL;
drop table if exists PS_CLD_RW.PDDSTG.ACCT_BALN_BKDT_STG1;
drop table if exists PS_CLD_RW.PDDSTG.ACCT_BALN_BKDT_STG2;


/* DGRDDB.GRD_PRTF_TYPE_ENHC_HIST_PSST -> PDGRD.GRD_PRTF_TYPE_ENHC_HIST_PSST */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE PS_CLD_RW.PDGRD.GRD_PRTF_TYPE_ENHC_HIST_PSST (
 PRTF_TYPE_C STRING,
 PRTF_TYPE_M STRING,
 PRTF_CLAS_C STRING,
 PRTF_CLAS_M STRING,
 PRTF_CATG_C STRING,
 PRTF_CATG_M STRING,
 VALD_FROM_D DATE,
 VALD_TO_D DATE
);

/* DGRDDB.GRD_PRTF_TYPE_ENHC_PSST -> PDGRD.GRD_PRTF_TYPE_ENHC_PSST */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE PS_CLD_RW.PDGRD.GRD_PRTF_TYPE_ENHC_PSST (
 PERD_D DATE,
 PRTF_TYPE_C STRING,
 PRTF_TYPE_M STRING,
 PRTF_CLAS_C STRING,
 PRTF_CLAS_M STRING,
 PRTF_CATG_C STRING,
 PRTF_CATG_M STRING
);
/* PDDSTG.ACCT_BALN_BKDT_STG1 -> PDDSTG.ACCT_BALN_BKDT_STG1 */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE PS_CLD_RW.PDDSTG.ACCT_BALN_BKDT_STG1 (
 ACCT_I STRING NOT NULL,
 BALN_TYPE_C STRING,
 CALC_FUNC_C STRING,
 TIME_PERD_C STRING,
 BKDT_EFFT_D DATE NOT NULL,
 BKDT_EXPY_D DATE,
 BALN_A DECIMAL(15,2),
 CALC_F STRING,
 PROS_KEY_EFFT_I DECIMAL(10,0),
 PROS_KEY_EXPY_I DECIMAL(10,0),
 BKDT_PROS_KEY_I DECIMAL(10,0),
 ORIG_SRCE_SYST_C STRING,
 SRCE_SYST_C STRING,
 LOAD_D DATE
);

/* PDDSTG.ACCT_BALN_BKDT_STG2 -> PDDSTG.ACCT_BALN_BKDT_STG2 */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE PS_CLD_RW.PDDSTG.ACCT_BALN_BKDT_STG2 (
 ACCT_I STRING NOT NULL,
 BALN_TYPE_C STRING,
 CALC_FUNC_C STRING,
 TIME_PERD_C STRING,
 BKDT_EFFT_D DATE,
 BKDT_EXPY_D DATE,
 BALN_A DECIMAL(15,2),
 CALC_F STRING,
 PROS_KEY_EFFT_I DECIMAL(10,0),
 PROS_KEY_EXPY_I DECIMAL(10,0),
 BKDT_PROS_KEY_I DECIMAL(10,0),
 ADJ_PROS_KEY_EFFT_I DECIMAL(10,0),
 ORIG_SRCE_SYST_C STRING,
 SRCE_SYST_C STRING,
 LOAD_D DATE
);

/* PDDSTG.ACCT_REL_HLS_REME -> PDCBSTG.ACCT_REL_HLS_REME */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE PS_CLD_RW.PDCBSTG.ACCT_REL_HLS_REME (
 SUBJ_ACCT_I STRING,
 OBJC_ACCT_I STRING,
 OBJC_BDT_APPT STRING,
 VALD_FROM TIMESTAMP(6),
 ACTL_VALD_END TIMESTAMP(6),
 REL_C STRING,
 MIRR_REL_C STRING,
 CTCT_STUS STRING,
 INTR_CNCT_NUMB_OF_MAIN_CNCT STRING,
 HIER_ID STRING,
 CNCT_CATG STRING,
 RUN_STRM_PROS_D DATE,
 OBJC_ACCT_LEVL_N INTEGER,
 SUBJ_ACCT_LEVL_N INTEGER,
 TGT_EFFT_D DATE,
 FLG STRING
);

/* PDDSTG.ACCT_REL_HLS_REME_HIST -> PDCBSTG.ACCT_REL_HLS_REME_HIST */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE PS_CLD_RW.PDCBSTG.ACCT_REL_HLS_REME_HIST (
 SUBJ_ACCT_I STRING,
 OBJC_ACCT_I STRING,
 OBJC_BDT_APPT STRING,
 VALD_FROM TIMESTAMP(6),
 ACTL_VALD_END TIMESTAMP(6),
 REL_C STRING,
 MIRR_REL_C STRING,
 CTCT_STUS STRING,
 INTR_CNCT_NUMB_OF_MAIN_CNCT STRING,
 HIER_ID STRING,
 CNCT_CATG STRING,
 RUN_STRM_PROS_D DATE,
 OBJC_ACCT_LEVL_N INTEGER,
 SUBJ_ACCT_LEVL_N INTEGER,
 TGT_EFFT_D DATE,
 FLG STRING,
 LOAD_DATE DATE NOT NULL
);

/* PDDSTG.UTIL_PROS_SAP_RUN -> PDCBSTG.UTIL_PROS_SAP_RUN */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE PS_CLD_RW.PDCBSTG.UTIL_PROS_SAP_RUN (
 RUN_DATE DATE,
 PROS_KEY_EFFT_I BIGINT
 -- ,
--  (START STRING,
--  INCREMENT STRING,
--  MINVALUE STRING,
--  MAXVALUE STRING,
--  NO STRING,
--  RECD_CNT INTEGER
)
;

/* PVTECH.ACCT_BALN_BKDT -> STARCADPRODDATA.ACCT_BALN_BKDT */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE PS_CLD_RW.STARCADPRODDATA.ACCT_BALN_BKDT (
 ACCT_I STRING NOT NULL COMMENT 'Account Identifier',
 BALN_TYPE_C STRING NOT NULL COMMENT 'Balance Type Code',
 CALC_FUNC_C STRING NOT NULL COMMENT 'Calculation Function Code',
 TIME_PERD_C STRING NOT NULL COMMENT 'Time Period Code',
 BALN_A DECIMAL(23,5) COMMENT 'Balance Amount',
 CALC_F STRING NOT NULL COMMENT 'Calculate Flag',
 SRCE_SYST_C STRING COMMENT 'Source System Code',
 ORIG_SRCE_SYST_C STRING COMMENT 'Original Source System Code',
 LOAD_D DATE COMMENT 'Load Date',
 BKDT_EFFT_D DATE NOT NULL COMMENT 'Backdate Effective Date',
 BKDT_EXPY_D DATE NOT NULL COMMENT 'Backdate Expiry Date',
 PROS_KEY_EFFT_I DECIMAL(10,0) COMMENT 'Process Key Effective Identifier',
 PROS_KEY_EXPY_I DECIMAL(10,0) COMMENT 'Process Key Expiry Identifier',
 BKDT_PROS_KEY_I DECIMAL(10,0) COMMENT 'Backdate Process Key Identifier',
 CNCY_C STRING COMMENT 'Currency Code',
 ROW_SECU_ACCS_C INTEGER COMMENT 'Row Security Access Code'
);

/* PVTECH.ACCT_BALN_BKDT_RECN -> STARCADPRODDATA.ACCT_BALN_BKDT_RECN */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE PS_CLD_RW.STARCADPRODDATA.ACCT_BALN_BKDT_RECN (
 ACCT_I STRING NOT NULL COMMENT 'Account Identifier',
 BALN_A DECIMAL(15,2) COMMENT 'Balance Amount',
 BKDT_EFFT_D DATE NOT NULL COMMENT 'Backdate Effective Date',
 BKDT_EXPY_D DATE NOT NULL COMMENT 'Backdate Expiry Date',
 PROS_KEY_EFFT_I DECIMAL(10,0) COMMENT 'Process Key Effective Identifier'
);

/* STAR_CAD_PROD_DATA.ACCT_BALN_BKDT_AUDT -> STARCADPRODDATA.ACCT_BALN_BKDT_AUDT */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE PS_CLD_RW.STARCADPRODDATA.ACCT_BALN_BKDT_AUDT (
 ACCT_I STRING NOT NULL COMMENT 'Account Identifier',
 BALN_TYPE_C STRING NOT NULL COMMENT 'Balance Type Code',
 CALC_FUNC_C STRING NOT NULL COMMENT 'Calculation Function Code',
 TIME_PERD_C STRING NOT NULL COMMENT 'Time Period Code',
 BALN_A DECIMAL(15,2) COMMENT 'Balance Amount',
 CALC_F STRING NOT NULL COMMENT 'Calculate Flag',
 SRCE_SYST_C STRING COMMENT 'Source System Code',
 ORIG_SRCE_SYST_C STRING COMMENT 'Original Source System Code',
 LOAD_D DATE COMMENT 'Load Date',
 BKDT_EFFT_D DATE NOT NULL COMMENT 'Backdate Effective Date',
 BKDT_EXPY_D DATE NOT NULL COMMENT 'Backdate Expiry Date',
 PROS_KEY_EFFT_I DECIMAL(10,0) COMMENT 'Process Key Effective Identifier',
 ABAL_PROS_KEY_EFFT_I DECIMAL(10,0) COMMENT 'Adjusted Balance Process Key Effective Identifier',
 ABAL_PROS_KEY_EXPY_I DECIMAL(10,0) COMMENT 'Adjusted Balance Process Key Expiry Identifier',
 ABAL_BKDT_PROS_KEY_I DECIMAL(10,0) COMMENT 'Adjusted Balance Backdate Process Key Effective Identifier',
 ADJ_PROS_KEY_EFFT_I DECIMAL(10,0) COMMENT 'Adjusted Process Key Effective Identifier'
);

/* PVTECH.ACCT_INT_GRUP -> PP01STARCADPRODDATA.ACCT_INT_GRUP */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **

CREATE ICEBERG TABLE PS_CLD_RW.PP01STARCADPRODDATA.ACCT_INT_GRUP (
 ACCT_I STRING NOT NULL COMMENT 'Account Identifier',
 INT_GRUP_I STRING NOT NULL COMMENT 'Interest Group Identifier',
 REL_C STRING NOT NULL COMMENT 'Relationship Code',
 SRCE_SYST_C STRING COMMENT 'Source System Code',
 VALD_FROM_D DATE COMMENT 'Valid From Date',
 VALD_TO_D DATE COMMENT 'Valid To Date',
 EFFT_D DATE NOT NULL COMMENT 'Effective Date',
 EXPY_D DATE NOT NULL COMMENT 'Expiry Date',
 PROS_KEY_EFFT_I DECIMAL(10,0) NOT NULL COMMENT 'Process Key Effective Identifier',
 PROS_KEY_EXPY_I DECIMAL(10,0) COMMENT 'Process Key Expiry Identifier',
 ROW_SECU_ACCS_C INTEGER NOT NULL COMMENT 'Row Security Access Code'
);

/* PVTECH.ACCT_INT_GRUP -> STARCADPRODDATA.ACCT_INT_GRUP */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE PS_CLD_RW.STARCADPRODDATA.ACCT_INT_GRUP (
 ACCT_I STRING NOT NULL COMMENT 'Account Identifier',
 INT_GRUP_I STRING NOT NULL COMMENT 'Interest Group Identifier',
 REL_C STRING NOT NULL COMMENT 'Relationship Code',
 SRCE_SYST_C STRING COMMENT 'Source System Code',
 VALD_FROM_D DATE COMMENT 'Valid From Date',
 VALD_TO_D DATE COMMENT 'Valid To Date',
 EFFT_D DATE NOT NULL COMMENT 'Effective Date',
 EXPY_D DATE NOT NULL COMMENT 'Expiry Date',
 PROS_KEY_EFFT_I DECIMAL(10,0) NOT NULL COMMENT 'Process Key Effective Identifier',
 PROS_KEY_EXPY_I DECIMAL(10,0) COMMENT 'Process Key Expiry Identifier',
 ROW_SECU_ACCS_C INTEGER NOT NULL COMMENT 'Row Security Access Code'
);

/* PVTECH.DERV_PRTF_ACCT_HIST_PSST -> UDTDWRK.DERV_PRTF_ACCT_HIST_PSST */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE PS_CLD_RW.UDTDWRK.DERV_PRTF_ACCT_HIST_PSST (
 INT_GRUP_I STRING,
 ACCT_I STRING,
 REL_C STRING,
 JOIN_FROM_D DATE,
 JOIN_TO_D DATE,
 VALD_FROM_D DATE,
 VALD_TO_D DATE,
 EFFT_D DATE,
 EXPY_D DATE,
 SRCE_SYST_C STRING,
 ROW_SECU_ACCS_C INTEGER
);

/* PVTECH.DERV_PRTF_ACCT_HIST_PSST -> STARCADPRODDATA.DERV_PRTF_ACCT_HIST_PSST */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE PS_CLD_RW.STARCADPRODDATA.DERV_PRTF_ACCT_HIST_PSST (
 INT_GRUP_I STRING,
 ACCT_I STRING,
 REL_C STRING,
 JOIN_FROM_D DATE,
 JOIN_TO_D DATE,
 VALD_FROM_D DATE,
 VALD_TO_D DATE,
 EFFT_D DATE,
 EXPY_D DATE,
 SRCE_SYST_C STRING,
 ROW_SECU_ACCS_C INTEGER
);

/* PVTECH.DERV_PRTF_ACCT_INT_GRUP_PSST -> STARCADPRODDATA.DERV_PRTF_ACCT_INT_GRUP_PSST */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE PS_CLD_RW.STARCADPRODDATA.DERV_PRTF_ACCT_INT_GRUP_PSST (
 INT_GRUP_I STRING,
 ACCT_I STRING,
 EFFT_D DATE,
 EXPY_D DATE,
 VALD_FROM_D DATE,
 VALD_TO_D DATE,
 PERD_D DATE,
 REL_C STRING,
 SRCE_SYST_C STRING,
 ROW_N DECIMAL(10,0),
 ROW_SECU_ACCS_C INTEGER,
 PROS_KEY_I DECIMAL(10,0)
);

/* PVTECH.DERV_PRTF_ACCT_PSST -> STARCADPRODDATA.DERV_PRTF_ACCT_PSST */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE PS_CLD_RW.STARCADPRODDATA.DERV_PRTF_ACCT_PSST (
 INT_GRUP_I STRING,
 ACCT_I STRING,
 REL_C STRING,
 JOIN_FROM_D DATE,
 JOIN_TO_D DATE,
 VALD_FROM_D DATE,
 VALD_TO_D DATE,
 EFFT_D DATE,
 EXPY_D DATE,
 SRCE_SYST_C STRING,
 PROS_KEY_I DECIMAL(10,0),
 ROW_SECU_ACCS_C INTEGER
);

/* PVTECH.DERV_PRTF_INT_GRUP_ENHC_PSST -> STARCADPRODDATA.DERV_PRTF_INT_GRUP_ENHC_PSST */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE PS_CLD_RW.STARCADPRODDATA.DERV_PRTF_INT_GRUP_ENHC_PSST (
 INT_GRUP_I STRING,
 INT_GRUP_TYPE_C STRING,
 EFFT_D DATE,
 EXPY_D DATE,
 VALD_FROM_D DATE,
 VALD_TO_D DATE,
 PERD_D DATE,
 PTCL_N STRING,
 REL_MNGE_I STRING,
 ROW_N DECIMAL(10,0),
 PROS_KEY_I DECIMAL(10,0)
);

/* PVTECH.DERV_PRTF_INT_GRUP_OWN_PSST -> STARCADPRODDATA.DERV_PRTF_INT_GRUP_OWN_PSST */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE PS_CLD_RW.STARCADPRODDATA.DERV_PRTF_INT_GRUP_OWN_PSST (
 INT_GRUP_I STRING,
 ROLE_PLAY_I STRING,
 EFFT_D DATE,
 EXPY_D DATE,
 VALD_FROM_D DATE,
 VALD_TO_D DATE,
 PERD_D DATE,
 ROLE_PLAY_TYPE_X STRING,
 DERV_PRTF_ROLE_C STRING,
 SRCE_SYST_C STRING,
 ROW_N DECIMAL(10,0),
 ROW_SECU_ACCS_C INTEGER,
 PROS_KEY_I DECIMAL(10,0)
);

/* PVTECH.DERV_PRTF_INT_HIST_PSST -> STARCADPRODDATA.DERV_PRTF_INT_HIST_PSST */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE PS_CLD_RW.STARCADPRODDATA.DERV_PRTF_INT_HIST_PSST (
 INT_GRUP_I STRING,
 INT_GRUP_TYPE_C STRING,
 EFFT_D DATE,
 EXPY_D DATE,
 VALD_FROM_D DATE,
 VALD_TO_D DATE,
 JOIN_FROM_D DATE,
 JOIN_TO_D DATE,
 PTCL_N STRING,
 REL_MNGE_I STRING
);

/* PVTECH.DERV_PRTF_INT_PSST -> STARCADPRODDATA.DERV_PRTF_INT_PSST */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE PS_CLD_RW.STARCADPRODDATA.DERV_PRTF_INT_PSST (
 INT_GRUP_I STRING,
 INT_GRUP_TYPE_C STRING,
 JOIN_FROM_D DATE,
 JOIN_TO_D DATE,
 EFFT_D DATE,
 EXPY_D DATE,
 PTCL_N STRING,
 REL_MNGE_I STRING,
 VALD_FROM_D DATE,
 VALD_TO_D DATE,
 PROS_KEY_I DECIMAL(10,0)
);

/* PVTECH.DERV_PRTF_INT_PSST -> PTEMP.DERV_PRTF_INT_PSST */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE PS_CLD_RW.PTEMP.DERV_PRTF_INT_PSST (
 INT_GRUP_I STRING,
 INT_GRUP_TYPE_C STRING,
 JOIN_FROM_D DATE,
 JOIN_TO_D DATE,
 EFFT_D DATE,
 EXPY_D DATE,
 PTCL_N STRING,
 REL_MNGE_I STRING,
 VALD_FROM_D DATE,
 VALD_TO_D DATE,
 PROS_KEY_I DECIMAL(10,0)
);

/* PVTECH.DERV_PRTF_OWN_HIST_PSST -> STARCADPRODDATA.DERV_PRTF_OWN_HIST_PSST */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE PS_CLD_RW.STARCADPRODDATA.DERV_PRTF_OWN_HIST_PSST (
 INT_GRUP_I STRING,
 ROLE_PLAY_I STRING,
 JOIN_FROM_D DATE,
 JOIN_TO_D DATE,
 EFFT_D DATE,
 EXPY_D DATE,
 VALD_FROM_D DATE,
 VALD_TO_D DATE,
 ROLE_PLAY_TYPE_X STRING,
 DERV_PRTF_ROLE_C STRING,
 SRCE_SYST_C STRING,
 ROW_SECU_ACCS_C INTEGER,
 PROS_KEY_I DECIMAL(10,0)
);

/* PVTECH.DERV_PRTF_OWN_PSST -> STARCADPRODDATA.DERV_PRTF_OWN_PSST */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE PS_CLD_RW.STARCADPRODDATA.DERV_PRTF_OWN_PSST (
 INT_GRUP_I STRING,
 JOIN_FROM_D DATE,
 JOIN_TO_D DATE,
 VALD_FROM_D DATE,
 VALD_TO_D DATE,
 EFFT_D DATE,
 EXPY_D DATE,
 DERV_PRTF_ROLE_C STRING,
 ROLE_PLAY_TYPE_X STRING,
 ROLE_PLAY_I STRING,
 SRCE_SYST_C STRING,
 ROW_SECU_ACCS_C INTEGER,
 PROS_KEY_I DECIMAL(10,0)
);

/* PVTECH.DERV_PRTF_PATY_HIST_PSST -> STARCADPRODDATA.DERV_PRTF_PATY_HIST_PSST */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE PS_CLD_RW.STARCADPRODDATA.DERV_PRTF_PATY_HIST_PSST (
 INT_GRUP_I STRING,
 PATY_I STRING,
 REL_C STRING,
 JOIN_FROM_D DATE,
 JOIN_TO_D DATE,
 VALD_FROM_D DATE,
 VALD_TO_D DATE,
 EFFT_D DATE,
 EXPY_D DATE,
 SRCE_SYST_C STRING,
 ROW_SECU_ACCS_C INTEGER,
 PROS_KEY_I DECIMAL(10,0)
);

/* PVTECH.DERV_PRTF_PATY_INT_GRUP_PSST -> STARCADPRODDATA.DERV_PRTF_PATY_INT_GRUP_PSST */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE PS_CLD_RW.STARCADPRODDATA.DERV_PRTF_PATY_INT_GRUP_PSST (
 INT_GRUP_I STRING,
 PATY_I STRING,
 EFFT_D DATE,
 EXPY_D DATE,
 VALD_FROM_D DATE,
 VALD_TO_D DATE,
 PERD_D DATE,
 REL_C STRING,
 SRCE_SYST_C STRING,
 ROW_N DECIMAL(10,0),
 ROW_SECU_ACCS_C INTEGER,
 PROS_KEY_I DECIMAL(10,0)
);

/* STAR_CAD_PROD_DATA.DERV_PRTF_ACCT_OWN_REL -> STARCADPRODDATA.DERV_PRTF_ACCT_OWN_REL */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE PS_CLD_RW.STARCADPRODDATA.DERV_PRTF_ACCT_OWN_REL (
 ACCT_I STRING NOT NULL COMMENT 'Account Identifier',
 INT_GRUP_I STRING NOT NULL COMMENT 'Interest Group Identifier',
 DERV_PRTF_CATG_C STRING COMMENT 'Derived Portfolio Catgeory Code',
 DERV_PRTF_CLAS_C STRING COMMENT 'Derived Portfolio Class Code',
 DERV_PRTF_TYPE_C STRING COMMENT 'Derived Portfolio Type Code',
 PRTF_ACCT_VALD_FROM_D DATE COMMENT 'Portfolio Account Valid From Date',
 PRTF_ACCT_VALD_TO_D DATE COMMENT 'Portfolio Account Valid To Date',
 PRTF_ACCT_EFFT_D DATE COMMENT 'Portfolio Account Effective Date',
 PRTF_ACCT_EXPY_D DATE COMMENT 'Portfolio Account Expiry Date',
 PRTF_OWN_VALD_FROM_D DATE COMMENT 'Portfolio Owner Valid From Date',
 PRTF_OWN_VALD_TO_D DATE COMMENT 'Portfolio Owner Valid To Date',
 PRTF_OWN_EFFT_D DATE COMMENT 'Portfolio Owner Effective Date',
 PRTF_OWN_EXPY_D DATE COMMENT 'Portfolio Owner Expiry Date',
 PTCL_N INT COMMENT 'Point Of Control Number',
 REL_MNGE_I STRING COMMENT 'Relationship Manager Identifier',
 PRTF_CODE_X STRING COMMENT 'Portfolio Code Description',
 DERV_PRTF_ROLE_C STRING COMMENT 'Derived Portfolio Role Code',
 ROLE_PLAY_TYPE_X STRING COMMENT 'Role Player Type Description',
 ROLE_PLAY_I STRING NOT NULL COMMENT 'Role Player Identifier',
 SRCE_SYST_C STRING COMMENT 'Source System Code',
 ROW_SECU_ACCS_C INTEGER NOT NULL COMMENT 'Row Security Access Code'
);

/* STAR_CAD_PROD_DATA.DERV_PRTF_PATY_OWN_REL -> STARCADPRODDATA.DERV_PRTF_PATY_OWN_REL */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE PS_CLD_RW.STARCADPRODDATA.DERV_PRTF_PATY_OWN_REL (
 PATY_I STRING NOT NULL COMMENT 'Party Identifier',
 INT_GRUP_I STRING NOT NULL COMMENT 'Interest Group Identifier',
 DERV_PRTF_CATG_C STRING COMMENT 'Derived Portfolio Category Code',
 DERV_PRTF_CLAS_C STRING COMMENT 'Derived Portfolio Class Code',
 DERV_PRTF_TYPE_C STRING COMMENT 'Derived Portfolio Type Code',
 PRTF_PATY_VALD_FROM_D DATE COMMENT 'Portfolio Party Valid From Date',
 PRTF_PATY_VALD_TO_D DATE COMMENT 'Portfolio Party Valid To Date',
 PRTF_PATY_EFFT_D DATE COMMENT 'Portfolio Party Effective Date',
 PRTF_PATY_EXPY_D DATE COMMENT 'Portfolio Party Expiry Date',
 PRTF_OWN_VALD_FROM_D DATE COMMENT 'Portfolio Owner Valid From Date',
 PRTF_OWN_VALD_TO_D DATE COMMENT 'Portfolio Owner Valid To Date',
 PRTF_OWN_EFFT_D DATE COMMENT 'Portfolio Owner Effective Date',
 PRTF_OWN_EXPY_D DATE COMMENT 'Portfolio Owner Expiry Date',
 PTCL_N INT COMMENT 'Point Of Control Number',
 REL_MNGE_I STRING COMMENT 'Relationship Manager Identifier',
 PRTF_CODE_X STRING COMMENT 'Portfolio Code Description',
 DERV_PRTF_ROLE_C STRING COMMENT 'Derived Portfolio Role Code',
 ROLE_PLAY_TYPE_X STRING COMMENT 'Role Player Type Description',
 ROLE_PLAY_I STRING NOT NULL COMMENT 'Role Player Identifier',
 SRCE_SYST_C STRING COMMENT 'Source System Code',
 ROW_SECU_ACCS_C INTEGER NOT NULL COMMENT 'Row Security Access Code'
);