use role ACCOUNTADMIN;
USE DATABASE PS_CLD_RW;

drop schema if exists PS_CLD_RW."pdcbstg";
drop schema if exists PS_CLD_RW.PDCBSTG;
CREATE SCHEMA IF NOT EXISTS PS_CLD_RW.PDCBSTG;

drop schema if exists PS_CLD_RW."pdgrd";
drop schema if exists PS_CLD_RW.PDGRD;
CREATE SCHEMA IF NOT EXISTS PS_CLD_RW.PDGRD;

drop schema if exists PS_CLD_RW."pdrctl";
drop schema if exists PS_CLD_RW.PDRCTL;
CREATE SCHEMA IF NOT EXISTS PS_CLD_RW.PDRCTL;

drop schema if exists PS_CLD_RW."udcrcd";
drop schema if exists PS_CLD_RW.UDCRCD;
CREATE SCHEMA IF NOT EXISTS PS_CLD_RW.UDCRCD;

DROP TABLE IF EXISTS PS_CLD_RW.PDCBSTG.RPC_GRD_PRTF_TYPE_ATTR;
DROP TABLE IF EXISTS PS_CLD_RW.PDRCTL.MAP_SAP_INT_GRUP;
DROP TABLE IF EXISTS PS_CLD_RW.PDRCTL.TYPE_INT_GRUP;
DROP TABLE IF EXISTS PS_CLD_RW.UDCRCD.REF_CALENDAR;
DROP TABLE IF EXISTS PS_CLD_RW.PDGRD.DIMN_NODE_ASSC;
DROP TABLE IF EXISTS PS_CLD_RW.PDCBSTG.RPC_GRD_PRTF_CATG_ATTR;


/* PDCBSTG.RPC_GRD_PRTF_TYPE_ATTR -> PDCBSTG.RPC_GRD_PRTF_TYPE_ATTR */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE PS_CLD_RW.PDCBSTG.RPC_GRD_PRTF_TYPE_ATTR (
 SAP_C STRING,
 PRTF_TYPE_C STRING,
 EXPY_D DATE COMMENT 'EXPIRY DATE'
);

/* PDRCTL.MAP_SAP_INT_GRUP -> PDRCTL.MAP_SAP_INT_GRUP */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE PS_CLD_RW.PDRCTL.MAP_SAP_INT_GRUP (
 EFFT_D DATE,
 EXPY_D DATE,
 BUSN_PTNR_GRUP_TYPE STRING,
 INT_GRUP_TYPE_C STRING
);

/* PDRCTL.TYPE_INT_GRUP -> PDRCTL.TYPE_INT_GRUP */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE PS_CLD_RW.PDRCTL.TYPE_INT_GRUP (
 EFFT_D DATE,
 EXPY_D DATE,
 INT_GRUP_TYPE_C STRING,
 INT_GRUP_TYPE_M STRING
);

/* UDCRCD.REF_CALENDAR -> UDCRCD.REF_CALENDAR */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE PS_CLD_RW.UDCRCD.REF_CALENDAR (
 CALENDAR_DATE DATE,
 CALENDAR_DATE_DESC STRING,
 DAY_OF_MONTH_NBR INT,
 DAY_OF_WEEK_NBR INT,
 DAY_OF_WEEK_DESC STRING,
 DAY_OF_YEAR_NBR INT,
 WEEK_OF_YEAR_NBR INT,
 MONTH_NBR INT,
 MONTH_DESC STRING,
 QUARTER_NBR INT,
 QUARTER_DESC STRING,
 YEAR_NBR INT,
 WEEKEND_IND STRING
);

/* PDGRD.DIMN_NODE_ASSC -> PDGRD.DIMN_NODE_ASSC */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE PS_CLD_RW.PDGRD.DIMN_NODE_ASSC (
 CLAS_SCHM_1_C STRING,
 CLAS_SCHM_2_C STRING,
 DIMN_NODE_1_C STRING,
 DIMN_NODE_2_C STRING,
 DIMN_NODE_ASSC_TYPE_C STRING,
 EFFT_D DATE,
 EXPY_D DATE,
 BUSN_EFFT_D DATE,
 BUSN_EXPY_D DATE
);

/* PDCBSTG.RPC_GRD_PRTF_CATG_ATTR -> PDCBSTG.RPC_GRD_PRTF_CATG_ATTR */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE PS_CLD_RW.PDCBSTG.RPC_GRD_PRTF_CATG_ATTR (
 SAP_C STRING,
 PRTF_CATG_C STRING,
 EXPY_D DATE COMMENT 'EXPIRY DATE'
);
