-- DDLs for tables required by PVTECH.GRD_PRTF_TYPE_ENHC view
-- Extracted from CBA_GDW_DDL_Extracts

-- PDCBSTG.RPC_GRD_PRTF_TYPE_ATTR from DDL extract

-- PDRCTL.MAP_SAP_INT_GRUP from DDL extract

-- PDRCTL.TYPE_INT_GRUP from DDL extract

-- UDCRCD.REF_CALENDAR from DDL extract

-- PDGRD.DIMN_NODE_ASSC from DDL extract

-- PDCBSTG.RPC_GRD_PRTF_CATG_ATTR from DDL extract

/* <sc-table> PDCBSTG.RPC_GRD_PRTF_TYPE_ATTR </sc-table> */
CREATE MULTISET TABLE PDCBSTG.RPC_GRD_PRTF_TYPE_ATTR ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      SAP_C VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      PRTF_TYPE_C VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      EXPY_D DATE FORMAT 'YYYY-MM-DD' TITLE 'EXPIRY DATE')
PRIMARY INDEX ( SAP_C );

/* <sc-table> PDRCTL.MAP_SAP_INT_GRUP </sc-table> */
CREATE SET TABLE PDRCTL.MAP_SAP_INT_GRUP ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      BUSN_PTNR_GRUP_Type CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Business Partner Group Type' NOT NULL,
      INT_GRUP_TYPE_C CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Interest Group Type Code',
      EFFT_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Effective Date' NOT NULL,
      EXPY_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Expiry Date' NOT NULL DEFAULT DATE '9999-12-31' COMPRESS (DATE '9999-12-31'))
PRIMARY INDEX XIE1MAP_SAP_INT_GRUP ( BUSN_PTNR_GRUP_Type );

/* <sc-table> PDRCTL.TYPE_INT_GRUP </sc-table> */
CREATE SET TABLE PDRCTL.TYPE_INT_GRUP ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      INT_GRUP_TYPE_C CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Event Group Type Code' NOT NULL,
      EFFT_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Effective Date' NOT NULL,
      INT_GRUP_TYPE_M VARCHAR(40) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Event Group Type Name',
      INT_GRUP_TYPE_X VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Event Group Type Description',
      EXPY_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Expiry Date' NOT NULL)
PRIMARY INDEX XIE1TYPE_INT_GRUP ( INT_GRUP_TYPE_C );

/* <sc-table> UDCRCD.REF_CALENDAR </sc-table> */
CREATE SET TABLE UDCRCD.REF_CALENDAR ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      CALENDAR_DATE DATE FORMAT 'YYYY-MM-DD' NOT NULL,
      DAY_OF_WEEK INTEGER COMPRESS (1 ,2 ,3 ,4 ,5 ,6 ,7 ),
      DAY_OF_MONTH INTEGER,
      DAY_OF_YEAR INTEGER,
      DAY_OF_CALENDAR INTEGER,
      WEEKDAY_OF_MONTH INTEGER COMPRESS (1 ,2 ,3 ,4 ,5 ),
      WEEK_OF_MONTH INTEGER COMPRESS (0 ,1 ,2 ,3 ,4 ,5 ),
      WEEK_OF_YEAR INTEGER,
      WEEK_OF_CALENDAR INTEGER,
      MONTH_OF_QUARTER INTEGER COMPRESS (1 ,2 ,3 ),
      MONTH_OF_YEAR INTEGER COMPRESS (1 ,2 ,3 ,4 ,5 ,6 ,7 ,8 ,9 ,10 ,11 ,12 ),
      MONTH_OF_CALENDAR INTEGER,
      QUARTER_OF_YEAR INTEGER COMPRESS (1 ,2 ,3 ,4 ),
      QUARTER_OF_CALENDAR INTEGER,
      YEAR_OF_CALENDAR INTEGER,
      YEAR_MNTH_N INTEGER,
      PREV_YEAR_MNTH_N INTEGER,
      MMM CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ('APR','AUG','DEC','FEB','JAN','JUL','JUN','MAR','MAY','NOV','OCT','SEP'),
      MMMYY CHAR(6) CHARACTER SET LATIN NOT CASESPECIFIC,
      MONTH_START DATE FORMAT 'YYYY-MM-DD',
      MONTH_END DATE FORMAT 'YYYY-MM-DD',
      WEEK_BEGINNING DATE FORMAT 'YYYY-MM-DD',
      WEEK_ENDING DATE FORMAT 'YYYY-MM-DD',
      YEAR_N INTEGER,
      WORK_DATE_F INTEGER COMPRESS (0 ,1 ),
      FIN_YEAR CHAR(9) CHARACTER SET LATIN NOT CASESPECIFIC,
      DAILY_F BYTEINT)
UNIQUE PRIMARY INDEX ( CALENDAR_DATE );

/* <sc-table> PDGRD.DIMN_NODE_ASSC </sc-table> */
CREATE SET TABLE PDGRD.DIMN_NODE_ASSC ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      CLAS_SCHM_1_C VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Classification Scheme Code' NOT NULL,
      DIMN_NODE_1_C VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Dimension Node 1 Code' NOT NULL,
      CLAS_SCHM_2_C VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Classification Scheme Code' NOT NULL,
      DIMN_NODE_2_C VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Dimension Node 2 Code' NOT NULL,
      BUSN_EFFT_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Business Effective Date' NOT NULL,
      DIMN_NODE_ASSC_TYPE_C VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Dimension Node Association Type Code' NOT NULL,
      BUSN_EXPY_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Business Expiry Date',
      DSPL_SEQN_N SMALLINT TITLE 'Display Sequence Number',
      DIMN_NODE_ASSC_X VARCHAR(3000) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Dimension Node Association Description',
      NUMC_VALU_Q DECIMAL(15,6) TITLE 'Numeric Value Quantity',
      TEXT_VALU_X VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Text Value Description',
      DATE_VALU_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Date Value Date',
      CLAS_SCHM_3_C VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Classification Scheme Code',
      DIMN_NODE_3_C VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Dimension Node Code',
      CLAS_SCHM_4_C VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Classification Scheme Code',
      DIMN_NODE_4_C VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Dimension Node Code',
      CLAS_SCHM_5_C VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Classification Scheme Code',
      DIMN_NODE_5_C VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Dimension Node Code',
      CLAS_SCHM_6_C VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Classification Scheme Code',
      DIMN_NODE_6_C VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Dimension Node Code',
      CLAS_SCHM_7_C VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Classification Scheme Code',
      DIMN_NODE_7_C VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Dimension Node Code',
      CLAS_SCHM_8_C VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Classification Scheme Code',
      DIMN_NODE_8_C VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Dimension Node Code',
      EFFT_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Effective Date' NOT NULL,
      EXPY_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Expiry Date' NOT NULL DEFAULT DATE '9999-12-31' COMPRESS (DATE '9999-12-31'),
      CLAS_SCHM_9_C VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Classification Scheme Code',
      DIMN_NODE_9_C VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Dimension Node Code',
      CLAS_SCHM_10_C VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Classification Scheme Code',
      DIMN_NODE_10_C VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Dimension Node Code',
      CLAS_SCHM_11_C VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Classification Scheme Code',
      DIMN_NODE_11_C VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Dimension Node Code',
      CLAS_SCHM_12_C VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Classification Scheme Code',
      DIMN_NODE_12_C VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Dimension Node Code',
      CLAS_SCHM_13_C VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Classification Scheme Code',
      DIMN_NODE_13_C VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Dimension Node Code',
      CLAS_SCHM_14_C VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Classification Scheme Code',
      DIMN_NODE_14_C VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Dimension Node Code',
      CLAS_SCHM_15_C VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Classification Scheme Code',
      DIMN_NODE_15_C VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Dimension Node Code',
      NUMC_VALU_1_Q DECIMAL(15,6) TITLE 'Numeric Value Quantity' COMPRESS ,
      NUMC_VALU_2_Q DECIMAL(15,6) TITLE 'Numeric Value Quantity' COMPRESS ,
      NUMC_VALU_3_Q DECIMAL(15,6) TITLE 'Numeric Value Quantity' COMPRESS ,
      NUMC_VALU_4_Q DECIMAL(15,6) TITLE 'Numeric Value Quantity' COMPRESS ,
      NUMC_VALU_5_Q DECIMAL(15,6) TITLE 'Numeric Value Quantity' COMPRESS ,
      TEXT_VALU_1_X VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Text Value Description',
      TEXT_VALU_2_X VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Text Value Description',
      TEXT_VALU_3_X VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Text Value Description',
      TEXT_VALU_4_X VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Text Value Description',
      TEXT_VALU_5_X VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Text Value Description',
      DATE_VALU_1_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Date Value Date' DEFAULT NULL  COMPRESS ,
      DATE_VALU_2_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Date Value Date' DEFAULT NULL  COMPRESS ,
      DATE_VALU_3_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Date Value Date' DEFAULT NULL  COMPRESS ,
      DATE_VALU_4_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Date Value Date' DEFAULT NULL  COMPRESS ,
      DATE_VALU_5_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Date Value Date' DEFAULT NULL  COMPRESS )
PRIMARY INDEX XIE1DIMN_NODE_ASSC ( DIMN_NODE_1_C );

/* <sc-table> PDCBSTG.RPC_GRD_PRTF_CATG_ATTR </sc-table> */
CREATE MULTISET TABLE PDCBSTG.RPC_GRD_PRTF_CATG_ATTR ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      SAP_C VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      PRTF_CATG_C VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      EXPY_D DATE FORMAT 'YYYY-MM-DD' TITLE 'EXPIRY DATE')
PRIMARY INDEX ( SAP_C );
