-- DDLs for tables required by PVTECH.GRD_PRTF_TYPE_ENHC view
-- Extracted from CBA_GDW_DDL_Extracts

-- PDCBSTG.RPC_GRD_PRTF_TYPE_ATTR -> PDCBSTG.RPC_GRD_PRTF_TYPE_ATTR
/* <sc-table> PDCBSTG.RPC_GRD_PRTF_TYPE_ATTR </sc-table> */
CREATE MULTISET TABLE PDCBSTG.RPC_GRD_PRTF_TYPE_ATTR ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      SAP_C VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      PRTF_TYPE_C VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      EXPY_D DATE FORMAT 'YYYY-MM-DD' TITLE 'EXPIRY DATE')
PRIMARY INDEX ( SAP_C );

-- PDRCTL.MAP_SAP_INT_GRUP -> PDRCTL.MAP_SAP_INT_GRUP
/* <sc-table> PDRCTL.MAP_SAP_INT_GRUP </sc-table> */
CREATE SET TABLE PDRCTL.MAP_SAP_INT_GRUP ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      EFFT_D DATE FORMAT 'YYYY-MM-DD',
      EXPY_D DATE FORMAT 'YYYY-MM-DD',
      BUSN_PTNR_GRUP_TYPE CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC,
      INT_GRUP_TYPE_C CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC)
PRIMARY INDEX ( BUSN_PTNR_GRUP_TYPE );

-- PDRCTL.TYPE_INT_GRUP -> PDRCTL.TYPE_INT_GRUP
/* <sc-table> PDRCTL.TYPE_INT_GRUP </sc-table> */
CREATE SET TABLE PDRCTL.TYPE_INT_GRUP ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      EFFT_D DATE FORMAT 'YYYY-MM-DD',
      EXPY_D DATE FORMAT 'YYYY-MM-DD',
      INT_GRUP_TYPE_C CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC,
      INT_GRUP_TYPE_M VARCHAR(80) CHARACTER SET LATIN NOT CASESPECIFIC)
PRIMARY INDEX ( INT_GRUP_TYPE_C );

-- UDCRCD.REF_CALENDAR -> UDCRCD.REF_CALENDAR
/* <sc-table> UDCRCD.REF_CALENDAR </sc-table> */
CREATE SET TABLE UDCRCD.REF_CALENDAR ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      CALENDAR_DATE DATE FORMAT 'YYYY-MM-DD',
      CALENDAR_DATE_DESC VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC,
      DAY_OF_MONTH_NBR SMALLINT,
      DAY_OF_WEEK_NBR SMALLINT,
      DAY_OF_WEEK_DESC VARCHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC,
      DAY_OF_YEAR_NBR SMALLINT,
      WEEK_OF_YEAR_NBR SMALLINT,
      MONTH_NBR SMALLINT,
      MONTH_DESC VARCHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC,
      QUARTER_NBR SMALLINT,
      QUARTER_DESC VARCHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC,
      YEAR_NBR SMALLINT,
      WEEKEND_IND CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC)
PRIMARY INDEX ( CALENDAR_DATE );

-- PDGRD.DIMN_NODE_ASSC -> PDGRD.DIMN_NODE_ASSC
/* <sc-table> PDGRD.DIMN_NODE_ASSC </sc-table> */
CREATE MULTISET TABLE PDGRD.DIMN_NODE_ASSC ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      CLAS_SCHM_1_C VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      CLAS_SCHM_2_C VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      DIMN_NODE_1_C VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      DIMN_NODE_2_C VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      DIMN_NODE_ASSC_TYPE_C VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      EFFT_D DATE FORMAT 'yyyy-mm-dd',
      EXPY_D DATE FORMAT 'yyyy-mm-dd',
      BUSN_EFFT_D DATE FORMAT 'yyyy-mm-dd',
      BUSN_EXPY_D DATE FORMAT 'yyyy-mm-dd')
PRIMARY INDEX ( CLAS_SCHM_1_C ,CLAS_SCHM_2_C ,DIMN_NODE_1_C ,DIMN_NODE_2_C ,DIMN_NODE_ASSC_TYPE_C );

-- PDCBSTG.RPC_GRD_PRTF_CATG_ATTR -> PDCBSTG.RPC_GRD_PRTF_CATG_ATTR
/* <sc-table> PDCBSTG.RPC_GRD_PRTF_CATG_ATTR </sc-table> */
CREATE MULTISET TABLE PDCBSTG.RPC_GRD_PRTF_CATG_ATTR ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      SAP_C VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      PRTF_CATG_C VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      EXPY_D DATE FORMAT 'YYYY-MM-DD' TITLE 'EXPIRY DATE')
PRIMARY INDEX ( SAP_C ); 