use role ACCOUNTADMIN;
USE DATABASE PS_CLD_RW;

drop schema if exists PS_CLD_RW."star_cad_prod_data";
drop schema if exists PS_CLD_RW.STAR_CAD_PROD_DATA;
CREATE SCHEMA IF NOT EXISTS PS_CLD_RW.STAR_CAD_PROD_DATA;

DROP TABLE IF EXISTS PS_CLD_RW.STAR_CAD_PROD_DATA.ACCT_BALN;


/* STAR_CAD_PROD_DATA.ACCT_BALN -> STAR_CAD_PROD_DATA.ACCT_BALN */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE PS_CLD_RW.STARCADPRODDATA.ACCT_BALN (
 ACCT_I STRING NOT NULL COMMENT 'Account Identifier',
 BALN_TYPE_C STRING NOT NULL COMMENT 'Balance Type Code',
 CALC_FUNC_C STRING NOT NULL COMMENT 'Calculation Function Code',
 TIME_PERD_C STRING NOT NULL COMMENT 'Time Period Code',
 EFFT_D DATE NOT NULL COMMENT 'Effective Date',
 EXPY_D DATE NOT NULL COMMENT 'Expire Date',
 BALN_A DECIMAL(23,5) COMMENT 'Balance Amount',
 CALC_F STRING NOT NULL COMMENT 'Calculate Flag',
 PROS_KEY_EFFT_I DECIMAL(10,0) COMMENT 'Process Key Effective Identifier',
 PROS_KEY_EXPY_I DECIMAL(10,0) COMMENT 'Process Key Expire Identifier',
 EROR_SEQN_I DECIMAL(10,0) COMMENT 'Error Sequence Identifier',
 CNCY_C STRING COMMENT 'Currency Code',
 SRCE_SYST_C STRING COMMENT 'Source System Code',
 ROW_SECU_ACCS_C INTEGER NOT NULL COMMENT 'Row Security Access Code'
);
