-- DDL for STAR_CAD_PROD_DATA.ACCT_BALN table
-- Extracted from CBA_GDW_DDL_Extracts

-- STAR_CAD_PROD_DATA.ACCT_BALN -> STAR_CAD_PROD_DATA.ACCT_BALN
/* <sc-table> STAR_CAD_PROD_DATA.ACCT_BALN </sc-table> */
CREATE SET TABLE STAR_CAD_PROD_DATA.ACCT_BALN ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      ACCT_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Account Identifier' NOT NULL,
      BALN_TYPE_C CHAR(5) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Balance Type Code' NOT NULL COMPRESS 'BALN ',
      CALC_FUNC_C CHAR(5) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Calculation Function Code' NOT NULL COMPRESS 'SPOT ',
      TIME_PERD_C CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Time Period Code' NOT NULL COMPRESS 'E',
      EFFT_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Effective Date' NOT NULL,
      EXPY_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Expire Date' NOT NULL DEFAULT DATE '9999-12-31' COMPRESS (DATE '9999-12-31'),
      BALN_A DECIMAL(23,5) TITLE 'Balance Amount' COMPRESS 0.00000 ,
      CALC_F CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Calculate Flag' NOT NULL DEFAULT 'N' COMPRESS 'N',
      PROS_KEY_EFFT_I DECIMAL(10,0) TITLE 'Process Key Effective Identifier',
      PROS_KEY_EXPY_I DECIMAL(10,0) TITLE 'Process Key Expire Identifier' COMPRESS ,
      EROR_SEQN_I DECIMAL(10,0) TITLE 'Error Sequence Identifier' COMPRESS 0. ,
      CNCY_C CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Currency Code' DEFAULT NULL  COMPRESS ('AUD','EUR','USD'),
      SRCE_SYST_C CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Source System Code' DEFAULT NULL  COMPRESS 'WSS',
      ROW_SECU_ACCS_C INTEGER TITLE 'Row Security Access Code' NOT NULL DEFAULT 0  COMPRESS 0 )
PRIMARY INDEX XIE1ACCT_BALN ( ACCT_I );
