{{ config(materialized='view', tags=['XfmDelFlagAPPT_REL']) }}

WITH XfmProsKey AS (
	SELECT
		DELETED_TABLE_NAME,
		{{ ref('SrcAppRelDS') }}.DELETED_KEY_1_VALUE AS APP_PROD_ID,
		DELETED_KEY_2_VALUE,
		-- *SRC*: \(20)If OutAppRelDS.DELETED_TABLE_NAME = 'CCL_HL_APP' Then 'CSE_CCL_BUS_HL_APP_APPT_REL' Else ( If OutAppRelDS.DELETED_TABLE_NAME = 'CCL_APP_LINK' Then 'CSE_CCL_APP_LINK_APPT_REL' Else ''),
		IFF({{ ref('SrcAppRelDS') }}.DELETED_TABLE_NAME = 'CCL_HL_APP', 'CSE_CCL_BUS_HL_APP_APPT_REL', IFF({{ ref('SrcAppRelDS') }}.DELETED_TABLE_NAME = 'CCL_APP_LINK', 'CSE_CCL_APP_LINK_APPT_REL', '')) AS CONV_M
	FROM {{ ref('SrcAppRelDS') }}
	WHERE 
)

SELECT * FROM XfmProsKey