{{ config(materialized='view', tags=['DltAppt_Pdct_RpayFrmTMP']) }}

WITH RmvdupFrmTrans AS (
	SELECT APPT_PDCT_I, RPAY_TYPE_C, EFFT_D, PAYT_FREQ_C, STRT_RPAY_D, EXPY_D, PROS_KEY_EFFT_I, PROS_KEY_EXPY_I, EROR_SEQN_I, SRCE_SYST_C, RPAY_SRCE_C, RPAY_SRCE_OTHR_X 
	FROM (
		SELECT APPT_PDCT_I, RPAY_TYPE_C, EFFT_D, PAYT_FREQ_C, STRT_RPAY_D, EXPY_D, PROS_KEY_EFFT_I, PROS_KEY_EXPY_I, EROR_SEQN_I, SRCE_SYST_C, RPAY_SRCE_C, RPAY_SRCE_OTHR_X,
		 ROW_NUMBER() OVER (PARTITION BY APPT_PDCT_I, SRCE_SYST_C, PAYT_FREQ_C, RPAY_TYPE_C, RPAY_SRCE_OTHR_X, STRT_RPAY_D, RPAY_SRCE_C ORDER BY 1 ASC) AS ROW_NUM 
		FROM {{ ref('Update__Appt_Pdct_Rpay_Ins') }}
	) AS RmvdupFrmTrans_TEMP
	WHERE ROW_NUM = 1
)

SELECT * FROM RmvdupFrmTrans