{{ config(materialized='view', tags=['XfmDelFlagAPPT_PDCT_REL']) }}

WITH XfmProsKey AS (
	SELECT
		{{ ref('TMP_DELETED') }}.DLTD_TABL_NAME AS DELETED_TABLE_NAME,
		{{ ref('TMP_DELETED') }}.DLTD_KEY1_VALU AS APP_PROD_ID,
		-- *SRC*: \(20)If OutJoin.DLTD_TABL_NAME = 'CCL_APP_PROD' Then 'CSE_CCL_BUS_APP_PROD_APPT_PDCT_REL' Else ( If OutJoin.DLTD_TABL_NAME = 'HL_APP_PROD' OR OutJoin.DLTD_TABL_NAME = 'PL_APP_PROD' Then 'CSE_GDW_APPT_PDCT_APPT_PDCT_REL' Else ''),
		IFF({{ ref('TMP_DELETED') }}.DLTD_TABL_NAME = 'CCL_APP_PROD', 'CSE_CCL_BUS_APP_PROD_APPT_PDCT_REL', IFF({{ ref('TMP_DELETED') }}.DLTD_TABL_NAME = 'HL_APP_PROD' OR {{ ref('TMP_DELETED') }}.DLTD_TABL_NAME = 'PL_APP_PROD', 'CSE_GDW_APPT_PDCT_APPT_PDCT_REL', '')) AS CONV_M,
		RELD_APPT_PDCT_I,
		APPT_PDCT_I
	FROM {{ ref('TMP_DELETED') }}
	WHERE 
)

SELECT * FROM XfmProsKey