{{ config(materialized='view', tags=['XfmAppt_Pdct']) }}

WITH Xfm__To_TgtApptPdct AS (
	SELECT
		-- *SRC*: \(20)If IsNull(ToXfm.PO_OVERDRAFT_CAT_ID) Then 'Y' Else  if Trim(ToXfm.PO_OVERDRAFT_CAT_ID) = '0' Then 'Y' Else  if ( IF IsNotNull((ToXfm.PO_OVERDRAFT_CAT_ID)) THEN (ToXfm.PO_OVERDRAFT_CAT_ID) ELSE "") = '' Then 'Y' Else 'N',
		IFF({{ ref('FnlToXfm') }}.PO_OVERDRAFT_CAT_ID IS NULL, 'Y', IFF(TRIM({{ ref('FnlToXfm') }}.PO_OVERDRAFT_CAT_ID) = '0', 'Y', IFF(IFF({{ ref('FnlToXfm') }}.PO_OVERDRAFT_CAT_ID IS NOT NULL, {{ ref('FnlToXfm') }}.PO_OVERDRAFT_CAT_ID, '') = '', 'Y', 'N'))) AS svIsNullPoOverdraftCatId,
		-- *SRC*: \(20)If IsNull(ToXfm.APPT_PDCT_CATG_C) OR Trim(( IF IsNotNull((ToXfm.APPT_PDCT_CATG_C)) THEN (ToXfm.APPT_PDCT_CATG_C) ELSE "")) = '' Then 'Y' ELSE 'N',
		IFF({{ ref('FnlToXfm') }}.APPT_PDCT_CATG_C IS NULL OR TRIM(IFF({{ ref('FnlToXfm') }}.APPT_PDCT_CATG_C IS NOT NULL, {{ ref('FnlToXfm') }}.APPT_PDCT_CATG_C, '')) = '', 'Y', 'N') AS svIsNullApptPdctCatgC,
		-- *SRC*: \(20)If IsNull(ToXfm.APPT_PDCT_DURT_C) OR Trim(( IF IsNotNull((ToXfm.APPT_PDCT_DURT_C)) THEN (ToXfm.APPT_PDCT_DURT_C) ELSE "")) = '' Then 'Y' ELSE 'N',
		IFF({{ ref('FnlToXfm') }}.APPT_PDCT_DURT_C IS NULL OR TRIM(IFF({{ ref('FnlToXfm') }}.APPT_PDCT_DURT_C IS NOT NULL, {{ ref('FnlToXfm') }}.APPT_PDCT_DURT_C, '')) = '', 'Y', 'N') AS svIsNullApptPdctDurtC,
		-- *SRC*: \(20)If IsNull(ToXfm.APP_PROD_ID) Then 'Y' Else  if Trim(ToXfm.APP_PROD_ID) = '0' Then 'Y' Else  if ( IF IsNotNull((ToXfm.APP_PROD_ID)) THEN (ToXfm.APP_PROD_ID) ELSE "") = '' Then 'Y' Else 'N',
		IFF({{ ref('FnlToXfm') }}.APP_PROD_ID IS NULL, 'Y', IFF(TRIM({{ ref('FnlToXfm') }}.APP_PROD_ID) = '0', 'Y', IFF(IFF({{ ref('FnlToXfm') }}.APP_PROD_ID IS NOT NULL, {{ ref('FnlToXfm') }}.APP_PROD_ID, '') = '', 'Y', 'N'))) AS svIsNullAppProdId,
		-- *SRC*: "CSEPO" : Trim(ToXfm.APP_PROD_ID),
		CONCAT('CSEPO', TRIM({{ ref('FnlToXfm') }}.APP_PROD_ID)) AS APPT_PDCT_I,
		-- *SRC*: SetNull(),
		SETNULL() AS DEBT_ABN_X,
		-- *SRC*: SetNull(),
		SETNULL() AS DEBT_BUSN_M,
		-- *SRC*: SetNull(),
		SETNULL() AS SMPL_APPT_F,
		-- *SRC*: SetNull(),
		SETNULL() AS CLP_JOB_FAMILY_CAT_ID,
		'PO' AS APPT_QLFY_C,
		-- *SRC*: SetNull(),
		SETNULL() AS ACQR_TYPE_C,
		-- *SRC*: SetNull(),
		SETNULL() AS ACQR_ADHC_X,
		-- *SRC*: SetNull(),
		SETNULL() AS ACQR_SRCE_C,
		PDCT_N,
		-- *SRC*: "CSEPO" : Trim(ToXfm.APP_ID),
		CONCAT('CSEPO', TRIM({{ ref('FnlToXfm') }}.APP_ID)) AS APPT_I,
		'CSE' AS SRCE_SYST_C,
		{{ ref('FnlToXfm') }}.APP_PROD_ID AS SRCE_SYST_APPT_PDCT_I,
		-- *SRC*: SetNull(),
		SETNULL() AS LOAN_FNDD_METH_C,
		'N' AS NEW_ACCT_F,
		-- *SRC*: SetNull(),
		SETNULL() AS BROK_PATY_I,
		'N' AS COPY_FROM_OTHR_APPT_F,
		-- *SRC*: StringToDate(Trim(pRUN_STRM_PROS_D[1, 4]) : '-' : Trim(pRUN_STRM_PROS_D[5, 2]) : '-' : Trim(pRUN_STRM_PROS_D[7, 2]), "%yyyy-%mm-%dd"),
		STRINGTODATE(CONCAT(CONCAT(CONCAT(CONCAT(TRIM(SUBSTRING(pRUN_STRM_PROS_D, 1, 4)), '-'), TRIM(SUBSTRING(pRUN_STRM_PROS_D, 5, 2))), '-'), TRIM(SUBSTRING(pRUN_STRM_PROS_D, 7, 2))), '%yyyy-%mm-%dd') AS EFFT_D,
		'9999-12-31' AS EXPY_D,
		pGDW_PROS_ID AS PROS_KEY_EFFT_I,
		-- *SRC*: SetNull(),
		SETNULL() AS PROS_KEY_EXPY_I,
		-- *SRC*: SetNull(),
		SETNULL() AS EROR_SEQN_I,
		pRUN_STRM_C AS RUN_STRM,
		-- *SRC*: \(20)If svIsNullPoOverdraftCatId = 'Y' Then SetNull() Else  if svIsNullApptPdctCatgC = 'Y' Then '9999' Else ToXfm.APPT_PDCT_CATG_C,
		IFF(svIsNullPoOverdraftCatId = 'Y', SETNULL(), IFF(svIsNullApptPdctCatgC = 'Y', '9999', {{ ref('FnlToXfm') }}.APPT_PDCT_CATG_C)) AS APPT_PDCT_CATG_C,
		-- *SRC*: \(20)If svIsNullPoOverdraftCatId = 'Y' Then SetNull() Else  If svIsNullApptPdctDurtC = 'Y' Then '9999' Else ToXfm.APPT_PDCT_DURT_C,
		IFF(svIsNullPoOverdraftCatId = 'Y', SETNULL(), IFF(svIsNullApptPdctDurtC = 'Y', '9999', {{ ref('FnlToXfm') }}.APPT_PDCT_DURT_C)) AS APPT_PDCT_DURT_C,
		-- *SRC*: SetNull(),
		SETNULL() AS ASES_D
	FROM {{ ref('FnlToXfm') }}
	WHERE svIsNullAppProdId = 'N'
)

SELECT * FROM Xfm__To_TgtApptPdct