{{ config(materialized='view', tags=['LdREJT_CCC_BUS_APP_PROD']) }}

WITH FunCCAppProdIdNulls AS (
	SELECT
		CC_APP_PROD_ID as CC_APP_PROD_ID,
		REQUESTED_LIMIT_AMT as REQUESTED_LIMIT_AMT,
		CC_INTEREST_OPT_CAT_ID as CC_INTEREST_OPT_CAT_ID,
		CBA_HOMELOAN_NO as CBA_HOMELOAN_NO,
		PRE_APPRV_AMOUNT as PRE_APPRV_AMOUNT,
		ETL_D as ETL_D,
		ORIG_ETL_D as ORIG_ETL_D,
		EROR_C as EROR_C,
		READ_COSTS_AND_RISKS_FLAG as READ_COSTS_AND_RISKS_FLAG,
		ACCEPTS_COSTS_AND_RISKS_DATE as ACCEPTS_COSTS_AND_RISKS_DATE
	FROM {{ ref('SrcRejCCAppProdIdNullsDS') }}
	UNION ALL
	SELECT
		CC_APP_PROD_ID,
		REQUESTED_LIMIT_AMT,
		CC_INTEREST_OPT_CAT_ID,
		CBA_HOMELOAN_NO,
		PRE_APPRV_AMOUNT,
		ETL_D,
		ORIG_ETL_D,
		READ_COSTS_AND_RISKS_FLAG,
		ACCEPTS_COSTS_AND_RISKS_DATE,
		EROR_C
	FROM {{ ref('SrcCCAppProdRejectsDS') }}
)

SELECT * FROM FunCCAppProdIdNulls