# GDW1 DataStage to dbt Migration Project
# Based on CSEL4 CPL Business Application Data Flow

name: 'gdw1_csel4_migration'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'ccods_gdw1'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations
models:
  gdw1_csel4_migration:
    # Global default
    +materialized: view

    # Stream: CSEL4
    csel4:
      +tags: [csel4]
      intermediate:
        +materialized: view
        +schema: csel4_int
      reference:
        +materialized: table
        +schema: csel4_ref
      marts:
        +materialized: table
        +schema: csel4_mart
        +on_schema_change: fail

    # Stream: CCODS
    ccods:
      +tags: [ccods]
      intermediate:
        +materialized: view
        +schema: ccods_int
      marts:
        +materialized: table
        +schema: ccods_mart
        +on_schema_change: fail
      
# Variable definitions (matching DataStage parameters)
vars:
  # Default null value from DataStage
  default_null_value: '0x0'
  
  # Audit user
  audit_user: 'ETL'
  
  # Run stream name
  run_stream: 'CSE_CPL_BUS_APP'
  
  # Database and schema references
  staging_database: 'ps_cld_rw'
  staging_schema: 'stg'
  reference_database: 'ps_cld_rw'
  reference_schema: 'starcadproddata'
  target_database: 'ps_cld_rw'
  dcf_database: 'psund_migr_dcf'
  dcf_schema: 'p_d_dcf_001_std_0'