{{ config(materialized='view', tags=['XfmCSE_CCL_BUS_APP_FEEFrmExt']) }}

WITH UpperCaseCol AS (
	SELECT
		CCL_APP_FEE_ID,
		CCL_APP_FEE_CCL_APP_ID,
		CCL_APP_FEE_CCL_APP_PROD_ID,
		CCL_APP_FEE_CHARGE_AMT,
		CCL_APP_FEE_CHARGE_DATE,
		CCL_APP_FEE_CONCESSION_FLAG,
		CCL_APP_FEE_CONCESSION_REASON,
		CCL_APP_FEE_OVERRIDE_FEE_PCT,
		-- *SRC*: \(20)if IsNull(OutColumnGenerator.CCL_APP_FEE_OVERRIDE_FEE_PCT_FREQ) then SetNull() else UpCase(OutColumnGenerator.CCL_APP_FEE_OVERRIDE_FEE_PCT_FREQ),
		IFF({{ ref('AddColMapType') }}.CCL_APP_FEE_OVERRIDE_FEE_PCT_FREQ IS NULL, SETNULL(), UPPER({{ ref('AddColMapType') }}.CCL_APP_FEE_OVERRIDE_FEE_PCT_FREQ)) AS OVRD_FEE_PCT_FREQ,
		CCL_APP_FEE_FEE_REPAYMENT_FREQ,
		CCL_APP_FEE_TYPE_CAT_ID,
		CCL_APP_FEE_CHARGE_EXTERNAL_FLAG,
		{{ ref('AddColMapType') }}.CCL_FEE_TYPE_CAT_ID AS SRCE_NUMC_1_C,
		CCL_FEE_TYPE_CAT_DEFAULT_AMT,
		CCL_FEE_TYPE_CAT_DEFAULT_FEE_PCT,
		CCL_FEE_TYPE_CAT_FEE_TYPE_DESC,
		ORIG_ETL_D,
		MAP_TYPE_C
	FROM {{ ref('AddColMapType') }}
	WHERE 
)

SELECT * FROM UpperCaseCol