{{ config(materialized='view', tags=['ExtCclBusPreprovLog']) }}

WITH 
_cba__app_csel4_sit_inprocess_cse__ccl__bus__preapproval__log__cse__ccl__bus__preapproval__log__20090703 AS (
	SELECT
	*
	FROM {{ source("","_cba__app_csel4_sit_inprocess_cse__ccl__bus__preapproval__log__cse__ccl__bus__preapproval__log__20090703")  }})
SrcCclPreprvlogSeq AS (
	SELECT RECORDTYPE,
		MOD_TIMESTAMP,
		CCL_PREAPPROVAL_LOG_ID,
		CCL_PREAPPROVAL_LOG_VN,
		PREAPPROVAL_CCL_APP_ID,
		SOURCE_CCL_APP_ID,
		OVERDRAFT_INDEX_RATE_PCT,
		BUFFER_RATE_PCT,
		UNSECURED_CAP_MIN_THRESHOLD,
		UNSECURED_CAP_MAX_THRESHOLD,
		WORST_RISK_CRG,
		CRG_MULTIPLIER,
		FORM_MULTIPLIER,
		APP_MULTIPLIER,
		CRG_MAA,
		CRG_HIGH_CAP_THRESHOLD_AMT,
		PREAPPROVAL_AMT,
		PREAPPROVAL_SOURCE_CIF_CODE,
		MOD_CBA_STAFF_NO,
		MOD_CSE_USER_ID,
		SEC_PREAPPR_CRG_MULTIPLIER,
		SEC_FORM_MULTIPLER,
		SECURED_CAP_MAX_ACCF_THRESHOLD,
		EF_CAP_MAX_THRESHOLD,
		TOTAL_PREAPPR_BUFFER_RATE_PCT,
		EF_PREAPPR_BUFFER_RATE_PCT,
		TOTAL_PREAPPROVAL_AMT,
		EF_PREAPPROVAL_AMT,
		SEC_APP_MULTIPLIER,
		SEC_MAA,
		EF_MAA,
		SEC_PREAPPR_HIGHCAP_THRESHOLD,
		EF_PREAPPR_HIGHCAP_THRESHOLD,
		EF_APP_MULTIPLIER,
		EF_FORM_MULTIPLIER,
		EF_CRG_MULTIPLIER,
		MOD_USER_ID
	FROM _cba__app_csel4_sit_inprocess_cse__ccl__bus__preapproval__log__cse__ccl__bus__preapproval__log__20090703
)

SELECT * FROM SrcCclPreprvlogSeq