{{ config(materialized='view', tags=['XfmChlBusFeeDiscFeeFrmExt']) }}

WITH XfmBusinessRules__OutApptPdctFeatDS AS (
	SELECT
		-- *SRC*: Len(Trim(( IF IsNotNull((InXfmBusinessRules.BFD_HL_FEE_DISCOUNT_ID)) THEN (InXfmBusinessRules.BFD_HL_FEE_DISCOUNT_ID) ELSE ""))) > 0,
		LEN(TRIM(IFF({{ ref('ModNullHandling') }}.BFD_HL_FEE_DISCOUNT_ID IS NOT NULL, {{ ref('ModNullHandling') }}.BFD_HL_FEE_DISCOUNT_ID, ''))) > 0 AS svDiscountFeeFlag,
		-- *SRC*: InXfmBusinessRules.BF_FOUND_FLAG = 'Y' AND Len(Trim(( IF IsNotNull((InXfmBusinessRules.SRCE_CHAR_1_C)) THEN (InXfmBusinessRules.SRCE_CHAR_1_C) ELSE ""))) = 0,
		{{ ref('ModNullHandling') }}.BF_FOUND_FLAG = 'Y' AND LEN(TRIM(IFF({{ ref('ModNullHandling') }}.SRCE_CHAR_1_C IS NOT NULL, {{ ref('ModNullHandling') }}.SRCE_CHAR_1_C, ''))) = 0 AS svIgnoreFlag,
		-- *SRC*: \(20)if InXfmBusinessRules.BFD_FOUND_FLAG = 'Y' AND Not(svIgnoreFlag) AND (Len(Trim(( IF IsNotNull((InXfmBusinessRules.BFD_HL_FEE_DISCOUNT_CAT_ID)) THEN (InXfmBusinessRules.BFD_HL_FEE_DISCOUNT_CAT_ID) ELSE ""))) <> 0 AND InXfmBusinessRules.OVRD_REAS_C = '9999') Then 'Y' Else 'N',
		IFF({{ ref('ModNullHandling') }}.BFD_FOUND_FLAG = 'Y' AND Not svIgnoreFlag AND LEN(TRIM(IFF({{ ref('ModNullHandling') }}.BFD_HL_FEE_DISCOUNT_CAT_ID IS NOT NULL, {{ ref('ModNullHandling') }}.BFD_HL_FEE_DISCOUNT_CAT_ID, ''))) <> 0 AND {{ ref('ModNullHandling') }}.OVRD_REAS_C = '9999', 'Y', 'N') AS svErrorOvrdReasC,
		-- *SRC*: \(20)If InXfmBusinessRules.TARG_CHAR_C = "999010" AND InXfmBusinessRules.BF_FOUND_FLAG = "Y" Then "RPR4004" Else  If svErrorOvrdReasC = "Y" Then "RPR4009" Else '',
		IFF({{ ref('ModNullHandling') }}.TARG_CHAR_C = '999010' AND {{ ref('ModNullHandling') }}.BF_FOUND_FLAG = 'Y', 'RPR4004', IFF(svErrorOvrdReasC = 'Y', 'RPR4009', '')) AS svErrorCode,
		-- *SRC*: svErrorCode <> "",
		svErrorCode <> '' AS svRejectFlag,
		-- *SRC*: "CSEHL" : ( IF IsNotNull((InXfmBusinessRules.BF_HL_APP_PROD_ID)) THEN (InXfmBusinessRules.BF_HL_APP_PROD_ID) ELSE (DEFAULT_NULL_VALUE)),
		CONCAT('CSEHL', IFF({{ ref('ModNullHandling') }}.BF_HL_APP_PROD_ID IS NOT NULL, {{ ref('ModNullHandling') }}.BF_HL_APP_PROD_ID, DEFAULT_NULL_VALUE)) AS APPT_PDCT_I,
		{{ ref('ModNullHandling') }}.TARG_CHAR_C AS FEAT_I,
		-- *SRC*: 'HF' : InXfmBusinessRules.HL_FEE_ID,
		CONCAT('HF', {{ ref('ModNullHandling') }}.HL_FEE_ID) AS SRCE_SYST_APPT_FEAT_I,
		-- *SRC*: StringToDate(InXfmBusinessRules.ORIG_ETL_D, "%yyyy%mm%dd"),
		STRINGTODATE({{ ref('ModNullHandling') }}.ORIG_ETL_D, '%yyyy%mm%dd') AS EFFT_D,
		'CSE' AS SRCE_SYST_C,
		{{ ref('ModNullHandling') }}.BFD_HL_FEE_DISCOUNT_ID AS SRCE_SYST_APPT_OVRD_I,
		-- *SRC*: SetNull(),
		SETNULL() AS OVRD_FEAT_I,
		-- *SRC*: SetNull(),
		SETNULL() AS SRCE_SYST_STND_VALU_Q,
		-- *SRC*: SetNull(),
		SETNULL() AS SRCE_SYST_STND_VALU_R,
		{{ ref('ModNullHandling') }}.BF_TOTAL_AMOUNT AS SRCE_SYST_STND_VALU_A,
		'AUD' AS CNCY_C,
		{{ ref('ModNullHandling') }}.BFD_DISCOUNT_TERM AS ACTL_VALU_Q,
		-- *SRC*: SetNull(),
		SETNULL() AS ACTL_VALU_R,
		-- *SRC*: \(20)If Len(Trim(( IF IsNotNull((InXfmBusinessRules.BFD_DISCOUNT_AMT)) THEN (InXfmBusinessRules.BFD_DISCOUNT_AMT) ELSE ""))) = 0 Then InXfmBusinessRules.BF_TOTAL_AMOUNT else InXfmBusinessRules.BFD_DISCOUNT_AMT,
		IFF(LEN(TRIM(IFF({{ ref('ModNullHandling') }}.BFD_DISCOUNT_AMT IS NOT NULL, {{ ref('ModNullHandling') }}.BFD_DISCOUNT_AMT, ''))) = 0, {{ ref('ModNullHandling') }}.BF_TOTAL_AMOUNT, {{ ref('ModNullHandling') }}.BFD_DISCOUNT_AMT) AS ACTL_VALU_A,
		-- *SRC*: StringToDate("99991231", "%yyyy%mm%dd"),
		STRINGTODATE('99991231', '%yyyy%mm%dd') AS EXPY_D,
		-- *SRC*: SetNull(),
		SETNULL() AS FEAT_SEQN_N,
		-- *SRC*: SetNull(),
		SETNULL() AS FEAT_STRT_D,
		-- *SRC*: SetNull(),
		SETNULL() AS FEE_CHRG_D,
		-- *SRC*: \(20)if Len(Trim(( IF IsNotNull((InXfmBusinessRules.BFD_HL_FEE_DISCOUNT_CAT_ID)) THEN (InXfmBusinessRules.BFD_HL_FEE_DISCOUNT_CAT_ID) ELSE ""))) = 0 Then SetNull() Else  If Len(Trim(( IF IsNotNull((InXfmBusinessRules.OVRD_REAS_C)) THEN (InXfmBusinessRules.OVRD_REAS_C) ELSE ""))) = 0 Then '9999' Else InXfmBusinessRules.OVRD_REAS_C,
		IFF(LEN(TRIM(IFF({{ ref('ModNullHandling') }}.BFD_HL_FEE_DISCOUNT_CAT_ID IS NOT NULL, {{ ref('ModNullHandling') }}.BFD_HL_FEE_DISCOUNT_CAT_ID, ''))) = 0, SETNULL(), IFF(LEN(TRIM(IFF({{ ref('ModNullHandling') }}.OVRD_REAS_C IS NOT NULL, {{ ref('ModNullHandling') }}.OVRD_REAS_C, ''))) = 0, '9999', {{ ref('ModNullHandling') }}.OVRD_REAS_C)) AS OVRD_REAS_C,
		'N' AS FEE_ADD_TO_TOTL_F,
		'N' AS FEE_CAPL_F,
		'0' AS PROS_KEY_EFFT_I,
		-- *SRC*: SetNull(),
		SETNULL() AS PROS_KEY_EXPY_I,
		-- *SRC*: SetNull(),
		SETNULL() AS EROR_SEQN_I,
		HL_FEE_ID,
		BF_HL_FEE_ID,
		BF_HL_APP_PROD_ID,
		{{ ref('ModNullHandling') }}.SRCE_CHAR_1_C AS BF_XML_CODE,
		BF_DISPLAY_NAME,
		BF_CATEGORY,
		BF_UNIT_AMOUNT,
		BF_TOTAL_AMOUNT,
		BF_FOUND_FLAG,
		BFD_HL_FEE_DISCOUNT_ID,
		BFD_HL_FEE_ID,
		BFD_DISCOUNT_REASON,
		BFD_DISCOUNT_CODE,
		BFD_DISCOUNT_AMT,
		BFD_DISCOUNT_TERM,
		BFD_HL_FEE_DISCOUNT_CAT_ID,
		BFD_FOUND_FLAG,
		ORIG_ETL_D
	FROM {{ ref('ModNullHandling') }}
	WHERE Not svIgnoreFlag
)

SELECT * FROM XfmBusinessRules__OutApptPdctFeatDS