--
/* <sc-joinindex> BENCHMARK.L_FNCL_TRAN_ACCT_REL_STJI </sc-joinindex> */
CREATE JOIN INDEX BENCHMARK.L_FNCL_TRAN_ACCT_REL_STJI ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT (PTEMP.L_FNCL_TRAN_ACCT_REL.ACCT_IDNN_HK ,PTEMP.L_FNCL_TRAN_ACCT_REL.ROW_SECU_ACCS_C ,
PTEMP.L_FNCL_TRAN_ACCT_REL.MSTR_SRCE_SYST_C ,PTEMP.L_FNCL_TRAN_ACCT_REL.EXPY_D ),
(PTEMP.L_FNCL_TRAN_ACCT_REL.ROWID )
 FROM PTEMP.L_FNCL_TRAN_ACCT_REL 
WHERE PTEMP.L_FNCL_TRAN_ACCT_REL.RECORD_DELETED_FLAG =  0 
PRIMARY INDEX ( ACCT_IDNN_HK )

;

--
/* <sc-joinindex> BENCHMARK.ORD_CUST_IDX </sc-joinindex> */
CREATE JOIN INDEX BENCHMARK.ORD_CUST_IDX ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT BENCHMARK.ORDERS_TBL.O_CUSTKEY ,BENCHMARK.CUSTOMER.C_NAME ,
BENCHMARK.ORDERS_TBL.O_STATUS ,BENCHMARK.ORDERS_TBL.O_DATE ,
BENCHMARK.ORDERS_TBL.O_COMMENT 
 FROM BENCHMARK.ORDERS_TBL ,BENCHMARK.CUSTOMER 
WHERE BENCHMARK.ORDERS_TBL.O_CUSTKEY =  BENCHMARK.CUSTOMER.C_CUSTKEY 
PRIMARY INDEX ( O_CUSTKEY );

--
/* <sc-joinindex> B_B01_J_BAL_001_HST_0.BV_RBS_TRAN_JI </sc-joinindex> */
CREATE JOIN INDEX B_B01_J_BAL_001_HST_0.BV_RBS_TRAN_JI ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT (B_B01_D_BAL_001_HST_0.BV_RBS_TRAN.ACCT_I ),(B_B01_D_BAL_001_HST_0.BV_RBS_TRAN.ROWID )
 FROM B_B01_D_BAL_001_HST_0.BV_RBS_TRAN 
PRIMARY INDEX ( ACCT_I )

;

--
/* <sc-joinindex> B_B01_J_BAL_001_STD_0.BV_RBS_TRAN_HK_JI </sc-joinindex> */
CREATE JOIN INDEX B_B01_J_BAL_001_STD_0.BV_RBS_TRAN_HK_JI ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT (B_B01_D_BAL_001_STD_0.BV_RBS_TRAN.TRAN_IDNN_HK ),(B_B01_D_BAL_001_STD_0.BV_RBS_TRAN.ROWID )
 FROM B_B01_D_BAL_001_STD_0.BV_RBS_TRAN 
PRIMARY INDEX ( TRAN_IDNN_HK )

;

--
/* <sc-joinindex> B_B01_J_BAL_001_STD_0.BV_RBS_TRAN_JI </sc-joinindex> */
CREATE JOIN INDEX B_B01_J_BAL_001_STD_0.BV_RBS_TRAN_JI ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT (B_B01_D_BAL_001_STD_0.BV_RBS_TRAN.ACCT_I ),(B_B01_D_BAL_001_STD_0.BV_RBS_TRAN.ROWID )
 FROM B_B01_D_BAL_001_STD_0.BV_RBS_TRAN 
PRIMARY INDEX ( ACCT_I )

;

--
/* <sc-joinindex> B_J_BAL_001_HST_0.BV_RBS_TRAN_JI </sc-joinindex> */
CREATE JOIN INDEX B_J_BAL_001_HST_0.BV_RBS_TRAN_JI ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT (B_D_BAL_001_HST_0.BV_RBS_TRAN.ACCT_I ),(B_D_BAL_001_HST_0.BV_RBS_TRAN.ROWID )
 FROM B_D_BAL_001_HST_0.BV_RBS_TRAN 
PRIMARY INDEX ( ACCT_I )

;

--
/* <sc-joinindex> B_J_BAL_001_STD_0.BV_RBS_TRAN_HK_JI </sc-joinindex> */
CREATE JOIN INDEX B_J_BAL_001_STD_0.BV_RBS_TRAN_HK_JI ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT (B_D_BAL_001_STD_0.BV_RBS_TRAN.TRAN_IDNN_HK ),(B_D_BAL_001_STD_0.BV_RBS_TRAN.ROWID )
 FROM B_D_BAL_001_STD_0.BV_RBS_TRAN 
PRIMARY INDEX ( TRAN_IDNN_HK )

;

--
/* <sc-joinindex> B_J_BAL_001_STD_0.BV_RBS_TRAN_JI </sc-joinindex> */
CREATE JOIN INDEX B_J_BAL_001_STD_0.BV_RBS_TRAN_JI ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT (B_D_BAL_001_STD_0.BV_RBS_TRAN.ACCT_I ),(B_D_BAL_001_STD_0.BV_RBS_TRAN.ROWID )
 FROM B_D_BAL_001_STD_0.BV_RBS_TRAN 
PRIMARY INDEX ( ACCT_I )

;

--
/* <sc-joinindex> D_D01_J_SHR_001_STD_0.L_ACCT_MSUR_ACCT </sc-joinindex> */
CREATE JOIN INDEX D_D01_J_SHR_001_STD_0.L_ACCT_MSUR_ACCT ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT D_D01_D_SHR_001_STD_0.L_ACCT_MSUR_NEW.ACCT_IDNN_HK ,
D_D01_D_SHR_001_STD_0.L_ACCT_MSUR_NEW.MSUR_IDNN_HK ,D_D01_D_SHR_001_STD_0.L_ACCT_MSUR_NEW.MSTR_SRCE_SYST_C ,
D_D01_D_SHR_001_STD_0.L_ACCT_MSUR_NEW.ROWID 
 FROM D_D01_D_SHR_001_STD_0.L_ACCT_MSUR_NEW 
WHERE D_D01_D_SHR_001_STD_0.L_ACCT_MSUR_NEW.RECORD_DELETED_FLAG =  0 
PRIMARY INDEX ( ACCT_IDNN_HK );

--
/* <sc-joinindex> PDBIDM.FACT_PRCM_FNCL_GL_SSTJI1 </sc-joinindex> */
CREATE JOIN INDEX PDBIDM.FACT_PRCM_FNCL_GL_SSTJI1 ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT PDBIDM.FACT_PRCM_FNCL_GL.JRNL_I ,PDBIDM.FACT_PRCM_FNCL_GL.JRNL_LINE_N ,
PDBIDM.FACT_PRCM_FNCL_GL.BUSN_UNIT_KEY_I ,PDBIDM.FACT_PRCM_FNCL_GL.JRNL_LINE_C ,
PDBIDM.FACT_PRCM_FNCL_GL.JRNL_LINE_X ,PDBIDM.FACT_PRCM_FNCL_GL.UNPT_SEQN_N ,
PDBIDM.FACT_PRCM_FNCL_GL.JRNL_D ,PDBIDM.FACT_PRCM_FNCL_GL.ACCG_D ,
PDBIDM.FACT_PRCM_FNCL_GL.SETL_D ,PDBIDM.FACT_PRCM_FNCL_GL.Gl_ORIG_CNCY_KEY_I ,
PDBIDM.FACT_PRCM_FNCL_GL.Gl_ACTL_CNCY_KEY_I ,PDBIDM.FACT_PRCM_FNCL_GL.DEPT_KEY_I ,
PDBIDM.FACT_PRCM_FNCL_GL.SPLY_LOCN_KEY_I ,PDBIDM.FACT_PRCM_FNCL_GL.VALU_BAND_KEY_I ,
PDBIDM.FACT_PRCM_FNCL_GL.PRCM_METH_KEY_I ,PDBIDM.FACT_PRCM_FNCL_GL.Gl_ORIG_KEY_I ,
PDBIDM.FACT_PRCM_FNCL_GL.PRCM_ORIG_KEY_I ,PDBIDM.FACT_PRCM_FNCL_GL.PRJC_KEY_I ,
PDBIDM.FACT_PRCM_FNCL_GL.Gl_ACCT_KEY_I ,PDBIDM.FACT_PRCM_FNCL_GL.CPLY_TO_PAYT_TERM_INDA_KEY_I ,
PDBIDM.FACT_PRCM_FNCL_GL.CPLY_TO_CHNL_INDA_KEY_I ,PDBIDM.FACT_PRCM_FNCL_GL.PRCM_CMIT_PAYT_INDA_KEY_I ,
PDBIDM.FACT_PRCM_FNCL_GL.PRCM_SETL_INDA_KEY_I ,PDBIDM.FACT_PRCM_FNCL_GL.SPLY_UNDR_CNCT_INDA_KEY_I ,
PDBIDM.FACT_PRCM_FNCL_GL.JRNL_ENTR_EMPL_KEY_I ,PDBIDM.FACT_PRCM_FNCL_GL.PRCM_ORIG_LINE_X ,
PDBIDM.FACT_PRCM_FNCL_GL.JRNL_HEAD_CMMT_X ,PDBIDM.FACT_PRCM_FNCL_GL.PROP_ACCT_KEY_I ,
PDBIDM.FACT_PRCM_FNCL_GL.Gl_ACTL_ORIG_CNCY_A ,PDBIDM.FACT_PRCM_FNCL_GL.Gl_ACTL_CNCY_A ,
PDBIDM.FACT_PRCM_FNCL_GL.EXPS_CLAM_EMPL_KEY_I ,PDBIDM.FACT_PRCM_FNCL_GL.PRCM_CATG_KEY_I ,
PDBIDM.FACT_PRCM_FNCL_GL.POST_CATG_CONF_KEY_I ,PDBIDM.FACT_PRCM_FNCL_GL.INVC_LINE_UOM_KEY_I ,
PDBIDM.FACT_PRCM_FNCL_GL.EXPS_TYPE_KEY_I ,PDBIDM.FACT_PRCM_FNCL_GL.EXPS_CLAM_DEPT_KEY_I 
 FROM PDBIDM.FACT_PRCM_FNCL_GL 
WHERE ((PDBIDM.FACT_PRCM_FNCL_GL.RECORD_DELETED_FLAG =  0 ) AND  (PDBIDM.FACT_PRCM_FNCL_GL.EXPY_D =  DATE '9999-12-31')) AND  ((PDBIDM.FACT_PRCM_FNCL_GL.PRCM_CMIT_PAYT_INDA_KEY_I =  1 ) OR  (PDBIDM.FACT_PRCM_FNCL_GL.PRCM_SETL_INDA_KEY_I =  1 ))
PRIMARY INDEX ( JRNL_I ,JRNL_LINE_N );

--
/* <sc-joinindex> PDBIDM.FACT_PRCM_INVC_LINE_STJI1 </sc-joinindex> */
CREATE JOIN INDEX PDBIDM.FACT_PRCM_INVC_LINE_STJI1 ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT (PDBIDM.FACT_PRCM_INVC_LINE.VOCH_I ),(PDBIDM.FACT_PRCM_INVC_LINE.BUSN_UNIT_KEY_I ,
PDBIDM.FACT_PRCM_INVC_LINE.INVC_D ,PDBIDM.FACT_PRCM_INVC_LINE.CMIT_PAYT_D ,
PDBIDM.FACT_PRCM_INVC_LINE.EXPY_D ,PDBIDM.FACT_PRCM_INVC_LINE.RECORD_DELETED_FLAG ,
PDBIDM.FACT_PRCM_INVC_LINE.ROWID )
 FROM PDBIDM.FACT_PRCM_INVC_LINE 
PRIMARY INDEX ( VOCH_I )

;

--
/* <sc-joinindex> PDBIDM.FACT_PRCM_PAYT_AGGR_MTJI1 </sc-joinindex> */
CREATE JOIN INDEX PDBIDM.FACT_PRCM_PAYT_AGGR_MTJI1 ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT PDBIDM.F_PAYT_AGGR.CALR_YEAR_MNTH_N (NAMED F_CALR_YEAR_MNTH_N ),
PDBIDM.F_PAYT_AGGR.DEPT_KEY_I (NAMED F_DEPT_KEY_I ),PDBIDM.F_PAYT_AGGR.SPLY_LOCN_KEY_I (NAMED F_SPLY_LOCN_KEY_I ),
PDBIDM.F_PAYT_AGGR.PRCM_CATG_KEY_I (NAMED F_PRCM_CATG_KEY_I ),
PDBIDM.F_PAYT_AGGR.BUSN_UNIT_KEY_I (NAMED F_BUSN_UNIT_KEY_I ),
PDBIDM.F_PAYT_AGGR.PRCM_METH_KEY_I (NAMED F_PRCM_METH_KEY_I ),
PDBIDM.F_PAYT_AGGR.SPLY_UNDR_CNCT_INDA_KEY_I (NAMED F_SPLY_UNDR_CNCT_INDA_KEY_I ),
PDBIDM.F_PAYT_AGGR.CMIT_PAYT_A (NAMED F_CMIT_PAYT_A ),PDBIDM.F_PAYT_AGGR.SETL_A (NAMED F_SETL_A ),
PDBIDM.F_PAYT_AGGR.ROWID (NAMED F_ROWID ),PDBIDM.D_CALR_MNTH.FNCL_YEAR_MNTH_N (NAMED D_CALR_FNCL_YEAR_MNTH_N ),
PDBIDM.D_CALR_MNTH.CALR_MNTH_YEAR_SNAM_M (NAMED D_CALR_MNTH_YEAR_SNAM_M ),
PDBIDM.D_PRCM_CATG.CMDY_FULL_C (NAMED D_PRCM_CATG_CMDY_FULL_C ),
PDBIDM.D_PRCM_CATG.BUSN_CATG_M (NAMED D_PRCM_CATG_BUSN_CATG_M ) FROM 
((PDBIDM.FACT_PRCM_PAYT_AGGR  F_PAYT_AGGR  INNER JOIN PDBIDM.DIMN_PRCM_CATG  D_PRCM_CATG  ON PDBIDM.D_PRCM_CATG.PRCM_CATG_KEY_I =  PDBIDM.F_PAYT_AGGR.PRCM_CATG_KEY_I )
 INNER JOIN PDBIDM.DIMN_CALR_MNTH  D_CALR_MNTH  ON PDBIDM.D_CALR_MNTH.CALR_YEAR_MNTH_N =  PDBIDM.F_PAYT_AGGR.CALR_YEAR_MNTH_N )

WHERE (PDBIDM.D_PRCM_CATG.RECORD_DELETED_FLAG =  0 ) AND  (PDBIDM.F_PAYT_AGGR.RECORD_DELETED_FLAG =  0 )
PRIMARY INDEX ( F_CALR_YEAR_MNTH_N ,F_DEPT_KEY_I ,F_SPLY_LOCN_KEY_I ,
F_PRCM_CATG_KEY_I );

--
/* <sc-joinindex> PDCBODS.ACCT_MSTR_DATA_STJI1 </sc-joinindex> */
CREATE JOIN INDEX PDCBODS.ACCT_MSTR_DATA_STJI1 ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT PDCBODS.ACCT_MSTR_DATA.ACCT_I ,PDCBODS.ACCT_MSTR_DATA.ACCT ,
PDCBODS.ACCT_MSTR_DATA.ACCT_STUS ,PDCBODS.ACCT_MSTR_DATA.SALE_PDCT ,
PDCBODS.ACCT_MSTR_DATA.PDCT ,PDCBODS.ACCT_MSTR_DATA.SRCE_SYST_ISAC_CODE ,
PDCBODS.ACCT_MSTR_DATA.LOAD_S ,PDCBODS.ACCT_MSTR_DATA.ROW_SECU_ACCS_C ,
PDCBODS.ACCT_MSTR_DATA.IS_CURR_IND ,PDCBODS.ACCT_MSTR_DATA.ROWID 
 FROM PDCBODS.ACCT_MSTR_DATA 
PRIMARY INDEX ( ACCT_I );

--
/* <sc-joinindex> PDCBODS.CUST_INIT_PAYT_ITEM_DATE_AJI1 </sc-joinindex> */
CREATE JOIN INDEX PDCBODS.CUST_INIT_PAYT_ITEM_DATE_AJI1 ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT COUNT(*)(FLOAT, NAMED CountStar ),PDCBODS.CUST_INIT_PAYT_ITEM_DATE.ACCT ,
PDCBODS.CUST_INIT_PAYT_ITEM_DATE.ROW_SECU_ACCS_C ,MAX(PDCBODS.CUST_INIT_PAYT_ITEM_DATE.DATE_OF_CIMT )(DATE, NAMED Max_DATE_OF_CIMT )
 FROM PDCBODS.CUST_INIT_PAYT_ITEM_DATE 
GROUP BY PDCBODS.CUST_INIT_PAYT_ITEM_DATE.ACCT ,PDCBODS.CUST_INIT_PAYT_ITEM_DATE.ROW_SECU_ACCS_C 
PRIMARY INDEX ( ACCT );

--
/* <sc-joinindex> PDCBODS.MSTR_CNCT_FCLY_UTLS_AJI1 </sc-joinindex> */
CREATE JOIN INDEX PDCBODS.MSTR_CNCT_FCLY_UTLS_AJI1 ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT COUNT(*)(FLOAT, NAMED CountStar ),PDCBODS.MSTR_CNCT_FCLY_UTLS.INTR_IDNN_OF_A_CMIT ,
PDCBODS.MSTR_CNCT_FCLY_UTLS.UTLS_CATG ,PDCBODS.MSTR_CNCT_FCLY_UTLS.TIME_STMP_FOR_EVLN_OF_CURR_UTL ,
PDCBODS.MSTR_CNCT_FCLY_UTLS.SRCE_SYST_ISAC_CODE ,MAX(PDCBODS.MSTR_CNCT_FCLY_UTLS.LOAD_S )(TIMESTAMP(6), NAMED Max_LOAD_S )
 FROM PDCBODS.MSTR_CNCT_FCLY_UTLS 
GROUP BY PDCBODS.MSTR_CNCT_FCLY_UTLS.INTR_IDNN_OF_A_CMIT ,PDCBODS.MSTR_CNCT_FCLY_UTLS.UTLS_CATG ,
PDCBODS.MSTR_CNCT_FCLY_UTLS.TIME_STMP_FOR_EVLN_OF_CURR_UTL ,
PDCBODS.MSTR_CNCT_FCLY_UTLS.SRCE_SYST_ISAC_CODE 
PRIMARY INDEX ( INTR_IDNN_OF_A_CMIT ,UTLS_CATG ,TIME_STMP_FOR_EVLN_OF_CURR_UTL ,
SRCE_SYST_ISAC_CODE );

--
/* <sc-joinindex> PDCBODS.MSTR_CNCT_FCLY_UTLS_STJI1 </sc-joinindex> */
CREATE JOIN INDEX PDCBODS.MSTR_CNCT_FCLY_UTLS_STJI1 ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT (PDCBODS.MSTR_CNCT_FCLY_UTLS.INTR_IDNN_OF_A_CMIT ,PDCBODS.MSTR_CNCT_FCLY_UTLS.UTLS_CATG ,
PDCBODS.MSTR_CNCT_FCLY_UTLS.TIME_STMP_FOR_EVLN_OF_CURR_UTL ,
PDCBODS.MSTR_CNCT_FCLY_UTLS.SRCE_SYST_ISAC_CODE ,PDCBODS.MSTR_CNCT_FCLY_UTLS.ROW_SECU_ACCS_C ),
(PDCBODS.MSTR_CNCT_FCLY_UTLS.LOAD_S ,PDCBODS.MSTR_CNCT_FCLY_UTLS.UTLSD_AMT_OF_MSTR_CNCT ,
PDCBODS.MSTR_CNCT_FCLY_UTLS.ROWID )
 FROM PDCBODS.MSTR_CNCT_FCLY_UTLS 
PRIMARY INDEX ( INTR_IDNN_OF_A_CMIT ,UTLS_CATG ,TIME_STMP_FOR_EVLN_OF_CURR_UTL ,
SRCE_SYST_ISAC_CODE )

;

--
/* <sc-joinindex> PDCBODS.POST_BALN_AJI1 </sc-joinindex> */
CREATE JOIN INDEX PDCBODS.POST_BALN_AJI1 ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT COUNT(*)(FLOAT, NAMED CountStar ),PDCBODS.POST_BALN.ACCT ,
PDCBODS.POST_BALN.SRCE_SYST_ISAC_CODE ,PDCBODS.POST_BALN.IS_CURR_IND ,
PDCBODS.POST_BALN.ROW_SECU_ACCS_C ,MAX(PDCBODS.POST_BALN.POST_DATE )(DATE, NAMED Max_POST_DATE ),
MAX(PDCBODS.POST_BALN.LOAD_S )(TIMESTAMP(6), NAMED Max_LOAD_S )
 FROM PDCBODS.POST_BALN 
GROUP BY PDCBODS.POST_BALN.ACCT ,PDCBODS.POST_BALN.SRCE_SYST_ISAC_CODE ,
PDCBODS.POST_BALN.IS_CURR_IND ,PDCBODS.POST_BALN.ROW_SECU_ACCS_C 
PRIMARY INDEX ( ACCT );

--
/* <sc-joinindex> PDHCLWR.BV_RBS_TRAN_HK_JI </sc-joinindex> */
CREATE JOIN INDEX PDHCLWR.BV_RBS_TRAN_HK_JI ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT (PDHCLWR.BV_RBS_TRAN.TRAN_IDNN_HK ),(PDHCLWR.BV_RBS_TRAN.ROWID )
 FROM PDHCLWR.BV_RBS_TRAN 
PRIMARY INDEX ( TRAN_IDNN_HK )

;

--
/* <sc-joinindex> PDHCLWR.BV_RBS_TRAN_JI </sc-joinindex> */
CREATE JOIN INDEX PDHCLWR.BV_RBS_TRAN_JI ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT (PDHCLWR.BV_RBS_TRAN.ACCT_I ),(PDHCLWR.BV_RBS_TRAN.ROWID )
 FROM PDHCLWR.BV_RBS_TRAN 
PRIMARY INDEX ( ACCT_I )

;

--
/* <sc-joinindex> PDHCLWR.employee_index </sc-joinindex> */
CREATE JOIN INDEX PDHCLWR.employee_index ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT PDHCLWR.employee.ename ,PDHCLWR.employee.eno 
 FROM PDHCLWR.employee 
PRIMARY INDEX ( ename );

--
/* <sc-joinindex> PDHCLWR.Employee_ji </sc-joinindex> */
CREATE JOIN INDEX PDHCLWR.Employee_ji ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT pdhclwr.employee1.Employeeno ,pdhclwr.employee1.Firstname ,
pdhclwr.employee1.Lastname ,pdhclwr.employee1.DOB ,pdhclwr.employee1.Joineddate ,
pdhclwr.employee1.Departmentno 
 FROM pdhclwr.employee1 
PRIMARY INDEX ( Firstname );

--
/* <sc-joinindex> PDHCLWR.FACT_CRCD_ACTV_TRAN_DALY_JRNLD </sc-joinindex> */
CREATE JOIN INDEX PDHCLWR.FACT_CRCD_ACTV_TRAN_DALY_JRNLD ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT PDHCLWR.FACT_CRCD_ACTV_TRAN_DALY.FNCL_TRAN_IDNN_HK ,
PDHCLWR.FACT_CRCD_ACTV_TRAN_DALY.JRNL_D ,PDHCLWR.FACT_CRCD_ACTV_TRAN_DALY.ROWID 
 FROM PDHCLWR.FACT_CRCD_ACTV_TRAN_DALY 
PRIMARY INDEX ( FNCL_TRAN_IDNN_HK )
PARTITION BY RANGE_N(PDHCLWR.FACT_CRCD_ACTV_TRAN_DALY.JRNL_D  BETWEEN 
DATE '1998-01-01' AND '2030-06-30' EACH INTERVAL '1' DAY ,
 NO RANGE);

--
/* <sc-joinindex> PDHCLWR.L_FNCL_TRAN_ACCT_REL_STJI </sc-joinindex> */
CREATE JOIN INDEX PDHCLWR.L_FNCL_TRAN_ACCT_REL_STJI ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT (PDHCLWR.L_FNCL_TRAN_ACCT_REL.ACCT_IDNN_HK ,PDHCLWR.L_FNCL_TRAN_ACCT_REL.ROW_SECU_ACCS_C ,
PDHCLWR.L_FNCL_TRAN_ACCT_REL.MSTR_SRCE_SYST_C ,PDHCLWR.L_FNCL_TRAN_ACCT_REL.EXPY_D ),
(PDHCLWR.L_FNCL_TRAN_ACCT_REL.ROWID )
 FROM PDHCLWR.L_FNCL_TRAN_ACCT_REL 
WHERE PDHCLWR.L_FNCL_TRAN_ACCT_REL.RECORD_DELETED_FLAG =  0 
PRIMARY INDEX ( ACCT_IDNN_HK )

;

--
/* <sc-joinindex> PDHCLWR.ORD_CUST_IDX </sc-joinindex> */
CREATE JOIN INDEX PDHCLWR.ORD_CUST_IDX ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT PDHCLWR.ORDERS_TBL.O_CUSTKEY ,PDHCLWR.CUSTOMER.C_NAME ,
PDHCLWR.ORDERS_TBL.O_STATUS ,PDHCLWR.ORDERS_TBL.O_DATE ,PDHCLWR.ORDERS_TBL.O_COMMENT 
 FROM PDHCLWR.ORDERS_TBL ,PDHCLWR.CUSTOMER 
WHERE PDHCLWR.ORDERS_TBL.O_CUSTKEY =  PDHCLWR.CUSTOMER.C_CUSTKEY 
PRIMARY INDEX ( O_CUSTKEY );

--
/* <sc-joinindex> PDHCLWR.sampl </sc-joinindex> */
CREATE JOIN INDEX PDHCLWR.sampl ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT PDHCLWR.set_sam.eno ,PDHCLWR.set_sam.ename 
 FROM PDHCLWR.set_sam 
PRIMARY INDEX ( eno );

--
/* <sc-joinindex> PDHCLWR.sam_index </sc-joinindex> */
CREATE JOIN INDEX PDHCLWR.sam_index ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT PDHCLWR.dep_sam.dno ,PDHCLWR.dep_sam.dname 
 FROM PDHCLWR.dep_sam 
PRIMARY INDEX ( dno );

--
/* <sc-joinindex> PDI3DEVL.JY2_CUSTOMER_SCHEMA_ACCOUNT_SSTJI </sc-joinindex> */
CREATE JOIN INDEX PDI3DEVL.JY2_CUSTOMER_SCHEMA_ACCOUNT_SSTJI ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT pDI3DEVL.JY2_CUSTOMER_SCHEMA_ACCOUNT.Paty_i ,pDI3DEVL.JY2_CUSTOMER_SCHEMA_ACCOUNT.Acct_i 
 FROM pDI3DEVL.JY2_CUSTOMER_SCHEMA_ACCOUNT 
WHERE pDI3DEVL.JY2_CUSTOMER_SCHEMA_ACCOUNT.Expy_D =  DATE '9999-12-31'
PRIMARY INDEX ( Paty_i );

--
/* <sc-joinindex> PDTRMCORE.CR_FOLDER_JI </sc-joinindex> */
CREATE JOIN INDEX PDTRMCORE.CR_FOLDER_JI ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT (PDTRMCORE.CR_FOLDER.Parent_Folder_Id ),(PDTRMCORE.CR_FOLDER.Folder_Id ,
PDTRMCORE.CR_FOLDER.Name ,PDTRMCORE.CR_FOLDER.Security_Type_Cd ,
PDTRMCORE.CR_FOLDER.Create_User ,PDTRMCORE.CR_FOLDER.Create_Dttm ,
PDTRMCORE.CR_FOLDER.Update_User ,PDTRMCORE.CR_FOLDER.Update_Dttm )
 FROM PDTRMCORE.CR_FOLDER 
PRIMARY INDEX ( Parent_Folder_Id )

;

--
/* <sc-joinindex> PDTRMLEAD.LH_SELECTION_VARIABLE_JIDX </sc-joinindex> */
CREATE JOIN INDEX PDTRMLEAD.LH_SELECTION_VARIABLE_JIDX ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT (PDTRMLEAD.LH_SELECTION_VARIABLE.Leaf_Segment_Id ,PDTRMLEAD.LH_SELECTION_VARIABLE.Paty_i ),
(PDTRMLEAD.LH_SELECTION_VARIABLE.ROWID )
 FROM PDTRMLEAD.LH_SELECTION_VARIABLE 
PRIMARY INDEX ( Leaf_Segment_Id ,Paty_i )

;

--
/* <sc-joinindex> PDTRMMAP.CUSTOMER_SCHEMA_ACCOUNT_SSTJI </sc-joinindex> */
CREATE JOIN INDEX PDTRMMAP.CUSTOMER_SCHEMA_ACCOUNT_SSTJI ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT PDTRMMAP.CUSTOMER_SCHEMA_ACCOUNT.Paty_i ,PDTRMMAP.CUSTOMER_SCHEMA_ACCOUNT.Acct_i 
 FROM PDTRMMAP.CUSTOMER_SCHEMA_ACCOUNT 
WHERE PDTRMMAP.CUSTOMER_SCHEMA_ACCOUNT.Expy_D =  DATE '9999-12-31'
PRIMARY INDEX ( Paty_i );

--
/* <sc-joinindex> PTEMP.empl_dept </sc-joinindex> */
CREATE JOIN INDEX PTEMP.empl_dept ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT ptemp.a.ename ,ptemp.a.empid ,ptemp.a.deptno ,ptemp.b.dname  FROM 
(ptemp.empl  a  INNER JOIN ptemp.dept  b  ON ptemp.a.deptno =  ptemp.b.deptno )

PRIMARY INDEX ( empid );

--
/* <sc-joinindex> PTEMP.jt </sc-joinindex> */
CREATE JOIN INDEX PTEMP.jt ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT ptemp.emp_kar.id ,ptemp.emp_kar.name 
 FROM ptemp.emp_kar 
WHERE ptemp.emp_kar.name =  'satheesh'
PRIMARY INDEX ( id );

--
/* <sc-joinindex> PTEMP.L_FNCL_TRAN_ACCT_REL_STJI </sc-joinindex> */
CREATE JOIN INDEX PTEMP.L_FNCL_TRAN_ACCT_REL_STJI ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT (PTEMP.L_FNCL_TRAN_ACCT_REL.ACCT_IDNN_HK ,PTEMP.L_FNCL_TRAN_ACCT_REL.ROW_SECU_ACCS_C ,
PTEMP.L_FNCL_TRAN_ACCT_REL.MSTR_SRCE_SYST_C ,PTEMP.L_FNCL_TRAN_ACCT_REL.EXPY_D ),
(PTEMP.L_FNCL_TRAN_ACCT_REL.ROWID )
 FROM PTEMP.L_FNCL_TRAN_ACCT_REL 
WHERE PTEMP.L_FNCL_TRAN_ACCT_REL.RECORD_DELETED_FLAG =  0 
PRIMARY INDEX ( ACCT_IDNN_HK )

;

--
/* <sc-joinindex> P_J_BAL_001_STD_0.FACT_ACCT_MSUR_MNLY_AGGR_MTJI </sc-joinindex> */
CREATE JOIN INDEX P_J_BAL_001_STD_0.FACT_ACCT_MSUR_MNLY_AGGR_MTJI ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT COUNT(*)(FLOAT, NAMED CountStar ),P_D_BAL_001_STD_0.FACT.ACCT_IDNN_HK ,
P_D_BAL_001_STD_0.FACT.GRD_PDCT_IDNN_HK ,P_D_BAL_001_STD_0.FACT.MONTHONBK_IDNN_HK ,
P_D_BAL_001_STD_0.FACT.REL_MNGE_EMPL_IDNN_HK ,P_D_BAL_001_STD_0.FACT.PRIM_CUST_ANZI_IDNN_HK ,
P_D_BAL_001_STD_0.FACT.PRIM_CUST_IDNN_HK ,P_D_BAL_001_STD_0.FACT.REL_MNGE_DEPT_IDNN_HK ,
P_D_BAL_001_STD_0.FACT.GL_ACCT_IDNN_HK ,P_D_BAL_001_STD_0.FACT.GL_PRJC_IDNN_HK ,
P_D_BAL_001_STD_0.FACT.BUSN_UNIT_IDNN_HK ,P_D_BAL_001_STD_0.FACT.AFLT_IDNN_HK ,
P_D_BAL_001_STD_0.FACT.CNCY_IDNN_HK ,P_D_BAL_001_STD_0.FACT.DEPT_IDNN_HK ,
P_D_BAL_001_STD_0.FACT.GL_OPER_UNIT_IDNN_HK ,P_D_BAL_001_STD_0.FACT.MNTH_END_D ,
P_D_BAL_001_STD_0.FACT.MNTH_OPEN_D ,P_D_BAL_001_STD_0.FACT.GL_PDCT_IDNN_HK ,
P_D_BAL_001_STD_0.FACT.ACCT_OPEN_DEPT_IDNN_HK ,P_D_BAL_001_STD_0.FACT.ARRS_IDNN_HK ,
MAX(P_D_BAL_001_STD_0.FACT.CYCL_POIT_D )(DATE, NAMED MAX_CYCL_POIT_D ),
MAX(P_D_BAL_001_STD_0.FACT.CYCL_POIT_ARRS_IDNN_HK )(CHAR(32), CHARACTER SET LATIN, NOT CASESPECIFIC, NAMED MAX_CYCL_POIT_ARRS_IDNN_HK ),
SUM(( CASE WHEN (P_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'CLSE_BALN_A') THEN (P_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED CLSE_BALN_A ),
SUM(( CASE WHEN (P_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'LIMT_A') THEN (P_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED LIMT_A ),
SUM(( CASE WHEN (P_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'XPOS_ACCT_Q') THEN (P_D_BAL_001_STD_0.FACT.MSUR_Q ) ELSE (0 ) END ))(FLOAT, NAMED XPOS_ACCT_Q ),
SUM(( CASE WHEN (P_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'CRCD_INUSE_Q') THEN (P_D_BAL_001_STD_0.FACT.MSUR_Q ) ELSE (0 ) END ))(FLOAT, NAMED CRCD_INUSE_Q ),
SUM(( CASE WHEN (P_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'ADD_CARD_FEE_A') THEN (P_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED ADD_CARD_FEE_A ),
SUM(( CASE WHEN (P_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'ADD_CARD_FRFD_A') THEN (P_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED ADD_CARD_FRFD_A ),
SUM(( CASE WHEN (P_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'ANNL_FEE_A') THEN (P_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED ANNL_FEE_A ),
SUM(( CASE WHEN (P_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'ANNL_FRFD_A') THEN (P_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED ANNL_FRFD_A ),
SUM(( CASE WHEN (P_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'INT_CHRG_BALN_TRNF_A') THEN (P_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED INT_CHRG_BALN_TRNF_A ),
SUM(( CASE WHEN (P_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'INT_CHRG_CSAD_A') THEN (P_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED INT_CHRG_CSAD_A ),
SUM(( CASE WHEN (P_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'CASD_FEE_A') THEN (P_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED CASD_FEE_A ),
SUM(( CASE WHEN (P_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'CASD_FRFD_A') THEN (P_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED CASD_FRFD_A ),
SUM(( CASE WHEN (P_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'CYCL_POIT_BALN_A') THEN (P_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED CYCL_POIT_BALN_A ),
SUM(( CASE WHEN (P_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'INTL_TRAN_FEE_A') THEN (P_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED INTL_TRAN_FEE_A ),
SUM(( CASE WHEN (P_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'INTL_TRAN_FRFD_A') THEN (P_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED INTL_TRAN_FRFD_A ),
SUM(( CASE WHEN (P_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'LATE_PAYT_FEE_A') THEN (P_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED LATE_PAYT_FEE_A ),
SUM(( CASE WHEN (P_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'LATE_PAYT_FRFD_A') THEN (P_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED LATE_PAYT_FRFD_A ),
SUM(( CASE WHEN (P_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'LIMT_XCES_A') THEN (P_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED LIMT_XCES_A ),
SUM(( CASE WHEN (P_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'OVER_LIMT_FEE_A') THEN (P_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED OVER_LIMT_FEE_A ),
SUM(( CASE WHEN (P_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'OVER_LIMT_FRFD_A') THEN (P_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED OVER_LIMT_FRFD_A ),
SUM(( CASE WHEN (P_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'INT_CHRG_PUR_A') THEN (P_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED INT_CHRG_PUR_A ),
SUM(( CASE WHEN (P_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'QAN_FREQ_FLYR_FEE_A') THEN (P_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED QAN_FREQ_FLYR_FEE_A ),
SUM(( CASE WHEN (P_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'QAN_FREQ_FLYR_FRFD_A') THEN (P_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED QAN_FREQ_FLYR_FRFD_A ),
SUM(( CASE WHEN (P_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'INT_CHRG_RFND_A') THEN (P_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED INT_CHRG_RFND_A ),
SUM(( CASE WHEN (P_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'INT_CHRG_SPEC_RATE_A') THEN (P_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED INT_CHRG_SPEC_RATE_A ),
SUM(( CASE WHEN (P_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'UDRW_LIMT_A') THEN (P_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED UDRW_LIMT_A ),
SUM(( CASE WHEN (P_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'MNLY_DR_AVRG_CLSE_BALN_A') THEN (P_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED MNLY_DR_AVRG_CLSE_BALN_A ),
SUM(( CASE WHEN (P_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'MNLY_CR_AVRG_CLSE_BALN_A') THEN (P_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED MNLY_CR_AVRG_CLSE_BALN_A ),
SUM(( CASE WHEN (P_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'MNLY_NET_AVRG_CLSE_BALN_A') THEN (P_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED MNLY_NET_AVRG_CLSE_BALN_A ),
SUM(( CASE WHEN (P_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'FQTD_DR_AVRG_CLSE_BALN_A') THEN (P_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED FQTD_DR_AVRG_CLSE_BALN_A ),
SUM(( CASE WHEN (P_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'FQTD_CR_AVRG_CLSE_BALN_A') THEN (P_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED FQTD_CR_AVRG_CLSE_BALN_A ),
SUM(( CASE WHEN (P_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'FQTD_NET_AVRG_CLSE_BALN_A') THEN (P_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED FQTD_NET_AVRG_CLSE_BALN_A ),
SUM(( CASE WHEN (P_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'FYTD_DR_AVRG_CLSE_BALN_A') THEN (P_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED FYTD_DR_AVRG_CLSE_BALN_A ),
SUM(( CASE WHEN (P_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'FYTD_CR_AVRG_CLSE_BALN_A') THEN (P_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED FYTD_CR_AVRG_CLSE_BALN_A ),
SUM(( CASE WHEN (P_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'FYTD_NET_AVRG_CLSE_BALN_A') THEN (P_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED FYTD_NET_AVRG_CLSE_BALN_A ),
SUM(( CASE WHEN (P_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'INT_WROF_A') THEN (P_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED INT_FEE_WROF_A ),
SUM(( CASE WHEN (P_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'ANNL_FEE_WROF_A') THEN (P_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED ANNL_FEE_WROF_A ),
SUM(( CASE WHEN (P_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'LATE_PAYT_FEE_WROF_A') THEN (P_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED LATE_PAYT_FEE_WROF_A ),
SUM(( CASE WHEN (P_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'OPEN_BALN_A') THEN (P_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED OPEN_BALN_A ),
SUM(( CASE WHEN (P_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'INSR_FEE_WROF_A') THEN (P_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED INSR_FEE_WROF_A ),
SUM(( CASE WHEN (P_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'PRIN_WROF_A') THEN (P_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED PRIN_WROF_A ),
SUM(( CASE WHEN (P_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'COF_UDRW_LIQDP_A') THEN (P_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED COF_UDRW_LIQDP_A ),
SUM(( CASE WHEN (P_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'COF_CASH_AND_BASE_RATE_PREM_A') THEN (P_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED COF_CASH_AND_BASE_RATE_PREM_A ),
SUM(( CASE WHEN (P_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'COF_LGTM_FUND_PREM_A') THEN (P_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED COF_LGTM_FUND_PREM_A ),
SUM(( CASE WHEN (P_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'COF_LIQD_PREM_A') THEN (P_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED COF_LIQD_PREM_A ),
SUM(( CASE WHEN (P_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'INCG_FEE_A') THEN (P_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED INCG_FEE_A ),
SUM(( CASE WHEN (P_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'SCHM_FEE_A') THEN (P_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED SCHM_FEE_A ) FROM 
(P_D_BAL_001_STD_0.FACT_ACCT_MSUR_MNLY  FACT  INNER JOIN P_D_BUS_001_STD_0.H_MSUR  MSUR  ON P_D_BAL_001_STD_0.FACT.MSUR_IDNN_HK =  P_D_BUS_001_STD_0.MSUR.MSUR_IDNN_HK )

WHERE ((((P_D_BAL_001_STD_0.FACT.EXPY_D =  DATE '9999-12-31') AND  (P_D_BUS_001_STD_0.MSUR.EXPY_D =  DATE '9999-12-31')) AND  (P_D_BAL_001_STD_0.FACT.RECORD_DELETED_FLAG =  0 )) AND  (P_D_BUS_001_STD_0.MSUR.RECORD_DELETED_FLAG =  0 )) AND  (P_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK  IN ('CLSE_BALN_A',
'LIMT_A','XPOS_ACCT_Q','CRCD_INUSE_Q','ADD_CARD_FEE_A','ADD_CARD_FRFD_A',
'ANNL_FEE_A','ANNL_FRFD_A','INT_CHRG_BALN_TRNF_A','INT_CHRG_CSAD_A',
'CASD_FEE_A','CASD_FRFD_A','CYCL_POIT_BALN_A','INTL_TRAN_FEE_A',
'INTL_TRAN_FRFD_A','LATE_PAYT_FEE_A','LATE_PAYT_FRFD_A','LIMT_XCES_A',
'OVER_LIMT_FEE_A','OVER_LIMT_FRFD_A','INT_CHRG_PUR_A','QAN_FREQ_FLYR_FEE_A',
'QAN_FREQ_FLYR_FRFD_A','INT_CHRG_RFND_A','INT_CHRG_SPEC_RATE_A',
'UDRW_LIMT_A','MNLY_DR_AVRG_CLSE_BALN_A','MNLY_CR_AVRG_CLSE_BALN_A',
'MNLY_NET_AVRG_CLSE_BALN_A','FQTD_DR_AVRG_CLSE_BALN_A','FQTD_CR_AVRG_CLSE_BALN_A',
'FQTD_NET_AVRG_CLSE_BALN_A','FYTD_DR_AVRG_CLSE_BALN_A','FYTD_CR_AVRG_CLSE_BALN_A',
'FYTD_NET_AVRG_CLSE_BALN_A','INT_WROF_A','ANNL_FEE_WROF_A','LATE_PAYT_FEE_WROF_A',
'OPEN_BALN_A','INSR_FEE_WROF_A','PRIN_WROF_A','COF_UDRW_LIQDP_A',
'COF_CASH_AND_BASE_RATE_PREM_A','COF_LGTM_FUND_PREM_A','COF_LIQD_PREM_A',
'INCG_FEE_A','SCHM_FEE_A'))
GROUP BY P_D_BAL_001_STD_0.FACT.ACCT_IDNN_HK ,P_D_BAL_001_STD_0.FACT.GRD_PDCT_IDNN_HK ,
P_D_BAL_001_STD_0.FACT.MONTHONBK_IDNN_HK ,P_D_BAL_001_STD_0.FACT.REL_MNGE_EMPL_IDNN_HK ,
P_D_BAL_001_STD_0.FACT.PRIM_CUST_ANZI_IDNN_HK ,P_D_BAL_001_STD_0.FACT.PRIM_CUST_IDNN_HK ,
P_D_BAL_001_STD_0.FACT.REL_MNGE_DEPT_IDNN_HK ,P_D_BAL_001_STD_0.FACT.GL_ACCT_IDNN_HK ,
P_D_BAL_001_STD_0.FACT.GL_PRJC_IDNN_HK ,P_D_BAL_001_STD_0.FACT.BUSN_UNIT_IDNN_HK ,
P_D_BAL_001_STD_0.FACT.AFLT_IDNN_HK ,P_D_BAL_001_STD_0.FACT.CNCY_IDNN_HK ,
P_D_BAL_001_STD_0.FACT.DEPT_IDNN_HK ,P_D_BAL_001_STD_0.FACT.GL_OPER_UNIT_IDNN_HK ,
P_D_BAL_001_STD_0.FACT.MNTH_END_D ,P_D_BAL_001_STD_0.FACT.MNTH_OPEN_D ,
P_D_BAL_001_STD_0.FACT.GL_PDCT_IDNN_HK ,P_D_BAL_001_STD_0.FACT.ACCT_OPEN_DEPT_IDNN_HK ,
P_D_BAL_001_STD_0.FACT.ARRS_IDNN_HK 
PRIMARY INDEX ( ACCT_IDNN_HK )
PARTITION BY RANGE_N(P_D_BAL_001_STD_0.FACT.MNTH_END_D  BETWEEN 
DATE '2013-07-01' AND '2030-06-30' EACH INTERVAL '1' MONTH );

--
/* <sc-joinindex> P_J_BAL_001_STD_0.FACT_CRCD_ACTV_TRAN_DALY_JRNLD </sc-joinindex> */
CREATE JOIN INDEX P_J_BAL_001_STD_0.FACT_CRCD_ACTV_TRAN_DALY_JRNLD ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT P_D_BAL_001_STD_0.FACT_CRCD_ACTV_TRAN_DALY.FNCL_TRAN_IDNN_HK ,
P_D_BAL_001_STD_0.FACT_CRCD_ACTV_TRAN_DALY.JRNL_D ,P_D_BAL_001_STD_0.FACT_CRCD_ACTV_TRAN_DALY.ROWID 
 FROM P_D_BAL_001_STD_0.FACT_CRCD_ACTV_TRAN_DALY 
PRIMARY INDEX ( FNCL_TRAN_IDNN_HK )
PARTITION BY RANGE_N(P_D_BAL_001_STD_0.FACT_CRCD_ACTV_TRAN_DALY.JRNL_D  BETWEEN 
DATE '1998-01-01' AND '2030-06-30' EACH INTERVAL '1' DAY ,
 NO RANGE);

--
/* <sc-joinindex> P_J_BUS_001_STD_0.S_MSUR_DALY_SNAP_SSTJI1 </sc-joinindex> */
CREATE JOIN INDEX P_J_BUS_001_STD_0.S_MSUR_DALY_SNAP_SSTJI1 ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT P_D_BUS_001_STD_0.S_MSUR_DALY_SNAP.MSUR_IDNN_HK ,P_D_BUS_001_STD_0.S_MSUR_DALY_SNAP.MSTR_SRCE_SYST_C ,
P_D_BUS_001_STD_0.S_MSUR_DALY_SNAP.MSUR_QLFY_C ,P_D_BUS_001_STD_0.S_MSUR_DALY_SNAP.MSUR_CODE_IDNN_BK ,
P_D_BUS_001_STD_0.S_MSUR_DALY_SNAP.MSUR_A ,P_D_BUS_001_STD_0.S_MSUR_DALY_SNAP.MSUR_Q ,
P_D_BUS_001_STD_0.S_MSUR_DALY_SNAP.MSUR_R ,P_D_BUS_001_STD_0.S_MSUR_DALY_SNAP.SNAP_D ,
P_D_BUS_001_STD_0.S_MSUR_DALY_SNAP.EFFT_D ,P_D_BUS_001_STD_0.S_MSUR_DALY_SNAP.EXPY_D ,
P_D_BUS_001_STD_0.S_MSUR_DALY_SNAP.RECORD_DELETED_FLAG ,P_D_BUS_001_STD_0.S_MSUR_DALY_SNAP.ROW_SECU_ACCS_C ,
P_D_BUS_001_STD_0.S_MSUR_DALY_SNAP.ROWID 
 FROM P_D_BUS_001_STD_0.S_MSUR_DALY_SNAP 
WHERE P_D_BUS_001_STD_0.S_MSUR_DALY_SNAP.EXPY_D =  DATE '9999-12-31'
PRIMARY INDEX ( MSUR_IDNN_HK )
PARTITION BY RANGE_N(P_D_BUS_001_STD_0.S_MSUR_DALY_SNAP.SNAP_D  BETWEEN 
DATE '2014-01-01' AND '2030-06-30' EACH INTERVAL '1' DAY ,
 NO RANGE);

--
/* <sc-joinindex> P_J_RAW_001_STD_0.PREN_ACCT_JI </sc-joinindex> */
CREATE JOIN INDEX P_J_RAW_001_STD_0.PREN_ACCT_JI ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT P_D_RAW_001_STD_0.S_SAP_FNCL_TRAN_PREN_ZTB_PRE1.ACCT_IDNN_HK ,
P_D_RAW_001_STD_0.S_SAP_FNCL_TRAN_PREN_ZTB_PRE1.ROWID 
 FROM P_D_RAW_001_STD_0.S_SAP_FNCL_TRAN_PREN_ZTB_PRE1 
WHERE P_D_RAW_001_STD_0.S_SAP_FNCL_TRAN_PREN_ZTB_PRE1.RECORD_DELETED_FLAG =  0 
PRIMARY INDEX ( ACCT_IDNN_HK );

--
/* <sc-joinindex> P_J_SHR_001_STD_0.L_ACCT_MSUR_ACCT </sc-joinindex> */
CREATE JOIN INDEX P_J_SHR_001_STD_0.L_ACCT_MSUR_ACCT ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT P_D_SHR_001_STD_0.L_ACCT_MSUR_NEW.ACCT_IDNN_HK ,P_D_SHR_001_STD_0.L_ACCT_MSUR_NEW.MSUR_IDNN_HK ,
P_D_SHR_001_STD_0.L_ACCT_MSUR_NEW.MSTR_SRCE_SYST_C ,P_D_SHR_001_STD_0.L_ACCT_MSUR_NEW.ROWID 
 FROM P_D_SHR_001_STD_0.L_ACCT_MSUR_NEW 
WHERE P_D_SHR_001_STD_0.L_ACCT_MSUR_NEW.RECORD_DELETED_FLAG =  0 
PRIMARY INDEX ( ACCT_IDNN_HK );

--
/* <sc-joinindex> P_J_SHR_001_STD_0.L_FNCL_TRAN_ACCT_REL_STJI </sc-joinindex> */
CREATE JOIN INDEX P_J_SHR_001_STD_0.L_FNCL_TRAN_ACCT_REL_STJI ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT (P_D_SHR_001_STD_0.L_FNCL_TRAN_ACCT_REL.ACCT_IDNN_HK ,
P_D_SHR_001_STD_0.L_FNCL_TRAN_ACCT_REL.ROW_SECU_ACCS_C ,P_D_SHR_001_STD_0.L_FNCL_TRAN_ACCT_REL.MSTR_SRCE_SYST_C ,
P_D_SHR_001_STD_0.L_FNCL_TRAN_ACCT_REL.EXPY_D ),(P_D_SHR_001_STD_0.L_FNCL_TRAN_ACCT_REL.ROWID )
 FROM P_D_SHR_001_STD_0.L_FNCL_TRAN_ACCT_REL 
WHERE P_D_SHR_001_STD_0.L_FNCL_TRAN_ACCT_REL.RECORD_DELETED_FLAG =  0 
PRIMARY INDEX ( ACCT_IDNN_HK )

;

--
/* <sc-joinindex> P_P01_J_BAL_001_STD_0.FACT_ACCT_MSUR_MNLY_AGGR_MTJI </sc-joinindex> */
CREATE JOIN INDEX P_P01_J_BAL_001_STD_0.FACT_ACCT_MSUR_MNLY_AGGR_MTJI ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT COUNT(*)(FLOAT, NAMED CountStar ),P_P01_D_BAL_001_STD_0.FACT.ACCT_IDNN_HK ,
P_P01_D_BAL_001_STD_0.FACT.GRD_PDCT_IDNN_HK ,P_P01_D_BAL_001_STD_0.FACT.MONTHONBK_IDNN_HK ,
P_P01_D_BAL_001_STD_0.FACT.REL_MNGE_EMPL_IDNN_HK ,P_P01_D_BAL_001_STD_0.FACT.PRIM_CUST_ANZI_IDNN_HK ,
P_P01_D_BAL_001_STD_0.FACT.PRIM_CUST_IDNN_HK ,P_P01_D_BAL_001_STD_0.FACT.REL_MNGE_DEPT_IDNN_HK ,
P_P01_D_BAL_001_STD_0.FACT.GL_ACCT_IDNN_HK ,P_P01_D_BAL_001_STD_0.FACT.GL_PRJC_IDNN_HK ,
P_P01_D_BAL_001_STD_0.FACT.BUSN_UNIT_IDNN_HK ,P_P01_D_BAL_001_STD_0.FACT.AFLT_IDNN_HK ,
P_P01_D_BAL_001_STD_0.FACT.CNCY_IDNN_HK ,P_P01_D_BAL_001_STD_0.FACT.DEPT_IDNN_HK ,
P_P01_D_BAL_001_STD_0.FACT.GL_OPER_UNIT_IDNN_HK ,P_P01_D_BAL_001_STD_0.FACT.MNTH_END_D ,
P_P01_D_BAL_001_STD_0.FACT.MNTH_OPEN_D ,P_P01_D_BAL_001_STD_0.FACT.GL_PDCT_IDNN_HK ,
P_P01_D_BAL_001_STD_0.FACT.ACCT_OPEN_DEPT_IDNN_HK ,P_P01_D_BAL_001_STD_0.FACT.ARRS_IDNN_HK ,
MAX(P_P01_D_BAL_001_STD_0.FACT.CYCL_POIT_D )(DATE, NAMED MAX_CYCL_POIT_D ),
MAX(P_P01_D_BAL_001_STD_0.FACT.CYCL_POIT_ARRS_IDNN_HK )(CHAR(32), CHARACTER SET LATIN, NOT CASESPECIFIC, NAMED MAX_CYCL_POIT_ARRS_IDNN_HK ),
SUM(( CASE WHEN (P_P01_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'CLSE_BALN_A') THEN (P_P01_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED CLSE_BALN_A ),
SUM(( CASE WHEN (P_P01_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'LIMT_A') THEN (P_P01_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED LIMT_A ),
SUM(( CASE WHEN (P_P01_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'XPOS_ACCT_Q') THEN (P_P01_D_BAL_001_STD_0.FACT.MSUR_Q ) ELSE (0 ) END ))(FLOAT, NAMED XPOS_ACCT_Q ),
SUM(( CASE WHEN (P_P01_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'CRCD_INUSE_Q') THEN (P_P01_D_BAL_001_STD_0.FACT.MSUR_Q ) ELSE (0 ) END ))(FLOAT, NAMED CRCD_INUSE_Q ),
SUM(( CASE WHEN (P_P01_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'ADD_CARD_FEE_A') THEN (P_P01_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED ADD_CARD_FEE_A ),
SUM(( CASE WHEN (P_P01_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'ADD_CARD_FRFD_A') THEN (P_P01_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED ADD_CARD_FRFD_A ),
SUM(( CASE WHEN (P_P01_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'ANNL_FEE_A') THEN (P_P01_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED ANNL_FEE_A ),
SUM(( CASE WHEN (P_P01_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'ANNL_FRFD_A') THEN (P_P01_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED ANNL_FRFD_A ),
SUM(( CASE WHEN (P_P01_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'INT_CHRG_BALN_TRNF_A') THEN (P_P01_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED INT_CHRG_BALN_TRNF_A ),
SUM(( CASE WHEN (P_P01_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'INT_CHRG_CSAD_A') THEN (P_P01_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED INT_CHRG_CSAD_A ),
SUM(( CASE WHEN (P_P01_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'CASD_FEE_A') THEN (P_P01_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED CASD_FEE_A ),
SUM(( CASE WHEN (P_P01_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'CASD_FRFD_A') THEN (P_P01_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED CASD_FRFD_A ),
SUM(( CASE WHEN (P_P01_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'CYCL_POIT_BALN_A') THEN (P_P01_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED CYCL_POIT_BALN_A ),
SUM(( CASE WHEN (P_P01_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'INTL_TRAN_FEE_A') THEN (P_P01_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED INTL_TRAN_FEE_A ),
SUM(( CASE WHEN (P_P01_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'INTL_TRAN_FRFD_A') THEN (P_P01_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED INTL_TRAN_FRFD_A ),
SUM(( CASE WHEN (P_P01_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'LATE_PAYT_FEE_A') THEN (P_P01_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED LATE_PAYT_FEE_A ),
SUM(( CASE WHEN (P_P01_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'LATE_PAYT_FRFD_A') THEN (P_P01_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED LATE_PAYT_FRFD_A ),
SUM(( CASE WHEN (P_P01_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'LIMT_XCES_A') THEN (P_P01_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED LIMT_XCES_A ),
SUM(( CASE WHEN (P_P01_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'OVER_LIMT_FEE_A') THEN (P_P01_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED OVER_LIMT_FEE_A ),
SUM(( CASE WHEN (P_P01_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'OVER_LIMT_FRFD_A') THEN (P_P01_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED OVER_LIMT_FRFD_A ),
SUM(( CASE WHEN (P_P01_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'INT_CHRG_PUR_A') THEN (P_P01_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED INT_CHRG_PUR_A ),
SUM(( CASE WHEN (P_P01_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'QAN_FREQ_FLYR_FEE_A') THEN (P_P01_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED QAN_FREQ_FLYR_FEE_A ),
SUM(( CASE WHEN (P_P01_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'QAN_FREQ_FLYR_FRFD_A') THEN (P_P01_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED QAN_FREQ_FLYR_FRFD_A ),
SUM(( CASE WHEN (P_P01_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'INT_CHRG_RFND_A') THEN (P_P01_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED INT_CHRG_RFND_A ),
SUM(( CASE WHEN (P_P01_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'INT_CHRG_SPEC_RATE_A') THEN (P_P01_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED INT_CHRG_SPEC_RATE_A ),
SUM(( CASE WHEN (P_P01_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'UDRW_LIMT_A') THEN (P_P01_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED UDRW_LIMT_A ),
SUM(( CASE WHEN (P_P01_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'MNLY_DR_AVRG_CLSE_BALN_A') THEN (P_P01_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED MNLY_DR_AVRG_CLSE_BALN_A ),
SUM(( CASE WHEN (P_P01_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'MNLY_CR_AVRG_CLSE_BALN_A') THEN (P_P01_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED MNLY_CR_AVRG_CLSE_BALN_A ),
SUM(( CASE WHEN (P_P01_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'MNLY_NET_AVRG_CLSE_BALN_A') THEN (P_P01_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED MNLY_NET_AVRG_CLSE_BALN_A ),
SUM(( CASE WHEN (P_P01_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'FQTD_DR_AVRG_CLSE_BALN_A') THEN (P_P01_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED FQTD_DR_AVRG_CLSE_BALN_A ),
SUM(( CASE WHEN (P_P01_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'FQTD_CR_AVRG_CLSE_BALN_A') THEN (P_P01_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED FQTD_CR_AVRG_CLSE_BALN_A ),
SUM(( CASE WHEN (P_P01_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'FQTD_NET_AVRG_CLSE_BALN_A') THEN (P_P01_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED FQTD_NET_AVRG_CLSE_BALN_A ),
SUM(( CASE WHEN (P_P01_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'FYTD_DR_AVRG_CLSE_BALN_A') THEN (P_P01_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED FYTD_DR_AVRG_CLSE_BALN_A ),
SUM(( CASE WHEN (P_P01_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'FYTD_CR_AVRG_CLSE_BALN_A') THEN (P_P01_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED FYTD_CR_AVRG_CLSE_BALN_A ),
SUM(( CASE WHEN (P_P01_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'FYTD_NET_AVRG_CLSE_BALN_A') THEN (P_P01_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED FYTD_NET_AVRG_CLSE_BALN_A ),
SUM(( CASE WHEN (P_P01_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'INT_WROF_A') THEN (P_P01_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED INT_FEE_WROF_A ),
SUM(( CASE WHEN (P_P01_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'ANNL_FEE_WROF_A') THEN (P_P01_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED ANNL_FEE_WROF_A ),
SUM(( CASE WHEN (P_P01_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'LATE_PAYT_FEE_WROF_A') THEN (P_P01_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED LATE_PAYT_FEE_WROF_A ),
SUM(( CASE WHEN (P_P01_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'OPEN_BALN_A') THEN (P_P01_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED OPEN_BALN_A ),
SUM(( CASE WHEN (P_P01_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'INSR_FEE_WROF_A') THEN (P_P01_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED INSR_FEE_WROF_A ),
SUM(( CASE WHEN (P_P01_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'PRIN_WROF_A') THEN (P_P01_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED PRIN_WROF_A ),
SUM(( CASE WHEN (P_P01_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'COF_UDRW_LIQDP_A') THEN (P_P01_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED COF_UDRW_LIQDP_A ),
SUM(( CASE WHEN (P_P01_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'COF_CASH_AND_BASE_RATE_PREM_A') THEN (P_P01_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED COF_CASH_AND_BASE_RATE_PREM_A ),
SUM(( CASE WHEN (P_P01_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'COF_LGTM_FUND_PREM_A') THEN (P_P01_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED COF_LGTM_FUND_PREM_A ),
SUM(( CASE WHEN (P_P01_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'COF_LIQD_PREM_A') THEN (P_P01_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED COF_LIQD_PREM_A ),
SUM(( CASE WHEN (P_P01_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'INCG_FEE_A') THEN (P_P01_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED INCG_FEE_A ),
SUM(( CASE WHEN (P_P01_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK =  'SCHM_FEE_A') THEN (P_P01_D_BAL_001_STD_0.FACT.MSUR_A ) ELSE (0 ) END ))(DECIMAL(38,5), NAMED SCHM_FEE_A ) FROM 
(P_P01_D_BAL_001_STD_0.FACT_ACCT_MSUR_MNLY  FACT  INNER JOIN P_P01_D_BUS_001_STD_0.H_MSUR  MSUR  ON P_P01_D_BAL_001_STD_0.FACT.MSUR_IDNN_HK =  P_P01_D_BUS_001_STD_0.MSUR.MSUR_IDNN_HK )

WHERE ((((P_P01_D_BAL_001_STD_0.FACT.EXPY_D =  DATE '9999-12-31') AND  (P_P01_D_BUS_001_STD_0.MSUR.EXPY_D =  DATE '9999-12-31')) AND  (P_P01_D_BAL_001_STD_0.FACT.RECORD_DELETED_FLAG =  0 )) AND  (P_P01_D_BUS_001_STD_0.MSUR.RECORD_DELETED_FLAG =  0 )) AND  (P_P01_D_BUS_001_STD_0.MSUR.MSUR_IDNN_BK  IN ('CLSE_BALN_A',
'LIMT_A','XPOS_ACCT_Q','CRCD_INUSE_Q','ADD_CARD_FEE_A','ADD_CARD_FRFD_A',
'ANNL_FEE_A','ANNL_FRFD_A','INT_CHRG_BALN_TRNF_A','INT_CHRG_CSAD_A',
'CASD_FEE_A','CASD_FRFD_A','CYCL_POIT_BALN_A','INTL_TRAN_FEE_A',
'INTL_TRAN_FRFD_A','LATE_PAYT_FEE_A','LATE_PAYT_FRFD_A','LIMT_XCES_A',
'OVER_LIMT_FEE_A','OVER_LIMT_FRFD_A','INT_CHRG_PUR_A','QAN_FREQ_FLYR_FEE_A',
'QAN_FREQ_FLYR_FRFD_A','INT_CHRG_RFND_A','INT_CHRG_SPEC_RATE_A',
'UDRW_LIMT_A','MNLY_DR_AVRG_CLSE_BALN_A','MNLY_CR_AVRG_CLSE_BALN_A',
'MNLY_NET_AVRG_CLSE_BALN_A','FQTD_DR_AVRG_CLSE_BALN_A','FQTD_CR_AVRG_CLSE_BALN_A',
'FQTD_NET_AVRG_CLSE_BALN_A','FYTD_DR_AVRG_CLSE_BALN_A','FYTD_CR_AVRG_CLSE_BALN_A',
'FYTD_NET_AVRG_CLSE_BALN_A','INT_WROF_A','ANNL_FEE_WROF_A','LATE_PAYT_FEE_WROF_A',
'OPEN_BALN_A','INSR_FEE_WROF_A','PRIN_WROF_A','COF_UDRW_LIQDP_A',
'COF_CASH_AND_BASE_RATE_PREM_A','COF_LGTM_FUND_PREM_A','COF_LIQD_PREM_A',
'INCG_FEE_A','SCHM_FEE_A'))
GROUP BY P_P01_D_BAL_001_STD_0.FACT.ACCT_IDNN_HK ,P_P01_D_BAL_001_STD_0.FACT.GRD_PDCT_IDNN_HK ,
P_P01_D_BAL_001_STD_0.FACT.MONTHONBK_IDNN_HK ,P_P01_D_BAL_001_STD_0.FACT.REL_MNGE_EMPL_IDNN_HK ,
P_P01_D_BAL_001_STD_0.FACT.PRIM_CUST_ANZI_IDNN_HK ,P_P01_D_BAL_001_STD_0.FACT.PRIM_CUST_IDNN_HK ,
P_P01_D_BAL_001_STD_0.FACT.REL_MNGE_DEPT_IDNN_HK ,P_P01_D_BAL_001_STD_0.FACT.GL_ACCT_IDNN_HK ,
P_P01_D_BAL_001_STD_0.FACT.GL_PRJC_IDNN_HK ,P_P01_D_BAL_001_STD_0.FACT.BUSN_UNIT_IDNN_HK ,
P_P01_D_BAL_001_STD_0.FACT.AFLT_IDNN_HK ,P_P01_D_BAL_001_STD_0.FACT.CNCY_IDNN_HK ,
P_P01_D_BAL_001_STD_0.FACT.DEPT_IDNN_HK ,P_P01_D_BAL_001_STD_0.FACT.GL_OPER_UNIT_IDNN_HK ,
P_P01_D_BAL_001_STD_0.FACT.MNTH_END_D ,P_P01_D_BAL_001_STD_0.FACT.MNTH_OPEN_D ,
P_P01_D_BAL_001_STD_0.FACT.GL_PDCT_IDNN_HK ,P_P01_D_BAL_001_STD_0.FACT.ACCT_OPEN_DEPT_IDNN_HK ,
P_P01_D_BAL_001_STD_0.FACT.ARRS_IDNN_HK 
PRIMARY INDEX ( ACCT_IDNN_HK )
PARTITION BY RANGE_N(P_P01_D_BAL_001_STD_0.FACT.MNTH_END_D  BETWEEN 
DATE '2013-07-01' AND '2030-06-30' EACH INTERVAL '1' MONTH );

--
/* <sc-joinindex> P_P01_J_BAL_001_STD_0.FACT_CRCD_ACTV_TRAN_DALY_JRNLD </sc-joinindex> */
CREATE JOIN INDEX P_P01_J_BAL_001_STD_0.FACT_CRCD_ACTV_TRAN_DALY_JRNLD ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT P_P01_D_BAL_001_STD_0.FACT_CRCD_ACTV_TRAN_DALY.FNCL_TRAN_IDNN_HK ,
P_P01_D_BAL_001_STD_0.FACT_CRCD_ACTV_TRAN_DALY.JRNL_D ,P_P01_D_BAL_001_STD_0.FACT_CRCD_ACTV_TRAN_DALY.ROWID 
 FROM P_P01_D_BAL_001_STD_0.FACT_CRCD_ACTV_TRAN_DALY 
PRIMARY INDEX ( FNCL_TRAN_IDNN_HK )
PARTITION BY RANGE_N(P_P01_D_BAL_001_STD_0.FACT_CRCD_ACTV_TRAN_DALY.JRNL_D  BETWEEN 
DATE '1998-01-01' AND '2030-06-30' EACH INTERVAL '1' DAY ,
 NO RANGE);

--
/* <sc-joinindex> P_P01_J_BUS_001_STD_0.S_MSUR_DALY_SNAP_SSTJI1 </sc-joinindex> */
CREATE JOIN INDEX P_P01_J_BUS_001_STD_0.S_MSUR_DALY_SNAP_SSTJI1 ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT P_P01_D_BUS_001_STD_0.S_MSUR_DALY_SNAP.MSUR_IDNN_HK ,
P_P01_D_BUS_001_STD_0.S_MSUR_DALY_SNAP.MSTR_SRCE_SYST_C ,P_P01_D_BUS_001_STD_0.S_MSUR_DALY_SNAP.MSUR_QLFY_C ,
P_P01_D_BUS_001_STD_0.S_MSUR_DALY_SNAP.MSUR_CODE_IDNN_BK ,P_P01_D_BUS_001_STD_0.S_MSUR_DALY_SNAP.MSUR_A ,
P_P01_D_BUS_001_STD_0.S_MSUR_DALY_SNAP.MSUR_Q ,P_P01_D_BUS_001_STD_0.S_MSUR_DALY_SNAP.MSUR_R ,
P_P01_D_BUS_001_STD_0.S_MSUR_DALY_SNAP.SNAP_D ,P_P01_D_BUS_001_STD_0.S_MSUR_DALY_SNAP.EFFT_D ,
P_P01_D_BUS_001_STD_0.S_MSUR_DALY_SNAP.EXPY_D ,P_P01_D_BUS_001_STD_0.S_MSUR_DALY_SNAP.RECORD_DELETED_FLAG ,
P_P01_D_BUS_001_STD_0.S_MSUR_DALY_SNAP.ROW_SECU_ACCS_C ,P_P01_D_BUS_001_STD_0.S_MSUR_DALY_SNAP.ROWID 
 FROM P_P01_D_BUS_001_STD_0.S_MSUR_DALY_SNAP 
WHERE P_P01_D_BUS_001_STD_0.S_MSUR_DALY_SNAP.EXPY_D =  DATE '9999-12-31'
PRIMARY INDEX ( MSUR_IDNN_HK )
PARTITION BY RANGE_N(P_P01_D_BUS_001_STD_0.S_MSUR_DALY_SNAP.SNAP_D  BETWEEN 
DATE '2014-01-01' AND '2030-06-30' EACH INTERVAL '1' DAY ,
 NO RANGE);

--
/* <sc-joinindex> P_P01_J_RAW_001_STD_0.PREN_ACCT_JI </sc-joinindex> */
CREATE JOIN INDEX P_P01_J_RAW_001_STD_0.PREN_ACCT_JI ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT P_P01_D_RAW_001_STD_0.S_SAP_FNCL_TRAN_PREN_ZTB_PRE1.ACCT_IDNN_HK ,
P_P01_D_RAW_001_STD_0.S_SAP_FNCL_TRAN_PREN_ZTB_PRE1.ROWID 
 FROM P_P01_D_RAW_001_STD_0.S_SAP_FNCL_TRAN_PREN_ZTB_PRE1 
WHERE P_P01_D_RAW_001_STD_0.S_SAP_FNCL_TRAN_PREN_ZTB_PRE1.RECORD_DELETED_FLAG =  0 
PRIMARY INDEX ( ACCT_IDNN_HK );

--
/* <sc-joinindex> P_P01_J_SHR_001_STD_0.L_ACCT_MSUR_ACCT </sc-joinindex> */
CREATE JOIN INDEX P_P01_J_SHR_001_STD_0.L_ACCT_MSUR_ACCT ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT P_P01_D_SHR_001_STD_0.L_ACCT_MSUR_NEW.ACCT_IDNN_HK ,
P_P01_D_SHR_001_STD_0.L_ACCT_MSUR_NEW.MSUR_IDNN_HK ,P_P01_D_SHR_001_STD_0.L_ACCT_MSUR_NEW.MSTR_SRCE_SYST_C ,
P_P01_D_SHR_001_STD_0.L_ACCT_MSUR_NEW.ROWID 
 FROM P_P01_D_SHR_001_STD_0.L_ACCT_MSUR_NEW 
WHERE P_P01_D_SHR_001_STD_0.L_ACCT_MSUR_NEW.RECORD_DELETED_FLAG =  0 
PRIMARY INDEX ( ACCT_IDNN_HK );

--
/* <sc-joinindex> P_P01_J_SHR_001_STD_0.L_FNCL_TRAN_ACCT_REL_STJI </sc-joinindex> */
CREATE JOIN INDEX P_P01_J_SHR_001_STD_0.L_FNCL_TRAN_ACCT_REL_STJI ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT (P_P01_D_SHR_001_STD_0.L_FNCL_TRAN_ACCT_REL.ACCT_IDNN_HK ,
P_P01_D_SHR_001_STD_0.L_FNCL_TRAN_ACCT_REL.ROW_SECU_ACCS_C ,
P_P01_D_SHR_001_STD_0.L_FNCL_TRAN_ACCT_REL.MSTR_SRCE_SYST_C ,
P_P01_D_SHR_001_STD_0.L_FNCL_TRAN_ACCT_REL.EXPY_D ),(P_P01_D_SHR_001_STD_0.L_FNCL_TRAN_ACCT_REL.ROWID )
 FROM P_P01_D_SHR_001_STD_0.L_FNCL_TRAN_ACCT_REL 
WHERE P_P01_D_SHR_001_STD_0.L_FNCL_TRAN_ACCT_REL.RECORD_DELETED_FLAG =  0 
PRIMARY INDEX ( ACCT_IDNN_HK )

;

--
/* <sc-joinindex> P_P01_PDTRMLEAD.LH_SELECTION_VARIABLE_JIDX </sc-joinindex> */
CREATE JOIN INDEX P_P01_PDTRMLEAD.LH_SELECTION_VARIABLE_JIDX ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT (P_P01_PDTRMLEAD.LH_SELECTION_VARIABLE.Leaf_Segment_Id ,
P_P01_PDTRMLEAD.LH_SELECTION_VARIABLE.Paty_i ),(P_P01_PDTRMLEAD.LH_SELECTION_VARIABLE.ROWID )
 FROM P_P01_PDTRMLEAD.LH_SELECTION_VARIABLE 
PRIMARY INDEX ( Leaf_Segment_Id ,Paty_i )

;

--
/* <sc-joinindex> UDLMIDATA.KHORNH_HLS_PORTFOLIO_NIM_AJI1 </sc-joinindex> */
CREATE JOIN INDEX UDLMIDATA.KHORNH_HLS_PORTFOLIO_NIM_AJI1 ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT COUNT(*)(FLOAT, NAMED CountStar ),UDLMIDATA.KHORNH_HLS_PORTFOLIO_NIM.PATY_I ,
UDLMIDATA.KHORNH_HLS_PORTFOLIO_NIM.AS_AT ,SUM(UDLMIDATA.KHORNH_HLS_PORTFOLIO_NIM.GROSS_REVENUE )(DECIMAL(38,4), NAMED Annualised_HL_Revenue )
 FROM UDLMIDATA.KHORNH_HLS_PORTFOLIO_NIM 
GROUP BY UDLMIDATA.KHORNH_HLS_PORTFOLIO_NIM.PATY_I ,UDLMIDATA.KHORNH_HLS_PORTFOLIO_NIM.AS_AT 
PRIMARY INDEX ( PATY_I );

--
/* <sc-joinindex> UDMABTCH.KACH_CLNT_DVCE_JI1 </sc-joinindex> */
CREATE JOIN INDEX UDMABTCH.KACH_CLNT_DVCE_JI1 ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT Udmabtch.kdm.device_i ,Udmabtch.kdm.client_i ,Udmabtch.kdm.ROWID 
 FROM Udmabtch.kaching_client_device_main  kdm 
PRIMARY INDEX ( device_i );

--
/* <sc-joinindex> UDMABTCH.KACH_CLNT_PRFR_MAIN_JI1 </sc-joinindex> */
CREATE JOIN INDEX UDMABTCH.KACH_CLNT_PRFR_MAIN_JI1 ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT Udmabtch.kcp.client_pref_i ,Udmabtch.kcp.client_i ,
Udmabtch.kcp.ROWID 
 FROM Udmabtch.kaching_client_prefernce_main  kcp 
PRIMARY INDEX ( client_pref_i );

--
/* <sc-joinindex> UDMABTCH.NV_PRIC_PATY_ACCT </sc-joinindex> */
CREATE JOIN INDEX UDMABTCH.NV_PRIC_PATY_ACCT ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT Udmabtch.ab1.paty_i ,Udmabtch.ab1.acct_i ,Udmabtch.ab1.ROWID 
 FROM Udmabtch.wk_nv_pric_acct_mnth  ab1 
PRIMARY INDEX ( paty_i );

--
/* <sc-joinindex> UDMAMDT.STJI_EVNT_GRUP_ASSC_HIST_TMP </sc-joinindex> */
CREATE JOIN INDEX UDMAMDT.STJI_EVNT_GRUP_ASSC_HIST_TMP ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT UDMAMDT.ega.EVNT_GRUP_I ,UDMAMDT.ega.ROWID 
 FROM UDMAMDT.EVNT_GRUP_ASSC_HIST_TMP  ega 
PRIMARY INDEX ( EVNT_GRUP_I );

--
/* <sc-joinindex> UDMASTIG.MKT_CUST_PRFL_JI </sc-joinindex> */
CREATE JOIN INDEX UDMASTIG.MKT_CUST_PRFL_JI ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT COUNT(*)(FLOAT, NAMED CountStar ),UDMASTIG.MKT_CUST_PRFL.perd_d 
 FROM UDMASTIG.MKT_CUST_PRFL 
GROUP BY UDMASTIG.MKT_CUST_PRFL.perd_d 
PRIMARY INDEX ( perd_d );

--
/* <sc-joinindex> UDRMD.CD_DSPT_TRAN_RAW2_JI </sc-joinindex> */
CREATE JOIN INDEX UDRMD.CD_DSPT_TRAN_RAW2_JI ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT UDRMD.DSPT.TRAN_A ,UDRMD.DSPT.TRAN_C ,UDRMD.DSPT.TRAN_SUB_C ,
UDRMD.DSPT.ORIG_CURR_C ,UDRMD.DSPT.MERC_CNTY_C ,UDRMD.DSPT.ACCT_I ,
UDRMD.DSPT.TRAN_POST_D 
 FROM UDRMD.CD_DSPT_TRAN_RAW2  DSPT 
PRIMARY INDEX ( ACCT_I ,TRAN_POST_D );

--
/* <sc-joinindex> UDTDWRK.SJI_CLUSTA_ACCESS_LOG </sc-joinindex> */
CREATE JOIN INDEX UDTDWRK.SJI_CLUSTA_ACCESS_LOG ,FALLBACK ,CHECKSUM = DEFAULT, MAP = TD_MAP1 AS 
SELECT COUNT(*)(FLOAT, NAMED CountStar ),UDTDWRK.CLUSTA_ACCESS_LOG.log_timestamp ,
UDTDWRK.CLUSTA_ACCESS_LOG.email 
 FROM UDTDWRK.CLUSTA_ACCESS_LOG 
GROUP BY UDTDWRK.CLUSTA_ACCESS_LOG.log_timestamp ,UDTDWRK.CLUSTA_ACCESS_LOG.email 
PRIMARY INDEX ( log_timestamp );

