{{ config(materialized='view', tags=['DltCSE_APPT_HL_COND_APPR_FrmTMPAPPTHLCONDAPPR_HSCA']) }}

WITH 
tmp_cse_appt_hl_cond_appr AS (
	SELECT
	*
	FROM {{ source("ddnikescpd","tmp_cse_appt_hl_cond_appr")  }}),
cse_appt_hl_cond_appr AS (
	SELECT
	*
	FROM {{ source("dvnike_out","cse_appt_hl_cond_appr")  }}),
SrcTmpApptHlCondApprTera AS (SELECT A.APPT_I AS NEW_APPT_I, A.COND_APPR_F AS NEW_COND_APPR_F, A.COND_APPR_CONV_TO_FULL_D AS NEW_COND_APPR_CONV_TO_FULL_D, B.EFFT_D AS OLD_EFFT_D, CASE WHEN B.OLD_FLAG IS NULL THEN 'I' WHEN B.OLD_FLAG = 'Y' AND (COALESCE(A.COND_APPR_F, '') <> COALESCE(B.COND_APPR_F, '') OR COALESCE(A.COND_APPR_CONV_TO_FULL_D, CAST('1800-01-01' AS DATE)) <> COALESCE(B.COND_APPR_CONV_TO_FULL_D, CAST('1800-01-01' AS DATE))) THEN 'U' ELSE 'S' END AS REC_TYPE FROM TMP_CSE_APPT_HL_COND_APPR LEFT OUTER JOIN (SELECT APPT_I, COND_APPR_F, COND_APPR_CONV_TO_FULL_D, EFFT_D, 'Y' AS OLD_FLAG FROM CSE_APPT_HL_COND_APPR WHERE EXPY_D = '9999-12-31') AS B ON A.APPT_I = B.APPT_I WHERE REC_TYPE <> 'S')


SELECT * FROM SrcTmpApptHlCondApprTera