{{ config(materialized='view', tags=['LdREJT_CSE_COI_BUS_ENVI_EVNT']) }}

WITH FunRejectsNulls AS (
	SELECT
		FA_ENVISION_EVENT_ID as FA_ENVISION_EVENT_ID,
		FA_UNDERTAKING_ID as FA_UNDERTAKING_ID,
		FA_ENVISION_EVENT_CAT_ID as FA_ENVISION_EVENT_CAT_ID,
		CREATED_DATE as CREATED_DATE,
		CREATED_BY_STAFF_NUMBER as CREATED_BY_STAFF_NUMBER,
		COIN_REQUEST_ID as COIN_REQUEST_ID,
		ETL_D as ETL_D,
		ORIG_ETL_D as ORIG_ETL_D,
		EROR_C as EROR_C
	FROM {{ ref('SrcIdNullsDS') }}
	UNION ALL
	SELECT
		FA_ENVISION_EVENT_ID,
		FA_UNDERTAKING_ID,
		FA_ENVISION_EVENT_CAT_ID,
		CREATED_DATE,
		CREATED_BY_STAFF_NUMBER,
		COIN_REQUEST_ID,
		ETL_D,
		ORIG_ETL_D,
		EROR_C
	FROM {{ ref('SrcMappingRejectsDS') }}
	UNION ALL
	SELECT
		FA_ENVISION_EVENT_ID,
		FA_UNDERTAKING_ID,
		FA_ENVISION_EVENT_CAT_ID,
		CREATED_DATE,
		CREATED_BY_STAFF_NUMBER,
		COIN_REQUEST_ID,
		ETL_D,
		ORIG_ETL_D,
		EROR_C
	FROM {{ ref('DeltarejectsDS') }}
)

SELECT * FROM FunRejectsNulls