{{ config(materialized='view', tags=['LdREJT_CSE_COI_BUS_ENVI_EVNT']) }}

SELECT
	FA_ENVISION_EVENT_ID
	FA_UNDERTAKING_ID
	FA_ENVISION_EVENT_CAT_ID
	CREATED_DATE
	CREATED_BY_STAFF_NUMBER
	COIN_REQUEST_ID
	ETL_D
	ORIG_ETL_D
	EROR_C 
FROM {{ ref('ModConversions') }}