{{ config(materialized='view', tags=['DltAPPT_PDCTFrmTMP_APPT_PDCT']) }}

WITH ChangeCapture AS (
	SELECT
		COALESCE({{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_APPT_PDCT_I, {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_APPT_PDCT_I) AS NEW_APPT_PDCT_I,
		COALESCE({{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_DEBT_ABN_X, {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_DEBT_ABN_X) AS NEW_DEBT_ABN_X,
		COALESCE({{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_DEBT_BUSN_M, {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_DEBT_BUSN_M) AS NEW_DEBT_BUSN_M,
		COALESCE({{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_SMPL_APPT_F, {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_SMPL_APPT_F) AS NEW_SMPL_APPT_F,
		COALESCE({{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_JOB_COMM_CATG_C, {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_JOB_COMM_CATG_C) AS NEW_JOB_COMM_CATG_C,
		COALESCE({{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_APPT_QLFY_C, {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_APPT_QLFY_C) AS NEW_APPT_QLFY_C,
		COALESCE({{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_ACQR_TYPE_C, {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_ACQR_TYPE_C) AS NEW_ACQR_TYPE_C,
		COALESCE({{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_ACQR_ADHC_X, {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_ACQR_ADHC_X) AS NEW_ACQR_ADHC_X,
		COALESCE({{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_ACQR_SRCE_C, {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_ACQR_SRCE_C) AS NEW_ACQR_SRCE_C,
		COALESCE({{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_PDCT_N, {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_PDCT_N) AS NEW_PDCT_N,
		COALESCE({{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_APPT_I, {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_APPT_I) AS NEW_APPT_I,
		COALESCE({{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_SRCE_SYST_C, {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_SRCE_SYST_C) AS NEW_SRCE_SYST_C,
		COALESCE({{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_SRCE_SYST_APPT_PDCT_I, {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_SRCE_SYST_APPT_PDCT_I) AS NEW_SRCE_SYST_APPT_PDCT_I,
		COALESCE({{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_LOAN_FNDD_METH_C, {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_LOAN_FNDD_METH_C) AS NEW_LOAN_FNDD_METH_C,
		COALESCE({{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_NEW_ACCT_F, {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_NEW_ACCT_F) AS NEW_NEW_ACCT_F,
		COALESCE({{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_BROK_PATY_I, {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_BROK_PATY_I) AS NEW_BROK_PATY_I,
		COALESCE({{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_COPY_FROM_OTHR_APPT_F, {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_COPY_FROM_OTHR_APPT_F) AS NEW_COPY_FROM_OTHR_APPT_F,
		COALESCE({{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_APPT_PDCT_CATG_C, {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_APPT_PDCT_CATG_C) AS NEW_APPT_PDCT_CATG_C,
		COALESCE({{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_APPT_PDCT_DURT_C, {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_APPT_PDCT_DURT_C) AS NEW_APPT_PDCT_DURT_C,
		COALESCE({{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_ASES_D, {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_ASES_D) AS NEW_ASES_D,
		CASE
			WHEN {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_APPT_PDCT_I IS NULL THEN '1'
			WHEN {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_APPT_PDCT_I IS NULL THEN '2'
			WHEN ({{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_APPT_PDCT_I = {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_APPT_PDCT_I) AND ({{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_DEBT_ABN_X <> {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_DEBT_ABN_X OR {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_DEBT_BUSN_M <> {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_DEBT_BUSN_M OR {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_JOB_COMM_CATG_C <> {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_JOB_COMM_CATG_C OR {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_APPT_QLFY_C <> {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_APPT_QLFY_C OR {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_ACQR_TYPE_C <> {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_ACQR_TYPE_C OR {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_ACQR_ADHC_X <> {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_ACQR_ADHC_X OR {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_ACQR_SRCE_C <> {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_ACQR_SRCE_C OR {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_PDCT_N <> {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_PDCT_N OR {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_APPT_I <> {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_APPT_I OR {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_SRCE_SYST_C <> {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_SRCE_SYST_C OR {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_SRCE_SYST_APPT_PDCT_I <> {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_SRCE_SYST_APPT_PDCT_I OR {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_LOAN_FNDD_METH_C <> {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_LOAN_FNDD_METH_C OR {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_NEW_ACCT_F <> {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_NEW_ACCT_F OR {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_BROK_PATY_I <> {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_BROK_PATY_I OR {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_COPY_FROM_OTHR_APPT_F <> {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_COPY_FROM_OTHR_APPT_F OR {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_SMPL_APPT_F <> {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_SMPL_APPT_F OR {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_APPT_PDCT_CATG_C <> {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_APPT_PDCT_CATG_C OR {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_APPT_PDCT_DURT_C <> {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_APPT_PDCT_DURT_C OR {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_ASES_D <> {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_ASES_D) THEN '3'
			WHEN {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_APPT_PDCT_I = {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_APPT_PDCT_I AND {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_DEBT_ABN_X = {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_DEBT_ABN_X AND {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_DEBT_BUSN_M = {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_DEBT_BUSN_M AND {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_JOB_COMM_CATG_C = {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_JOB_COMM_CATG_C AND {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_APPT_QLFY_C = {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_APPT_QLFY_C AND {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_ACQR_TYPE_C = {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_ACQR_TYPE_C AND {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_ACQR_ADHC_X = {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_ACQR_ADHC_X AND {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_ACQR_SRCE_C = {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_ACQR_SRCE_C AND {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_PDCT_N = {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_PDCT_N AND {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_APPT_I = {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_APPT_I AND {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_SRCE_SYST_C = {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_SRCE_SYST_C AND {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_SRCE_SYST_APPT_PDCT_I = {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_SRCE_SYST_APPT_PDCT_I AND {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_LOAN_FNDD_METH_C = {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_LOAN_FNDD_METH_C AND {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_NEW_ACCT_F = {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_NEW_ACCT_F AND {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_BROK_PATY_I = {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_BROK_PATY_I AND {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_COPY_FROM_OTHR_APPT_F = {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_COPY_FROM_OTHR_APPT_F AND {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_SMPL_APPT_F = {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_SMPL_APPT_F AND {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_APPT_PDCT_CATG_C = {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_APPT_PDCT_CATG_C AND {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_APPT_PDCT_DURT_C = {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_APPT_PDCT_DURT_C AND {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_ASES_D = {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_ASES_D THEN '0'
		END AS change_code 
	FROM {{ ref('{{ ref('CpyApptPdct') }}') }} 
	FULL OUTER JOIN {{ ref('{{ ref('CpyApptPdct') }}') }} 
	ON {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_APPT_PDCT_I = {{ ref('{{ ref('CpyApptPdct') }}') }}.NEW_APPT_PDCT_I
	WHERE change_code = '1' OR change_code = '3'
)

SELECT * FROM ChangeCapture