{{ config(materialized='view', tags=['LdREJT_CCC_BUS_APP_PROD_BAL_XFER']) }}

WITH FunCCApptProdBalXferIdNulls AS (
	SELECT
		CC_APP_PROD_BAL_XFER_ID as CC_APP_PROD_BAL_XFER_ID,
		BAL_XFER_OPTION_CAT_ID as BAL_XFER_OPTION_CAT_ID,
		XFER_AMT as XFER_AMT,
		BAL_XFER_INSTITUTION_CAT_ID as BAL_XFER_INSTITUTION_CAT_ID,
		CC_APP_PROD_ID as CC_APP_PROD_ID,
		CC_APP_ID as CC_APP_ID,
		ETL_D as ETL_D,
		ORIG_ETL_D as ORIG_ETL_D,
		EROR_C as EROR_C
	FROM {{ ref('RejCCAppProdBalXferIdNullsDS') }}
	UNION ALL
	SELECT
		CC_APP_PROD_BAL_XFER_ID,
		BAL_XFER_OPTION_CAT_ID,
		XFER_AMT,
		BAL_XFER_INSTITUTION_CAT_ID,
		CC_APP_PROD_ID,
		CC_APP_ID,
		ETL_D,
		ORIG_ETL_D,
		EROR_C
	FROM {{ ref('SrcCCApptProdBalXferRejectsDS') }}
)

SELECT * FROM FunCCApptProdBalXferIdNulls