USE ROLE r_dev_npd_d12_gdwmig;

CREATE OR REPLACE PROCEDURE npd_d12_dmn_gdwmig.lcl.sp_bteq_derv_acct_paty_04_pop_curr_tabl(
    EXTR_D STRING DEFAULT '2023-01-01'
)
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
  error_code INTEGER DEFAULT 0;
BEGIN
  -- Populate staging table with rows from all sources effective on extract date
  -- Original Author: Helen Zak, Version 1.0 (04/06/2013)
  
  -- 1. Clean and populate ACCT_PATY_DEDUP with deduplicated ACCT_PATY data
  DELETE FROM NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_PATY_DEDUP;
  
  INSERT INTO NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_PATY_DEDUP
  SELECT AP.ACCT_I,
         PATY_I,
         AP.ACCT_I AS ASSC_ACCT_I,
         PATY_ACCT_REL_C,
         'N',
         SRCE_SYST_C,
         EFFT_D,
         CASE
           WHEN EFFT_D = EXPY_D THEN EXPY_D
           WHEN EXPY_D >= :EXTR_D THEN DATE '9999-12-31'
           ELSE EXPY_D
         END AS EXPY_D,
         AP.ROW_SECU_ACCS_C
  FROM NPD_D12_DMN_GDWMIG_IBRG_V.pvtech.ACCT_PATY AP
  WHERE :EXTR_D BETWEEN AP.EFFT_D AND AP.EXPY_D
  QUALIFY ROW_NUMBER() OVER (PARTITION BY ACCT_I, PATY_I, PATY_ACCT_REL_C ORDER BY EFFT_D) = 1;
  
  -- 2. Initialize main table with ACCT_PATY data
  DELETE FROM NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.DERV_ACCT_PATY_CURR;
  
  INSERT INTO NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.DERV_ACCT_PATY_CURR
  SELECT ACCT_I, PATY_I, ASSC_ACCT_I, PATY_ACCT_REL_C, PRFR_PATY_F,
         SRCE_SYST_C, EFFT_D, EXPY_D, ROW_SECU_ACCS_C
  FROM NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_PATY_DEDUP;
  
  -- 3. BPS accounts - convert using ACCT_REL and XREF table
  INSERT INTO NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.DERV_ACCT_PATY_CURR
  SELECT AX.BPS_ACCT_I AS ACCT_I,
         AP.PATY_I,
         CBS_ACCT_I AS ASSC_ACCT_I,
         AP.PATY_ACCT_REL_C,
         'N' AS PRFR_PATY_F,
         AP.SRCE_SYST_C,
         (CASE WHEN AP.EFFT_D > AX.EFFT_D THEN AP.EFFT_D ELSE AX.EFFT_D END) AS EFFT_D,
         (CASE WHEN AP.EXPY_D < AX.EXPY_D THEN AP.EXPY_D ELSE AX.EXPY_D END) AS EXPY_D,
         AP.ROW_SECU_ACCS_C
  FROM (
    SELECT ACCT_I, PATY_I, PATY_ACCT_REL_C, SRCE_SYST_C, EFFT_D,
           CASE
             WHEN EFFT_D = EXPY_D THEN EXPY_D
             WHEN EXPY_D >= :EXTR_D THEN DATE '9999-12-31'
             ELSE EXPY_D
           END AS EXPY_D,
           ROW_SECU_ACCS_C
    FROM NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_PATY_DEDUP
    WHERE :EXTR_D BETWEEN EFFT_D AND EXPY_D
  ) AP
  JOIN (
    SELECT CBS_ACCT_I, BPS_ACCT_I, EFFT_D,
           CASE
             WHEN EFFT_D = EXPY_D THEN EXPY_D
             WHEN EXPY_D >= :EXTR_D THEN DATE '9999-12-31'
             ELSE EXPY_D
           END AS EXPY_D
    FROM NPD_D12_DMN_GDWMIG_IBRG_V.pvtech.ACCT_XREF_BPS_CBS
    WHERE :EXTR_D BETWEEN EFFT_D AND EXPY_D
  ) AX ON AP.ACCT_I = AX.CBS_ACCT_I
  WHERE (
    (AP.EFFT_D BETWEEN AX.EFFT_D AND AX.EXPY_D)
    OR (AX.EFFT_D BETWEEN AP.EFFT_D AND AP.EXPY_D)
  )
  GROUP BY 1,2,3,4,5,6,7,8,9
  
  UNION ALL
  
  SELECT AR.OBJC_ACCT_I AS ACCT_I,
         BPS.PATY_I,
         BPS.CBS_ACCT_I AS ASSC_ACCT_I,
         BPS.PATY_ACCT_REL_C,
         'N' AS PRFR_PATY_F,
         BPS.SRCE_SYST_C,
         (CASE WHEN AR.EFFT_D > BPS.EFFT_D THEN AR.EFFT_D ELSE BPS.EFFT_D END) AS EFFT_D,
         (CASE WHEN AR.EXPY_D < BPS.EXPY_D THEN AR.EXPY_D ELSE BPS.EXPY_D END) AS EXPY_D,
         BPS.ROW_SECU_ACCS_C
  FROM (
    SELECT SUBJ_ACCT_I, OBJC_ACCT_I, EFFT_D,
           CASE
             WHEN EFFT_D = EXPY_D THEN EXPY_D
             WHEN EXPY_D >= :EXTR_D THEN DATE '9999-12-31'
             ELSE EXPY_D
           END AS EXPY_D
    FROM NPD_D12_DMN_GDWMIG_IBRG_V.pvtech.ACCT_REL
    WHERE TRIM(REL_C) = 'FLBLL' AND :EXTR_D BETWEEN EFFT_D AND EXPY_D
  ) AR
  JOIN (
    SELECT AX.BPS_ACCT_I, CBS_ACCT_I, AP.PATY_I, AP.PATY_ACCT_REL_C, AP.SRCE_SYST_C,
           (CASE WHEN AP.EFFT_D > AX.EFFT_D THEN AP.EFFT_D ELSE AX.EFFT_D END) AS EFFT_D,
           (CASE WHEN AP.EXPY_D < AX.EXPY_D THEN AP.EXPY_D ELSE AX.EXPY_D END) AS EXPY_D,
           AP.ROW_SECU_ACCS_C
    FROM (
      SELECT ACCT_I, PATY_I, PATY_ACCT_REL_C, SRCE_SYST_C, EFFT_D,
             CASE
               WHEN EFFT_D = EXPY_D THEN EXPY_D
               WHEN EXPY_D >= :EXTR_D THEN DATE '9999-12-31'
               ELSE EXPY_D
             END AS EXPY_D,
             ROW_SECU_ACCS_C
      FROM NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_PATY_DEDUP
      WHERE :EXTR_D BETWEEN EFFT_D AND EXPY_D
    ) AP
    JOIN (
      SELECT CBS_ACCT_I, BPS_ACCT_I, EFFT_D,
             CASE
               WHEN EFFT_D = EXPY_D THEN EXPY_D
               WHEN EXPY_D >= :EXTR_D THEN DATE '9999-12-31'
               ELSE EXPY_D
             END AS EXPY_D
      FROM NPD_D12_DMN_GDWMIG_IBRG_V.pvtech.ACCT_XREF_BPS_CBS
      WHERE :EXTR_D BETWEEN EFFT_D AND EXPY_D
    ) AX ON AP.ACCT_I = AX.CBS_ACCT_I
    WHERE (
      (AP.EFFT_D BETWEEN AX.EFFT_D AND AX.EXPY_D)
      OR (AX.EFFT_D BETWEEN AP.EFFT_D AND AP.EXPY_D)
    )
    GROUP BY 1,2,3,4,5,6,7,8
  ) BPS ON AR.SUBJ_ACCT_I = BPS.BPS_ACCT_I
  WHERE (
    (AR.EFFT_D BETWEEN BPS.EFFT_D AND BPS.EXPY_D)
    OR (BPS.EFFT_D BETWEEN AR.EFFT_D AND AR.EXPY_D)
  )
  GROUP BY 1,2,3,4,5,6,7,8,9;

  
  -- 4. CLS accounts - convert using CLS_FCLY and CLS_UNID_PATY
  INSERT INTO NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.DERV_ACCT_PATY_CURR
  SELECT CLS.ACCT_I,
         AP.PATY_I,
         CLS.GDW_ACCT_I AS ASSC_ACCT_I,
         AP.PATY_ACCT_REL_C,
         'N' AS PRFR_PATY_F,
         AP.SRCE_SYST_C,
         (CASE WHEN AP.EFFT_D > CLS.EFFT_D THEN AP.EFFT_D ELSE CLS.EFFT_D END) AS EFFT_D,
         (CASE WHEN AP.EXPY_D < CLS.EXPY_D THEN AP.EXPY_D ELSE CLS.EXPY_D END) AS EXPY_D,
         AP.ROW_SECU_ACCS_C
  FROM (
    SELECT ACCT_I, PATY_I, PATY_ACCT_REL_C, SRCE_SYST_C, EFFT_D,
           CASE
             WHEN EFFT_D = EXPY_D THEN EXPY_D
             WHEN EXPY_D >= :EXTR_D THEN DATE '9999-12-31'
             ELSE EXPY_D
           END AS EXPY_D,
           ROW_SECU_ACCS_C
    FROM NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_PATY_DEDUP
    WHERE :EXTR_D BETWEEN EFFT_D AND EXPY_D
  ) AP
  JOIN (
    SELECT CF.ACCT_I,
           'CLSCO'||TRIM(CUP.CRIS_DEBT_I) AS GDW_ACCT_I,
           (CASE WHEN CF.EFFT_D > CUP.EFFT_D THEN CF.EFFT_D ELSE CUP.EFFT_D END) AS EFFT_D,
           (CASE WHEN CF.EXPY_D < CUP.EXPY_D THEN CF.EXPY_D ELSE CUP.EXPY_D END) AS EXPY_D
    FROM (
      SELECT ACCT_I, SRCE_SYST_PATY_I, EFFT_D,
             CASE
               WHEN EFFT_D = EXPY_D THEN EXPY_D
               WHEN EXPY_D >= :EXTR_D THEN DATE '9999-12-31'
               ELSE EXPY_D
             END AS EXPY_D
      FROM NPD_D12_DMN_GDWMIG_IBRG_V.pvtech.CLS_FCLY
      WHERE :EXTR_D BETWEEN EFFT_D AND EXPY_D
    ) CF
    JOIN (
      SELECT SRCE_SYST_PATY_I, CRIS_DEBT_I, EFFT_D,
             CASE
               WHEN EFFT_D = EXPY_D THEN EXPY_D
               WHEN EXPY_D >= :EXTR_D THEN DATE '9999-12-31'
               ELSE EXPY_D
             END AS EXPY_D
      FROM NPD_D12_DMN_GDWMIG_IBRG_V.pvtech.CLS_UNID_PATY
      WHERE :EXTR_D BETWEEN EFFT_D AND EXPY_D
    ) CUP ON CUP.SRCE_SYST_PATY_I = CF.SRCE_SYST_PATY_I
    WHERE (
      (CUP.EFFT_D BETWEEN CF.EFFT_D AND CF.EXPY_D)
      OR (CF.EFFT_D BETWEEN CUP.EFFT_D AND CUP.EXPY_D)
    )
    GROUP BY 1,2,3,4
  ) AS CLS ON CLS.GDW_ACCT_I = AP.ACCT_I
  WHERE (
    (AP.EFFT_D BETWEEN CLS.EFFT_D AND CLS.EXPY_D)
    OR (CLS.EFFT_D BETWEEN AP.EFFT_D AND AP.EXPY_D)
  )
  GROUP BY 1,2,3,4,5,6,7,8,9;

  
  -- 5. MAS accounts - convert using ACCT_XREF_MAS_DAR and DAR_ACCT
  INSERT INTO NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.DERV_ACCT_PATY_CURR
  SELECT DAR.MERC_ACCT_I AS ACCT_I,
         AP.PATY_I,
         DAR.MAS_MERC_ACCT_I AS ASSC_ACCT_I,
         AP.PATY_ACCT_REL_C,
         'N' AS PRFR_PATY_F,
         AP.SRCE_SYST_C,
         (CASE WHEN AP.EFFT_D > DAR.EFFT_D THEN AP.EFFT_D ELSE DAR.EFFT_D END) AS EFFT_D,
         (CASE WHEN AP.EXPY_D < DAR.EXPY_D THEN AP.EXPY_D ELSE DAR.EXPY_D END) AS EXPY_D,
         AP.ROW_SECU_ACCS_C
  FROM (
    SELECT ACCT_I, PATY_I, PATY_ACCT_REL_C, SRCE_SYST_C, EFFT_D,
           CASE
             WHEN EFFT_D = EXPY_D THEN EXPY_D
             WHEN EXPY_D >= :EXTR_D THEN DATE '9999-12-31'
             ELSE EXPY_D
           END AS EXPY_D,
           ROW_SECU_ACCS_C
    FROM NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_PATY_DEDUP
    WHERE :EXTR_D BETWEEN EFFT_D AND EXPY_D
  ) AP
  JOIN (
    SELECT DA.MERC_ACCT_I,
           AX.MAS_MERC_ACCT_I,
           (CASE WHEN DA.EFFT_D > AX.EFFT_D THEN DA.EFFT_D ELSE AX.EFFT_D END) AS EFFT_D,
           (CASE WHEN DA.EXPY_D < AX.EXPY_D THEN DA.EXPY_D ELSE AX.EXPY_D END) AS EXPY_D
    FROM (
      SELECT MERC_ACCT_I, EFFT_D,
             CASE
               WHEN EFFT_D = EXPY_D THEN EXPY_D
               WHEN EXPY_D >= :EXTR_D THEN DATE '9999-12-31'
               ELSE EXPY_D
             END AS EXPY_D
      FROM NPD_D12_DMN_GDWMIG_IBRG_V.pvtech.DAR_ACCT
      WHERE :EXTR_D BETWEEN EFFT_D AND EXPY_D
    ) DA
    JOIN (
      SELECT MAS_MERC_ACCT_I, DAR_ACCT_I, EFFT_D,
             CASE
               WHEN EFFT_D = EXPY_D THEN EXPY_D
               WHEN EXPY_D >= :EXTR_D THEN DATE '9999-12-31'
               ELSE EXPY_D
             END AS EXPY_D
      FROM NPD_D12_DMN_GDWMIG_IBRG_V.pvtech.ACCT_XREF_MAS_DAR
      WHERE :EXTR_D BETWEEN EFFT_D AND EXPY_D
    ) AX ON AX.DAR_ACCT_I = DA.MERC_ACCT_I
    WHERE (
      (AX.EFFT_D BETWEEN DA.EFFT_D AND DA.EXPY_D)
      OR (DA.EFFT_D BETWEEN AX.EFFT_D AND AX.EXPY_D)
    )
    GROUP BY 1,2,3,4
  ) AS DAR ON DAR.MAS_MERC_ACCT_I = AP.ACCT_I
  WHERE (
    (AP.EFFT_D BETWEEN DAR.EFFT_D AND DAR.EXPY_D)
    OR (DAR.EFFT_D BETWEEN AP.EFFT_D AND AP.EXPY_D)
  );

  -- 6. ACCT_REL processing with SUBJ_ACCT_I using GRD_GNRC_MAP_DERV_PATY_REL
  -- Convert using ACCT_REL and SUBJ_ACCT_I. The values of REL_C are stored in GRD_GNRC_MAP_DERV_PATY_REL
  
  INSERT INTO NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.DERV_ACCT_PATY_CURR
  SELECT AR.OBJC_ACCT_I AS ACCT_I,
         AP.PATY_I,
         AR.SUBJ_ACCT_I AS ASSC_ACCT_I,
         AP.PATY_ACCT_REL_C,
         'N' AS PRFR_PATY_F,
         AP.SRCE_SYST_C,
         (CASE WHEN AR.EFFT_D > AP.EFFT_D THEN AR.EFFT_D ELSE AP.EFFT_D END) AS EFFT_D,
         (CASE WHEN AR.EXPY_D < AP.EXPY_D THEN AR.EXPY_D ELSE AP.EXPY_D END) AS EXPY_D,
         AP.ROW_SECU_ACCS_C
  FROM (
    SELECT ACCT_I, PATY_I, PATY_ACCT_REL_C, SRCE_SYST_C, EFFT_D,
           CASE
             WHEN EFFT_D = EXPY_D THEN EXPY_D
             WHEN EXPY_D >= :EXTR_D THEN DATE '9999-12-31'
             ELSE EXPY_D
           END AS EXPY_D,
           ROW_SECU_ACCS_C
    FROM NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_PATY_DEDUP
    WHERE :EXTR_D BETWEEN EFFT_D AND EXPY_D
  ) AP
  JOIN (
    SELECT AR1.SUBJ_ACCT_I, AR1.OBJC_ACCT_I, AR1.EFFT_D,
           CASE
             WHEN AR1.EFFT_D = AR1.EXPY_D THEN AR1.EXPY_D
             WHEN AR1.EXPY_D >= :EXTR_D THEN DATE '9999-12-31'
             ELSE AR1.EXPY_D
           END AS EXPY_D
    FROM NPD_D12_DMN_GDWMIG_IBRG_V.pvtech.ACCT_REL AR1
    JOIN NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.GRD_GNRC_MAP_DERV_PATY_REL GGM
      ON TRIM(AR1.REL_C) = GGM.REL_C
     AND GGM.ACCT_I_C = 'SUBJ'
     AND :EXTR_D BETWEEN AR1.EFFT_D AND AR1.EXPY_D
  ) AR
    ON AR.SUBJ_ACCT_I = AP.ACCT_I
  WHERE (
    (AR.EFFT_D BETWEEN AP.EFFT_D AND AP.EXPY_D) 
    OR (AP.EFFT_D BETWEEN AR.EFFT_D AND AR.EXPY_D)
  )
  GROUP BY 1,2,3,4,5,6,7,8,9;

  -- 7. ACCT_REL processing with OBJC_ACCT_I using GRD_GNRC_MAP_DERV_PATY_REL
  -- Convert using ACCT_REL and OBJC_ACCT_I. The values of REL_C are stored in GRD_GNRC_MAP_DERV_PATY_REL
  
  INSERT INTO NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.DERV_ACCT_PATY_CURR
  SELECT AR.SUBJ_ACCT_I AS ACCT_I,
         AP.PATY_I,
         AR.OBJC_ACCT_I AS ASSC_ACCT_I,
         AP.PATY_ACCT_REL_C,
         'N' AS PRFR_PATY_F,
         AP.SRCE_SYST_C,
         (CASE WHEN AR.EFFT_D > AP.EFFT_D THEN AR.EFFT_D ELSE AP.EFFT_D END) AS EFFT_D,
         (CASE WHEN AR.EXPY_D < AP.EXPY_D THEN AR.EXPY_D ELSE AP.EXPY_D END) AS EXPY_D,
         AP.ROW_SECU_ACCS_C
  FROM (
    SELECT ACCT_I, PATY_I, PATY_ACCT_REL_C, SRCE_SYST_C, EFFT_D,
           CASE
             WHEN EFFT_D = EXPY_D THEN EXPY_D
             WHEN EXPY_D >= :EXTR_D THEN DATE '9999-12-31'
             ELSE EXPY_D
           END AS EXPY_D,
           ROW_SECU_ACCS_C
    FROM NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_PATY_DEDUP
    WHERE :EXTR_D BETWEEN EFFT_D AND EXPY_D
  ) AP
  JOIN (
    SELECT AR1.SUBJ_ACCT_I, AR1.OBJC_ACCT_I, AR1.EFFT_D,
           CASE
             WHEN AR1.EFFT_D = AR1.EXPY_D THEN AR1.EXPY_D
             WHEN AR1.EXPY_D >= :EXTR_D THEN DATE '9999-12-31'
             ELSE AR1.EXPY_D
           END AS EXPY_D
    FROM NPD_D12_DMN_GDWMIG_IBRG_V.pvtech.ACCT_REL AR1
    JOIN NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.GRD_GNRC_MAP_DERV_PATY_REL GGM
      ON TRIM(AR1.REL_C) = GGM.REL_C
     AND GGM.ACCT_I_C = 'OBJC'
     AND :EXTR_D BETWEEN AR1.EFFT_D AND AR1.EXPY_D
  ) AR
    ON AR.OBJC_ACCT_I = AP.ACCT_I
  WHERE (
    (AR.EFFT_D BETWEEN AP.EFFT_D AND AP.EXPY_D) 
    OR (AP.EFFT_D BETWEEN AR.EFFT_D AND AR.EXPY_D)
  )
  GROUP BY 1,2,3,4,5,6,7,8,9;

  
  -- 8. THA accounts - populate staging table
  DELETE FROM NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_PATY_REL_THA;
  
  INSERT INTO NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_PATY_REL_THA
  SELECT THA_ACCT_I,
         TRAD_ACCT_I,
         EFFT_D,
         CASE
           WHEN EFFT_D = EXPY_D THEN EXPY_D
           WHEN EXPY_D >= :EXTR_D THEN DATE '9999-12-31'
           ELSE EXPY_D
         END AS EXPY_D
  FROM NPD_D12_DMN_GDWMIG_IBRG_V.pvtech.THA_ACCT
  WHERE :EXTR_D BETWEEN EFFT_D AND EXPY_D
  QUALIFY ROW_NUMBER() OVER (PARTITION BY THA_ACCT_I, EFFT_D ORDER BY TRAD_ACCT_I, CSL_CLNT_I DESC) = 1;

  -- 6a. Process THA date ranges - populate ACCT_PATY_THA_NEW_RNGE
  DELETE FROM NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_PATY_THA_NEW_RNGE;
  
  INSERT INTO NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_PATY_THA_NEW_RNGE
  SELECT THA_ACCT_I,
         TRAD_ACCT_I,
         EFFT_D,
         EXPY_D,
         CASE 
           WHEN NEW_EXPY_D IS NULL THEN EXPY_D
           WHEN NEW_EXPY_D <= EXPY_D AND NEW_EXPY_D > EFFT_D THEN NEW_EXPY_D - 1
           ELSE EXPY_D
         END AS NEW_EXPY_D
  FROM (
    SELECT THA_ACCT_I,
           TRAD_ACCT_I,
           EFFT_D,
           EXPY_D,
           MIN(EFFT_D) OVER(
             PARTITION BY THA_ACCT_I
             ORDER BY EFFT_D, EXPY_D
             ROWS BETWEEN 1 FOLLOWING AND UNBOUNDED FOLLOWING
           ) AS NEW_EXPY_D
    FROM NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_PATY_REL_THA
  ) T;

  -- 6b. Insert gap-filling records into ACCT_PATY_THA_NEW_RNGE
  INSERT INTO NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_PATY_THA_NEW_RNGE
  SELECT T1.THA_ACCT_I,
         T1.TRAD_ACCT_I,
         T1.NEW_EXPY_D + 1 AS EFFT_D,
         T1.EXPY_D,
         T1.EXPY_D AS NEW_EXPY_D
  FROM NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_PATY_THA_NEW_RNGE T1
  LEFT JOIN NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_PATY_THA_NEW_RNGE T2
    ON T1.THA_ACCT_I = T2.THA_ACCT_I
   AND T1.NEW_EXPY_D + 1 = T2.EFFT_D
  WHERE T1.NEW_EXPY_D < T1.EXPY_D 
    AND T1.NEW_EXPY_D > T1.EFFT_D
    AND T2.THA_ACCT_I IS NULL
  GROUP BY 1,2,3,4,5;

  -- 6c. Update ACCT_PATY_REL_THA with optimized ranges
  DELETE FROM NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_PATY_REL_THA;
  
  INSERT INTO NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_PATY_REL_THA
  SELECT THA_ACCT_I,
         MAX(TRAD_ACCT_I) AS TRAD_ACCT_I,
         EFFT_D,
         NEW_EXPY_D AS EXPY_D
  FROM NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_PATY_THA_NEW_RNGE
  GROUP BY 1,3,4;
  
  -- 7. Insert THA account mappings
  INSERT INTO NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.DERV_ACCT_PATY_CURR
  SELECT TA.THA_ACCT_I AS ACCT_I,
         AP.PATY_I,
         TA.TRAD_ACCT_I AS ASSC_ACCT_I,
         AP.PATY_ACCT_REL_C,
         'N' AS PRFR_PATY_F,
         AP.SRCE_SYST_C,
         (CASE WHEN TA.EFFT_D > AP.EFFT_D THEN TA.EFFT_D ELSE AP.EFFT_D END) AS EFFT_D,
         (CASE WHEN TA.EXPY_D < AP.EXPY_D THEN TA.EXPY_D ELSE AP.EXPY_D END) AS EXPY_D,
         AP.ROW_SECU_ACCS_C
  FROM (
    SELECT ACCT_I, PATY_I, PATY_ACCT_REL_C, SRCE_SYST_C, EFFT_D,
           CASE
             WHEN EFFT_D = EXPY_D THEN EXPY_D
             WHEN EXPY_D >= :EXTR_D THEN DATE '9999-12-31'
             ELSE EXPY_D
           END AS EXPY_D,
           ROW_SECU_ACCS_C
    FROM NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_PATY_DEDUP
    WHERE :EXTR_D BETWEEN EFFT_D AND EXPY_D
  ) AP
  JOIN NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_PATY_REL_THA TA ON TA.TRAD_ACCT_I = AP.ACCT_I
  WHERE (
    (TA.EFFT_D BETWEEN AP.EFFT_D AND AP.EXPY_D)
    OR (AP.EFFT_D BETWEEN TA.EFFT_D AND TA.EXPY_D)
  )
  GROUP BY 1,2,3,4,5,6,7,8,9;

  
  -- 9. Insert MID, MTX and LMS accounts using ACCT_UNID_PATY transformation
  INSERT INTO NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.DERV_ACCT_PATY_CURR
  SELECT XREF.ACCT_I,
         AP.PATY_I,
         XREF.ASSC_ACCT_I,
         AP.PATY_ACCT_REL_C,
         'N' AS PRFR_PATY_F,
         AP.SRCE_SYST_C,
         (CASE WHEN AP.EFFT_D > XREF.EFFT_D THEN AP.EFFT_D ELSE XREF.EFFT_D END) AS EFFT_D,
         (CASE WHEN AP.EXPY_D < XREF.EXPY_D THEN AP.EXPY_D ELSE XREF.EXPY_D END) AS EXPY_D,
         AP.ROW_SECU_ACCS_C
  FROM (
    SELECT ACCT_I, PATY_I, PATY_ACCT_REL_C, SRCE_SYST_C, EFFT_D,
           CASE
             WHEN EFFT_D = EXPY_D THEN EXPY_D
             WHEN EXPY_D >= :EXTR_D THEN DATE '9999-12-31'
             ELSE EXPY_D
           END AS EXPY_D,
           ROW_SECU_ACCS_C
    FROM NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_PATY_DEDUP
    WHERE :EXTR_D BETWEEN EFFT_D AND EXPY_D
  ) AP
  JOIN (
    SELECT XREF1.ACCT_I,
           XREF2.ASSC_ACCT_I,
           (CASE WHEN XREF2.EFFT_D > XREF1.EFFT_D THEN XREF2.EFFT_D ELSE XREF1.EFFT_D END) AS EFFT_D,
           (CASE WHEN XREF2.EXPY_D < XREF1.EXPY_D THEN XREF2.EXPY_D ELSE XREF1.EXPY_D END) AS EXPY_D
    FROM (
      SELECT ACCT_I, SRCE_SYST_PATY_I, SRCE_SYST_C, EFFT_D,
             CASE
               WHEN EFFT_D = EXPY_D THEN EXPY_D
               WHEN EXPY_D >= :EXTR_D THEN DATE '9999-12-31'
               ELSE EXPY_D
             END AS EXPY_D
      FROM NPD_D12_DMN_GDWMIG_IBRG_V.pvtech.ACCT_UNID_PATY
      WHERE :EXTR_D BETWEEN EFFT_D AND EXPY_D
    ) XREF1
    JOIN (
      SELECT ACCT_I AS ASSC_ACCT_I, SRCE_SYST_PATY_I, PATY_ACCT_REL_C, SRCE_SYST_C, ORIG_SRCE_SYST_C, EFFT_D,
             CASE
               WHEN EFFT_D = EXPY_D THEN EXPY_D
               WHEN EXPY_D >= :EXTR_D THEN DATE '9999-12-31'
               ELSE EXPY_D
             END AS EXPY_D
      FROM NPD_D12_DMN_GDWMIG_IBRG_V.pvtech.ACCT_UNID_PATY
      WHERE :EXTR_D BETWEEN EFFT_D AND EXPY_D
    ) XREF2 ON XREF2.SRCE_SYST_PATY_I = XREF1.SRCE_SYST_PATY_I
    JOIN NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.GRD_GNRC_MAP_DERV_UNID_PATY GGM 
      ON GGM.UNID_PATY_SRCE_SYST_C = XREF2.SRCE_SYST_C
     AND GGM.UNID_PATY_ACCT_REL_C = XREF2.PATY_ACCT_REL_C
     AND GGM.SRCE_SYST_C = XREF2.ORIG_SRCE_SYST_C
    WHERE XREF1.SRCE_SYST_C = GGM.SRCE_SYST_C
      AND ((XREF1.EFFT_D BETWEEN XREF2.EFFT_D AND XREF2.EXPY_D)
           OR (XREF2.EFFT_D BETWEEN XREF1.EFFT_D AND XREF1.EXPY_D))
  ) XREF ON XREF.ASSC_ACCT_I = AP.ACCT_I
  WHERE ((AP.EFFT_D BETWEEN XREF.EFFT_D AND XREF.EXPY_D)
         OR (XREF.EFFT_D BETWEEN AP.EFFT_D AND AP.EXPY_D))
  GROUP BY 1,2,3,4,5,6,7,8,9;

  
  -- 10. Include MOS account level mappings - Loan accounts
  INSERT INTO NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.DERV_ACCT_PATY_CURR
  SELECT AX.ACCT_I,
         AP.PATY_I,
         AX.ASSC_ACCT_I,
         AP.PATY_ACCT_REL_C,
         'N' AS PRFR_PATY_F,
         AP.SRCE_SYST_C,
         (CASE WHEN AP.EFFT_D > AX.EFFT_D THEN AP.EFFT_D ELSE AX.EFFT_D END) AS EFFT_D,
         (CASE WHEN AP.EXPY_D < AX.EXPY_D THEN AP.EXPY_D ELSE AX.EXPY_D END) AS EXPY_D,
         AP.ROW_SECU_ACCS_C
  FROM (
    SELECT ACCT_I, PATY_I, PATY_ACCT_REL_C, SRCE_SYST_C, EFFT_D,
           CASE
             WHEN EFFT_D = EXPY_D THEN EXPY_D
             WHEN EXPY_D >= :EXTR_D THEN DATE '9999-12-31'
             ELSE EXPY_D
           END AS EXPY_D,
           ROW_SECU_ACCS_C
    FROM NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_PATY_DEDUP
    WHERE :EXTR_D BETWEEN EFFT_D AND EXPY_D
  ) AP
  JOIN (
    -- Loan accounts processing
    SELECT T1.LOAN_I AS ACCT_I,
           UIP.ACCT_I AS ASSC_ACCT_I,
           (CASE WHEN UIP.EFFT_D > T1.EFFT_D THEN UIP.EFFT_D ELSE T1.EFFT_D END) AS EFFT_D,
           (CASE WHEN UIP.EXPY_D < T1.EXPY_D THEN UIP.EXPY_D ELSE T1.EXPY_D END) AS EXPY_D
    FROM (
      SELECT LOAN.LOAN_I,
             FCLY.SRCE_SYST_PATY_I,
             (CASE WHEN LOAN.EFFT_D > FCLY.EFFT_D THEN LOAN.EFFT_D ELSE FCLY.EFFT_D END) AS EFFT_D,
             (CASE WHEN LOAN.EXPY_D < FCLY.EXPY_D THEN LOAN.EXPY_D ELSE FCLY.EXPY_D END) AS EXPY_D
      FROM (
        SELECT LOAN_I, FCLY_I, EFFT_D,
               CASE
                 WHEN EFFT_D = EXPY_D THEN EXPY_D
                 WHEN EXPY_D >= :EXTR_D THEN DATE '9999-12-31'
                 ELSE EXPY_D
               END AS EXPY_D
        FROM NPD_D12_DMN_GDWMIG_IBRG_V.pvtech.MOS_LOAN
        WHERE :EXTR_D BETWEEN EFFT_D AND EXPY_D
      ) LOAN
      JOIN (
        SELECT SUBSTR(FCLY_I,1,14) AS MOS_FCLY_I, SRCE_SYST_PATY_I, EFFT_D,
               CASE
                 WHEN EFFT_D = EXPY_D THEN EXPY_D
                 WHEN EXPY_D >= :EXTR_D THEN DATE '9999-12-31'
                 ELSE EXPY_D
               END AS EXPY_D
        FROM NPD_D12_DMN_GDWMIG_IBRG_V.pvtech.MOS_FCLY
        WHERE :EXTR_D BETWEEN EFFT_D AND EXPY_D
      ) FCLY ON FCLY.MOS_FCLY_I = LOAN.FCLY_I
      WHERE ((FCLY.EFFT_D BETWEEN LOAN.EFFT_D AND LOAN.EXPY_D)
             OR (LOAN.EFFT_D BETWEEN FCLY.EFFT_D AND FCLY.EXPY_D))
    ) T1
    JOIN (
      SELECT ACCT_I, SRCE_SYST_PATY_I, EFFT_D,
             CASE
               WHEN EFFT_D = EXPY_D THEN EXPY_D
               WHEN EXPY_D >= :EXTR_D THEN DATE '9999-12-31'
               ELSE EXPY_D
             END AS EXPY_D
      FROM NPD_D12_DMN_GDWMIG_IBRG_V.pvtech.ACCT_UNID_PATY
      WHERE :EXTR_D BETWEEN EFFT_D AND EXPY_D
        AND TRIM(SRCE_SYST_C) = 'SAP'
        AND TRIM(PATY_ACCT_REL_C) = 'ACTO'
    ) UIP ON UIP.SRCE_SYST_PATY_I = T1.SRCE_SYST_PATY_I
    WHERE ((UIP.EFFT_D BETWEEN T1.EFFT_D AND T1.EXPY_D)
           OR (T1.EFFT_D BETWEEN UIP.EFFT_D AND UIP.EXPY_D))
  ) AX ON AX.ASSC_ACCT_I = AP.ACCT_I
  WHERE ((AX.EFFT_D BETWEEN AP.EFFT_D AND AP.EXPY_D)
         OR (AP.EFFT_D BETWEEN AX.EFFT_D AND AX.EXPY_D))
  GROUP BY 1,2,3,4,5,6,7,8,9

  UNION ALL
  
  -- Facility accounts processing
  SELECT AX.ACCT_I,
         AP.PATY_I,
         AX.ASSC_ACCT_I,
         AP.PATY_ACCT_REL_C,
         'N' AS PRFR_PATY_F,
         AP.SRCE_SYST_C,
         (CASE WHEN AP.EFFT_D > AX.EFFT_D THEN AP.EFFT_D ELSE AX.EFFT_D END) AS EFFT_D,
         (CASE WHEN AP.EXPY_D < AX.EXPY_D THEN AP.EXPY_D ELSE AX.EXPY_D END) AS EXPY_D,
         AP.ROW_SECU_ACCS_C
  FROM (
    SELECT ACCT_I, PATY_I, PATY_ACCT_REL_C, SRCE_SYST_C, EFFT_D,
           CASE
             WHEN EFFT_D = EXPY_D THEN EXPY_D
             WHEN EXPY_D >= :EXTR_D THEN DATE '9999-12-31'
             ELSE EXPY_D
           END AS EXPY_D,
           ROW_SECU_ACCS_C
    FROM NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_PATY_DEDUP
    WHERE :EXTR_D BETWEEN EFFT_D AND EXPY_D
  ) AP
  JOIN (
    SELECT FCLY.FCLY_I AS ACCT_I,
           UIP.ACCT_I AS ASSC_ACCT_I,
           (CASE WHEN UIP.EFFT_D > FCLY.EFFT_D THEN UIP.EFFT_D ELSE FCLY.EFFT_D END) AS EFFT_D,
           (CASE WHEN UIP.EXPY_D < FCLY.EXPY_D THEN UIP.EXPY_D ELSE FCLY.EXPY_D END) AS EXPY_D
    FROM (
      SELECT FCLY_I, SRCE_SYST_PATY_I, EFFT_D,
             CASE
               WHEN EFFT_D = EXPY_D THEN EXPY_D
               WHEN EXPY_D >= :EXTR_D THEN DATE '9999-12-31'
               ELSE EXPY_D
             END AS EXPY_D
      FROM NPD_D12_DMN_GDWMIG_IBRG_V.pvtech.MOS_FCLY
      WHERE :EXTR_D BETWEEN EFFT_D AND EXPY_D
    ) FCLY
    JOIN (
      SELECT ACCT_I, SRCE_SYST_PATY_I, EFFT_D,
             CASE
               WHEN EFFT_D = EXPY_D THEN EXPY_D
               WHEN EXPY_D >= :EXTR_D THEN DATE '9999-12-31'
               ELSE EXPY_D
             END AS EXPY_D
      FROM NPD_D12_DMN_GDWMIG_IBRG_V.pvtech.ACCT_UNID_PATY
      WHERE :EXTR_D BETWEEN EFFT_D AND EXPY_D
        AND TRIM(SRCE_SYST_C) = 'SAP'
        AND TRIM(PATY_ACCT_REL_C) = 'ACTO'
    ) UIP ON UIP.SRCE_SYST_PATY_I = FCLY.SRCE_SYST_PATY_I
    WHERE ((UIP.EFFT_D BETWEEN FCLY.EFFT_D AND FCLY.EXPY_D)
           OR (FCLY.EFFT_D BETWEEN UIP.EFFT_D AND UIP.EXPY_D))
  ) AX ON AX.ASSC_ACCT_I = AP.ACCT_I
  WHERE ((AX.EFFT_D BETWEEN AP.EFFT_D AND AP.EXPY_D)
         OR (AP.EFFT_D BETWEEN AX.EFFT_D AND AX.EXPY_D))
  GROUP BY 1,2,3,4,5,6,7,8,9;

  
  -- 11. Process WSS accounts - populate ACCT_PATY_REL_WSS staging table
  DELETE FROM NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_PATY_REL_WSS;
  
  INSERT INTO NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_PATY_REL_WSS
  SELECT AR.SUBJ_ACCT_I AS ACCT_I,
         AP.PATY_I,
         AR.OBJC_ACCT_I AS ASSC_ACCT_I,
         AP.PATY_ACCT_REL_C,
         'N' AS PRFR_PATY_F,
         AP.SRCE_SYST_C,
         (CASE WHEN AR.EFFT_D > AP.EFFT_D THEN AR.EFFT_D ELSE AP.EFFT_D END) AS EFFT_D,
         (CASE WHEN AR.EXPY_D < AP.EXPY_D THEN AR.EXPY_D ELSE AP.EXPY_D END) AS EXPY_D,
         AP.ROW_SECU_ACCS_C
  FROM (
    SELECT ACCT_I, PATY_I, PATY_ACCT_REL_C, SRCE_SYST_C, EFFT_D,
           CASE
             WHEN EFFT_D = EXPY_D THEN EXPY_D
             WHEN EXPY_D >= :EXTR_D THEN DATE '9999-12-31'
             ELSE EXPY_D
           END AS EXPY_D,
           ROW_SECU_ACCS_C
    FROM NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_PATY_DEDUP
    WHERE :EXTR_D BETWEEN EFFT_D AND EXPY_D
  ) AP
  JOIN (
    SELECT SUBJ_ACCT_I, OBJC_ACCT_I, EFFT_D,
           CASE
             WHEN EFFT_D = EXPY_D THEN EXPY_D
             WHEN EXPY_D >= :EXTR_D THEN DATE '9999-12-31'
             ELSE EXPY_D
           END AS EXPY_D
    FROM NPD_D12_DMN_GDWMIG_IBRG_V.pvtech.ACCT_REL
    WHERE TRIM(REL_C) = 'FCLYO' AND :EXTR_D BETWEEN EFFT_D AND EXPY_D
  ) AR ON AR.OBJC_ACCT_I = AP.ACCT_I
  WHERE (
    (AR.EFFT_D BETWEEN AP.EFFT_D AND AP.EXPY_D)
    OR (AP.EFFT_D BETWEEN AR.EFFT_D AND AR.EXPY_D)
  );

  -- 12. Get accounts that also exist in ACCT_REL with DITPS relationship
  DELETE FROM NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_REL_WSS_DITPS;
  
  INSERT INTO NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_REL_WSS_DITPS
  SELECT APA.ACCT_I
  FROM NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_PATY_REL_WSS APA
  JOIN (
    SELECT SUBJ_ACCT_I, OBJC_ACCT_I, EFFT_D,
           CASE
             WHEN EFFT_D = EXPY_D THEN EXPY_D
             WHEN EXPY_D >= :EXTR_D THEN DATE '9999-12-31'
             ELSE EXPY_D
           END AS EXPY_D
    FROM NPD_D12_DMN_GDWMIG_IBRG_V.pvtech.ACCT_REL
    WHERE TRIM(REL_C) = 'DITPS' AND :EXTR_D BETWEEN EFFT_D AND EXPY_D
  ) AR ON APA.ACCT_I = AR.OBJC_ACCT_I
  WHERE (
    (APA.EFFT_D BETWEEN AR.EFFT_D AND AR.EXPY_D)
    OR (AR.EFFT_D BETWEEN APA.EFFT_D AND APA.EXPY_D)
  )
  GROUP BY 1;

  -- 13. Delete those accounts that also exist in ACCT_REL with DITPS relationship
  DELETE FROM NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_PATY_REL_WSS
  WHERE ACCT_I IN (
    SELECT ACCT_I FROM NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_REL_WSS_DITPS
  );

  -- 14. Insert accounts that also exist in ACCT_REL with DITPS relationship, using OBJC_ACCT_I
  INSERT INTO NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_PATY_REL_WSS
  SELECT REL.ACCT_I,
         AP.PATY_I,
         REL.ASSC_ACCT_I,
         AP.PATY_ACCT_REL_C,
         'N' AS PRFR_PATY_F,
         AP.SRCE_SYST_C,
         (CASE WHEN AP.EFFT_D > REL.EFFT_D THEN AP.EFFT_D ELSE REL.EFFT_D END) AS EFFT_D,
         (CASE WHEN AP.EXPY_D < REL.EXPY_D THEN AP.EXPY_D ELSE REL.EXPY_D END) AS EXPY_D,
         AP.ROW_SECU_ACCS_C
  FROM (
    SELECT ACCT_I, PATY_I, PATY_ACCT_REL_C, SRCE_SYST_C, EFFT_D,
           CASE
             WHEN EFFT_D = EXPY_D THEN EXPY_D
             WHEN EXPY_D >= :EXTR_D THEN DATE '9999-12-31'
             ELSE EXPY_D
           END AS EXPY_D,
           ROW_SECU_ACCS_C
    FROM NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_PATY_DEDUP
    WHERE :EXTR_D BETWEEN EFFT_D AND EXPY_D
  ) AP
  JOIN (
    SELECT DITPS.OBJC_ACCT_I AS ACCT_I,
           FCLYO.OBJC_ACCT_I AS ASSC_ACCT_I,
           (CASE WHEN FCLYO.EFFT_D > DITPS.EFFT_D THEN FCLYO.EFFT_D ELSE DITPS.EFFT_D END) AS EFFT_D,
           (CASE WHEN FCLYO.EXPY_D < DITPS.EXPY_D THEN FCLYO.EXPY_D ELSE DITPS.EXPY_D END) AS EXPY_D
    FROM (
      SELECT SUBJ_ACCT_I, OBJC_ACCT_I, EFFT_D,
             CASE
               WHEN EFFT_D = EXPY_D THEN EXPY_D
               WHEN EXPY_D >= :EXTR_D THEN DATE '9999-12-31'
               ELSE EXPY_D
             END AS EXPY_D
      FROM NPD_D12_DMN_GDWMIG_IBRG_V.pvtech.ACCT_REL
      WHERE TRIM(REL_C) = 'FCLYO' AND :EXTR_D BETWEEN EFFT_D AND EXPY_D
    ) FCLYO
    JOIN (
      SELECT SUBJ_ACCT_I, OBJC_ACCT_I, REL_C, EFFT_D,
             CASE
               WHEN EFFT_D = EXPY_D THEN EXPY_D
               WHEN EXPY_D >= :EXTR_D THEN DATE '9999-12-31'
               ELSE EXPY_D
             END AS EXPY_D
      FROM NPD_D12_DMN_GDWMIG_IBRG_V.pvtech.ACCT_REL
      WHERE TRIM(REL_C) = 'DITPS' AND :EXTR_D BETWEEN EFFT_D AND EXPY_D
    ) DITPS ON FCLYO.SUBJ_ACCT_I = DITPS.OBJC_ACCT_I  -- C2151903 - WSS DERV ACCT_PATY CHANGE
    JOIN NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_REL_WSS_DITPS AR3 ON DITPS.OBJC_ACCT_I = AR3.ACCT_I
    WHERE (
      (DITPS.EFFT_D BETWEEN FCLYO.EFFT_D AND FCLYO.EXPY_D)
      OR (FCLYO.EFFT_D BETWEEN DITPS.EFFT_D AND DITPS.EXPY_D)
    )
    -- Eliminate duplicate relationships that exist for some of DITPS
    QUALIFY ROW_NUMBER() OVER(PARTITION BY DITPS.OBJC_ACCT_I, DITPS.REL_C ORDER BY DITPS.SUBJ_ACCT_I DESC) = 1
  ) AS REL ON REL.ASSC_ACCT_I = AP.ACCT_I
  WHERE (
    (AP.EFFT_D BETWEEN REL.EFFT_D AND REL.EXPY_D)
    OR (REL.EFFT_D BETWEEN AP.EFFT_D AND AP.EXPY_D)
  )
  GROUP BY 1,2,3,4,5,6,7,8,9;

  -- 15. Insert WSS rows into the main table
  INSERT INTO NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.DERV_ACCT_PATY_CURR
  SELECT ACCT_I,
         PATY_I,
         ASSC_ACCT_I,
         PATY_ACCT_REL_C,
         PRFR_PATY_F,
         SRCE_SYST_C,
         EFFT_D,
         EXPY_D,
         ROW_SECU_ACCS_C
  FROM NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_PATY_REL_WSS;
  
  RETURN 'SUCCESS: Completed processing for extract date ' || :EXTR_D;
  
EXCEPTION
  WHEN OTHER THEN
    RETURN 'ERROR: ' || SQLERRM || ' (Code: ' || SQLCODE || ')';
END;
$$;