{{ config(materialized='view', tags=['ExtCC_APP_PROD']) }}

WITH CpyCCAppProdSeq AS (
	SELECT
		CC_APP_PROD_ID,
		REQUESTED_LIMIT_AMT,
		CC_INTEREST_OPT_CAT_ID,
		CBA_HOMELOAN_NO,
		PRE_APPRV_AMOUNT,
		READ_COSTS_AND_RISKS_FLAG,
		ACCEPTS_COSTS_AND_RISKS_DATE,
		MOD_TIMESTAMP,
		NTM_CAMPAIGN_ID,
		FRIES_CAMPAIGN_CODE,
		OAP_CAMPAIGN_CODE
	FROM {{ ref('SrcCCAppProdSeq') }}
)

SELECT * FROM CpyCCAppProdSeq