{{ config(materialized='view', tags=['ExtCC_APP_PROD']) }}

WITH Remove_Duplicates_214 AS (
	SELECT CC_APP_PROD_ID, REQUESTED_LIMIT_AMT, CC_INTEREST_OPT_CAT_ID, CBA_HOMELOAN_NO, PRE_APPRV_AMOUNT, READ_COSTS_AND_RISKS_FLAG, ACCEPTS_COSTS_AND_RISKS_DATE, MOD_TIMESTAMP, NTM_CAMPAIGN_ID, FRIES_CAMPAIGN_CODE, OAP_CAMPAIGN_CODE 
	FROM (
		SELECT CC_APP_PROD_ID, REQUESTED_LIMIT_AMT, CC_INTEREST_OPT_CAT_ID, CBA_HOMELOAN_NO, PRE_APPRV_AMOUNT, READ_COSTS_AND_RISKS_FLAG, ACCEPTS_COSTS_AND_RISKS_DATE, MOD_TIMESTAMP, NTM_CAMPAIGN_ID, FRIES_CAMPAIGN_CODE, OAP_CAMPAIGN_CODE,
		 ROW_NUMBER() OVER (PARTITION BY CC_APP_PROD_ID ORDER BY 1 ASC) AS ROW_NUM 
		FROM {{ ref('CpyCCAppProdSeq') }}
	) AS Remove_Duplicates_214_TEMP
	WHERE ROW_NUM = 1
)

SELECT * FROM Remove_Duplicates_214