{{ config(materialized='view', tags=['ExtChlBusHlmAppSec']) }}

WITH XfmCheckNulls AS (
	SELECT
		HL_APP_PROD_ID,
		HLM_APP_ID,
		ASSET_LIABILITY_ID,
		PRINCIPAL_SECU_FLAG,
		SETTLEMENT_REQD,
		FORWARD_DOC_TO,
		TO_MS,
		TO_BRANCH,
		TO_AGENT,
		SETTLEMENT_COMMENT
	FROM {{ ref('CSE_CHL_BUS_HLM_APP_SEC') }}
	WHERE 
)

SELECT * FROM XfmCheckNulls