{{

    config(

       pre_hook = [
    'CREATE OR REPLACE TRANSIENT TABLE ' ~ cvar("intermediate_db") ~ '.' ~ cvar("datasets_schema") ~ '.' ~ cvar("base_dir") ~ '__dataset__' ~ cvar("run_stream") ~ '_Mapping_Rejects__DS ( PL_APP_ID VARCHAR(12), NOMINATED_BRANCH_ID VARCHAR(12), PL_PACKAGE_CAT_ID VARCHAR(12), ETL_D VARCHAR(10), ORIG_ETL_D VARCHAR(10), EROR_C VARCHAR(10));',
    'CREATE OR REPLACE TRANSIENT TABLE ' ~ cvar("intermediate_db") ~ '.' ~ cvar("datasets_schema") ~ '.' ~ cvar("base_dir") ~ '__dataset__Tmp_' ~ cvar("run_stream") ~ '_APPT_DEPT__DS ( APPT_I VARCHAR(255) NOT NULL, DEPT_ROLE_C VARCHAR(5) NOT NULL, EFFT_D DATE NOT NULL, DEPT_I VARCHAR(255) NOT NULL, EXPY_D DATE NOT NULL, PROS_KEY_EFFT_I NUMBER(10,0) NOT NULL, PROS_KEY_EXPY_I NUMBER(10,0), EROR_SEQN_I NUMBER(10,0), RUN_STRM VARCHAR(100));',
    'CREATE OR REPLACE TRANSIENT TABLE ' ~ cvar("intermediate_db") ~ '.' ~ cvar("datasets_schema") ~ '.' ~ cvar("base_dir") ~ '__dataset__Tmp_' ~ cvar("run_stream") ~ '_APPT_PDCT__DS ( APPT_PDCT_I VARCHAR(255) NOT NULL, APPT_QLFY_C VARCHAR(2), ACQR_TYPE_C VARCHAR(4), ACQR_ADHC_X VARCHAR(255), ACQR_SRCE_C VARCHAR(4), PDCT_N INTEGER NOT NULL, APPT_I VARCHAR(255) NOT NULL, SRCE_SYST_C VARCHAR(3) NOT NULL, SRCE_SYST_APPT_PDCT_I VARCHAR(255) NOT NULL, LOAN_FNDD_METH_C VARCHAR(4), NEW_ACCT_F VARCHAR(1), BROK_PATY_I VARCHAR(255), COPY_FROM_OTHR_APPT_F VARCHAR(1), EFFT_D DATE NOT NULL, EXPY_D DATE NOT NULL, PROS_KEY_EFFT_I NUMBER(10,0) NOT NULL, PROS_KEY_EXPY_I NUMBER(10,0), EROR_SEQN_I NUMBER(10,0), RUN_STRM VARCHAR(100), APPT_PDCT_CATG_C VARCHAR(4), ASES_D DATE, APPT_PDCT_DURT_C VARCHAR(4));',
    'CREATE OR REPLACE TRANSIENT TABLE ' ~ cvar("intermediate_db") ~ '.' ~ cvar("files_schema") ~ '.' ~ cvar("base_dir") ~ '__error__' ~ cvar("run_stream") ~ '_' ~ cvar("etl_process_dt") ~ '_MapPdctN__ERR ( SRCE_KEY_I VARCHAR NOT NULL, CONV_M VARCHAR NOT NULL, CONV_MAP_RULE_M VARCHAR NOT NULL, TRSF_TABL_M VARCHAR NOT NULL, VALU_CHNG_BFOR_X VARCHAR NOT NULL, VALU_CHNG_AFTR_X VARCHAR NOT NULL, TRSF_X VARCHAR NOT NULL, TRSF_COLM_M VARCHAR NOT NULL);'

]

    )

}}

WITH cte as(
Select 1 as dummy
)

SELECT
dummy
FROM cte