{{ config(materialized='view', tags=['XfmFunnelExt']) }}

WITH Funnel_52 AS (
	SELECT
		APP_ID as APP_ID,
		APP_PROD_ID as APP_PROD_ID,
		SUBTYPE_CODE as SUBTYPE_CODE,
		QA_QUESTION_ID as QA_QUESTION_ID,
		QA_ANSWER_ID as QA_ANSWER_ID,
		TEXT_ANSWER as TEXT_ANSWER,
		CIF_CODE as CIF_CODE
	FROM {{ ref('CLP_BUS_CLNT_ANS') }}
	UNION ALL
	SELECT
		APP_ID,
		APP_PROD_ID,
		SUBTYPE_CODE,
		QA_QUESTION_ID,
		QA_ANSWER_ID,
		TEXT_ANSWER,
		CIF_CODE
	FROM {{ ref('CLP_BUS_APP_PROD') }}
)

SELECT * FROM Funnel_52