version: 2

sources:
  - name: raw_files
    description: "Raw source files from CSE CPL Business Application"
    schema: raw
    tables:
      - name: cse_cpl_bus_app_daily
        description: "Daily CPL business application file"
        columns:
          - name: pl_app_id
            description: "Personal Loan Application ID"
            tests:
              - not_null
              - unique
          - name: nominated_branch_id
            description: "Branch ID that becomes Department ID"
          - name: pl_package_cat_id
            description: "Package category ID for product lookup"
          - name: journal_type
            description: "Journal type code"
          - name: journal_status
            description: "Journal status code"
          - name: journal_reason
            description: "Journal reason code"
          - name: cc_app_prod_id
            description: "Credit card application product ID"
          - name: requested_limit_amt
            description: "Requested limit amount"
          - name: dept_role_code
            description: "Department role code"
          - name: effective_date
            description: "Effective date YYYYMMDD"
          - name: expiry_date
            description: "Expiry date YYYYMMDD"
          - name: orig_etl_d
            description: "Original ETL date"
          - name: load_date
            description: "File load date"
            
  # Note: CSEL4 stream intentionally excludes Oracle and unknown reference sources in this project
