{{ config(materialized='view', tags=['DltAppt_Pdct_PurpfrmTMP_tran']) }}

WITH RmvdupFrmJoin AS (
	SELECT NEW_APPT_PDCT_I, NEW_PURP_TYPE_C, NEW_SRCE_SYST_APPT_PDCT_PURP_I, NEW_PURP_CLAS_C, NEW_SRCE_SYST_C, NEW_PURP_A, NEW_CNCY_C, NEW_MAIN_PURP_F, OLD_EFFT_D, change_code 
	FROM (
		SELECT NEW_APPT_PDCT_I, NEW_PURP_TYPE_C, NEW_SRCE_SYST_APPT_PDCT_PURP_I, NEW_PURP_CLAS_C, NEW_SRCE_SYST_C, NEW_PURP_A, NEW_CNCY_C, NEW_MAIN_PURP_F, OLD_EFFT_D, change_code,
		 ROW_NUMBER() OVER (PARTITION BY NEW_APPT_PDCT_I, NEW_CNCY_C, NEW_MAIN_PURP_F, NEW_PURP_A, NEW_PURP_CLAS_C, NEW_PURP_TYPE_C, NEW_SRCE_SYST_APPT_PDCT_PURP_I, NEW_SRCE_SYST_C, change_code, OLD_EFFT_D ORDER BY 1 ASC) AS ROW_NUM 
		FROM {{ ref('JoinAll') }}
	) AS RmvdupFrmJoin_TEMP
	WHERE ROW_NUM = 1
)

SELECT * FROM RmvdupFrmJoin