GDW1_BTEQ_Migration:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: '' #"{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: '' #"{{ env_var('SNOWFLAKE_USER') }}"
      password: '' #"{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: 'R_DEV_NPD_D12_GDWMIG' #"{{ env_var('SNOWFLAKE_ROLE', 'GDW1_DBT_ROLE') }}"
      database: 'NPD_D12_DMN_GDWMIG_IBRG_V' #"{{ env_var('SNOWFLAKE_DATABASE', 'PSUND_MIGR_DCF') }}"
      warehouse: 'wh_usr_npd_d12_gdwmig_001' #"{{ env_var('SNOWFLAKE_WAREHOUSE', 'GDW1_WH') }}"
      schema: 'P_V_OUT_001_STD_0' #"{{ env_var('SNOWFLAKE_SCHEMA', 'P_D_DCF_001_STD_0') }}"
      threads: 4
      client_session_keep_alive: true
      query_tag: "GDW1_BTEQ_MIGRATION"

# np_projects_commbank_sf_dbt:
#   target: dev
#   outputs:
#     dev:
#       type: snowflake
#       account: '' #COMMONWEALTHBANKOFAUSTRALIA.CDAO_CDL_NONPROD
#       user: '' #HINDIMA
#       role: R_DEV_NPD_D12_GDWMIG
#       database: NPD_D12_DMN_GDWMIG_IBRG_V #
#       password: '' #9vruH!AyhmDKKExV
#       threads: 4
#       warehouse: wh_usr_npd_d12_gdwmig_001
#       schema: P_V_OUT_001_STD_0 #stage_views
      
    test:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', 'GDW1_DBT_ROLE') }}"
      database: "{{ env_var('SNOWFLAKE_TEST_DATABASE', 'PSUND_MIGR_DCF_TEST') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'GDW1_WH') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA', 'P_D_DCF_001_STD_0') }}"
      threads: 2
      client_session_keep_alive: true
      query_tag: "GDW1_BTEQ_MIGRATION_TEST"
      
    prod:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_PROD_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PROD_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_PROD_ROLE', 'GDW1_DBT_PROD_ROLE') }}"
      database: "{{ env_var('SNOWFLAKE_PROD_DATABASE', 'PSUND_MIGR_CLD') }}"
      warehouse: "{{ env_var('SNOWFLAKE_PROD_WAREHOUSE', 'GDW1_PROD_WH') }}"
      schema: "{{ env_var('SNOWFLAKE_PROD_SCHEMA', 'P_D_GDW_001_STD_0') }}"
      threads: 8
      client_session_keep_alive: true
      query_tag: "GDW1_BTEQ_MIGRATION_PROD" 