{{ config(materialized='view', tags=['ExtAppCclAppChlApp']) }}

WITH XfmCheckNulls__OutCheckNullsSorted AS (
	SELECT
		-- *SRC*: \(20)If Len(Trim(( IF IsNotNull((XfmCheckNulls.APP_ID)) THEN (XfmCheckNulls.APP_ID) ELSE ""))) = 0 Then 'REJ5001' Else '',
		IFF(LEN(TRIM(IFF({{ ref('Cpy_NoOp') }}.APP_ID IS NOT NULL, {{ ref('Cpy_NoOp') }}.APP_ID, ''))) = 0, 'REJ5001', '') AS ErrorCode,
		APP_ID,
		APP_APP_ID,
		APP_SUBTYPE_CODE,
		APP_APP_NO,
		APP_CREATED_DATE,
		APP_CREATED_BY_STAFF_NUMBER,
		APP_OWNED_BY_STAFF_NUMBER,
		APP_CHANNEL_CAT_ID,
		APP_LODGEMENT_BRANCH_ID,
		APP_SM_CASE_ID,
		CCL_APP_CCL_APP_ID,
		CCL_APP_CCL_APP_CAT_ID,
		CCL_APP_CCL_FORM_CAT_ID,
		CCL_APP_TOT_PERSONAL_FAC_AMT,
		CCL_APP_TOT_EQUIPFIN_FAC_AMT,
		CCL_APP_TOT_COMMERCIAL_FAC_AMT,
		CCL_APP_TOPUP_APP_ID,
		CCL_APP_AF_PRIMARY_INDUSTRY_ID,
		CCL_APP_AD_TUC_AMT,
		CCL_APP_COMMISSION_AMT,
		CCL_APP_BROKER_REFERAL_FLAG,
		CHL_APP_HL_APP_ID,
		CHL_APP_HL_PACKAGE_CAT_ID,
		CHL_APP_LPC_OFFICE,
		CHL_APP_STATUS_TRACKER_ID,
		APP_FOUND_FLAG,
		CCL_APP_FOUND_FLAG,
		CHL_APP_FOUND_FLAG,
		CHL_TPB_HL_APP_ID,
		CHL_TPB_SUBTYPE_CODE,
		REL_MANAGER_STATE_ID,
		DATE_RECEIVED,
		{{ ref('Cpy_NoOp') }}.CHL_APP_PCD_EXTERNAL_SYS_CAT_ID AS CHL_APP_PCD_EXT_SYS_CAT_ID,
		CHL_TPB_FOUND_FLAG,
		HLM_APP_TYPE_CAT_ID,
		HLM_APP_PROD_ID,
		HLM_APP_DISCHARGE_REASON_ID,
		HLM_APP_CRIS_PRODUCT_ID,
		HLM_APP_ACCOUNT_NUMBER,
		HLM_APP_FOUND_FLAG,
		HL_BUSN_CHNL_CAT_I,
		CCC_APP_CC_APP_CAT_ID,
		CCC_APP_FOUND_FLAG
	FROM {{ ref('Cpy_NoOp') }}
	WHERE SUBSTRING(ErrorCode, 1, 3) <> 'REJ'
)

SELECT * FROM XfmCheckNulls__OutCheckNullsSorted