{{ config(materialized='view', tags=['DltINT_GRUPFrmTMP_FA_UNDERTAKING']) }}

WITH 
tmp_fa_utak AS (
	SELECT
	*
	FROM {{ ref("tmp_fa_utak")  }}),
int_grup AS (
	SELECT
	*
	FROM {{ ref("int_grup")  }}),
SrcTmpFAUtakTera AS (SELECT a.INT_GRUP_I, a.INT_GRUP_TYPE_C, a.INT_GRUP_M, a.SRCE_SYST_INT_GRUP_I, a.SRCE_SYST_C, a.ORIG_SRCE_SYST_INT_GRUP_I, a.CRAT_D, b.INT_GRUP_I AS OLD_INT_GRUP_I, b.INT_GRUP_M AS OLD_INT_GRUP_M, b.ORIG_SRCE_SYST_INT_GRUP_I AS OLD_ORIG_SRCE_SYST_INT_GRUP_I, b.EFFT_D AS OLD_EFFT_D FROM TMP_FA_UTAK LEFT OUTER JOIN INT_GRUP ON TRIM(a.INT_GRUP_I) = TRIM(b.INT_GRUP_I) AND b.EXPY_D = '9999-12-31')


SELECT * FROM SrcTmpFAUtakTera