{{ config(materialized='view', tags=['DltAPPT_PDCT_RPAYFrmTMP_APPT_PDCT_RPAY']) }}

WITH 
tmp_appt_pdct_rpay AS (
	SELECT
	*
	FROM {{ ref("tmp_appt_pdct_rpay")  }}),
appt_pdct_rpay AS (
	SELECT
	*
	FROM {{ ref("appt_pdct_rpay")  }}),
SrcTmpApptPdctRpayTera AS (SELECT a.APPT_PDCT_I AS NEW_APPT_PDCT_I, a.RPAY_TYPE_C AS NEW_RPAY_TYPE_C, a.PAYT_FREQ_C AS NEW_PAYT_FREQ_C, a.STRT_RPAY_D AS NEW_STRT_RPAY_D, b.APPT_PDCT_I AS OLD_APPT_PDCT_I, b.RPAY_TYPE_C AS OLD_RPAY_TYPE_C, b.EFFT_D AS OLD_EFFT_D, b.PAYT_FREQ_C AS OLD_PAYT_FREQ_C FROM TMP_APPT_PDCT_RPAY LEFT OUTER JOIN APPT_PDCT_RPAY ON TRIM(a.APPT_PDCT_I) = TRIM(b.APPT_PDCT_I) AND b.EXPY_D = '9999-12-31' WHERE a.RUN_STRM = '{{ var("RUN_STREAM") }}')


SELECT * FROM SrcTmpApptPdctRpayTera