{{ config(materialized='view', tags=['ExtHL_APP_PROD']) }}

WITH CpyHlAppProdSeq AS (
	SELECT
		HL_APP_PROD_ID,
		PARENT_HL_APP_PROD_ID,
		HL_REPAYMENT_PERIOD_CAT_ID,
		AMOUNT,
		LOAN_TERM_MONTHS,
		ACCOUNT_NUMBER,
		TOTAL_LOAN_AMOUNT,
		HLS_FLAG,
		GDW_UPDATED_LDP_PAID_ON_AMOUNT
	FROM {{ ref('SrcHlAppProdSeq') }}
)

SELECT * FROM CpyHlAppProdSeq