{{ config(materialized='view', tags=['LdREJT_CHL_BUS_FEAT_ATTR']) }}

WITH FunJnlIdNulls AS (
	SELECT
		HL_FEATURE_ATTR_ID as HL_FEATURE_ATTR_ID,
		HL_FEATURE_TERM as HL_FEATURE_TERM,
		HL_FEATURE_AMOUNT as HL_FEATURE_AMOUNT,
		HL_FEATURE_BALANCE as HL_FEATURE_BALANCE,
		HL_FEATURE_FEE as HL_FEATURE_FEE,
		HL_FEATURE_SPEC_REPAY as HL_FEATURE_SPEC_REPAY,
		HL_FEATURE_EST_INT_AMT as HL_FEATURE_EST_INT_AMT,
		HL_FEATURE_DATE as HL_FEATURE_DATE,
		HL_FEATURE_COMMENT as HL_FEATURE_COMMENT,
		HL_FEATURE_CAT_ID as HL_FEATURE_CAT_ID,
		HL_APP_PROD_ID as HL_APP_PROD_ID,
		ETL_D as ETL_D,
		ORIG_ETL_D as ORIG_ETL_D,
		EROR_C as EROR_C
	FROM {{ ref('SrcRejJnlIdNullsDS') }}
	UNION ALL
	SELECT
		HL_FEATURE_ATTR_ID,
		HL_FEATURE_TERM,
		HL_FEATURE_AMOUNT,
		HL_FEATURE_BALANCE,
		HL_FEATURE_FEE,
		HL_FEATURE_SPEC_REPAY,
		HL_FEATURE_EST_INT_AMT,
		HL_FEATURE_DATE,
		HL_FEATURE_COMMENT,
		HL_FEATURE_CAT_ID,
		HL_APP_PROD_ID,
		ETL_D,
		ORIG_ETL_D,
		EROR_C
	FROM {{ ref('SrcHlFeatureAttrRejectsDS') }}
)

SELECT * FROM FunJnlIdNulls