{{ config(materialized='view', tags=['LdREJT_CHL_BUS_FEAT_ATTR']) }}

SELECT
	HL_FEATURE_ATTR_ID
	FEATURE_TERM
	FEATURE_AMOUNT
	FEATURE_BALANCE
	FEATURE_FEE
	FEATURE_SPEC_REPAY
	FEATURE_EST_INT_AMT
	FEATURE_DATE
	FEATURE_COMMENT
	HL_FEATURE_CAT_ID
	HL_APP_PROD_ID
	ETL_D
	ORIG_ETL_D
	EROR_C 
FROM {{ ref('MappingCols') }}