{{ config(materialized='view', tags=['XfmDelFlagAPPT_PDCT_RPAY']) }}

WITH XfmProsKey AS (
	SELECT
		DELETED_TABLE_NAME,
		{{ ref('SrcAppPdctRpayDS') }}.DELETED_KEY_1_VALUE AS APP_PROD_ID,
		-- *SRC*: \(20)If OutAppPdctRpayDS.DELETED_TABLE_NAME = 'HL_APP_PROD' Then 'CSE_CHL_BUS_APP_PROD_APPT_PDCT_RPAY' Else ( If OutAppPdctRpayDS.DELETED_TABLE_NAME = 'PL_APP_PROD' Then 'CSE_CPL_BUS_APP_PROD_APPT_PDCT_RPAY' Else ''),
		IFF({{ ref('SrcAppPdctRpayDS') }}.DELETED_TABLE_NAME = 'HL_APP_PROD', 'CSE_CHL_BUS_APP_PROD_APPT_PDCT_RPAY', IFF({{ ref('SrcAppPdctRpayDS') }}.DELETED_TABLE_NAME = 'PL_APP_PROD', 'CSE_CPL_BUS_APP_PROD_APPT_PDCT_RPAY', '')) AS CONV_M
	FROM {{ ref('SrcAppPdctRpayDS') }}
	WHERE 
)

SELECT * FROM XfmProsKey