{{ config(materialized='view', tags=['DltAPPT_FEAT_SHLFrmTMP_APPT_FEAT']) }}

WITH Funnel_71 AS (
	SELECT
		APPT_I as APPT_I,
		FEAT_I as FEAT_I,
		EFFT_D as EFFT_D,
		SRCE_SYST_C as SRCE_SYST_C,
		SRCE_SYST_APPT_FEAT_I as SRCE_SYST_APPT_FEAT_I,
		SRCE_SYST_STND_VALU_Q as SRCE_SYST_STND_VALU_Q,
		SRCE_SYST_STND_VALU_R as SRCE_SYST_STND_VALU_R,
		SRCE_SYST_STND_VALU_A as SRCE_SYST_STND_VALU_A,
		ACTL_VALU_Q as ACTL_VALU_Q,
		ACTL_VALU_R as ACTL_VALU_R,
		ACTL_VALU_A as ACTL_VALU_A,
		CNCY_C as CNCY_C,
		OVRD_FEAT_I as OVRD_FEAT_I,
		OVRD_REAS_C as OVRD_REAS_C,
		FEAT_SEQN_N as FEAT_SEQN_N,
		FEAT_STRT_D as FEAT_STRT_D,
		FEE_CHRG_D as FEE_CHRG_D,
		EXPY_D as EXPY_D,
		PROS_KEY_EFFT_I as PROS_KEY_EFFT_I,
		PROS_KEY_EXPY_I as PROS_KEY_EXPY_I,
		EROR_SEQN_I as EROR_SEQN_I
	FROM {{ ref('XfmCheckDeltaAction__OutTgtApptFeatInsertDS1') }}
	UNION ALL
	SELECT
		APPT_I,
		FEAT_I,
		EFFT_D,
		SRCE_SYST_C,
		SRCE_SYST_APPT_FEAT_I,
		SRCE_SYST_STND_VALU_Q,
		SRCE_SYST_STND_VALU_R,
		SRCE_SYST_STND_VALU_A,
		ACTL_VALU_Q,
		ACTL_VALU_R,
		ACTL_VALU_A,
		CNCY_C,
		OVRD_FEAT_I,
		OVRD_REAS_C,
		FEAT_SEQN_N,
		FEAT_STRT_D,
		FEE_CHRG_D,
		EXPY_D,
		PROS_KEY_EFFT_I,
		PROS_KEY_EXPY_I,
		EROR_SEQN_I
	FROM {{ ref('XfmCheckDeltaAction__OutTgtApptFeatInsertDS2') }}
)

SELECT * FROM Funnel_71