{{ config(materialized='view', tags=['DltAPPT_FEAT_SHLFrmTMP_APPT_FEAT']) }}

WITH 
tmp_appt_feat AS (
	SELECT
	*
	FROM {{ ref("tmp_appt_feat")  }}),
appt_feat AS (
	SELECT
	*
	FROM {{ ref("appt_feat")  }}),
SrcTmpApptFeatTera AS (SELECT a.APPT_I AS NEW_APPT_I, a.FEAT_I AS NEW_FEAT_I, a.SRCE_SYST_C AS NEW_SRCE_SYST_C, a.SRCE_SYST_APPT_FEAT_I AS NEW_SHL_F, b.APPT_I AS OLD_APPT_I, b.EFFT_D AS OLD_EFFT_D, b.FEAT_I AS OLD_FEAT_I, 'Y' AS OLD_SHL_F, a.CASS_WITHHOLD_RISKBANK_FLAG AS NEW_CASS_WITHHOLD_RISKBANK_FLAG FROM TMP_APPT_FEAT LEFT OUTER JOIN APPT_FEAT ON TRIM(a.APPT_I) = TRIM(b.APPT_I) AND TRIM(a.FEAT_I) = TRIM(b.FEAT_I) AND b.EXPY_D = '9999-12-31' WHERE a.RUN_STRM = '{{ var("RUN_STREAM") }}')


SELECT * FROM SrcTmpApptFeatTera