{{ config(materialized='view', tags=['LdMAP_CSE_SM_CASE_STUS_REASLkp']) }}

WITH XfmConversions AS (
	SELECT
		-- *SRC*: trim(InMAP_CSE_SM_CASE_STUS_REASTera.SM_REAS_CAT_ID),
		TRIM({{ ref('SrcMAP_CSE_SM_CASE_STUS_REASTera') }}.SM_REAS_CAT_ID) AS SM_REAS_CAT_ID,
		-- *SRC*: trim(InMAP_CSE_SM_CASE_STUS_REASTera.STUS_REAS_TYPE_C),
		TRIM({{ ref('SrcMAP_CSE_SM_CASE_STUS_REASTera') }}.STUS_REAS_TYPE_C) AS STUS_REAS_TYPE_C
	FROM {{ ref('SrcMAP_CSE_SM_CASE_STUS_REASTera') }}
	WHERE 
)

SELECT * FROM XfmConversions