{{ config(materialized='view', tags=['LdMAP_CSE_APPT_PURP_CLLkp']) }}

WITH 
,
SrcMAP_CSE_APPT_PURP_CLTera AS (SELECT 
MAP_CSE_APPT_PURP_CL.CCL_LOAN_PURP_CAT_ID,
MAP_CSE_APPT_PURP_CL.PURP_TYPE_C,
MAP_CSE_APPT_PURP_CL.EFFT_D,
MAP_CSE_APPT_PURP_CL.EXPY_D
FROM {{ var('GDW_ACCT_VW') }}.MAP_CSE_APPT_PURP_CL as MAP_CSE_APPT_PURP_CL
WHERE MAP_CSE_APPT_PURP_CL.efft_d (date, format 'yyyymmdd') <= '{{ var('ETL_PROCESS_DT') }}' 
and MAP_CSE_APPT_PURP_CL.expy_d (date, format 'yyyymmdd') >= '{{ var('ETL_PROCESS_DT') }}' 
)


SELECT * FROM SrcMAP_CSE_APPT_PURP_CLTera