{{ config(materialized='view', tags=['XfmCclAppProdFrmExt3']) }}

WITH CpyRename AS (
	SELECT
		{{ ref('SrcCclAppProd_OTHERS') }}.APP_PROD_ID AS CCL_APP_PROD_ID,
		PARENT_CCL_APP_PROD_ID,
		ACCOUNT_NUMBER,
		ACTUAL_RATE,
		BALLOON_PAY_AMT,
		BASIS_TYPE_CAT_ID,
		INTEREST_RATE_MARGIN,
		LOAN_TERM_MTH_NUM,
		CURRENT_LIMIT,
		INC_DEC_AMT,
		POST_APP_AMT,
		NEW_PROD_FLAG,
		INDEX_RATE,
		INTEREST_ADV_FLAG,
		INTERESTONLY_TERM_MTH_NUM,
		CAPPED_TERM_MTH_NUM,
		CAPPED_RATE,
		{{ ref('SrcCclAppProd_OTHERS') }}.CRIS_PRODUCT_ID AS CRIS_PDCT_CAT_ID,
		{{ ref('SrcCclAppProd_OTHERS') }}.CCL_LOAN_PURPOSE_ID AS CCL_LOAN_PURPOSE_CAT_ID,
		NEW_PROD_SUBTYPE_FLAG,
		TEMP_EXCESS_MTHS,
		LOAN_PURPOSE_CLASS_CODE,
		CCL_INTEREST_RATE_CAT_ID,
		CRR,
		AD_TUC_INC_AMT,
		CCL_RATE_TYPE_CAT_ID,
		LINK_CCL_APP_ID,
		LINK_CCL_APP_PROD_ID,
		CHL_LMI_AMT,
		USED_IN_EXPOSURE_VIEW_FLAG,
		CCL_APP_BROKER_CIF_CODE,
		APP_ID,
		FIXED_INT_START_DATE,
		CHILD_PRODUCT_LEVEL_CAT_ID,
		PARENT_PRODUCT_LEVEL_CAT_ID,
		ORIG_ETL_D
	FROM {{ ref('SrcCclAppProd_OTHERS') }}
)

SELECT * FROM CpyRename