{{ config(materialized='view', tags=['DltAPPT_FEATFrmTMP_APPT_FEAT']) }}

WITH 
tmp_appt_feat AS (
	SELECT
	*
	FROM {{ ref("tmp_appt_feat")  }}),
appt_feat AS (
	SELECT
	*
	FROM {{ ref("appt_feat")  }}),
SrcTmpApptFeatTera AS (SELECT a.APPT_I AS NEW_APPT_I, a.FEAT_I AS NEW_FEAT_I, a.SRCE_SYST_C AS NEW_SRCE_SYST_C, a.SRCE_SYST_APPT_FEAT_I AS NEW_SRCE_SYST_APPT_FEAT_I, a.SRCE_SYST_STND_VALU_Q AS NEW_SRCE_SYST_STND_VALU_Q, a.SRCE_SYST_STND_VALU_R AS NEW_SRCE_SYST_STND_VALU_R, a.SRCE_SYST_STND_VALU_A AS NEW_SRCE_SYST_STND_VALU_A, a.ACTL_VALU_Q AS NEW_ACTL_VALU_Q, a.ACTL_VALU_R AS NEW_ACTL_VALU_R, a.ACTL_VALU_A AS NEW_ACTL_VALU_A, a.CNCY_C AS NEW_CNCY_C, a.OVRD_FEAT_I AS NEW_OVRD_FEAT_I, a.OVRD_REAS_C AS NEW_OVRD_REAS_C, a.FEAT_SEQN_N AS NEW_FEAT_SEQN_N, a.FEAT_STRT_D AS NEW_FEAT_STRT_D, a.FEE_CHRG_D AS NEW_FEE_CHRG_D, b.APPT_I AS OLD_APPT_I, b.EFFT_D AS OLD_EFFT_D, b.SRCE_SYST_APPT_FEAT_I AS OLD_SRCE_SYST_APPT_FEAT_I, b.SRCE_SYST_STND_VALU_R AS OLD_SRCE_SYST_STND_VALU_R, b.SRCE_SYST_STND_VALU_A AS OLD_SRCE_SYST_STND_VALU_A, b.ACTL_VALU_Q AS OLD_ACTL_VALU_Q, b.ACTL_VALU_R AS OLD_ACTL_VALU_R, b.ACTL_VALU_A AS OLD_ACTL_VALU_A, b.FEE_CHRG_D AS OLD_FEE_CHRG_D, b.FEAT_I AS OLD_FEAT_I, b.SRCE_SYST_C AS OLD_SRCE_SYST_C, b.SRCE_SYST_STND_VALU_Q AS OLD_SRCE_SYST_STND_VALU_Q, b.CNCY_C AS OLD_CNCY_C, b.OVRD_FEAT_I AS OLD_OVRD_FEAT_I, b.OVRD_REAS_C AS OLD_OVRD_REAS_C, b.FEAT_SEQN_N AS OLD_FEAT_SEQN_N, b.FEAT_STRT_D AS OLD_FEAT_STRT_D FROM TMP_APPT_FEAT LEFT OUTER JOIN APPT_FEAT ON TRIM(a.APPT_I) = TRIM(b.APPT_I) AND TRIM(a.SRCE_SYST_APPT_FEAT_I) = TRIM(b.SRCE_SYST_APPT_FEAT_I) AND b.EXPY_D = '9999-12-31' WHERE a.RUN_STRM = '{{ var("RUN_STREAM") }}')


SELECT * FROM SrcTmpApptFeatTera