{{ config(materialized='view', tags=['DltINT_GRUP_STUSFrmTMP_INT_GRUP_STUS']) }}

WITH 
tmp_int_grup_stus AS (
	SELECT
	*
	FROM {{ ref("tmp_int_grup_stus")  }}),
int_grup_stus AS (
	SELECT
	*
	FROM {{ source("tdcsad","int_grup_stus")  }}),
SrcTmpIntGrupStusTera AS (SELECT a.INT_GRUP_I AS NEW_INT_GRUP_I, a.STRT_S AS NEW_STRT_S, a.STUS_C AS NEW_STUS_C, a.STRT_D AS NEW_STRT_D, CAST(a.STRT_T AS VARCHAR(8)) || '.000000' AS NEW_STRT_T, a.EMPL_I AS NEW_EMPL_I, a.END_S AS NEW_END_S, a.END_D AS NEW_END_D, CAST(a.END_T AS VARCHAR(8)) || '.000000' AS NEW_END_T, b.INT_GRUP_I AS OLD_INT_GRUP_I, b.STRT_S AS OLD_STRT_S, b.STUS_C AS OLD_STUS_C, b.END_S AS OLD_END_S, b.END_D AS OLD_END_D, CAST(b.END_T AS VARCHAR(15)) AS OLD_END_T, b.EFFT_D AS OLD_EFFT_D FROM TMP_INT_GRUP_STUS LEFT OUTER JOIN INT_GRUP_STUS ON TRIM(a.INT_GRUP_I) = TRIM(b.INT_GRUP_I) AND a.STRT_S = b.STRT_S AND TRIM(a.STUS_C) = TRIM(b.STUS_C) AND b.EXPY_D = '9999-12-31' WHERE a.RUN_STRM = '{{ var("RUN_STREAM") }}')


SELECT * FROM SrcTmpIntGrupStusTera