{{ config(materialized='view', tags=['XfmDelFlagPlFeeJoin']) }}

WITH FL_RemoveNulls AS (
	SELECT
		DELETED_TABLE_NAME,
		DELETED_KEY_1,
		DELETED_KEY_1_VALUE,
		DELETED_KEY_2,
		DELETED_KEY_2_VALUE,
		DELETED_KEY_3,
		DELETED_KEY_3_VALUE,
		DELETED_KEY_4,
		DELETED_KEY_4_VALUE,
		DELETED_KEY_5,
		DELETED_KEY_5_VALUE
	FROM {{ ref('SrcPlMarginDS') }}
	WHERE DELETED_KEY_3_VALUE IS NOT NULL
)

SELECT * FROM FL_RemoveNulls