{{ config(materialized='view', tags=['ExtCclBusApp']) }}

WITH 
rejt_ccl_bus_app AS (
	SELECT
	*
	FROM {{ source("cse4_stg","rejt_ccl_bus_app")  }}),
SrcRejtCclAppRejectOra AS (SELECT CCL_APP_ID, CCL_APP_CAT_ID, CCL_FORM_CAT_ID, TOTAL_PERSONAL_FAC_AMT, TOTAL_EQUIPMENTFINANCE_FAC_AMT, TOTAL_COMMERCIAL_FAC_AMT, TOPUP_APP_ID, AF_PRIMARY_INDUSTRY_ID, AD_TUC_AMT, COMMISSION_AMT, BROKER_REFERAL_FLAG, CAST(ORIG_ETL_D AS TEXT) AS ORIG_ETL_D FROM REJT_CCL_BUS_APP WHERE EROR_C LIKE 'RPR%')


SELECT * FROM SrcRejtCclAppRejectOra