{{ config(materialized='view', tags=['XfmPL_APP_PRODFrmExt']) }}

WITH ModNullHandling AS (
	SELECT 
	--Manual
	--UNID_PATY_CATG_C: string[4]= handle_null (UNID_PATY_CATG_C, '9999')
	--TARG_CHAR_C: string[max=255]= handle_null (string_trim(TARG_CHAR_C), '999007')
	--SRCE_SYST_ACTL_TERM_Q : decimal[15,6]= handle_null (SRCE_SYST_ACTL_TERM_Q, 9999)
	--PAYT_FREQ_C : string[1]= handle_null (PAYT_FREQ_C, '9')
	--TARG_CHAR_C2: string[4]= handle_null (string_trim(TARG_CHAR_C2), '999012')
	PL_APP_PROD_ID, PL_TARGET_CAT_ID, REPAY_APPROX_AMT, REPAY_FREQUENCY_ID, PL_APP_PROD_REPAY_CAT_ID, PL_PROD_TERM_CAT_ID, PL_CAMPAIGN_CAT_ID, AD_HOC_CAMPAIGN_DESC, CAR_SEEKER_FLAG, PL_PROD_TARGET_CAT_ID, PL_MARKETING_SOURCE_CAT_ID, HLS_ACCT_NO, TOTAL_INTEREST_AMT, APP_PROD_AMT, TP_BROKER_ID, TP_BROKER_FIRST_NAME, TP_BROKER_LAST_NAME, TP_BROKER_GROUP_CAT_ID, READ_COSTS_AND_RISKS_FLAG, ACCEPTS_COSTS_AND_RISKS_DATE, MAP_TYPE_C, ORIG_ETL_D, UNID_PATY_CATG_C, TARG_CHAR_C, SRCE_SYST_ACTL_TERM_Q, PAYT_FREQ_C, MAP_TYPE_C2, TARG_CHAR_C2 
	FROM {{ ref('LkpReferences') }}
)

SELECT * FROM ModNullHandling