{{ config(materialized='view', tags=['LdTMP_CSE_APPT_PDCT_OFI_SETL_FrmXfm']) }}

WITH Copy_89 AS (
	SELECT
		APPT_PDCT_I,
		EFFT_D,
		EXPY_D,
		PROS_KEY_EFFT_I,
		PROS_KEY_EXPY_I,
		{{ ref('CSE_APPT_PDCT_OFI_SETL') }}.OFI_IDNN_X AS DCHG_OFI_IDNN_X,
		{{ ref('CSE_APPT_PDCT_OFI_SETL') }}.OFI_M AS DCHG_OFI_M,
		{{ ref('CSE_APPT_PDCT_OFI_SETL') }}.ROW_SECU_ACCS_C AS ROW_SECU_ACESS_C,
		{{ ref('CSE_APPT_PDCT_OFI_SETL') }}.RUN_STREAM AS RUN_STRM
	FROM {{ ref('CSE_APPT_PDCT_OFI_SETL') }}
)

SELECT * FROM Copy_89