{{ config(materialized='view', tags=['MergeChlIntRateChlIntRatePercChlProdIntMarg']) }}

WITH RD_KeepLatestMargin AS (
	SELECT MARG_HL_PROD_INT_MARGIN_ID, HL_INT_RATE_ID, MARG_HL_PROD_INT_MARGIN_CAT_ID, MARG_MARGIN_TYPE, MARG_MARGIN_DESC, MARG_MARGIN_CODE, MARG_MARGIN_AMOUNT, MARG_ADJ_AMT, MARG_FOUND_FLAG 
	FROM (
		SELECT MARG_HL_PROD_INT_MARGIN_ID, HL_INT_RATE_ID, MARG_HL_PROD_INT_MARGIN_CAT_ID, MARG_MARGIN_TYPE, MARG_MARGIN_DESC, MARG_MARGIN_CODE, MARG_MARGIN_AMOUNT, MARG_ADJ_AMT, MARG_FOUND_FLAG,
		 ROW_NUMBER() OVER (PARTITION BY HL_INT_RATE_ID ORDER BY 1 ASC) AS ROW_NUM 
		FROM {{ ref('CgAdd_Flag3') }}
	) AS RD_KeepLatestMargin_TEMP
	WHERE ROW_NUM = 1
)

SELECT * FROM RD_KeepLatestMargin