{{ config(materialized='view', tags=['XfmUnidPatyNameGnrc']) }}

WITH Modify_Null AS (
	SELECT 
	--Manual
	--REFERRAL_AGENT_ID= handle_null(REFERRAL_AGENT_ID,'99999');NAME=handle_null(NAME,'99999');HL_APP_ID= handle_null(HL_APP_ID,'99999')
	REC_TYPE, HL_APP_COMMISSION_ID, MOD_TIMESTAMP, MOD_USER_ID, HL_APP_ID, HL_COMMISSION_CAT_ID, NAME, ABN_ACN_NUMBER, AMOUNT, ACN, ABN, ADDITIONAL_COMMISSIONS_FLAG, MOD_CLIENT_ID, HL_APP_COMMISSION_BASE_VN, IS_REFERRAL_AGENT, REFERRAL_AGENT_ID 
	FROM {{ ref('SrcCseChlBusAppCommDet') }}
)

SELECT * FROM Modify_Null