{{ config(materialized='view', tags=['DltAPPT_DOCUFrmTMP_WIM_BUS']) }}

WITH 
,
Join_Tmp_Wim_Bus_Evnt_Tables AS (SELECT DT3.APPT_I AS "NEW_APPT_I", T.APPT_I AS "OLD_APPT_I" FROM (SELECT AGE.APPT_I FROM (SELECT EGA.EVNT_GRUP_I FROM (SELECT DT1.EVNT_I FROM (SELECT A.WORK_ITEM_ID, D.EVNT_I FROM TMP_WIM_BUS_WRKITM_GNRC JOIN (SELECT SRCE_SYST_EVNT_I, EVNT_I FROM (SELECT SRCE_SYST_EVNT_I, EVNT_I FROM CTCT_EVNT WHERE SRCE_SYST_C = 'CSE' UNION ALL SELECT SRCE_SYST_EVNT_I, EVNT_I FROM BUSN_EVNT WHERE SRCE_SYST_C = 'CSE') AS DT) AS D ON A.WORK_ITEM_ID = D.SRCE_SYST_EVNT_I) AS DT1) AS B INNER JOIN EVNT_GRUP_ASSC ON B.EVNT_I = EGA.EVNT_I) AS DT2 INNER JOIN APPT_EVNT_GRUP ON DT2.EVNT_GRUP_I = AGE.EVNT_GRUP_I) AS DT3 LEFT OUTER JOIN APPT_DOCU ON DT3.APPT_I = T.APPT_I AND T.SRCE_SYST_C = 'CSE' AND T.EXPY_D = '9999-12-31' GROUP BY 1, 2)


SELECT * FROM Join_Tmp_Wim_Bus_Evnt_Tables