{{ config(materialized='view', tags=['ExtComBusAppProdClientRole']) }}

WITH RemoveDuplicates AS (
	SELECT RECORD_TYPE, MOD_TIMESTAMP, APP_PROD_CLIENT_ROLE_ID, ROLE_CAT_ID, CIF_CODE, APP_PROD_ID, SUBTYPE_CODE, DUMMY 
	FROM (
		SELECT RECORD_TYPE, MOD_TIMESTAMP, APP_PROD_CLIENT_ROLE_ID, ROLE_CAT_ID, CIF_CODE, APP_PROD_ID, SUBTYPE_CODE, DUMMY,
		 ROW_NUMBER() OVER (PARTITION BY APP_PROD_ID, ROLE_CAT_ID, CIF_CODE ORDER BY 1 ASC) AS ROW_NUM 
		FROM {{ ref('SrcBusApPrdClntSeq') }}
	) AS RemoveDuplicates_TEMP
	WHERE ROW_NUM = 1
)

SELECT * FROM RemoveDuplicates