version: 2

models:
  - name: int_validate_cse_cpl_bus_app
    description: "Intermediate validation model for CSE CPL Business Application data with comprehensive field validation"
    config:
      tags: ['stream_csel4', 'intermediate_layer', 'data_validation', 'cse_cpl_bus_app']
    columns:
      - name: pl_app_id
        description: "Personal Loan Application ID - Primary Key (validated)"
        tests:
          - not_null
          - unique
      - name: nominated_branch_id
        description: "Branch ID that becomes Department ID - Required for DEPT_I mapping (validated)"
        tests:
          - not_null
      - name: mod_timestamp
        description: "Modification timestamp (validated)"
        tests:
          - not_null
      - name: pl_package_cat_id
        description: "Package category ID for product lookup (optional)"
      - name: file_nm
        description: "Source file name (validated)"
        tests:
          - not_null
      - name: file_row_num
        description: "File row number (validated)"
        tests:
          - not_null
      - name: file_load_ts
        description: "File load timestamp (validated)"
        tests:
          - not_null
      - name: record_valid
        description: "Overall record validation flag"
        tests:
          - accepted_values:
              values: [true]
              quote: false
      - name: data_quality_score
        description: "Data quality score (0-100)"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 100
      - name: validation_timestamp
        description: "Timestamp when validation was performed"
        tests:
          - not_null
      - name: etl_process_date
        description: "ETL process date for this run"
        tests:
          - not_null

  - name: int_tmp_appt_dept
    description: "Intermediate transformation for APPT_DEPT target table"
    config:
      tags: ['stream_csel4', 'intermediate_layer', 'data_transform', 'appt_dept']

  - name: int_tmp_appt_pdct
    description: "Intermediate transformation for APPT_PDCT target table"  
    config:
      tags: ['stream_csel4', 'intermediate_layer', 'data_transform', 'appt_pdct']

  - name: int_tmp_dept_appt
    description: "Intermediate transformation for DEPT_APPT target table"
    config:
      tags: ['stream_csel4', 'intermediate_layer', 'data_transform', 'dept_appt']
