{{ config(materialized='view', tags=['UtilProcessMetaDataTC_Promo']) }}

WITH 
,
tc_SyncTbl AS (SELECT CAST(SyncId AS DECIMAL(10, 0)) AS SyncId, SUM(INSERTCOUNT) AS INS_CNT, SUM(UPDATECOUNT) AS UPD_CNT, SUM(DELETECOUNT) AS DEL_CNT, SUM(REJECTCOUNT) AS REJ_CNT, SUM(MISSINGROWCOUNT) AS MIS_ROW_CNT, SUM(ERRORCOUNT1) AS ERR_CNT1, SUM(ERRORCOUNT2) AS ERR_CNT2, SUM(DUPLICATEKEYCOUNT) AS DUP_KEY_CNT, MIN(StartTime) AS START_T, MAX(EndTime) AS END_T FROM __VAR_DBT_pRUN_STRM_C___SYNC WHERE SYNCID = {{ var("pTD_SYNC_ID") }} AND STARTTIME IN (SELECT MAX(STARTTIME) FROM __VAR_DBT_pRUN_STRM_C___SYNC WHERE INSERTCOUNT <> 0 UNION SELECT MAX(STARTTIME) FROM __VAR_DBT_pRUN_STRM_C___SYNC WHERE UPDATECOUNT <> 0 UNION SELECT MAX(STARTTIME) FROM __VAR_DBT_pRUN_STRM_C___SYNC WHERE DELETECOUNT <> 0) GROUP BY 1)


SELECT * FROM tc_SyncTbl