-- Count check for all source tables in Teradata from CBA_GDW1_Table_Mapping.csv
-- This query will show the row count for each source table in Teradata before migration
-- Run this in Teradata to validate source data counts

-- Connect to Teradata environment
-- Configure appropriate session settings if needed

-- Count all source tables in Teradata
SELECT 'K_PDCBODS.ODS_RULE' as table_name, COUNT(1) as row_count FROM K_PDCBODS.ODS_RULE
UNION
SELECT 'K_PDCMS.MAP_CMS_PDCT', COUNT(1) FROM K_PDCMS.MAP_CMS_PDCT
UNION
SELECT 'K_PDGRD.DEPT_DIMN_NODE_ANCS_CURR', COUNT(1) FROM K_PDGRD.DEPT_DIMN_NODE_ANCS_CURR
UNION
SELECT 'K_PDGRD.GRD_DEPT_FLAT_CURR', COUNT(1) FROM K_PDGRD.GRD_DEPT_FLAT_CURR
UNION
SELECT 'K_PDGRD.GRD_GNRC_MAP', COUNT(1) FROM K_PDGRD.GRD_GNRC_MAP
UNION
SELECT 'K_PDGRD.NON_WORK_DAY', COUNT(1) FROM K_PDGRD.NON_WORK_DAY
UNION
SELECT 'K_PDPATY.ACCT_PATY', COUNT(1) FROM K_PDPATY.ACCT_PATY
UNION
SELECT 'K_PDPATY.PATY_REL', COUNT(1) FROM K_PDPATY.PATY_REL
UNION
SELECT 'K_PDPATY.UTIL_PROS_ISAC', COUNT(1) FROM K_PDPATY.UTIL_PROS_ISAC
UNION
SELECT 'K_PDSECURITY.ROW_LEVL_SECU_USER_PRFL', COUNT(1) FROM K_PDSECURITY.ROW_LEVL_SECU_USER_PRFL
UNION
SELECT 'K_PDSRCCS.PLAN_BALN_SEGM_MSTR', COUNT(1) FROM K_PDSRCCS.PLAN_BALN_SEGM_MSTR
UNION
SELECT 'K_PDSRCCS.PLAN_BALN_SEGM_MSTR_ARCH', COUNT(1) FROM K_PDSRCCS.PLAN_BALN_SEGM_MSTR_ARCH
UNION
SELECT 'K_PDSRCCS.UTIL_BTCH_ISAC', COUNT(1) FROM K_PDSRCCS.UTIL_BTCH_ISAC
UNION
SELECT 'K_PDSRCCS.UTIL_PARM', COUNT(1) FROM K_PDSRCCS.UTIL_PARM
UNION
SELECT 'K_PDSRCCS.UTIL_PROS_ISAC', COUNT(1) FROM K_PDSRCCS.UTIL_PROS_ISAC
UNION
SELECT 'K_PDSRCCS.UTIL_TRSF_EROR_RQM3', COUNT(1) FROM K_PDSRCCS.UTIL_TRSF_EROR_RQM3
UNION
SELECT 'K_PDTRPC.WKND_PBLC_HLDY', COUNT(1) FROM K_PDTRPC.WKND_PBLC_HLDY
UNION
SELECT 'K_PUTIL.TERASYNC', COUNT(1) FROM K_PUTIL.TERASYNC
UNION
SELECT 'K_PUTIL.PROS_EROR_LOG', COUNT(1) FROM K_PUTIL.PROS_EROR_LOG
UNION
SELECT 'K_STAR_CAD_PROD_DATA.ACCT_APPT_PDCT', COUNT(1) FROM K_STAR_CAD_PROD_DATA.ACCT_APPT_PDCT
UNION
SELECT 'K_STAR_CAD_PROD_DATA.ACCT_REL', COUNT(1) FROM K_STAR_CAD_PROD_DATA.ACCT_REL
UNION
SELECT 'K_STAR_CAD_PROD_DATA.ACCT_UNID_PATY', COUNT(1) FROM K_STAR_CAD_PROD_DATA.ACCT_UNID_PATY
UNION
SELECT 'K_STAR_CAD_PROD_DATA.ACCT_XREF_BPS_CBS', COUNT(1) FROM K_STAR_CAD_PROD_DATA.ACCT_XREF_BPS_CBS
UNION
SELECT 'K_STAR_CAD_PROD_DATA.ACCT_XREF_MAS_DAR', COUNT(1) FROM K_STAR_CAD_PROD_DATA.ACCT_XREF_MAS_DAR
UNION
SELECT 'K_STAR_CAD_PROD_DATA.APPT', COUNT(1) FROM K_STAR_CAD_PROD_DATA.APPT
UNION
SELECT 'K_STAR_CAD_PROD_DATA.APPT_DEPT', COUNT(1) FROM K_STAR_CAD_PROD_DATA.APPT_DEPT
UNION
SELECT 'K_STAR_CAD_PROD_DATA.APPT_FEAT', COUNT(1) FROM K_STAR_CAD_PROD_DATA.APPT_FEAT
UNION
SELECT 'K_STAR_CAD_PROD_DATA.APPT_PDCT', COUNT(1) FROM K_STAR_CAD_PROD_DATA.APPT_PDCT
UNION
SELECT 'K_STAR_CAD_PROD_DATA.APPT_PDCT_ACCT', COUNT(1) FROM K_STAR_CAD_PROD_DATA.APPT_PDCT_ACCT
UNION
SELECT 'K_STAR_CAD_PROD_DATA.APPT_PDCT_AMT', COUNT(1) FROM K_STAR_CAD_PROD_DATA.APPT_PDCT_AMT
UNION
SELECT 'K_STAR_CAD_PROD_DATA.APPT_PDCT_FEAT', COUNT(1) FROM K_STAR_CAD_PROD_DATA.APPT_PDCT_FEAT
UNION
SELECT 'K_STAR_CAD_PROD_DATA.APPT_PDCT_PATY', COUNT(1) FROM K_STAR_CAD_PROD_DATA.APPT_PDCT_PATY
UNION
SELECT 'K_STAR_CAD_PROD_DATA.APPT_PDCT_PURP', COUNT(1) FROM K_STAR_CAD_PROD_DATA.APPT_PDCT_PURP
UNION
SELECT 'K_STAR_CAD_PROD_DATA.APPT_PDCT_REL', COUNT(1) FROM K_STAR_CAD_PROD_DATA.APPT_PDCT_REL
UNION
SELECT 'K_STAR_CAD_PROD_DATA.APPT_PDCT_RPAY', COUNT(1) FROM K_STAR_CAD_PROD_DATA.APPT_PDCT_RPAY
UNION
SELECT 'K_STAR_CAD_PROD_DATA.APPT_PDCT_UNID_PATY', COUNT(1) FROM K_STAR_CAD_PROD_DATA.APPT_PDCT_UNID_PATY
UNION
SELECT 'K_STAR_CAD_PROD_DATA.APPT_REL', COUNT(1) FROM K_STAR_CAD_PROD_DATA.APPT_REL
UNION
SELECT 'K_STAR_CAD_PROD_DATA.APPT_TRNF_DETL', COUNT(1) FROM K_STAR_CAD_PROD_DATA.APPT_TRNF_DETL
UNION
SELECT 'K_STAR_CAD_PROD_DATA.BUSN_EVNT', COUNT(1) FROM K_STAR_CAD_PROD_DATA.BUSN_EVNT
UNION
SELECT 'K_STAR_CAD_PROD_DATA.CLS_FCLY', COUNT(1) FROM K_STAR_CAD_PROD_DATA.CLS_FCLY
UNION
SELECT 'K_STAR_CAD_PROD_DATA.CLS_UNID_PATY', COUNT(1) FROM K_STAR_CAD_PROD_DATA.CLS_UNID_PATY
UNION
SELECT 'K_STAR_CAD_PROD_DATA.DAR_ACCT', COUNT(1) FROM K_STAR_CAD_PROD_DATA.DAR_ACCT
UNION
SELECT 'K_STAR_CAD_PROD_DATA.DEPT_APPT', COUNT(1) FROM K_STAR_CAD_PROD_DATA.DEPT_APPT
UNION
SELECT 'K_STAR_CAD_PROD_DATA.DERV_ACCT_PATY', COUNT(1) FROM K_STAR_CAD_PROD_DATA.DERV_ACCT_PATY
UNION
SELECT 'K_STAR_CAD_PROD_DATA.DERV_PRTF_ACCT_REL', COUNT(1) FROM K_STAR_CAD_PROD_DATA.DERV_PRTF_ACCT_REL
UNION
SELECT 'K_STAR_CAD_PROD_DATA.DERV_PRTF_OWN_REL', COUNT(1) FROM K_STAR_CAD_PROD_DATA.DERV_PRTF_OWN_REL
UNION
SELECT 'K_STAR_CAD_PROD_DATA.DERV_PRTF_PATY_REL', COUNT(1) FROM K_STAR_CAD_PROD_DATA.DERV_PRTF_PATY_REL
UNION
SELECT 'K_STAR_CAD_PROD_DATA.EVNT', COUNT(1) FROM K_STAR_CAD_PROD_DATA.EVNT
UNION
SELECT 'K_STAR_CAD_PROD_DATA.EVNT_EMPL', COUNT(1) FROM K_STAR_CAD_PROD_DATA.EVNT_EMPL
UNION
SELECT 'K_STAR_CAD_PROD_DATA.EVNT_INT_GRUP', COUNT(1) FROM K_STAR_CAD_PROD_DATA.EVNT_INT_GRUP
UNION
SELECT 'K_STAR_CAD_PROD_DATA.GDW_EFFT_DATE', COUNT(1) FROM K_STAR_CAD_PROD_DATA.GDW_EFFT_DATE
UNION
SELECT 'K_STAR_CAD_PROD_DATA.INT_GRUP', COUNT(1) FROM K_STAR_CAD_PROD_DATA.INT_GRUP
UNION
SELECT 'K_STAR_CAD_PROD_DATA.INT_GRUP_DEPT', COUNT(1) FROM K_STAR_CAD_PROD_DATA.INT_GRUP_DEPT
UNION
SELECT 'K_STAR_CAD_PROD_DATA.INT_GRUP_EMPL', COUNT(1) FROM K_STAR_CAD_PROD_DATA.INT_GRUP_EMPL
UNION
SELECT 'K_STAR_CAD_PROD_DATA.INT_GRUP_UNID_PATY', COUNT(1) FROM K_STAR_CAD_PROD_DATA.INT_GRUP_UNID_PATY
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_ADRS_TYPE', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_ADRS_TYPE
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_APPT_ACQR_SRCE', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_APPT_ACQR_SRCE
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_APPT_C', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_APPT_C
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_APPT_CMPE', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_APPT_CMPE
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_APPT_CODE_HM', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_APPT_CODE_HM
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_APPT_COND', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_APPT_COND
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_APPT_DOCU_DELY', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_APPT_DOCU_DELY
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_APPT_FEAT', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_APPT_FEAT
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_APPT_FORM', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_APPT_FORM
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_APPT_ORIG', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_APPT_ORIG
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_APPT_PDCT_FEAT', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_APPT_PDCT_FEAT
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_APPT_PDCT_PATY_ROLE', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_APPT_PDCT_PATY_ROLE
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_APPT_PURP_CL', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_APPT_PURP_CL
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_APPT_PURP_CLAS_CL', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_APPT_PURP_CLAS_CL
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_APPT_PURP_HL', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_APPT_PURP_HL
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_APPT_PURP_PL', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_APPT_PURP_PL
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_APPT_QLFY', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_APPT_QLFY
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_APPT_QSTN_HL', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_APPT_QSTN_HL
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_APPT_QSTN_RESP_HL', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_APPT_QSTN_RESP_HL
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_CMPE_IDNN', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_CMPE_IDNN
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_CNTY', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_CNTY
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_CRIS_PDCT', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_CRIS_PDCT
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_DOCU_METH', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_DOCU_METH
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_ENV_CHLD_PATY_REL', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_ENV_CHLD_PATY_REL
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_ENV_EVNT_ACTV_TYPE', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_ENV_EVNT_ACTV_TYPE
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_ENV_PATY_REL', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_ENV_PATY_REL
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_ENV_PATY_TYPE', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_ENV_PATY_TYPE
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_FEAT_OVRD_REAS_HL', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_FEAT_OVRD_REAS_HL
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_FEAT_OVRD_REAS_HL_D', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_FEAT_OVRD_REAS_HL_D
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_FEAT_OVRD_REAS_PL', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_FEAT_OVRD_REAS_PL
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_FEE_CAPL', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_FEE_CAPL
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_FNDD_METH', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_FNDD_METH
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_JOB_COMM_CATG', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_JOB_COMM_CATG
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_LOAN_FNDD_METH', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_LOAN_FNDD_METH
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_LOAN_TERM_PL', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_LOAN_TERM_PL
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_LPC_DEPT_HL', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_LPC_DEPT_HL
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_ORIG_APPT_SRCE', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_ORIG_APPT_SRCE
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_ORIG_APPT_SRCE_HM', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_ORIG_APPT_SRCE_HM
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_OVRD_FEE_FRQ_CL', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_OVRD_FEE_FRQ_CL
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_PACK_PDCT_HL', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_PACK_PDCT_HL
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_PACK_PDCT_PL', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_PACK_PDCT_PL
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_PAYT_FREQ', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_PAYT_FREQ
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_PDCT_REL_CL', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_PDCT_REL_CL
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_PL_ACQR_TYPE', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_PL_ACQR_TYPE
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_SM_CASE_STUS', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_SM_CASE_STUS
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_SM_CASE_STUS_REAS', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_SM_CASE_STUS_REAS
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_STATE', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_STATE
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_TRNF_OPTN', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_TRNF_OPTN
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_TU_APPT_C', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_TU_APPT_C
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MAP_CSE_UNID_PATY_CATG_PL', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MAP_CSE_UNID_PATY_CATG_PL
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MOS_FCLY', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MOS_FCLY
UNION
SELECT 'K_STAR_CAD_PROD_DATA.MOS_LOAN', COUNT(1) FROM K_STAR_CAD_PROD_DATA.MOS_LOAN
UNION
SELECT 'K_STAR_CAD_PROD_DATA.PATY_APPT_PDCT', COUNT(1) FROM K_STAR_CAD_PROD_DATA.PATY_APPT_PDCT
UNION
SELECT 'K_STAR_CAD_PROD_DATA.PATY_INT_GRUP', COUNT(1) FROM K_STAR_CAD_PROD_DATA.PATY_INT_GRUP
UNION
SELECT 'K_STAR_CAD_PROD_DATA.THA_ACCT', COUNT(1) FROM K_STAR_CAD_PROD_DATA.THA_ACCT
UNION
SELECT 'K_STAR_CAD_PROD_DATA.UTIL_BTCH_ISAC', COUNT(1) FROM K_STAR_CAD_PROD_DATA.UTIL_BTCH_ISAC
UNION
SELECT 'K_STAR_CAD_PROD_DATA.UTIL_ETI_CONV', COUNT(1) FROM K_STAR_CAD_PROD_DATA.UTIL_ETI_CONV
UNION
SELECT 'K_STAR_CAD_PROD_DATA.UTIL_PARM', COUNT(1) FROM K_STAR_CAD_PROD_DATA.UTIL_PARM
UNION
SELECT 'K_STAR_CAD_PROD_DATA.UTIL_PROS_ISAC', COUNT(1) FROM K_STAR_CAD_PROD_DATA.UTIL_PROS_ISAC
UNION
SELECT 'K_PDDSTG.DERV_ACCT_PATY_NON_RM', COUNT(1) FROM K_PDDSTG.DERV_ACCT_PATY_NON_RM
UNION
SELECT 'K_PDDSTG.ACCT_PATY_THA_NEW_RNGE', COUNT(1) FROM K_PDDSTG.ACCT_PATY_THA_NEW_RNGE
UNION
SELECT 'K_PDDSTG.ACCT_PATY_REL_WSS', COUNT(1) FROM K_PDDSTG.ACCT_PATY_REL_WSS
UNION
SELECT 'K_PDDSTG.DERV_PRTF_PATY_STAG', COUNT(1) FROM K_PDDSTG.DERV_PRTF_PATY_STAG
UNION
SELECT 'K_PDDSTG.GRD_GNRC_MAP_DERV_PATY_REL', COUNT(1) FROM K_PDDSTG.GRD_GNRC_MAP_DERV_PATY_REL
UNION
SELECT 'K_PDDSTG.DERV_ACCT_PATY_ROW_SECU_FIX', COUNT(1) FROM K_PDDSTG.DERV_ACCT_PATY_ROW_SECU_FIX
UNION
SELECT 'K_PDDSTG.DERV_ACCT_PATY_FLAG', COUNT(1) FROM K_PDDSTG.DERV_ACCT_PATY_FLAG
UNION
SELECT 'K_PDDSTG.ACCT_PATY_DEDUP', COUNT(1) FROM K_PDDSTG.ACCT_PATY_DEDUP
UNION
SELECT 'K_PDDSTG.ACCT_REL_WSS_DITPS', COUNT(1) FROM K_PDDSTG.ACCT_REL_WSS_DITPS
UNION
SELECT 'K_PDDSTG.GRD_GNRC_MAP_PATY_HOLD_PRTY', COUNT(1) FROM K_PDDSTG.GRD_GNRC_MAP_PATY_HOLD_PRTY
UNION
SELECT 'K_PDDSTG.DERV_PRTF_ACCT_STAG', COUNT(1) FROM K_PDDSTG.DERV_PRTF_ACCT_STAG
UNION
SELECT 'K_PDDSTG.ACCT_PATY_REL_THA', COUNT(1) FROM K_PDDSTG.ACCT_PATY_REL_THA
UNION
SELECT 'K_PDDSTG.GRD_GNRC_MAP_DERV_PATY_HOLD', COUNT(1) FROM K_PDDSTG.GRD_GNRC_MAP_DERV_PATY_HOLD
UNION
SELECT 'K_PDDSTG.GRD_GNRC_MAP_BUSN_SEGM_PRTY', COUNT(1) FROM K_PDDSTG.GRD_GNRC_MAP_BUSN_SEGM_PRTY
UNION
SELECT 'K_PDDSTG.DERV_PRTF_ACCT_PATY_PSST', COUNT(1) FROM K_PDDSTG.DERV_PRTF_ACCT_PATY_PSST
UNION
SELECT 'K_PDDSTG.DERV_ACCT_PATY_CURR', COUNT(1) FROM K_PDDSTG.DERV_ACCT_PATY_CURR
UNION
SELECT 'K_PDDSTG.GRD_GNRC_MAP_DERV_UNID_PATY', COUNT(1) FROM K_PDDSTG.GRD_GNRC_MAP_DERV_UNID_PATY
UNION
SELECT 'K_PDDSTG.DERV_ACCT_PATY_DEL', COUNT(1) FROM K_PDDSTG.DERV_ACCT_PATY_DEL
UNION
SELECT 'K_PDDSTG.DERV_ACCT_PATY_CHG', COUNT(1) FROM K_PDDSTG.DERV_ACCT_PATY_CHG
UNION
SELECT 'K_PDDSTG.DERV_PRTF_ACCT_PATY_STAG', COUNT(1) FROM K_PDDSTG.DERV_PRTF_ACCT_PATY_STAG
UNION
SELECT 'K_PDDSTG.DERV_ACCT_PATY_RM', COUNT(1) FROM K_PDDSTG.DERV_ACCT_PATY_RM
UNION
SELECT 'K_PDDSTG.DERV_ACCT_PATY_ADD', COUNT(1) FROM K_PDDSTG.DERV_ACCT_PATY_ADD
UNION
SELECT 'Sys_Calendar.CALDATES', COUNT(1) FROM Sys_Calendar.CALDATES
UNION
SELECT 'SysAdmin.TPUMPSTATUSTBL', COUNT(1) FROM SysAdmin.TPUMPSTATUSTBL
ORDER BY table_name;

-- Note: This script should be executed in the Teradata environment
-- Ensure you have appropriate permissions to access all source databases and tables
-- Some tables may be empty or may not exist - handle errors appropriately
