{{ config(materialized='view', tags=['DltAPPT_PDCT_FEATFrmTMP_APPT_PDCT_FEAT_5']) }}

WITH 
feat AS (
	SELECT
	*
	FROM {{ source("sdcsgrd","feat")  }}),
tmp_appt_pdct_feat AS (
	SELECT
	*
	FROM {{ ref("tmp_appt_pdct_feat")  }}),
appt_pdct_feat AS (
	SELECT
	*
	FROM {{ ref("appt_pdct_feat")  }}),
SrcTmpApptPdctFeatTera AS (SELECT a.APPT_PDCT_I AS NEW_APPT_PDCT_I, a.FEAT_I AS NEW_FEAT_I, a.SRCE_SYST_APPT_FEAT_I AS NEW_SRCE_SYST_APPT_FEAT_I, a.SRCE_SYST_C AS NEW_SRCE_SYST_C, a.SRCE_SYST_APPT_OVRD_I AS NEW_SRCE_SYST_APPT_OVRD_I, a.OVRD_FEAT_I AS NEW_OVRD_FEAT_I, a.SRCE_SYST_STND_VALU_Q AS NEW_SRCE_SYST_STND_VALU_Q, a.SRCE_SYST_STND_VALU_R AS NEW_SRCE_SYST_STND_VALU_R, a.SRCE_SYST_STND_VALU_A AS NEW_SRCE_SYST_STND_VALU_A, a.CNCY_C AS NEW_CNCY_C, a.ACTL_VALU_Q AS NEW_ACTL_VALU_Q, a.ACTL_VALU_R AS NEW_ACTL_VALU_R, a.ACTL_VALU_A AS NEW_ACTL_VALU_A, a.FEAT_SEQN_N AS NEW_FEAT_SEQN_N, a.FEAT_STRT_D AS NEW_FEAT_STRT_D, a.FEE_CHRG_D AS NEW_FEE_CHRG_D, a.OVRD_REAS_C AS NEW_OVRD_REAS_C, a.FEE_ADD_TO_TOTL_F AS NEW_FEE_ADD_TO_TOTL_F, a.FEE_CAPL_F AS NEW_FEE_CAPL_F, a.FEAT_TYPE_C AS NEW_FEAT_TYPE_C, b.APPT_PDCT_I AS OLD_APPT_PDCT_I, b.FEAT_I AS OLD_FEAT_I, b.EFFT_D AS OLD_EFFT_D, b.SRCE_SYST_STND_VALU_Q AS OLD_SRCE_SYST_STND_VALU_Q, b.SRCE_SYST_STND_VALU_R AS OLD_SRCE_SYST_STND_VALU_R, b.SRCE_SYST_STND_VALU_A AS OLD_SRCE_SYST_STND_VALU_A, b.ACTL_VALU_Q AS OLD_ACTL_VALU_Q, b.ACTL_VALU_R AS OLD_ACTL_VALU_R, b.ACTL_VALU_A AS OLD_ACTL_VALU_A, b.FEAT_SEQN_N AS OLD_FEAT_SEQN_N, b.FEAT_STRT_D AS OLD_FEAT_STRT_D, b.FEE_CHRG_D AS OLD_FEE_CHRG_D, b.OVRD_REAS_C AS OLD_OVRD_REAS_C, b.SRCE_SYST_APPT_FEAT_I AS OLD_SRCE_SYST_APPT_FEAT_I, b.SRCE_SYST_C AS OLD_SRCE_SYST_C, b.SRCE_SYST_APPT_OVRD_I AS OLD_SRCE_SYST_APPT_OVRD_I, b.OVRD_FEAT_I AS OLD_OVRD_FEAT_I, b.CNCY_C AS OLD_CNCY_C, b.FEE_ADD_TO_TOTL_F AS OLD_FEE_ADD_TO_TOTL_F, b.FEE_CAPL_F AS OLD_FEE_CAPL_F, b.FEAT_TYPE_C AS OLD_FEAT_TYPE_C FROM TMP_APPT_PDCT_FEAT LEFT OUTER JOIN (SELECT t1.APPT_PDCT_I, t1.FEAT_I, t1.EFFT_D, t1.SRCE_SYST_STND_VALU_Q, t1.SRCE_SYST_STND_VALU_R, t1.SRCE_SYST_STND_VALU_A, t1.ACTL_VALU_Q, t1.ACTL_VALU_R, t1.ACTL_VALU_A, t1.FEAT_SEQN_N, t1.FEAT_STRT_D, t1.FEE_CHRG_D, t1.OVRD_REAS_C, t2.FEAT_CATG_TYPE_C AS FEAT_TYPE_C, t1.SRCE_SYST_APPT_FEAT_I, t1.SRCE_SYST_C, t1.SRCE_SYST_APPT_OVRD_I, t1.OVRD_FEAT_I, t1.CNCY_C, t1.FEE_ADD_TO_TOTL_F, t1.FEE_CAPL_F FROM APPT_PDCT_FEAT, FEAT, (SELECT DISTINCT feat_type_c AS tmp_feat_type_c FROM TMP_APPT_PDCT_FEAT WHERE DLTA_VERS = '5') AS t3 WHERE t1.FEAT_I = t2.FEAT_I AND t2.FEAT_CATG_TYPE_C = t3.tmp_FEAT_TYPE_C AND t1.EXPY_D = '9999-12-31' AND t2.EXPY_D = '9999-12-31') AS b ON TRIM(a.APPT_PDCT_I) = TRIM(b.APPT_PDCT_I) AND TRIM(b.FEAT_TYPE_C) = TRIM(a.FEAT_TYPE_C) WHERE a.RUN_STRM = '{{ var("RUN_STREAM") }}' AND a.DLTA_VERS = '5')


SELECT * FROM SrcTmpApptPdctFeatTera