{{ config(materialized='view', tags=['LdMAP_CSE_FEAT_OVRD_REAS_PLLkp']) }}

WITH XfmConversions AS (
	SELECT
		-- *SRC*: Trim(InMAP_CSE_FEAT_OVRD_REAS_PLTera.MARG_REAS_CAT_ID),
		TRIM({{ ref('SrcMAP_CSE_FEAT_OVRD_REAS_PLTera') }}.MARG_REAS_CAT_ID) AS MARG_REAS_CAT_ID,
		-- *SRC*: Trim(InMAP_CSE_FEAT_OVRD_REAS_PLTera.OVRD_REAS_C),
		TRIM({{ ref('SrcMAP_CSE_FEAT_OVRD_REAS_PLTera') }}.OVRD_REAS_C) AS FEAT_OVRD_REAS_C
	FROM {{ ref('SrcMAP_CSE_FEAT_OVRD_REAS_PLTera') }}
	WHERE 
)

SELECT * FROM XfmConversions