{{ config(materialized='view', tags=['XfmHL_APPFrmExt']) }}

WITH DeDup_ApptPdct AS (
	SELECT APPT_PDCT_I, APPT_QLFY_C, ACQR_TYPE_C, ACQR_ADHC_X, ACQR_SRCE_C, PDCT_N, APPT_I, SRCE_SYST_C, SRCE_SYST_APPT_PDCT_I, LOAN_FNDD_METH_C, NEW_ACCT_F, EFFT_D, BROK_PATY_I, COPY_FROM_OTHR_APPT_F, EXPY_D, PROS_KEY_EFFT_I, PROS_KEY_EXPY_I, EROR_SEQN_I, RUN_STRM, APPT_PDCT_CATG_C, ASES_D, APPT_PDCT_DURT_C 
	FROM (
		SELECT APPT_PDCT_I, APPT_QLFY_C, ACQR_TYPE_C, ACQR_ADHC_X, ACQR_SRCE_C, PDCT_N, APPT_I, SRCE_SYST_C, SRCE_SYST_APPT_PDCT_I, LOAN_FNDD_METH_C, NEW_ACCT_F, EFFT_D, BROK_PATY_I, COPY_FROM_OTHR_APPT_F, EXPY_D, PROS_KEY_EFFT_I, PROS_KEY_EXPY_I, EROR_SEQN_I, RUN_STRM, APPT_PDCT_CATG_C, ASES_D, APPT_PDCT_DURT_C,
		 ROW_NUMBER() OVER (PARTITION BY APPT_I ORDER BY 1 ASC) AS ROW_NUM 
		FROM {{ ref('XfmBusinessRules__OutTmpApptPdctDS') }}
	) AS DeDup_ApptPdct_TEMP
	WHERE ROW_NUM = 1
)

SELECT * FROM DeDup_ApptPdct