{{ config(materialized='view', tags=['XfmHL_APPFrmExt']) }}

WITH DeDup_ApptFeat AS (
	SELECT APPT_I, FEAT_I, EFFT_D, SRCE_SYST_C, SRCE_SYST_APPT_FEAT_I, SRCE_SYST_STND_VALU_Q, SRCE_SYST_STND_VALU_R, SRCE_SYST_STND_VALU_A, ACTL_VALU_Q, ACTL_VALU_R, ACTL_VALU_A, CNCY_C, OVRD_FEAT_I, OVRD_REAS_C, EXPY_D, FEAT_SEQN_N, FEAT_STRT_D, FEE_CHRG_D, PROS_KEY_EFFT_I, PROS_KEY_EXPY_I, EROR_SEQN_I, RUN_STRM, CASS_WITHHOLD_RISKBANK_FLAG 
	FROM (
		SELECT APPT_I, FEAT_I, EFFT_D, SRCE_SYST_C, SRCE_SYST_APPT_FEAT_I, SRCE_SYST_STND_VALU_Q, SRCE_SYST_STND_VALU_R, SRCE_SYST_STND_VALU_A, ACTL_VALU_Q, ACTL_VALU_R, ACTL_VALU_A, CNCY_C, OVRD_FEAT_I, OVRD_REAS_C, EXPY_D, FEAT_SEQN_N, FEAT_STRT_D, FEE_CHRG_D, PROS_KEY_EFFT_I, PROS_KEY_EXPY_I, EROR_SEQN_I, RUN_STRM, CASS_WITHHOLD_RISKBANK_FLAG,
		 ROW_NUMBER() OVER (PARTITION BY APPT_I, FEAT_I ORDER BY 1 ASC) AS ROW_NUM 
		FROM {{ ref('OutTmpAppFeatFunlStg') }}
	) AS DeDup_ApptFeat_TEMP
	WHERE ROW_NUM = 1
)

SELECT * FROM DeDup_ApptFeat