USE DATABASE GDW1_STG;

CREATE SCHEMA IF NOT EXISTS GDW1_STG.FILES;
CREATE SCHEMA IF NOT EXISTS GDW1_STG.DATASETS;

-- change the date according to the etl_process_dt (20250807) and populate data using he ingetion framework.
create or replace TABLE GDW1_STG.FILES.CBA_APP__CSEL4__PROD__INPROCESS__CSE_CPL_BUS_APP_CSE_CPL_BUS_APP_20250807__DLY (
	RECORD_TYPE VARCHAR(1),
	MOD_TIMESTAMP VARCHAR(25),
	PL_APP_ID VARCHAR(12),
	NOMINATED_BRANCH_ID VARCHAR(12),
	PL_PACKAGE_CAT_ID VARCHAR(12),
	DUMMY VARCHAR(1)
);
