CREATE OR REPLACE PROCEDURE PS_GDW1_BTEQ.BTEQ_SPS.PRTF_TECH_ACCT_OWN_REL_PSST_PROC(
  ERROR_TABLE STRING DEFAULT 'PROCESS_ERROR_LOG',
  PROCESS_KEY STRING DEFAULT 'UNKNOWN_PROCESS'
)
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
  error_code INTEGER DEFAULT 0;
  row_count INTEGER DEFAULT 0;
  total_inserted INTEGER DEFAULT 0;
BEGIN
  -- Object Name: prtf_tech_acct_own_rel_psst.sql
  -- Description: Persist rows for DERV_PRTF_ACCT_OWN view
  -- Original Author: Helen Zak (09/01/2014)
  
  -- Delete all rows from target table
  DELETE FROM PS_CLD_RW.STARCADPRODDATA.DERV_PRTF_ACCT_OWN_REL;
  
  row_count := SQLROWCOUNT;
  
  -- Insert portfolio account ownership relationships
  INSERT INTO PS_CLD_RW.STARCADPRODDATA.DERV_PRTF_ACCT_OWN_REL
  (  ACCT_I 
   , INT_GRUP_I 
   , DERV_PRTF_CATG_C
   , DERV_PRTF_CLAS_C 
   , DERV_PRTF_TYPE_C 
   , PRTF_ACCT_VALD_FROM_D 
   , PRTF_ACCT_VALD_TO_D 
   , PRTF_ACCT_EFFT_D 
   , PRTF_ACCT_EXPY_D
   , PRTF_OWN_VALD_FROM_D 
   , PRTF_OWN_VALD_TO_D 
   , PRTF_OWN_EFFT_D
   , PRTF_OWN_EXPY_D
   , PTCL_N 
   , REL_MNGE_I 
   , PRTF_CODE_X 
   , DERV_PRTF_ROLE_C
   , ROLE_PLAY_TYPE_X 
   , ROLE_PLAY_I 
   , SRCE_SYST_C
   , ROW_SECU_ACCS_C
  )
  SELECT 
        PP4.ACCT_I AS ACCT_I 
      , PP4.INT_GRUP_I AS INT_GRUP_I  
      , PP4.DERV_PRTF_CATG_C AS DERV_PRTF_CATG_C 
      , PP4.DERV_PRTF_CLAS_C AS DERV_PRTF_CLAS_C 
      , PP4.DERV_PRTF_TYPE_C AS DERV_PRTF_TYPE_C 
      , PP4.VALD_FROM_D AS PRTF_ACCT_VALD_FROM_D 
      , PP4.VALD_TO_D AS PRTF_ACCT_VALD_TO_D 
      , PP4.EFFT_D AS PRTF_ACCT_EFFT_D 
      , PP4.EXPY_D AS PRTF_ACCT_EXPY_D 
      , PO4.VALD_FROM_D AS PRTF_OWN_VALD_FROM_D 
      , PO4.VALD_TO_D AS PRTF_OWN_VALD_TO_D 
      , PO4.EFFT_D AS PRTF_OWN_EFFT_D
      , PO4.EXPY_D AS PRTF_OWN_EXPY_D 
      , PP4.PTCL_N AS PTCL_N 
      , PP4.REL_MNGE_I AS REL_MNGE_I 
      , PP4.PRTF_CODE_X AS PRTF_CODE_X 
      , PO4.DERV_PRTF_ROLE_C AS DERV_PRTF_ROLE_C
      , PO4.ROLE_PLAY_TYPE_X AS ROLE_PLAY_TYPE_X 
      , PO4.ROLE_PLAY_I AS ROLE_PLAY_I
      , PP4.SRCE_SYST_C AS SRCE_SYST_C 
      , PP4.ROW_SECU_ACCS_C AS ROW_SECU_ACCS_C 
  FROM ps_gdw1_bteq.PVTECH.DERV_PRTF_ACCT_REL PP4 
  INNER JOIN ps_gdw1_bteq.PVTECH.DERV_PRTF_OWN_REL PO4 
  ON PO4.INT_GRUP_I = PP4.INT_GRUP_I 
  AND PO4.DERV_PRTF_TYPE_C = PP4.DERV_PRTF_TYPE_C;
  
  total_inserted := SQLROWCOUNT;
  
  RETURN 'SUCCESS: Deleted ' || :row_count || ' records, inserted ' || :total_inserted || ' records into DERV_PRTF_ACCT_OWN_REL';
EXCEPTION
  WHEN OTHER THEN
    RETURN 'ERROR: ' || SQLERRM || ' (Code: ' || SQLCODE || ')';
END;
$$;