SELECT BCF_CORP,
	BCF_ACCOUNT_NO1,
	BCF_PLAN_ID,
	BCF_PLAN_SEQ,
	BCF_STORE_ID,
	BCF_ORIGINAL_STATE,
	BCF_PLAN_TYPE,
	BCF_PLAN_CATEGORY,
	BCF_POST_PURCHASE_STATUS,
	BCF_TERMS_STATUS,
	BCF_INTEREST_DEFER_STATUS,
	BCF_PAYMENT_DEFER_STATUS,
	BCF_TIMES_BILLED,
	BCF_SPECIAL_TERMS_CYCLES,
	BCF_INTEREST_DEFER_CYCLES,
	BCF_PAYMENT_DEFER_CYCLES,
	BCF_DT_SPEC_TERMS_END,
	BCF_DT_INTEREST_DEFER,
	BCF_DT_PAYMENT_DEFER,
	BCF_DT_FIRST_TRANS,
	BCF_DT_PAID_OFF,
	BCF_DT_LAST_PAYMENT,
	BCF_DT_LAST_MAINT,
	BCF_LTD_HIGH_BALANCE,
	BCF_PYMT_TBL_HIGH_BALANCE,
	BCF_LTD_INTEREST_CHGD,
	BCF_LTD_INTEREST_WAIVED,
	BCF_FIXED_PAY_AMT,
	BCF_FIXED_PAY_CYCLES,
	BCF_LAST_INT_RATE,
	BCF_LAST_RATE_CODE,
	BCF_LAST_RATE_CODE_SEQ,
	BCF_LAST_MIN_PAY_CODE,
	BCF_LAST_MIN_PAY_CODE_SEQ,
	BCF_MIN_PAY_AMT,
	BCF_MIN_PAY_DUE,
	BCF_MIN_PAY_PAST_DUE,
	BCF_AMT_LAST_PYMT_APPLIED,
	BCF_PAYMENTS_BEFORE_GRACE,
	BCF_ORIGINAL_BALANCE,
	BCF_RATE_SAVER_RATE,
	FILLER4,
	BCF_PLAN_DUE_DATE,
	BCF_DATE_END_INTEREST_FREE,
	BCF_INTEREST_FREE_PRIN_AMT,
	BCF_OPENING_BALANCE,
	BCF_CURRENT,
	BCF_DEBITS,
	BCF_CREDITS,
	BCF_PAYMENTS,
	BCF_INT_OPEN_NON_ACCR,
	BCF_INT_CTD_NON_ACCR,
	BCF_INT_CURR_CYC_BAL,
	BCF_INT_1CYC_AGO_BAL,
	BCF_INT_2CYC_AGO_BAL,
	BCF_FEES_OPEN_NON_ACCR,
	BCF_FEES_CTD_NON_ACCR,
	BCF_FEES_CURR_CYC_BAL,
	BCF_FEES_1CYC_AGO_BAL,
	BCF_FEES_2CYC_AGO_BAL,
	BCF_AMF_OPEN_NON_ACCR,
	BCF_AMF_CTD_NON_ACCR,
	BCF_AMF_CURR_CYC_BAL,
	BCF_AMF_1CYC_AGO_BAL,
	BCF_AMF_2CYC_AGO_BAL,
	BCF_INS_OPEN_NON_ACCR,
	BCF_INS_CTD_NON_ACCR,
	BCF_INS_CURR_CYC_BAL,
	BCF_INS_1CYC_AGO_BAL,
	BCF_INS_2CYC_AGO_BAL,
	BCF_PRIN_OPEN_NON_ACCR,
	BCF_PRIN_CTD_NON_ACCR,
	BCF_PRIN_CURR_CYC_BAL,
	BCF_PRIN_1CYC_AGO_BAL,
	BCF_PRIN_2CYC_AGO_BAL,
	BCF_AGGR_CURR_CYC_BAL,
	BCF_AGGR_1CYC_AGO_BAL,
	BCF_AGGR_2CYC_AGO_BAL,
	BCF_AGGR_DELAYED_BAL,
	BCF_DELAYED_DAYS,
	BCF_CTD_TRANS_FEE,
	BCF_CTD_TRANS_FEE_AMT,
	BCF_DEFERRED_DAYS,
	BCF_DEFERRED_INTEREST,
	BCF_AGGR_DEFERRED_BAL,
	BCF_USER_CODE,
	BCF_MIGRATE_TO_PLAN,
	BCF_MIGRATE_TO_SEQ,
	BCF_DT_MIGRATE,
	BCF_DISPUTE_AMT,
	BCF_EXT_DISPUTE_AMT,
	BCF_ACCR_DISPUTE_AMT,
	BCF_FL_INSTALLMENTS_BILLED,
	BCF_FL_LAST_INSTALLMENT_DT,
	BCF_FL_ORIG_INTEREST_AMT,
	BCF_FL_EARNED_INTEREST_AMT,
	BCF_FL_REBATE_INTEREST_AMT,
	BCF_FL_INTEREST_RATE,
	BCF_FL_ORIG_INSUR_AMT,
	BCF_FL_EARNED_INSUR_AMT,
	BCF_FL_UPFRONT_INSUR_AMT,
	BCF_FL_REBATE_INSUR_AMT,
	BCF_SCHED_PAYOFF_DT,
	BCF_SCHED_PAYOFF_AMT,
	BCF_SCHED_PAYOFF_FEE,
	BCF_SCHED_PAYOFF_REASON,
	BCF_ACTUAL_PAYOFF_DT,
	BCF_ACTUAL_PAYOFF_AMT,
	BCF_FL_UPFRONT_INSUR_PAID,
	BCF_FL_REBATE_INSUR_PAID,
	BCF_GOVT_NON_ACCR_OPN_AMT,
	BCF_GOVT_NON_ACCR_CTD_AMT,
	BCF_GOVT_BAL_CURR_CYC_AMT,
	BCF_GOVT_BAL_1CYC_AGO_AMT,
	BCF_GOVT_BAL_2CYC_AGO_AMT,
	BCF_CTD_FIN_CHG_REV,
	BCF_INSTALL_TERM,
	BCF_PREV_INSTALL_TERM,
	BCF_DT_INSTALL_TERM_CHG,
	BCF_PREV_MIN_PAY_AMT,
	BCF_ORIG_LOAN_BAL,
	BCF_LTD_ALL_CRDTS,
	BCF_LTD_INTEREST_SAVED,
	BCF_PREV_CYC_INT_SAVED,
	BCF_DT_INSTALL_PAID,
	BCF_PROJECTED_PAYOFF_DT,
	BCF_DISPUTE_TIMES,
	BCF_DISPUTE_OLD_DATE,
	BCF_TERM,
	FILLER5,
	CASE 
		WHEN BCF_PLAN_DUE_DATE IS NULL
			THEN 'N'
		WHEN Trim(BCF_PLAN_DUE_DATE) = ''
			THEN 'N'
		WHEN TRIM(TO_CHAR(BCF_PLAN_DUE_DATE, '000000000.')) = '000000000.'
			THEN 'N'
		ELSE 'Y'
	END AS svIsNullBcfPlanDueDt,
	CONCAT (
		TRIM(SUBSTRING(IFNULL(BCF_PLAN_DUE_DATE, ''), 1, 4)),
		'-',
		TRIM(SUBSTRING(IFNULL(BCF_PLAN_DUE_DATE, ''), 5, 2)),
		'-',
		TRIM(SUBSTRING(IFNULL(BCF_PLAN_DUE_DATE, ''), 7, 2))
		) AS svTransformBcfPlanDueDt,
	CASE 
		WHEN TRY_TO_DATE(svTransformBcfPlanDueDt) IS NOT NULL
			THEN 'Y'
		WHEN TRIM(TO_CHAR(BCF_PLAN_DUE_DATE, '000000000.')) = '000000000.'
			THEN 'Y'
		ELSE 'N'
	END AS svIsValidBcfPlanDueDt,
	CASE 
		WHEN BCF_DATE_END_INTEREST_FREE IS NULL
			THEN 'N'
		WHEN TRIM(BCF_DATE_END_INTEREST_FREE) = ''
			THEN 'N'
		WHEN TRIM(TO_CHAR(BCF_DATE_END_INTEREST_FREE, '000000000.')) = '000000000.'
			THEN 'N'
		ELSE 'Y'
	END AS svIsNullBcfDtEndInterestFree,
	CONCAT (
		TRIM(SUBSTRING(IFNULL(BCF_DATE_END_INTEREST_FREE, ''), 1, 4)),
		'-',
		TRIM(SUBSTRING(IFNULL(BCF_DATE_END_INTEREST_FREE, ''), 5, 2)),
		'-',
		TRIM(SUBSTRING(IFNULL(BCF_DATE_END_INTEREST_FREE, ''), 7, 2))
		) AS svTransformBcfDtEndInterestFree,
	CASE 
		WHEN TRY_TO_DATE(svTransformBcfDtEndInterestFree) IS NOT NULL
			THEN 'Y'
		WHEN TRIM(TO_CHAR(BCF_DATE_END_INTEREST_FREE, '000000000.')) = '000000000.'
			THEN 'Y'
		ELSE 'N'
	END AS svIsValidBcfDtEndInterestFree,
	CASE 
		WHEN BCF_DT_MIGRATE IS NULL
			THEN 'N'
		WHEN TRIM( ABS(BCF_DT_MIGRATE) ) = ''
			THEN 'N'
		WHEN TRIM(TO_CHAR( ABS(BCF_DT_MIGRATE), '000000000.')) = '000000000.'
			THEN 'N'
		ELSE 'Y'
	END AS svIsNullBcfDtMigrate,
	CONCAT (
		TRIM(SUBSTRING(IFNULL( ABS(BCF_DT_MIGRATE), ''), 1, 4)),
		'-',
		TRIM(SUBSTRING(IFNULL( ABS(BCF_DT_MIGRATE), ''), 5, 2)),
		'-',
		TRIM(SUBSTRING(IFNULL( ABS(BCF_DT_MIGRATE), ''), 7, 2))
		) AS svTransformBcfDtMigrate,
	CASE 
		WHEN TRY_TO_DATE(svTransformBcfDtMigrate) IS NOT NULL
			THEN 'Y'
		WHEN TRIM(TO_CHAR( ABS(BCF_DT_MIGRATE), '000000000.')) = '000000000.'
			THEN 'Y'
		ELSE 'N'
	END AS svIsValidBcfDtMigrate,
	CASE 
		WHEN BCF_FL_LAST_INSTALLMENT_DT IS NULL
			THEN 'N'
		WHEN TRIM(BCF_FL_LAST_INSTALLMENT_DT) = ''
			THEN 'N'
		WHEN TRIM(TO_CHAR(BCF_FL_LAST_INSTALLMENT_DT, '000000000.')) = '000000000.'
			THEN 'N'
		ELSE 'Y'
	END AS svIsNullBcfFlLastInstallmentsDt,
	CONCAT (
		TRIM(SUBSTRING(IFNULL(BCF_FL_LAST_INSTALLMENT_DT, ''), 1, 4)),
		'-',
		TRIM(SUBSTRING(IFNULL(BCF_FL_LAST_INSTALLMENT_DT, ''), 5, 2)),
		'-',
		TRIM(SUBSTRING(IFNULL(BCF_FL_LAST_INSTALLMENT_DT, ''), 7, 2))
		) AS svTransformBcfFlLastInstallmentsDt,
	CASE 
		WHEN TRY_TO_DATE(svTransformBcfFlLastInstallmentsDt) IS NOT NULL
			THEN 'Y'
		WHEN TRIM(TO_CHAR(BCF_FL_LAST_INSTALLMENT_DT, '000000000.')) = '000000000.'
			THEN 'Y'
		ELSE 'N'
	END AS svIsValidBcfFlLastInstallmentsDt,
	CASE 
		WHEN BCF_SCHED_PAYOFF_DT IS NULL
			THEN 'N'
		WHEN TRIM(BCF_SCHED_PAYOFF_DT) = ''
			THEN 'N'
		WHEN TRIM(TO_CHAR(BCF_SCHED_PAYOFF_DT, '000000000.')) = '000000000.'
			THEN 'N'
		ELSE 'Y'
	END AS svIsNullBcfSchedPayoffDt,
	CONCAT (
		TRIM(SUBSTRING(IFNULL(BCF_SCHED_PAYOFF_DT, ''), 1, 4)),
		'-',
		TRIM(SUBSTRING(IFNULL(BCF_SCHED_PAYOFF_DT, ''), 5, 2)),
		'-',
		TRIM(SUBSTRING(IFNULL(BCF_SCHED_PAYOFF_DT, ''), 7, 2))
		) AS svTransformBcfSchedPayoffDt,
	CASE 
		WHEN TRY_TO_DATE(svTransformBcfSchedPayoffDt) IS NOT NULL
			THEN 'Y'
		WHEN TRIM(TO_CHAR(BCF_SCHED_PAYOFF_DT, '000000000.')) = '000000000.'
			THEN 'Y'
		ELSE 'N'
	END AS svIsValidBcfSchedPayoffDt,
	CASE 
		WHEN BCF_ACTUAL_PAYOFF_DT IS NULL
			THEN 'N'
		WHEN TRIM(BCF_ACTUAL_PAYOFF_DT) = ''
			THEN 'N'
		WHEN TRIM(TO_CHAR(BCF_ACTUAL_PAYOFF_DT, '000000000.')) = '000000000.'
			THEN 'N'
		ELSE 'Y'
	END AS svIsNullBcfActualPayoffDt,
	CONCAT (
		TRIM(SUBSTRING(IFNULL(BCF_ACTUAL_PAYOFF_DT, ''), 1, 4)),
		'-',
		TRIM(SUBSTRING(IFNULL(BCF_ACTUAL_PAYOFF_DT, ''), 5, 2)),
		'-',
		TRIM(SUBSTRING(IFNULL(BCF_ACTUAL_PAYOFF_DT, ''), 7, 2))
		) AS svTransformBcfActualPayoffDt,
	CASE 
		WHEN TRY_TO_DATE(svTransformBcfActualPayoffDt) IS NOT NULL
			THEN 'Y'
		WHEN TRIM(TO_CHAR(BCF_ACTUAL_PAYOFF_DT, '000000000.')) = '000000000.'
			THEN 'Y'
		ELSE 'N'
	END AS svIsValidBcfActualPayoffDt,
	CASE 
		WHEN BCF_DT_INSTALL_TERM_CHG IS NULL
			THEN 'N'
		WHEN TRIM(BCF_DT_INSTALL_TERM_CHG) = ''
			THEN 'N'
		WHEN TRIM(TO_CHAR(BCF_DT_INSTALL_TERM_CHG, '000000000.')) = '000000000.'
			THEN 'N'
		ELSE 'Y'
	END AS svIsNullBcfDtInstallTermChg,
	CONCAT (
		TRIM(SUBSTRING(IFNULL(BCF_DT_INSTALL_TERM_CHG, ''), 1, 4)),
		'-',
		TRIM(SUBSTRING(IFNULL(BCF_DT_INSTALL_TERM_CHG, ''), 5, 2)),
		'-',
		TRIM(SUBSTRING(IFNULL(BCF_DT_INSTALL_TERM_CHG, ''), 7, 2))
		) AS svTransformBcfDtInstallTermChg,
	CASE 
		WHEN TRY_TO_DATE(svTransformBcfDtInstallTermChg) IS NOT NULL
			THEN 'Y'
		WHEN TRIM(TO_CHAR(BCF_DT_INSTALL_TERM_CHG, '000000000.')) = '000000000.'
			THEN 'Y'
		ELSE 'N'
	END AS svIsValidBcfDtInstallTermChg,
	CASE 
		WHEN BCF_DT_INSTALL_PAID IS NULL
			THEN 'N'
		WHEN TRIM(BCF_DT_INSTALL_PAID) = ''
			THEN 'N'
		WHEN TRIM(TO_CHAR(BCF_DT_INSTALL_PAID, '000000000.')) = '000000000.'
			THEN 'N'
		ELSE 'Y'
	END AS svIsNullBcfDtInstallPaid,
	CONCAT (
		TRIM(SUBSTRING(IFNULL(BCF_DT_INSTALL_PAID, ''), 1, 4)),
		'-',
		TRIM(SUBSTRING(IFNULL(BCF_DT_INSTALL_PAID, ''), 5, 2)),
		'-',
		TRIM(SUBSTRING(IFNULL(BCF_DT_INSTALL_PAID, ''), 7, 2))
		) AS svTransformBcfDtInstallPaid,
	CASE 
		WHEN TRY_TO_DATE(svTransformBcfDtInstallPaid) IS NOT NULL
			THEN 'Y'
		WHEN TRIM(TO_CHAR(BCF_DT_INSTALL_PAID, '000000000.')) = '000000000.'
			THEN 'Y'
		ELSE 'N'
	END AS svIsValidBcfDtInstallPaid,
	CASE 
		WHEN BCF_PROJECTED_PAYOFF_DT IS NULL
			THEN 'N'
		WHEN TRIM(BCF_PROJECTED_PAYOFF_DT) = ''
			THEN 'N'
		WHEN TRIM(TO_CHAR(BCF_PROJECTED_PAYOFF_DT, '000000000.')) = '000000000.'
			THEN 'N'
		ELSE 'Y'
	END AS svIsNullBcfProjectedPayoffDt,
	CASE 
		WHEN svIsNullBcfProjectedPayoffDt = 'Y'
			THEN DATEADD(DAY, TO_NUMBER(BCF_PROJECTED_PAYOFF_DT) - 1721426, DATE '0001-01-01') --DateFromJulianDay(BCF_PROJECTED_PAYOFF_DT) 
		ELSE NULL
	END AS svTransformBcfProjectedPayoffDt,
	CASE 
		WHEN TRY_TO_DATE(svTransformBcfProjectedPayoffDt) IS NOT NULL
			THEN 'Y'
		WHEN TRIM(TO_CHAR(BCF_PROJECTED_PAYOFF_DT, '000000000.')) = '000000000.'
			THEN 'Y'
		ELSE 'N'
	END AS svIsValidBcfProjectedPayoffDt,
	CASE 
		WHEN BCF_DISPUTE_OLD_DATE IS NULL
			THEN 'N'
		WHEN TRIM(BCF_DISPUTE_OLD_DATE) = ''
			THEN 'N'
		WHEN TRIM(TO_CHAR(BCF_DISPUTE_OLD_DATE, '000000000.')) = '000000000.'
			THEN 'N'
		ELSE 'Y'
	END AS svIsNullBcfDisputeOldDt,
	CONCAT (
		TRIM(SUBSTRING(IFNULL(BCF_DISPUTE_OLD_DATE, ''), 1, 4)),
		'-',
		TRIM(SUBSTRING(IFNULL(BCF_DISPUTE_OLD_DATE, ''), 5, 2)),
		'-',
		TRIM(SUBSTRING(IFNULL(BCF_DISPUTE_OLD_DATE, ''), 7, 2))
		) AS svTransformBcfDisputeOldDt,
	CASE 
		WHEN TRY_TO_DATE(svTransformBcfDisputeOldDt) IS NOT NULL
			THEN 'Y'
		WHEN TRIM(TO_CHAR(BCF_DISPUTE_OLD_DATE, '000000000.')) = '000000000.'
			THEN 'Y'
		ELSE 'N'
	END AS svIsValidBcfDisputeOldDt,
	CASE 
		WHEN BCF_DT_LAST_PAYMENT IS NULL
			THEN 'N'
		WHEN TRIM(BCF_DT_LAST_PAYMENT) = ''
			THEN 'N'
		WHEN TRIM(TO_CHAR(BCF_DT_LAST_PAYMENT, '000000000.')) = '000000000.'
			THEN 'N'
		ELSE 'Y'
	END AS svIsNullBcfDtLastPayt,
	CONCAT (
		TRIM(SUBSTRING(IFNULL(BCF_DT_LAST_PAYMENT, ''), 1, 4)),
		'-',
		TRIM(SUBSTRING(IFNULL(BCF_DT_LAST_PAYMENT, ''), 5, 2)),
		'-',
		TRIM(SUBSTRING(IFNULL(BCF_DT_LAST_PAYMENT, ''), 7, 2))
		) AS svTransformBcfDtLastPayt,
	CASE 
		WHEN TRY_TO_DATE(svTransformBcfDtLastPayt) IS NOT NULL
			THEN 'Y'
		WHEN TRIM(TO_CHAR(BCF_DT_LAST_PAYMENT, '000000000.')) = '000000000.'
			THEN 'Y'
		ELSE 'N'
	END AS svIsValidBcfDtLastPayt,
	CASE 
		WHEN BCF_DT_LAST_MAINT IS NULL
			THEN 'N'
		WHEN TRIM(BCF_DT_LAST_MAINT) = ''
			THEN 'N'
		WHEN TRIM(TO_CHAR(BCF_DT_LAST_MAINT, '000000000.')) = '000000000.'
			THEN 'N'
		ELSE 'Y'
	END AS svIsNullBcfDtLastMntn,
	CONCAT (
		TRIM(SUBSTRING(IFNULL(BCF_DT_LAST_MAINT, ''), 1, 4)),
		'-',
		TRIM(SUBSTRING(IFNULL(BCF_DT_LAST_MAINT, ''), 5, 2)),
		'-',
		TRIM(SUBSTRING(IFNULL(BCF_DT_LAST_MAINT, ''), 7, 2))
		) AS svTransformBcfDtLastMntn,
	CASE 
		WHEN TRY_TO_DATE(svTransformBcfDtLastMntn) IS NOT NULL
			THEN 'Y'
		WHEN TRIM(TO_CHAR(BCF_DT_LAST_MAINT, '000000000.')) = '000000000.'
			THEN 'Y'
		ELSE 'N'
	END AS svIsValidBcfDtLastMntn,
	CASE 
		WHEN BCF_DT_PAID_OFF IS NULL
			THEN 'N'
		WHEN TRIM(BCF_DT_PAID_OFF) = ''
			THEN 'N'
		WHEN TRIM(TO_CHAR(BCF_DT_PAID_OFF, '000000000.')) = '000000000.'
			THEN 'N'
		ELSE 'Y'
	END AS svIsNullBcfDtPaidOff,
	CONCAT (
		TRIM(SUBSTRING(IFNULL(BCF_DT_PAID_OFF, ''), 1, 4)),
		'-',
		TRIM(SUBSTRING(IFNULL(BCF_DT_PAID_OFF, ''), 5, 2)),
		'-',
		TRIM(SUBSTRING(IFNULL(BCF_DT_PAID_OFF, ''), 7, 2))
		) AS svTransformBcfDtPaidOff,
	CASE 
		WHEN TRY_TO_DATE(svTransformBcfDtPaidOff) IS NOT NULL
			THEN 'Y'
		WHEN TRIM(TO_CHAR(BCF_DT_PAID_OFF, '000000000.')) = '000000000.'
			THEN 'Y'
		ELSE 'N'
	END AS svIsValidBcfDtPaidOff,
	CASE 
		WHEN BCF_DT_FIRST_TRANS IS NULL
			THEN 'N'
		WHEN TRIM(BCF_DT_FIRST_TRANS) = ''
			THEN 'N'
		WHEN TRIM(TO_CHAR(BCF_DT_FIRST_TRANS, '000000000.')) = '000000000.'
			THEN 'N'
		ELSE 'Y'
	END AS svIsNullBcfDtFirstTrans,
	CONCAT (
		TRIM(SUBSTRING(IFNULL(BCF_DT_FIRST_TRANS, ''), 1, 4)),
		'-',
		TRIM(SUBSTRING(IFNULL(BCF_DT_FIRST_TRANS, ''), 5, 2)),
		'-',
		TRIM(SUBSTRING(IFNULL(BCF_DT_FIRST_TRANS, ''), 7, 2))
		) AS svTransformBcfDtFirstTrans,
	CASE 
		WHEN TRY_TO_DATE(svTransformBcfDtFirstTrans) IS NOT NULL
			THEN 'Y'
		WHEN TRIM(TO_CHAR(BCF_DT_FIRST_TRANS, '000000000.')) = '000000000.'
			THEN 'Y'
		ELSE 'N'
	END AS svIsValidBcfDtFirstTrans,
	CASE 
		WHEN BCF_DT_PAYMENT_DEFER IS NULL
			THEN 'N'
		WHEN TRIM(BCF_DT_PAYMENT_DEFER) = ''
			THEN 'N'
		WHEN TRIM(TO_CHAR(BCF_DT_PAYMENT_DEFER, '000000000.')) = '000000000.'
			THEN 'N'
		ELSE 'Y'
	END AS svIsNullBcfDtPaymentDefer,
	CONCAT (
		TRIM(SUBSTRING(IFNULL(BCF_DT_PAYMENT_DEFER, ''), 1, 4)),
		'-',
		TRIM(SUBSTRING(IFNULL(BCF_DT_PAYMENT_DEFER, ''), 5, 2)),
		'-',
		TRIM(SUBSTRING(IFNULL(BCF_DT_PAYMENT_DEFER, ''), 7, 2))
		) AS svTransformBcfDtPaymentDefer,
	CASE 
		WHEN TRY_TO_DATE(svTransformBcfDtPaymentDefer) IS NOT NULL
			THEN 'Y'
		WHEN TRIM(TO_CHAR(BCF_DT_PAYMENT_DEFER, '000000000.')) = '000000000.'
			THEN 'Y'
		ELSE 'N'
	END AS svIsValidBcfDtPaymentDefer,
	CASE 
		WHEN BCF_DT_INTEREST_DEFER IS NULL
			THEN 'N'
		WHEN TRIM(BCF_DT_INTEREST_DEFER) = ''
			THEN 'N'
		WHEN TRIM(TO_CHAR(BCF_DT_INTEREST_DEFER, '000000000.')) = '000000000.'
			THEN 'N'
		ELSE 'Y'
	END AS svIsNullBcfDtInterestDefer,
	CONCAT (
		TRIM(SUBSTRING(IFNULL(BCF_DT_INTEREST_DEFER, ''), 1, 4)),
		'-',
		TRIM(SUBSTRING(IFNULL(BCF_DT_INTEREST_DEFER, ''), 5, 2)),
		'-',
		TRIM(SUBSTRING(IFNULL(BCF_DT_INTEREST_DEFER, ''), 7, 2))
		) AS svTransformBcfDtInterestDefer,
	CASE 
		WHEN TRY_TO_DATE(svTransformBcfDtInterestDefer) IS NOT NULL
			THEN 'Y'
		WHEN TRIM(TO_CHAR(BCF_DT_INTEREST_DEFER, '000000000.')) = '000000000.'
			THEN 'Y'
		ELSE 'N'
	END AS svIsValidBcfDtInterestDefer,
	CASE 
		WHEN BCF_DT_SPEC_TERMS_END IS NULL
			THEN 'N'
		WHEN TRIM(BCF_DT_SPEC_TERMS_END) = ''
			THEN 'N'
		WHEN TRIM(TO_CHAR(BCF_DT_SPEC_TERMS_END, '000000000.')) = '000000000.'
			THEN 'N'
		ELSE 'Y'
	END AS svIsNullBcfDtSpecTermsEnd,
	CONCAT (
		TRIM(SUBSTRING(IFNULL(BCF_DT_SPEC_TERMS_END, ''), 1, 4)),
		'-',
		TRIM(SUBSTRING(IFNULL(BCF_DT_SPEC_TERMS_END, ''), 5, 2)),
		'-',
		TRIM(SUBSTRING(IFNULL(BCF_DT_SPEC_TERMS_END, ''), 7, 2))
		) AS svTransformBcfDtSpecTermsEnd,
	CASE 
		WHEN TRY_TO_DATE(svTransformBcfDtSpecTermsEnd) IS NOT NULL
			THEN 'Y'
		WHEN TRIM(TO_CHAR(BCF_DT_SPEC_TERMS_END, '000000000.')) = '000000000.'
			THEN 'Y'
		ELSE 'N'
	END AS svIsValidBcfDtSpecTermsEnd,
	CASE 
		WHEN BCF_CORP IS NULL
			THEN 'Y'
		WHEN trim(BCF_CORP) = ''
			THEN 'Y'
		WHEN trim(BCF_CORP) = '0'
			THEN 'Y'
		WHEN BCF_ACCOUNT_NO1 IS NULL
			THEN 'Y'
		WHEN trim(BCF_ACCOUNT_NO1) = ''
			THEN 'Y'
		WHEN trim(BCF_ACCOUNT_NO1) = '0'
			THEN 'Y'
		WHEN BCF_PLAN_ID IS NULL
			THEN 'Y'
		WHEN trim(BCF_PLAN_ID) = ''
			THEN 'Y'
		WHEN trim(BCF_PLAN_ID) = '0'
			THEN 'Y'
		ELSE 'N'
	END AS svIsValidRecord,
--	IFF(svRowI = 0, @PARTITIONNUM + 1, svRowI + @NUMPARTITIONS) AS svRowI
	ROW_NUMBER() OVER (ORDER BY null) AS svRowI
FROM {{ ref("bcfinsg__xfmplanbalnsegmmstrfrombcfinsg") }}