{{ config(materialized='view', tags=['ExtChlBusPrtyAdrs']) }}

WITH FunMergeSourceAndRejt AS (
	SELECT
		CHL_APP_HL_APP_ID as CHL_APP_HL_APP_ID,
		CHL_APP_SUBTYPE_CODE as CHL_APP_SUBTYPE_CODE,
		CHL_APP_SECURITY_ID as CHL_APP_SECURITY_ID,
		CHL_ASSET_LIABILITY_ID as CHL_ASSET_LIABILITY_ID,
		CHL_PRINCIPAL_SECURITY_FLAG as CHL_PRINCIPAL_SECURITY_FLAG,
		CHL_ADDRESS_LINE_1 as CHL_ADDRESS_LINE_1,
		CHL_ADDRESS_LINE_2 as CHL_ADDRESS_LINE_2,
		CHL_SUBURB as CHL_SUBURB,
		CHL_STATE as CHL_STATE,
		CHL_POSTCODE as CHL_POSTCODE,
		CHL_DPID as CHL_DPID,
		CHL_COUNTRY_ID as CHL_COUNTRY_ID,
		ORIG_ETL_D as ORIG_ETL_D
	FROM {{ ref('XfmSeparateRejectWithoutSourceAndTheRest__InSourceRec') }}
	UNION ALL
	SELECT
		CHL_APP_HL_APP_ID,
		CHL_APP_SUBTYPE_CODE,
		CHL_APP_SECURITY_ID,
		CHL_ASSET_LIABILITY_ID,
		CHL_PRINCIPAL_SECURITY_FLAG,
		CHL_ADDRESS_LINE_1,
		CHL_ADDRESS_LINE_2,
		CHL_SUBURB,
		CHL_STATE,
		CHL_POSTCODE,
		CHL_DPID,
		CHL_COUNTRY_ID,
		ORIG_ETL_D
	FROM {{ ref('XfmSeparateRejectWithoutSourceAndTheRest__InRejectWithoutSourceRec') }}
)

SELECT * FROM FunMergeSourceAndRejt