{{ config(materialized='view', tags=['ExtChlBusPrtyAdrs']) }}

WITH 
rejt_chl_bus_prty_adrs AS (
	SELECT
	*
	FROM {{ source("cse4_stg","rejt_chl_bus_prty_adrs")  }}),
SrcRejtRejectOra AS (SELECT CHL_APP_HL_APP_ID, CHL_APP_SUBTYPE_CODE, CHL_APP_SECURITY_ID, CHL_ASSET_LIABILITY_ID, CHL_PRCP_SCUY_FLAG, CHL_ADDRESS_LINE_1, CHL_ADDRESS_LINE_2, CHL_SUBURB, CHL_STATE, CHL_POSTCODE, CHL_DPID, CHL_COUNTRY_ID, CAST(ORIG_ETL_D AS TEXT) AS ORIG_ETL_D FROM REJT_CHL_BUS_PRTY_ADRS WHERE EROR_C LIKE 'RPR%')


SELECT * FROM SrcRejtRejectOra