{{ config(materialized='view', tags=['XfmAppCclAppChlAppFrmExt']) }}

WITH ModNullHandling AS (
	SELECT 
	--Manual
	--APPT_QLFY_C: nullable string[2]= handle_null (APPT_QLFY_C, '99')
	--APPT_C:nullable string[4] = handle_null (APPT_C, '9999')
	--APPT_TU_C:nullable string[4] = handle_null (APPT_C_TU, '9999')
	--APPT_FORM_C:nullable string[4] = handle_null (APPT_FORM_C, '9999')
	--APPT_ORIG_C:nullable string[4] = handle_null(APPT_ORIG_C, '9999')
	--APP_SUBTYPE_CODE:nullable string[max=12] =handle_null(SBTY_CODE,'-1')
	--APP_CHANNEL_CAT_ID = CHNL_CAT_ID
	--CCL_APP_CCL_APP_CAT_ID = CCL_APP_CAT_ID
	--CCL_APP_CCL_FORM_CAT_ID = CCL_FORM_CAT_ID
	--TPB_APPT_QLFY_C: nullable string[2]= handle_null (TPB_APPT_QLFY_C, '99')
	--STAT_X: NULLABLE STRING[4]=handle_null(STAT_X, 'UNK')
	--ORIG_SRCE_SYST_C: nullable string[3]=handle_null(ORIG_SRCE_SYST_C,'UNK')
	--APPT_C_TPB:nullable string[4] = handle_null(APPT_C_TPB, '9999')
	--APPT_C_HLM:nullable string[4] = handle_null(APPT_C_HLM, '9999')
	APP_ID, APP_APP_ID, SBTY_CODE AS APP_SUBTYPE_CODE, APP_APP_NO, APP_CREATED_DATE, APP_CREATED_BY_STAFF_NUMBER, APP_OWNED_BY_STAFF_NUMBER, CHNL_CAT_ID AS APP_CHANNEL_CAT_ID, APP_LODGEMENT_BRANCH_ID, APP_SM_CASE_ID, CCL_APP_CCL_APP_ID, CCL_APP_CAT_ID AS CCL_APP_CCL_APP_CAT_ID, CCL_FORM_CAT_ID AS CCL_APP_CCL_FORM_CAT_ID, CCL_APP_TOT_PERSONAL_FAC_AMT, CCL_APP_TOT_EQUIPFIN_FAC_AMT, CCL_APP_TOT_COMMERCIAL_FAC_AMT, CCL_APP_TOPUP_APP_ID, CCL_APP_AF_PRIMARY_INDUSTRY_ID, CCL_APP_AD_TUC_AMT, CCL_APP_COMMISSION_AMT, CCL_APP_BROKER_REFERAL_FLAG, CHL_APP_HL_APP_ID, CHL_APP_HL_PACKAGE_CAT_ID, CHL_APP_LPC_OFFICE, CHL_APP_STATUS_TRACKER_ID, APP_FOUND_FLAG, CCL_APP_FOUND_FLAG, CHL_APP_FOUND_FLAG, ORIG_ETL_D, APPT_QLFY_C, APPT_C, APPT_FORM_C, CHNL_TYPE_C AS APPT_ORIG_C, APPT_TU_C, CHL_TPB_HL_APP_ID, CHL_TPB_SUBTYPE_CODE, REL_MANAGER_STATE_ID, DATE_RECEIVED, CHL_TPB_FOUND_FLAG, TPB_APPT_QLFY_C, STAT_X, ORIG_SRCE_SYST_I, ORIG_SRCE_SYST_C, APPT_C_TPB, APPT_C_HLM, ORIG_APPT_SRCE_SYST_C, HL_BUSN_CHNL_CAT_I, HLM_APP_PROD_ID, HLM_APP_DISCHARGE_REASON_ID, HLM_APP_CRIS_PRODUCT_ID, HLM_APP_ACCOUNT_NUMBER, HLM_APP_FOUND_FLAG, HLM_APP_TYPE_CAT_ID, CCC_APP_CC_APP_CAT_ID, CCC_APP_FOUND_FLAG 
	FROM {{ ref('LkpReferences') }}
)

SELECT * FROM ModNullHandling