{{ config(materialized='incremental', alias='_cba__app_csel4_csel4dev_dataset_cse__cpl__bus__int__rate__amt__margin__merge__20060101', incremental_strategy='insert_overwrite', tags=['MergePlIntRatePlMargin']) }}

SELECT
	PL_INT_RATE_ID,
	PL_INT_RATE_PL_INT_RATE_ID,
	PL_INT_RATE_DOC_SEQ_NO,
	PL_INT_RATE_CASS_MARGIN_AMT,
	PL_INT_RATE_INT_RATE_TERM,
	PL_INT_RATE_INT_RATE_FREQUENCY_ID,
	PL_INT_RATE_VARIANT_CAT_ID,
	PL_INT_RATE_USAGE_CAT_ID,
	PL_INT_RATE_PL_APP_PROD_ID,
	PL_MARGIN_PL_MARGIN_ID,
	PL_MARGIN_MARGIN_AMT,
	PL_MARGIN_PL_FEE_ID,
	PL_MARGIN_PL_INT_RATE_ID,
	PL_MARGIN_MARGIN_REASON_CAT_ID,
	PL_MARGIN_PL_APP_PROD_ID,
	PL_INT_RATE_AMT_INT_RATE_AMT_2,
	PL_INT_RATE_AMT_PL_INT_RATE_CAT_ID_2,
	PL_INT_RATE_AMT_PL_INT_RATE_ID,
	PL_INT_RATE_AMT_INT_RATE_AMT_1,
	PL_INT_RATE_AMT_PL_INT_RATE_CAT_ID_1,
	PL_MARGIN_FOUND_FLAG,
	PL_INT_RATE_FOUND_FLAG,
	PL_INT_RATE_AMT_FOUND_FLAG 
FROM {{ ref('Identify_PL_INT_RATE_ID') }}