{{ config(materialized='view', tags=['XfmHL_APP_PRODFrmExt']) }}

WITH CpyRename AS (
	SELECT
		HL_APP_PROD_ID,
		PARENT_HL_APP_PROD_ID,
		HL_REPAYMENT_PERIOD_CAT_ID,
		AMOUNT,
		LOAN_TERM_MONTHS,
		ACCOUNT_NUMBER,
		TOTAL_LOAN_AMOUNT,
		HLS_FLAG,
		GDW_UPDATED_LDP_PAID_ON_AMOUNT,
		ORIG_ETL_D
	FROM {{ ref('SrcHlAppProdPremapDS') }}
)

SELECT * FROM CpyRename