{{ config(materialized='view', tags=['XfmDelFlagACCT_APPT_PDCT']) }}

WITH XfmProsKey AS (
	SELECT
		-- *SRC*: \(20)If OutJoin.DLTD_TABL_NAME = 'CCL_APP_PROD' Then 'HL' Else ( If OutJoin.DLTD_TABL_NAME = 'HL_APP_PROD' Then 'HL' Else ( If OutJoin.DLTD_TABL_NAME = 'PL_APP_PROD' Then 'PL' Else ( If OutJoin.DLTD_TABL_NAME = 'CC_APP_PROD' Then 'CC' Else ''))),
		IFF({{ ref('TMP_DELETED') }}.DLTD_TABL_NAME = 'CCL_APP_PROD', 'HL', IFF({{ ref('TMP_DELETED') }}.DLTD_TABL_NAME = 'HL_APP_PROD', 'HL', IFF({{ ref('TMP_DELETED') }}.DLTD_TABL_NAME = 'PL_APP_PROD', 'PL', IFF({{ ref('TMP_DELETED') }}.DLTD_TABL_NAME = 'CC_APP_PROD', 'CC', '')))) AS svStreamType,
		DLTD_TABL_NAME,
		DLTD_KEY1_VALU,
		{{ ref('TMP_DELETED') }}.DLTD_KEY1_VALU AS APP_PROD_ID,
		-- *SRC*: \(20)If OutJoin.DLTD_TABL_NAME = 'CCL_APP_PROD' Then 'CSE_CCL_BUS_APP_PROD_ACCT_APPT_PDCT' Else ( If OutJoin.DLTD_TABL_NAME = 'HL_APP_PROD' Then 'CSE_CHL_BUS_APP_PROD_ACCT_APPT_PDCT' Else ( If OutJoin.DLTD_TABL_NAME = 'PL_APP_PROD' Then 'CSE_CPL_BUS_APP_PROD_ACCT_APPT_PDCT' Else ( If OutJoin.DLTD_TABL_NAME = 'CC_APP_PROD' Then 'CSE_CCC_BUS_APP_PROD_ACCT_APPT_PDCT' Else ''))),
		IFF(
	    {{ ref('TMP_DELETED') }}.DLTD_TABL_NAME = 'CCL_APP_PROD', 'CSE_CCL_BUS_APP_PROD_ACCT_APPT_PDCT', 
	    IFF({{ ref('TMP_DELETED') }}.DLTD_TABL_NAME = 'HL_APP_PROD', 'CSE_CHL_BUS_APP_PROD_ACCT_APPT_PDCT', IFF({{ ref('TMP_DELETED') }}.DLTD_TABL_NAME = 'PL_APP_PROD', 'CSE_CPL_BUS_APP_PROD_ACCT_APPT_PDCT', IFF({{ ref('TMP_DELETED') }}.DLTD_TABL_NAME = 'CC_APP_PROD', 'CSE_CCC_BUS_APP_PROD_ACCT_APPT_PDCT', '')))
	) AS CONV_M,
		APPT_PDCT_I,
		ACCT_I
	FROM {{ ref('TMP_DELETED') }}
	WHERE 
)

SELECT * FROM XfmProsKey