{{ config(materialized='view', tags=['DltPATY_RELFrmTMP_FA_CLIENT_UNDERTAKING2']) }}

WITH 
paty_rel AS (
	SELECT
	*
	FROM {{ ref("paty_rel")  }}),
paty_int_grup AS (
	SELECT
	*
	FROM {{ ref("paty_int_grup")  }}),
tmp_fa_clnt_utak AS (
	SELECT
	*
	FROM {{ ref("tmp_fa_clnt_utak")  }}),
SrcTmpFAClientUndertakingTera AS (SELECT tmp_int.REL_I, tmp_int.SRCE_SYST_REL_I, tmp_int.REL_TYPE_C, tmp_int.RELD_PATY_I, tmp_int.SRCE_SYST_C, tmp_int.PATY_ROLE_C, tmp_int.REL_STUS_C, tmp_int.REL_EFFT_D, tmp_int.REL_EXPY_D, tmp_int.REL_REAS_C, tmp_int.REL_LEVL_C, tmp_int.CSE_FA_CLNT_UNTK_ID, tmp_int.CSE_FA_UNTK_ID, tmp_int.CSE_COIN_ENTY_ID, tmp_int.CSE_CLNT_CORR_ID, tmp_int.CSE_FA_ENTY_CAT_ID, tmp_int.CSE_FA_CHLD_STAT_CAT_ID, tmp_int.CSE_CLNT_REL_TYPE_ID, tmp_int.CSE_CLNT_POSN, tmp_int.CSE_IS_PRIM_FLAG, tmp_int.CSE_CIF_CODE, tmp_int.CSE_ORIG_ETL_D, tmp_int.PATY_I, gdw.REL_I AS OLD_REL_I, gdw.REL_TYPE_C AS OLD_REL_TYPE_C, gdw.RELD_PATY_I AS OLD_RELD_PATY_I, gdw.REL_LEVL_C AS OLD_REL_LEVL_C, gdw.PATY_I AS OLD_PATY_I, gdw.EFFT_D AS OLD_EFFT_D, gdw.SRCE_SYST_REL_I AS OLD_SRCE_SYST_REL_I, gdw.SRCE_SYST_C AS OLD_SRCE_SYST_C, gdw.PATY_ROLE_C AS OLD_PATY_ROLE_C, gdw.REL_STUS_C AS OLD_REL_STUS_C, gdw.REL_EFFT_D AS OLD_REL_EFFT_D, gdw.REL_EXPY_D AS OLD_REL_EXPY_D, gdw.REL_REAS_C AS OLD_REL_REAS_C FROM (SELECT a.REL_I, a.SRCE_SYST_REL_I, a.REL_TYPE_C_CHLD AS REL_TYPE_C, a.RELD_PATY_I_CHILD AS RELD_PATY_I, a.SRCE_SYST_C, a.PATY_ROLE_C, a.REL_STUS_C, a.REL_EFFT_D, a.REL_EXPY_D, a.REL_REAS_C, a.REL_LEVL_C_CHLD AS REL_LEVL_C, a.CSE_FA_CLNT_UNTK_ID, a.CSE_FA_UNTK_ID, a.CSE_COIN_ENTY_ID, a.CSE_CLNT_CORR_ID, a.CSE_FA_ENTY_CAT_ID, a.CSE_FA_CHLD_STAT_CAT_ID, a.CSE_CLNT_REL_TYPE_ID, a.CSE_CLNT_POSN, a.CSE_IS_PRIM_FLAG, a.CSE_CIF_CODE, a.CSE_ORIG_ETL_D, b.PATY_I FROM TMP_FA_CLNT_UTAK LEFT OUTER JOIN PATY_INT_GRUP ON TRIM(a.INT_GRUP_I) = TRIM(b.INT_GRUP_I) AND b.EXPY_D = '9999-12-31' AND b.PRIM_CLNT_F = 'Y' WHERE PATY_REL_CHLD_F = 'Y') AS tmp_int LEFT OUTER JOIN PATY_REL ON TRIM(tmp_int.REL_I) = TRIM(gdw.REL_I) AND gdw.EXPY_D = '9999-12-31' AND gdw.REL_LEVL_C = 'SECN')


SELECT * FROM SrcTmpFAClientUndertakingTera