{{ config(materialized='view', tags=['XfmAppt_Pdct_Amt']) }}

WITH FunnelXfm AS (
	SELECT
		APPT_PDCT_I as APPT_PDCT_I,
		AMT_TYPE_C as AMT_TYPE_C,
		CNCY_C as CNCY_C,
		APPT_PDCT_A as APPT_PDCT_A,
		XCES_AMT_REAS_X as XCES_AMT_REAS_X,
		EFFT_D as EFFT_D,
		SRCE_SYST_C as SRCE_SYST_C,
		EXPY_D as EXPY_D,
		PROS_KEY_EFFT_I as PROS_KEY_EFFT_I,
		PROS_KEY_EXPY_I as PROS_KEY_EXPY_I,
		EROR_SEQN_I as EROR_SEQN_I,
		RUN_STRM as RUN_STRM,
		DLTA_VERS as DLTA_VERS
	FROM {{ ref('Xfm__Lapa') }}
	UNION ALL
	SELECT
		APPT_PDCT_I,
		AMT_TYPE_C,
		CNCY_C,
		APPT_PDCT_A,
		XCES_AMT_REAS_X,
		EFFT_D,
		SRCE_SYST_C,
		EXPY_D,
		PROS_KEY_EFFT_I,
		PROS_KEY_EXPY_I,
		EROR_SEQN_I,
		RUN_STRM,
		DLTA_VERS
	FROM {{ ref('Xfm__Larq') }}
	UNION ALL
	SELECT
		APPT_PDCT_I,
		AMT_TYPE_C,
		CNCY_C,
		APPT_PDCT_A,
		XCES_AMT_REAS_X,
		EFFT_D,
		SRCE_SYST_C,
		EXPY_D,
		PROS_KEY_EFFT_I,
		PROS_KEY_EXPY_I,
		EROR_SEQN_I,
		RUN_STRM,
		DLTA_VERS
	FROM {{ ref('Xfm__Laap') }}
	UNION ALL
	SELECT
		APPT_PDCT_I,
		AMT_TYPE_C,
		CNCY_C,
		APPT_PDCT_A,
		XCES_AMT_REAS_X,
		EFFT_D,
		SRCE_SYST_C,
		EXPY_D,
		PROS_KEY_EFFT_I,
		PROS_KEY_EXPY_I,
		EROR_SEQN_I,
		RUN_STRM,
		DLTA_VERS
	FROM {{ ref('Xfm__Laex') }}
)

SELECT * FROM FunnelXfm