# BTEQ to DBT Converter Configuration
# This file defines model categories and their directory mappings

# Model Categories Configuration
# Define the categories that will be created in the intermediate models directory
model_categories:
  - account_balance
  - derived_account_party
  - portfolio_technical
  - process_control

# Category Mapping Configuration  
# Maps BTEQ file categories to their target directory structure
category_mapping:
  account_balance: account_balance
  derived_account_party: derived_account_party
  portfolio_technical: portfolio_technical
  process_control: process_control
  data_loading: intermediate
  misc: intermediate
  configuration: null  # null means skip these files

# BTEQ File Pattern Matching
# Patterns used to categorize BTEQ files based on filename and content
# NOTE: Patterns are case-insensitive (filenames are converted to uppercase)
categorization_patterns:
  account_balance:
    - "ACCT_BALN_BKDT"
  derived_account_party:
    - "DERV_ACCT_PATY"
  portfolio_technical:
    - "PRTF_TECH"
  process_control:
    - "SP_"
    - "_SP_"
  data_loading:
    - "BTEQ_"
  configuration:
    - "LOGIN"
    - ".SNOWCT"
    - "STORAGE"

# Directory Structure
# Additional directories to create in the DBT project
# Note: models/marts/{category} directories are automatically created for each model_categories entry
additional_directories:
  - analyses
  - seeds
  - tests
  - snapshots
  - docs 