{{ config(materialized='view', tags=['DltAPPT_PDCT_COND']) }}

WITH 
tmp_appt_pdct_cond AS (
	SELECT
	*
	FROM {{ ref("tmp_appt_pdct_cond")  }}),
appt_pdct_cond AS (
	SELECT
	*
	FROM {{ ref("appt_pdct_cond")  }}),
Src_Tera_APPT_PDCT_COND AS (SELECT a.APPT_PDCT_I AS NEW_APPT_PDCT_I, a.COND_C AS NEW_COND_C, a.APPT_PDCT_COND_MEET_D AS NEW_APPT_PDCT_COND_MEET_D, b.APPT_PDCT_I AS OLD_APPT_PDCT_I, b.COND_C AS OLD_COND_C, b.APPT_PDCT_COND_MEET_D AS OLD_APPT_PDCT_COND_MEET_D FROM TMP_APPT_PDCT_COND FULL OUTER JOIN APPT_PDCT_COND ON TRIM(a.APPT_PDCT_I) = TRIM(b.APPT_PDCT_I) AND TRIM(a.COND_C) = TRIM(b.COND_C) AND b.EXPY_D = '9999-12-31' WHERE (B.EXPY_D = '9999-12-31' OR B.EXPY_D IS NULL))


SELECT * FROM Src_Tera_APPT_PDCT_COND