{{ config(materialized='view', tags=['XfmHL_APPFrmExt']) }}

WITH DeDup_ApptDept AS (
	SELECT APPT_I, DEPT_ROLE_C, EFFT_D, DEPT_I, EXPY_D, PROS_KEY_EFFT_I, PROS_KEY_EXPY_I, EROR_SEQN_I, RUN_STRM 
	FROM (
		SELECT APPT_I, DEPT_ROLE_C, EFFT_D, DEPT_I, EXPY_D, PROS_KEY_EFFT_I, PROS_KEY_EXPY_I, EROR_SEQN_I, RUN_STRM,
		 ROW_NUMBER() OVER (PARTITION BY APPT_I ORDER BY 1 ASC) AS ROW_NUM 
		FROM {{ ref('XfmBusinessRules__OutTmpApptDeptDS') }}
	) AS DeDup_ApptDept_TEMP
	WHERE ROW_NUM = 1
)

SELECT * FROM DeDup_ApptDept