{{ config(materialized='view', tags=['ExtChlBusFeeBusFeeDisc']) }}

WITH 
rejt_chl_bus_fee_disc_fee AS (
	SELECT
	*
	FROM {{ source("cse4_stg","rejt_chl_bus_fee_disc_fee")  }}),
SrcRejectOra AS (SELECT HL_FEE_ID, BF_HL_FEE_ID, BF_HL_APP_PROD_ID, BF_XML_CODE, BF_DISPLAY_NAME, BF_CATEGORY, BF_UNIT_AMOUNT, BF_TOTAL_AMOUNT, BFD_HL_FEE_DISCOUNT_ID, BFD_HL_FEE_ID, BFD_DISCOUNT_REASON, BFD_DISCOUNT_CODE, BFD_DISCOUNT_AMT, BFD_DISCOUNT_TERM, BFD_HL_FEE_DISCOUNT_CAT_ID, BF_FOUND_FLAG, BFD_FOUND_FLAG, CAST(ORIG_ETL_D AS TEXT) AS ORIG_ETL_D FROM REJT_CHL_BUS_FEE_DISC_FEE WHERE EROR_C LIKE 'RPR%')


SELECT * FROM SrcRejectOra