{{ config(materialized='view', tags=['XfmAppt_Pdct_AcctFrmTmp']) }}

WITH Funnel_Acct_I AS (
	SELECT
		APPT_PDCT_I as APPT_PDCT_I,
		REPAYMENT_ACCOUNT_NUMBER as ACCT_I,
		ACCOUNT_NUMBER as REL_TYPE_C,
		ACCT_I as EFFT_D,
		REL_TYPE_C as PROS_KEY_EFFT_I,
		EFFT_D as PROS_KEY_EXPY_I,
		PROS_KEY_EFFT_I as EXPY_D,
		PROS_KEY_EXPY_I as EROR_SEQN_I,
		EXPY_D as ERR_FLG,
		EROR_SEQN_I as keyChange,
		ERR_FLG as ACCOUNT_NUMBER,
		keyChange as REPAYMENT_ACCOUNT_NUMBER
	FROM {{ ref('Acct_I_Null_Check__Acct_I_Null') }}
	UNION ALL
	SELECT
		APPT_PDCT_I,
		ACCT_I,
		REL_TYPE_C,
		EFFT_D,
		PROS_KEY_EFFT_I,
		ERR_FLG,
		EXPY_D,
		PROS_KEY_EXPY_I,
		EROR_SEQN_I,
		ACCOUNT_NUMBER,
		REPAYMENT_ACCOUNT_NUMBER,
		keyChange
	FROM {{ ref('Sort') }}
)

SELECT * FROM Funnel_Acct_I