{{ config(materialized='view', tags=['XfmAppt_Pdct_AcctFrmTmp']) }}

WITH 
,
UTIL_ACCT_IDNN_EROR AS (SELECT EROR_ACCT_NUMB AS ACCOUNT_NUMBER, 1 AS REPAYMENT_ACCOUNT_NUMBER, LOAD_S, RJCT_RECD, ACCT_I FROM UTIL_ACCT_IDNN_EROR INNER JOIN (SELECT srce_syst_acct_numb, TRIM(acct_i) AS acct_i FROM locn_serv_curr) AS b ON TRIM(a.EROR_ACCT_NUMB) = TRIM(b.srce_syst_acct_numb) WHERE CONV_M = 'CSEPO001' AND EXPY_DATE = '9999-12-31' AND EROR_TABL_NAME = 'APPT_PDCT_ACCT' UNION ALL SELECT EROR_ACCT_NUMB AS REPAYMENT_ACCOUNT_NUMBER, 1 AS ACCOUNT_NUMBER, LOAD_S, RJCT_RECD, ACCT_I FROM UTIL_ACCT_IDNN_EROR INNER JOIN (SELECT srce_syst_acct_numb, TRIM(acct_i) AS acct_i FROM locn_serv_curr) AS b ON TRIM(a.EROR_ACCT_NUMB) = TRIM(b.srce_syst_acct_numb) WHERE CONV_M = 'CSEPO002' AND EXPY_DATE = '9999-12-31' AND EROR_TABL_NAME = 'APPT_PDCT_ACCT')


SELECT * FROM UTIL_ACCT_IDNN_EROR