{{ config(materialized='view', tags=['XfmPlFeePlMarginFrmExt']) }}

WITH ModNullHandling AS (
	SELECT 
	--Manual
	--FEAT_I: string[max=255]= handle_null (TARG_CHAR_C, '999010')
	--FEAT_OVRD_REAS_C:nullable string[4] = handle_null (FEAT_OVRD_REAS_C, '9999')
	--FEE_CAPL_F:nullable string[1] = handle_null (FEE_CAPL_F, '9')
	--PL_FEE_FEE_SCREEN_DESC = SRCE_CHAR_1_C
	--PL_MARGIN_MARGIN_REASON_CAT_ID = MARG_REAS_CAT_ID
	--PL_FEE_PL_CAPITALIS_FEE_CAT_ID = PL_CAPL_FEE_CAT_ID
	PL_FEE_ID, PL_APP_PROD_ID, PL_FEE_PL_FEE_ID, PL_FEE_ADD_TO_TOTAL_FLAG, PL_FEE_FEE_AMT, PL_FEE_BASE_FEE_AMT, PL_FEE_PAY_FEE_AT_FUNDING_FLAG, PL_FEE_START_DATE, PL_CAPL_FEE_CAT_ID AS PL_FEE_PL_CAPITALIS_FEE_CAT_ID, SRCE_CHAR_1_C AS PL_FEE_FEE_SCREEN_DESC, PL_FEE_FEE_DESC, PL_FEE_CASS_FEE_CODE, PL_FEE_CASS_FEE_KEY, PL_FEE_TOTAL_FEE_AMT, PL_FEE_PL_APP_PROD_ID, PL_MARGIN_PL_MARGIN_ID, PL_MARGIN_MARGIN_AMT, PL_MARGIN_PL_FEE_ID, PL_MARGIN_PL_INT_RATE_ID, MARG_REAS_CAT_ID AS PL_MARGIN_MARGIN_REASON_CAT_ID, PL_MARGIN_PL_APP_PROD_ID, PL_FEE_FOUND_FLAG, PL_MARGIN_FOUND_FLAG, ORIG_ETL_D, TARG_CHAR_C AS FEAT_I, FEAT_OVRD_REAS_C, FEE_CAPL_F 
	FROM {{ ref('LkpReferences') }}
)

SELECT * FROM ModNullHandling