{{ config(materialized='view', tags=['ExtWRK_APPT_PDCT_FEAT_RTPERCMARGFrmStg']) }}

WITH 
wrk_appt_pdct_feat_rt_prc_mrg AS (
	SELECT
	*
	FROM {{ source("tdcsdstg","wrk_appt_pdct_feat_rt_prc_mrg")  }}),
SrcWrkApptPdctFeatTera AS (SELECT APPT_PDCT_I, FEAT_I, SRCE_SYST_APPT_FEAT_I, EFFT_D, SRCE_SYST_C, SRCE_SYST_APPT_OVRD_I, OVRD_FEAT_I, SRCE_SYST_STND_VALU_Q, SRCE_SYST_STND_VALU_R, SRCE_SYST_STND_VALU_A, CNCY_C, ACTL_VALU_Q, ACTL_VALU_R, ACTL_VALU_A, FEAT_SEQN_N, FEAT_STRT_D, FEE_CHRG_D, OVRD_REAS_C, FEE_ADD_TO_TOTL_F, FEE_CAPL_F, EXPY_D, PROS_KEY_EFFT_I, PROS_KEY_EXPY_I, EROR_SEQN_I, RUN_STRM, HL_INT_RATE_ID, RATE_HL_INT_RATE_ID, RATE_HL_APP_PROD_ID, RATE_CASS_INT_RATE_TYPE_CODE, RATE_RATE_SEQUENCE, RATE_DURATION, PERC_HL_INT_RATE_ID, PERC_SCHEDULE_RATE_TYPE, PERC_RATE_PERCENT_1, PERC_RATE_PERCENT_2, MARG_HL_PROD_INT_MARGIN_ID, MARG_HL_INT_RATE_ID, MARG_HL_PROD_INT_MARGIN_CAT_ID, MARG_MARGIN_TYPE, MARG_MARGIN_DESC, MARG_MARGIN_CODE, MARG_MARGIN_AMOUNT, MARG_ADJ_AMT, RATE_FOUND_FLAG, PERC_FOUND_FLAG, MARG_FOUND_FLAG, ORIG_ETL_D, CASE WHEN ((RATE_FOUND_FLAG = 'N' OR PERC_FOUND_FLAG = 'N') AND FEAT_I = '{{ var("DEFAULT_NULL_VALUE") }}') THEN 'Y' ELSE 'N' END AS REJECT_FLAG FROM WRK_APPT_PDCT_FEAT_RT_PRC_MRG)


SELECT * FROM SrcWrkApptPdctFeatTera