{{ config(materialized='view', tags=['ExtHL_APP']) }}

WITH FunMergeJournal AS (
	SELECT
		HL_APP_ID as HL_APP_ID,
		HL_APP_PROD_ID as HL_APP_PROD_ID,
		HL_PACKAGE_CAT_ID as HL_PACKAGE_CAT_ID,
		LPC_OFFICE as LPC_OFFICE,
		STATUS_TRACKER_ID as STATUS_TRACKER_ID,
		CHL_APP_PCD_EXTERNAL_SYS_CAT_ID as CHL_APP_PCD_EXT_SYS_CAT_ID,
		CHL_APP_SIMPLE_APP_FLAG as CHL_APP_SIMPLE_APP_FLAG,
		CHL_APP_ORIGINATING_AGENT_ID as CHL_APP_ORIGINATING_AGENT_ID,
		CHL_APP_AGENT_NAME as CHL_APP_AGENT_NAME,
		CASS_WITHHOLD_RISKBANK_FLAG as CASS_WITHHOLD_RISKBANK_FLAG,
		CR_DATE as CR_DATE,
		ASSESSMENT_DATE as ASSESSMENT_DATE,
		NCPR_FLAG as NCPR_FLAG,
		CAMPAIGN_CODE as CAMPAIGN_CODE,
		FHB_FLAG as FHB_FLAG,
		SETTLEMENT_DATE as SETTLEMENT_DATE,
		PEXA_FLAG as PEXA_FLAG,
		HSCA_FLAG as HSCA_FLAG,
		HSCA_CONVERTED_TO_FULL_AT as HSCA_CONVERTED_TO_FULL_AT,
		ORIG_ETL_D as ORIG_ETL_D
	FROM {{ ref('XfmSeparateRejectWithoutSourceAndTheRest__InSourceRec') }}
	UNION ALL
	SELECT
		HL_APP_ID,
		HL_APP_PROD_ID,
		HL_PACKAGE_CAT_ID,
		LPC_OFFICE,
		STATUS_TRACKER_ID,
		CHL_APP_PCD_EXTERNAL_SYS_CAT_ID,
		CHL_APP_SIMPLE_APP_FLAG,
		CHL_APP_ORIGINATING_AGENT_ID,
		CHL_APP_AGENT_NAME,
		CASS_WITHHOLD_RISKBANK_FLAG,
		CR_DATE,
		ASSESSMENT_DATE,
		NCPR_FLAG,
		CAMPAIGN_CODE,
		FHB_FLAG,
		SETTLEMENT_DATE,
		PEXA_FLAG,
		HSCA_FLAG,
		HSCA_CONVERTED_TO_FULL_AT,
		ORIG_ETL_D
	FROM {{ ref('XfmSeparateRejectWithoutSourceAndTheRest__InRejectWithoutSourceRec') }}
)

SELECT * FROM FunMergeJournal