{{ config(materialized='view', tags=['DltAPPT_STUSFrmTMP_APPT_STUS']) }}

WITH 
appt_stus AS (
	SELECT
	*
	FROM {{ ref("appt_stus")  }}),
tmp_appt_stus AS (
	SELECT
	*
	FROM {{ ref("tmp_appt_stus")  }}),
SrcTmpApptStusTera AS (SELECT a.APPT_I AS NEW_APPT_I, a.STUS_C AS NEW_STUS_C, a.STRT_S AS NEW_STRT_S, a.STRT_D AS NEW_STRT_D, CAST(a.STRT_T AS VARCHAR(8)) || '.000000' AS NEW_STRT_T, a.END_D AS NEW_END_D, CAST(a.END_T AS VARCHAR(8)) || '.000000' AS NEW_END_T, a.END_S AS NEW_END_S, a.EMPL_I AS NEW_EMPL_I, b.APPT_I AS OLD_APPT_I, b.STUS_C AS OLD_STUS_C, b.STRT_S AS OLD_STRT_S, b.END_D AS OLD_END_D, CAST(b.END_T AS VARCHAR(15)) || '.000000' AS OLD_END_T, b.END_S AS OLD_END_S, b.EFFT_D AS OLD_EFFT_D FROM TMP_APPT_STUS LEFT OUTER JOIN APPT_STUS ON TRIM(a.APPT_I) = TRIM(b.APPT_I) AND TRIM(a.STUS_C) = TRIM(b.STUS_C) AND a.STRT_S = b.STRT_S AND b.EXPY_D = '9999-12-31' WHERE a.RUN_STRM = '{{ var("RUN_STREAM") }}')


SELECT * FROM SrcTmpApptStusTera