{{ config(materialized='view', tags=['ExtCclBusPreprovLog']) }}

WITH Trm__Dummy_U_DS AS (
	SELECT
		-- *SRC*: \(20)If IsNull(OutCclAppPremapDS.PREAPPROVAL_SOURCE_CIF_CODE) Then 'Y' Else  if trim(OutCclAppPremapDS.PREAPPROVAL_SOURCE_CIF_CODE = '') Then 'Y' Else 'N',
		IFF({{ ref('CpyCclAppSeq') }}.PREAPPROVAL_SOURCE_CIF_CODE IS NULL, 'Y', IFF(TRIM({{ ref('CpyCclAppSeq') }}.PREAPPROVAL_SOURCE_CIF_CODE = ''), 'Y', 'N')) AS svIsNullSourceCifCode,
		-- *SRC*: \(20)If IsNull(OutCclAppPremapDS.SEC_PREAPPR_CRG_MULTIPLIER) THEN 'Y' ELse  if trim(OutCclAppPremapDS.SEC_PREAPPR_CRG_MULTIPLIER) = '' Then 'Y' Else 'N',
		IFF({{ ref('CpyCclAppSeq') }}.SEC_PREAPPR_CRG_MULTIPLIER IS NULL, 'Y', IFF(TRIM({{ ref('CpyCclAppSeq') }}.SEC_PREAPPR_CRG_MULTIPLIER) = '', 'Y', 'N')) AS svIsNullSecPreapprCrgMul,
		-- *SRC*: \(20)If IsNull(OutCclAppPremapDS.SEC_FORM_MULTIPLER) THEN 'Y' Else  if Trim(OutCclAppPremapDS.SEC_FORM_MULTIPLER) = '' Then 'Y' Else 'N',
		IFF({{ ref('CpyCclAppSeq') }}.SEC_FORM_MULTIPLER IS NULL, 'Y', IFF(TRIM({{ ref('CpyCclAppSeq') }}.SEC_FORM_MULTIPLER) = '', 'Y', 'N')) AS svIsNullSecFormMul,
		-- *SRC*: \(20)If IsNull(OutCclAppPremapDS.SECURED_CAP_MAX_ACCF_THRESHOLD) THEN 'Y' Else  if trim(OutCclAppPremapDS.SECURED_CAP_MAX_ACCF_THRESHOLD) = '' Then 'Y' Else 'N',
		IFF({{ ref('CpyCclAppSeq') }}.SECURED_CAP_MAX_ACCF_THRESHOLD IS NULL, 'Y', IFF(TRIM({{ ref('CpyCclAppSeq') }}.SECURED_CAP_MAX_ACCF_THRESHOLD) = '', 'Y', 'N')) AS svIsNullSecuredMaxTshd,
		-- *SRC*: \(20)If IsNull(OutCclAppPremapDS.EF_CAP_MAX_THRESHOLD) THEN 'Y' Else  if trim(OutCclAppPremapDS.EF_CAP_MAX_THRESHOLD) = '' Then 'Y' Else 'N',
		IFF({{ ref('CpyCclAppSeq') }}.EF_CAP_MAX_THRESHOLD IS NULL, 'Y', IFF(TRIM({{ ref('CpyCclAppSeq') }}.EF_CAP_MAX_THRESHOLD) = '', 'Y', 'N')) AS svIsNullEfMaxThsd,
		-- *SRC*: \(20)If IsNull(OutCclAppPremapDS.TOTAL_PREAPPR_BUFFER_RATE_PCT) Then 'Y' Else  if trim(OutCclAppPremapDS.TOTAL_PREAPPR_BUFFER_RATE_PCT = '') Then 'Y' Else 'N',
		IFF({{ ref('CpyCclAppSeq') }}.TOTAL_PREAPPR_BUFFER_RATE_PCT IS NULL, 'Y', IFF(TRIM({{ ref('CpyCclAppSeq') }}.TOTAL_PREAPPR_BUFFER_RATE_PCT = ''), 'Y', 'N')) AS svIsNullTotalBufferRate,
		-- *SRC*: \(20)If IsNull(OutCclAppPremapDS.EF_PREAPPR_BUFFER_RATE_PCT) Then 'Y' Else  if trim(OutCclAppPremapDS.EF_PREAPPR_BUFFER_RATE_PCT = '') Then 'Y' Else 'N',
		IFF({{ ref('CpyCclAppSeq') }}.EF_PREAPPR_BUFFER_RATE_PCT IS NULL, 'Y', IFF(TRIM({{ ref('CpyCclAppSeq') }}.EF_PREAPPR_BUFFER_RATE_PCT = ''), 'Y', 'N')) AS svIsNullEfBufferRate,
		-- *SRC*: \(20)If IsNull(OutCclAppPremapDS.TOTAL_PREAPPROVAL_AMT) Then 'Y' Else  if trim(OutCclAppPremapDS.TOTAL_PREAPPROVAL_AMT = '') Then 'Y' Else 'N',
		IFF({{ ref('CpyCclAppSeq') }}.TOTAL_PREAPPROVAL_AMT IS NULL, 'Y', IFF(TRIM({{ ref('CpyCclAppSeq') }}.TOTAL_PREAPPROVAL_AMT = ''), 'Y', 'N')) AS svIsNullTotPreApprovalAmt,
		-- *SRC*: \(20)If IsNull(OutCclAppPremapDS.EF_PREAPPROVAL_AMT) Then 'Y' ELse  if trim(OutCclAppPremapDS.EF_PREAPPROVAL_AMT = '') Then 'Y' Else 'N',
		IFF({{ ref('CpyCclAppSeq') }}.EF_PREAPPROVAL_AMT IS NULL, 'Y', IFF(TRIM({{ ref('CpyCclAppSeq') }}.EF_PREAPPROVAL_AMT = ''), 'Y', 'N')) AS svIsNullEfPreApprovalAmt,
		-- *SRC*: \(20)If IsNull(OutCclAppPremapDS.SEC_APP_MULTIPLIER) Then 'Y' Else  if trim(OutCclAppPremapDS.SEC_APP_MULTIPLIER = '') Then 'Y' Else 'N',
		IFF({{ ref('CpyCclAppSeq') }}.SEC_APP_MULTIPLIER IS NULL, 'Y', IFF(TRIM({{ ref('CpyCclAppSeq') }}.SEC_APP_MULTIPLIER = ''), 'Y', 'N')) AS svIsNullSecAppMult,
		-- *SRC*: \(20)If IsNull(OutCclAppPremapDS.SEC_MAA) Then 'Y' Else  if trim(OutCclAppPremapDS.SEC_MAA = '') Then 'Y' Else 'N',
		IFF({{ ref('CpyCclAppSeq') }}.SEC_MAA IS NULL, 'Y', IFF(TRIM({{ ref('CpyCclAppSeq') }}.SEC_MAA = ''), 'Y', 'N')) AS svIsNullSecMaa,
		-- *SRC*: \(20)If IsNull(OutCclAppPremapDS.EF_MAA) Then 'Y' Else  if trim(OutCclAppPremapDS.EF_MAA = '') Then 'Y' Else 'N',
		IFF({{ ref('CpyCclAppSeq') }}.EF_MAA IS NULL, 'Y', IFF(TRIM({{ ref('CpyCclAppSeq') }}.EF_MAA = ''), 'Y', 'N')) AS svIsNullEfMaa,
		-- *SRC*: \(20)If IsNull(OutCclAppPremapDS.SEC_PREAPPR_HIGHCAP_THRESHOLD) Then 'Y' Else  if trim(OutCclAppPremapDS.SEC_PREAPPR_HIGHCAP_THRESHOLD = '') Then 'Y' Else 'N',
		IFF({{ ref('CpyCclAppSeq') }}.SEC_PREAPPR_HIGHCAP_THRESHOLD IS NULL, 'Y', IFF(TRIM({{ ref('CpyCclAppSeq') }}.SEC_PREAPPR_HIGHCAP_THRESHOLD = ''), 'Y', 'N')) AS svIsNullSecHighcapTshd,
		-- *SRC*: \(20)If IsNull(OutCclAppPremapDS.EF_PREAPPR_HIGHCAP_THRESHOLD) Then 'Y' Else  if trim(OutCclAppPremapDS.EF_PREAPPR_HIGHCAP_THRESHOLD = '') Then 'Y' Else 'N',
		IFF({{ ref('CpyCclAppSeq') }}.EF_PREAPPR_HIGHCAP_THRESHOLD IS NULL, 'Y', IFF(TRIM({{ ref('CpyCclAppSeq') }}.EF_PREAPPR_HIGHCAP_THRESHOLD = ''), 'Y', 'N')) AS svIsNullEfHighcapTshd,
		-- *SRC*: \(20)If IsNull(OutCclAppPremapDS.EF_APP_MULTIPLIER) Then 'Y' Else  if trim(OutCclAppPremapDS.EF_APP_MULTIPLIER = '') Then 'Y' Else 'N',
		IFF({{ ref('CpyCclAppSeq') }}.EF_APP_MULTIPLIER IS NULL, 'Y', IFF(TRIM({{ ref('CpyCclAppSeq') }}.EF_APP_MULTIPLIER = ''), 'Y', 'N')) AS svIsNullEfAppMult,
		-- *SRC*: \(20)If IsNull(OutCclAppPremapDS.EF_FORM_MULTIPLIER) Then 'Y' Else  if trim(OutCclAppPremapDS.EF_FORM_MULTIPLIER = '') Then 'Y' Else 'N',
		IFF({{ ref('CpyCclAppSeq') }}.EF_FORM_MULTIPLIER IS NULL, 'Y', IFF(TRIM({{ ref('CpyCclAppSeq') }}.EF_FORM_MULTIPLIER = ''), 'Y', 'N')) AS svIsNullEfFormMult,
		-- *SRC*: \(20)If IsNull(OutCclAppPremapDS.EF_CRG_MULTIPLIER) Then 'Y' Else  if trim(OutCclAppPremapDS.EF_CRG_MULTIPLIER = '') Then 'Y' Else 'N',
		IFF({{ ref('CpyCclAppSeq') }}.EF_CRG_MULTIPLIER IS NULL, 'Y', IFF(TRIM({{ ref('CpyCclAppSeq') }}.EF_CRG_MULTIPLIER = ''), 'Y', 'N')) AS svIsNullEfCrgMult,
		-- *SRC*: \(20)If IsNull(OutCclAppPremapDS.MOD_USER_ID) Then 'Y' Else  if trim(OutCclAppPremapDS.MOD_USER_ID = '') Then 'Y' Else 'N',
		IFF({{ ref('CpyCclAppSeq') }}.MOD_USER_ID IS NULL, 'Y', IFF(TRIM({{ ref('CpyCclAppSeq') }}.MOD_USER_ID = ''), 'Y', 'N')) AS svIsNullModUserId,
		-- *SRC*: 'CSECL' : OutCclAppPremapDS.PREAPPROVAL_CCL_APP_ID,
		CONCAT('CSECL', {{ ref('CpyCclAppSeq') }}.PREAPPROVAL_CCL_APP_ID) AS APPT_I,
		-- *SRC*: 'CSECL' : OutCclAppPremapDS.CCL_PREAPPROVAL_LOG_ID,
		CONCAT('CSECL', {{ ref('CpyCclAppSeq') }}.CCL_PREAPPROVAL_LOG_ID) AS APPT_PRE_APPR_PARM_I,
		{{ ref('CpyCclAppSeq') }}.CCL_PREAPPROVAL_LOG_ID AS SRCE_SYST_PRE_APPR_PARM_I,
		{{ ref('CpyCclAppSeq') }}.OVERDRAFT_INDEX_RATE_PCT AS OVDR_INDX_R,
		{{ ref('CpyCclAppSeq') }}.BUFFER_RATE_PCT AS BUFR_R,
		{{ ref('CpyCclAppSeq') }}.UNSECURED_CAP_MIN_THRESHOLD AS UNSC_CAPL_MIN_TSHD_A,
		{{ ref('CpyCclAppSeq') }}.UNSECURED_CAP_MAX_THRESHOLD AS UNSC_CAPL_MAX_TSHD_A,
		{{ ref('CpyCclAppSeq') }}.WORST_RISK_CRG AS WRST_RISK_CRGD_C,
		{{ ref('CpyCclAppSeq') }}.CRG_MULTIPLIER AS CRGD_MULT_R,
		{{ ref('CpyCclAppSeq') }}.FORM_MULTIPLIER AS FORM_MULT_R,
		{{ ref('CpyCclAppSeq') }}.APP_MULTIPLIER AS APPT_MULT_R,
		{{ ref('CpyCclAppSeq') }}.CRG_MAA AS CRGD_MIN_APLC_A,
		{{ ref('CpyCclAppSeq') }}.CRG_HIGH_CAP_THRESHOLD_AMT AS CRGD_HIGH_CAPL_TSHD_A,
		{{ ref('CpyCclAppSeq') }}.PREAPPROVAL_AMT AS PRE_APPR_A,
		-- *SRC*: StringToDate(ETL_PROCESS_DT, '%yyyy%mm%dd'),
		STRINGTODATE(ETL_PROCESS_DT, '%yyyy%mm%dd') AS EFFT_D,
		0 AS PROS_KEY_EFFT_I,
		-- *SRC*: setnull(),
		SETNULL() AS EROR_SEQN_I
	FROM {{ ref('CpyCclAppSeq') }}
	WHERE 1 = 2
)

SELECT * FROM Trm__Dummy_U_DS