CREATE OR REPLACE PROCEDURE PS_GDW1_BTEQ.BTEQ_SPS.ACCT_BALN_BKDT_UTIL_PROS_UPDT_PROC()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
  -- Procedure: ACCT_BALN_BKDT_UTIL_PROS_UPDT_PROC
  -- Purpose: Update UTIL_PROS_ISAC with status and record counts
  -- Original Author: Suresh Vajapeyajula (vajapes)
  -- Original Date: 2011-10-05
  
  ERROR_CODE INTEGER DEFAULT 0;
  ROW_COUNT INTEGER DEFAULT 0;
  INS_COUNT INTEGER DEFAULT 0;
  DEL_COUNT INTEGER DEFAULT 0;
BEGIN
  -- Get record counts from staging tables
  SELECT COUNT(*) INTO :INS_COUNT FROM PS_CLD_RW.PDDSTG.ACCT_BALN_BKDT_STG2;
  SELECT COUNT(*) INTO :DEL_COUNT FROM PS_CLD_RW.PDDSTG.ACCT_BALN_BKDT_STG1;
  
  -- Update UTIL_PROS_ISAC with completion status and record counts
  UPDATE PS_CLD_RW.STARCADPRODDATA.UTIL_PROS_ISAC
  SET  
    COMT_F = 'Y',
    SUCC_F = 'Y',
    COMT_S = CURRENT_TIMESTAMP(),
    SYST_INS_Q = :INS_COUNT,
    SYST_DEL_Q = :DEL_COUNT
  WHERE 
    CONV_M = 'CAD_X01_ACCT_BALN_BKDT'
    AND PROS_KEY_I = (
      SELECT MAX(PROS_KEY_I) 
      FROM ps_gdw1_bteq.PVTECH.UTIL_PROS_ISAC 
      WHERE CONV_M = 'CAD_X01_ACCT_BALN_BKDT'
    );
  
  ROW_COUNT := SQLROWCOUNT;
  
  RETURN 'SUCCESS: Updated ' || :ROW_COUNT || ' UTIL_PROS_ISAC records. Insert count: ' || :INS_COUNT || ', Delete count: ' || :DEL_COUNT;
  
EXCEPTION
  WHEN OTHER THEN
    RETURN 'ERROR: ' || SQLERRM || ' (Code: ' || SQLCODE || ')';
END;
$$;