{{ config(materialized='view', tags=['LdREJT_CSE_TU_APP_COND']) }}

SELECT
	SUBTYPE_CODE
	HL_APP_PROD_ID
	TU_APP_CONDITION_ID
	TU_APP_CONDITION_CAT_ID
	CONDITION_MET_DATE
	ETL_D
	ORIG_ETL_D
	EROR_C 
FROM {{ ref('ModConversions') }}