{{ config(materialized='view', tags=['LdMAP_CSE_PDCT_REL_CLLkp']) }}

WITH XfmConversions AS (
	SELECT
		-- *SRC*: trim(InMAP_CSE_PDCT_REL_CLTera.PARN_PDCT_LVL_CAT_ID),
		TRIM({{ ref('SrcMAP_CSE_PDCT_REL_CLTera') }}.PARN_PDCT_LVL_CAT_ID) AS PARENT_PRODUCT_LEVEL_CAT_ID,
		-- *SRC*: trim(InMAP_CSE_PDCT_REL_CLTera.CHLD_PDCT_LVL_CAT_ID),
		TRIM({{ ref('SrcMAP_CSE_PDCT_REL_CLTera') }}.CHLD_PDCT_LVL_CAT_ID) AS CHILD_PRODUCT_LEVEL_CAT_ID,
		{{ ref('SrcMAP_CSE_PDCT_REL_CLTera') }}.REL_TYPE_C AS REL_C
	FROM {{ ref('SrcMAP_CSE_PDCT_REL_CLTera') }}
	WHERE 
)

SELECT * FROM XfmConversions