{{ config(materialized='view', tags=['DltAPPT_PDCT_FNDD_INSSFrmTMP_APPT_PDCT_FNDD_INSS']) }}

WITH 
tmp_appt_pdct_fndd_inss AS (
	SELECT
	*
	FROM {{ ref("tmp_appt_pdct_fndd_inss")  }}),
appt_pdct_fndd_inss AS (
	SELECT
	*
	FROM {{ ref("appt_pdct_fndd_inss")  }}),
SrcTmpApptPdctFnddInssTera AS (SELECT a.APPT_PDCT_I AS NEW_APPT_PDCT_I, a.APPT_PDCT_FNDD_I AS NEW_APPT_PDCT_FNDD_I, a.APPT_PDCT_FNDD_METH_I AS NEW_APPT_PDCT_FNDD_METH_I, a.FNDD_INSS_METH_C AS NEW_FNDD_INSS_METH_C, a.SRCE_SYST_FNDD_I AS NEW_SRCE_SYST_FNDD_I, a.SRCE_SYST_FNDD_METH_I AS NEW_SRCE_SYST_FNDD_METH_I, a.SRCE_SYST_C AS NEW_SRCE_SYST_C, a.FNDD_D AS NEW_FNDD_D, a.FNDD_A AS NEW_FNDD_A, a.PDCT_SYST_ACCT_N AS NEW_PDCT_SYST_ACCT_N, a.CMPE_I AS NEW_CMPE_I, a.CMPE_ACCT_BSB_N AS NEW_CMPE_ACCT_BSB_N, a.CMPE_ACCT_N AS NEW_CMPE_ACCT_N, b.APPT_PDCT_I AS OLD_APPT_PDCT_I, b.APPT_PDCT_FNDD_I AS OLD_APPT_PDCT_FNDD_I, b.APPT_PDCT_FNDD_METH_I AS OLD_APPT_PDCT_FNDD_METH_I, b.FNDD_INSS_METH_C AS OLD_FNDD_INSS_METH_C, b.SRCE_SYST_FNDD_I AS OLD_SRCE_SYST_FNDD_I, b.SRCE_SYST_FNDD_METH_I AS OLD_SRCE_SYST_FNDD_METH_I, b.SRCE_SYST_C AS OLD_SRCE_SYST_C, b.FNDD_D AS OLD_FNDD_D, b.FNDD_A AS OLD_FNDD_A, b.PDCT_SYST_ACCT_N AS OLD_PDCT_SYST_ACCT_N, b.CMPE_I AS OLD_CMPE_I, b.CMPE_ACCT_BSB_N AS OLD_CMPE_ACCT_BSB_N, b.CMPE_ACCT_N AS OLD_CMPE_ACCT_N, b.EFFT_D AS OLD_EFFT_D FROM TMP_APPT_PDCT_FNDD_INSS LEFT OUTER JOIN APPT_PDCT_FNDD_INSS ON TRIM(a.APPT_PDCT_FNDD_METH_I) = TRIM(b.APPT_PDCT_FNDD_METH_I) AND b.EXPY_D = '9999-12-31' WHERE a.RUN_STREAM = '{{ var("RUN_STREAM") }}')


SELECT * FROM SrcTmpApptPdctFnddInssTera