name: bteq_test01
version: 1.0.0
config-version: 2
profile: bteq_test01_profile
model-paths:
- models
analysis-paths:
- analyses
test-paths:
- tests
seed-paths:
- seeds
macro-paths:
- macros
snapshot-paths:
- snapshots
target-path: target
clean-targets:
- target
- dbt_packages
vars:
  BTEQ_LOGON_SCRIPT: REPLACE_WITH_BTEQ_LOGON_SCRIPT_VALUE
  CAD_PROD_DATA: REPLACE_WITH_CAD_PROD_DATA_VALUE
  CAD_PROD_MACRO: REPLACE_WITH_CAD_PROD_MACRO_VALUE
  DDSTG: REPLACE_WITH_DDSTG_VALUE
  DGRDDB: REPLACE_WITH_DGRDDB_VALUE
  ENV_C: REPLACE_WITH_ENV_C_VALUE
  GDW_HOST: REPLACE_WITH_GDW_HOST_VALUE
  GDW_PASS: REPLACE_WITH_GDW_PASS_VALUE
  GDW_USER: REPLACE_WITH_GDW_USER_VALUE
  INDATE: REPLACE_WITH_INDATE_VALUE
  PSST_TABLE_M: REPLACE_WITH_PSST_TABLE_M_VALUE
  RSTR_F: REPLACE_WITH_RSTR_F_VALUE
  SRCE_M: REPLACE_WITH_SRCE_M_VALUE
  SRCE_SYST_M: REPLACE_WITH_SRCE_SYST_M_VALUE
  STARDATADB: REPLACE_WITH_STARDATADB_VALUE
  STARMACRDB: REPLACE_WITH_STARMACRDB_VALUE
  STRM_C: REPLACE_WITH_STRM_C_VALUE
  TBSHORT: REPLACE_WITH_TBSHORT_VALUE
  UCB: REPLACE_WITH_UCB_VALUE
  UTILSTG: REPLACE_WITH_UTILSTG_VALUE
  VCBODS: REPLACE_WITH_VCBODS_VALUE
  VEXTR: REPLACE_WITH_VEXTR_VALUE
  VPATY: REPLACE_WITH_VPATY_VALUE
  VTECH: REPLACE_WITH_VTECH_VALUE
models:
  bteq_test01:
    staging:
      +materialized: view
      +docs:
        show: true
    intermediate:
      +materialized: table
      +docs:
        show: true
      +pre_hook: '{{ register_process_instance(this.name) }}'
      +post_hook: '{{ update_process_status(''SUCCESS'') }}'
    marts:
      +materialized: table
      +docs:
        show: true
