{{ config(materialized='view', tags=['XfmChlBusTuAPPFrmExt']) }}

WITH CpyRename AS (
	SELECT
		{{ ref('SrcTuApptremapDS') }}.SUBTYPE_CODE AS SBTY_CODE,
		HL_APP_PROD_ID,
		TU_APP_ID,
		TU_ACCOUNT_ID,
		TU_DOCCOLLECT_METHOD_CAT_ID,
		{{ ref('SrcTuApptremapDS') }}.DOCCOLLECT_ADDRESS_TYPE_ID AS ADRS_TYPE_ID,
		DOCCOLLECT_BSB,
		TU_DOCCOLLECT_ADDRESS_LINE_1,
		TU_DOCCOLLECT_ADDRESS_LINE_2,
		TU_DOCCOLLECT_SUBURB,
		{{ ref('SrcTuApptremapDS') }}.TU_DOCCOLLECT_STATE_ID AS STAT_C,
		TU_DOCCOLLECT_POSTCODE,
		{{ ref('SrcTuApptremapDS') }}.TU_DOCCOLLECT_COUNTRY_ID AS CNTY_ID,
		TU_DOCCOLLECT_OVERSEA_STATE,
		TOPUP_AMOUNT,
		TOPUP_AGENT_ID,
		TOPUP_AGENT_NAME,
		ACCOUNT_NO,
		{{ ref('SrcTuApptremapDS') }}.CRIS_PRODUCT_ID AS CRIS_PDCT_C,
		CAMPAIGN_CODE,
		ORIG_ETL_D
	FROM {{ ref('SrcTuApptremapDS') }}
)

SELECT * FROM CpyRename