{{ config(materialized='view', tags=['XfmChlBusTuAPPFrmExt']) }}

WITH OutRejApptQfy__OutRej1 AS (
	SELECT
		{{ ref('LkpReferences') }}.SBTY_CODE AS SUBTYPE_CODE,
		HL_APP_PROD_ID,
		TU_APP_ID,
		TU_ACCOUNT_ID,
		TU_DOCCOLLECT_METHOD_CAT_ID,
		{{ ref('LkpReferences') }}.ADRS_TYPE_ID AS DOCCOLLECT_ADDRESS_TYPE_ID,
		DOCCOLLECT_BSB,
		TU_DOCCOLLECT_ADDRESS_LINE_1,
		TU_DOCCOLLECT_ADDRESS_LINE_2,
		TU_DOCCOLLECT_SUBURB,
		{{ ref('LkpReferences') }}.STAT_C AS TU_DOCCOLLECT_STATE_ID,
		TU_DOCCOLLECT_POSTCODE,
		{{ ref('LkpReferences') }}.CNTY_ID AS TU_DOCCOLLECT_COUNTRY_ID,
		TU_DOCCOLLECT_OVERSEA_STATE,
		TOPUP_AMOUNT,
		TOPUP_AGENT_ID,
		TOPUP_AGENT_NAME,
		ACCOUNT_NO,
		{{ ref('LkpReferences') }}.CRIS_PDCT_C AS CRIS_PRODUCT_ID,
		ORIG_ETL_D,
		ETL_PROCESS_DT AS ETL_D,
		'RPR7001' AS EROR_C
	FROM {{ ref('LkpReferences') }}
	WHERE 
)

SELECT * FROM OutRejApptQfy__OutRej1