
--
/* <sc-table> STAR_CAD_PROD_DATA.ACCT_BALN_ADJ </sc-table> */
CREATE SET TABLE STAR_CAD_PROD_DATA.ACCT_BALN_ADJ ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      ACCT_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Account Identifier' NOT NULL,
      SRCE_SYST_C CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Source System Code' NOT NULL COMPRESS 'SAP',
      BALN_TYPE_C CHAR(5) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Balance Type Code' NOT NULL COMPRESS 'BALN ',
      CALC_FUNC_C CHAR(5) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Calculation Function Code' NOT NULL COMPRESS 'SPOT ',
      TIME_PERD_C CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Time Period Code' NOT NULL COMPRESS 'E',
      ADJ_FROM_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Adjustment From Date' NOT NULL,
      ADJ_TO_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Adjustment To Date',
      ADJ_A DECIMAL(23,5) TITLE 'Adjustment Amount' COMPRESS 0.00000 ,
      GL_RECN_F CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Gl Reconciliation Flag' DEFAULT 'N' COMPRESS ('F','N','T','Y'),
      EFFT_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Effective Date' NOT NULL,
      PROS_KEY_EFFT_I DECIMAL(10,0) TITLE 'Process Key Effective Identifier',
      EROR_SEQN_I DECIMAL(10,0) TITLE 'Error Sequence Identifier' COMPRESS ,
      CNCY_C CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Currency Code' COMPRESS 'AUD',
      CALC_F CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Calculate Flag' DEFAULT 'N' COMPRESS ('N','Y'),
      ROW_SECU_ACCS_C INTEGER TITLE 'Row Security Access Code' DEFAULT 0  COMPRESS 0 )
PRIMARY INDEX XIE1ACCT_BALN_ADJ ( ACCT_I );


 
REPLACE VIEW PVTECH.ACCT_BALN_ADJ
(
ACCT_I,
  SRCE_SYST_C,
  BALN_TYPE_C,
  CALC_FUNC_C,
  TIME_PERD_C,
  ADJ_FROM_D,
  ADJ_TO_D,
  ADJ_A,
  GL_RECN_F,
  EFFT_D,
  PROS_KEY_EFFT_I,
  EROR_SEQN_I,
  CNCY_C,
  CALC_F,
  ROW_SECU_ACCS_C
)
AS LOCKING TABLE STAR_CAD_PROD_DATA.ACCT_BALN_ADJ FOR ACCESS
SELECT
        ACCT_I,
  SRCE_SYST_C,
  BALN_TYPE_C,
  CALC_FUNC_C,
  TIME_PERD_C,
  ADJ_FROM_D,
  ADJ_TO_D,
  CASE WHEN (SRCE_SYST_C = 'SAP' AND (CNCY_C = 'AUD' OR CNCY_C IS NULL)) OR (COALESCE(SRCE_SYST_C,'') <> 'SAP')
              THEN CAST(ADJ_A AS DECIMAL (15,2) )
              END AS ADJ_A,
  GL_RECN_F,
  EFFT_D,
  PROS_KEY_EFFT_I,
  EROR_SEQN_I,
  CNCY_C,
  CALC_F,
  ROW_SECU_ACCS_C
  FROM
        STAR_CAD_PROD_DATA.ACCT_BALN_ADJ
 WHERE (SRCE_SYST_C = 'SAP' AND (CNCY_C = 'AUD' OR CNCY_C is NULL))
  OR (COALESCE(SRCE_SYST_C,'') <> 'SAP')
                                          
 AND ( 
(
/* Start - RLS */
COALESCE(ROW_SECU_ACCS_C,0) = 0 OR
TD_SYSFNLIB.GETBIT( (SELECT ROW_SECU_PRFL_C
FROM PVSECURITY.ROW_LEVL_SECU_USER_PRFL
WHERE USERNAME = USER
),ROW_SECU_ACCS_C
) =1
/* End - RLS */
)
    );
