-- Count check for all migrated tables from 03-Creating Iceberg Tables.sql
-- This query will show the row count for each successfully migrated table

use role r_dev_npd_d12_gdwmig;
use database npd_d12_dmn_gdwmig;
use schema migration_tracking;
use warehouse wh_usr_npd_d12_gdwmig_001;

-- Count all migrated tables
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.PDCBODS.ODS_RULE' as table_name, COUNT(1) as row_count FROM NPD_D12_DMN_GDWMIG_IBRG.PDCBODS.ODS_RULE
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.PDCMS.MAP_CMS_PDCT', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.PDCMS.MAP_CMS_PDCT
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_PATY_DEDUP', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_PATY_DEDUP
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_PATY_REL_THA', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_PATY_REL_THA
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_PATY_REL_WSS', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_PATY_REL_WSS
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_PATY_THA_NEW_RNGE', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_PATY_THA_NEW_RNGE
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_REL_WSS_DITPS', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_REL_WSS_DITPS
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.DERV_ACCT_PATY_ADD', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.DERV_ACCT_PATY_ADD
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.DERV_ACCT_PATY_CHG', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.DERV_ACCT_PATY_CHG
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.DERV_ACCT_PATY_CURR', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.DERV_ACCT_PATY_CURR
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.DERV_ACCT_PATY_DEL', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.DERV_ACCT_PATY_DEL
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.DERV_ACCT_PATY_FLAG', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.DERV_ACCT_PATY_FLAG
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.DERV_ACCT_PATY_NON_RM', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.DERV_ACCT_PATY_NON_RM
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.DERV_ACCT_PATY_RM', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.DERV_ACCT_PATY_RM
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.DERV_ACCT_PATY_ROW_SECU_FIX', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.DERV_ACCT_PATY_ROW_SECU_FIX
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.DERV_PRTF_ACCT_PATY_PSST', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.DERV_PRTF_ACCT_PATY_PSST
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.DERV_PRTF_ACCT_PATY_STAG', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.DERV_PRTF_ACCT_PATY_STAG
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.DERV_PRTF_ACCT_STAG', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.DERV_PRTF_ACCT_STAG
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.DERV_PRTF_PATY_STAG', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.DERV_PRTF_PATY_STAG
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.GRD_GNRC_MAP_BUSN_SEGM_PRTY', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.GRD_GNRC_MAP_BUSN_SEGM_PRTY
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.GRD_GNRC_MAP_DERV_PATY_HOLD', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.GRD_GNRC_MAP_DERV_PATY_HOLD
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.GRD_GNRC_MAP_DERV_PATY_REL', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.GRD_GNRC_MAP_DERV_PATY_REL
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.GRD_GNRC_MAP_DERV_UNID_PATY', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.GRD_GNRC_MAP_DERV_UNID_PATY
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.GRD_GNRC_MAP_PATY_HOLD_PRTY', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.GRD_GNRC_MAP_PATY_HOLD_PRTY
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.PDGRD.DEPT_DIMN_NODE_ANCS_CURR', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.PDGRD.DEPT_DIMN_NODE_ANCS_CURR
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.PDGRD.GRD_DEPT_FLAT_CURR', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.PDGRD.GRD_DEPT_FLAT_CURR
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.PDGRD.GRD_GNRC_MAP', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.PDGRD.GRD_GNRC_MAP
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.PDGRD.NON_WORK_DAY', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.PDGRD.NON_WORK_DAY
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.PDPATY.ACCT_PATY', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.PDPATY.ACCT_PATY
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.PDPATY.PATY_REL', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.PDPATY.PATY_REL
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.PDPATY.UTIL_PROS_ISAC', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.PDPATY.UTIL_PROS_ISAC
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.PDSECURITY.ROW_LEVL_SECU_USER_PRFL', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.PDSECURITY.ROW_LEVL_SECU_USER_PRFL
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.PDSRCCS.PLAN_BALN_SEGM_MSTR', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.PDSRCCS.PLAN_BALN_SEGM_MSTR
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.PDSRCCS.PLAN_BALN_SEGM_MSTR_ARCH', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.PDSRCCS.PLAN_BALN_SEGM_MSTR_ARCH
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.PDSRCCS.UTIL_BTCH_ISAC', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.PDSRCCS.UTIL_BTCH_ISAC
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.PDSRCCS.UTIL_PARM', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.PDSRCCS.UTIL_PARM
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.PDSRCCS.UTIL_PROS_ISAC', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.PDSRCCS.UTIL_PROS_ISAC
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.PDTRPC.WKND_PBLC_HLDY', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.PDTRPC.WKND_PBLC_HLDY
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.PUTIL.PROS_EROR_LOG', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.PUTIL.PROS_EROR_LOG
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.PUTIL.TERASYNC', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.PUTIL.TERASYNC
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.ACCT_APPT_PDCT', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.ACCT_APPT_PDCT
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.ACCT_REL', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.ACCT_REL
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.ACCT_UNID_PATY', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.ACCT_UNID_PATY
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.ACCT_XREF_BPS_CBS', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.ACCT_XREF_BPS_CBS
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.ACCT_XREF_MAS_DAR', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.ACCT_XREF_MAS_DAR
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.APPT', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.APPT
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.APPT_DEPT', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.APPT_DEPT
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.APPT_FEAT', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.APPT_FEAT
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.APPT_PDCT', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.APPT_PDCT
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.APPT_PDCT_ACCT', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.APPT_PDCT_ACCT
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.APPT_PDCT_AMT', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.APPT_PDCT_AMT
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.APPT_PDCT_FEAT', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.APPT_PDCT_FEAT
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.APPT_PDCT_PATY', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.APPT_PDCT_PATY
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.APPT_PDCT_PURP', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.APPT_PDCT_PURP
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.APPT_PDCT_REL', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.APPT_PDCT_REL
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.APPT_PDCT_RPAY', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.APPT_PDCT_RPAY
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.APPT_PDCT_UNID_PATY', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.APPT_PDCT_UNID_PATY
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.APPT_REL', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.APPT_REL
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.APPT_TRNF_DETL', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.APPT_TRNF_DETL
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.BUSN_EVNT', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.BUSN_EVNT
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.CLS_FCLY', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.CLS_FCLY
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.CLS_UNID_PATY', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.CLS_UNID_PATY
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.DAR_ACCT', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.DAR_ACCT
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.DEPT_APPT', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.DEPT_APPT
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.DERV_ACCT_PATY', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.DERV_ACCT_PATY
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.DERV_PRTF_ACCT_REL', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.DERV_PRTF_ACCT_REL
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.DERV_PRTF_OWN_REL', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.DERV_PRTF_OWN_REL
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.DERV_PRTF_PATY_REL', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.DERV_PRTF_PATY_REL
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.EVNT', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.EVNT
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.EVNT_EMPL', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.EVNT_EMPL
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.EVNT_INT_GRUP', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.EVNT_INT_GRUP
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.GDW_EFFT_DATE', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.GDW_EFFT_DATE
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.INT_GRUP', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.INT_GRUP
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.INT_GRUP_DEPT', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.INT_GRUP_DEPT
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.INT_GRUP_EMPL', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.INT_GRUP_EMPL
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.INT_GRUP_UNID_PATY', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.INT_GRUP_UNID_PATY
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_ADRS_TYPE', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_ADRS_TYPE
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_APPT_ACQR_SRCE', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_APPT_ACQR_SRCE
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_APPT_C', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_APPT_C
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_APPT_CMPE', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_APPT_CMPE
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_APPT_CODE_HM', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_APPT_CODE_HM
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_APPT_COND', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_APPT_COND
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_APPT_DOCU_DELY', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_APPT_DOCU_DELY
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_APPT_FEAT', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_APPT_FEAT
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_APPT_FORM', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_APPT_FORM
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_APPT_ORIG', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_APPT_ORIG
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_APPT_PDCT_FEAT', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_APPT_PDCT_FEAT
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_APPT_PDCT_PATY_ROLE', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_APPT_PDCT_PATY_ROLE
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_APPT_PURP_CL', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_APPT_PURP_CL
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_APPT_PURP_CLAS_CL', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_APPT_PURP_CLAS_CL
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_APPT_PURP_HL', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_APPT_PURP_HL
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_APPT_PURP_PL', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_APPT_PURP_PL
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_APPT_QLFY', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_APPT_QLFY
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_APPT_QSTN_HL', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_APPT_QSTN_HL
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_APPT_QSTN_RESP_HL', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_APPT_QSTN_RESP_HL
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_CMPE_IDNN', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_CMPE_IDNN
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_CNTY', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_CNTY
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_CRIS_PDCT', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_CRIS_PDCT
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_DOCU_METH', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_DOCU_METH
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_ENV_CHLD_PATY_REL', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_ENV_CHLD_PATY_REL
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_ENV_EVNT_ACTV_TYPE', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_ENV_EVNT_ACTV_TYPE
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_ENV_PATY_REL', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_ENV_PATY_REL
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_ENV_PATY_TYPE', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_ENV_PATY_TYPE
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_FEAT_OVRD_REAS_HL', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_FEAT_OVRD_REAS_HL
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_FEAT_OVRD_REAS_HL_D', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_FEAT_OVRD_REAS_HL_D
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_FEAT_OVRD_REAS_PL', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_FEAT_OVRD_REAS_PL
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_FEE_CAPL', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_FEE_CAPL
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_FNDD_METH', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_FNDD_METH
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_JOB_COMM_CATG', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_JOB_COMM_CATG
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_LOAN_FNDD_METH', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_LOAN_FNDD_METH
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_LOAN_TERM_PL', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_LOAN_TERM_PL
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_LPC_DEPT_HL', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_LPC_DEPT_HL
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_ORIG_APPT_SRCE', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_ORIG_APPT_SRCE
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_ORIG_APPT_SRCE_HM', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_ORIG_APPT_SRCE_HM
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_OVRD_FEE_FRQ_CL', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_OVRD_FEE_FRQ_CL
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_PACK_PDCT_HL', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_PACK_PDCT_HL
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_PACK_PDCT_PL', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_PACK_PDCT_PL
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_PAYT_FREQ', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_PAYT_FREQ
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_PDCT_REL_CL', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_PDCT_REL_CL
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_PL_ACQR_TYPE', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_PL_ACQR_TYPE
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_SM_CASE_STUS', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_SM_CASE_STUS
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_SM_CASE_STUS_REAS', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_SM_CASE_STUS_REAS
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_STATE', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_STATE
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_TRNF_OPTN', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_TRNF_OPTN
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_TU_APPT_C', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_TU_APPT_C
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_UNID_PATY_CATG_PL', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_CSE_UNID_PATY_CATG_PL
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MOS_FCLY', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MOS_FCLY
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MOS_LOAN', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MOS_LOAN
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.PATY_APPT_PDCT', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.PATY_APPT_PDCT
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.PATY_INT_GRUP', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.PATY_INT_GRUP
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.THA_ACCT', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.THA_ACCT
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.UTIL_BTCH_ISAC', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.UTIL_BTCH_ISAC
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.UTIL_ETI_CONV', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.UTIL_ETI_CONV
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.UTIL_PARM', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.UTIL_PARM
UNION
SELECT 'NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.UTIL_PROS_ISAC', COUNT(1) FROM NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.UTIL_PROS_ISAC
ORDER BY table_name;
