{{ config(materialized='view', tags=['XfmCclAppProdFrmExt2']) }}

WITH RD_FEAT_I_4 AS (
	SELECT MAP_TYPE_C, SRCE_NUMC_1_C, SRCE_CHAR_2_C, FEAT_I_4 
	FROM (
		SELECT MAP_TYPE_C, SRCE_NUMC_1_C, SRCE_CHAR_2_C, FEAT_I_4,
		 ROW_NUMBER() OVER (PARTITION BY MAP_TYPE_C, SRCE_NUMC_1_C, SRCE_CHAR_2_C ORDER BY 1 ASC) AS ROW_NUM 
		FROM {{ ref('CpyRenameGRD_GNRC_MAPLks') }}
	) AS RD_FEAT_I_4_TEMP
	WHERE ROW_NUM = 1
)

SELECT * FROM RD_FEAT_I_4