{{ config(materialized='view', tags=['XfmCclAppProdFrmExt2']) }}

WITH XfmBusinessRules__ApptPdctFeat2 AS (
	SELECT
		-- *SRC*: \(20)If Len(Trim(( IF IsNotNull((InXfmBusinessRules.INDEX_RATE)) THEN (InXfmBusinessRules.INDEX_RATE) ELSE ""))) = 0 And Len(Trim(( IF IsNotNull((InXfmBusinessRules.ACTUAL_RATE)) THEN (InXfmBusinessRules.ACTUAL_RATE) ELSE ""))) = 0 Then 'N' Else 'Y',
		IFF(LEN(TRIM(IFF({{ ref('ModNullHandling') }}.INDEX_RATE IS NOT NULL, {{ ref('ModNullHandling') }}.INDEX_RATE, ''))) = 0 AND LEN(TRIM(IFF({{ ref('ModNullHandling') }}.ACTUAL_RATE IS NOT NULL, {{ ref('ModNullHandling') }}.ACTUAL_RATE, ''))) = 0, 'N', 'Y') AS LoadFeatI1,
		-- *SRC*: \(20)If Len(Trim(( IF IsNotNull((InXfmBusinessRules.LOAN_TERM_MTH_NUM)) THEN (InXfmBusinessRules.LOAN_TERM_MTH_NUM) ELSE ""))) > 0 And ( IF IsNotNull((InXfmBusinessRules.NEW_PROD_FLAG)) THEN (InXfmBusinessRules.NEW_PROD_FLAG) ELSE "") = 'Y' Then 'Y' Else 'N',
		IFF(LEN(TRIM(IFF({{ ref('ModNullHandling') }}.LOAN_TERM_MTH_NUM IS NOT NULL, {{ ref('ModNullHandling') }}.LOAN_TERM_MTH_NUM, ''))) > 0 AND IFF({{ ref('ModNullHandling') }}.NEW_PROD_FLAG IS NOT NULL, {{ ref('ModNullHandling') }}.NEW_PROD_FLAG, '') = 'Y', 'Y', 'N') AS LoadFeatI2,
		-- *SRC*: \(20)If Len(Trim(( IF IsNotNull((InXfmBusinessRules.INTERESTONLY_TERM_MTH_NUM)) THEN (InXfmBusinessRules.INTERESTONLY_TERM_MTH_NUM) ELSE ""))) > 0 Then 'Y' Else 'N',
		IFF(LEN(TRIM(IFF({{ ref('ModNullHandling') }}.INTERESTONLY_TERM_MTH_NUM IS NOT NULL, {{ ref('ModNullHandling') }}.INTERESTONLY_TERM_MTH_NUM, ''))) > 0, 'Y', 'N') AS LoadFeatI3,
		-- *SRC*: \(20)If Len(Trim(( IF IsNotNull((InXfmBusinessRules.CAPPED_RATE)) THEN (InXfmBusinessRules.CAPPED_RATE) ELSE ""))) = 0 Then 'N' Else 'Y',
		IFF(LEN(TRIM(IFF({{ ref('ModNullHandling') }}.CAPPED_RATE IS NOT NULL, {{ ref('ModNullHandling') }}.CAPPED_RATE, ''))) = 0, 'N', 'Y') AS LoadFeatI4,
		-- *SRC*: \(20)If Len(Trim(( IF IsNotNull((InXfmBusinessRules.CAPPED_TERM_MTH_NUM)) THEN (InXfmBusinessRules.CAPPED_TERM_MTH_NUM) ELSE ""))) > 0 Then 'Y' Else 'N',
		IFF(LEN(TRIM(IFF({{ ref('ModNullHandling') }}.CAPPED_TERM_MTH_NUM IS NOT NULL, {{ ref('ModNullHandling') }}.CAPPED_TERM_MTH_NUM, ''))) > 0, 'Y', 'N') AS LoadFeatI5,
		-- *SRC*: \(20)If Len(Trim(( IF IsNotNull((InXfmBusinessRules.TEMP_EXCESS_MTHS)) THEN (InXfmBusinessRules.TEMP_EXCESS_MTHS) ELSE ""))) = 0 Then 'N' Else 'Y',
		IFF(LEN(TRIM(IFF({{ ref('ModNullHandling') }}.TEMP_EXCESS_MTHS IS NOT NULL, {{ ref('ModNullHandling') }}.TEMP_EXCESS_MTHS, ''))) = 0, 'N', 'Y') AS LoadFeatI6,
		-- *SRC*: \(20)If (LoadFeatI1 = 'Y' And InXfmBusinessRules.FEAT_I_1 = '999009' And Len(Trim(( IF IsNotNull((InXfmBusinessRules.CCL_INTEREST_RATE_CAT_ID)) THEN (InXfmBusinessRules.CCL_INTEREST_RATE_CAT_ID) ELSE ""))) > 0) Then 'RPR3100' Else '',
		IFF(LoadFeatI1 = 'Y' AND {{ ref('ModNullHandling') }}.FEAT_I_1 = '999009' AND LEN(TRIM(IFF({{ ref('ModNullHandling') }}.CCL_INTEREST_RATE_CAT_ID IS NOT NULL, {{ ref('ModNullHandling') }}.CCL_INTEREST_RATE_CAT_ID, ''))) > 0, 'RPR3100', '') AS ErrorCode_1,
		-- *SRC*: \(20)If (LoadFeatI2 = 'Y' And InXfmBusinessRules.FEAT_I_2 = '999007') Then 'RPR3101' Else '',
		IFF(LoadFeatI2 = 'Y' AND {{ ref('ModNullHandling') }}.FEAT_I_2 = '999007', 'RPR3101', '') AS ErrorCode_2,
		-- *SRC*: \(20)If (LoadFeatI3 = 'Y' And InXfmBusinessRules.FEAT_I_3 = '999007') Then 'RPR3102' Else '',
		IFF(LoadFeatI3 = 'Y' AND {{ ref('ModNullHandling') }}.FEAT_I_3 = '999007', 'RPR3102', '') AS ErrorCode_3,
		-- *SRC*: \(20)If (LoadFeatI4 = 'Y' And InXfmBusinessRules.FEAT_I_4 = '999008') Then 'RPR3103' Else '',
		IFF(LoadFeatI4 = 'Y' AND {{ ref('ModNullHandling') }}.FEAT_I_4 = '999008', 'RPR3103', '') AS ErrorCode_4,
		-- *SRC*: \(20)If (LoadFeatI5 = 'Y' And InXfmBusinessRules.FEAT_I_5 = '999007') Then 'RPR3104' Else '',
		IFF(LoadFeatI5 = 'Y' AND {{ ref('ModNullHandling') }}.FEAT_I_5 = '999007', 'RPR3104', '') AS ErrorCode_5,
		-- *SRC*: \(20)If (LoadFeatI6 = 'Y' And InXfmBusinessRules.FEAT_I_6 = '999011') Then 'RPR3105' Else '',
		IFF(LoadFeatI6 = 'Y' AND {{ ref('ModNullHandling') }}.FEAT_I_6 = '999011', 'RPR3105', '') AS ErrorCode_6,
		-- *SRC*: \(20)If ErrorCode_1 <> "" Then ErrorCode_1 Else  If ErrorCode_2 <> "" Then ErrorCode_2 Else  If ErrorCode_3 <> "" Then ErrorCode_3 Else  If ErrorCode_4 <> "" Then ErrorCode_4 Else  If ErrorCode_5 <> "" Then ErrorCode_5 Else  If ErrorCode_6 <> "" Then ErrorCode_6 Else '',
		IFF(ErrorCode_1 <> '', ErrorCode_1, IFF(ErrorCode_2 <> '', ErrorCode_2, IFF(ErrorCode_3 <> '', ErrorCode_3, IFF(ErrorCode_4 <> '', ErrorCode_4, IFF(ErrorCode_5 <> '', ErrorCode_5, IFF(ErrorCode_6 <> '', ErrorCode_6, '')))))) AS ErrorCode,
		-- *SRC*: \(20)If ErrorCode <> "" Then @TRUE Else @FALSE,
		IFF(ErrorCode <> '', @TRUE, @FALSE) AS RejectFlag,
		-- *SRC*: 'CSECL' : InXfmBusinessRules.APP_PROD_ID,
		CONCAT('CSECL', {{ ref('ModNullHandling') }}.APP_PROD_ID) AS APPT_PDCT_I,
		{{ ref('ModNullHandling') }}.FEAT_I_2 AS FEAT_I,
		{{ ref('ModNullHandling') }}.APP_PROD_ID AS SRCE_SYST_APPT_FEAT_I,
		-- *SRC*: StringToDate(ETL_PROCESS_DT, "%yyyy%mm%dd"),
		STRINGTODATE(ETL_PROCESS_DT, '%yyyy%mm%dd') AS EFFT_D,
		'CSE' AS SRCE_SYST_C,
		-- *SRC*: SetNull(),
		SETNULL() AS SRCE_SYST_APPT_OVRD_I,
		-- *SRC*: SetNull(),
		SETNULL() AS OVRD_FEAT_I,
		-- *SRC*: SetNull(),
		SETNULL() AS SRCE_SYST_STND_VALU_Q,
		-- *SRC*: SetNull(),
		SETNULL() AS SRCE_SYST_STND_VALU_R,
		-- *SRC*: SetNull(),
		SETNULL() AS SRCE_SYST_STND_VALU_A,
		-- *SRC*: SetNull(),
		SETNULL() AS CNCY_C,
		{{ ref('ModNullHandling') }}.LOAN_TERM_MTH_NUM AS ACTL_VALU_Q,
		-- *SRC*: SetNull(),
		SETNULL() AS ACTL_VALU_R,
		-- *SRC*: SetNull(),
		SETNULL() AS ACTL_VALU_A,
		-- *SRC*: SetNull(),
		SETNULL() AS FEAT_SEQN_N,
		-- *SRC*: SetNull(),
		SETNULL() AS FEAT_STRT_D,
		-- *SRC*: SetNull(),
		SETNULL() AS FEE_CHRG_D,
		-- *SRC*: SetNull(),
		SETNULL() AS OVRD_REAS_C,
		'N' AS FEE_ADD_TO_TOTL_F,
		'N' AS FEE_CAPL_F,
		-- *SRC*: StringToDate('9999-12-31', "%yyyy-%mm-%dd"),
		STRINGTODATE('9999-12-31', '%yyyy-%mm-%dd') AS EXPY_D,
		0 AS PROS_KEY_EFFT_I,
		-- *SRC*: SetNull(),
		SETNULL() AS PROS_KEY_EXPY_I,
		-- *SRC*: SetNull(),
		SETNULL() AS EROR_SEQN_I,
		RUN_STREAM AS RUN_STRM,
		1 AS DLTA_VERS,
		'DUMY' AS FEAT_TYPE_C
	FROM {{ ref('ModNullHandling') }}
	WHERE LoadFeatI2 = 'Y'
)

SELECT * FROM XfmBusinessRules__ApptPdctFeat2