{{ config(materialized='view', tags=['DltAppt_QstnFrmTMP']) }}

WITH Remove_Duplicates_261 AS (
	SELECT APPT_I, QSTN_C, RESP_C, RESP_CMMT_X, PATY_I, EFFT_D, EXPY_D, ROW_SECU_ACCS_C, PROS_KEY_EFFT_I, PROS_KEY_EXPY_I, EROR_SEQN_I 
	FROM (
		SELECT APPT_I, QSTN_C, RESP_C, RESP_CMMT_X, PATY_I, EFFT_D, EXPY_D, ROW_SECU_ACCS_C, PROS_KEY_EFFT_I, PROS_KEY_EXPY_I, EROR_SEQN_I,
		 ROW_NUMBER() OVER (PARTITION BY APPT_I, QSTN_C, RESP_C, RESP_CMMT_X, PATY_I ORDER BY 1 ASC) AS ROW_NUM 
		FROM {{ ref('Update__Appt_Qstn_Ins') }}
	) AS Remove_Duplicates_261_TEMP
	WHERE ROW_NUM = 1
)

SELECT * FROM Remove_Duplicates_261