{{ config(materialized='view', tags=['LdGRD_GNRC_MAPLkpDS']) }}

WITH XfmConversions AS (
	SELECT
		-- *SRC*: Trim(( IF IsNotNull((InGRD_GNRC_MAPTera.MAP_TYPE_C)) THEN (InGRD_GNRC_MAPTera.MAP_TYPE_C) ELSE "")),
		TRIM(IFF({{ ref('SrcGRD_GNRC_MAPTera') }}.MAP_TYPE_C IS NOT NULL, {{ ref('SrcGRD_GNRC_MAPTera') }}.MAP_TYPE_C, '')) AS MAP_TYPE_C,
		SRCE_NUMC_1_C,
		-- *SRC*: Trim(( IF IsNotNull((InGRD_GNRC_MAPTera.SRCE_CHAR_1_C)) THEN (InGRD_GNRC_MAPTera.SRCE_CHAR_1_C) ELSE "")),
		TRIM(IFF({{ ref('SrcGRD_GNRC_MAPTera') }}.SRCE_CHAR_1_C IS NOT NULL, {{ ref('SrcGRD_GNRC_MAPTera') }}.SRCE_CHAR_1_C, '')) AS SRCE_CHAR_1_C,
		SRCE_NUMC_2_C,
		-- *SRC*: Trim(( IF IsNotNull((InGRD_GNRC_MAPTera.SRCE_CHAR_2_C)) THEN (InGRD_GNRC_MAPTera.SRCE_CHAR_2_C) ELSE "")),
		TRIM(IFF({{ ref('SrcGRD_GNRC_MAPTera') }}.SRCE_CHAR_2_C IS NOT NULL, {{ ref('SrcGRD_GNRC_MAPTera') }}.SRCE_CHAR_2_C, '')) AS SRCE_CHAR_2_C,
		SRCE_NUMC_3_C,
		-- *SRC*: Trim(( IF IsNotNull((InGRD_GNRC_MAPTera.SRCE_CHAR_3_C)) THEN (InGRD_GNRC_MAPTera.SRCE_CHAR_3_C) ELSE "")),
		TRIM(IFF({{ ref('SrcGRD_GNRC_MAPTera') }}.SRCE_CHAR_3_C IS NOT NULL, {{ ref('SrcGRD_GNRC_MAPTera') }}.SRCE_CHAR_3_C, '')) AS SRCE_CHAR_3_C,
		SRCE_NUMC_4_C,
		-- *SRC*: Trim(( IF IsNotNull((InGRD_GNRC_MAPTera.SRCE_CHAR_4_C)) THEN (InGRD_GNRC_MAPTera.SRCE_CHAR_4_C) ELSE "")),
		TRIM(IFF({{ ref('SrcGRD_GNRC_MAPTera') }}.SRCE_CHAR_4_C IS NOT NULL, {{ ref('SrcGRD_GNRC_MAPTera') }}.SRCE_CHAR_4_C, '')) AS SRCE_CHAR_4_C,
		SRCE_NUMC_5_C,
		-- *SRC*: Trim(( IF IsNotNull((InGRD_GNRC_MAPTera.SRCE_CHAR_5_C)) THEN (InGRD_GNRC_MAPTera.SRCE_CHAR_5_C) ELSE "")),
		TRIM(IFF({{ ref('SrcGRD_GNRC_MAPTera') }}.SRCE_CHAR_5_C IS NOT NULL, {{ ref('SrcGRD_GNRC_MAPTera') }}.SRCE_CHAR_5_C, '')) AS SRCE_CHAR_5_C,
		SRCE_NUMC_6_C,
		-- *SRC*: Trim(( IF IsNotNull((InGRD_GNRC_MAPTera.SRCE_CHAR_6_C)) THEN (InGRD_GNRC_MAPTera.SRCE_CHAR_6_C) ELSE "")),
		TRIM(IFF({{ ref('SrcGRD_GNRC_MAPTera') }}.SRCE_CHAR_6_C IS NOT NULL, {{ ref('SrcGRD_GNRC_MAPTera') }}.SRCE_CHAR_6_C, '')) AS SRCE_CHAR_6_C,
		SRCE_NUMC_7_C,
		-- *SRC*: Trim(( IF IsNotNull((InGRD_GNRC_MAPTera.SRCE_CHAR_7_C)) THEN (InGRD_GNRC_MAPTera.SRCE_CHAR_7_C) ELSE "")),
		TRIM(IFF({{ ref('SrcGRD_GNRC_MAPTera') }}.SRCE_CHAR_7_C IS NOT NULL, {{ ref('SrcGRD_GNRC_MAPTera') }}.SRCE_CHAR_7_C, '')) AS SRCE_CHAR_7_C,
		TARG_NUMC_C,
		-- *SRC*: Trim(( IF IsNotNull((InGRD_GNRC_MAPTera.TARG_CHAR_C)) THEN (InGRD_GNRC_MAPTera.TARG_CHAR_C) ELSE "")),
		TRIM(IFF({{ ref('SrcGRD_GNRC_MAPTera') }}.TARG_CHAR_C IS NOT NULL, {{ ref('SrcGRD_GNRC_MAPTera') }}.TARG_CHAR_C, '')) AS TARG_CHAR_C
	FROM {{ ref('SrcGRD_GNRC_MAPTera') }}
	WHERE 
)

SELECT * FROM XfmConversions