{{ config(materialized='view', tags=['ExtChlBusTuApp']) }}

WITH FunMergeJournal AS (
	SELECT
		SUBTYPE_CODE as SUBTYPE_CODE,
		HL_APP_PROD_ID as HL_APP_PROD_ID,
		TU_APP_ID as TU_APP_ID,
		TU_ACCOUNT_ID as TU_ACCOUNT_ID,
		TU_DOCCOLLECT_METHOD_CAT_ID as TU_DOCCOLLECT_METHOD_CAT_ID,
		DOCCOLLECT_ADDRESS_TYPE_ID as DOCCOLLECT_ADDRESS_TYPE_ID,
		DOCCOLLECT_BSB as DOCCOLLECT_BSB,
		TU_DOCCOLLECT_ADDRESS_LINE_1 as TU_DOCCOLLECT_ADDRESS_LINE_1,
		TU_DOCCOLLECT_ADDRESS_LINE_2 as TU_DOCCOLLECT_ADDRESS_LINE_2,
		TU_DOCCOLLECT_SUBURB as TU_DOCCOLLECT_SUBURB,
		TU_DOCCOLLECT_STATE_ID as TU_DOCCOLLECT_STATE_ID,
		TU_DOCCOLLECT_POSTCODE as TU_DOCCOLLECT_POSTCODE,
		TU_DOCCOLLECT_COUNTRY_ID as TU_DOCCOLLECT_COUNTRY_ID,
		TU_DOCCOLLECT_OVERSEA_STATE as TU_DOCCOLLECT_OVERSEA_STATE,
		TOPUP_AMOUNT as TOPUP_AMOUNT,
		TOPUP_AGENT_ID as TOPUP_AGENT_ID,
		TOPUP_AGENT_NAME as TOPUP_AGENT_NAME,
		ACCOUNT_NO as ACCOUNT_NO,
		CRIS_PRODUCT_ID as CRIS_PRODUCT_ID,
		CAMPAIGN_CODE as CAMPAIGN_CODE,
		ORIG_ETL_D as ORIG_ETL_D
	FROM {{ ref('XfmSeparateRejectWithoutSourceAndTheRest__InSourceRec') }}
	UNION ALL
	SELECT
		SUBTYPE_CODE,
		HL_APP_PROD_ID,
		TU_APP_ID,
		TU_ACCOUNT_ID,
		TU_DOCCOLLECT_METHOD_CAT_ID,
		DOCCOLLECT_ADDRESS_TYPE_ID,
		DOCCOLLECT_BSB,
		TU_DOCCOLLECT_ADDRESS_LINE_1,
		TU_DOCCOLLECT_ADDRESS_LINE_2,
		TU_DOCCOLLECT_SUBURB,
		TU_DOCCOLLECT_STATE_ID,
		TU_DOCCOLLECT_POSTCODE,
		TU_DOCCOLLECT_COUNTRY_ID,
		TU_DOCCOLLECT_OVERSEA_STATE,
		TOPUP_AMOUNT,
		TOPUP_AGENT_ID,
		TOPUP_AGENT_NAME,
		ACCOUNT_NO,
		CRIS_PRODUCT_ID,
		CAMPAIGN_CODE,
		ORIG_ETL_D
	FROM {{ ref('XfmSeparateRejectWithoutSourceAndTheRest__InRejectWithoutSourceRec') }}
)

SELECT * FROM FunMergeJournal