{{ config(materialized='view', tags=['DltAPPTAttrClasAsscFrmTMP_APPT_ATTR_CLAS_ASSC']) }}

WITH 
,
SrcTgtApptAttrClasAsscTera AS (SELECT 
a.APPT_I As NEW_APPT_I,
a.APPT_ATTR_CLAS_C As NEW_APPT_ATTR_CLAS_C,
a.APPT_ATTR_CLAS_VALU_C As NEW_APPT_ATTR_CLAS_VALU_C,
a.EFFT_D As NEW_EFFT_D,
a.SRCE_SYST_C As NEW_SRCE_SYST_C,
a.EXPY_D As NEW_EXPY_D,
a.PROS_KEY_EFFT_I AS NEW_PROS_KEY_EFFT_I,
a.PROS_KEY_EXPY_I As NEW_PROS_KEY_EXPY_I,
a.ROW_SECU_ACCS_C As NEW_ROW_SECU_ACCS_C, 
b.APPT_I AS OLD_APPT_I,
B.EFFT_D   (FORMAT 'YYYY-MM-DD')  AS OLD_EFFT_D,
B.APPT_ATTR_CLAS_C AS OLD_APPT_ATTR_CLAS_C,
'NULL' as REC_TYPE_I
from {{ var('GDW_STG_DB') }}.TMP_APPT_ATTR_CLAS_ASSC a 
LEFT OUTER JOIN
{{ var('GDW_ACCT_VW') }}.APPT_ATTR_CLAS_ASSC b
ON a.APPT_I=b.APPT_I
AND a.APPT_ATTR_CLAS_C=b.APPT_ATTR_CLAS_C 
where a.SRCE_SYST_C ='CSE'
And a.APPT_ATTR_CLAS_C='FHBF'

UNION ALL

SELECT 
a.APPT_I As NEW_APPT_I,
a.APPT_ATTR_CLAS_C As NEW_APPT_ATTR_CLAS_C,
a.APPT_ATTR_CLAS_VALU_C As NEW_APPT_ATTR_CLAS_VALU_C,
a.EFFT_D As NEW_EFFT_D,
a.SRCE_SYST_C As NEW_SRCE_SYST_C,
a.EXPY_D As NEW_EXPY_D,
a.PROS_KEY_EFFT_I AS NEW_PROS_KEY_EFFT_I,
a.PROS_KEY_EXPY_I As NEW_PROS_KEY_EXPY_I,
a.ROW_SECU_ACCS_C As NEW_ROW_SECU_ACCS_C, 
b.OLD_APPT_I AS OLD_APPT_I,
B.OLD_EFFT_D   (FORMAT 'YYYY-MM-DD')  AS OLD_EFFT_D,
B.OLD_APPT_ATTR_CLAS_C AS OLD_APPT_ATTR_CLAS_C,
CASE
WHEN B.OLD_FLAG IS NULL AND A.APPT_ATTR_CLAS_C='Y' AND  A.APPT_ATTR_CLAS_VALU_C IS NOT NULL THEN 'I'

WHEN B.OLD_FLAG='Y'  AND A.APPT_ATTR_CLAS_C='Y'  AND A.APPT_ATTR_CLAS_VALU_C IS NOT NULL 
AND( COALESCE(A.APPT_ATTR_CLAS_VALU_C,'') <> COALESCE(B.OLD_APPT_ATTR_CLAS_VALU_C,'') ) THEN 'U'

WHEN B.OLD_FLAG='Y'  AND  ( A.APPT_ATTR_CLAS_C='N' or A.APPT_ATTR_CLAS_C IS NULL)  
 THEN 'E'

WHEN B.OLD_FLAG IS NULL AND ( A.APPT_ATTR_CLAS_C='N' or A.APPT_ATTR_CLAS_C IS NULL)  THEN 'D' 
ELSE 'S'
END AS REC_TYPE_I

FROM {{ var('GDW_STG_DB') }}.TMP_APPT_ATTR_CLAS_ASSC a
LEFT OUTER JOIN 
(SELECT APPT_I AS OLD_APPT_I,APPT_ATTR_CLAS_C AS OLD_APPT_ATTR_CLAS_C,SRCE_SYST_C AS OLD_SRCE_SYST_C,
APPT_ATTR_CLAS_VALU_C as OLD_APPT_ATTR_CLAS_VALU_C,EFFT_D  (FORMAT 'YYYY-MM-DD') as  OLD_EFFT_D,'Y' AS OLD_FLAG 
FROM {{ var('GDW_ACCT_VW') }}.APPT_ATTR_CLAS_ASSC 
WHERE EXPY_D='9999-12-31' and OLD_APPT_ATTR_CLAS_C<>'FHBF') B
ON 
A.APPT_I=B.OLD_APPT_I
AND
A.SRCE_SYST_C=B.OLD_SRCE_SYST_C
WHERE REC_TYPE_I not in ('S','D')
and  A.APPT_ATTR_CLAS_C<>'FHBF')


SELECT * FROM SrcTgtApptAttrClasAsscTera