{{ config(materialized='view', tags=['DltPATY_RELFrmTMP_FA_CLIENT_UNDERTAKING2']) }}

WITH CpyFAClientUndertaking AS (
	SELECT
		REL_I,
		SRCE_SYST_REL_I,
		REL_TYPE_C,
		RELD_PATY_I,
		SRCE_SYST_C,
		PATY_ROLE_C,
		REL_STUS_C,
		REL_EFFT_D,
		REL_EXPY_D,
		REL_REAS_C,
		REL_LEVL_C,
		PATY_I,
		{{ ref('SrcTmpFAClientUndertakingTera') }}.OLD_REL_I AS REL_I,
		{{ ref('SrcTmpFAClientUndertakingTera') }}.OLD_SRCE_SYST_REL_I AS SRCE_SYST_REL_I,
		{{ ref('SrcTmpFAClientUndertakingTera') }}.OLD_REL_TYPE_C AS REL_TYPE_C,
		{{ ref('SrcTmpFAClientUndertakingTera') }}.OLD_RELD_PATY_I AS RELD_PATY_I,
		{{ ref('SrcTmpFAClientUndertakingTera') }}.OLD_SRCE_SYST_C AS SRCE_SYST_C,
		{{ ref('SrcTmpFAClientUndertakingTera') }}.OLD_PATY_ROLE_C AS PATY_ROLE_C,
		{{ ref('SrcTmpFAClientUndertakingTera') }}.OLD_REL_STUS_C AS REL_STUS_C,
		{{ ref('SrcTmpFAClientUndertakingTera') }}.OLD_REL_EFFT_D AS REL_EFFT_D,
		{{ ref('SrcTmpFAClientUndertakingTera') }}.OLD_REL_EXPY_D AS REL_EXPY_D,
		{{ ref('SrcTmpFAClientUndertakingTera') }}.OLD_REL_REAS_C AS REL_REAS_C,
		{{ ref('SrcTmpFAClientUndertakingTera') }}.OLD_REL_LEVL_C AS REL_LEVL_C,
		{{ ref('SrcTmpFAClientUndertakingTera') }}.OLD_PATY_I AS PATY_I,
		CSE_FA_CLNT_UNTK_ID,
		CSE_FA_UNTK_ID,
		CSE_COIN_ENTY_ID,
		CSE_CLNT_CORR_ID,
		CSE_FA_ENTY_CAT_ID,
		CSE_FA_CHLD_STAT_CAT_ID,
		CSE_CLNT_REL_TYPE_ID,
		CSE_CLNT_POSN,
		CSE_IS_PRIM_FLAG,
		CSE_CIF_CODE,
		CSE_ORIG_ETL_D,
		OLD_REL_I,
		OLD_REL_TYPE_C,
		OLD_RELD_PATY_I,
		OLD_REL_LEVL_C,
		OLD_PATY_I,
		OLD_EFFT_D,
		OLD_SRCE_SYST_REL_I,
		OLD_SRCE_SYST_C,
		OLD_PATY_ROLE_C,
		OLD_REL_STUS_C,
		OLD_REL_EFFT_D,
		OLD_REL_EXPY_D,
		OLD_REL_REAS_C
	FROM {{ ref('SrcTmpFAClientUndertakingTera') }}
)

SELECT * FROM CpyFAClientUndertaking