-- Count query for PDSECURITY.ROW_LEVL_SECU_USER_PRFL
-- Snowflake table: PS_CLD_RW.PDSECURITY.ROW_LEVL_SECU_USER_PRFL
-- Teradata counterpart: PDSECURITY.ROW_LEVL_SECU_USER_PRFL

SELECT count(1) AS record_count
FROM PDSECURITY.ROW_LEVL_SECU_USER_PRFL; 