-- Count query for STARCADPRODDATA.MAP_SAP_INVL_PDCT
-- Snowflake table: PS_CLD_RW.STARCADPRODDATA.MAP_SAP_INVL_PDCT
-- Teradata counterpart: STARCADPRODDATA.MAP_SAP_INVL_PDCT

SELECT count(1) AS record_count
FROM STARCADPRODDATA.MAP_SAP_INVL_PDCT; 