-- Count query for PVTECH.DERV_PRTF_INT_PSST (mapped to STARCADPRODDATA)
-- Snowflake table: PS_CLD_RW.STARCADPRODDATA.DERV_PRTF_INT_PSST
-- Teradata counterpart: PVTECH.DERV_PRTF_INT_PSST

SELECT count(1) AS record_count
FROM PVTECH.DERV_PRTF_INT_PSST; 