{{ config(materialized='view', tags=['LdREJT_CHL_BUS_APP_PROD']) }}

WITH FunChlBusAppProdPurpNulls AS (
	SELECT
		HL_APP_PROD_ID as HL_APP_PROD_ID,
		PARENT_HL_APP_PROD_ID as PARENT_HL_APP_PROD_ID,
		HL_REPAYMENT_PERIOD_CAT_ID as HL_REPAYMENT_PERIOD_CAT_ID,
		AMOUNT as AMOUNT,
		LOAN_TERM_MONTHS as LOAN_TERM_MONTHS,
		ACCOUNT_NUMBER as ACCOUNT_NUMBER,
		TOTAL_LOAN_AMOUNT as TOTAL_LOAN_AMOUNT,
		HLS_FLAG as HLS_FLAG,
		GDW_UPDATED_LDP_PAID_ON_AMOUNT as GDW_UPDATED_LDP_PAID_ON_AMOUNT,
		ETL_D as ETL_D,
		ORIG_ETL_D as ORIG_ETL_D,
		EROR_C as EROR_C
	FROM {{ ref('RejChlBusAppProdDS') }}
	UNION ALL
	SELECT
		HL_APP_PROD_ID,
		PARENT_HL_APP_PROD_ID,
		HL_REPAYMENT_PERIOD_CAT_ID,
		AMOUNT,
		LOAN_TERM_MONTHS,
		ACCOUNT_NUMBER,
		TOTAL_LOAN_AMOUNT,
		HLS_FLAG,
		GDW_UPDATED_LDP_PAID_ON_AMOUNT,
		ETL_D,
		ORIG_ETL_D,
		EROR_C
	FROM {{ ref('SrcChlBusAppProdRejectsDS') }}
)

SELECT * FROM FunChlBusAppProdPurpNulls