{{ config(materialized='view', tags=['LdMAP_CSE_ENV_EVNT_ACT_TYPELkp']) }}

WITH XfmConversions AS (
	SELECT
		-- *SRC*: trim(InMAP_CSE_ENV_EVNT_ACT_TYPE_Tera.FA_ENV_EVNT_CAT_ID),
		TRIM({{ ref('SrcMAP_CSE_ENV_EVNT_ACT_TYPE_Tera') }}.FA_ENV_EVNT_CAT_ID) AS FA_ENV_EVNT_CAT_ID,
		-- *SRC*: trim(InMAP_CSE_ENV_EVNT_ACT_TYPE_Tera.EVNT_ACTV_TYPE_C),
		TRIM({{ ref('SrcMAP_CSE_ENV_EVNT_ACT_TYPE_Tera') }}.EVNT_ACTV_TYPE_C) AS EVNT_ACTV_TYPE_C
	FROM {{ ref('SrcMAP_CSE_ENV_EVNT_ACT_TYPE_Tera') }}
	WHERE 
)

SELECT * FROM XfmConversions