{{ config(materialized='view', tags=['XfmUnidPatyIdnnGnrc']) }}

WITH Modify_Null AS (
	SELECT 
	--Manual
	--ABN= handle_null(ABN,'99999');ACN= handle_null(ACN,'99999');REFERRAL_AGENT_ID=handle_null(REFERRAL_AGENT_ID,'99999');HL_APP_ID=handle_null(HL_APP_ID,'99999')
	REC_TYPE, HL_APP_COMMISSION_ID, MOD_TIMESTAMP, MOD_USER_ID, HL_APP_ID, HL_COMMISSION_CAT_ID, NAME, ABN_ACN_NUMBER, AMOUNT, ACN, ABN, ADDITIONAL_COMMISSIONS_FLAG, MOD_CLIENT_ID, HL_APP_COMMISSION_BASE_VN, IS_REFERRAL_AGENT, REFERRAL_AGENT_ID 
	FROM {{ ref('SrcCseChlBusAppCommDet') }}
)

SELECT * FROM Modify_Null