{{ config(materialized='incremental', alias='appt_pdct', incremental_strategy='append', tags=['LdApptPdctIns']) }}

SELECT
	APPT_PDCT_I
	DEBT_ABN_X
	DEBT_BUSN_M
	SMPL_APPT_F
	JOB_COMM_CATG_C
	APPT_QLFY_C
	ACQR_TYPE_C
	ACQR_ADHC_X
	ACQR_SRCE_C
	PDCT_N
	APPT_I
	SRCE_SYST_C
	SRCE_SYST_APPT_PDCT_I
	LOAN_FNDD_METH_C
	NEW_ACCT_F
	BROK_PATY_I
	COPY_FROM_OTHR_APPT_F
	EFFT_D
	EXPY_D
	PROS_KEY_EFFT_I
	PROS_KEY_EXPY_I
	EROR_SEQN_I
	APPT_PDCT_CATG_C
	APPT_PDCT_DURT_C
	ASES_D 
FROM {{ ref('TgtApptPdctInsertDS') }}