{{ config(materialized='view', tags=['XfmDelFlagAPPT_PDCT_AMT']) }}

WITH XfmProsKey AS (
	SELECT
		DELETED_TABLE_NAME,
		-- *SRC*: \(20)If OutAppPdctAmtDS.DELETED_TABLE_NAME = 'HL_FEATURE_ATTR' Then OutAppPdctAmtDS.DELETED_KEY_2_VALUE Else OutAppPdctAmtDS.DELETED_KEY_1_VALUE,
		IFF({{ ref('SrcAppPdctAmtDS') }}.DELETED_TABLE_NAME = 'HL_FEATURE_ATTR', {{ ref('SrcAppPdctAmtDS') }}.DELETED_KEY_2_VALUE, {{ ref('SrcAppPdctAmtDS') }}.DELETED_KEY_1_VALUE) AS APP_PROD_ID,
		-- *SRC*: \(20)If OutAppPdctAmtDS.DELETED_TABLE_NAME = 'CCL_APP_PROD' Then 'CSE_CCL_BUS_APP_PROD_APPT_PDCT_AMT1' Else  If OutAppPdctAmtDS.DELETED_TABLE_NAME = 'HL_APP_PROD' Then 'CSE_CHL_BUS_APP_PROD_APPT_PDCT_AMT2' Else  If OutAppPdctAmtDS.DELETED_TABLE_NAME = 'PL_APP_PROD' Then 'CSE_CPL_BUS_APP_PROD_APPT_PDCT_AMT2' Else  If OutAppPdctAmtDS.DELETED_TABLE_NAME = 'CC_APP_PROD' Then 'CSE_CCC_BUS_APP_PROD_APPT_PDCT_AMT2' Else  If OutAppPdctAmtDS.DELETED_TABLE_NAME = 'HL_FEATURE_ATTR' Then 'CSE_CHL_BUS_FEAT_ATTR_APPT_PDCT_AMT2' Else '',
		IFF(
	    {{ ref('SrcAppPdctAmtDS') }}.DELETED_TABLE_NAME = 'CCL_APP_PROD', 'CSE_CCL_BUS_APP_PROD_APPT_PDCT_AMT1',     
	    IFF(
	        {{ ref('SrcAppPdctAmtDS') }}.DELETED_TABLE_NAME = 'HL_APP_PROD', 'CSE_CHL_BUS_APP_PROD_APPT_PDCT_AMT2',         
	        IFF(
	            {{ ref('SrcAppPdctAmtDS') }}.DELETED_TABLE_NAME = 'PL_APP_PROD', 'CSE_CPL_BUS_APP_PROD_APPT_PDCT_AMT2', 
	            IFF({{ ref('SrcAppPdctAmtDS') }}.DELETED_TABLE_NAME = 'CC_APP_PROD', 'CSE_CCC_BUS_APP_PROD_APPT_PDCT_AMT2', IFF({{ ref('SrcAppPdctAmtDS') }}.DELETED_TABLE_NAME = 'HL_FEATURE_ATTR', 'CSE_CHL_BUS_FEAT_ATTR_APPT_PDCT_AMT2', ''))
	        )
	    )
	) AS CONV_M
	FROM {{ ref('SrcAppPdctAmtDS') }}
	WHERE 
)

SELECT * FROM XfmProsKey