{{ config(materialized='view', tags=['ExtWRK_APPT_PDCT_FEATFrmStg_IntRateAmtMargin']) }}

WITH XfmAddDate AS (
	SELECT
		'RPR5116' AS ErrorCode,
		PL_INT_RATE_ID,
		PL_INT_RATE_PL_INT_RATE_ID,
		PL_INT_RATE_DOC_SEQ_NO,
		PL_INT_RATE_CASS_MARGIN_AMT,
		PL_INT_RATE_INT_RATE_TERM,
		PL_INT_RATE_INT_RATE_FREQ_ID,
		PL_INT_RATE_VARIANT_CAT_ID,
		PL_INT_RATE_USAGE_CAT_ID,
		PL_INT_RATE_PL_APP_PROD_ID,
		PL_MARGIN_PL_MARGIN_ID,
		PL_MARGIN_MARGIN_AMT,
		PL_MARGIN_PL_FEE_ID,
		PL_MARGIN_PL_INT_RATE_ID,
		PL_MARGIN_MARGIN_RESN_CAT_ID,
		PL_MARGIN_PL_APP_PROD_ID,
		PL_INT_RATE_AMT_INT_RTE_AMT_2,
		PL_INT_RATE_AMT_INT_RTCT_ID2,
		PL_INT_RATE_AMT_PL_INT_RATE_ID,
		PL_INT_RATE_AMT_INT_RATE_AMT_1,
		PL_INT_RATE_AMT_INT_RTCT_ID1,
		PL_MARGIN_FOUND_FLAG,
		PL_INT_RATE_FOUND_FLAG,
		PL_INT_RATE_AMT_FOUND_FLAG,
		ETL_PROCESS_DT AS ETL_D,
		ORIG_ETL_D,
		ErrorCode AS EROR_C
	FROM {{ ref('SwRejectFlag') }}
	WHERE 
)

SELECT * FROM XfmAddDate