{{ config(materialized='view', tags=['XfmAppt_Pdct_Paty']) }}

WITH FunlToXfm AS (
	SELECT
		SUBTYPE_CODE as SUBTYPE_CODE,
		APP_PROD_ID as APP_PROD_ID,
		ROLE_CAT_ID as ROLE_CAT_ID,
		APP_PROD_CLIENT_ROLE_ID as APP_PROD_CLIENT_ROLE_ID,
		APPT_QLFY_C as APPT_QLFY_C,
		PATY_ROLE_C as PATY_ROLE_C,
		CIF_CODE as CIF_CODE
	FROM {{ ref('LkpApptQlfyC') }}
	UNION ALL
	SELECT
		APP_PROD_ID,
		SUBTYPE_CODE,
		ROLE_CAT_ID,
		APP_PROD_CLIENT_ROLE_ID,
		PATY_ROLE_C,
		APPT_QLFY_C,
		CIF_CODE
	FROM {{ ref('FiltrNulAndNotnul') }}
)

SELECT * FROM FunlToXfm