{{ config(materialized='view', tags=['Ext_Fn_Hl_PL']) }}

WITH Funnel_2 AS (
	SELECT
		RECORD_TYPE as RECORD_TYPE,
		MOD_TIMESTAMP as MOD_TIMESTAMP,
		HL_APP_ID as HL_APP_ID,
		QA_QUESTION_ID as QA_QUESTION_ID,
		QA_ANSWER_ID as QA_ANSWER_ID,
		TEXT_ANSWER as TEXT_ANSWER,
		CIF_CODE as CIF_CODE,
		CBA_STAFF_NUMBER as CBA_STAFF_NUMBER,
		LODGEMENT_BRANCH_ID as LODGEMENT_BRANCH_ID,
		SUBTYPE_CODE as SUBTYPE_CODE,
		YN_FLAG_ANSWER as YN_FLAG_ANSWER,
		Dummy as Dummy
	FROM {{ ref('Data_Set_HL') }}
	UNION ALL
	SELECT
		RECORD_TYPE,
		MOD_TIMESTAMP,
		HL_APP_ID,
		QA_QUESTION_ID,
		QA_ANSWER_ID,
		TEXT_ANSWER,
		CIF_CODE,
		CBA_STAFF_NUMBER,
		LODGEMENT_BRANCH_ID,
		SUBTYPE_CODE,
		YN_FLAG_ANSWER,
		Dummy
	FROM {{ ref('Transformer_11') }}
)

SELECT * FROM Funnel_2