{{ config(materialized='view', tags=['DltAPPT_FEATFrmTMP_APPT_FEAT']) }}

WITH ChangeCapture AS (
	SELECT
		COALESCE({{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_APPT_I, {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_APPT_I) AS NEW_APPT_I,
		COALESCE({{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_SRCE_SYST_APPT_FEAT_I, {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_SRCE_SYST_APPT_FEAT_I) AS NEW_SRCE_SYST_APPT_FEAT_I,
		COALESCE({{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_SRCE_SYST_STND_VALU_R, {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_SRCE_SYST_STND_VALU_R) AS NEW_SRCE_SYST_STND_VALU_R,
		COALESCE({{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_SRCE_SYST_STND_VALU_A, {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_SRCE_SYST_STND_VALU_A) AS NEW_SRCE_SYST_STND_VALU_A,
		COALESCE({{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_ACTL_VALU_Q, {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_ACTL_VALU_Q) AS NEW_ACTL_VALU_Q,
		COALESCE({{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_ACTL_VALU_R, {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_ACTL_VALU_R) AS NEW_ACTL_VALU_R,
		COALESCE({{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_ACTL_VALU_A, {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_ACTL_VALU_A) AS NEW_ACTL_VALU_A,
		COALESCE({{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_FEE_CHRG_D, {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_FEE_CHRG_D) AS NEW_FEE_CHRG_D,
		CASE
			WHEN {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_APPT_I IS NULL AND {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_SRCE_SYST_APPT_FEAT_I IS NULL THEN '1'
			WHEN {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_APPT_I IS NULL AND {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_SRCE_SYST_APPT_FEAT_I IS NULL THEN '2'
			WHEN ({{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_APPT_I = {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_APPT_I AND {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_SRCE_SYST_APPT_FEAT_I = {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_SRCE_SYST_APPT_FEAT_I) AND ({{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_SRCE_SYST_STND_VALU_R <> {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_SRCE_SYST_STND_VALU_R OR {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_SRCE_SYST_STND_VALU_A <> {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_SRCE_SYST_STND_VALU_A OR {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_ACTL_VALU_Q <> {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_ACTL_VALU_Q OR {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_ACTL_VALU_R <> {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_ACTL_VALU_R OR {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_ACTL_VALU_A <> {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_ACTL_VALU_A OR {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_FEE_CHRG_D <> {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_FEE_CHRG_D OR {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_FEAT_I <> {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_FEAT_I OR {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_SRCE_SYST_C <> {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_SRCE_SYST_C OR {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_SRCE_SYST_STND_VALU_Q <> {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_SRCE_SYST_STND_VALU_Q OR {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_CNCY_C <> {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_CNCY_C OR {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_OVRD_FEAT_I <> {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_OVRD_FEAT_I OR {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_OVRD_REAS_C <> {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_OVRD_REAS_C OR {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_FEAT_SEQN_N <> {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_FEAT_SEQN_N OR {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_FEAT_STRT_D <> {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_FEAT_STRT_D) THEN '3'
			WHEN {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_APPT_I = {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_APPT_I AND {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_SRCE_SYST_APPT_FEAT_I = {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_SRCE_SYST_APPT_FEAT_I AND {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_SRCE_SYST_STND_VALU_R = {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_SRCE_SYST_STND_VALU_R AND {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_SRCE_SYST_STND_VALU_A = {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_SRCE_SYST_STND_VALU_A AND {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_ACTL_VALU_Q = {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_ACTL_VALU_Q AND {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_ACTL_VALU_R = {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_ACTL_VALU_R AND {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_ACTL_VALU_A = {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_ACTL_VALU_A AND {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_FEE_CHRG_D = {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_FEE_CHRG_D AND {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_FEAT_I = {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_FEAT_I AND {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_SRCE_SYST_C = {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_SRCE_SYST_C AND {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_SRCE_SYST_STND_VALU_Q = {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_SRCE_SYST_STND_VALU_Q AND {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_CNCY_C = {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_CNCY_C AND {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_OVRD_FEAT_I = {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_OVRD_FEAT_I AND {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_OVRD_REAS_C = {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_OVRD_REAS_C AND {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_FEAT_SEQN_N = {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_FEAT_SEQN_N AND {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_FEAT_STRT_D = {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_FEAT_STRT_D THEN '0'
		END AS change_code 
	FROM {{ ref('{{ ref('CpyApptFeat') }}') }} 
	FULL OUTER JOIN {{ ref('{{ ref('CpyApptFeat') }}') }} 
	ON {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_APPT_I = {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_APPT_I
	AND {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_SRCE_SYST_APPT_FEAT_I = {{ ref('{{ ref('CpyApptFeat') }}') }}.NEW_SRCE_SYST_APPT_FEAT_I
	WHERE change_code = '1' OR change_code = '3'
)

SELECT * FROM ChangeCapture