{{ config(materialized='view', tags=['DltAPPT_PDCT_AMTFrmTMP_APPT_PDCT_AMT_1']) }}

WITH 
appt_pdct_amt AS (
	SELECT
	*
	FROM {{ ref("appt_pdct_amt")  }}),
tmp_appt_pdct_amt AS (
	SELECT
	*
	FROM {{ ref("tmp_appt_pdct_amt")  }}),
SrcTmpApptPdctAmtTera AS (SELECT a.APPT_PDCT_I AS NEW_APPT_PDCT_I, a.AMT_TYPE_C AS NEW_AMT_TYPE_C, a.CNCY_C AS NEW_CNCY_C, a.APPT_PDCT_A AS NEW_APPT_PDCT_A, b.APPT_PDCT_I AS OLD_APPT_PDCT_I, b.AMT_TYPE_C AS OLD_AMT_TYPE_C, b.EFFT_D AS OLD_EFFT_D, b.APPT_PDCT_A AS OLD_APPT_PDCT_A FROM TMP_APPT_PDCT_AMT LEFT OUTER JOIN APPT_PDCT_AMT ON TRIM(a.APPT_PDCT_I) = TRIM(b.APPT_PDCT_I) AND TRIM(b.AMT_TYPE_C) IN ('XPSR', 'NUXP') AND b.EXPY_D = '9999-12-31' WHERE a.RUN_STRM = '{{ var("RUN_STREAM") }}' AND a.DLTA_VERS = '1')


SELECT * FROM SrcTmpApptPdctAmtTera