{{ config(materialized='view', tags=['DltAPPT_PDCT_FEAT_FrmTMP_APPT_PDCT_FEAT_PEXAHM_ONEOFF']) }}

WITH 
,
SrcTmpApptPDctFeatTera AS (SELECT 
A.APPT_PDCT_I AS NEW_APPT_PDCT_I,
A.FEAT_I      AS NEW_FEAT_I,
A.SRCE_SYST_C AS NEW_SRCE_SYST_C,
A.FEAT_VALU_C AS NEW_FEAT_VALU_C,
B.OLD_EFFT_D   (FORMAT 'YYYY-MM-DD')  AS OLD_EFFT_D,
CASE
WHEN B.OLD_FLAG IS NULL  AND A.FEAT_VALU_C IS NOT NULL THEN 'I'
WHEN B.OLD_FLAG='Y' AND A.FEAT_VALU_C IS NOT NULL
	 AND (COALESCE(A.FEAT_VALU_C,'') <> COALESCE(B.OLD_FEAT_VALU_C,''))  THEN 'U'
ELSE 'S'
END AS REC_TYPE_I

FROM {{ var('GDW_STG_DB') }}.TMP_APPT_PDCT_FEAT_PEXAHMONEOFF A
LEFT OUTER JOIN 
(SELECT APPT_PDCT_I AS OLD_APPT_PDCT_I,FEAT_I AS OLD_FEAT_I,SRCE_SYST_C AS OLD_SRCE_SYST_C,
FEAT_VALU_C as OLD_FEAT_VALU_C,EFFT_D  (FORMAT 'YYYY-MM-DD') as  OLD_EFFT_D,'Y' AS OLD_FLAG 
FROM {{ var('GDW_ACCT_VW') }}.APPT_PDCT_FEAT 
WHERE EXPY_D='9999-12-31') B
ON 
A.APPT_PDCT_I=B.OLD_APPT_PDCT_I
AND
A.FEAT_I=B.OLD_FEAT_I
AND
A.SRCE_SYST_C=B.OLD_SRCE_SYST_C
WHERE REC_TYPE_I <> 'S';
)


SELECT * FROM SrcTmpApptPDctFeatTera