{{ config(materialized='view', tags=['LdREJT_CSE_CHL_BUS_APP']) }}

WITH FunCseChlBusNulls AS (
	SELECT
		HL_APP_ID as HL_APP_ID,
		HL_PACKAGE_CAT_ID as HL_PACKAGE_CAT_ID,
		LPC_OFFICE as LPC_OFFICE,
		STATUS_TRACKER_ID as STATUS_TRACKER_ID,
		ETL_D as ETL_D,
		ORIG_ETL_D as ORIG_ETL_D,
		EROR_C as EROR_C,
		HL_APP_PROD_ID as HL_APP_PROD_ID,
		CHL_APP_PCD_EXT_SYS_CAT_ID as CHL_APP_PCD_EXT_SYS_CAT_ID,
		CHL_APP_SIMPLE_APP_FLAG as CHL_APP_SIMPLE_APP_FLAG,
		CHL_APP_ORIGINATING_AGENT_ID as CHL_APP_ORIGINATING_AGENT_ID,
		CHL_APP_AGENT_NAME as CHL_APP_AGENT_NAME,
		CASS_WITHHOLD_RISKBANK_FLAG as CASS_WITHHOLD_RISKBANK_FLAG,
		CR_DATE as FHB_FLAG,
		ASSESSMENT_DATE as SETTLEMENT_DATE,
		NCPR_FLAG as PEXA_FLAG,
		FHB_FLAG as HSCA_FLAG,
		SETTLEMENT_DATE as HSCA_CONVERTED_TO_FULL_AT,
		PEXA_FLAG,
		HSCA_FLAG,
		HSCA_CONVERTED_TO_FULL_AT
	FROM {{ ref('RejCseChlBusDS') }}
	UNION ALL
	SELECT
		HL_APP_ID,
		HL_PACKAGE_CAT_ID,
		LPC_OFFICE,
		STATUS_TRACKER_ID,
		ETL_D,
		ORIG_ETL_D,
		EROR_C,
		HL_APP_PROD_ID,
		CHL_APP_PCD_EXT_SYS_CAT_ID,
		CHL_APP_SIMPLE_APP_FLAG,
		CHL_APP_ORIGINATING_AGENT_ID,
		CHL_APP_AGENT_NAME,
		CASS_WITHHOLD_RISKBANK_FLAG,
		CR_DATE,
		ASSESSMENT_DATE,
		NCPR_FLAG,
		FHB_FLAG,
		SETTLEMENT_DATE,
		PEXA_FLAG,
		HSCA_FLAG,
		HSCA_CONVERTED_TO_FULL_AT
	FROM {{ ref('SrcCseChlBusRejectsDS') }}
)

SELECT * FROM FunCseChlBusNulls