{{ config(materialized='view', tags=['LdMAP_CSE_APPT_PURP_CLAS_CLLkp']) }}

WITH XfmConversions AS (
	SELECT
		-- *SRC*: trim(InMAP_CSE_APPT_PURP_CLAS_CLTera.LOAN_PURP_CLAS_CODE),
		TRIM({{ ref('SrcMAP_CSE_APPT_PURP_CLAS_CLTera') }}.LOAN_PURP_CLAS_CODE) AS LOAN_PURPOSE_CLASS_CODE,
		-- *SRC*: Trim(InMAP_CSE_APPT_PURP_CLAS_CLTera.PURP_CLAS_C),
		TRIM({{ ref('SrcMAP_CSE_APPT_PURP_CLAS_CLTera') }}.PURP_CLAS_C) AS PURP_CLAS_C
	FROM {{ ref('SrcMAP_CSE_APPT_PURP_CLAS_CLTera') }}
	WHERE 
)

SELECT * FROM XfmConversions