SELECT
	PL_APP_ID,
	NOMINATED_BRANCH_ID,
	PL_PACKAGE_CAT_ID
	
FROM {{ ref('srcplappseq__extpl_app') }}

QUALIFY ROW_NUMBER() OVER (PARTITION BY PL_APP_ID ORDER BY PL_APP_ID COLLATE 'en' ASC NULLS FIRST ) = 1