{{ config(materialized='view', tags=['XfmFaEnvisionEventFrmExt']) }}

WITH XfmBusinessRules__OutTgtEnvEventDS AS (
	SELECT
		-- *SRC*: \(20)If (Len(Trim(( IF IsNotNull((ModOut.CREATED_BY_STAFF_NUMBER)) THEN (ModOut.CREATED_BY_STAFF_NUMBER) ELSE ""))) = 0) then 'Y' else 'N',
		IFF(LEN(TRIM(IFF({{ ref('ModEvntActvTypeC') }}.CREATED_BY_STAFF_NUMBER IS NOT NULL, {{ ref('ModEvntActvTypeC') }}.CREATED_BY_STAFF_NUMBER, ''))) = 0, 'Y', 'N') AS svCreatedStaffNull,
		-- *SRC*: \(20)if (Len(trim(( IF IsNotNull((ModOut.FA_ENV_EVNT_CAT_ID)) THEN (ModOut.FA_ENV_EVNT_CAT_ID) ELSE ""))) = 0) then DEFAULT_NULL_VALUE else ModOut.EVNT_ACTV_TYPE_C,
		IFF(LEN(TRIM(IFF({{ ref('ModEvntActvTypeC') }}.FA_ENV_EVNT_CAT_ID IS NOT NULL, {{ ref('ModEvntActvTypeC') }}.FA_ENV_EVNT_CAT_ID, ''))) = 0, DEFAULT_NULL_VALUE, {{ ref('ModEvntActvTypeC') }}.EVNT_ACTV_TYPE_C) AS svEvntActvTypeC,
		-- *SRC*: \(20)If (Len(Trim(( IF IsNotNull((ModOut.CREATED_DATE)) THEN (ModOut.CREATED_DATE) ELSE ""))) = 0) then 'Y' else 'N',
		IFF(LEN(TRIM(IFF({{ ref('ModEvntActvTypeC') }}.CREATED_DATE IS NOT NULL, {{ ref('ModEvntActvTypeC') }}.CREATED_DATE, ''))) = 0, 'Y', 'N') AS CratDateIsNull,
		-- *SRC*: \(20)If CratDateIsNull = 'Y' then 'N' else ( if IsValid('date', StringToDate(trim(ModOut.CREATED_DATE)[1, 8], '%yyyy%mm%dd')) Then 'N' Else 'Y'),
		IFF(CratDateIsNull = 'Y', 'N', IFF(ISVALID('date', STRINGTODATE(SUBSTRING(TRIM({{ ref('ModEvntActvTypeC') }}.CREATED_DATE), 1, 8), '%yyyy%mm%dd')), 'N', 'Y')) AS ErrorCratDate,
		-- *SRC*: \(20)If CratDateIsNull = 'Y' then 'N' else ( if IsValid('time', StringToTime(trim(ModOut.CREATED_DATE)[9, 6], "%hh%nn%ss")) Then 'N' Else 'Y'),
		IFF(CratDateIsNull = 'Y', 'N', IFF(ISVALID('time', STRINGTOTIME(SUBSTRING(TRIM({{ ref('ModEvntActvTypeC') }}.CREATED_DATE), 9, 6), '%hh%nn%ss')), 'N', 'Y')) AS ErrorCratTime,
		-- *SRC*: \(20)If svEvntActvTypeC = '9999' then 'RPR6201' else '',
		IFF(svEvntActvTypeC = '9999', 'RPR6201', '') AS svErrorCode,
		-- *SRC*: \(20)If (svCreatedStaffNull = 'Y' or ModOut.FA_ENV_EVNT_CAT_ID <> '1') then 'N' else  if svUndertaking <> ModOut.FA_UNDERTAKING_ID then 'Y' else 'N',
		IFF(svCreatedStaffNull = 'Y' OR {{ ref('ModEvntActvTypeC') }}.FA_ENV_EVNT_CAT_ID <> '1', 'N', IFF(svUndertaking <> {{ ref('ModEvntActvTypeC') }}.FA_UNDERTAKING_ID, 'Y', 'N')) AS svIntGrupEmplF,
		-- *SRC*: \(20)If svIntGrupEmplF = 'Y' then ModOut.FA_UNDERTAKING_ID else svUndertaking,
		IFF(svIntGrupEmplF = 'Y', {{ ref('ModEvntActvTypeC') }}.FA_UNDERTAKING_ID, svUndertaking) AS svUndertaking,
		-- *SRC*: \(20)If (svCreatedStaffNull = 'Y') then 'N' else 'Y',
		IFF(svCreatedStaffNull = 'Y', 'N', 'Y') AS svEvntEmplF,
		{{ ref('ModEvntActvTypeC') }}.FA_ENVISION_EVENT_ID AS FA_ENV_EVNT_ID,
		{{ ref('ModEvntActvTypeC') }}.FA_UNDERTAKING_ID AS FA_UTAK_ID,
		FA_ENV_EVNT_CAT_ID,
		{{ ref('ModEvntActvTypeC') }}.CREATED_DATE AS CRAT_DATE,
		{{ ref('ModEvntActvTypeC') }}.CREATED_BY_STAFF_NUMBER AS CRAT_BY_STAF_NUM,
		{{ ref('ModEvntActvTypeC') }}.COIN_REQUEST_ID AS COIN_REQ_ID,
		ORIG_ETL_D,
		-- *SRC*: 'CSEC1' : trim(ModOut.FA_ENVISION_EVENT_ID),
		CONCAT('CSEC1', TRIM({{ ref('ModEvntActvTypeC') }}.FA_ENVISION_EVENT_ID)) AS EVNT_I,
		-- *SRC*: 'CSEC1' : ModOut.FA_UNDERTAKING_ID,
		CONCAT('CSEC1', {{ ref('ModEvntActvTypeC') }}.FA_UNDERTAKING_ID) AS INT_GRUP_I,
		-- *SRC*: \(20)If svEvntActvTypeC = DEFAULT_NULL_VALUE then SetNull() else svEvntActvTypeC,
		IFF(svEvntActvTypeC = DEFAULT_NULL_VALUE, SETNULL(), svEvntActvTypeC) AS EVNT_ACTV_TYPE_C,
		'Y' AS BUSN_EVNT_F,
		'N' AS CTCT_EVNT_F,
		'N' AS INVT_EVNT_F,
		'N' AS FNCL_ACCT_EVNT_F,
		'N' AS FNCL_NVAL_EVNT_F,
		'N' AS INCD_F,
		'N' AS INSR_EVNT_F,
		'N' AS INSR_NVAL_EVNT_F,
		0 AS ROW_SECU_ACCS_C,
		{{ ref('ModEvntActvTypeC') }}.FA_ENVISION_EVENT_ID AS SRCE_SYST_EVNT_I,
		-- *SRC*: SetNull(),
		SETNULL() AS SRCE_SYST_EVNT_TYPE_I,
		-- *SRC*: \(20)If ErrorCratDate = 'N' Then StringToDate((trim(ModOut.CREATED_DATE))[1, 8], "%yyyy%mm%dd") Else StringToDate(DEFAULT_DT, "%yyyy%mm%dd"),
		IFF(ErrorCratDate = 'N', STRINGTODATE(TRIM({{ ref('ModEvntActvTypeC') }}.CREATED_DATE), '%yyyy%mm%dd'), STRINGTODATE(DEFAULT_DT, '%yyyy%mm%dd')) AS EVNT_ACTL_D,
		-- *SRC*: \(20)If ErrorCratTime = 'N' Then StringToTime(trim(ModOut.CREATED_DATE)[9, 6], "%hh%nn%ss") Else SetNull(),
		IFF(ErrorCratTime = 'N', STRINGTOTIME(SUBSTRING(TRIM({{ ref('ModEvntActvTypeC') }}.CREATED_DATE), 9, 6), '%hh%nn%ss'), SETNULL()) AS EVNT_ACTL_T,
		'CSE' AS SRCE_SYST_C,
		-- *SRC*: ( IF IsNotNull((ModOut.CREATED_BY_STAFF_NUMBER)) THEN (ModOut.CREATED_BY_STAFF_NUMBER) ELSE ('00000000')),
		IFF({{ ref('ModEvntActvTypeC') }}.CREATED_BY_STAFF_NUMBER IS NOT NULL, {{ ref('ModEvntActvTypeC') }}.CREATED_BY_STAFF_NUMBER, '00000000') AS EMPL_I,
		'OWNG' AS EVNT_PATY_ROLE_TYPE_C,
		'FNP' AS EMPL_ROLE_C,
		svIntGrupEmplF AS INT_GRUP_EMPL_F,
		svEvntEmplF AS EVNT_EMPL_F
	FROM {{ ref('ModEvntActvTypeC') }}
	WHERE 
)

SELECT * FROM XfmBusinessRules__OutTgtEnvEventDS