{{ config(materialized='view', tags=['ExtCclBusApp']) }}

WITH FunMergeJournal AS (
	SELECT
		CCL_APP_ID as CCL_APP_ID,
		CCL_APP_CAT_ID as CCL_APP_CAT_ID,
		CCL_FORM_CAT_ID as CCL_FORM_CAT_ID,
		TOTAL_PERSONAL_FAC_AMT as TOTAL_PERSONAL_FAC_AMT,
		TOTAL_EQUIPMENTFINANCE_FAC_AMT as TOTAL_EQUIPMENTFINANCE_FAC_AMT,
		TOTAL_COMMERCIAL_FAC_AMT as TOTAL_COMMERCIAL_FAC_AMT,
		TOPUP_APP_ID as TOPUP_APP_ID,
		AF_PRIMARY_INDUSTRY_ID as AF_PRIMARY_INDUSTRY_ID,
		AD_TUC_AMT as AD_TUC_AMT,
		COMMISSION_AMT as COMMISSION_AMT,
		BROKER_REFERAL_FLAG as BROKER_REFERAL_FLAG,
		CARNELL_EXPOSURE_AMT as CARNELL_EXPOSURE_AMT,
		CARNELL_EXPOSURE_AMT_DATE as CARNELL_EXPOSURE_AMT_DATE,
		CARNELL_OVERRIDE_COV_ASSESSMNT as CARNELL_OVERRIDE_COV_ASSESSMNT,
		CARNELL_OVERRIDE_REASON_CAT_ID as CARNELL_OVERRIDE_REASON_CAT_ID,
		CARNELL_SHORT_DEFAULT_OVERRIDE as CARNELL_SHORT_DEFAULT_OVERRIDE,
		SRCE_REC as SRCE_REC,
		ORIG_ETL_D as ORIG_ETL_D
	FROM {{ ref('XfmSeparateRejectWithoutSourceAndTheRest__InSourceRec') }}
	UNION ALL
	SELECT
		CCL_APP_ID,
		CCL_APP_CAT_ID,
		CCL_FORM_CAT_ID,
		TOTAL_PERSONAL_FAC_AMT,
		TOTAL_EQUIPMENTFINANCE_FAC_AMT,
		TOTAL_COMMERCIAL_FAC_AMT,
		TOPUP_APP_ID,
		AF_PRIMARY_INDUSTRY_ID,
		AD_TUC_AMT,
		COMMISSION_AMT,
		BROKER_REFERAL_FLAG,
		CARNELL_EXPOSURE_AMT,
		CARNELL_EXPOSURE_AMT_DATE,
		CARNELL_OVERRIDE_COV_ASSESSMNT,
		CARNELL_OVERRIDE_REASON_CAT_ID,
		CARNELL_SHORT_DEFAULT_OVERRIDE,
		SRCE_REC,
		ORIG_ETL_D
	FROM {{ ref('XfmSeparateRejectWithoutSourceAndTheRest__InRejectWithoutSourceRec') }}
)

SELECT * FROM FunMergeJournal