WITH OutCopyNew
AS (
	SELECT NEW_APPT_PDCT_I,
		NEW_DEBT_ABN_X,
		NEW_DEBT_BUSN_M,
		NEW_SMPL_APPT_F,
		NEW_JOB_COMM_CATG_C,
		NEW_APPT_QLFY_C,
		NEW_ACQR_TYPE_C,
		NEW_ACQR_ADHC_X,
		NEW_ACQR_SRCE_C,
		NEW_PDCT_N,
		NEW_APPT_I,
		NEW_SRCE_SYST_C,
		NEW_SRCE_SYST_APPT_PDCT_I,
		NEW_LOAN_FNDD_METH_C,
		NEW_NEW_ACCT_F,
		NEW_BROK_PATY_I,
		NEW_COPY_FROM_OTHR_APPT_F,
		NEW_APPT_PDCT_CATG_C,
		NEW_APPT_PDCT_DURT_C,
		NEW_ASES_D
	
	FROM {{ ref('cpyapptpdct__dltappt_pdctfrmtmp_appt_pdct') }}
	),
OutCopyOld
AS (
	SELECT OLD_APPT_PDCT_I,
		OLD_DEBT_ABN_X,
		OLD_DEBT_BUSN_M,
		OLD_JOB_COMM_CATG_C,
		OLD_APPT_QLFY_C,
		OLD_ACQR_TYPE_C,
		OLD_ACQR_ADHC_X,
		OLD_ACQR_SRCE_C,
		OLD_PDCT_N,
		OLD_APPT_I,
		OLD_SRCE_SYST_C,
		OLD_SRCE_SYST_APPT_PDCT_I,
		OLD_LOAN_FNDD_METH_C,
		OLD_NEW_ACCT_F,
		OLD_BROK_PATY_I,
		OLD_COPY_FROM_OTHR_APPT_F,
		OLD_SMPL_APPT_F,
		OLD_APPT_PDCT_CATG_C,
		OLD_APPT_PDCT_DURT_C,
		OLD_ASES_D
	
	FROM {{ ref('cpyapptpdct__dltappt_pdctfrmtmp_appt_pdct') }}
	),
ChangeCapture
AS (
	SELECT COALESCE(new.NEW_APPT_PDCT_I, old.old_APPT_PDCT_I) AS NEW_APPT_PDCT_I,
		COALESCE(new.NEW_DEBT_ABN_X, old.old_DEBT_ABN_X) AS NEW_DEBT_ABN_X,
		COALESCE(new.NEW_DEBT_BUSN_M, old.old_DEBT_BUSN_M) AS NEW_DEBT_BUSN_M,
		COALESCE(new.NEW_SMPL_APPT_F, old.old_SMPL_APPT_F) AS NEW_SMPL_APPT_F,
		COALESCE(new.NEW_JOB_COMM_CATG_C, old.old_JOB_COMM_CATG_C) AS NEW_JOB_COMM_CATG_C,
		COALESCE(new.NEW_APPT_QLFY_C, old.old_APPT_QLFY_C) AS NEW_APPT_QLFY_C,
		COALESCE(new.NEW_ACQR_TYPE_C, old.old_ACQR_TYPE_C) AS NEW_ACQR_TYPE_C,
		COALESCE(new.NEW_ACQR_ADHC_X, old.old_ACQR_ADHC_X) AS NEW_ACQR_ADHC_X,
		COALESCE(new.NEW_ACQR_SRCE_C, old.old_ACQR_SRCE_C) AS NEW_ACQR_SRCE_C,
		COALESCE(new.NEW_PDCT_N, old.old_PDCT_N) AS NEW_PDCT_N,
		COALESCE(new.NEW_APPT_I, old.old_APPT_I) AS NEW_APPT_I,
		COALESCE(new.NEW_SRCE_SYST_C, old.old_SRCE_SYST_C) AS NEW_SRCE_SYST_C,
		COALESCE(new.NEW_SRCE_SYST_APPT_PDCT_I, old.old_SRCE_SYST_APPT_PDCT_I) AS NEW_SRCE_SYST_APPT_PDCT_I,
		COALESCE(new.NEW_LOAN_FNDD_METH_C, old.old_LOAN_FNDD_METH_C) AS NEW_LOAN_FNDD_METH_C,
		COALESCE(new.NEW_NEW_ACCT_F, old.old_NEW_ACCT_F) AS NEW_NEW_ACCT_F,
		COALESCE(new.NEW_BROK_PATY_I, old.old_BROK_PATY_I) AS NEW_BROK_PATY_I,
		COALESCE(new.NEW_COPY_FROM_OTHR_APPT_F, old.old_COPY_FROM_OTHR_APPT_F) AS NEW_COPY_FROM_OTHR_APPT_F,
		COALESCE(new.NEW_APPT_PDCT_CATG_C, old.old_APPT_PDCT_CATG_C) AS NEW_APPT_PDCT_CATG_C,
		COALESCE(new.NEW_APPT_PDCT_DURT_C, old.old_APPT_PDCT_DURT_C) AS NEW_APPT_PDCT_DURT_C,
		COALESCE(new.NEW_ASES_D, old.old_ASES_D) AS NEW_ASES_D,
		CASE 
			WHEN new.NEW_APPT_PDCT_I IS NULL
				THEN '1'
			WHEN new.NEW_APPT_PDCT_I IS NULL
				THEN '2'
			WHEN (new.NEW_APPT_PDCT_I = old.old_APPT_PDCT_I)
				AND (
					new.NEW_DEBT_ABN_X <> old.old_DEBT_ABN_X
					OR new.NEW_DEBT_BUSN_M <> old.old_DEBT_BUSN_M
					OR new.NEW_JOB_COMM_CATG_C <> old.old_JOB_COMM_CATG_C
					OR new.NEW_APPT_QLFY_C <> old.old_APPT_QLFY_C
					OR new.NEW_ACQR_TYPE_C <> old.old_ACQR_TYPE_C
					OR new.NEW_ACQR_ADHC_X <> old.old_ACQR_ADHC_X
					OR new.NEW_ACQR_SRCE_C <> old.old_ACQR_SRCE_C
					OR new.NEW_PDCT_N <> old.old_PDCT_N
					OR new.NEW_APPT_I <> old.old_APPT_I
					OR new.NEW_SRCE_SYST_C <> old.old_SRCE_SYST_C
					OR new.NEW_SRCE_SYST_APPT_PDCT_I <> old.old_SRCE_SYST_APPT_PDCT_I
					OR new.NEW_LOAN_FNDD_METH_C <> old.old_LOAN_FNDD_METH_C
					OR new.NEW_NEW_ACCT_F <> old.old_NEW_ACCT_F
					OR new.NEW_BROK_PATY_I <> old.old_BROK_PATY_I
					OR new.NEW_COPY_FROM_OTHR_APPT_F <> old.old_COPY_FROM_OTHR_APPT_F
					OR new.NEW_SMPL_APPT_F <> old.old_SMPL_APPT_F
					OR new.NEW_APPT_PDCT_CATG_C <> old.old_APPT_PDCT_CATG_C
					OR new.NEW_APPT_PDCT_DURT_C <> old.old_APPT_PDCT_DURT_C
					OR new.NEW_ASES_D <> old.old_ASES_D
					)
				THEN '3'
			WHEN new.NEW_APPT_PDCT_I = old.old_APPT_PDCT_I
				AND new.NEW_DEBT_ABN_X = old.old_DEBT_ABN_X
				AND new.NEW_DEBT_BUSN_M = old.old_DEBT_BUSN_M
				AND new.NEW_JOB_COMM_CATG_C = old.old_JOB_COMM_CATG_C
				AND new.NEW_APPT_QLFY_C = old.old_APPT_QLFY_C
				AND new.NEW_ACQR_TYPE_C = old.old_ACQR_TYPE_C
				AND new.NEW_ACQR_ADHC_X = old.old_ACQR_ADHC_X
				AND new.NEW_ACQR_SRCE_C = old.old_ACQR_SRCE_C
				AND new.NEW_PDCT_N = old.old_PDCT_N
				AND new.NEW_APPT_I = old.old_APPT_I
				AND new.NEW_SRCE_SYST_C = old.old_SRCE_SYST_C
				AND new.NEW_SRCE_SYST_APPT_PDCT_I = old.old_SRCE_SYST_APPT_PDCT_I
				AND new.NEW_LOAN_FNDD_METH_C = old.old_LOAN_FNDD_METH_C
				AND new.NEW_NEW_ACCT_F = old.old_NEW_ACCT_F
				AND new.NEW_BROK_PATY_I = old.old_BROK_PATY_I
				AND new.NEW_COPY_FROM_OTHR_APPT_F = old.old_COPY_FROM_OTHR_APPT_F
				AND new.NEW_SMPL_APPT_F = old.old_SMPL_APPT_F
				AND new.NEW_APPT_PDCT_CATG_C = old.old_APPT_PDCT_CATG_C
				AND new.NEW_APPT_PDCT_DURT_C = old.old_APPT_PDCT_DURT_C
				AND new.NEW_ASES_D = old.old_ASES_D
				THEN '0'
			END AS change_code
	
	FROM OutCopyOld old
	
	FULL OUTER JOIN OutCopyNew new
		ON new.NEW_APPT_PDCT_I = old.old_APPT_PDCT_I
	)

SELECT *

FROM ChangeCapture