{{ config(materialized='view', tags=['DltAPPT_PDCT_DOCU_DELY_INSSFrmTMP_APPT_PDCT_DOCU_DELY_INSS']) }}

WITH CpyApptDeptEntSeq AS (
	SELECT
		NEW_APPT_PDCT_I,
		NEW_DOCU_DELY_METH_C,
		NEW_PYAD_TYPE_C,
		NEW_ADRS_LINE_1_X,
		NEW_ADRS_LINE_2_X,
		NEW_SURB_X,
		NEW_PCOD_C,
		NEW_STAT_X,
		NEW_ISO_CNTY_C,
		NEW_BRCH_N,
		{{ ref('SrcTmpAPPT_PDCT_DOCU_DELY_INSSTera') }}.OLD_APPT_PDCT_I AS NEW_APPT_PDCT_I,
		{{ ref('SrcTmpAPPT_PDCT_DOCU_DELY_INSSTera') }}.OLD_DOCU_DELY_METH_C AS NEW_DOCU_DELY_METH_C,
		{{ ref('SrcTmpAPPT_PDCT_DOCU_DELY_INSSTera') }}.OLD_PYAD_TYPE_C AS NEW_PYAD_TYPE_C,
		{{ ref('SrcTmpAPPT_PDCT_DOCU_DELY_INSSTera') }}.OLD_ADRS_LINE_1_X AS NEW_ADRS_LINE_1_X,
		{{ ref('SrcTmpAPPT_PDCT_DOCU_DELY_INSSTera') }}.OLD_ADRS_LINE_2_X AS NEW_ADRS_LINE_2_X,
		{{ ref('SrcTmpAPPT_PDCT_DOCU_DELY_INSSTera') }}.OLD_SURB_X AS NEW_SURB_X,
		{{ ref('SrcTmpAPPT_PDCT_DOCU_DELY_INSSTera') }}.OLD_PCOD_C AS NEW_PCOD_C,
		{{ ref('SrcTmpAPPT_PDCT_DOCU_DELY_INSSTera') }}.OLD_STAT_X AS NEW_STAT_X,
		{{ ref('SrcTmpAPPT_PDCT_DOCU_DELY_INSSTera') }}.OLD_ISO_CNTY_C AS NEW_ISO_CNTY_C,
		{{ ref('SrcTmpAPPT_PDCT_DOCU_DELY_INSSTera') }}.OLD_BRCH_N AS NEW_BRCH_N,
		OLD_DOCU_DELY_METH_C,
		OLD_EFFT_D
	FROM {{ ref('SrcTmpAPPT_PDCT_DOCU_DELY_INSSTera') }}
)

SELECT * FROM CpyApptDeptEntSeq