{{ config(materialized='view', tags=['DltAPPT_PDCT_DOCU_DELY_INSSFrmTMP_APPT_PDCT_DOCU_DELY_INSS']) }}

WITH 
tmp_appt_pdct_docu_dely_inss AS (
	SELECT
	*
	FROM {{ ref("tmp_appt_pdct_docu_dely_inss")  }}),
appt_pdct_docu_dely_inss AS (
	SELECT
	*
	FROM {{ ref("appt_pdct_docu_dely_inss")  }}),
SrcTmpAPPT_PDCT_DOCU_DELY_INSSTera AS (SELECT a.APPT_PDCT_I AS NEW_APPT_PDCT_I, a.DOCU_DELY_METH_C AS NEW_DOCU_DELY_METH_C, a.PYAD_TYPE_C AS NEW_PYAD_TYPE_C, a.ADRS_LINE_1_X AS NEW_ADRS_LINE_1_X, a.ADRS_LINE_2_X AS NEW_ADRS_LINE_2_X, a.SURB_X AS NEW_SURB_X, a.PCOD_C AS NEW_PCOD_C, a.STAT_X AS NEW_STAT_X, a.ISO_CNTY_C AS NEW_ISO_CNTY_C, a.BRCH_N AS NEW_BRCH_N, b.APPT_PDCT_I AS OLD_APPT_PDCT_I, b.DOCU_DELY_METH_C AS OLD_DOCU_DELY_METH_C, b.PYAD_TYPE_C AS OLD_PYAD_TYPE_C, b.ADRS_LINE_1_X AS OLD_ADRS_LINE_1_X, b.ADRS_LINE_2_X AS OLD_ADRS_LINE_2_X, b.SURB_X AS OLD_SURB_X, b.PCOD_C AS OLD_PCOD_C, b.STAT_X AS OLD_STAT_X, b.ISO_CNTY_C AS OLD_ISO_CNTY_C, b.BRCH_N AS OLD_BRCH_N, b.EFFT_D AS OLD_EFFT_D FROM TMP_APPT_PDCT_DOCU_DELY_INSS LEFT OUTER JOIN APPT_PDCT_DOCU_DELY_INSS ON TRIM(a.APPT_PDCT_I) = TRIM(b.APPT_PDCT_I) AND b.EXPY_D = '9999-12-31' WHERE a.RUN_STRM = '{{ var("RUN_STREAM") }}')


SELECT * FROM SrcTmpAPPT_PDCT_DOCU_DELY_INSSTera