{{ config(materialized='view', tags=['DltCSE_CMLN_APPT_XPOS_ASES_DETLFrmTMP']) }}

WITH 
tmp_appt_pdct_cpgn AS (
	SELECT
	*
	FROM {{ ref("tmp_appt_pdct_cpgn")  }}),
appt_pdct_cpgn AS (
	SELECT
	*
	FROM {{ ref("appt_pdct_cpgn")  }}),
SrcTmpCseCmlnApptXposAsesDetlTera AS (SELECT A.APPT_I, A.XPOS_A, A.XPOS_AMT_D, A.OVRD_COVTS_ASES_F, A.CSE_CMLN_OVRD_REAS_CATG_C, A.SHRT_DFLT_OVRD_F, CASE WHEN (B.APPT_I IS NULL) THEN A.EFFT_D ELSE B.EFFT_D END AS EFFT_D, A.EXPY_D, CASE WHEN (B.APPT_I IS NULL) THEN 'I' WHEN ((COALESCE(TRIM(A.XPOS_A), 'D') = COALESCE(TRIM(B.XPOS_A), 'D')) AND COALESCE(A.XPOS_AMT_D, CAST('1111-01-01 00:00:00.000000' AS TIMESTAMP(6))) = COALESCE(B.XPOS_AMT_D, CAST('1111-01-01 00:00:00.000000' AS TIMESTAMP(6))) AND (COALESCE(TRIM(A.OVRD_COVTS_ASES_F), 'D') = COALESCE(TRIM(B.OVRD_COVTS_ASES_F), 'D')) AND (COALESCE(TRIM(A.CSE_CMLN_OVRD_REAS_CATG_C), 'D') = COALESCE(TRIM(B.CSE_CMLN_OVRD_REAS_CATG_C), 'D')) AND (COALESCE(TRIM(A.SHRT_DFLT_OVRD_F), 'D') = COALESCE(TRIM(B.SHRT_DFLT_OVRD_F), 'D'))) THEN 'C' ELSE 'U' END AS IND_FLAG FROM TMP_APPT_PDCT_CPGN LEFT OUTER JOIN (SELECT APPT_I, XPOS_A, XPOS_AMT_D, OVRD_COVTS_ASES_F, CSE_CMLN_OVRD_REAS_CATG_C, SHRT_DFLT_OVRD_F, EFFT_D, EXPY_D FROM APPT_PDCT_CPGN WHERE EXPY_D = '9999-12-31') AS B ON A.APPT_I = B.APPT_I WHERE IND_FLAG <> 'C')


SELECT * FROM SrcTmpCseCmlnApptXposAsesDetlTera