{{ config(materialized='view', tags=['LdREJT_COM_BUS_SM_CASE_STATE']) }}

WITH Funnel_93 AS (
	SELECT
		SM_CASE_STATE_ID as SM_CASE_STATE_ID,
		SM_CASE_ID as SM_CASE_ID,
		SM_STATE_CAT_ID as SM_STATE_CAT_ID,
		START_DATE as START_DATE,
		END_DATE as END_DATE,
		CREATED_BY_STAFF_NUMBER as CREATED_BY_STAFF_NUMBER,
		STATE_CAUSED_BY_ACTION_ID as STATE_CAUSED_BY_ACTION_ID,
		ETL_D as ETL_D,
		ORIG_ETL_D as ORIG_ETL_D,
		EROR_C as EROR_C
	FROM {{ ref('SrcBusSmCaseStatIdNullsDS') }}
	UNION ALL
	SELECT
		SM_CASE_STATE_ID,
		SM_CASE_ID,
		SM_STATE_CAT_ID,
		START_DATE,
		END_DATE,
		CREATED_BY_STAFF_NUMBER,
		STATE_CAUSED_BY_ACTION_ID,
		ETL_D,
		ORIG_ETL_D,
		EROR_C
	FROM {{ ref('SrcMappingRejectsDS') }}
)

SELECT * FROM Funnel_93