{{ config(materialized='view', tags=['XfmAntn']) }}

WITH XfmTrans AS (
	SELECT
		-- *SRC*: 'CSE' : 'A5' : FrmSrc.OL_CLIENT_RM_RATING_ID,
		CONCAT(CONCAT('CSE', 'A5'), {{ ref('CSE_ONLN_BUS_OL_CLNT_RM_RATE_CMMT') }}.OL_CLIENT_RM_RATING_ID) AS svAntnI,
		-- *SRC*: StringToTime(FrmSrc.MOD_TIMESTAMP[9, 2] : ':' : FrmSrc.MOD_TIMESTAMP[11, 2] : ':' : FrmSrc.MOD_TIMESTAMP[13, 2], '%hh:%nn:%ss'),
		STRINGTOTIME(CONCAT(CONCAT(CONCAT(CONCAT(SUBSTRING({{ ref('CSE_ONLN_BUS_OL_CLNT_RM_RATE_CMMT') }}.MOD_TIMESTAMP, 9, 2), ':'), SUBSTRING({{ ref('CSE_ONLN_BUS_OL_CLNT_RM_RATE_CMMT') }}.MOD_TIMESTAMP, 11, 2)), ':'), SUBSTRING({{ ref('CSE_ONLN_BUS_OL_CLNT_RM_RATE_CMMT') }}.MOD_TIMESTAMP, 13, 2)), '%hh:%nn:%ss') AS svAntnAcltT,
		-- *SRC*: StringToDate(FrmSrc.MOD_TIMESTAMP[1, 4] : '-' : FrmSrc.MOD_TIMESTAMP[5, 2] : '-' : FrmSrc.MOD_TIMESTAMP[7, 2], "%yyyy-%mm-%dd"),
		STRINGTODATE(CONCAT(CONCAT(CONCAT(CONCAT(SUBSTRING({{ ref('CSE_ONLN_BUS_OL_CLNT_RM_RATE_CMMT') }}.MOD_TIMESTAMP, 1, 4), '-'), SUBSTRING({{ ref('CSE_ONLN_BUS_OL_CLNT_RM_RATE_CMMT') }}.MOD_TIMESTAMP, 5, 2)), '-'), SUBSTRING({{ ref('CSE_ONLN_BUS_OL_CLNT_RM_RATE_CMMT') }}.MOD_TIMESTAMP, 7, 2)), '%yyyy-%mm-%dd') AS svAntnActlD,
		svAntnI AS ANTN_I,
		'RMCO' AS ANTN_TYPE_C,
		{{ ref('CSE_ONLN_BUS_OL_CLNT_RM_RATE_CMMT') }}.COMMENTS AS ANTN_X,
		'CSE' AS SRCE_SYST_C,
		{{ ref('CSE_ONLN_BUS_OL_CLNT_RM_RATE_CMMT') }}.OL_CLIENT_RM_RATING_ID AS SRCE_SYST_ANTN_I,
		-- *SRC*: StringToTimestamp(FrmSrc.MOD_TIMESTAMP[1, 4] : '-' : FrmSrc.MOD_TIMESTAMP[5, 2] : '-' : FrmSrc.MOD_TIMESTAMP[7, 2] : ' ' : FrmSrc.MOD_TIMESTAMP[9, 2] : ':' : FrmSrc.MOD_TIMESTAMP[11, 2] : ':' : FrmSrc.MOD_TIMESTAMP[13, 2], "%yyyy-%mm-%dd %hh:%nn:%ss"),
		STRINGTOTIMESTAMP(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(SUBSTRING({{ ref('CSE_ONLN_BUS_OL_CLNT_RM_RATE_CMMT') }}.MOD_TIMESTAMP, 1, 4), '-'), SUBSTRING({{ ref('CSE_ONLN_BUS_OL_CLNT_RM_RATE_CMMT') }}.MOD_TIMESTAMP, 5, 2)), '-'), SUBSTRING({{ ref('CSE_ONLN_BUS_OL_CLNT_RM_RATE_CMMT') }}.MOD_TIMESTAMP, 7, 2)), ' '), SUBSTRING({{ ref('CSE_ONLN_BUS_OL_CLNT_RM_RATE_CMMT') }}.MOD_TIMESTAMP, 9, 2)), ':'), SUBSTRING({{ ref('CSE_ONLN_BUS_OL_CLNT_RM_RATE_CMMT') }}.MOD_TIMESTAMP, 11, 2)), ':'), SUBSTRING({{ ref('CSE_ONLN_BUS_OL_CLNT_RM_RATE_CMMT') }}.MOD_TIMESTAMP, 13, 2)), '%yyyy-%mm-%dd %hh:%nn:%ss') AS ANTN_S,
		svAntnActlD AS ANTN_D,
		svAntnAcltT AS ANTN_T,
		-- *SRC*: SetNull(),
		SETNULL() AS EMPL_I,
		-- *SRC*: SetNull(),
		SETNULL() AS USER_I,
		'Y' AS PRVT_F,
		-- *SRC*: SetNull(),
		SETNULL() AS EROR_SEQN_I
	FROM {{ ref('CSE_ONLN_BUS_OL_CLNT_RM_RATE_CMMT') }}
	WHERE 
)

SELECT * FROM XfmTrans