{{ config(materialized='view', tags=['ExtCclAppProd']) }}

WITH JoinSrcSortReject AS (
	SELECT
		{{ ref('XfmCheckIdNulls__OutCheckIdNullsSorted') }}.CCL_APP_PROD_ID,
		{{ ref('XfmCheckIdNulls__OutCheckIdNullsSorted') }}.PARENT_CCL_APP_PROD_ID,
		{{ ref('XfmCheckIdNulls__OutCheckIdNullsSorted') }}.ACCOUNT_NUMBER,
		{{ ref('XfmCheckIdNulls__OutCheckIdNullsSorted') }}.ACTUAL_RATE,
		{{ ref('XfmCheckIdNulls__OutCheckIdNullsSorted') }}.BALLOON_PAY_AMT,
		{{ ref('XfmCheckIdNulls__OutCheckIdNullsSorted') }}.BASIS_TYPE_CAT_ID,
		{{ ref('XfmCheckIdNulls__OutCheckIdNullsSorted') }}.INTEREST_RATE_MARGIN,
		{{ ref('XfmCheckIdNulls__OutCheckIdNullsSorted') }}.LOAN_TERM_MTH_NUM,
		{{ ref('XfmCheckIdNulls__OutCheckIdNullsSorted') }}.CURRENT_LIMIT,
		{{ ref('XfmCheckIdNulls__OutCheckIdNullsSorted') }}.INC_DEC_AMT,
		{{ ref('XfmCheckIdNulls__OutCheckIdNullsSorted') }}.POST_APP_AMT,
		{{ ref('XfmCheckIdNulls__OutCheckIdNullsSorted') }}.NEW_PROD_FLAG,
		{{ ref('XfmCheckIdNulls__OutCheckIdNullsSorted') }}.INDEX_RATE,
		{{ ref('XfmCheckIdNulls__OutCheckIdNullsSorted') }}.INTEREST_ADV_FLAG,
		{{ ref('XfmCheckIdNulls__OutCheckIdNullsSorted') }}.INTERESTONLY_TERM_MTH_NUM,
		{{ ref('XfmCheckIdNulls__OutCheckIdNullsSorted') }}.CAPPED_TERM_MTH_NUM,
		{{ ref('XfmCheckIdNulls__OutCheckIdNullsSorted') }}.CAPPED_RATE,
		{{ ref('XfmCheckIdNulls__OutCheckIdNullsSorted') }}.CRIS_PRODUCT_ID,
		{{ ref('XfmCheckIdNulls__OutCheckIdNullsSorted') }}.CCL_LOAN_PURPOSE_ID,
		{{ ref('XfmCheckIdNulls__OutCheckIdNullsSorted') }}.NEW_PROD_SUBTYPE_FLAG,
		{{ ref('XfmCheckIdNulls__OutCheckIdNullsSorted') }}.TEMP_EXCESS_MTHS,
		{{ ref('XfmCheckIdNulls__OutCheckIdNullsSorted') }}.LOAN_PURPOSE_CLASS_CODE,
		{{ ref('XfmCheckIdNulls__OutCheckIdNullsSorted') }}.CCL_INTEREST_RATE_CAT_ID,
		{{ ref('XfmCheckIdNulls__OutCheckIdNullsSorted') }}.CRR,
		{{ ref('XfmCheckIdNulls__OutCheckIdNullsSorted') }}.AD_TUC_INC_AMT,
		{{ ref('XfmCheckIdNulls__OutCheckIdNullsSorted') }}.CCL_RATE_TYPE_CAT_ID,
		{{ ref('XfmCheckIdNulls__OutCheckIdNullsSorted') }}.LINK_CCL_APP_ID,
		{{ ref('XfmCheckIdNulls__OutCheckIdNullsSorted') }}.LINK_CCL_APP_PROD_ID,
		{{ ref('XfmCheckIdNulls__OutCheckIdNullsSorted') }}.CHL_LMI_AMT,
		{{ ref('XfmCheckIdNulls__OutCheckIdNullsSorted') }}.USED_IN_EXPOSURE_VIEW_FLAG,
		{{ ref('XfmCheckIdNulls__OutCheckIdNullsSorted') }}.CCL_APP_BROKER_CIF_CODE,
		{{ ref('XfmCheckIdNulls__OutCheckIdNullsSorted') }}.APP_ID,
		{{ ref('XfmCheckIdNulls__OutCheckIdNullsSorted') }}.FIXED_INT_START_DATE,
		{{ ref('XfmCheckIdNulls__OutCheckIdNullsSorted') }}.CHILD_PRODUCT_LEVEL_CAT_ID,
		{{ ref('XfmCheckIdNulls__OutCheckIdNullsSorted') }}.PARENT_PRODUCT_LEVEL_CAT_ID,
		{{ ref('CpyRejtRejectOra') }}.CCL_APP_PROD_ID AS CCL_APP_PROD_ID_R,
		{{ ref('CpyRejtRejectOra') }}.PARENT_CCL_APP_PROD_ID_R,
		{{ ref('CpyRejtRejectOra') }}.ACCOUNT_NUMBER_R,
		{{ ref('CpyRejtRejectOra') }}.ACTUAL_RATE_R,
		{{ ref('CpyRejtRejectOra') }}.BALLOON_PAY_AMT_R,
		{{ ref('CpyRejtRejectOra') }}.BASIS_TYPE_CAT_ID_R,
		{{ ref('CpyRejtRejectOra') }}.INTEREST_RATE_MARGIN_R,
		{{ ref('CpyRejtRejectOra') }}.LOAN_TERM_MTH_NUM_R,
		{{ ref('CpyRejtRejectOra') }}.CURRENT_LIMIT_R,
		{{ ref('CpyRejtRejectOra') }}.INC_DEC_AMT_R,
		{{ ref('CpyRejtRejectOra') }}.POST_APP_AMT_R,
		{{ ref('CpyRejtRejectOra') }}.NEW_PROD_FLAG_R,
		{{ ref('CpyRejtRejectOra') }}.INDEX_RATE_R,
		{{ ref('CpyRejtRejectOra') }}.INTEREST_ADV_FLAG_R,
		{{ ref('CpyRejtRejectOra') }}.INTERESTONLY_TERM_MTH_NUM_R,
		{{ ref('CpyRejtRejectOra') }}.CAPPED_TERM_MTH_NUM_R,
		{{ ref('CpyRejtRejectOra') }}.CAPPED_RATE_R,
		{{ ref('CpyRejtRejectOra') }}.CRIS_PRODUCT_ID_R,
		{{ ref('CpyRejtRejectOra') }}.CCL_LOAN_PURPOSE_ID_R,
		{{ ref('CpyRejtRejectOra') }}.NEW_PROD_SUBTYPE_FLAG_R,
		{{ ref('CpyRejtRejectOra') }}.TEMP_EXCESS_MTHS_R,
		{{ ref('CpyRejtRejectOra') }}.LOAN_PURPOSE_CLASS_CODE_R,
		{{ ref('CpyRejtRejectOra') }}.CCL_INTEREST_RATE_CAT_ID_R,
		{{ ref('CpyRejtRejectOra') }}.CRR_R,
		{{ ref('CpyRejtRejectOra') }}.AD_TUC_INC_AMT_R,
		{{ ref('CpyRejtRejectOra') }}.CCL_RATE_TYPE_CAT_ID_R,
		{{ ref('CpyRejtRejectOra') }}.LINK_CCL_APP_ID_R,
		{{ ref('CpyRejtRejectOra') }}.LINK_CCL_APP_PROD_ID_R,
		{{ ref('CpyRejtRejectOra') }}.CHL_LMI_AMT_R,
		{{ ref('CpyRejtRejectOra') }}.USED_IN_EXPOSURE_VIEW_FLAG_R,
		{{ ref('CpyRejtRejectOra') }}.CCL_APP_BROKER_CIF_CODE_R,
		{{ ref('CpyRejtRejectOra') }}.APP_ID_R,
		{{ ref('CpyRejtRejectOra') }}.FIXED_INT_START_DATE_R,
		{{ ref('CpyRejtRejectOra') }}.CHILD_PRODUCT_LEVEL_CAT_ID_R,
		{{ ref('CpyRejtRejectOra') }}.PARENT_PRODUCT_LEVEL_CAT_ID_R,
		{{ ref('CpyRejtRejectOra') }}.ORIG_ETL_D_R
	FROM {{ ref('XfmCheckIdNulls__OutCheckIdNullsSorted') }}
	OUTER JOIN {{ ref('CpyRejtRejectOra') }} ON {{ ref('XfmCheckIdNulls__OutCheckIdNullsSorted') }}.CCL_APP_PROD_ID = {{ ref('CpyRejtRejectOra') }}.CCL_APP_PROD_ID
)

SELECT * FROM JoinSrcSortReject