{{ config(materialized='view', tags=['ExtWRK_APPT_PDCT_FEAT_HL_FEE_DISCFrmStg']) }}

WITH 
wrk_appt_pdct_feat_hl_fee_disc AS (
	SELECT
	*
	FROM {{ ref("wrk_appt_pdct_feat_hl_fee_disc")  }}),
SrcWrkTera AS (SELECT APPT_PDCT_I, FEAT_I, SRCE_SYST_APPT_FEAT_I, EFFT_D, SRCE_SYST_C, SRCE_SYST_APPT_OVRD_I, OVRD_FEAT_I, SRCE_SYST_STND_VALU_Q, SRCE_SYST_STND_VALU_R, SRCE_SYST_STND_VALU_A, CNCY_C, ACTL_VALU_Q, ACTL_VALU_R, ACTL_VALU_A, EXPY_D, FEAT_SEQN_N, FEAT_STRT_D, FEE_CHRG_D, OVRD_REAS_C, FEE_ADD_TO_TOTL_F, FEE_CAPL_F, PROS_KEY_EFFT_I, PROS_KEY_EXPY_I, EROR_SEQN_I, HL_FEE_ID, BF_HL_FEE_ID, BF_HL_APP_PROD_ID, BF_XML_CODE, BF_DISPLAY_NAME, BF_CATEGORY, BF_UNIT_AMOUNT, BF_TOTAL_AMOUNT, BF_FOUND_FLAG, BFD_HL_FEE_DISCOUNT_ID, BFD_HL_FEE_ID, BFD_DISCOUNT_REASON, BFD_DISCOUNT_CODE, BFD_DISCOUNT_AMT, BFD_DISCOUNT_TERM, BFD_HL_FEE_DISCOUNT_CAT_ID, BFD_FOUND_FLAG, ORIG_ETL_D, CASE WHEN (BF_FOUND_FLAG = 'N' AND APPT_PDCT_I = 'CSEHL0x0') THEN 'Y' ELSE 'N' END AS REJECT_FLAG, '{{ var("RUN_STREAM") }}' AS RUN_STREAM FROM WRK_APPT_PDCT_FEAT_HL_FEE_DISC)


SELECT * FROM SrcWrkTera