
-- -- 1. Clustering and Partitioning
-- -- Cluster the large tables on TTS_TRAN_DATE_ALT and CHL_ID_OB_USERID/SSX_CUST_NUM since these are your primary filter columns
-- -- Consider automatic clustering for these tables given their size

-- --FIND WHETHER THERE IS ANY CLUSTERING APPLIED ON THESE TABLES
-- SELECT
--     TABLE_SCHEMA,
--     TABLE_NAME,
--     CLUSTERING_KEY,
--     AUTO_CLUSTERING_ON
-- FROM
--     NEXTHINK.INFORMATION_SCHEMA.TABLES
-- WHERE
--     TABLE_NAME = 'DIM_APPLICATIONS'
--     AND TABLE_SCHEMA = 'CURATED' ;

-- --FIND CLUSTERING EFFECTIVENESS
-- /*
-- This is the most powerful function for understanding the actual physical clustering of your data on specific columns, whether or not they are defined as clustering keys. This function returns a JSON object with detailed metrics about overlap, depth, and the constant state of micro-partitions.

-- Specify Columns in Parentheses: Provide the columns you want to assess the clustering for, even if they are not part of the defined clustering key. If you want to check the defined clustering key, you'd specify those columns.
-- */
-- SELECT SYSTEM$CLUSTERING_INFORMATION('NEXTHINK.CURATED.DIM_APPLICATIONS', '(ID)');
-- SELECT SYSTEM$CLUSTERING_INFORMATION('NEXTHINK.CURATED.DIM_APPLICATIONS', '(BINARY_PRODUCT_NAME, BINARY_NAME)');

-- select SYSTEM$CLUSTERING_INFORMATION('NEXTHINK.CURATED.DIM_APPLICATIONS', '(CONCAT(BINARY_PRODUCT_NAME, '' '', BINARY_NAME))') AS clustering_info;
-- select SYSTEM$CLUSTERING_INFORMATION('LCL.FDP_DIGITAL_MONETARY_TRANSACTIONS_SEND_FLAT', '(CONCAT(TTS_TRAN_DATE_ALT, '' '', TTS_TRAN_TIME_ALT))') AS clustering_info;




-- =====================================================================================
-- SECTION 1: CHECK EXISTING CLUSTERING
-- =====================================================================================

SELECT
    TABLE_CATALOG,
    TABLE_SCHEMA,
    TABLE_NAME,
    TABLE_TYPE,
    CLUSTERING_KEY,
    ROW_COUNT,
    BYTES,
    RETENTION_TIME,
    CREATED,
    LAST_ALTERED,
    AUTO_CLUSTERING_ON,
    COMMENT
FROM
    PRD_P01_DMN_FRAUMD.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'LCL' 
  AND TABLE_NAME IN (
    'FDP_CUSTOMER_TRANSACTIONS_SEND_FLAT',
    'FDP_DIGITAL_MONETARY_TRANSACTIONS_SEND_FLAT'
  );


-- Check clustering information from ACCOUNT_USAGE (if available)
SELECT 
    TABLE_NAME,
    CLUSTERING_KEY,
    TOTAL_PARTITION_COUNT,
    TOTAL_CONSTANT_PARTITION_COUNT,
    AVERAGE_OVERLAPS,
    AVERAGE_DEPTH,
    PARTITION_DEPTH_HISTOGRAM
FROM SNOWFLAKE.ACCOUNT_USAGE.TABLES 
WHERE TABLE_SCHEMA = 'LCL' 
  AND TABLE_NAME IN (
    'FDP_CUSTOMER_TRANSACTIONS_SEND_FLAT',
    'FDP_DIGITAL_MONETARY_TRANSACTIONS_SEND_FLAT'
  )
  AND DELETED IS NULL;

-- =====================================================================================
-- SECTION 2: CLUSTERING EFFECTIVENESS ANALYSIS
-- =====================================================================================


SELECT 
    'NPP_EVENTS_DATE_ONLY_CLUSTERING' AS analysis_type,
    SYSTEM$CLUSTERING_INFORMATION('PRD_P01_DMN_FRAUMD.LCL.FDP_CUSTOMER_TRANSACTIONS_SEND_FLAT', '(TTS_TRAN_DATE_ALT)') AS clustering_info;
SELECT 
    'NPP_EVENTS_NETBANK_ID_CLUSTERING' AS analysis_type,
    SYSTEM$CLUSTERING_INFORMATION('PRD_P01_DMN_FRAUMD.LCL.FDP_CUSTOMER_TRANSACTIONS_SEND_FLAT', '(CHL_ID_OB_USERID)') AS clustering_info;
SELECT 
    'NPP_EVENTS_CUSTOMER_ID_CLUSTERING' AS analysis_type,
    SYSTEM$CLUSTERING_INFORMATION('PRD_P01_DMN_FRAUMD.LCL.FDP_CUSTOMER_TRANSACTIONS_SEND_FLAT', '(SSX_CUST_NUM)') AS clustering_info;
SELECT 
    'NPP_EVENTS_DATE_NETBANK_ID_CLUSTERING' AS analysis_type,
    SYSTEM$CLUSTERING_INFORMATION('PRD_P01_DMN_FRAUMD.LCL.FDP_CUSTOMER_TRANSACTIONS_SEND_FLAT', '(TTS_TRAN_DATE_ALT, CHL_ID_OB_USERID)') AS clustering_info;
SELECT 
    'NPP_EVENTS_DATE_CUSTOMER_ID_CLUSTERING' AS analysis_type,
    SYSTEM$CLUSTERING_INFORMATION('PRD_P01_DMN_FRAUMD.LCL.FDP_CUSTOMER_TRANSACTIONS_SEND_FLAT', '(TTS_TRAN_DATE_ALT, SSX_CUST_NUM)') AS clustering_info;
SELECT 
    'NPP_EVENTS_DATE_TIME_CLUSTERING' AS analysis_type,
    SYSTEM$CLUSTERING_INFORMATION('PRD_P01_DMN_FRAUMD.LCL.FDP_CUSTOMER_TRANSACTIONS_SEND_FLAT', '(TTS_TRAN_DATE_ALT, TTS_TRAN_TIME_ALT)') AS clustering_info;
SELECT 
    'NPP_EVENTS_DATE_TIME_CLUSTERING' AS analysis_type,
    SYSTEM$CLUSTERING_INFORMATION('PRD_P01_DMN_FRAUMD.LCL.FDP_CUSTOMER_TRANSACTIONS_SEND_FLAT', '(CONCAT(TTS_TRAN_DATE_ALT, '' '', TTS_TRAN_TIME_ALT))') AS clustering_info;

   
SELECT 
    'NPP_EVENTS_DATE_ONLY_CLUSTERING2' AS analysis_type,
    SYSTEM$CLUSTERING_INFORMATION('PRD_P01_DMN_FRAUMD.LCL.FDP_DIGITAL_MONETARY_TRANSACTIONS_SEND_FLAT', '(TTS_TRAN_DATE_ALT)') AS clustering_info;
SELECT 
    'NPP_EVENTS_NETBANK_ID_CLUSTERING2' AS analysis_type,
    SYSTEM$CLUSTERING_INFORMATION('PRD_P01_DMN_FRAUMD.LCL.FDP_DIGITAL_MONETARY_TRANSACTIONS_SEND_FLAT', '(CHL_ID_OB_USERID)') AS clustering_info;
SELECT 
    'NPP_EVENTS_CUSTOMER_ID_CLUSTERING2' AS analysis_type,
    SYSTEM$CLUSTERING_INFORMATION('PRD_P01_DMN_FRAUMD.LCL.FDP_DIGITAL_MONETARY_TRANSACTIONS_SEND_FLAT', '(SSX_CUST_NUM)') AS clustering_info;
SELECT 
    'NPP_EVENTS_DATE_NETBANK_ID_CLUSTERING2' AS analysis_type,
    SYSTEM$CLUSTERING_INFORMATION('PRD_P01_DMN_FRAUMD.LCL.FDP_DIGITAL_MONETARY_TRANSACTIONS_SEND_FLAT', '(TTS_TRAN_DATE_ALT, CHL_ID_OB_USERID)') AS clustering_info;
SELECT 
    'NPP_EVENTS_DATE_CUSTOMER_ID_CLUSTERING2' AS analysis_type,
    SYSTEM$CLUSTERING_INFORMATION('PRD_P01_DMN_FRAUMD.LCL.FDP_DIGITAL_MONETARY_TRANSACTIONS_SEND_FLAT', '(TTS_TRAN_DATE_ALT, SSX_CUST_NUM)') AS clustering_info;
SELECT 
    'NPP_EVENTS_DATE_TIME_CLUSTERING2' AS analysis_type,
    SYSTEM$CLUSTERING_INFORMATION('PRD_P01_DMN_FRAUMD.LCL.FDP_DIGITAL_MONETARY_TRANSACTIONS_SEND_FLAT', '(TTS_TRAN_DATE_ALT, TTS_TRAN_TIME_ALT)') AS clustering_info;
SELECT 
    'NPP_EVENTS_DATE_TIME_CLUSTERING2' AS analysis_type,
    SYSTEM$CLUSTERING_INFORMATION('PRD_P01_DMN_FRAUMD.LCL.FDP_DIGITAL_MONETARY_TRANSACTIONS_SEND_FLAT', '(CONCAT(TTS_TRAN_DATE_ALT, '' '', TTS_TRAN_TIME_ALT))') AS clustering_info;
   