{{ config(materialized='view', tags=['ExtCSE_CCL_BUS_APP_FEE']) }}

WITH CpyRejtJournalRejectOra AS (
	SELECT
		CCL_APP_FEE_ID,
		{{ ref('SrcRejtCCL_APP_FEERejectOra') }}.CCL_APP_FEE_CCL_APP_ID AS CCL_APP_FEE_CCL_APP_ID_R,
		{{ ref('SrcRejtCCL_APP_FEERejectOra') }}.CCL_APP_FEE_CCL_APP_PROD_ID AS CCL_APP_FEE_CCL_APP_PROD_ID_R,
		{{ ref('SrcRejtCCL_APP_FEERejectOra') }}.CCL_APP_FEE_CHARGE_AMT AS CCL_APP_FEE_CHARGE_AMT_R,
		{{ ref('SrcRejtCCL_APP_FEERejectOra') }}.CCL_APP_FEE_CHARGE_DATE AS CCL_APP_FEE_CHARGE_DATE_R,
		{{ ref('SrcRejtCCL_APP_FEERejectOra') }}.CCL_APP_FEE_CONCESSION_FLAG AS CCL_APP_FEE_CONCESSION_FLAG_R,
		{{ ref('SrcRejtCCL_APP_FEERejectOra') }}.CCL_APP_FEE_CONCESSION_REASON AS CCL_APP_FEE_CONCESSION_REASON_R,
		{{ ref('SrcRejtCCL_APP_FEERejectOra') }}.CCL_APP_FEE_OVRRD_FEE_PCT AS CCL_APP_FEE_OVERRIDE_FEE_PCT_R,
		{{ ref('SrcRejtCCL_APP_FEERejectOra') }}.CCL_APP_FEE_OVRRD_FEE_PCT_FREQ AS CCL_APP_FEE_OVERRIDE_FEE_PCT_FREQ_R,
		{{ ref('SrcRejtCCL_APP_FEERejectOra') }}.CCL_APP_FEE_FEE_REPAYMENT_FREQ AS CCL_APP_FEE_FEE_REPAYMENT_FREQ_R,
		{{ ref('SrcRejtCCL_APP_FEERejectOra') }}.CCL_APP_FEE_TYPE_CAT_ID AS CCL_APP_FEE_TYPE_CAT_ID_R,
		{{ ref('SrcRejtCCL_APP_FEERejectOra') }}.CCL_APP_FEE_CHRGE_EXTERNL_FLAG AS CCL_APP_FEE_CHARGE_EXTERNAL_FLAG_R,
		{{ ref('SrcRejtCCL_APP_FEERejectOra') }}.CCL_FEE_TYPE_CAT_ID AS CCL_FEE_TYPE_CAT_ID_R,
		{{ ref('SrcRejtCCL_APP_FEERejectOra') }}.CCL_FEE_TYPE_CAT_DEFAULT_AMT AS CCL_FEE_TYPE_CAT_DEFAULT_AMT_R,
		{{ ref('SrcRejtCCL_APP_FEERejectOra') }}.CCL_FEE_TYPE_CAT_DFLT_FEE_PCT AS CCL_FEE_TYPE_CAT_DEFAULT_FEE_PCT_R,
		{{ ref('SrcRejtCCL_APP_FEERejectOra') }}.CCL_FEE_TYPE_CAT_FEE_TYPE_DESC AS CCL_FEE_TYPE_CAT_FEE_TYPE_DESC_R,
		{{ ref('SrcRejtCCL_APP_FEERejectOra') }}.ORIG_ETL_D AS ORIG_ETL_D_R
	FROM {{ ref('SrcRejtCCL_APP_FEERejectOra') }}
)

SELECT * FROM CpyRejtJournalRejectOra