{{ config(materialized='view', tags=['ExtCSE_CCL_BUS_APP_FEE']) }}

WITH 
rejt_ccl_app_fee_fee_type_cat AS (
	SELECT
	*
	FROM {{ source("cse4_stg","rejt_ccl_app_fee_fee_type_cat")  }}),
SrcRejtCCL_APP_FEERejectOra AS (SELECT CCL_APP_FEE_ID, CCL_APP_FEE_CCL_APP_ID, CCL_APP_FEE_CCL_APP_PROD_ID, CCL_APP_FEE_CHARGE_AMT, CCL_APP_FEE_CHARGE_DATE, CCL_APP_FEE_CONCESSION_FLAG, CCL_APP_FEE_CONCESSION_REASON, CCL_APP_FEE_OVRRD_FEE_PCT, CCL_APP_FEE_OVRRD_FEE_PCT_FREQ, CCL_APP_FEE_FEE_REPAYMENT_FREQ, CCL_APP_FEE_TYPE_CAT_ID, CCL_APP_FEE_CHRGE_EXTERNL_FLAG, CCL_FEE_TYPE_CAT_ID, CCL_FEE_TYPE_CAT_DEFAULT_AMT, CCL_FEE_TYPE_CAT_DFLT_FEE_PCT, CCL_FEE_TYPE_CAT_FEE_TYPE_DESC, CAST(ORIG_ETL_D AS TEXT) AS ORIG_ETL_D FROM REJT_CCL_APP_FEE_FEE_TYPE_CAT WHERE EROR_C LIKE 'RPR%')


SELECT * FROM SrcRejtCCL_APP_FEERejectOra