{{ config(materialized='view', tags=['XfmReasonSmCaseStateFrmExt']) }}

WITH ModNullHandling AS (
	SELECT 
	--Manual
	--STUS_C: string[4]= handle_null (STUS_C, '9999')
	--STUS_REAS_TYPE_C: string[4]= handle_null (STUS_REAS_TYPE_C, '9999')
	--SCS_END_DATE : string[max=25]= handle_null (SCS_END_DATE, '9999')
	SM_CASE_STATE_ID, SM_CASE_ID, SM_STATE_CAT_ID, SCS_START_DATE, SCS_END_DATE, SCS_CREATED_BY_STAFF_NUMBER, SCS_STATE_CAUSED_BY_ACTION_ID, SCSR_SM_CASE_STATE_REASON_ID, SM_REASON_CAT_ID AS SM_REAS_CAT_ID, SM_CASE_STATE_REAS_FOUND_FLAG, SM_CASE_STATE_FOUND_FLAG, ORIG_ETL_D, STUS_REAS_TYPE_C, STUS_C, TARG_I, TARG_SUBJ 
	FROM {{ ref('LkpReferences') }}
)

SELECT * FROM ModNullHandling