{{ config(materialized='view', tags=['ExtCSE_CHL_BUS_TU_APP_FUND_DET']) }}

WITH 
rejt_cse_chl_tu_app_fund_det AS (
	SELECT
	*
	FROM {{ source("hltu_stg","rejt_cse_chl_tu_app_fund_det")  }}),
SrcRejtApptRelRejectOra AS (SELECT TU_APP_ID, FUNDING_DATE, TU_APP_FUNDING_DETAIL_ID, TU_APP_FUNDING_ID, FUNDING_CBA_ACCOUNT_ID, FUNDING_NONCBA_INSTITUTION_ID, FUNDING_NONCBA_INST_NAME, FUNDING_NONCBA_INST_ADDRESS, FUNDING_NONCBA_BSB, FUNDING_NONCBA_ACCOUNT_NUMBER, FUNDING_NONCBA_ACCOUNT_NAME, FUNDING_BANKCHEQUE_NUMBER, FUNDING_BANKCHEQUE_PAYEE, FUNDING_METHOD_CAT_ID, FUNDING_BANKCHEQUE_CBAACCOUNT, PROGRESSIVE_PAYMENT_AMT, SBTY_CODE, HL_APP_PROD_ID, CAST(ORIG_ETL_D AS TEXT) AS ORIG_ETL_D FROM REJT_CSE_CHL_TU_APP_FUND_DET WHERE EROR_C LIKE 'RPR%')


SELECT * FROM SrcRejtApptRelRejectOra