{{ config(materialized='view', tags=['DltApptPdctFeatFrmTMP']) }}

WITH 
tmp_appt_pdct_feat AS (
	SELECT
	*
	FROM {{ ref("tmp_appt_pdct_feat")  }}),
Appt_Pdct_Feat_Trans AS (SELECT APPT_PDCT_I, FEAT_I, SRCE_SYST_APPT_FEAT_I, EFFT_D, SRCE_SYST_C, SRCE_SYST_APPT_OVRD_I, OVRD_FEAT_I, SRCE_SYST_STND_VALU_Q, SRCE_SYST_STND_VALU_R, SRCE_SYST_STND_VALU_A, CNCY_C, ACTL_VALU_Q, ACTL_VALU_R, ACTL_VALU_A, FEAT_SEQN_N, FEAT_STRT_D, FEE_CHRG_D, OVRD_REAS_C, FEE_ADD_TO_TOTL_F, FEE_CAPL_F, EXPY_D, PROS_KEY_EFFT_I, PROS_KEY_EXPY_I, EROR_SEQN_I FROM TMP_APPT_PDCT_FEAT WHERE RUN_STRM = 'CSE_COM_CPO_BUS_NCPR_CLNT')


SELECT * FROM Appt_Pdct_Feat_Trans