{{ config(materialized='view', tags=['LdDltAPP_ANS_EVNT_DEPT']) }}

WITH 
tmp_xs_evnt_app_ans AS (
	SELECT
	*
	FROM {{ ref("tmp_xs_evnt_app_ans")  }}),
evnt_dept AS (
	SELECT
	*
	FROM {{ ref("evnt_dept")  }}),
Src_Tera_APPT_PDCT_COND AS (SELECT a.EVNT_I AS NEW_EVNT_I, a.DEPT_ROLE_C AS NEW_DEPT_ROLE_C, a.DEPT_I AS NEW_DEPT_I, b.EVNT_I AS OLD_EVNT_I, b.DEPT_ROLE_C AS OLD_DEPT_ROLE_C, b.DEPT_I AS OLD_DEPT_I FROM TMP_XS_EVNT_APP_ANS LEFT OUTER JOIN EVNT_DEPT ON a.EVNT_I = b.EVNT_I AND a.DEPT_ROLE_C = b.DEPT_ROLE_C AND b.EXPY_D = '9999-12-31' AND a.RUN_STRM = '{{ var("RUN_STREAM") }}' GROUP BY NEW_EVNT_I, NEW_DEPT_ROLE_C, NEW_DEPT_I, OLD_EVNT_I, OLD_DEPT_ROLE_C, OLD_DEPT_I)


SELECT * FROM Src_Tera_APPT_PDCT_COND