{{ config(materialized='view', tags=['XfmCclAppProdFrmExt1']) }}

WITH LuAppProdExcl AS (
	SELECT
		{{ ref('CpyRename') }}.APP_PROD_ID,
		{{ ref('CpyRename') }}.PARENT_CCL_APP_PROD_ID,
		{{ ref('CpyRename') }}.ACCOUNT_NUMBER,
		{{ ref('CpyRename') }}.ACTUAL_RATE,
		{{ ref('CpyRename') }}.BALLOON_PAY_AMT,
		{{ ref('CpyRename') }}.BASIS_TYPE_CAT_ID,
		{{ ref('CpyRename') }}.INTEREST_RATE_MARGIN,
		{{ ref('CpyRename') }}.LOAN_TERM_MTH_NUM,
		{{ ref('CpyRename') }}.CURRENT_LIMIT,
		{{ ref('CpyRename') }}.INC_DEC_AMT,
		{{ ref('CpyRename') }}.POST_APP_AMT,
		{{ ref('CpyRename') }}.NEW_PROD_FLAG,
		{{ ref('CpyRename') }}.INDEX_RATE,
		{{ ref('CpyRename') }}.INTEREST_ADV_FLAG,
		{{ ref('CpyRename') }}.INTERESTONLY_TERM_MTH_NUM,
		{{ ref('CpyRename') }}.CAPPED_TERM_MTH_NUM,
		{{ ref('CpyRename') }}.CAPPED_RATE,
		{{ ref('CpyRename') }}.CRIS_PRODUCT_ID,
		{{ ref('CpyRename') }}.CCL_LOAN_PURPOSE_ID,
		{{ ref('CpyRename') }}.NEW_PROD_SUBTYPE_FLAG,
		{{ ref('CpyRename') }}.TEMP_EXCESS_MTHS,
		{{ ref('CpyRename') }}.LOAN_PURPOSE_CLASS_CODE,
		{{ ref('CpyRename') }}.CCL_INTEREST_RATE_CAT_ID,
		{{ ref('CpyRename') }}.CRR,
		{{ ref('CpyRename') }}.AD_TUC_INC_AMT,
		{{ ref('CpyRename') }}.CCL_RATE_TYPE_CAT_ID,
		{{ ref('CpyRename') }}.LINK_CCL_APP_ID,
		{{ ref('CpyRename') }}.LINK_CCL_APP_PROD_ID,
		{{ ref('CpyRename') }}.CHL_LMI_AMT,
		{{ ref('CpyRename') }}.USED_IN_EXPOSURE_VIEW_FLAG,
		{{ ref('CpyRename') }}.CCL_APP_BROKER_CIF_CODE,
		{{ ref('CpyRename') }}.APP_ID,
		{{ ref('CpyRename') }}.FIXED_INT_START_DATE,
		{{ ref('CpyRename') }}.CHILD_PRODUCT_LEVEL_CAT_ID,
		{{ ref('CpyRename') }}.PARENT_PRODUCT_LEVEL_CAT_ID,
		{{ ref('CpyRename') }}.ORIG_ETL_D,
		OutCclAppProdPremapDS.CCL_APP_PROD_ID AS APP_PROD_ID,
		OutCclAppProdPremapDS.PARENT_CCL_APP_PROD_ID,
		OutCclAppProdPremapDS.ACCOUNT_NUMBER,
		OutCclAppProdPremapDS.ACTUAL_RATE,
		OutCclAppProdPremapDS.BALLOON_PAY_AMT,
		OutCclAppProdPremapDS.BASIS_TYPE_CAT_ID,
		OutCclAppProdPremapDS.INTEREST_RATE_MARGIN,
		OutCclAppProdPremapDS.LOAN_TERM_MTH_NUM,
		OutCclAppProdPremapDS.CURRENT_LIMIT,
		OutCclAppProdPremapDS.INC_DEC_AMT,
		OutCclAppProdPremapDS.POST_APP_AMT,
		OutCclAppProdPremapDS.NEW_PROD_FLAG,
		OutCclAppProdPremapDS.INDEX_RATE,
		OutCclAppProdPremapDS.INTEREST_ADV_FLAG,
		OutCclAppProdPremapDS.INTERESTONLY_TERM_MTH_NUM,
		OutCclAppProdPremapDS.CAPPED_TERM_MTH_NUM,
		OutCclAppProdPremapDS.CAPPED_RATE,
		OutCclAppProdPremapDS.CRIS_PRODUCT_ID,
		OutCclAppProdPremapDS.CCL_LOAN_PURPOSE_ID,
		OutCclAppProdPremapDS.NEW_PROD_SUBTYPE_FLAG,
		OutCclAppProdPremapDS.TEMP_EXCESS_MTHS,
		OutCclAppProdPremapDS.LOAN_PURPOSE_CLASS_CODE,
		OutCclAppProdPremapDS.CCL_INTEREST_RATE_CAT_ID,
		OutCclAppProdPremapDS.CRR,
		OutCclAppProdPremapDS.AD_TUC_INC_AMT,
		OutCclAppProdPremapDS.CCL_RATE_TYPE_CAT_ID,
		OutCclAppProdPremapDS.LINK_CCL_APP_ID,
		OutCclAppProdPremapDS.LINK_CCL_APP_PROD_ID,
		OutCclAppProdPremapDS.CHL_LMI_AMT,
		OutCclAppProdPremapDS.USED_IN_EXPOSURE_VIEW_FLAG,
		OutCclAppProdPremapDS.CCL_APP_BROKER_CIF_CODE,
		OutCclAppProdPremapDS.APP_ID,
		OutCclAppProdPremapDS.FIXED_INT_START_DATE,
		OutCclAppProdPremapDS.CHILD_PRODUCT_LEVEL_CAT_ID,
		OutCclAppProdPremapDS.PARENT_PRODUCT_LEVEL_CAT_ID,
		OutCclAppProdPremapDS.ORIG_ETL_D
	FROM {{ ref('CpyRename') }}
	LEFT JOIN {{ ref('SrcAPP_PROD_EXCLLks') }} ON 
)

SELECT * FROM LuAppProdExcl