{{ config(materialized='view', tags=['ExtPlIntRatePlMargin']) }}

WITH Cpy_NoOp AS (
	SELECT
		PL_INT_RATE_ID,
		PL_INT_RATE_PL_INT_RATE_ID,
		PL_INT_RATE_DOC_SEQ_NO,
		PL_INT_RATE_CASS_MARGIN_AMT,
		PL_INT_RATE_INT_RATE_TERM,
		{{ ref('MergeDS') }}.PL_INT_RATE_INT_RATE_FREQUENCY_ID AS PL_INT_RATE_INT_RATE_FREQ_ID,
		PL_INT_RATE_VARIANT_CAT_ID,
		PL_INT_RATE_USAGE_CAT_ID,
		PL_INT_RATE_PL_APP_PROD_ID,
		PL_MARGIN_PL_MARGIN_ID,
		PL_MARGIN_MARGIN_AMT,
		PL_MARGIN_PL_FEE_ID,
		PL_MARGIN_PL_INT_RATE_ID,
		{{ ref('MergeDS') }}.PL_MARGIN_MARGIN_REASON_CAT_ID AS PL_MARGIN_MARGIN_RESN_CAT_ID,
		PL_MARGIN_PL_APP_PROD_ID,
		{{ ref('MergeDS') }}.PL_INT_RATE_AMT_INT_RATE_AMT_2 AS PL_INT_RATE_AMT_INT_RTE_AMT_2,
		{{ ref('MergeDS') }}.PL_INT_RATE_AMT_PL_INT_RATE_CAT_ID_2 AS PL_INT_RATE_AMT_INT_RTCT_ID2,
		PL_INT_RATE_AMT_PL_INT_RATE_ID,
		PL_INT_RATE_AMT_INT_RATE_AMT_1,
		{{ ref('MergeDS') }}.PL_INT_RATE_AMT_PL_INT_RATE_CAT_ID_1 AS PL_INT_RATE_AMT_INT_RTCT_ID1,
		PL_MARGIN_FOUND_FLAG,
		PL_INT_RATE_FOUND_FLAG,
		PL_INT_RATE_AMT_FOUND_FLAG
	FROM {{ ref('MergeDS') }}
)

SELECT * FROM Cpy_NoOp