-- DDL for missing tables and view dependencies
-- Generated automatically

-- ===============================
-- MISSING TABLES
-- ===============================

-- DGRDDB.GRD_PRTF_TYPE_ENHC_HIST_PSST -> PDGRD.GRD_PRTF_TYPE_ENHC_HIST_PSST
/* <sc-table> PDGRD.GRD_PRTF_TYPE_ENHC_HIST_PSST </sc-table> */
CREATE MULTISET TABLE PDGRD.GRD_PRTF_TYPE_ENHC_HIST_PSST ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      PRTF_TYPE_C VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      PRTF_TYPE_M VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      PRTF_CLAS_C VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      PRTF_CLAS_M VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      PRTF_CATG_C VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      PRTF_CATG_M VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALD_FROM_D DATE FORMAT 'yyyy-mm-dd',
      VALD_TO_D DATE FORMAT 'yyyy-mm-dd')
PRIMARY INDEX ( PRTF_TYPE_C );

-- DGRDDB.GRD_PRTF_TYPE_ENHC_PSST -> PDGRD.GRD_PRTF_TYPE_ENHC_PSST
/* <sc-table> PDGRD.GRD_PRTF_TYPE_ENHC_PSST </sc-table> */
CREATE MULTISET TABLE PDGRD.GRD_PRTF_TYPE_ENHC_PSST ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      PERD_D DATE FORMAT 'yyyy-mm-dd',
      PRTF_TYPE_C VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      PRTF_TYPE_M VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      PRTF_CLAS_C VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      PRTF_CLAS_M VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      PRTF_CATG_C VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      PRTF_CATG_M VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC)
PRIMARY INDEX ( PERD_D ,PRTF_TYPE_C );

-- PDDSTG.ACCT_BALN_BKDT_STG1 -> PDDSTG.ACCT_BALN_BKDT_STG1
/* <sc-table> PDDSTG.ACCT_BALN_BKDT_STG1 </sc-table> */
CREATE SET TABLE PDDSTG.ACCT_BALN_BKDT_STG1 ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      ACCT_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      BALN_TYPE_C CHAR(5) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS 'BDCL ',
      CALC_FUNC_C CHAR(5) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS 'SPOT ',
      TIME_PERD_C CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS 'E',
      BKDT_EFFT_D DATE FORMAT 'YYYY-MM-DD' NOT NULL,
      BKDT_EXPY_D DATE FORMAT 'YYYY-MM-DD' DEFAULT DATE '9999-12-31',
      BALN_A DECIMAL(15,2) COMPRESS 0.00 ,
      CALC_F CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS 'N',
      PROS_KEY_EFFT_I DECIMAL(10,0),
      PROS_KEY_EXPY_I DECIMAL(10,0),
      BKDT_PROS_KEY_I DECIMAL(10,0),
      ORIG_SRCE_SYST_C CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS 'SAP',
      SRCE_SYST_C CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS 'GDW',
      LOAD_D DATE FORMAT 'YYYY-MM-DD')
PRIMARY INDEX ( ACCT_I );

-- PDDSTG.ACCT_BALN_BKDT_STG2 -> PDDSTG.ACCT_BALN_BKDT_STG2
/* <sc-table> PDDSTG.ACCT_BALN_BKDT_STG2 </sc-table> */
CREATE SET TABLE PDDSTG.ACCT_BALN_BKDT_STG2 ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      ACCT_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      BALN_TYPE_C CHAR(5) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS 'BDCL ',
      CALC_FUNC_C CHAR(5) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS 'SPOT ',
      TIME_PERD_C CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS 'E',
      BKDT_EFFT_D DATE FORMAT 'YYYY-MM-DD',
      BKDT_EXPY_D DATE FORMAT 'YYYY-MM-DD' DEFAULT DATE '9999-12-31',
      BALN_A DECIMAL(15,2) COMPRESS 0.00 ,
      CALC_F CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS 'N',
      PROS_KEY_EFFT_I DECIMAL(10,0),
      PROS_KEY_EXPY_I DECIMAL(10,0),
      BKDT_PROS_KEY_I DECIMAL(10,0),
      ADJ_PROS_KEY_EFFT_I DECIMAL(10,0),
      ORIG_SRCE_SYST_C CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS 'SAP',
      SRCE_SYST_C CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS 'GDW',
      LOAD_D DATE FORMAT 'YYYY-MM-DD')
PRIMARY INDEX ( ACCT_I );

-- PDDSTG.ACCT_REL_HLS_REME -> PDCBSTG.ACCT_REL_HLS_REME
/* <sc-table> PDCBSTG.ACCT_REL_HLS_REME </sc-table> */
CREATE MULTISET TABLE PDCBSTG.ACCT_REL_HLS_REME ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      SUBJ_ACCT_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      OBJC_ACCT_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      OBJC_BDT_APPT CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALD_FROM TIMESTAMP(6),
      ACTL_VALD_END TIMESTAMP(6),
      REL_C CHAR(5) CHARACTER SET LATIN NOT CASESPECIFIC,
      MIRR_REL_C CHAR(5) CHARACTER SET LATIN NOT CASESPECIFIC,
      CTCT_STUS CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      INTR_CNCT_NUMB_OF_MAIN_CNCT VARCHAR(32) CHARACTER SET LATIN NOT CASESPECIFIC,
      HIER_ID VARCHAR(32) CHARACTER SET LATIN NOT CASESPECIFIC,
      CNCT_CATG CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC,
      RUN_STRM_PROS_D DATE FORMAT 'yyyy-mm-dd',
      OBJC_ACCT_LEVL_N INTEGER,
      SUBJ_ACCT_LEVL_N INTEGER,
      TGT_EFFT_D DATE FORMAT 'yyyy-mm-dd',
      FLG VARCHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC)
PRIMARY INDEX ( SUBJ_ACCT_I );

-- PDDSTG.ACCT_REL_HLS_REME_HIST -> PDCBSTG.ACCT_REL_HLS_REME_HIST
/* <sc-table> PDCBSTG.ACCT_REL_HLS_REME_HIST </sc-table> */
CREATE MULTISET TABLE PDCBSTG.ACCT_REL_HLS_REME_HIST ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      SUBJ_ACCT_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      OBJC_ACCT_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      OBJC_BDT_APPT CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALD_FROM TIMESTAMP(6),
      ACTL_VALD_END TIMESTAMP(6),
      REL_C CHAR(5) CHARACTER SET LATIN NOT CASESPECIFIC,
      MIRR_REL_C CHAR(5) CHARACTER SET LATIN NOT CASESPECIFIC,
      CTCT_STUS CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      INTR_CNCT_NUMB_OF_MAIN_CNCT VARCHAR(32) CHARACTER SET LATIN NOT CASESPECIFIC,
      HIER_ID VARCHAR(32) CHARACTER SET LATIN NOT CASESPECIFIC,
      CNCT_CATG CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC,
      RUN_STRM_PROS_D DATE FORMAT 'yyyy-mm-dd',
      OBJC_ACCT_LEVL_N INTEGER,
      SUBJ_ACCT_LEVL_N INTEGER,
      TGT_EFFT_D DATE FORMAT 'yyyy-mm-dd',
      FLG VARCHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC,
      LOAD_DATE DATE FORMAT 'yyyy-mm-dd' NOT NULL)
PRIMARY INDEX ( SUBJ_ACCT_I );

-- PDDSTG.UTIL_PROS_SAP_RUN -> PDCBSTG.UTIL_PROS_SAP_RUN
/* <sc-table> PDCBSTG.UTIL_PROS_SAP_RUN </sc-table> */
CREATE MULTISET TABLE PDCBSTG.UTIL_PROS_SAP_RUN ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      RUN_DATE DATE FORMAT 'yyyy-mm-dd',
      PROS_KEY_EFFT_I BIGINT GENERATED ALWAYS AS IDENTITY
           (START WITH 999999163 
            INCREMENT BY 1 
            MINVALUE 999999163 
            MAXVALUE 999999999999999999 
            NO CYCLE),
      RECD_CNT INTEGER)
PRIMARY INDEX ( RUN_DATE );

-- PVTECH.ACCT_BALN_BKDT -> STAR_CAD_PROD_DATA.ACCT_BALN_BKDT
/* <sc-table> STAR_CAD_PROD_DATA.ACCT_BALN_BKDT </sc-table> */
CREATE SET TABLE STAR_CAD_PROD_DATA.ACCT_BALN_BKDT ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     BLOCKCOMPRESSION = AUTOTEMP,
     MAP = TD_MAP1
     (
      ACCT_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Account Identifier' NOT NULL,
      BALN_TYPE_C CHAR(5) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Balance Type Code' NOT NULL COMPRESS 'BDCL ',
      CALC_FUNC_C CHAR(5) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Calculation Function Code' NOT NULL COMPRESS 'SPOT ',
      TIME_PERD_C CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Time Period Code' NOT NULL COMPRESS 'E',
      BALN_A DECIMAL(23,5) TITLE 'Balance Amount' COMPRESS 0.00000 ,
      CALC_F CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Calculate Flag' NOT NULL DEFAULT 'N' COMPRESS ('N','Y'),
      SRCE_SYST_C CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Source System Code' COMPRESS 'GDW',
      ORIG_SRCE_SYST_C CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Original Source System Code' COMPRESS 'SAP',
      LOAD_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Load Date',
      BKDT_EFFT_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Backdate Effective Date' NOT NULL,
      BKDT_EXPY_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Backdate Expiry Date' NOT NULL DEFAULT DATE '9999-12-31',
      PROS_KEY_EFFT_I DECIMAL(10,0) TITLE 'Process Key Effective Identifier',
      PROS_KEY_EXPY_I DECIMAL(10,0) TITLE 'Process Key Expiry Identifier' COMPRESS ,
      BKDT_PROS_KEY_I DECIMAL(10,0) TITLE 'Backdate Process Key Identifier' COMPRESS ,
      CNCY_C CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Currency Code' COMPRESS ('AUD','CAD','CHF','CNY','EUR','GBP','HKD','INR','JPY','NZD','SEK','SGD','THB','USD','ZAR'),
      ROW_SECU_ACCS_C INTEGER TITLE 'Row Security Access Code' DEFAULT 0  COMPRESS 0 )
PRIMARY INDEX XIE1ACCT_BALN_BKDT ( ACCT_I );

-- PVTECH.ACCT_BALN_BKDT_RECN -> STAR_CAD_PROD_DATA.ACCT_BALN_BKDT_RECN
/* <sc-table> STAR_CAD_PROD_DATA.ACCT_BALN_BKDT_RECN </sc-table> */
CREATE SET TABLE STAR_CAD_PROD_DATA.ACCT_BALN_BKDT_RECN ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      ACCT_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Account Identifier' NOT NULL,
      BALN_A DECIMAL(15,2) TITLE 'Balance Amount' COMPRESS 0.00 ,
      BKDT_EFFT_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Backdate Effective Date' NOT NULL,
      BKDT_EXPY_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Backdate Expiry Date' NOT NULL DEFAULT DATE '9999-12-31',
      PROS_KEY_EFFT_I DECIMAL(10,0) TITLE 'Process Key Effective Identifier')
PRIMARY INDEX XIE1ACCT_BALN_BKDT_RECN ( ACCT_I );

-- PVTECH.ACCT_INT_GRUP -> P_P01_STAR_CAD_PROD_DATA.ACCT_INT_GRUP
/* <sc-table> P_P01_STAR_CAD_PROD_DATA.ACCT_INT_GRUP </sc-table> */
CREATE SET TABLE P_P01_STAR_CAD_PROD_DATA.ACCT_INT_GRUP ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      ACCT_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Account Identifier' NOT NULL,
      INT_GRUP_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Interest Group Identifier' NOT NULL,
      REL_C CHAR(5) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Relationship Code' NOT NULL COMPRESS ('ZP00 ','ZP01 ','ZP02 ','ZP03 ','ZP04 ','ZP05 ','ZP06 '),
      SRCE_SYST_C CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Source System Code' COMPRESS 'SAP',
      VALD_FROM_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Valid From Date',
      VALD_TO_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Valid To Date' COMPRESS (DATE '9999-12-31'),
      EFFT_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Effective Date' NOT NULL,
      EXPY_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Expiry Date' NOT NULL DEFAULT DATE '9999-12-31' COMPRESS (DATE '9999-12-31'),
      PROS_KEY_EFFT_I DECIMAL(10,0) TITLE 'Process Key Effective Identifier' NOT NULL,
      PROS_KEY_EXPY_I DECIMAL(10,0) TITLE 'Process Key Expiry Identifier' DEFAULT NULL  COMPRESS ,
      ROW_SECU_ACCS_C INTEGER TITLE 'Row Security Access Code' NOT NULL DEFAULT 0  COMPRESS 0 )
PRIMARY INDEX XIE1ACCT_INT_GRUP ( ACCT_I );

-- PVTECH.ACCT_INT_GRUP -> STAR_CAD_PROD_DATA.ACCT_INT_GRUP
/* <sc-table> STAR_CAD_PROD_DATA.ACCT_INT_GRUP </sc-table> */
CREATE SET TABLE STAR_CAD_PROD_DATA.ACCT_INT_GRUP ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      ACCT_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Account Identifier' NOT NULL,
      INT_GRUP_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Interest Group Identifier' NOT NULL,
      REL_C CHAR(5) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Relationship Code' NOT NULL COMPRESS ('ZP00 ','ZP01 ','ZP02 ','ZP03 ','ZP04 ','ZP05 ','ZP06 '),
      SRCE_SYST_C CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Source System Code' COMPRESS 'SAP',
      VALD_FROM_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Valid From Date',
      VALD_TO_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Valid To Date' COMPRESS (DATE '9999-12-31'),
      EFFT_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Effective Date' NOT NULL,
      EXPY_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Expiry Date' NOT NULL DEFAULT DATE '9999-12-31' COMPRESS (DATE '9999-12-31'),
      PROS_KEY_EFFT_I DECIMAL(10,0) TITLE 'Process Key Effective Identifier' NOT NULL,
      PROS_KEY_EXPY_I DECIMAL(10,0) TITLE 'Process Key Expiry Identifier' DEFAULT NULL  COMPRESS ,
      ROW_SECU_ACCS_C INTEGER TITLE 'Row Security Access Code' NOT NULL DEFAULT 0  COMPRESS 0 )
PRIMARY INDEX XIE1ACCT_INT_GRUP ( ACCT_I );

-- PVTECH.DERV_PRTF_ACCT_HIST_PSST -> UDTDWRK.DERV_PRTF_ACCT_HIST_PSST
/* <sc-table> UDTDWRK.DERV_PRTF_ACCT_HIST_PSST </sc-table> */
CREATE MULTISET TABLE UDTDWRK.DERV_PRTF_ACCT_HIST_PSST ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      INT_GRUP_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      ACCT_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      REL_C CHAR(5) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ('CPOC ','JABP ','RLMT ','RMGR ','TRBN '),
      JOIN_FROM_D DATE FORMAT 'yyyy-mm-dd',
      JOIN_TO_D DATE FORMAT 'yyyy-mm-dd',
      VALD_FROM_D DATE FORMAT 'yyyy-mm-dd',
      VALD_TO_D DATE FORMAT 'yyyy-mm-dd',
      EFFT_D DATE FORMAT 'yyyy-mm-dd',
      EXPY_D DATE FORMAT 'yyyy-mm-dd',
      SRCE_SYST_C CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS 'SAP',
      ROW_SECU_ACCS_C INTEGER COMPRESS 0 )
PRIMARY INDEX ( INT_GRUP_I );

-- PVTECH.DERV_PRTF_ACCT_HIST_PSST -> STAR_CAD_PROD_DATA.DERV_PRTF_ACCT_HIST_PSST
/* <sc-table> STAR_CAD_PROD_DATA.DERV_PRTF_ACCT_HIST_PSST </sc-table> */
CREATE MULTISET TABLE STAR_CAD_PROD_DATA.DERV_PRTF_ACCT_HIST_PSST ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      INT_GRUP_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      ACCT_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      REL_C CHAR(5) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ('CPOC ','JABP ','RLMT ','RMGR ','TRBN '),
      JOIN_FROM_D DATE FORMAT 'yyyy-mm-dd',
      JOIN_TO_D DATE FORMAT 'yyyy-mm-dd',
      VALD_FROM_D DATE FORMAT 'yyyy-mm-dd',
      VALD_TO_D DATE FORMAT 'yyyy-mm-dd',
      EFFT_D DATE FORMAT 'yyyy-mm-dd',
      EXPY_D DATE FORMAT 'yyyy-mm-dd',
      SRCE_SYST_C CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS 'SAP',
      ROW_SECU_ACCS_C INTEGER COMPRESS 0 )
PRIMARY INDEX ( INT_GRUP_I );

-- PVTECH.DERV_PRTF_ACCT_INT_GRUP_PSST -> STAR_CAD_PROD_DATA.DERV_PRTF_ACCT_INT_GRUP_PSST
/* <sc-table> STAR_CAD_PROD_DATA.DERV_PRTF_ACCT_INT_GRUP_PSST </sc-table> */
CREATE MULTISET TABLE STAR_CAD_PROD_DATA.DERV_PRTF_ACCT_INT_GRUP_PSST ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      INT_GRUP_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      ACCT_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      EFFT_D DATE FORMAT 'yyyy-mm-dd',
      EXPY_D DATE FORMAT 'yyyy-mm-dd',
      VALD_FROM_D DATE FORMAT 'yyyy-mm-dd',
      VALD_TO_D DATE FORMAT 'yyyy-mm-dd',
      PERD_D DATE FORMAT 'yyyy-mm-dd',
      REL_C CHAR(5) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ('CPOC ','JABP ','RLMT ','RMGR ','TRBN '),
      SRCE_SYST_C CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS 'SAP',
      ROW_N DECIMAL(10,0),
      ROW_SECU_ACCS_C INTEGER COMPRESS 0 ,
      PROS_KEY_I DECIMAL(10,0))
PRIMARY INDEX ( INT_GRUP_I ,ACCT_I ,PERD_D );

-- PVTECH.DERV_PRTF_ACCT_PSST -> STAR_CAD_PROD_DATA.DERV_PRTF_ACCT_PSST
/* <sc-table> STAR_CAD_PROD_DATA.DERV_PRTF_ACCT_PSST </sc-table> */
CREATE MULTISET TABLE STAR_CAD_PROD_DATA.DERV_PRTF_ACCT_PSST ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      INT_GRUP_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      ACCT_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      REL_C CHAR(5) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ('CPOC ','JABP ','RLMT ','RMGR ','TRBN '),
      JOIN_FROM_D DATE FORMAT 'yyyy-mm-dd',
      JOIN_TO_D DATE FORMAT 'yyyy-mm-dd',
      VALD_FROM_D DATE FORMAT 'yyyy-mm-dd',
      VALD_TO_D DATE FORMAT 'yyyy-mm-dd',
      EFFT_D DATE FORMAT 'yyyy-mm-dd',
      EXPY_D DATE FORMAT 'yyyy-mm-dd',
      SRCE_SYST_C CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS 'SAP',
      PROS_KEY_I DECIMAL(10,0),
      ROW_SECU_ACCS_C INTEGER COMPRESS 0 )
PRIMARY INDEX ( ACCT_I )
INDEX ( INT_GRUP_I );

-- PVTECH.DERV_PRTF_INT_GRUP_ENHC_PSST -> STAR_CAD_PROD_DATA.DERV_PRTF_INT_GRUP_ENHC_PSST
/* <sc-table> STAR_CAD_PROD_DATA.DERV_PRTF_INT_GRUP_ENHC_PSST </sc-table> */
CREATE MULTISET TABLE STAR_CAD_PROD_DATA.DERV_PRTF_INT_GRUP_ENHC_PSST ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      INT_GRUP_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      INT_GRUP_TYPE_C CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ('JABP','RLMT','RMGR','SALE'),
      EFFT_D DATE FORMAT 'yyyy-mm-dd',
      EXPY_D DATE FORMAT 'yyyy-mm-dd',
      VALD_FROM_D DATE FORMAT 'yyyy-mm-dd',
      VALD_TO_D DATE FORMAT 'yyyy-mm-dd',
      PERD_D DATE FORMAT 'yyyy-mm-dd',
      PTCL_N CHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC,
      REL_MNGE_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      ROW_N DECIMAL(10,0),
      PROS_KEY_I DECIMAL(10,0))
PRIMARY INDEX ( INT_GRUP_I );

-- PVTECH.DERV_PRTF_INT_GRUP_OWN_PSST -> STAR_CAD_PROD_DATA.DERV_PRTF_INT_GRUP_OWN_PSST
/* <sc-table> STAR_CAD_PROD_DATA.DERV_PRTF_INT_GRUP_OWN_PSST </sc-table> */
CREATE MULTISET TABLE STAR_CAD_PROD_DATA.DERV_PRTF_INT_GRUP_OWN_PSST ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      INT_GRUP_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      ROLE_PLAY_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      EFFT_D DATE FORMAT 'yyyy-mm-dd',
      EXPY_D DATE FORMAT 'yyyy-mm-dd',
      VALD_FROM_D DATE FORMAT 'yyyy-mm-dd',
      VALD_TO_D DATE FORMAT 'yyyy-mm-dd',
      PERD_D DATE FORMAT 'yyyy-mm-dd',
      ROLE_PLAY_TYPE_X CHAR(40) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ('Department                              ','Employee                                '),
      DERV_PRTF_ROLE_C CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ('AOWN','ASTT','OWNR','STDP'),
      SRCE_SYST_C CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS 'SAP',
      ROW_N DECIMAL(10,0),
      ROW_SECU_ACCS_C INTEGER COMPRESS 0 ,
      PROS_KEY_I DECIMAL(10,0))
PRIMARY INDEX ( INT_GRUP_I );

-- PVTECH.DERV_PRTF_INT_HIST_PSST -> STAR_CAD_PROD_DATA.DERV_PRTF_INT_HIST_PSST
/* <sc-table> STAR_CAD_PROD_DATA.DERV_PRTF_INT_HIST_PSST </sc-table> */
CREATE MULTISET TABLE STAR_CAD_PROD_DATA.DERV_PRTF_INT_HIST_PSST ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      INT_GRUP_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      INT_GRUP_TYPE_C CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ('JABP','RLMT','RMGR','SALE'),
      EFFT_D DATE FORMAT 'yyyy-mm-dd',
      EXPY_D DATE FORMAT 'yyyy-mm-dd',
      VALD_FROM_D DATE FORMAT 'yyyy-mm-dd',
      VALD_TO_D DATE FORMAT 'yyyy-mm-dd',
      JOIN_FROM_D DATE FORMAT 'yyyy-mm-dd',
      JOIN_TO_D DATE FORMAT 'yyyy-mm-dd',
      PTCL_N CHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC,
      REL_MNGE_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC)
PRIMARY INDEX ( INT_GRUP_I );

-- PVTECH.DERV_PRTF_INT_PSST -> STAR_CAD_PROD_DATA.DERV_PRTF_INT_PSST
/* <sc-table> STAR_CAD_PROD_DATA.DERV_PRTF_INT_PSST </sc-table> */
CREATE MULTISET TABLE STAR_CAD_PROD_DATA.DERV_PRTF_INT_PSST ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      INT_GRUP_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      INT_GRUP_TYPE_C CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ('JABP','RLMT','RMGR','SALE'),
      JOIN_FROM_D DATE FORMAT 'yyyy-mm-dd',
      JOIN_TO_D DATE FORMAT 'yyyy-mm-dd',
      EFFT_D DATE FORMAT 'yyyy-mm-dd',
      EXPY_D DATE FORMAT 'yyyy-mm-dd',
      PTCL_N CHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC,
      REL_MNGE_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALD_FROM_D DATE FORMAT 'yyyy-mm-dd',
      VALD_TO_D DATE FORMAT 'yyyy-mm-dd',
      PROS_KEY_I DECIMAL(10,0) COMPRESS 0. )
PRIMARY INDEX ( INT_GRUP_I );

-- PVTECH.DERV_PRTF_INT_PSST -> PTEMP.DERV_PRTF_INT_PSST
/* <sc-table> PTEMP.DERV_PRTF_INT_PSST </sc-table> */
CREATE MULTISET TABLE PTEMP.DERV_PRTF_INT_PSST ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      INT_GRUP_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      INT_GRUP_TYPE_C CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC,
      JOIN_FROM_D DATE FORMAT 'yyyy-mm-dd',
      JOIN_TO_D DATE FORMAT 'yyyy-mm-dd',
      EFFT_D DATE FORMAT 'yyyy-mm-dd',
      EXPY_D DATE FORMAT 'yyyy-mm-dd',
      PTCL_N CHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC,
      REL_MNGE_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALD_FROM_D DATE FORMAT 'yyyy-mm-dd',
      VALD_TO_D DATE FORMAT 'yyyy-mm-dd',
      PROS_KEY_I DECIMAL(10,0))
PRIMARY INDEX ( INT_GRUP_I );

-- PVTECH.DERV_PRTF_OWN_HIST_PSST -> STAR_CAD_PROD_DATA.DERV_PRTF_OWN_HIST_PSST
/* <sc-table> STAR_CAD_PROD_DATA.DERV_PRTF_OWN_HIST_PSST </sc-table> */
CREATE MULTISET TABLE STAR_CAD_PROD_DATA.DERV_PRTF_OWN_HIST_PSST ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      INT_GRUP_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      ROLE_PLAY_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      JOIN_FROM_D DATE FORMAT 'yyyy-mm-dd',
      JOIN_TO_D DATE FORMAT 'yyyy-mm-dd',
      EFFT_D DATE FORMAT 'yyyy-mm-dd',
      EXPY_D DATE FORMAT 'yyyy-mm-dd',
      VALD_FROM_D DATE FORMAT 'yyyy-mm-dd',
      VALD_TO_D DATE FORMAT 'yyyy-mm-dd',
      ROLE_PLAY_TYPE_X CHAR(40) CHARACTER SET LATIN NOT CASESPECIFIC,
      DERV_PRTF_ROLE_C CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ('AOWN','ASTT','OWNR','STDP'),
      SRCE_SYST_C CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS 'SAP',
      ROW_SECU_ACCS_C INTEGER COMPRESS 0 ,
      PROS_KEY_I DECIMAL(10,0))
PRIMARY INDEX ( INT_GRUP_I );

-- PVTECH.DERV_PRTF_OWN_PSST -> STAR_CAD_PROD_DATA.DERV_PRTF_OWN_PSST
/* <sc-table> STAR_CAD_PROD_DATA.DERV_PRTF_OWN_PSST </sc-table> */
CREATE MULTISET TABLE STAR_CAD_PROD_DATA.DERV_PRTF_OWN_PSST ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      INT_GRUP_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      JOIN_FROM_D DATE FORMAT 'yyyy-mm-dd',
      JOIN_TO_D DATE FORMAT 'yyyy-mm-dd',
      VALD_FROM_D DATE FORMAT 'yyyy-mm-dd',
      VALD_TO_D DATE FORMAT 'yyyy-mm-dd',
      EFFT_D DATE FORMAT 'yyyy-mm-dd',
      EXPY_D DATE FORMAT 'yyyy-mm-dd',
      DERV_PRTF_ROLE_C CHAR(4) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS ('AOWN','ASTT','OWNR','STDP'),
      ROLE_PLAY_TYPE_X VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC,
      ROLE_PLAY_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      SRCE_SYST_C CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC,
      ROW_SECU_ACCS_C INTEGER COMPRESS 0 ,
      PROS_KEY_I DECIMAL(10,0))
PRIMARY INDEX ( INT_GRUP_I ,PROS_KEY_I );

-- PVTECH.DERV_PRTF_PATY_HIST_PSST -> STAR_CAD_PROD_DATA.DERV_PRTF_PATY_HIST_PSST
/* <sc-table> STAR_CAD_PROD_DATA.DERV_PRTF_PATY_HIST_PSST </sc-table> */
CREATE MULTISET TABLE STAR_CAD_PROD_DATA.DERV_PRTF_PATY_HIST_PSST ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      INT_GRUP_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      PATY_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      REL_C CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ('RLMT','RMGR'),
      JOIN_FROM_D DATE FORMAT 'yyyy-mm-dd',
      JOIN_TO_D DATE FORMAT 'yyyy-mm-dd',
      VALD_FROM_D DATE FORMAT 'yyyy-mm-dd',
      VALD_TO_D DATE FORMAT 'yyyy-mm-dd',
      EFFT_D DATE FORMAT 'yyyy-mm-dd',
      EXPY_D DATE FORMAT 'yyyy-mm-dd',
      SRCE_SYST_C CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS 'SAP',
      ROW_SECU_ACCS_C INTEGER COMPRESS 0 ,
      PROS_KEY_I DECIMAL(10,0))
PRIMARY INDEX ( INT_GRUP_I );

-- PVTECH.DERV_PRTF_PATY_INT_GRUP_PSST -> STAR_CAD_PROD_DATA.DERV_PRTF_PATY_INT_GRUP_PSST
/* <sc-table> STAR_CAD_PROD_DATA.DERV_PRTF_PATY_INT_GRUP_PSST </sc-table> */
CREATE MULTISET TABLE STAR_CAD_PROD_DATA.DERV_PRTF_PATY_INT_GRUP_PSST ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      INT_GRUP_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      PATY_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      EFFT_D DATE FORMAT 'yyyy-mm-dd',
      EXPY_D DATE FORMAT 'yyyy-mm-dd',
      VALD_FROM_D DATE FORMAT 'yyyy-mm-dd',
      VALD_TO_D DATE FORMAT 'yyyy-mm-dd',
      PERD_D DATE FORMAT 'yyyy-mm-dd',
      REL_C CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ('RLMT','RMGR'),
      SRCE_SYST_C CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS 'SAP',
      ROW_N DECIMAL(10,0),
      ROW_SECU_ACCS_C INTEGER COMPRESS 0 ,
      PROS_KEY_I DECIMAL(10,0))
PRIMARY INDEX ( INT_GRUP_I );

-- PVTECH.GRD_PRTF_TYPE_ENHC_HIST_PSST -> PDGRD.GRD_PRTF_TYPE_ENHC_HIST_PSST
/* <sc-table> PDGRD.GRD_PRTF_TYPE_ENHC_HIST_PSST </sc-table> */
CREATE MULTISET TABLE PDGRD.GRD_PRTF_TYPE_ENHC_HIST_PSST ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      PRTF_TYPE_C VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      PRTF_TYPE_M VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      PRTF_CLAS_C VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      PRTF_CLAS_M VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      PRTF_CATG_C VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      PRTF_CATG_M VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALD_FROM_D DATE FORMAT 'yyyy-mm-dd',
      VALD_TO_D DATE FORMAT 'yyyy-mm-dd')
PRIMARY INDEX ( PRTF_TYPE_C );

-- PVTECH.GRD_PRTF_TYPE_ENHC_PSST -> PDGRD.GRD_PRTF_TYPE_ENHC_PSST
/* <sc-table> PDGRD.GRD_PRTF_TYPE_ENHC_PSST </sc-table> */
CREATE MULTISET TABLE PDGRD.GRD_PRTF_TYPE_ENHC_PSST ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      PERD_D DATE FORMAT 'yyyy-mm-dd',
      PRTF_TYPE_C VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      PRTF_TYPE_M VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      PRTF_CLAS_C VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      PRTF_CLAS_M VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      PRTF_CATG_C VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      PRTF_CATG_M VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC)
PRIMARY INDEX ( PERD_D ,PRTF_TYPE_C );

-- STAR_CAD_PROD_DATA.ACCT_BALN_BKDT -> STAR_CAD_PROD_DATA.ACCT_BALN_BKDT
/* <sc-table> STAR_CAD_PROD_DATA.ACCT_BALN_BKDT </sc-table> */
CREATE SET TABLE STAR_CAD_PROD_DATA.ACCT_BALN_BKDT ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     BLOCKCOMPRESSION = AUTOTEMP,
     MAP = TD_MAP1
     (
      ACCT_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Account Identifier' NOT NULL,
      BALN_TYPE_C CHAR(5) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Balance Type Code' NOT NULL COMPRESS 'BDCL ',
      CALC_FUNC_C CHAR(5) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Calculation Function Code' NOT NULL COMPRESS 'SPOT ',
      TIME_PERD_C CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Time Period Code' NOT NULL COMPRESS 'E',
      BALN_A DECIMAL(23,5) TITLE 'Balance Amount' COMPRESS 0.00000 ,
      CALC_F CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Calculate Flag' NOT NULL DEFAULT 'N' COMPRESS ('N','Y'),
      SRCE_SYST_C CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Source System Code' COMPRESS 'GDW',
      ORIG_SRCE_SYST_C CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Original Source System Code' COMPRESS 'SAP',
      LOAD_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Load Date',
      BKDT_EFFT_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Backdate Effective Date' NOT NULL,
      BKDT_EXPY_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Backdate Expiry Date' NOT NULL DEFAULT DATE '9999-12-31',
      PROS_KEY_EFFT_I DECIMAL(10,0) TITLE 'Process Key Effective Identifier',
      PROS_KEY_EXPY_I DECIMAL(10,0) TITLE 'Process Key Expiry Identifier' COMPRESS ,
      BKDT_PROS_KEY_I DECIMAL(10,0) TITLE 'Backdate Process Key Identifier' COMPRESS ,
      CNCY_C CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Currency Code' COMPRESS ('AUD','CAD','CHF','CNY','EUR','GBP','HKD','INR','JPY','NZD','SEK','SGD','THB','USD','ZAR'),
      ROW_SECU_ACCS_C INTEGER TITLE 'Row Security Access Code' DEFAULT 0  COMPRESS 0 )
PRIMARY INDEX XIE1ACCT_BALN_BKDT ( ACCT_I );

-- STAR_CAD_PROD_DATA.ACCT_BALN_BKDT_AUDT -> STAR_CAD_PROD_DATA.ACCT_BALN_BKDT_AUDT
/* <sc-table> STAR_CAD_PROD_DATA.ACCT_BALN_BKDT_AUDT </sc-table> */
CREATE SET TABLE STAR_CAD_PROD_DATA.ACCT_BALN_BKDT_AUDT ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      ACCT_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Account Identifier' NOT NULL,
      BALN_TYPE_C CHAR(5) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Balance Type Code' NOT NULL COMPRESS 'BDCL ',
      CALC_FUNC_C CHAR(5) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Calculation Function Code' NOT NULL COMPRESS 'SPOT ',
      TIME_PERD_C CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Time Period Code' NOT NULL COMPRESS 'E',
      BALN_A DECIMAL(15,2) TITLE 'Balance Amount' COMPRESS 0.00 ,
      CALC_F CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Calculate Flag' NOT NULL DEFAULT 'N' COMPRESS ('N','Y'),
      SRCE_SYST_C CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Source System Code' COMPRESS 'GDW',
      ORIG_SRCE_SYST_C CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Original Source System Code' COMPRESS 'SAP',
      LOAD_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Load Date',
      BKDT_EFFT_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Backdate Effective Date' NOT NULL,
      BKDT_EXPY_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Backdate Expiry Date' NOT NULL DEFAULT DATE '9999-12-31',
      PROS_KEY_EFFT_I DECIMAL(10,0) TITLE 'Process Key Effective Identifier',
      ABAL_PROS_KEY_EFFT_I DECIMAL(10,0) TITLE 'Adjusted Balance Process Key Effective Identifier',
      ABAL_PROS_KEY_EXPY_I DECIMAL(10,0) TITLE 'Adjusted Balance Process Key Expiry Identifier',
      ABAL_BKDT_PROS_KEY_I DECIMAL(10,0) TITLE 'Adjusted Balance Backdate Process Key Effective Identifier',
      ADJ_PROS_KEY_EFFT_I DECIMAL(10,0) TITLE 'Adjusted Process Key Effective Identifier')
PRIMARY INDEX XIE1ACCT_BALN_BKDT_AUDT ( ACCT_I );

-- STAR_CAD_PROD_DATA.ACCT_BALN_BKDT_RECN -> STAR_CAD_PROD_DATA.ACCT_BALN_BKDT_RECN
/* <sc-table> STAR_CAD_PROD_DATA.ACCT_BALN_BKDT_RECN </sc-table> */
CREATE SET TABLE STAR_CAD_PROD_DATA.ACCT_BALN_BKDT_RECN ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      ACCT_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Account Identifier' NOT NULL,
      BALN_A DECIMAL(15,2) TITLE 'Balance Amount' COMPRESS 0.00 ,
      BKDT_EFFT_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Backdate Effective Date' NOT NULL,
      BKDT_EXPY_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Backdate Expiry Date' NOT NULL DEFAULT DATE '9999-12-31',
      PROS_KEY_EFFT_I DECIMAL(10,0) TITLE 'Process Key Effective Identifier')
PRIMARY INDEX XIE1ACCT_BALN_BKDT_RECN ( ACCT_I );

-- STAR_CAD_PROD_DATA.ACCT_PATY_TAX_INSS -> P_P01_STAR_CAD_PROD_DATA.ACCT_PATY_TAX_INSS
/* <sc-table> P_P01_STAR_CAD_PROD_DATA.ACCT_PATY_TAX_INSS </sc-table> */
CREATE SET TABLE P_P01_STAR_CAD_PROD_DATA.ACCT_PATY_TAX_INSS ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      ACCT_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Account Identifier' NOT NULL,
      PATY_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Party Identifier' NOT NULL,
      SRCE_SYST_C CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Source System Code' NOT NULL COMPRESS 'SAP',
      RESI_STUS_C CHAR(5) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Life Cycle Reason Code' COMPRESS ('NRES ','RSDT '),
      IDNN_TYPE_C CHAR(5) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Identification Type Code' COMPRESS ('ABN  ','TED  ','TFN  '),
      IDNN_STUS_C CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Identification Status Code' COMPRESS ('PRNU','PRVN'),
      EFFT_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Effective Date',
      EXPY_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Expiry Date' NOT NULL COMPRESS (DATE '9999-12-31'),
      PROS_KEY_EFFT_I INTEGER TITLE 'Process Key Effective Identifier' NOT NULL,
      PROS_KEY_EXPY_I INTEGER TITLE 'Process Key Expiry Identifier' DEFAULT NULL  COMPRESS ,
      ROW_SECU_ACCS_C INTEGER TITLE 'Row Security Access Code' NOT NULL COMPRESS 0 )
PRIMARY INDEX XIE1ACCT_PATY_TAX_INSS ( ACCT_I );

-- STAR_CAD_PROD_DATA.ACCT_PATY_TAX_INSS -> STAR_CAD_PROD_DATA.ACCT_PATY_TAX_INSS
/* <sc-table> STAR_CAD_PROD_DATA.ACCT_PATY_TAX_INSS </sc-table> */
CREATE SET TABLE STAR_CAD_PROD_DATA.ACCT_PATY_TAX_INSS ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      ACCT_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Account Identifier' NOT NULL,
      PATY_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Party Identifier' NOT NULL,
      SRCE_SYST_C CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Source System Code' NOT NULL COMPRESS 'SAP',
      RESI_STUS_C CHAR(5) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Life Cycle Reason Code' COMPRESS ('NRES ','RSDT '),
      IDNN_TYPE_C CHAR(5) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Identification Type Code' COMPRESS ('ABN  ','TED  ','TFN  '),
      IDNN_STUS_C CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Identification Status Code' COMPRESS ('PRNU','PRVN'),
      EFFT_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Effective Date',
      EXPY_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Expiry Date' NOT NULL COMPRESS (DATE '9999-12-31'),
      PROS_KEY_EFFT_I INTEGER TITLE 'Process Key Effective Identifier' NOT NULL,
      PROS_KEY_EXPY_I INTEGER TITLE 'Process Key Expiry Identifier' DEFAULT NULL  COMPRESS ,
      ROW_SECU_ACCS_C INTEGER TITLE 'Row Security Access Code' NOT NULL COMPRESS 0 )
PRIMARY INDEX XIE1ACCT_PATY_TAX_INSS ( ACCT_I );

-- STAR_CAD_PROD_DATA.DERV_PRTF_ACCT_HIST_PSST -> UDTDWRK.DERV_PRTF_ACCT_HIST_PSST
/* <sc-table> UDTDWRK.DERV_PRTF_ACCT_HIST_PSST </sc-table> */
CREATE MULTISET TABLE UDTDWRK.DERV_PRTF_ACCT_HIST_PSST ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      INT_GRUP_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      ACCT_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      REL_C CHAR(5) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ('CPOC ','JABP ','RLMT ','RMGR ','TRBN '),
      JOIN_FROM_D DATE FORMAT 'yyyy-mm-dd',
      JOIN_TO_D DATE FORMAT 'yyyy-mm-dd',
      VALD_FROM_D DATE FORMAT 'yyyy-mm-dd',
      VALD_TO_D DATE FORMAT 'yyyy-mm-dd',
      EFFT_D DATE FORMAT 'yyyy-mm-dd',
      EXPY_D DATE FORMAT 'yyyy-mm-dd',
      SRCE_SYST_C CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS 'SAP',
      ROW_SECU_ACCS_C INTEGER COMPRESS 0 )
PRIMARY INDEX ( INT_GRUP_I );

-- STAR_CAD_PROD_DATA.DERV_PRTF_ACCT_HIST_PSST -> STAR_CAD_PROD_DATA.DERV_PRTF_ACCT_HIST_PSST
/* <sc-table> STAR_CAD_PROD_DATA.DERV_PRTF_ACCT_HIST_PSST </sc-table> */
CREATE MULTISET TABLE STAR_CAD_PROD_DATA.DERV_PRTF_ACCT_HIST_PSST ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      INT_GRUP_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      ACCT_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      REL_C CHAR(5) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ('CPOC ','JABP ','RLMT ','RMGR ','TRBN '),
      JOIN_FROM_D DATE FORMAT 'yyyy-mm-dd',
      JOIN_TO_D DATE FORMAT 'yyyy-mm-dd',
      VALD_FROM_D DATE FORMAT 'yyyy-mm-dd',
      VALD_TO_D DATE FORMAT 'yyyy-mm-dd',
      EFFT_D DATE FORMAT 'yyyy-mm-dd',
      EXPY_D DATE FORMAT 'yyyy-mm-dd',
      SRCE_SYST_C CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS 'SAP',
      ROW_SECU_ACCS_C INTEGER COMPRESS 0 )
PRIMARY INDEX ( INT_GRUP_I );

-- STAR_CAD_PROD_DATA.DERV_PRTF_ACCT_INT_GRUP_PSST -> STAR_CAD_PROD_DATA.DERV_PRTF_ACCT_INT_GRUP_PSST
/* <sc-table> STAR_CAD_PROD_DATA.DERV_PRTF_ACCT_INT_GRUP_PSST </sc-table> */
CREATE MULTISET TABLE STAR_CAD_PROD_DATA.DERV_PRTF_ACCT_INT_GRUP_PSST ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      INT_GRUP_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      ACCT_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      EFFT_D DATE FORMAT 'yyyy-mm-dd',
      EXPY_D DATE FORMAT 'yyyy-mm-dd',
      VALD_FROM_D DATE FORMAT 'yyyy-mm-dd',
      VALD_TO_D DATE FORMAT 'yyyy-mm-dd',
      PERD_D DATE FORMAT 'yyyy-mm-dd',
      REL_C CHAR(5) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ('CPOC ','JABP ','RLMT ','RMGR ','TRBN '),
      SRCE_SYST_C CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS 'SAP',
      ROW_N DECIMAL(10,0),
      ROW_SECU_ACCS_C INTEGER COMPRESS 0 ,
      PROS_KEY_I DECIMAL(10,0))
PRIMARY INDEX ( INT_GRUP_I ,ACCT_I ,PERD_D );

-- STAR_CAD_PROD_DATA.DERV_PRTF_ACCT_OWN_REL -> P_P01_STAR_CAD_PROD_DATA.DERV_PRTF_ACCT_OWN_REL
/* <sc-table> P_P01_STAR_CAD_PROD_DATA.DERV_PRTF_ACCT_OWN_REL </sc-table> */
CREATE MULTISET TABLE P_P01_STAR_CAD_PROD_DATA.DERV_PRTF_ACCT_OWN_REL ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      ACCT_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Account Identifier' NOT NULL,
      INT_GRUP_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Interest Group Identifier' NOT NULL,
      DERV_PRTF_CATG_C VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Derived Portfolio Catgeory Code',
      DERV_PRTF_CLAS_C VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Derived Portfolio Class Code',
      DERV_PRTF_TYPE_C CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Derived Portfolio Type Code' COMPRESS ('JABP','RLMT','RMGR','SALE'),
      PRTF_ACCT_VALD_FROM_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Portfolio Account Valid From Date',
      PRTF_ACCT_VALD_TO_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Portfolio Account Valid To Date',
      PRTF_ACCT_EFFT_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Portfolio Account Effective Date',
      PRTF_ACCT_EXPY_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Portfolio Account Expiry Date',
      PRTF_OWN_VALD_FROM_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Portfolio Owner Valid From Date',
      PRTF_OWN_VALD_TO_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Portfolio Owner Valid To Date',
      PRTF_OWN_EFFT_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Portfolio Owner Effective Date',
      PRTF_OWN_EXPY_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Portfolio Owner Expiry Date',
      PTCL_N SMALLINT TITLE 'Point Of Control Number',
      REL_MNGE_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Relationship Manager Identifier',
      PRTF_CODE_X VARCHAR(265) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Portfolio Code Description',
      DERV_PRTF_ROLE_C CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Derived Portfolio Role Code' COMPRESS ('AOWN','ASTT','OWNR','STDP'),
      ROLE_PLAY_TYPE_X VARCHAR(40) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Role Player Type Description',
      ROLE_PLAY_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Role Player Identifier' NOT NULL,
      SRCE_SYST_C CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Source System Code' COMPRESS 'SAP',
      ROW_SECU_ACCS_C INTEGER TITLE 'Row Security Access Code' NOT NULL DEFAULT 0  COMPRESS 0 )
PRIMARY INDEX XIE1DERV_PRTF_ACCT_OWN_REL ( ACCT_I );

-- STAR_CAD_PROD_DATA.DERV_PRTF_ACCT_OWN_REL -> STAR_CAD_PROD_DATA.DERV_PRTF_ACCT_OWN_REL
/* <sc-table> STAR_CAD_PROD_DATA.DERV_PRTF_ACCT_OWN_REL </sc-table> */
CREATE MULTISET TABLE STAR_CAD_PROD_DATA.DERV_PRTF_ACCT_OWN_REL ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      ACCT_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Account Identifier' NOT NULL,
      INT_GRUP_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Interest Group Identifier' NOT NULL,
      DERV_PRTF_CATG_C VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Derived Portfolio Catgeory Code',
      DERV_PRTF_CLAS_C VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Derived Portfolio Class Code',
      DERV_PRTF_TYPE_C CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Derived Portfolio Type Code' COMPRESS ('JABP','RLMT','RMGR','SALE'),
      PRTF_ACCT_VALD_FROM_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Portfolio Account Valid From Date',
      PRTF_ACCT_VALD_TO_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Portfolio Account Valid To Date',
      PRTF_ACCT_EFFT_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Portfolio Account Effective Date',
      PRTF_ACCT_EXPY_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Portfolio Account Expiry Date',
      PRTF_OWN_VALD_FROM_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Portfolio Owner Valid From Date',
      PRTF_OWN_VALD_TO_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Portfolio Owner Valid To Date',
      PRTF_OWN_EFFT_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Portfolio Owner Effective Date',
      PRTF_OWN_EXPY_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Portfolio Owner Expiry Date',
      PTCL_N SMALLINT TITLE 'Point Of Control Number',
      REL_MNGE_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Relationship Manager Identifier',
      PRTF_CODE_X VARCHAR(265) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Portfolio Code Description',
      DERV_PRTF_ROLE_C CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Derived Portfolio Role Code' COMPRESS ('AOWN','ASTT','OWNR','STDP'),
      ROLE_PLAY_TYPE_X VARCHAR(40) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Role Player Type Description',
      ROLE_PLAY_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Role Player Identifier' NOT NULL,
      SRCE_SYST_C CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Source System Code' COMPRESS 'SAP',
      ROW_SECU_ACCS_C INTEGER TITLE 'Row Security Access Code' NOT NULL DEFAULT 0  COMPRESS 0 )
PRIMARY INDEX XIE1DERV_PRTF_ACCT_OWN_REL ( ACCT_I );

-- STAR_CAD_PROD_DATA.DERV_PRTF_ACCT_PSST -> STAR_CAD_PROD_DATA.DERV_PRTF_ACCT_PSST
/* <sc-table> STAR_CAD_PROD_DATA.DERV_PRTF_ACCT_PSST </sc-table> */
CREATE MULTISET TABLE STAR_CAD_PROD_DATA.DERV_PRTF_ACCT_PSST ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      INT_GRUP_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      ACCT_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      REL_C CHAR(5) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ('CPOC ','JABP ','RLMT ','RMGR ','TRBN '),
      JOIN_FROM_D DATE FORMAT 'yyyy-mm-dd',
      JOIN_TO_D DATE FORMAT 'yyyy-mm-dd',
      VALD_FROM_D DATE FORMAT 'yyyy-mm-dd',
      VALD_TO_D DATE FORMAT 'yyyy-mm-dd',
      EFFT_D DATE FORMAT 'yyyy-mm-dd',
      EXPY_D DATE FORMAT 'yyyy-mm-dd',
      SRCE_SYST_C CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS 'SAP',
      PROS_KEY_I DECIMAL(10,0),
      ROW_SECU_ACCS_C INTEGER COMPRESS 0 )
PRIMARY INDEX ( ACCT_I )
INDEX ( INT_GRUP_I );

-- STAR_CAD_PROD_DATA.DERV_PRTF_INT_GRUP_ENHC_PSST -> STAR_CAD_PROD_DATA.DERV_PRTF_INT_GRUP_ENHC_PSST
/* <sc-table> STAR_CAD_PROD_DATA.DERV_PRTF_INT_GRUP_ENHC_PSST </sc-table> */
CREATE MULTISET TABLE STAR_CAD_PROD_DATA.DERV_PRTF_INT_GRUP_ENHC_PSST ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      INT_GRUP_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      INT_GRUP_TYPE_C CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ('JABP','RLMT','RMGR','SALE'),
      EFFT_D DATE FORMAT 'yyyy-mm-dd',
      EXPY_D DATE FORMAT 'yyyy-mm-dd',
      VALD_FROM_D DATE FORMAT 'yyyy-mm-dd',
      VALD_TO_D DATE FORMAT 'yyyy-mm-dd',
      PERD_D DATE FORMAT 'yyyy-mm-dd',
      PTCL_N CHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC,
      REL_MNGE_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      ROW_N DECIMAL(10,0),
      PROS_KEY_I DECIMAL(10,0))
PRIMARY INDEX ( INT_GRUP_I );

-- STAR_CAD_PROD_DATA.DERV_PRTF_INT_GRUP_OWN_PSST -> STAR_CAD_PROD_DATA.DERV_PRTF_INT_GRUP_OWN_PSST
/* <sc-table> STAR_CAD_PROD_DATA.DERV_PRTF_INT_GRUP_OWN_PSST </sc-table> */
CREATE MULTISET TABLE STAR_CAD_PROD_DATA.DERV_PRTF_INT_GRUP_OWN_PSST ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      INT_GRUP_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      ROLE_PLAY_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      EFFT_D DATE FORMAT 'yyyy-mm-dd',
      EXPY_D DATE FORMAT 'yyyy-mm-dd',
      VALD_FROM_D DATE FORMAT 'yyyy-mm-dd',
      VALD_TO_D DATE FORMAT 'yyyy-mm-dd',
      PERD_D DATE FORMAT 'yyyy-mm-dd',
      ROLE_PLAY_TYPE_X CHAR(40) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ('Department                              ','Employee                                '),
      DERV_PRTF_ROLE_C CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ('AOWN','ASTT','OWNR','STDP'),
      SRCE_SYST_C CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS 'SAP',
      ROW_N DECIMAL(10,0),
      ROW_SECU_ACCS_C INTEGER COMPRESS 0 ,
      PROS_KEY_I DECIMAL(10,0))
PRIMARY INDEX ( INT_GRUP_I );

-- STAR_CAD_PROD_DATA.DERV_PRTF_INT_HIST_PSST -> STAR_CAD_PROD_DATA.DERV_PRTF_INT_HIST_PSST
/* <sc-table> STAR_CAD_PROD_DATA.DERV_PRTF_INT_HIST_PSST </sc-table> */
CREATE MULTISET TABLE STAR_CAD_PROD_DATA.DERV_PRTF_INT_HIST_PSST ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      INT_GRUP_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      INT_GRUP_TYPE_C CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ('JABP','RLMT','RMGR','SALE'),
      EFFT_D DATE FORMAT 'yyyy-mm-dd',
      EXPY_D DATE FORMAT 'yyyy-mm-dd',
      VALD_FROM_D DATE FORMAT 'yyyy-mm-dd',
      VALD_TO_D DATE FORMAT 'yyyy-mm-dd',
      JOIN_FROM_D DATE FORMAT 'yyyy-mm-dd',
      JOIN_TO_D DATE FORMAT 'yyyy-mm-dd',
      PTCL_N CHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC,
      REL_MNGE_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC)
PRIMARY INDEX ( INT_GRUP_I );

-- STAR_CAD_PROD_DATA.DERV_PRTF_INT_PSST -> STAR_CAD_PROD_DATA.DERV_PRTF_INT_PSST
/* <sc-table> STAR_CAD_PROD_DATA.DERV_PRTF_INT_PSST </sc-table> */
CREATE MULTISET TABLE STAR_CAD_PROD_DATA.DERV_PRTF_INT_PSST ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      INT_GRUP_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      INT_GRUP_TYPE_C CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ('JABP','RLMT','RMGR','SALE'),
      JOIN_FROM_D DATE FORMAT 'yyyy-mm-dd',
      JOIN_TO_D DATE FORMAT 'yyyy-mm-dd',
      EFFT_D DATE FORMAT 'yyyy-mm-dd',
      EXPY_D DATE FORMAT 'yyyy-mm-dd',
      PTCL_N CHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC,
      REL_MNGE_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALD_FROM_D DATE FORMAT 'yyyy-mm-dd',
      VALD_TO_D DATE FORMAT 'yyyy-mm-dd',
      PROS_KEY_I DECIMAL(10,0) COMPRESS 0. )
PRIMARY INDEX ( INT_GRUP_I );

-- STAR_CAD_PROD_DATA.DERV_PRTF_INT_PSST -> PTEMP.DERV_PRTF_INT_PSST
/* <sc-table> PTEMP.DERV_PRTF_INT_PSST </sc-table> */
CREATE MULTISET TABLE PTEMP.DERV_PRTF_INT_PSST ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      INT_GRUP_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      INT_GRUP_TYPE_C CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC,
      JOIN_FROM_D DATE FORMAT 'yyyy-mm-dd',
      JOIN_TO_D DATE FORMAT 'yyyy-mm-dd',
      EFFT_D DATE FORMAT 'yyyy-mm-dd',
      EXPY_D DATE FORMAT 'yyyy-mm-dd',
      PTCL_N CHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC,
      REL_MNGE_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      VALD_FROM_D DATE FORMAT 'yyyy-mm-dd',
      VALD_TO_D DATE FORMAT 'yyyy-mm-dd',
      PROS_KEY_I DECIMAL(10,0))
PRIMARY INDEX ( INT_GRUP_I );

-- STAR_CAD_PROD_DATA.DERV_PRTF_OWN_HIST_PSST -> STAR_CAD_PROD_DATA.DERV_PRTF_OWN_HIST_PSST
/* <sc-table> STAR_CAD_PROD_DATA.DERV_PRTF_OWN_HIST_PSST </sc-table> */
CREATE MULTISET TABLE STAR_CAD_PROD_DATA.DERV_PRTF_OWN_HIST_PSST ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      INT_GRUP_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      ROLE_PLAY_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      JOIN_FROM_D DATE FORMAT 'yyyy-mm-dd',
      JOIN_TO_D DATE FORMAT 'yyyy-mm-dd',
      EFFT_D DATE FORMAT 'yyyy-mm-dd',
      EXPY_D DATE FORMAT 'yyyy-mm-dd',
      VALD_FROM_D DATE FORMAT 'yyyy-mm-dd',
      VALD_TO_D DATE FORMAT 'yyyy-mm-dd',
      ROLE_PLAY_TYPE_X CHAR(40) CHARACTER SET LATIN NOT CASESPECIFIC,
      DERV_PRTF_ROLE_C CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ('AOWN','ASTT','OWNR','STDP'),
      SRCE_SYST_C CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS 'SAP',
      ROW_SECU_ACCS_C INTEGER COMPRESS 0 ,
      PROS_KEY_I DECIMAL(10,0))
PRIMARY INDEX ( INT_GRUP_I );

-- STAR_CAD_PROD_DATA.DERV_PRTF_OWN_PSST -> STAR_CAD_PROD_DATA.DERV_PRTF_OWN_PSST
/* <sc-table> STAR_CAD_PROD_DATA.DERV_PRTF_OWN_PSST </sc-table> */
CREATE MULTISET TABLE STAR_CAD_PROD_DATA.DERV_PRTF_OWN_PSST ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      INT_GRUP_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      JOIN_FROM_D DATE FORMAT 'yyyy-mm-dd',
      JOIN_TO_D DATE FORMAT 'yyyy-mm-dd',
      VALD_FROM_D DATE FORMAT 'yyyy-mm-dd',
      VALD_TO_D DATE FORMAT 'yyyy-mm-dd',
      EFFT_D DATE FORMAT 'yyyy-mm-dd',
      EXPY_D DATE FORMAT 'yyyy-mm-dd',
      DERV_PRTF_ROLE_C CHAR(4) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS ('AOWN','ASTT','OWNR','STDP'),
      ROLE_PLAY_TYPE_X VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC,
      ROLE_PLAY_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      SRCE_SYST_C CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC,
      ROW_SECU_ACCS_C INTEGER COMPRESS 0 ,
      PROS_KEY_I DECIMAL(10,0))
PRIMARY INDEX ( INT_GRUP_I ,PROS_KEY_I );

-- STAR_CAD_PROD_DATA.DERV_PRTF_PATY_HIST_PSST -> STAR_CAD_PROD_DATA.DERV_PRTF_PATY_HIST_PSST
/* <sc-table> STAR_CAD_PROD_DATA.DERV_PRTF_PATY_HIST_PSST </sc-table> */
CREATE MULTISET TABLE STAR_CAD_PROD_DATA.DERV_PRTF_PATY_HIST_PSST ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      INT_GRUP_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      PATY_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      REL_C CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ('RLMT','RMGR'),
      JOIN_FROM_D DATE FORMAT 'yyyy-mm-dd',
      JOIN_TO_D DATE FORMAT 'yyyy-mm-dd',
      VALD_FROM_D DATE FORMAT 'yyyy-mm-dd',
      VALD_TO_D DATE FORMAT 'yyyy-mm-dd',
      EFFT_D DATE FORMAT 'yyyy-mm-dd',
      EXPY_D DATE FORMAT 'yyyy-mm-dd',
      SRCE_SYST_C CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS 'SAP',
      ROW_SECU_ACCS_C INTEGER COMPRESS 0 ,
      PROS_KEY_I DECIMAL(10,0))
PRIMARY INDEX ( INT_GRUP_I );

-- STAR_CAD_PROD_DATA.DERV_PRTF_PATY_INT_GRUP_PSST -> STAR_CAD_PROD_DATA.DERV_PRTF_PATY_INT_GRUP_PSST
/* <sc-table> STAR_CAD_PROD_DATA.DERV_PRTF_PATY_INT_GRUP_PSST </sc-table> */
CREATE MULTISET TABLE STAR_CAD_PROD_DATA.DERV_PRTF_PATY_INT_GRUP_PSST ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      INT_GRUP_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      PATY_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      EFFT_D DATE FORMAT 'yyyy-mm-dd',
      EXPY_D DATE FORMAT 'yyyy-mm-dd',
      VALD_FROM_D DATE FORMAT 'yyyy-mm-dd',
      VALD_TO_D DATE FORMAT 'yyyy-mm-dd',
      PERD_D DATE FORMAT 'yyyy-mm-dd',
      REL_C CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ('RLMT','RMGR'),
      SRCE_SYST_C CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS 'SAP',
      ROW_N DECIMAL(10,0),
      ROW_SECU_ACCS_C INTEGER COMPRESS 0 ,
      PROS_KEY_I DECIMAL(10,0))
PRIMARY INDEX ( INT_GRUP_I );

-- STAR_CAD_PROD_DATA.DERV_PRTF_PATY_OWN_REL -> STAR_CAD_PROD_DATA.DERV_PRTF_PATY_OWN_REL
/* <sc-table> STAR_CAD_PROD_DATA.DERV_PRTF_PATY_OWN_REL </sc-table> */
CREATE MULTISET TABLE STAR_CAD_PROD_DATA.DERV_PRTF_PATY_OWN_REL ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      PATY_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Party Identifier' NOT NULL,
      INT_GRUP_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Interest Group Identifier' NOT NULL,
      DERV_PRTF_CATG_C VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Derived Portfolio Category Code',
      DERV_PRTF_CLAS_C VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Derived Portfolio Class Code',
      DERV_PRTF_TYPE_C CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Derived Portfolio Type Code' COMPRESS ('JABP','RLMT','RMGR','SALE'),
      PRTF_PATY_VALD_FROM_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Portfolio Party Valid From Date',
      PRTF_PATY_VALD_TO_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Portfolio Party Valid To Date',
      PRTF_PATY_EFFT_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Portfolio Party Effective Date ',
      PRTF_PATY_EXPY_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Portfolio Party Expiry Date ',
      PRTF_OWN_VALD_FROM_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Portfolio Owner Valid From Date',
      PRTF_OWN_VALD_TO_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Portfolio Owner Valid To Date',
      PRTF_OWN_EFFT_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Portfolio Owner Effective Date',
      PRTF_OWN_EXPY_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Portfolio Owner Expiry Date',
      PTCL_N SMALLINT TITLE 'Point Of Control Number',
      REL_MNGE_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Relationship Manager Identifier',
      PRTF_CODE_X VARCHAR(265) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Portfolio Code Description',
      DERV_PRTF_ROLE_C CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Derived Portfolio Role Code' COMPRESS ('AOWN','ASTT','OWNR','STDP'),
      ROLE_PLAY_TYPE_X VARCHAR(40) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Role Player Type Description',
      ROLE_PLAY_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Role Player Identifier' NOT NULL,
      SRCE_SYST_C CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Source System Code' COMPRESS 'SAP',
      ROW_SECU_ACCS_C INTEGER TITLE 'Row Security Access Code' NOT NULL DEFAULT 0  COMPRESS 0 )
PRIMARY INDEX XIE2DERV_PRTF_PATY_OWN_REL ( PATY_I );

