{{ config(materialized='view', tags=['XfmTu_ApptPdctFnddInssFrmExt']) }}

WITH CpyRename AS (
	SELECT
		TU_APP_ID,
		FUNDING_DATE,
		TU_APP_FUNDING_DETAIL_ID,
		TU_APP_FUNDING_ID,
		FUNDING_CBA_ACCOUNT_ID,
		{{ ref('TgtApptPdctFnddInssPremapDS') }}.FUNDING_NONCBA_BANK_NUMBER AS INSN_ID,
		FUNDING_NONCBA_INST_NAME,
		FUNDING_NONCBA_INST_ADDRESS,
		FUNDING_NONCBA_BSB,
		FUNDING_NONCBA_ACCOUNT_NUMBER,
		FUNDING_NONCBA_ACCOUNT_NAME,
		FUNDING_BANKCHEQUE_NUMBER,
		FUNDING_BANKCHEQUE_PAYEE,
		{{ ref('TgtApptPdctFnddInssPremapDS') }}.FUNDING_METHOD_CAT_ID AS FNDD_METH_CAT_ID,
		FUNDING_BANKCHEQUE_CBAACCOUNT,
		PROGRESSIVE_PAYMENT_AMT,
		SBTY_CODE,
		HL_APP_PROD_ID,
		ORIG_ETL_D
	FROM {{ ref('TgtApptPdctFnddInssPremapDS') }}
)

SELECT * FROM CpyRename