{{ config(materialized='view', tags=['XfmTu_ApptPdctFnddInssFrmExt']) }}

WITH ModNullHandling AS (
	SELECT 
	--Manual
	--FNDD_INSS_METH_C= handle_null(FNDD_INSS_METH_C,'9999')
	--CMPE_I= handle_null(CMPE_I,'UNKN')
	TU_APP_ID, FUNDING_DATE, TU_APP_FUNDING_DETAIL_ID, TU_APP_FUNDING_ID, FUNDING_CBA_ACCOUNT_ID, FUNDING_NONCBA_INSTITUTION_ID AS FUNDING_NONCBA_BANK_NUMBER, FUNDING_NONCBA_INST_NAME, FUNDING_NONCBA_INST_ADDRESS, FUNDING_NONCBA_BSB, FUNDING_NONCBA_ACCOUNT_NUMBER, FUNDING_NONCBA_ACCOUNT_NAME, FUNDING_BANKCHEQUE_NUMBER, FUNDING_BANKCHEQUE_PAYEE, FUNDING_METHOD_CAT_ID, FUNDING_BANKCHEQUE_CBAACCOUNT, PROGRESSIVE_PAYMENT_AMT, SBTY_CODE, HL_APP_PROD_ID, ORIG_ETL_D, APPT_QLFY_C, FNDD_INSS_METH_C, CMPE_I 
	FROM {{ ref('LkpReferences') }}
)

SELECT * FROM ModNullHandling