{{ config(materialized='view', tags=['DltAPPT_ORIGFrmTMP_APPR_ORIG']) }}

WITH 
appt_orig AS (
	SELECT
	*
	FROM {{ ref("appt_orig")  }}),
tmp_appt_orig AS (
	SELECT
	*
	FROM {{ ref("tmp_appt_orig")  }}),
tc_ApptOrig AS (SELECT A.APPT_I, CASE WHEN B.APPT_I IS NULL THEN CURRENT_DATE ELSE B.EFFT_D END AS EFFT_D, A.EXPY_D, A.PROS_KEY_EFFT_I, A.PROS_KEY_EXPY_I, A.ROW_SECU_ACCS_C, A.SRCE_SYST_C, A.APPT_ORIG_C, A.APPT_ORIG_CATG_C, CASE WHEN B.APPT_I IS NULL THEN 'I' WHEN NOT B.APPT_I IS NULL AND COALESCE(A.APPT_ORIG_C, 'T') <> COALESCE(B.APPT_ORIG_C, 'T') THEN 'U' ELSE 'R' END AS IND_FLAG FROM TMP_APPT_ORIG LEFT OUTER JOIN (SELECT APPT_I, EFFT_D, EXPY_D, PROS_KEY_EFFT_I, PROS_KEY_EXPY_I, ROW_SECU_ACCS_C, SRCE_SYST_C, APPT_ORIG_C, APPT_ORIG_CATG_C FROM APPT_ORIG WHERE EXPY_D = '9999-12-31' AND SRCE_SYST_C = 'CSE') AS B ON A.APPT_I = B.APPT_I AND A.APPT_ORIG_CATG_C = B.APPT_ORIG_CATG_C WHERE IND_FLAG <> 'R')


SELECT * FROM tc_ApptOrig