{{ config(materialized='view', tags=['DltAPPT_PDCT_UNID_PATY_FrmTMP_APPT_PDCT_UNID_PATY']) }}

WITH 
appt_pdct_unid_paty AS (
	SELECT
	*
	FROM {{ ref("appt_pdct_unid_paty")  }}),
tmp_appt_pdct_unid_paty AS (
	SELECT
	*
	FROM {{ ref("tmp_appt_pdct_unid_paty")  }}),
SrcTmpApptPdctUnidPatyTera AS (SELECT a.APPT_PDCT_I AS NEW_APPT_PDCT_I, a.PATY_ROLE_C AS NEW_PATY_ROLE_C, a.SRCE_SYST_PATY_I AS NEW_SRCE_SYST_PATY_I, a.SRCE_SYST_C AS NEW_SRCE_SYST_C, a.UNID_PATY_CATG_C AS NEW_UNID_PATY_CATG_C, a.PATY_M AS NEW_PATY_M, b.APPT_PDCT_I AS OLD_APPT_PDCT_I, b.PATY_ROLE_C AS OLD_PATY_ROLE_C, b.EFFT_D AS OLD_EFFT_D, b.UNID_PATY_CATG_C AS OLD_UNID_PATY_CATG_C, b.SRCE_SYST_PATY_I AS OLD_SRCE_SYST_PATY_I, b.PATY_M AS OLD_PATY_M FROM TMP_APPT_PDCT_UNID_PATY LEFT OUTER JOIN APPT_PDCT_UNID_PATY ON TRIM(a.APPT_PDCT_I) = TRIM(b.APPT_PDCT_I) AND TRIM(a.PATY_ROLE_C) = TRIM(b.PATY_ROLE_C) AND b.EXPY_D = '9999-12-31' AND b.SRCE_SYST_C = 'CSE' AND b.PATY_ROLE_C = 'TPHM' WHERE a.RUN_STRM = '{{ var("RUN_STREAM") }}')


SELECT * FROM SrcTmpApptPdctUnidPatyTera