SHOW TABLE K_STAR_CAD_PROD_DATA.APPT_DEPT;

CREATE SET TABLE K_STAR_CAD_PROD_DATA.APPT_DEPT ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      APPT_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Application Identifier' NOT NULL,
      DEPT_ROLE_C CHAR(5) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Department Role Code' NOT NULL,
      EFFT_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Effective Date' NOT NULL,
      DEPT_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Department Identifier' NOT NULL,
      EXPY_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Expiry Date' NOT NULL DEFAULT DATE '9999-12-31' COMPRESS (DATE '9999-12-31'),
      PROS_KEY_EFFT_I DECIMAL(10,0) TITLE 'Process Key Effective Identifier' NOT NULL,
      PROS_KEY_EXPY_I DECIMAL(10,0) TITLE 'Process Key Expiry Identifier' COMPRESS ,
      EROR_SEQN_I DECIMAL(10,0) TITLE 'Error Sequence Identifier' COMPRESS 0. ,
      BRCH_N SMALLINT TITLE 'Branch Number' DEFAULT NULL ,
      SRCE_SYST_C CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Source System Code' DEFAULT NULL  COMPRESS 'CSE',
      CHNG_REAS_C CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Change Reason Code' DEFAULT NULL  COMPRESS ('NOMB','OTRB','RMDC'))
PRIMARY INDEX XIE1APPT_DEPT ( APPT_I );


SHOW TABLE K_STAR_CAD_PROD_DATA.DEPT_APPT;

CREATE SET TABLE K_STAR_CAD_PROD_DATA.DEPT_APPT ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      DEPT_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Department Identifier' NOT NULL,
      APPT_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Application Identifier' NOT NULL,
      DEPT_ROLE_C CHAR(5) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Department Role Code' NOT NULL,
      EFFT_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Effective Date' NOT NULL,
      EXPY_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Expiry date' NOT NULL DEFAULT DATE '9999-12-31' COMPRESS (DATE '9999-12-31'),
      PROS_KEY_EFFT_I DECIMAL(10,0) TITLE 'Process Key Effective Identifier' NOT NULL,
      PROS_KEY_EXPY_I DECIMAL(10,0) TITLE 'Process Key Expiry Identifier' COMPRESS ,
      EROR_SEQN_I DECIMAL(10,0) TITLE 'Error Sequence Identifier' COMPRESS 0. ,
      BRCH_N SMALLINT TITLE 'Branch Number' DEFAULT NULL ,
      SRCE_SYST_C CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Source System Code' DEFAULT NULL  COMPRESS 'CSE',
      CHNG_REAS_C CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Change Reason Code' DEFAULT NULL  COMPRESS ('NOMB','OTRB','RMDC'))
PRIMARY INDEX XIE1DEPT_APPT ( DEPT_I ,APPT_I );

SHOW TABLE K_STAR_CAD_PROD_DATA.APPT_PDCT;

CREATE SET TABLE K_STAR_CAD_PROD_DATA.APPT_PDCT ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      APPT_PDCT_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Application Product Identifier' NOT NULL,
      APPT_QLFY_C CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Application Qualifier Code' COMPRESS ('CC','CL','HL','HP','LP','PL','PP'),
      ACQR_TYPE_C CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Acquisition Type Code' COMPRESS ,
      ACQR_ADHC_X VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Acquisition Ad Hoc Comment',
      ACQR_SRCE_C CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Acquisition Source Code' COMPRESS ('CBA ','IRS ','OTH '),
      PDCT_N INTEGER TITLE 'Product Number' NOT NULL COMPRESS (192001 ,21509 ,800009 ,800013 ,1062 ,23614 ,23910 ,720000 ,720032 ,228017 ,720058 ,3003 ,720059 ,720060 ,907002 ),
      APPT_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Application Identifier' NOT NULL,
      SRCE_SYST_C CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Source System Code' NOT NULL COMPRESS 'CSE',
      SRCE_SYST_APPT_PDCT_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Source System Application Product Identifier' NOT NULL,
      LOAN_FNDD_METH_C CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Loan Funding Method Code' COMPRESS ('BCHQ','ECBA','NCBA'),
      NEW_ACCT_F CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'New Account Flag' COMPRESS (' ','N','Y'),
      BROK_PATY_I VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Broker Party Identifier',
      COPY_FROM_OTHR_APPT_F CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Copy From Other Application Flag' DEFAULT 'N' COMPRESS ('N','Y'),
      EFFT_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Effective Date' NOT NULL,
      EXPY_D DATE FORMAT 'YYYY-MM-DD' TITLE 'Expiry date' NOT NULL DEFAULT DATE '9999-12-31' COMPRESS (DATE '9999-12-31'),
      PROS_KEY_EFFT_I DECIMAL(10,0) TITLE 'Process Key Effective Identfier' NOT NULL,
      PROS_KEY_EXPY_I DECIMAL(10,0) TITLE 'Process Key Expiry Identifier' COMPRESS ,
      EROR_SEQN_I DECIMAL(10,0) TITLE 'Error Sequence Identifier' COMPRESS 0. ,
      JOB_COMM_CATG_C CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'JOB COMMISSION CATEGORY CODE' COMPRESS ('0001','0002','0003','0007','0008','0009','0010','0011','0012','0013','0014','0015','0016','0017','0018'),
      DEBT_ABN_X VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      DEBT_BUSN_M VARCHAR(40) CHARACTER SET LATIN NOT CASESPECIFIC,
      SMPL_APPT_F CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC DEFAULT NULL  COMPRESS ('N','Y'),
      APPT_PDCT_CATG_C CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC DEFAULT 'UNKN' COMPRESS ('0001','0002','UNKN'),
      APPT_PDCT_DURT_C CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC DEFAULT 'UNKN' COMPRESS ('0001','0002','UNKN'),
      ASES_D DATE FORMAT 'YYYY-MM-DD' DEFAULT NULL  COMPRESS )
PRIMARY INDEX XIE1APPT_PDCT ( APPT_I );

