{{ config(materialized='view', tags=['XfmCSE_CCL_BUS_APP_FEEFrmExt']) }}

WITH ModNullHandling AS (
	SELECT 
	--Manual
	--TARG_CHAR_C = handle_null(TARG_CHAR_C,'999010')
	--FREQ_IN_MTHS = handle_null(FREQ_IN_MTHS,9999)
	CCL_APP_FEE_ID, CCL_APP_FEE_CCL_APP_ID, CCL_APP_FEE_CCL_APP_PROD_ID, CCL_APP_FEE_CHARGE_AMT, CCL_APP_FEE_CHARGE_DATE, CCL_APP_FEE_CONCESSION_FLAG, CCL_APP_FEE_CONCESSION_REASON, CCL_APP_FEE_OVERRIDE_FEE_PCT, CCL_APP_FEE_OVERRIDE_FEE_PCT_FREQ, CCL_APP_FEE_FEE_REPAYMENT_FREQ, CCL_APP_FEE_TYPE_CAT_ID, CCL_APP_FEE_CHARGE_EXTERNAL_FLAG, CCL_FEE_TYPE_CAT_ID, CCL_FEE_TYPE_CAT_DEFAULT_AMT, CCL_FEE_TYPE_CAT_DEFAULT_FEE_PCT, CCL_FEE_TYPE_CAT_FEE_TYPE_DESC, ORIG_ETL_D, MAP_TYPE_C, FREQ_IN_MTHS, TARG_NUMC_C AS TARG_CHAR_C 
	FROM {{ ref('LkpReferences') }}
)

SELECT * FROM ModNullHandling