{{ config(materialized='view', tags=['ExtHL_APP_Adhoc']) }}

WITH CpyHlApponeoffSeq AS (
	SELECT
		{{ ref('SrcChlBusApp_oneoff') }}.CHL_APP_HL_APP_ID AS HL_APP_ID,
		HL_APP_PROD_ID,
		{{ ref('SrcChlBusApp_oneoff') }}.CHL_APP_HL_PACKAGE_CAT_ID AS HL_PACKAGE_CAT_ID,
		{{ ref('SrcChlBusApp_oneoff') }}.CHL_APP_LPC_OFFICE AS LPC_OFFICE,
		{{ ref('SrcChlBusApp_oneoff') }}.CHL_APP_STATUS_TRACKER_ID AS STATUS_TRACKER_ID,
		{{ ref('SrcChlBusApp_oneoff') }}.CHL_APP_PCD_EXTERNAL_SYS_CAT_ID AS CHL_APP_PCD_EXT_SYS_CAT_ID,
		CHL_APP_SIMPLE_APP_FLAG,
		CHL_APP_ORIGINATING_AGENT_ID,
		CHL_APP_AGENT_NAME,
		CASS_WITHHOLD_RISKBANK_FLAG,
		CR_DATE,
		ASSESSMENT_DATE,
		NCPR_FLAG,
		CAMPAIGN_CODE,
		FHB_FLAG,
		SETTLEMENT_DATE,
		PEXA_FLAG,
		HSCA_FLAG,
		HSCA_CONVERTED_TO_FULL_AT
	FROM {{ ref('SrcChlBusApp_oneoff') }}
)

SELECT * FROM CpyHlApponeoffSeq