{{ config(materialized='view', tags=['XfmPlFeePlMarginFrmExt']) }}

WITH CpyRename AS (
	SELECT
		PL_FEE_ID,
		PL_APP_PROD_ID,
		PL_FEE_PL_FEE_ID,
		PL_FEE_ADD_TO_TOTAL_FLAG,
		PL_FEE_FEE_AMT,
		PL_FEE_BASE_FEE_AMT,
		PL_FEE_PAY_FEE_AT_FUNDING_FLAG,
		PL_FEE_START_DATE,
		{{ ref('CgAddMapTypeC') }}.PL_FEE_PL_CAPITALIS_FEE_CAT_ID AS PL_CAPL_FEE_CAT_ID,
		{{ ref('CgAddMapTypeC') }}.PL_FEE_FEE_SCREEN_DESC AS SRCE_CHAR_1_C,
		PL_FEE_FEE_DESC,
		PL_FEE_CASS_FEE_CODE,
		PL_FEE_CASS_FEE_KEY,
		PL_FEE_TOTAL_FEE_AMT,
		PL_FEE_PL_APP_PROD_ID,
		PL_MARGIN_PL_MARGIN_ID,
		PL_MARGIN_MARGIN_AMT,
		PL_MARGIN_PL_FEE_ID,
		PL_MARGIN_PL_INT_RATE_ID,
		{{ ref('CgAddMapTypeC') }}.PL_MARGIN_MARGIN_REASON_CAT_ID AS MARG_REAS_CAT_ID,
		PL_MARGIN_PL_APP_PROD_ID,
		PL_FEE_FOUND_FLAG,
		PL_MARGIN_FOUND_FLAG,
		ORIG_ETL_D,
		MAP_TYPE_C
	FROM {{ ref('CgAddMapTypeC') }}
)

SELECT * FROM CpyRename