{{ config(materialized='view', tags=['XfmApptPdctAcctToTmp']) }}

WITH Funnel AS (
	SELECT
		APPT_PDCT_I as APPT_PDCT_I,
		ACCOUNT_NUMBER as ACCOUNT_NUMBER,
		REPAYMENT_ACCOUNT_NUMBER as REPAYMENT_ACCOUNT_NUMBER,
		REL_TYPE_C as REL_TYPE_C,
		EFFT_D as EFFT_D,
		EXPY_D as EXPY_D,
		PROS_KEY_EFFT_I as PROS_KEY_EFFT_I,
		PROS_KEY_EXPY_I as PROS_KEY_EXPY_I,
		EROR_SEQN_I as EROR_SEQN_I,
		ERR_FLG as ERR_FLG
	FROM {{ ref('AccNum__AccntNmbr') }}
	UNION ALL
	SELECT
		APPT_PDCT_I,
		ACCOUNT_NUMBER,
		REPAYMENT_ACCOUNT_NUMBER,
		REL_TYPE_C,
		EFFT_D,
		EXPY_D,
		PROS_KEY_EFFT_I,
		PROS_KEY_EXPY_I,
		EROR_SEQN_I,
		ERR_FLG
	FROM {{ ref('AccNum__RpayAccntNmbr') }}
)

SELECT * FROM Funnel