{{ config(materialized='view', tags=['ExtDelRecInfo']) }}

WITH DedupeDelRecs AS (
	SELECT DELETED_RECORDS_INFO_ID, DELETED_TIMESTAMP, DELETED_TABLE_OWNER, DELETED_TABLE_NAME, DELETED_KEY_1, DELETED_KEY_1_VALUE, DELETED_KEY_2, DELETED_KEY_2_VALUE, DELETED_KEY_3, DELETED_KEY_3_VALUE, DELETED_KEY_4, DELETED_KEY_4_VALUE, DELETED_KEY_5, DELETED_KEY_5_VALUE 
	FROM (
		SELECT DELETED_RECORDS_INFO_ID, DELETED_TIMESTAMP, DELETED_TABLE_OWNER, DELETED_TABLE_NAME, DELETED_KEY_1, DELETED_KEY_1_VALUE, DELETED_KEY_2, DELETED_KEY_2_VALUE, DELETED_KEY_3, DELETED_KEY_3_VALUE, DELETED_KEY_4, DELETED_KEY_4_VALUE, DELETED_KEY_5, DELETED_KEY_5_VALUE,
		 ROW_NUMBER() OVER (PARTITION BY DELETED_TABLE_NAME, DELETED_KEY_1, DELETED_KEY_1_VALUE, DELETED_KEY_2, DELETED_KEY_2_VALUE, DELETED_KEY_3, DELETED_KEY_3_VALUE, DELETED_KEY_4, DELETED_KEY_4_VALUE, DELETED_KEY_5, DELETED_KEY_5_VALUE ORDER BY 1 DESC) AS ROW_NUM 
		FROM {{ ref('SrcDelRecInfo') }}
	) AS DedupeDelRecs_TEMP
	WHERE ROW_NUM = 1
)

SELECT * FROM DedupeDelRecs