{{ config(materialized='view', tags=['ExtPlIntRatePlMargin']) }}

WITH XfmSeparateRejectWithoutSourceAndTheRest AS (
	SELECT
		-- *SRC*: \(20)If (Len(Trim(( IF IsNotNull((XfmSeparateRejects.PL_INT_RATE_ID)) THEN (XfmSeparateRejects.PL_INT_RATE_ID) ELSE ""))) = 0) Then 'R' Else 'S',
		IFF(LEN(TRIM(IFF({{ ref('JoinSrcSortReject') }}.PL_INT_RATE_ID IS NOT NULL, {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_ID, ''))) = 0, 'R', 'S') AS DeltaFlag,
		-- *SRC*: \(20)If DeltaFlag = 'S' Then XfmSeparateRejects.PL_INT_RATE_ID Else XfmSeparateRejects.PL_INT_RATE_ID_R,
		IFF(DeltaFlag = 'S', {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_ID, {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_ID_R) AS PL_INT_RATE_ID,
		-- *SRC*: \(20)If ( IF IsNotNull((XfmSeparateRejects.PL_INT_RATE_FOUND_FLAG)) THEN (XfmSeparateRejects.PL_INT_RATE_FOUND_FLAG) ELSE "") = 'Y' Then XfmSeparateRejects.PL_INT_RATE_PL_INT_RATE_ID Else XfmSeparateRejects.PL_INT_RATE_PL_INT_RATE_ID_R,
		IFF(IFF({{ ref('JoinSrcSortReject') }}.PL_INT_RATE_FOUND_FLAG IS NOT NULL, {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_FOUND_FLAG, '') = 'Y', {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_PL_INT_RATE_ID, {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_PL_INT_RATE_ID_R) AS PL_INT_RATE_PL_INT_RATE_ID,
		-- *SRC*: \(20)If ( IF IsNotNull((XfmSeparateRejects.PL_INT_RATE_FOUND_FLAG)) THEN (XfmSeparateRejects.PL_INT_RATE_FOUND_FLAG) ELSE "") = 'Y' Then XfmSeparateRejects.PL_INT_RATE_DOC_SEQ_NO Else XfmSeparateRejects.PL_INT_RATE_DOC_SEQ_NO_R,
		IFF(IFF({{ ref('JoinSrcSortReject') }}.PL_INT_RATE_FOUND_FLAG IS NOT NULL, {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_FOUND_FLAG, '') = 'Y', {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_DOC_SEQ_NO, {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_DOC_SEQ_NO_R) AS PL_INT_RATE_DOC_SEQ_NO,
		-- *SRC*: \(20)If ( IF IsNotNull((XfmSeparateRejects.PL_INT_RATE_FOUND_FLAG)) THEN (XfmSeparateRejects.PL_INT_RATE_FOUND_FLAG) ELSE "") = 'Y' Then XfmSeparateRejects.PL_INT_RATE_CASS_MARGIN_AMT Else XfmSeparateRejects.PL_INT_RATE_CASS_MARGIN_AMT_R,
		IFF(IFF({{ ref('JoinSrcSortReject') }}.PL_INT_RATE_FOUND_FLAG IS NOT NULL, {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_FOUND_FLAG, '') = 'Y', {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_CASS_MARGIN_AMT, {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_CASS_MARGIN_AMT_R) AS PL_INT_RATE_CASS_MARGIN_AMT,
		-- *SRC*: \(20)If ( IF IsNotNull((XfmSeparateRejects.PL_INT_RATE_FOUND_FLAG)) THEN (XfmSeparateRejects.PL_INT_RATE_FOUND_FLAG) ELSE "") = 'Y' Then XfmSeparateRejects.PL_INT_RATE_INT_RATE_TERM Else XfmSeparateRejects.PL_INT_RATE_INT_RATE_TERM_R,
		IFF(IFF({{ ref('JoinSrcSortReject') }}.PL_INT_RATE_FOUND_FLAG IS NOT NULL, {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_FOUND_FLAG, '') = 'Y', {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_INT_RATE_TERM, {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_INT_RATE_TERM_R) AS PL_INT_RATE_INT_RATE_TERM,
		-- *SRC*: \(20)If ( IF IsNotNull((XfmSeparateRejects.PL_INT_RATE_FOUND_FLAG)) THEN (XfmSeparateRejects.PL_INT_RATE_FOUND_FLAG) ELSE "") = 'Y' Then XfmSeparateRejects.PL_INT_RATE_INT_RATE_FREQ_ID Else XfmSeparateRejects.PL_INT_RATE_INT_RATE_FREQUENCY_ID_R,
		IFF(IFF({{ ref('JoinSrcSortReject') }}.PL_INT_RATE_FOUND_FLAG IS NOT NULL, {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_FOUND_FLAG, '') = 'Y', {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_INT_RATE_FREQ_ID, {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_INT_RATE_FREQUENCY_ID_R) AS PL_INT_RATE_INT_RATE_FREQ_ID,
		-- *SRC*: \(20)If ( IF IsNotNull((XfmSeparateRejects.PL_INT_RATE_FOUND_FLAG)) THEN (XfmSeparateRejects.PL_INT_RATE_FOUND_FLAG) ELSE "") = 'Y' Then XfmSeparateRejects.PL_INT_RATE_VARIANT_CAT_ID Else XfmSeparateRejects.PL_INT_RATE_VARIANT_CAT_ID_R,
		IFF(IFF({{ ref('JoinSrcSortReject') }}.PL_INT_RATE_FOUND_FLAG IS NOT NULL, {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_FOUND_FLAG, '') = 'Y', {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_VARIANT_CAT_ID, {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_VARIANT_CAT_ID_R) AS PL_INT_RATE_VARIANT_CAT_ID,
		-- *SRC*: \(20)If ( IF IsNotNull((XfmSeparateRejects.PL_INT_RATE_FOUND_FLAG)) THEN (XfmSeparateRejects.PL_INT_RATE_FOUND_FLAG) ELSE "") = 'Y' Then XfmSeparateRejects.PL_INT_RATE_USAGE_CAT_ID Else XfmSeparateRejects.PL_INT_RATE_USAGE_CAT_ID_R,
		IFF(IFF({{ ref('JoinSrcSortReject') }}.PL_INT_RATE_FOUND_FLAG IS NOT NULL, {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_FOUND_FLAG, '') = 'Y', {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_USAGE_CAT_ID, {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_USAGE_CAT_ID_R) AS PL_INT_RATE_USAGE_CAT_ID,
		-- *SRC*: \(20)If ( IF IsNotNull((XfmSeparateRejects.PL_INT_RATE_FOUND_FLAG)) THEN (XfmSeparateRejects.PL_INT_RATE_FOUND_FLAG) ELSE "") = 'Y' Then XfmSeparateRejects.PL_INT_RATE_PL_APP_PROD_ID Else XfmSeparateRejects.PL_INT_RATE_PL_APP_PROD_ID_R,
		IFF(IFF({{ ref('JoinSrcSortReject') }}.PL_INT_RATE_FOUND_FLAG IS NOT NULL, {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_FOUND_FLAG, '') = 'Y', {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_PL_APP_PROD_ID, {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_PL_APP_PROD_ID_R) AS PL_INT_RATE_PL_APP_PROD_ID,
		-- *SRC*: \(20)If ( IF IsNotNull((XfmSeparateRejects.PL_MARGIN_FOUND_FLAG)) THEN (XfmSeparateRejects.PL_MARGIN_FOUND_FLAG) ELSE "") = 'Y' Then XfmSeparateRejects.PL_MARGIN_PL_MARGIN_ID Else XfmSeparateRejects.PL_MARGIN_PL_MARGIN_ID_R,
		IFF(IFF({{ ref('JoinSrcSortReject') }}.PL_MARGIN_FOUND_FLAG IS NOT NULL, {{ ref('JoinSrcSortReject') }}.PL_MARGIN_FOUND_FLAG, '') = 'Y', {{ ref('JoinSrcSortReject') }}.PL_MARGIN_PL_MARGIN_ID, {{ ref('JoinSrcSortReject') }}.PL_MARGIN_PL_MARGIN_ID_R) AS PL_MARGIN_PL_MARGIN_ID,
		-- *SRC*: \(20)If ( IF IsNotNull((XfmSeparateRejects.PL_MARGIN_FOUND_FLAG)) THEN (XfmSeparateRejects.PL_MARGIN_FOUND_FLAG) ELSE "") = 'Y' Then XfmSeparateRejects.PL_MARGIN_MARGIN_AMT Else XfmSeparateRejects.PL_MARGIN_MARGIN_AMT_R,
		IFF(IFF({{ ref('JoinSrcSortReject') }}.PL_MARGIN_FOUND_FLAG IS NOT NULL, {{ ref('JoinSrcSortReject') }}.PL_MARGIN_FOUND_FLAG, '') = 'Y', {{ ref('JoinSrcSortReject') }}.PL_MARGIN_MARGIN_AMT, {{ ref('JoinSrcSortReject') }}.PL_MARGIN_MARGIN_AMT_R) AS PL_MARGIN_MARGIN_AMT,
		-- *SRC*: \(20)If ( IF IsNotNull((XfmSeparateRejects.PL_MARGIN_FOUND_FLAG)) THEN (XfmSeparateRejects.PL_MARGIN_FOUND_FLAG) ELSE "") = 'Y' Then XfmSeparateRejects.PL_MARGIN_PL_FEE_ID Else XfmSeparateRejects.PL_MARGIN_PL_FEE_ID_R,
		IFF(IFF({{ ref('JoinSrcSortReject') }}.PL_MARGIN_FOUND_FLAG IS NOT NULL, {{ ref('JoinSrcSortReject') }}.PL_MARGIN_FOUND_FLAG, '') = 'Y', {{ ref('JoinSrcSortReject') }}.PL_MARGIN_PL_FEE_ID, {{ ref('JoinSrcSortReject') }}.PL_MARGIN_PL_FEE_ID_R) AS PL_MARGIN_PL_FEE_ID,
		-- *SRC*: \(20)If ( IF IsNotNull((XfmSeparateRejects.PL_MARGIN_FOUND_FLAG)) THEN (XfmSeparateRejects.PL_MARGIN_FOUND_FLAG) ELSE "") = 'Y' Then XfmSeparateRejects.PL_MARGIN_PL_INT_RATE_ID Else XfmSeparateRejects.PL_MARGIN_PL_INT_RATE_ID_R,
		IFF(IFF({{ ref('JoinSrcSortReject') }}.PL_MARGIN_FOUND_FLAG IS NOT NULL, {{ ref('JoinSrcSortReject') }}.PL_MARGIN_FOUND_FLAG, '') = 'Y', {{ ref('JoinSrcSortReject') }}.PL_MARGIN_PL_INT_RATE_ID, {{ ref('JoinSrcSortReject') }}.PL_MARGIN_PL_INT_RATE_ID_R) AS PL_MARGIN_PL_INT_RATE_ID,
		-- *SRC*: \(20)If ( IF IsNotNull((XfmSeparateRejects.PL_MARGIN_FOUND_FLAG)) THEN (XfmSeparateRejects.PL_MARGIN_FOUND_FLAG) ELSE "") = 'Y' Then XfmSeparateRejects.PL_MARGIN_MARGIN_RESN_CAT_ID Else XfmSeparateRejects.PL_MARGIN_MARGIN_REASON_CAT_ID_R,
		IFF(IFF({{ ref('JoinSrcSortReject') }}.PL_MARGIN_FOUND_FLAG IS NOT NULL, {{ ref('JoinSrcSortReject') }}.PL_MARGIN_FOUND_FLAG, '') = 'Y', {{ ref('JoinSrcSortReject') }}.PL_MARGIN_MARGIN_RESN_CAT_ID, {{ ref('JoinSrcSortReject') }}.PL_MARGIN_MARGIN_REASON_CAT_ID_R) AS PL_MARGIN_MARGIN_RESN_CAT_ID,
		-- *SRC*: \(20)If ( IF IsNotNull((XfmSeparateRejects.PL_MARGIN_FOUND_FLAG)) THEN (XfmSeparateRejects.PL_MARGIN_FOUND_FLAG) ELSE "") = 'Y' Then XfmSeparateRejects.PL_MARGIN_PL_APP_PROD_ID Else XfmSeparateRejects.PL_MARGIN_PL_APP_PROD_ID_R,
		IFF(IFF({{ ref('JoinSrcSortReject') }}.PL_MARGIN_FOUND_FLAG IS NOT NULL, {{ ref('JoinSrcSortReject') }}.PL_MARGIN_FOUND_FLAG, '') = 'Y', {{ ref('JoinSrcSortReject') }}.PL_MARGIN_PL_APP_PROD_ID, {{ ref('JoinSrcSortReject') }}.PL_MARGIN_PL_APP_PROD_ID_R) AS PL_MARGIN_PL_APP_PROD_ID,
		-- *SRC*: \(20)If ( IF IsNotNull((XfmSeparateRejects.PL_INT_RATE_AMT_FOUND_FLAG)) THEN (XfmSeparateRejects.PL_INT_RATE_AMT_FOUND_FLAG) ELSE "") = 'Y' Then XfmSeparateRejects.PL_INT_RATE_AMT_INT_RTE_AMT_2 Else XfmSeparateRejects.PL_INT_RATE_AMT_INT_RATE_AMT_2_R,
		IFF(IFF({{ ref('JoinSrcSortReject') }}.PL_INT_RATE_AMT_FOUND_FLAG IS NOT NULL, {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_AMT_FOUND_FLAG, '') = 'Y', {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_AMT_INT_RTE_AMT_2, {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_AMT_INT_RATE_AMT_2_R) AS PL_INT_RATE_AMT_INT_RTE_AMT_2,
		-- *SRC*: \(20)If ( IF IsNotNull((XfmSeparateRejects.PL_INT_RATE_AMT_FOUND_FLAG)) THEN (XfmSeparateRejects.PL_INT_RATE_AMT_FOUND_FLAG) ELSE "") = 'Y' Then XfmSeparateRejects.PL_INT_RATE_AMT_INT_RTCT_ID2 Else XfmSeparateRejects.PL_INT_RATE_AMT_PL_INT_RATE_CAT_ID_2_R,
		IFF(IFF({{ ref('JoinSrcSortReject') }}.PL_INT_RATE_AMT_FOUND_FLAG IS NOT NULL, {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_AMT_FOUND_FLAG, '') = 'Y', {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_AMT_INT_RTCT_ID2, {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_AMT_PL_INT_RATE_CAT_ID_2_R) AS PL_INT_RATE_AMT_INT_RTCT_ID2,
		-- *SRC*: \(20)If ( IF IsNotNull((XfmSeparateRejects.PL_INT_RATE_AMT_FOUND_FLAG)) THEN (XfmSeparateRejects.PL_INT_RATE_AMT_FOUND_FLAG) ELSE "") = 'Y' Then XfmSeparateRejects.PL_INT_RATE_AMT_PL_INT_RATE_ID Else XfmSeparateRejects.PL_INT_RATE_AMT_PL_INT_RATE_ID_R,
		IFF(IFF({{ ref('JoinSrcSortReject') }}.PL_INT_RATE_AMT_FOUND_FLAG IS NOT NULL, {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_AMT_FOUND_FLAG, '') = 'Y', {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_AMT_PL_INT_RATE_ID, {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_AMT_PL_INT_RATE_ID_R) AS PL_INT_RATE_AMT_PL_INT_RATE_ID,
		-- *SRC*: \(20)If ( IF IsNotNull((XfmSeparateRejects.PL_INT_RATE_AMT_FOUND_FLAG)) THEN (XfmSeparateRejects.PL_INT_RATE_AMT_FOUND_FLAG) ELSE "") = 'Y' Then XfmSeparateRejects.PL_INT_RATE_AMT_INT_RATE_AMT_1 Else XfmSeparateRejects.PL_INT_RATE_AMT_INT_RATE_AMT_1_R,
		IFF(IFF({{ ref('JoinSrcSortReject') }}.PL_INT_RATE_AMT_FOUND_FLAG IS NOT NULL, {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_AMT_FOUND_FLAG, '') = 'Y', {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_AMT_INT_RATE_AMT_1, {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_AMT_INT_RATE_AMT_1_R) AS PL_INT_RATE_AMT_INT_RATE_AMT_1,
		-- *SRC*: \(20)If ( IF IsNotNull((XfmSeparateRejects.PL_INT_RATE_AMT_FOUND_FLAG)) THEN (XfmSeparateRejects.PL_INT_RATE_AMT_FOUND_FLAG) ELSE "") = 'Y' Then XfmSeparateRejects.PL_INT_RATE_AMT_INT_RTCT_ID1 Else XfmSeparateRejects.PL_INT_RATE_AMT_PL_INT_RATE_CAT_ID_1_R,
		IFF(IFF({{ ref('JoinSrcSortReject') }}.PL_INT_RATE_AMT_FOUND_FLAG IS NOT NULL, {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_AMT_FOUND_FLAG, '') = 'Y', {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_AMT_INT_RTCT_ID1, {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_AMT_PL_INT_RATE_CAT_ID_1_R) AS PL_INT_RATE_AMT_INT_RTCT_ID1,
		-- *SRC*: \(20)If ( IF IsNotNull((XfmSeparateRejects.PL_MARGIN_FOUND_FLAG)) THEN (XfmSeparateRejects.PL_MARGIN_FOUND_FLAG) ELSE "") = 'Y' Then XfmSeparateRejects.PL_MARGIN_FOUND_FLAG Else  If ( IF IsNotNull((XfmSeparateRejects.PL_MARGIN_FOUND_FLAG_R)) THEN (XfmSeparateRejects.PL_MARGIN_FOUND_FLAG_R) ELSE "") = 'Y' Then XfmSeparateRejects.PL_MARGIN_FOUND_FLAG_R Else 'N',
		IFF(
	    IFF({{ ref('JoinSrcSortReject') }}.PL_MARGIN_FOUND_FLAG IS NOT NULL, {{ ref('JoinSrcSortReject') }}.PL_MARGIN_FOUND_FLAG, '') = 'Y', {{ ref('JoinSrcSortReject') }}.PL_MARGIN_FOUND_FLAG, 
	    IFF(IFF({{ ref('JoinSrcSortReject') }}.PL_MARGIN_FOUND_FLAG_R IS NOT NULL, {{ ref('JoinSrcSortReject') }}.PL_MARGIN_FOUND_FLAG_R, '') = 'Y', {{ ref('JoinSrcSortReject') }}.PL_MARGIN_FOUND_FLAG_R, 'N')
	) AS PL_MARGIN_FOUND_FLAG,
		-- *SRC*: \(20)If ( IF IsNotNull((XfmSeparateRejects.PL_INT_RATE_FOUND_FLAG)) THEN (XfmSeparateRejects.PL_INT_RATE_FOUND_FLAG) ELSE "") = 'Y' Then XfmSeparateRejects.PL_INT_RATE_FOUND_FLAG Else  If ( IF IsNotNull((XfmSeparateRejects.PL_INT_RATE_FOUND_FLAG_R)) THEN (XfmSeparateRejects.PL_INT_RATE_FOUND_FLAG_R) ELSE "") = 'Y' Then XfmSeparateRejects.PL_INT_RATE_FOUND_FLAG_R Else 'N',
		IFF(
	    IFF({{ ref('JoinSrcSortReject') }}.PL_INT_RATE_FOUND_FLAG IS NOT NULL, {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_FOUND_FLAG, '') = 'Y', {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_FOUND_FLAG, 
	    IFF(IFF({{ ref('JoinSrcSortReject') }}.PL_INT_RATE_FOUND_FLAG_R IS NOT NULL, {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_FOUND_FLAG_R, '') = 'Y', {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_FOUND_FLAG_R, 'N')
	) AS PL_INT_RATE_FOUND_FLAG,
		-- *SRC*: \(20)If ( IF IsNotNull((XfmSeparateRejects.PL_INT_RATE_AMT_FOUND_FLAG)) THEN (XfmSeparateRejects.PL_INT_RATE_AMT_FOUND_FLAG) ELSE "") = 'Y' Then XfmSeparateRejects.PL_INT_RATE_AMT_FOUND_FLAG Else  If ( IF IsNotNull((XfmSeparateRejects.PL_INT_RATE_AMT_FOUND_FLAG_R)) THEN (XfmSeparateRejects.PL_INT_RATE_AMT_FOUND_FLAG_R) ELSE "") = 'Y' Then XfmSeparateRejects.PL_INT_RATE_AMT_FOUND_FLAG_R Else 'N',
		IFF(
	    IFF({{ ref('JoinSrcSortReject') }}.PL_INT_RATE_AMT_FOUND_FLAG IS NOT NULL, {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_AMT_FOUND_FLAG, '') = 'Y', {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_AMT_FOUND_FLAG, 
	    IFF(IFF({{ ref('JoinSrcSortReject') }}.PL_INT_RATE_AMT_FOUND_FLAG_R IS NOT NULL, {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_AMT_FOUND_FLAG_R, '') = 'Y', {{ ref('JoinSrcSortReject') }}.PL_INT_RATE_AMT_FOUND_FLAG_R, 'N')
	) AS PL_INT_RATE_AMT_FOUND_FLAG,
		-- *SRC*: \(20)If Len(Trim(( IF IsNotNull((XfmSeparateRejects.ORIG_ETL_D_R)) THEN (XfmSeparateRejects.ORIG_ETL_D_R) ELSE ""))) = 0 Then ETL_PROCESS_DT Else XfmSeparateRejects.ORIG_ETL_D_R,
		IFF(LEN(TRIM(IFF({{ ref('JoinSrcSortReject') }}.ORIG_ETL_D_R IS NOT NULL, {{ ref('JoinSrcSortReject') }}.ORIG_ETL_D_R, ''))) = 0, ETL_PROCESS_DT, {{ ref('JoinSrcSortReject') }}.ORIG_ETL_D_R) AS ORIG_ETL_D
	FROM {{ ref('JoinSrcSortReject') }}
	WHERE 
)

SELECT * FROM XfmSeparateRejectWithoutSourceAndTheRest