{{ config(materialized='view', tags=['XfmPlIntRateAmtMarginFrmExt']) }}

WITH ModNullHandling AS (
	SELECT 
	--Manual
	--FEAT_OVRD_REAS_C:nullable string[4] = handle_null (FEAT_OVRD_REAS_C, '9999')
	--PL_MARGIN_MARGIN_RESN_CAT_ID = MARG_REAS_CAT_ID
	--TARG_CHAR_C:nullable string[255] = handle_null (TARG_CHAR_C, '999009')
	PL_INT_RATE_ID, PL_INT_RATE_PL_INT_RATE_ID, PL_INT_RATE_DOC_SEQ_NO, PL_INT_RATE_CASS_MARGIN_AMT, PL_INT_RATE_INT_RATE_TERM, PL_INT_RATE_INT_RATE_FREQ_ID, PL_INT_RATE_VARIANT_CAT_ID, PL_INT_RATE_USAGE_CAT_ID, PL_INT_RATE_PL_APP_PROD_ID, PL_MARGIN_PL_MARGIN_ID, PL_MARGIN_MARGIN_AMT, PL_MARGIN_PL_FEE_ID, PL_MARGIN_PL_INT_RATE_ID, MARG_REAS_CAT_ID AS PL_MARGIN_MARGIN_RESN_CAT_ID, PL_MARGIN_PL_APP_PROD_ID, PL_INT_RATE_AMT_INT_RTE_AMT_2, PL_INT_RATE_AMT_INT_RTCT_ID2, PL_INT_RATE_AMT_PL_INT_RATE_ID, PL_INT_RATE_AMT_INT_RATE_AMT_1, PL_INT_RATE_AMT_INT_RTCT_ID1, PL_MARGIN_FOUND_FLAG, PL_INT_RATE_FOUND_FLAG, PL_INT_RATE_AMT_FOUND_FLAG, ORIG_ETL_D, FEAT_OVRD_REAS_C, TARG_CHAR_C 
	FROM {{ ref('LkpReferences') }}
)

SELECT * FROM ModNullHandling