{{ config(materialized='view', tags=['XfmPlIntRateAmtMarginFrmExt']) }}

WITH Transformer_225 AS (
	SELECT
		PL_INT_RATE_ID,
		PL_INT_RATE_PL_INT_RATE_ID,
		PL_INT_RATE_DOC_SEQ_NO,
		PL_INT_RATE_CASS_MARGIN_AMT,
		PL_INT_RATE_INT_RATE_TERM,
		SRCE_NUMC_2_C,
		SRCE_NUMC_1_C,
		PL_INT_RATE_USAGE_CAT_ID,
		PL_INT_RATE_PL_APP_PROD_ID,
		PL_MARGIN_PL_MARGIN_ID,
		PL_MARGIN_MARGIN_AMT,
		PL_MARGIN_PL_FEE_ID,
		PL_MARGIN_PL_INT_RATE_ID,
		MARG_REAS_CAT_ID,
		PL_MARGIN_PL_APP_PROD_ID,
		PL_INT_RATE_AMT_INT_RTE_AMT_2,
		PL_INT_RATE_AMT_INT_RTCT_ID2,
		PL_INT_RATE_AMT_PL_INT_RATE_ID,
		PL_INT_RATE_AMT_INT_RATE_AMT_1,
		PL_INT_RATE_AMT_INT_RTCT_ID1,
		PL_MARGIN_FOUND_FLAG,
		PL_INT_RATE_FOUND_FLAG,
		PL_INT_RATE_AMT_FOUND_FLAG,
		ORIG_ETL_D,
		MAP_TYPE_C
	FROM {{ ref('CpyRename') }}
	WHERE 
)

SELECT * FROM Transformer_225