{{ config(materialized='view', tags=['LdUtilAcctIdnnErorUpdCommon']) }}

WITH Rem_Dup AS (
	SELECT EROR_ACCT_NUMB, PROS_KEY_EFFT_I, EXPY_DATE, PROS_KEY_EXPY_I 
	FROM (
		SELECT EROR_ACCT_NUMB, PROS_KEY_EFFT_I, EXPY_DATE, PROS_KEY_EXPY_I,
		 ROW_NUMBER() OVER (PARTITION BY EROR_ACCT_NUMB, PROS_KEY_EFFT_I ORDER BY 1 ASC) AS ROW_NUM 
		FROM {{ ref('UTIL_ACCT_IDNN_EROR_U') }}
	) AS Rem_Dup_TEMP
	WHERE ROW_NUM = 1
)

SELECT * FROM Rem_Dup