{{ config(materialized='view', tags=['XfmCclAppProdFrmExt2']) }}

WITH RD_FEAT_I_2 AS (
	SELECT MAP_TYPE_C, SRCE_CHAR_1_C, FEAT_I_2 
	FROM (
		SELECT MAP_TYPE_C, SRCE_CHAR_1_C, FEAT_I_2,
		 ROW_NUMBER() OVER (PARTITION BY MAP_TYPE_C, SRCE_CHAR_1_C ORDER BY 1 ASC) AS ROW_NUM 
		FROM {{ ref('CpyRenameGRD_GNRC_MAPLks') }}
	) AS RD_FEAT_I_2_TEMP
	WHERE ROW_NUM = 1
)

SELECT * FROM RD_FEAT_I_2