{{ config(materialized='view', tags=['XfmPlanBalnSegmMstrFromBCFINSG']) }}

WITH XfmToTable__ToTable AS (
	SELECT
		-- *SRC*: \(20)If IsNull(FrmSrc.BCF_PLAN_DUE_DATE) then 'N' else  if Trim(FrmSrc.BCF_PLAN_DUE_DATE) = '' then 'N' else  if Trim(FrmSrc.BCF_PLAN_DUE_DATE) = '000000000.' then 'N' Else 'Y',
		IFF({{ ref('BCFINSG') }}.BCF_PLAN_DUE_DATE IS NULL, 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_PLAN_DUE_DATE) = '', 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_PLAN_DUE_DATE) = '000000000.', 'N', 'Y'))) AS svIsNullBcfPlanDueDt,
		-- *SRC*: Trim(( IF IsNotNull((FrmSrc.BCF_PLAN_DUE_DATE)) THEN (FrmSrc.BCF_PLAN_DUE_DATE) ELSE "")[3, 4]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_PLAN_DUE_DATE)) THEN (FrmSrc.BCF_PLAN_DUE_DATE) ELSE "")[7, 2]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_PLAN_DUE_DATE)) THEN (FrmSrc.BCF_PLAN_DUE_DATE) ELSE "")[9, 2]),
		CONCAT(CONCAT(CONCAT(CONCAT(TRIM(IFF({{ ref('BCFINSG') }}.BCF_PLAN_DUE_DATE IS NOT NULL, {{ ref('BCFINSG') }}.BCF_PLAN_DUE_DATE, '')), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_PLAN_DUE_DATE IS NOT NULL, {{ ref('BCFINSG') }}.BCF_PLAN_DUE_DATE, ''))), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_PLAN_DUE_DATE IS NOT NULL, {{ ref('BCFINSG') }}.BCF_PLAN_DUE_DATE, ''))) AS svTransformBcfPlanDueDt,
		-- *SRC*: \(20)If IsValid('date', svTransformBcfPlanDueDt) Then 'Y' else  if Trim(FrmSrc.BCF_PLAN_DUE_DATE) = '000000000.' Then 'Y' Else 'N',
		IFF(ISVALID('date', svTransformBcfPlanDueDt), 'Y', IFF(TRIM({{ ref('BCFINSG') }}.BCF_PLAN_DUE_DATE) = '000000000.', 'Y', 'N')) AS svIsValidBcfPlanDueDt,
		-- *SRC*: \(20)If IsNull(FrmSrc.BCF_DATE_END_INTEREST_FREE) then 'N' else  if Trim(FrmSrc.BCF_DATE_END_INTEREST_FREE) = '' then 'N' else  if Trim(FrmSrc.BCF_DATE_END_INTEREST_FREE) = '000000000.' then 'N' Else 'Y',
		IFF({{ ref('BCFINSG') }}.BCF_DATE_END_INTEREST_FREE IS NULL, 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DATE_END_INTEREST_FREE) = '', 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DATE_END_INTEREST_FREE) = '000000000.', 'N', 'Y'))) AS svIsNullBcfDtEndInterestFree,
		-- *SRC*: Trim(( IF IsNotNull((FrmSrc.BCF_DATE_END_INTEREST_FREE)) THEN (FrmSrc.BCF_DATE_END_INTEREST_FREE) ELSE "")[3, 4]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_DATE_END_INTEREST_FREE)) THEN (FrmSrc.BCF_DATE_END_INTEREST_FREE) ELSE "")[7, 2]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_DATE_END_INTEREST_FREE)) THEN (FrmSrc.BCF_DATE_END_INTEREST_FREE) ELSE "")[9, 2]),
		CONCAT(CONCAT(CONCAT(CONCAT(TRIM(IFF({{ ref('BCFINSG') }}.BCF_DATE_END_INTEREST_FREE IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DATE_END_INTEREST_FREE, '')), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_DATE_END_INTEREST_FREE IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DATE_END_INTEREST_FREE, ''))), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_DATE_END_INTEREST_FREE IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DATE_END_INTEREST_FREE, ''))) AS svTransformBcfDtEndInterestFree,
		-- *SRC*: \(20)If IsValid('date', svTransformBcfDtEndInterestFree) Then 'Y' else  if Trim(FrmSrc.BCF_DATE_END_INTEREST_FREE) = '000000000.' Then 'Y' Else 'N',
		IFF(ISVALID('date', svTransformBcfDtEndInterestFree), 'Y', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DATE_END_INTEREST_FREE) = '000000000.', 'Y', 'N')) AS svIsValidBcfDtEndInterestFree,
		-- *SRC*: \(20)If IsNull(FrmSrc.BCF_DT_MIGRATE) then 'N' else  if Trim(FrmSrc.BCF_DT_MIGRATE) = '' then 'N' else  if Trim(FrmSrc.BCF_DT_MIGRATE) = '000000000.' then 'N' Else 'Y',
		IFF({{ ref('BCFINSG') }}.BCF_DT_MIGRATE IS NULL, 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_MIGRATE) = '', 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_MIGRATE) = '000000000.', 'N', 'Y'))) AS svIsNullBcfDtMigrate,
		-- *SRC*: Trim(( IF IsNotNull((FrmSrc.BCF_DT_MIGRATE)) THEN (FrmSrc.BCF_DT_MIGRATE) ELSE "")[3, 4]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_DT_MIGRATE)) THEN (FrmSrc.BCF_DT_MIGRATE) ELSE "")[7, 2]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_DT_MIGRATE)) THEN (FrmSrc.BCF_DT_MIGRATE) ELSE "")[9, 2]),
		CONCAT(CONCAT(CONCAT(CONCAT(TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_MIGRATE IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_MIGRATE, '')), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_MIGRATE IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_MIGRATE, ''))), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_MIGRATE IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_MIGRATE, ''))) AS svTransformBcfDtMigrate,
		-- *SRC*: \(20)If IsValid('date', svTransformBcfDtMigrate) Then 'Y' else  if Trim(FrmSrc.BCF_DT_MIGRATE) = '000000000.' then 'Y' Else 'N',
		IFF(ISVALID('date', svTransformBcfDtMigrate), 'Y', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_MIGRATE) = '000000000.', 'Y', 'N')) AS svIsValidBcfDtMigrate,
		-- *SRC*: \(20)If IsNull(FrmSrc.BCF_FL_LAST_INSTALLMENT_DT) then 'N' else  if Trim(FrmSrc.BCF_FL_LAST_INSTALLMENT_DT) = '' then 'N' else  if Trim(FrmSrc.BCF_FL_LAST_INSTALLMENT_DT) = '000000000.' then 'N' Else 'Y',
		IFF({{ ref('BCFINSG') }}.BCF_FL_LAST_INSTALLMENT_DT IS NULL, 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_FL_LAST_INSTALLMENT_DT) = '', 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_FL_LAST_INSTALLMENT_DT) = '000000000.', 'N', 'Y'))) AS svIsNullBcfFlLastInstallmentsDt,
		-- *SRC*: Trim(( IF IsNotNull((FrmSrc.BCF_FL_LAST_INSTALLMENT_DT)) THEN (FrmSrc.BCF_FL_LAST_INSTALLMENT_DT) ELSE "")[3, 4]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_FL_LAST_INSTALLMENT_DT)) THEN (FrmSrc.BCF_FL_LAST_INSTALLMENT_DT) ELSE "")[7, 2]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_FL_LAST_INSTALLMENT_DT)) THEN (FrmSrc.BCF_FL_LAST_INSTALLMENT_DT) ELSE "")[9, 2]),
		CONCAT(CONCAT(CONCAT(CONCAT(TRIM(IFF({{ ref('BCFINSG') }}.BCF_FL_LAST_INSTALLMENT_DT IS NOT NULL, {{ ref('BCFINSG') }}.BCF_FL_LAST_INSTALLMENT_DT, '')), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_FL_LAST_INSTALLMENT_DT IS NOT NULL, {{ ref('BCFINSG') }}.BCF_FL_LAST_INSTALLMENT_DT, ''))), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_FL_LAST_INSTALLMENT_DT IS NOT NULL, {{ ref('BCFINSG') }}.BCF_FL_LAST_INSTALLMENT_DT, ''))) AS svTransformBcfFlLastInstallmentsDt,
		-- *SRC*: \(20)If IsValid('date', svTransformBcfFlLastInstallmentsDt) Then 'Y' else  if Trim(FrmSrc.BCF_FL_LAST_INSTALLMENT_DT) = '000000000.' then 'Y' Else 'N',
		IFF(ISVALID('date', svTransformBcfFlLastInstallmentsDt), 'Y', IFF(TRIM({{ ref('BCFINSG') }}.BCF_FL_LAST_INSTALLMENT_DT) = '000000000.', 'Y', 'N')) AS svIsValidBcfFlLastInstallmentsDt,
		-- *SRC*: \(20)If IsNull(FrmSrc.BCF_SCHED_PAYOFF_DT) then 'N' else  if Trim(FrmSrc.BCF_SCHED_PAYOFF_DT) = '' then 'N' else  if Trim(FrmSrc.BCF_SCHED_PAYOFF_DT) = '000000000.' then 'N' Else 'Y',
		IFF({{ ref('BCFINSG') }}.BCF_SCHED_PAYOFF_DT IS NULL, 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_SCHED_PAYOFF_DT) = '', 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_SCHED_PAYOFF_DT) = '000000000.', 'N', 'Y'))) AS svIsNullBcfSchedPayoffDt,
		-- *SRC*: Trim(( IF IsNotNull((FrmSrc.BCF_SCHED_PAYOFF_DT)) THEN (FrmSrc.BCF_SCHED_PAYOFF_DT) ELSE "")[3, 4]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_SCHED_PAYOFF_DT)) THEN (FrmSrc.BCF_SCHED_PAYOFF_DT) ELSE "")[7, 2]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_SCHED_PAYOFF_DT)) THEN (FrmSrc.BCF_SCHED_PAYOFF_DT) ELSE "")[9, 2]),
		CONCAT(CONCAT(CONCAT(CONCAT(TRIM(IFF({{ ref('BCFINSG') }}.BCF_SCHED_PAYOFF_DT IS NOT NULL, {{ ref('BCFINSG') }}.BCF_SCHED_PAYOFF_DT, '')), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_SCHED_PAYOFF_DT IS NOT NULL, {{ ref('BCFINSG') }}.BCF_SCHED_PAYOFF_DT, ''))), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_SCHED_PAYOFF_DT IS NOT NULL, {{ ref('BCFINSG') }}.BCF_SCHED_PAYOFF_DT, ''))) AS svTransformBcfSchedPayoffDt,
		-- *SRC*: \(20)If IsValid('date', svTransformBcfSchedPayoffDt) Then 'Y' else  if Trim(FrmSrc.BCF_SCHED_PAYOFF_DT) = '000000000.' then 'Y' Else 'N',
		IFF(ISVALID('date', svTransformBcfSchedPayoffDt), 'Y', IFF(TRIM({{ ref('BCFINSG') }}.BCF_SCHED_PAYOFF_DT) = '000000000.', 'Y', 'N')) AS svIsValidBcfSchedPayoffDt,
		-- *SRC*: \(20)If IsNull(FrmSrc.BCF_ACTUAL_PAYOFF_DT) then 'N' else  if Trim(FrmSrc.BCF_ACTUAL_PAYOFF_DT) = '' then 'N' else  if Trim(FrmSrc.BCF_ACTUAL_PAYOFF_DT) = '000000000.' then 'N' Else 'Y',
		IFF({{ ref('BCFINSG') }}.BCF_ACTUAL_PAYOFF_DT IS NULL, 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_ACTUAL_PAYOFF_DT) = '', 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_ACTUAL_PAYOFF_DT) = '000000000.', 'N', 'Y'))) AS svIsNullBcfActualPayoffDt,
		-- *SRC*: Trim(( IF IsNotNull((FrmSrc.BCF_ACTUAL_PAYOFF_DT)) THEN (FrmSrc.BCF_ACTUAL_PAYOFF_DT) ELSE "")[3, 4]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_ACTUAL_PAYOFF_DT)) THEN (FrmSrc.BCF_ACTUAL_PAYOFF_DT) ELSE "")[7, 2]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_ACTUAL_PAYOFF_DT)) THEN (FrmSrc.BCF_ACTUAL_PAYOFF_DT) ELSE "")[9, 2]),
		CONCAT(CONCAT(CONCAT(CONCAT(TRIM(IFF({{ ref('BCFINSG') }}.BCF_ACTUAL_PAYOFF_DT IS NOT NULL, {{ ref('BCFINSG') }}.BCF_ACTUAL_PAYOFF_DT, '')), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_ACTUAL_PAYOFF_DT IS NOT NULL, {{ ref('BCFINSG') }}.BCF_ACTUAL_PAYOFF_DT, ''))), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_ACTUAL_PAYOFF_DT IS NOT NULL, {{ ref('BCFINSG') }}.BCF_ACTUAL_PAYOFF_DT, ''))) AS svTransformBcfActualPayoffDt,
		-- *SRC*: \(20)If IsValid('date', svTransformBcfActualPayoffDt) Then 'Y' else  if Trim(FrmSrc.BCF_ACTUAL_PAYOFF_DT) = '000000000.' then 'Y' Else 'N',
		IFF(ISVALID('date', svTransformBcfActualPayoffDt), 'Y', IFF(TRIM({{ ref('BCFINSG') }}.BCF_ACTUAL_PAYOFF_DT) = '000000000.', 'Y', 'N')) AS svIsValidBcfActualPayoffDt,
		-- *SRC*: \(20)If IsNull(FrmSrc.BCF_DT_INSTALL_TERM_CHG) then 'N' else  if Trim(FrmSrc.BCF_DT_INSTALL_TERM_CHG) = '' then 'N' else  if Trim(FrmSrc.BCF_DT_INSTALL_TERM_CHG) = '000000000.' then 'N' Else 'Y',
		IFF({{ ref('BCFINSG') }}.BCF_DT_INSTALL_TERM_CHG IS NULL, 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_INSTALL_TERM_CHG) = '', 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_INSTALL_TERM_CHG) = '000000000.', 'N', 'Y'))) AS svIsNullBcfDtInstallTermChg,
		-- *SRC*: Trim(( IF IsNotNull((FrmSrc.BCF_DT_INSTALL_TERM_CHG)) THEN (FrmSrc.BCF_DT_INSTALL_TERM_CHG) ELSE "")[3, 4]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_DT_INSTALL_TERM_CHG)) THEN (FrmSrc.BCF_DT_INSTALL_TERM_CHG) ELSE "")[7, 2]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_DT_INSTALL_TERM_CHG)) THEN (FrmSrc.BCF_DT_INSTALL_TERM_CHG) ELSE "")[9, 2]),
		CONCAT(CONCAT(CONCAT(CONCAT(TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_INSTALL_TERM_CHG IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_INSTALL_TERM_CHG, '')), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_INSTALL_TERM_CHG IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_INSTALL_TERM_CHG, ''))), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_INSTALL_TERM_CHG IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_INSTALL_TERM_CHG, ''))) AS svTransformBcfDtInstallTermChg,
		-- *SRC*: \(20)If IsValid('date', svTransformBcfDtInstallTermChg) Then 'Y' else  if Trim(FrmSrc.BCF_DT_INSTALL_TERM_CHG) = '000000000.' then 'Y' Else 'N',
		IFF(ISVALID('date', svTransformBcfDtInstallTermChg), 'Y', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_INSTALL_TERM_CHG) = '000000000.', 'Y', 'N')) AS svIsValidBcfDtInstallTermChg,
		-- *SRC*: \(20)If IsNull(FrmSrc.BCF_DT_INSTALL_PAID) then 'N' else  if Trim(FrmSrc.BCF_DT_INSTALL_PAID) = '' then 'N' else  if Trim(FrmSrc.BCF_DT_INSTALL_PAID) = '000000000.' then 'N' Else 'Y',
		IFF({{ ref('BCFINSG') }}.BCF_DT_INSTALL_PAID IS NULL, 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_INSTALL_PAID) = '', 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_INSTALL_PAID) = '000000000.', 'N', 'Y'))) AS svIsNullBcfDtInstallPaid,
		-- *SRC*: Trim(( IF IsNotNull((FrmSrc.BCF_DT_INSTALL_PAID)) THEN (FrmSrc.BCF_DT_INSTALL_PAID) ELSE "")[3, 4]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_DT_INSTALL_PAID)) THEN (FrmSrc.BCF_DT_INSTALL_PAID) ELSE "")[7, 2]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_DT_INSTALL_PAID)) THEN (FrmSrc.BCF_DT_INSTALL_PAID) ELSE "")[9, 2]),
		CONCAT(CONCAT(CONCAT(CONCAT(TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_INSTALL_PAID IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_INSTALL_PAID, '')), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_INSTALL_PAID IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_INSTALL_PAID, ''))), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_INSTALL_PAID IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_INSTALL_PAID, ''))) AS svTransformBcfDtInstallPaid,
		-- *SRC*: \(20)If IsValid('date', svTransformBcfDtInstallPaid) Then 'Y' else  if Trim(FrmSrc.BCF_DT_INSTALL_PAID) = '000000000.' then 'Y' Else 'N',
		IFF(ISVALID('date', svTransformBcfDtInstallPaid), 'Y', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_INSTALL_PAID) = '000000000.', 'Y', 'N')) AS svIsValidBcfDtInstallPaid,
		-- *SRC*: \(20)If IsNull(FrmSrc.BCF_PROJECTED_PAYOFF_DT) then 'N' else  if Trim(FrmSrc.BCF_PROJECTED_PAYOFF_DT) = '' then 'N' else  if Trim(FrmSrc.BCF_PROJECTED_PAYOFF_DT) = '0000000.' then 'N' Else 'Y',
		IFF({{ ref('BCFINSG') }}.BCF_PROJECTED_PAYOFF_DT IS NULL, 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_PROJECTED_PAYOFF_DT) = '', 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_PROJECTED_PAYOFF_DT) = '0000000.', 'N', 'Y'))) AS svIsNullBcfProjectedPayoffDt,
		-- *SRC*: \(20)If svIsNullBcfProjectedPayoffDt = 'Y' Then DateFromJulianDay(FrmSrc.BCF_PROJECTED_PAYOFF_DT) Else '',
		IFF(svIsNullBcfProjectedPayoffDt = 'Y', DATEFROMJULIANDAY({{ ref('BCFINSG') }}.BCF_PROJECTED_PAYOFF_DT), '') AS svTransformBcfProjectedPayoffDt,
		-- *SRC*: \(20)If IsValid('date', svTransformBcfProjectedPayoffDt) Then 'Y' else  if Trim(FrmSrc.BCF_PROJECTED_PAYOFF_DT) = '0000000.' then 'Y' Else 'N',
		IFF(ISVALID('date', svTransformBcfProjectedPayoffDt), 'Y', IFF(TRIM({{ ref('BCFINSG') }}.BCF_PROJECTED_PAYOFF_DT) = '0000000.', 'Y', 'N')) AS svIsValidBcfProjectedPayoffDt,
		-- *SRC*: \(20)If IsNull(FrmSrc.BCF_DISPUTE_OLD_DATE) then 'N' else  if Trim(FrmSrc.BCF_DISPUTE_OLD_DATE) = '' then 'N' else  if Trim(FrmSrc.BCF_DISPUTE_OLD_DATE) = '000000000.' then 'N' Else 'Y',
		IFF({{ ref('BCFINSG') }}.BCF_DISPUTE_OLD_DATE IS NULL, 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DISPUTE_OLD_DATE) = '', 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DISPUTE_OLD_DATE) = '000000000.', 'N', 'Y'))) AS svIsNullBcfDisputeOldDt,
		-- *SRC*: Trim(( IF IsNotNull((FrmSrc.BCF_DISPUTE_OLD_DATE)) THEN (FrmSrc.BCF_DISPUTE_OLD_DATE) ELSE "")[3, 4]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_DISPUTE_OLD_DATE)) THEN (FrmSrc.BCF_DISPUTE_OLD_DATE) ELSE "")[7, 2]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_DISPUTE_OLD_DATE)) THEN (FrmSrc.BCF_DISPUTE_OLD_DATE) ELSE "")[9, 2]),
		CONCAT(CONCAT(CONCAT(CONCAT(TRIM(IFF({{ ref('BCFINSG') }}.BCF_DISPUTE_OLD_DATE IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DISPUTE_OLD_DATE, '')), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_DISPUTE_OLD_DATE IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DISPUTE_OLD_DATE, ''))), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_DISPUTE_OLD_DATE IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DISPUTE_OLD_DATE, ''))) AS svTransformBcfDisputeOldDt,
		-- *SRC*: \(20)If IsValid('date', svTransformBcfDisputeOldDt) Then 'Y' else  if Trim(FrmSrc.BCF_DISPUTE_OLD_DATE) = '000000000.' then 'Y' Else 'N',
		IFF(ISVALID('date', svTransformBcfDisputeOldDt), 'Y', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DISPUTE_OLD_DATE) = '000000000.', 'Y', 'N')) AS svIsValidBcfDisputeOldDt,
		-- *SRC*: \(20)If IsNull(FrmSrc.BCF_DT_LAST_PAYMENT) then 'N' else  if Trim(FrmSrc.BCF_DT_LAST_PAYMENT) = '' then 'N' else  if Trim(FrmSrc.BCF_DT_LAST_PAYMENT) = '000000000.' then 'N' Else 'Y',
		IFF({{ ref('BCFINSG') }}.BCF_DT_LAST_PAYMENT IS NULL, 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_LAST_PAYMENT) = '', 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_LAST_PAYMENT) = '000000000.', 'N', 'Y'))) AS svIsNullBcfDtLastPayt,
		-- *SRC*: Trim(( IF IsNotNull((FrmSrc.BCF_DT_LAST_PAYMENT)) THEN (FrmSrc.BCF_DT_LAST_PAYMENT) ELSE "")[3, 4]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_DT_LAST_PAYMENT)) THEN (FrmSrc.BCF_DT_LAST_PAYMENT) ELSE "")[7, 2]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_DT_LAST_PAYMENT)) THEN (FrmSrc.BCF_DT_LAST_PAYMENT) ELSE "")[9, 2]),
		CONCAT(CONCAT(CONCAT(CONCAT(TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_LAST_PAYMENT IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_LAST_PAYMENT, '')), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_LAST_PAYMENT IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_LAST_PAYMENT, ''))), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_LAST_PAYMENT IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_LAST_PAYMENT, ''))) AS svTransformBcfDtLastPayt,
		-- *SRC*: \(20)If IsValid('date', svTransformBcfDtLastPayt) Then 'Y' else  if Trim(FrmSrc.BCF_DT_LAST_PAYMENT) = '000000000.' then 'Y' Else 'N',
		IFF(ISVALID('date', svTransformBcfDtLastPayt), 'Y', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_LAST_PAYMENT) = '000000000.', 'Y', 'N')) AS svIsValidBcfDtLastPayt,
		-- *SRC*: \(20)If IsNull(FrmSrc.BCF_DT_LAST_MAINT) then 'N' else  if Trim(FrmSrc.BCF_DT_LAST_MAINT) = '' then 'N' else  if Trim(FrmSrc.BCF_DT_LAST_MAINT) = '000000000.' then 'N' Else 'Y',
		IFF({{ ref('BCFINSG') }}.BCF_DT_LAST_MAINT IS NULL, 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_LAST_MAINT) = '', 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_LAST_MAINT) = '000000000.', 'N', 'Y'))) AS svIsNullBcfDtLastMntn,
		-- *SRC*: Trim(( IF IsNotNull((FrmSrc.BCF_DT_LAST_MAINT)) THEN (FrmSrc.BCF_DT_LAST_MAINT) ELSE "")[3, 4]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_DT_LAST_MAINT)) THEN (FrmSrc.BCF_DT_LAST_MAINT) ELSE "")[7, 2]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_DT_LAST_MAINT)) THEN (FrmSrc.BCF_DT_LAST_MAINT) ELSE "")[9, 2]),
		CONCAT(CONCAT(CONCAT(CONCAT(TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_LAST_MAINT IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_LAST_MAINT, '')), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_LAST_MAINT IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_LAST_MAINT, ''))), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_LAST_MAINT IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_LAST_MAINT, ''))) AS svTransformBcfDtLastMntn,
		-- *SRC*: \(20)If IsValid('date', svTransformBcfDtLastMntn) Then 'Y' else  if Trim(FrmSrc.BCF_DT_LAST_MAINT) = '000000000.' then 'Y' Else 'N',
		IFF(ISVALID('date', svTransformBcfDtLastMntn), 'Y', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_LAST_MAINT) = '000000000.', 'Y', 'N')) AS svIsValidBcfDtLastMntn,
		-- *SRC*: \(20)If IsNull(FrmSrc.BCF_DT_PAID_OFF) then 'N' else  if Trim(FrmSrc.BCF_DT_PAID_OFF) = '' then 'N' else  if Trim(FrmSrc.BCF_DT_PAID_OFF) = '000000000.' then 'N' Else 'Y',
		IFF({{ ref('BCFINSG') }}.BCF_DT_PAID_OFF IS NULL, 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_PAID_OFF) = '', 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_PAID_OFF) = '000000000.', 'N', 'Y'))) AS svIsNullBcfDtPaidOff,
		-- *SRC*: Trim(( IF IsNotNull((FrmSrc.BCF_DT_PAID_OFF)) THEN (FrmSrc.BCF_DT_PAID_OFF) ELSE "")[3, 4]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_DT_PAID_OFF)) THEN (FrmSrc.BCF_DT_PAID_OFF) ELSE "")[7, 2]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_DT_PAID_OFF)) THEN (FrmSrc.BCF_DT_PAID_OFF) ELSE "")[9, 2]),
		CONCAT(CONCAT(CONCAT(CONCAT(TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_PAID_OFF IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_PAID_OFF, '')), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_PAID_OFF IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_PAID_OFF, ''))), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_PAID_OFF IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_PAID_OFF, ''))) AS svTransformBcfDtPaidOff,
		-- *SRC*: \(20)If IsValid('date', svTransformBcfDtPaidOff) Then 'Y' else  if Trim(FrmSrc.BCF_DT_PAID_OFF) = '000000000.' then 'Y' Else 'N',
		IFF(ISVALID('date', svTransformBcfDtPaidOff), 'Y', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_PAID_OFF) = '000000000.', 'Y', 'N')) AS svIsValidBcfDtPaidOff,
		-- *SRC*: \(20)If IsNull(FrmSrc.BCF_DT_FIRST_TRANS) then 'N' else  if Trim(FrmSrc.BCF_DT_FIRST_TRANS) = '' then 'N' else  if Trim(FrmSrc.BCF_DT_FIRST_TRANS) = '000000000.' then 'N' Else 'Y',
		IFF({{ ref('BCFINSG') }}.BCF_DT_FIRST_TRANS IS NULL, 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_FIRST_TRANS) = '', 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_FIRST_TRANS) = '000000000.', 'N', 'Y'))) AS svIsNullBcfDtFirstTrans,
		-- *SRC*: Trim(( IF IsNotNull((FrmSrc.BCF_DT_FIRST_TRANS)) THEN (FrmSrc.BCF_DT_FIRST_TRANS) ELSE "")[3, 4]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_DT_FIRST_TRANS)) THEN (FrmSrc.BCF_DT_FIRST_TRANS) ELSE "")[7, 2]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_DT_FIRST_TRANS)) THEN (FrmSrc.BCF_DT_FIRST_TRANS) ELSE "")[9, 2]),
		CONCAT(CONCAT(CONCAT(CONCAT(TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_FIRST_TRANS IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_FIRST_TRANS, '')), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_FIRST_TRANS IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_FIRST_TRANS, ''))), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_FIRST_TRANS IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_FIRST_TRANS, ''))) AS svTransformBcfDtFirstTrans,
		-- *SRC*: \(20)If IsValid('date', svTransformBcfDtFirstTrans) Then 'Y' else  if Trim(FrmSrc.BCF_DT_FIRST_TRANS) = '000000000.' then 'Y' Else 'N',
		IFF(ISVALID('date', svTransformBcfDtFirstTrans), 'Y', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_FIRST_TRANS) = '000000000.', 'Y', 'N')) AS svIsValidBcfDtFirstTrans,
		-- *SRC*: \(20)If IsNull(FrmSrc.BCF_DT_PAYMENT_DEFER) then 'N' else  if Trim(FrmSrc.BCF_DT_PAYMENT_DEFER) = '' then 'N' else  if Trim(FrmSrc.BCF_DT_PAYMENT_DEFER) = '000000000.' then 'N' Else 'Y',
		IFF({{ ref('BCFINSG') }}.BCF_DT_PAYMENT_DEFER IS NULL, 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_PAYMENT_DEFER) = '', 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_PAYMENT_DEFER) = '000000000.', 'N', 'Y'))) AS svIsNullBcfDtPaymentDefer,
		-- *SRC*: Trim(( IF IsNotNull((FrmSrc.BCF_DT_PAYMENT_DEFER)) THEN (FrmSrc.BCF_DT_PAYMENT_DEFER) ELSE "")[3, 4]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_DT_PAYMENT_DEFER)) THEN (FrmSrc.BCF_DT_PAYMENT_DEFER) ELSE "")[7, 2]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_DT_PAYMENT_DEFER)) THEN (FrmSrc.BCF_DT_PAYMENT_DEFER) ELSE "")[9, 2]),
		CONCAT(CONCAT(CONCAT(CONCAT(TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_PAYMENT_DEFER IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_PAYMENT_DEFER, '')), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_PAYMENT_DEFER IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_PAYMENT_DEFER, ''))), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_PAYMENT_DEFER IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_PAYMENT_DEFER, ''))) AS svTransformBcfDtPaymentDefer,
		-- *SRC*: \(20)If IsValid('date', svTransformBcfDtPaymentDefer) Then 'Y' else  if Trim(FrmSrc.BCF_DT_PAYMENT_DEFER) = '000000000.' then 'Y' Else 'N',
		IFF(ISVALID('date', svTransformBcfDtPaymentDefer), 'Y', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_PAYMENT_DEFER) = '000000000.', 'Y', 'N')) AS svIsValidBcfDtPaymentDefer,
		-- *SRC*: \(20)If IsNull(FrmSrc.BCF_DT_INTEREST_DEFER) then 'N' else  if Trim(FrmSrc.BCF_DT_INTEREST_DEFER) = '' then 'N' else  if Trim(FrmSrc.BCF_DT_INTEREST_DEFER) = '000000000.' then 'N' Else 'Y',
		IFF({{ ref('BCFINSG') }}.BCF_DT_INTEREST_DEFER IS NULL, 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_INTEREST_DEFER) = '', 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_INTEREST_DEFER) = '000000000.', 'N', 'Y'))) AS svIsNullBcfDtInterestDefer,
		-- *SRC*: Trim(( IF IsNotNull((FrmSrc.BCF_DT_INTEREST_DEFER)) THEN (FrmSrc.BCF_DT_INTEREST_DEFER) ELSE "")[3, 4]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_DT_INTEREST_DEFER)) THEN (FrmSrc.BCF_DT_INTEREST_DEFER) ELSE "")[7, 2]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_DT_INTEREST_DEFER)) THEN (FrmSrc.BCF_DT_INTEREST_DEFER) ELSE "")[9, 2]),
		CONCAT(CONCAT(CONCAT(CONCAT(TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_INTEREST_DEFER IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_INTEREST_DEFER, '')), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_INTEREST_DEFER IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_INTEREST_DEFER, ''))), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_INTEREST_DEFER IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_INTEREST_DEFER, ''))) AS svTransformBcfDtInterestDefer,
		-- *SRC*: \(20)If IsValid('date', svTransformBcfDtInterestDefer) Then 'Y' else  if Trim(FrmSrc.BCF_DT_INTEREST_DEFER) = '000000000.' then 'Y' Else 'N',
		IFF(ISVALID('date', svTransformBcfDtInterestDefer), 'Y', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_INTEREST_DEFER) = '000000000.', 'Y', 'N')) AS svIsValidBcfDtInterestDefer,
		-- *SRC*: \(20)If IsNull(FrmSrc.BCF_DT_SPEC_TERMS_END) then 'N' else  if Trim(FrmSrc.BCF_DT_SPEC_TERMS_END) = '' then 'N' else  if Trim(FrmSrc.BCF_DT_SPEC_TERMS_END) = '000000000.' then 'N' Else 'Y',
		IFF({{ ref('BCFINSG') }}.BCF_DT_SPEC_TERMS_END IS NULL, 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_SPEC_TERMS_END) = '', 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_SPEC_TERMS_END) = '000000000.', 'N', 'Y'))) AS svIsNullBcfDtSpecTermsEnd,
		-- *SRC*: Trim(( IF IsNotNull((FrmSrc.BCF_DT_SPEC_TERMS_END)) THEN (FrmSrc.BCF_DT_SPEC_TERMS_END) ELSE "")[3, 4]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_DT_SPEC_TERMS_END)) THEN (FrmSrc.BCF_DT_SPEC_TERMS_END) ELSE "")[7, 2]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_DT_SPEC_TERMS_END)) THEN (FrmSrc.BCF_DT_SPEC_TERMS_END) ELSE "")[9, 2]),
		CONCAT(CONCAT(CONCAT(CONCAT(TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_SPEC_TERMS_END IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_SPEC_TERMS_END, '')), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_SPEC_TERMS_END IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_SPEC_TERMS_END, ''))), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_SPEC_TERMS_END IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_SPEC_TERMS_END, ''))) AS svTransformBcfDtSpecTermsEnd,
		-- *SRC*: \(20)If IsValid('date', svTransformBcfDtSpecTermsEnd) Then 'Y' else  if Trim(FrmSrc.BCF_DT_SPEC_TERMS_END) = '000000000.' then 'Y' Else 'N',
		IFF(ISVALID('date', svTransformBcfDtSpecTermsEnd), 'Y', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_SPEC_TERMS_END) = '000000000.', 'Y', 'N')) AS svIsValidBcfDtSpecTermsEnd,
		-- *SRC*: \(20)If IsNull(FrmSrc.BCF_CORP) then 'Y' else  if trim(FrmSrc.BCF_CORP) = '' then 'Y' else  if trim(FrmSrc.BCF_CORP) = 0 then 'Y' else  if IsNull(FrmSrc.BCF_ACCOUNT_NO1) then 'Y' else  if trim(FrmSrc.BCF_ACCOUNT_NO1) = '' then 'Y' else  if trim(FrmSrc.BCF_ACCOUNT_NO1) = 0 then 'Y' else  if IsNull(FrmSrc.BCF_PLAN_ID) then 'Y' else  if trim(FrmSrc.BCF_PLAN_ID) = '' then 'Y' else  if trim(FrmSrc.BCF_PLAN_ID) = 0 then 'Y' else 'N',
		IFF(
	    {{ ref('BCFINSG') }}.BCF_CORP IS NULL, 'Y',     
	    IFF(
	        TRIM({{ ref('BCFINSG') }}.BCF_CORP) = '', 'Y',         
	        IFF(
	            TRIM({{ ref('BCFINSG') }}.BCF_CORP) = 0, 'Y', 
	            IFF({{ ref('BCFINSG') }}.BCF_ACCOUNT_NO1 IS NULL, 'Y', IFF(TRIM({{ ref('BCFINSG') }}.BCF_ACCOUNT_NO1) = '', 'Y', IFF(TRIM({{ ref('BCFINSG') }}.BCF_ACCOUNT_NO1) = 0, 'Y', IFF({{ ref('BCFINSG') }}.BCF_PLAN_ID IS NULL, 'Y', IFF(TRIM({{ ref('BCFINSG') }}.BCF_PLAN_ID) = '', 'Y', IFF(TRIM({{ ref('BCFINSG') }}.BCF_PLAN_ID) = 0, 'Y', 'N'))))))
	        )
	    )
	) AS svIsValidRecord,
		-- *SRC*: \(20)if svRowI = 0 then @PARTITIONNUM + 1 else svRowI + @NUMPARTITIONS,
		IFF(svRowI = 0, @PARTITIONNUM + 1, svRowI + @NUMPARTITIONS) AS svRowI,
		-- *SRC*: Trim(FrmSrc.BCF_CORP),
		TRIM({{ ref('BCFINSG') }}.BCF_CORP) AS CORP_IDNN,
		-- *SRC*: "CCSCC" : Trim(FrmSrc.BCF_ACCOUNT_NO1),
		CONCAT('CCSCC', TRIM({{ ref('BCFINSG') }}.BCF_ACCOUNT_NO1)) AS ACCT_I,
		-- *SRC*: Trim(FrmSrc.BCF_PLAN_ID),
		TRIM({{ ref('BCFINSG') }}.BCF_PLAN_ID) AS PLAN_IDNN,
		{{ ref('BCFINSG') }}.BCF_PLAN_SEQ AS PLAN_SQNO,
		-- *SRC*: \(20)If Trim(( IF IsNotNull((FrmSrc.BCF_ACCOUNT_NO1)) THEN (FrmSrc.BCF_ACCOUNT_NO1) ELSE "")) = '' then SetNull() Else Trim(FrmSrc.BCF_ACCOUNT_NO1),
		IFF(TRIM(IFF({{ ref('BCFINSG') }}.BCF_ACCOUNT_NO1 IS NOT NULL, {{ ref('BCFINSG') }}.BCF_ACCOUNT_NO1, '')) = '', SETNULL(), TRIM({{ ref('BCFINSG') }}.BCF_ACCOUNT_NO1)) AS SRCE_SYST_ACCT_NUMB,
		-- *SRC*: \(20)If Trim(( IF IsNotNull((FrmSrc.BCF_STORE_ID)) THEN (FrmSrc.BCF_STORE_ID) ELSE "")) = '' then SetNull() Else Trim(FrmSrc.BCF_STORE_ID),
		IFF(TRIM(IFF({{ ref('BCFINSG') }}.BCF_STORE_ID IS NOT NULL, {{ ref('BCFINSG') }}.BCF_STORE_ID, '')) = '', SETNULL(), TRIM({{ ref('BCFINSG') }}.BCF_STORE_ID)) AS STOR_IDNN,
		-- *SRC*: \(20)If Trim(( IF IsNotNull((FrmSrc.BCF_ORIGINAL_STATE)) THEN (FrmSrc.BCF_ORIGINAL_STATE) ELSE "")) = '' then SetNull() Else Trim(FrmSrc.BCF_ORIGINAL_STATE),
		IFF(TRIM(IFF({{ ref('BCFINSG') }}.BCF_ORIGINAL_STATE IS NOT NULL, {{ ref('BCFINSG') }}.BCF_ORIGINAL_STATE, '')) = '', SETNULL(), TRIM({{ ref('BCFINSG') }}.BCF_ORIGINAL_STATE)) AS ORIG_STAT,
		-- *SRC*: \(20)If Trim(( IF IsNotNull((FrmSrc.BCF_PLAN_TYPE)) THEN (FrmSrc.BCF_PLAN_TYPE) ELSE "")) = '' then SetNull() Else Trim(FrmSrc.BCF_PLAN_TYPE),
		IFF(TRIM(IFF({{ ref('BCFINSG') }}.BCF_PLAN_TYPE IS NOT NULL, {{ ref('BCFINSG') }}.BCF_PLAN_TYPE, '')) = '', SETNULL(), TRIM({{ ref('BCFINSG') }}.BCF_PLAN_TYPE)) AS PLAN_TYPE,
		-- *SRC*: \(20)If Trim(( IF IsNotNull((FrmSrc.BCF_PLAN_CATEGORY)) THEN (FrmSrc.BCF_PLAN_CATEGORY) ELSE "")) = '' then SetNull() Else Trim(FrmSrc.BCF_PLAN_CATEGORY),
		IFF(TRIM(IFF({{ ref('BCFINSG') }}.BCF_PLAN_CATEGORY IS NOT NULL, {{ ref('BCFINSG') }}.BCF_PLAN_CATEGORY, '')) = '', SETNULL(), TRIM({{ ref('BCFINSG') }}.BCF_PLAN_CATEGORY)) AS PLAN_CATG,
		-- *SRC*: \(20)If Trim(( IF IsNotNull((FrmSrc.BCF_POST_PURCHASE_STATUS)) THEN (FrmSrc.BCF_POST_PURCHASE_STATUS) ELSE "")) = '' then SetNull() Else Trim(FrmSrc.BCF_POST_PURCHASE_STATUS),
		IFF(TRIM(IFF({{ ref('BCFINSG') }}.BCF_POST_PURCHASE_STATUS IS NOT NULL, {{ ref('BCFINSG') }}.BCF_POST_PURCHASE_STATUS, '')) = '', SETNULL(), TRIM({{ ref('BCFINSG') }}.BCF_POST_PURCHASE_STATUS)) AS POST_PUR_STUS,
		-- *SRC*: \(20)If Trim(( IF IsNotNull((FrmSrc.BCF_TERMS_STATUS)) THEN (FrmSrc.BCF_TERMS_STATUS) ELSE "")) = '' then SetNull() Else Trim(FrmSrc.BCF_TERMS_STATUS),
		IFF(TRIM(IFF({{ ref('BCFINSG') }}.BCF_TERMS_STATUS IS NOT NULL, {{ ref('BCFINSG') }}.BCF_TERMS_STATUS, '')) = '', SETNULL(), TRIM({{ ref('BCFINSG') }}.BCF_TERMS_STATUS)) AS TERM_STUS,
		-- *SRC*: \(20)If Trim(( IF IsNotNull((FrmSrc.BCF_INTEREST_DEFER_STATUS)) THEN (FrmSrc.BCF_INTEREST_DEFER_STATUS) ELSE "")) = '' then SetNull() Else Trim(FrmSrc.BCF_INTEREST_DEFER_STATUS),
		IFF(TRIM(IFF({{ ref('BCFINSG') }}.BCF_INTEREST_DEFER_STATUS IS NOT NULL, {{ ref('BCFINSG') }}.BCF_INTEREST_DEFER_STATUS, '')) = '', SETNULL(), TRIM({{ ref('BCFINSG') }}.BCF_INTEREST_DEFER_STATUS)) AS INT_DEFR_STUS,
		-- *SRC*: \(20)If Trim(( IF IsNotNull((FrmSrc.BCF_PAYMENT_DEFER_STATUS)) THEN (FrmSrc.BCF_PAYMENT_DEFER_STATUS) ELSE "")) = '' then SetNull() Else Trim(FrmSrc.BCF_PAYMENT_DEFER_STATUS),
		IFF(TRIM(IFF({{ ref('BCFINSG') }}.BCF_PAYMENT_DEFER_STATUS IS NOT NULL, {{ ref('BCFINSG') }}.BCF_PAYMENT_DEFER_STATUS, '')) = '', SETNULL(), TRIM({{ ref('BCFINSG') }}.BCF_PAYMENT_DEFER_STATUS)) AS PAYT_DEFR_STUS,
		{{ ref('BCFINSG') }}.BCF_TIMES_BILLED AS TIME_BILL,
		{{ ref('BCFINSG') }}.BCF_SPECIAL_TERMS_CYCLES AS SPEC_TERM_CYCL,
		{{ ref('BCFINSG') }}.BCF_INTEREST_DEFER_CYCLES AS INT_DEFR_CYCL,
		{{ ref('BCFINSG') }}.BCF_PAYMENT_DEFER_CYCLES AS PAYT_DEFR_CYCL,
		-- *SRC*: \(20)If svIsNullBcfDtSpecTermsEnd = 'N' Then SetNull() Else  If svIsValidBcfDtSpecTermsEnd = 'N' Then '1111-11-11' Else svTransformBcfDtSpecTermsEnd,
		IFF(svIsNullBcfDtSpecTermsEnd = 'N', SETNULL(), IFF(svIsValidBcfDtSpecTermsEnd = 'N', '1111-11-11', svTransformBcfDtSpecTermsEnd)) AS DATE_SPEC_TERM_END,
		-- *SRC*: \(20)If svIsNullBcfDtInterestDefer = 'N' Then SetNull() Else  If svIsValidBcfDtInterestDefer = 'N' Then '1111-11-11' Else svTransformBcfDtInterestDefer,
		IFF(svIsNullBcfDtInterestDefer = 'N', SETNULL(), IFF(svIsValidBcfDtInterestDefer = 'N', '1111-11-11', svTransformBcfDtInterestDefer)) AS DATE_INT_DEFR_END,
		-- *SRC*: \(20)If svIsNullBcfDtPaymentDefer = 'N' Then SetNull() Else  If svIsValidBcfDtPaymentDefer = 'N' Then '1111-11-11' Else svTransformBcfDtPaymentDefer,
		IFF(svIsNullBcfDtPaymentDefer = 'N', SETNULL(), IFF(svIsValidBcfDtPaymentDefer = 'N', '1111-11-11', svTransformBcfDtPaymentDefer)) AS DATE_PAYT_DEFR_END,
		-- *SRC*: \(20)If svIsNullBcfDtFirstTrans = 'N' Then SetNull() Else  If svIsValidBcfDtFirstTrans = 'N' Then '1111-11-11' Else svTransformBcfDtFirstTrans,
		IFF(svIsNullBcfDtFirstTrans = 'N', SETNULL(), IFF(svIsValidBcfDtFirstTrans = 'N', '1111-11-11', svTransformBcfDtFirstTrans)) AS DATE_FRST_TRAN,
		-- *SRC*: \(20)If svIsNullBcfDtPaidOff = 'N' Then SetNull() Else  If svIsValidBcfDtPaidOff = 'N' Then '1111-11-11' Else svTransformBcfDtPaidOff,
		IFF(svIsNullBcfDtPaidOff = 'N', SETNULL(), IFF(svIsValidBcfDtPaidOff = 'N', '1111-11-11', svTransformBcfDtPaidOff)) AS DATE_PAID_OFF,
		-- *SRC*: \(20)If svIsNullBcfDtLastPayt = 'N' Then SetNull() Else  If svIsValidBcfDtLastPayt = 'N' Then '1111-11-11' Else svTransformBcfDtLastPayt,
		IFF(svIsNullBcfDtLastPayt = 'N', SETNULL(), IFF(svIsValidBcfDtLastPayt = 'N', '1111-11-11', svTransformBcfDtLastPayt)) AS DATE_LAST_PAYT,
		-- *SRC*: \(20)If svIsNullBcfDtLastMntn = 'N' Then SetNull() Else  If svIsValidBcfDtLastMntn = 'N' Then '1111-11-11' Else svTransformBcfDtLastMntn,
		IFF(svIsNullBcfDtLastMntn = 'N', SETNULL(), IFF(svIsValidBcfDtLastMntn = 'N', '1111-11-11', svTransformBcfDtLastMntn)) AS DATE_LAST_MNTN,
		{{ ref('BCFINSG') }}.BCF_LTD_HIGH_BALANCE AS LFTD_HIGH_BALN,
		{{ ref('BCFINSG') }}.BCF_PYMT_TBL_HIGH_BALANCE AS PAYT_TABL_HIGH_BALN,
		{{ ref('BCFINSG') }}.BCF_LTD_INTEREST_CHGD AS LFTD_ICHG,
		{{ ref('BCFINSG') }}.BCF_LTD_INTEREST_WAIVED AS LFTD_INT_WAVR,
		{{ ref('BCFINSG') }}.BCF_FIXED_PAY_AMT AS FIX_PAYT_AMT,
		{{ ref('BCFINSG') }}.BCF_FIXED_PAY_CYCLES AS FIX_PACY,
		{{ ref('BCFINSG') }}.BCF_LAST_INT_RATE AS LAST_IRTE,
		-- *SRC*: \(20)If Trim(( IF IsNotNull((FrmSrc.BCF_LAST_RATE_CODE)) THEN (FrmSrc.BCF_LAST_RATE_CODE) ELSE "")) = '' then SetNull() Else Trim(FrmSrc.BCF_LAST_RATE_CODE),
		IFF(TRIM(IFF({{ ref('BCFINSG') }}.BCF_LAST_RATE_CODE IS NOT NULL, {{ ref('BCFINSG') }}.BCF_LAST_RATE_CODE, '')) = '', SETNULL(), TRIM({{ ref('BCFINSG') }}.BCF_LAST_RATE_CODE)) AS LAST_RATE_CODE,
		{{ ref('BCFINSG') }}.BCF_LAST_RATE_CODE_SEQ AS LAST_RATE_CODE_SEQN,
		-- *SRC*: \(20)If Trim(( IF IsNotNull((FrmSrc.BCF_LAST_MIN_PAY_CODE)) THEN (FrmSrc.BCF_LAST_MIN_PAY_CODE) ELSE "")) = '' then SetNull() Else Trim(FrmSrc.BCF_LAST_MIN_PAY_CODE),
		IFF(TRIM(IFF({{ ref('BCFINSG') }}.BCF_LAST_MIN_PAY_CODE IS NOT NULL, {{ ref('BCFINSG') }}.BCF_LAST_MIN_PAY_CODE, '')) = '', SETNULL(), TRIM({{ ref('BCFINSG') }}.BCF_LAST_MIN_PAY_CODE)) AS LAST_MIN_PAYT_CODE,
		{{ ref('BCFINSG') }}.BCF_LAST_MIN_PAY_CODE_SEQ AS LAST_MIN_PAYT_CODE_SEQN,
		{{ ref('BCFINSG') }}.BCF_MIN_PAY_AMT AS LAST_MIN_PAYT_AMT,
		{{ ref('BCFINSG') }}.BCF_MIN_PAY_DUE AS CURR_MIN_PAYT_DUE,
		{{ ref('BCFINSG') }}.BCF_MIN_PAY_PAST_DUE AS MIN_PAYT_PAST_DUE,
		{{ ref('BCFINSG') }}.BCF_AMT_LAST_PYMT_APPLIED AS LAST_APPY_PAYT_AMT,
		{{ ref('BCFINSG') }}.BCF_PAYMENTS_BEFORE_GRACE AS PAYT_BFOR_GRCE,
		{{ ref('BCFINSG') }}.BCF_ORIGINAL_BALANCE AS ORIG_BALN,
		{{ ref('BCFINSG') }}.BCF_RATE_SAVER_RATE AS INT_SAVE_RATE,
		-- *SRC*: \(20)If svIsNullBcfPlanDueDt = 'N' Then SetNull() Else  If svIsValidBcfPlanDueDt = 'N' Then '1111-11-11' Else svTransformBcfPlanDueDt,
		IFF(svIsNullBcfPlanDueDt = 'N', SETNULL(), IFF(svIsValidBcfPlanDueDt = 'N', '1111-11-11', svTransformBcfPlanDueDt)) AS PLAN_DUE_DATE,
		-- *SRC*: \(20)If svIsNullBcfDtEndInterestFree = 'N' Then SetNull() Else  If svIsValidBcfDtEndInterestFree = 'N' Then '1111-11-11' Else svTransformBcfDtEndInterestFree,
		IFF(svIsNullBcfDtEndInterestFree = 'N', SETNULL(), IFF(svIsValidBcfDtEndInterestFree = 'N', '1111-11-11', svTransformBcfDtEndInterestFree)) AS INT_FEE_END_DATE,
		{{ ref('BCFINSG') }}.BCF_INTEREST_FREE_PRIN_AMT AS INT_FREE_BALN,
		{{ ref('BCFINSG') }}.BCF_OPENING_BALANCE AS OPEN_BALN_CURR_CYCL,
		{{ ref('BCFINSG') }}.BCF_CURRENT AS CTD_SALE_TRAN,
		{{ ref('BCFINSG') }}.BCF_DEBITS AS CTD_DR_TRAN,
		{{ ref('BCFINSG') }}.BCF_CREDITS AS CTD_CR_TRAN,
		{{ ref('BCFINSG') }}.BCF_PAYMENTS AS CTD_PAYT_TRAN,
		{{ ref('BCFINSG') }}.BCF_INT_OPEN_NON_ACCR AS INT_UNPD_OPEN_NOT_ACRL_BALN,
		{{ ref('BCFINSG') }}.BCF_INT_CTD_NON_ACCR AS INT_UNPD_CTD_NOT_ACRL_BALN,
		{{ ref('BCFINSG') }}.BCF_INT_CURR_CYC_BAL AS INT_UNPD_CURR_CYCL_BALN,
		{{ ref('BCFINSG') }}.BCF_INT_1CYC_AGO_BAL AS INT_UNPD_1_CYCL_AGO_BALN,
		{{ ref('BCFINSG') }}.BCF_INT_2CYC_AGO_BAL AS INT_UNPD_2_CYCL_AGO_BALN,
		{{ ref('BCFINSG') }}.BCF_FEES_OPEN_NON_ACCR AS FEE_UNPD_OPEN_NOT_ACRL_BALN,
		{{ ref('BCFINSG') }}.BCF_FEES_CTD_NON_ACCR AS FEE_UNPD_CTD_NOT_ACRL_BALN,
		{{ ref('BCFINSG') }}.BCF_FEES_CURR_CYC_BAL AS FEE_UNPD_CURR_CYCL_BALN,
		{{ ref('BCFINSG') }}.BCF_FEES_1CYC_AGO_BAL AS FEE_UNPD_1_CYCL_AGO_BALN,
		{{ ref('BCFINSG') }}.BCF_FEES_2CYC_AGO_BAL AS FEE_UNPD_2_CYCL_AGO_BALN,
		{{ ref('BCFINSG') }}.BCF_AMF_OPEN_NON_ACCR AS AMF_UNPD_OPEN_NOT_ACRL_BALN,
		{{ ref('BCFINSG') }}.BCF_AMF_CTD_NON_ACCR AS AMF_UNPD_CTD_NOT_ACRL_BALN,
		{{ ref('BCFINSG') }}.BCF_AMF_CURR_CYC_BAL AS AMF_UNPD_CURR_CYCL_BALN,
		{{ ref('BCFINSG') }}.BCF_AMF_1CYC_AGO_BAL AS AMF_UNPD_1_CYCL_AGO_BALN,
		{{ ref('BCFINSG') }}.BCF_AMF_2CYC_AGO_BAL AS AMF_UNPD_2_CYCL_AGO_BALN,
		{{ ref('BCFINSG') }}.BCF_INS_OPEN_NON_ACCR AS INSR_UNPD_OPEN_NOT_ACRL_BALN,
		{{ ref('BCFINSG') }}.BCF_INS_CTD_NON_ACCR AS INSR_UNPD_CTD_NOT_ACRL_BALN,
		{{ ref('BCFINSG') }}.BCF_INS_CURR_CYC_BAL AS INSR_UNPD_CURR_CYCL_BALN,
		{{ ref('BCFINSG') }}.BCF_INS_1CYC_AGO_BAL AS INSR_UNPD_1_CYCL_AGO_BALN,
		{{ ref('BCFINSG') }}.BCF_INS_2CYC_AGO_BAL AS INSR_UNPD_2_CYCL_AGO_BALN,
		{{ ref('BCFINSG') }}.BCF_PRIN_OPEN_NON_ACCR AS PRIN_UNPD_OPEN_NOT_ACRL_BALN,
		{{ ref('BCFINSG') }}.BCF_PRIN_CTD_NON_ACCR AS PRIN_UNPD_CTD_NOT_ACRL_BALN,
		{{ ref('BCFINSG') }}.BCF_PRIN_CURR_CYC_BAL AS PRIN_UNPD_CURR_CYCL_BALN,
		{{ ref('BCFINSG') }}.BCF_PRIN_1CYC_AGO_BAL AS PRIN_UNPD_1_CYCL_AGO_BALN,
		{{ ref('BCFINSG') }}.BCF_PRIN_2CYC_AGO_BAL AS PRIN_UNPD_2_CYCL_AGO_BALN,
		{{ ref('BCFINSG') }}.BCF_AGGR_CURR_CYC_BAL AS AGGR_CURR_CYCL_BALN,
		{{ ref('BCFINSG') }}.BCF_AGGR_1CYC_AGO_BAL AS AGGR_1_CYCL_AGO_BALN,
		{{ ref('BCFINSG') }}.BCF_AGGR_2CYC_AGO_BAL AS AGGR_2_CYCL_AGO_BALN,
		{{ ref('BCFINSG') }}.BCF_AGGR_DELAYED_BAL AS AGGR_DLAY_BALN,
		{{ ref('BCFINSG') }}.BCF_DELAYED_DAYS AS DLAY_DAY_QNTY,
		{{ ref('BCFINSG') }}.BCF_CTD_TRANS_FEE AS CTD_CSAD_FEE_AMT,
		{{ ref('BCFINSG') }}.BCF_CTD_TRANS_FEE_AMT AS CTD_SYST_GENR_CSAD_FEE_AMT,
		{{ ref('BCFINSG') }}.BCF_DEFERRED_DAYS AS INT_DEFR_DAY_QNTY,
		{{ ref('BCFINSG') }}.BCF_DEFERRED_INTEREST AS INT_DEFR_AMT,
		{{ ref('BCFINSG') }}.BCF_AGGR_DEFERRED_BAL AS INT_DEFR_AGGR_CURR_BALN,
		-- *SRC*: \(20)If Trim(( IF IsNotNull((FrmSrc.BCF_USER_CODE)) THEN (FrmSrc.BCF_USER_CODE) ELSE "")) = '' then SetNull() Else Trim(FrmSrc.BCF_USER_CODE),
		IFF(TRIM(IFF({{ ref('BCFINSG') }}.BCF_USER_CODE IS NOT NULL, {{ ref('BCFINSG') }}.BCF_USER_CODE, '')) = '', SETNULL(), TRIM({{ ref('BCFINSG') }}.BCF_USER_CODE)) AS USER_CODE,
		-- *SRC*: \(20)If Trim(( IF IsNotNull((FrmSrc.BCF_MIGRATE_TO_PLAN)) THEN (FrmSrc.BCF_MIGRATE_TO_PLAN) ELSE "")) = '' then SetNull() Else Trim(FrmSrc.BCF_MIGRATE_TO_PLAN),
		IFF(TRIM(IFF({{ ref('BCFINSG') }}.BCF_MIGRATE_TO_PLAN IS NOT NULL, {{ ref('BCFINSG') }}.BCF_MIGRATE_TO_PLAN, '')) = '', SETNULL(), TRIM({{ ref('BCFINSG') }}.BCF_MIGRATE_TO_PLAN)) AS MIGR_TO_PLAN_IDNN,
		{{ ref('BCFINSG') }}.BCF_MIGRATE_TO_SEQ AS MIGR_TO_PLAN_SQNO,
		-- *SRC*: \(20)If svIsNullBcfDtMigrate = 'N' Then SetNull() Else  If svIsValidBcfDtMigrate = 'N' Then '1111-11-11' Else svTransformBcfDtMigrate,
		IFF(svIsNullBcfDtMigrate = 'N', SETNULL(), IFF(svIsValidBcfDtMigrate = 'N', '1111-11-11', svTransformBcfDtMigrate)) AS DATE_MIGR,
		{{ ref('BCFINSG') }}.BCF_DISPUTE_AMT AS DSPT_AMT,
		{{ ref('BCFINSG') }}.BCF_EXT_DISPUTE_AMT AS EXCL_DSPT_AMT,
		{{ ref('BCFINSG') }}.BCF_ACCR_DISPUTE_AMT AS ACRL_DSPT_AMT,
		{{ ref('BCFINSG') }}.BCF_FL_INSTALLMENTS_BILLED AS FRNT_LOAD_ISMT_BILL,
		-- *SRC*: \(20)If svIsNullBcfFlLastInstallmentsDt = 'N' Then SetNull() Else  If svIsValidBcfFlLastInstallmentsDt = 'N' Then '1111-11-11' Else svTransformBcfFlLastInstallmentsDt,
		IFF(svIsNullBcfFlLastInstallmentsDt = 'N', SETNULL(), IFF(svIsValidBcfFlLastInstallmentsDt = 'N', '1111-11-11', svTransformBcfFlLastInstallmentsDt)) AS FRNT_LOAD_LAST_ISMT_DATE,
		{{ ref('BCFINSG') }}.BCF_FL_ORIG_INTEREST_AMT AS FRNT_LOAD_ORIG_INT_AMT,
		{{ ref('BCFINSG') }}.BCF_FL_EARNED_INTEREST_AMT AS FRNT_LOAD_EARN_INT_AMT,
		{{ ref('BCFINSG') }}.BCF_FL_REBATE_INTEREST_AMT AS FRNT_LOAD_REBT_INT_AMT,
		{{ ref('BCFINSG') }}.BCF_FL_INTEREST_RATE AS FRNT_LOAD_IRTE,
		{{ ref('BCFINSG') }}.BCF_FL_ORIG_INSUR_AMT AS FRNT_LOAD_ORIG_INSR_AMT,
		{{ ref('BCFINSG') }}.BCF_FL_EARNED_INSUR_AMT AS FRNT_LOAD_EARN_INSR_AMT,
		{{ ref('BCFINSG') }}.BCF_FL_UPFRONT_INSUR_AMT AS FRNT_LOAD_UPFR_INSR_AMT,
		{{ ref('BCFINSG') }}.BCF_FL_REBATE_INSUR_AMT AS FRNT_LOAD_REBT_INSR_AMT,
		-- *SRC*: \(20)If svIsNullBcfSchedPayoffDt = 'N' Then SetNull() Else  If svIsValidBcfSchedPayoffDt = 'N' Then '1111-11-11' Else svTransformBcfSchedPayoffDt,
		IFF(svIsNullBcfSchedPayoffDt = 'N', SETNULL(), IFF(svIsValidBcfSchedPayoffDt = 'N', '1111-11-11', svTransformBcfSchedPayoffDt)) AS SCHE_PAYF_DATE,
		{{ ref('BCFINSG') }}.BCF_SCHED_PAYOFF_AMT AS SCHE_PAYF_AMT,
		{{ ref('BCFINSG') }}.BCF_SCHED_PAYOFF_FEE AS SCHE_PAYF_FEE,
		-- *SRC*: \(20)If Trim(( IF IsNotNull((FrmSrc.BCF_SCHED_PAYOFF_REASON)) THEN (FrmSrc.BCF_SCHED_PAYOFF_REASON) ELSE "")) = '' then SetNull() Else Trim(FrmSrc.BCF_SCHED_PAYOFF_REASON),
		IFF(TRIM(IFF({{ ref('BCFINSG') }}.BCF_SCHED_PAYOFF_REASON IS NOT NULL, {{ ref('BCFINSG') }}.BCF_SCHED_PAYOFF_REASON, '')) = '', SETNULL(), TRIM({{ ref('BCFINSG') }}.BCF_SCHED_PAYOFF_REASON)) AS SCHE_PAYF_REAS,
		-- *SRC*: \(20)If svIsNullBcfActualPayoffDt = 'N' Then SetNull() Else  If svIsValidBcfActualPayoffDt = 'N' Then '1111-11-11' Else svTransformBcfActualPayoffDt,
		IFF(svIsNullBcfActualPayoffDt = 'N', SETNULL(), IFF(svIsValidBcfActualPayoffDt = 'N', '1111-11-11', svTransformBcfActualPayoffDt)) AS ACTL_PAYF_DATE,
		{{ ref('BCFINSG') }}.BCF_ACTUAL_PAYOFF_AMT AS ACTL_PAYF_AMT,
		{{ ref('BCFINSG') }}.BCF_FL_UPFRONT_INSUR_PAID AS FRNT_LOAD_INSR_PAID,
		{{ ref('BCFINSG') }}.BCF_FL_REBATE_INSUR_PAID AS FRNT_LOAD_REBT_INSR_PAID,
		{{ ref('BCFINSG') }}.BCF_GOVT_NON_ACCR_OPN_AMT AS GOVT_CHRG_NOT_ACRL_OPEN_AMT,
		{{ ref('BCFINSG') }}.BCF_GOVT_NON_ACCR_CTD_AMT AS GOVT_CHRG_NOT_ACRL_CTD_AMT,
		{{ ref('BCFINSG') }}.BCF_GOVT_BAL_CURR_CYC_AMT AS GOVT_CHRG_CURR_CYCL_AMT,
		{{ ref('BCFINSG') }}.BCF_GOVT_BAL_1CYC_AGO_AMT AS GOVT_CHRG_1_CYCL_AGO_AMT,
		{{ ref('BCFINSG') }}.BCF_GOVT_BAL_2CYC_AGO_AMT AS GOVT_CHRG_2_CYCL_AGO_AMT,
		{{ ref('BCFINSG') }}.BCF_CTD_FIN_CHG_REV AS CTD_FNCL_CHRG_REV,
		{{ ref('BCFINSG') }}.BCF_INSTALL_TERM AS ISMT_QNTY,
		{{ ref('BCFINSG') }}.BCF_PREV_INSTALL_TERM AS ISMT_PREV_QNTY,
		-- *SRC*: \(20)If svIsNullBcfDtInstallTermChg = 'N' Then SetNull() Else  If svIsValidBcfDtInstallTermChg = 'N' Then '1111-11-11' Else svTransformBcfDtInstallTermChg,
		IFF(svIsNullBcfDtInstallTermChg = 'N', SETNULL(), IFF(svIsValidBcfDtInstallTermChg = 'N', '1111-11-11', svTransformBcfDtInstallTermChg)) AS DATE_ISMT_TERM_CHNG,
		{{ ref('BCFINSG') }}.BCF_PREV_MIN_PAY_AMT AS PREV_MIN_PAYT_AMT,
		{{ ref('BCFINSG') }}.BCF_ORIG_LOAN_BAL AS ORIG_LOAN_BALN,
		{{ ref('BCFINSG') }}.BCF_LTD_ALL_CRDTS AS LFTD_ALL_CR,
		{{ ref('BCFINSG') }}.BCF_LTD_INTEREST_SAVED AS LFTD_INT_SAVE,
		{{ ref('BCFINSG') }}.BCF_PREV_CYC_INT_SAVED AS PREV_CYCL_INT_SAVE,
		-- *SRC*: \(20)If svIsNullBcfDtInstallPaid = 'N' Then SetNull() Else  If svIsValidBcfDtInstallPaid = 'N' Then '1111-11-11' Else svTransformBcfDtInstallPaid,
		IFF(svIsNullBcfDtInstallPaid = 'N', SETNULL(), IFF(svIsValidBcfDtInstallPaid = 'N', '1111-11-11', svTransformBcfDtInstallPaid)) AS DATE_LOAN_PAID_OUT,
		-- *SRC*: \(20)If svIsNullBcfProjectedPayoffDt = 'N' Then SetNull() Else  If svIsValidBcfProjectedPayoffDt = 'N' Then '1111-11-11' Else svTransformBcfProjectedPayoffDt,
		IFF(svIsNullBcfProjectedPayoffDt = 'N', SETNULL(), IFF(svIsValidBcfProjectedPayoffDt = 'N', '1111-11-11', svTransformBcfProjectedPayoffDt)) AS PRJC_PAY_OFF_DATE,
		{{ ref('BCFINSG') }}.BCF_DISPUTE_TIMES AS DSPT_QNTY,
		-- *SRC*: \(20)If svIsNullBcfDisputeOldDt = 'N' Then SetNull() Else  If svIsValidBcfDisputeOldDt = 'N' Then '1111-11-11' Else svTransformBcfDisputeOldDt,
		IFF(svIsNullBcfDisputeOldDt = 'N', SETNULL(), IFF(svIsValidBcfDisputeOldDt = 'N', '1111-11-11', svTransformBcfDisputeOldDt)) AS DSPT_OLD_DATE,
		{{ ref('BCFINSG') }}.BCF_TERM AS TERM,
		svRowI AS ROW_I,
		-- *SRC*: StringToDate(pRUN_STRM_PROS_D, "%yyyy%mm%dd") : ' 00:00:00',
		CONCAT(STRINGTODATE(pRUN_STRM_PROS_D, '%yyyy%mm%dd'), ' 00:00:00') AS EFFT_S,
		-- *SRC*: StringToDate(pRUN_STRM_PROS_D, "%yyyy%mm%dd"),
		STRINGTODATE(pRUN_STRM_PROS_D, '%yyyy%mm%dd') AS EFFT_D,
		'00:00:00' AS EFFT_T,
		pODS_PROS_ID AS PROS_KEY_EFFT_I,
		0 AS ROW_SECU_ACCS_C
	FROM {{ ref('BCFINSG') }}
	WHERE svIsValidRecord = 'N'
)

SELECT * FROM XfmToTable__ToTable