{{ config(materialized='view', tags=['XfmPlanBalnSegmMstrFromBCFINSG']) }}

WITH XfmToTable__BcfDtEndIntrstFree AS (
	SELECT
		-- *SRC*: \(20)If IsNull(FrmSrc.BCF_PLAN_DUE_DATE) then 'N' else  if Trim(FrmSrc.BCF_PLAN_DUE_DATE) = '' then 'N' else  if Trim(FrmSrc.BCF_PLAN_DUE_DATE) = '000000000.' then 'N' Else 'Y',
		IFF({{ ref('BCFINSG') }}.BCF_PLAN_DUE_DATE IS NULL, 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_PLAN_DUE_DATE) = '', 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_PLAN_DUE_DATE) = '000000000.', 'N', 'Y'))) AS svIsNullBcfPlanDueDt,
		-- *SRC*: Trim(( IF IsNotNull((FrmSrc.BCF_PLAN_DUE_DATE)) THEN (FrmSrc.BCF_PLAN_DUE_DATE) ELSE "")[3, 4]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_PLAN_DUE_DATE)) THEN (FrmSrc.BCF_PLAN_DUE_DATE) ELSE "")[7, 2]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_PLAN_DUE_DATE)) THEN (FrmSrc.BCF_PLAN_DUE_DATE) ELSE "")[9, 2]),
		CONCAT(CONCAT(CONCAT(CONCAT(TRIM(IFF({{ ref('BCFINSG') }}.BCF_PLAN_DUE_DATE IS NOT NULL, {{ ref('BCFINSG') }}.BCF_PLAN_DUE_DATE, '')), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_PLAN_DUE_DATE IS NOT NULL, {{ ref('BCFINSG') }}.BCF_PLAN_DUE_DATE, ''))), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_PLAN_DUE_DATE IS NOT NULL, {{ ref('BCFINSG') }}.BCF_PLAN_DUE_DATE, ''))) AS svTransformBcfPlanDueDt,
		-- *SRC*: \(20)If IsValid('date', svTransformBcfPlanDueDt) Then 'Y' else  if Trim(FrmSrc.BCF_PLAN_DUE_DATE) = '000000000.' Then 'Y' Else 'N',
		IFF(ISVALID('date', svTransformBcfPlanDueDt), 'Y', IFF(TRIM({{ ref('BCFINSG') }}.BCF_PLAN_DUE_DATE) = '000000000.', 'Y', 'N')) AS svIsValidBcfPlanDueDt,
		-- *SRC*: \(20)If IsNull(FrmSrc.BCF_DATE_END_INTEREST_FREE) then 'N' else  if Trim(FrmSrc.BCF_DATE_END_INTEREST_FREE) = '' then 'N' else  if Trim(FrmSrc.BCF_DATE_END_INTEREST_FREE) = '000000000.' then 'N' Else 'Y',
		IFF({{ ref('BCFINSG') }}.BCF_DATE_END_INTEREST_FREE IS NULL, 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DATE_END_INTEREST_FREE) = '', 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DATE_END_INTEREST_FREE) = '000000000.', 'N', 'Y'))) AS svIsNullBcfDtEndInterestFree,
		-- *SRC*: Trim(( IF IsNotNull((FrmSrc.BCF_DATE_END_INTEREST_FREE)) THEN (FrmSrc.BCF_DATE_END_INTEREST_FREE) ELSE "")[3, 4]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_DATE_END_INTEREST_FREE)) THEN (FrmSrc.BCF_DATE_END_INTEREST_FREE) ELSE "")[7, 2]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_DATE_END_INTEREST_FREE)) THEN (FrmSrc.BCF_DATE_END_INTEREST_FREE) ELSE "")[9, 2]),
		CONCAT(CONCAT(CONCAT(CONCAT(TRIM(IFF({{ ref('BCFINSG') }}.BCF_DATE_END_INTEREST_FREE IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DATE_END_INTEREST_FREE, '')), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_DATE_END_INTEREST_FREE IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DATE_END_INTEREST_FREE, ''))), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_DATE_END_INTEREST_FREE IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DATE_END_INTEREST_FREE, ''))) AS svTransformBcfDtEndInterestFree,
		-- *SRC*: \(20)If IsValid('date', svTransformBcfDtEndInterestFree) Then 'Y' else  if Trim(FrmSrc.BCF_DATE_END_INTEREST_FREE) = '000000000.' Then 'Y' Else 'N',
		IFF(ISVALID('date', svTransformBcfDtEndInterestFree), 'Y', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DATE_END_INTEREST_FREE) = '000000000.', 'Y', 'N')) AS svIsValidBcfDtEndInterestFree,
		-- *SRC*: \(20)If IsNull(FrmSrc.BCF_DT_MIGRATE) then 'N' else  if Trim(FrmSrc.BCF_DT_MIGRATE) = '' then 'N' else  if Trim(FrmSrc.BCF_DT_MIGRATE) = '000000000.' then 'N' Else 'Y',
		IFF({{ ref('BCFINSG') }}.BCF_DT_MIGRATE IS NULL, 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_MIGRATE) = '', 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_MIGRATE) = '000000000.', 'N', 'Y'))) AS svIsNullBcfDtMigrate,
		-- *SRC*: Trim(( IF IsNotNull((FrmSrc.BCF_DT_MIGRATE)) THEN (FrmSrc.BCF_DT_MIGRATE) ELSE "")[3, 4]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_DT_MIGRATE)) THEN (FrmSrc.BCF_DT_MIGRATE) ELSE "")[7, 2]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_DT_MIGRATE)) THEN (FrmSrc.BCF_DT_MIGRATE) ELSE "")[9, 2]),
		CONCAT(CONCAT(CONCAT(CONCAT(TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_MIGRATE IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_MIGRATE, '')), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_MIGRATE IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_MIGRATE, ''))), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_MIGRATE IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_MIGRATE, ''))) AS svTransformBcfDtMigrate,
		-- *SRC*: \(20)If IsValid('date', svTransformBcfDtMigrate) Then 'Y' else  if Trim(FrmSrc.BCF_DT_MIGRATE) = '000000000.' then 'Y' Else 'N',
		IFF(ISVALID('date', svTransformBcfDtMigrate), 'Y', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_MIGRATE) = '000000000.', 'Y', 'N')) AS svIsValidBcfDtMigrate,
		-- *SRC*: \(20)If IsNull(FrmSrc.BCF_FL_LAST_INSTALLMENT_DT) then 'N' else  if Trim(FrmSrc.BCF_FL_LAST_INSTALLMENT_DT) = '' then 'N' else  if Trim(FrmSrc.BCF_FL_LAST_INSTALLMENT_DT) = '000000000.' then 'N' Else 'Y',
		IFF({{ ref('BCFINSG') }}.BCF_FL_LAST_INSTALLMENT_DT IS NULL, 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_FL_LAST_INSTALLMENT_DT) = '', 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_FL_LAST_INSTALLMENT_DT) = '000000000.', 'N', 'Y'))) AS svIsNullBcfFlLastInstallmentsDt,
		-- *SRC*: Trim(( IF IsNotNull((FrmSrc.BCF_FL_LAST_INSTALLMENT_DT)) THEN (FrmSrc.BCF_FL_LAST_INSTALLMENT_DT) ELSE "")[3, 4]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_FL_LAST_INSTALLMENT_DT)) THEN (FrmSrc.BCF_FL_LAST_INSTALLMENT_DT) ELSE "")[7, 2]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_FL_LAST_INSTALLMENT_DT)) THEN (FrmSrc.BCF_FL_LAST_INSTALLMENT_DT) ELSE "")[9, 2]),
		CONCAT(CONCAT(CONCAT(CONCAT(TRIM(IFF({{ ref('BCFINSG') }}.BCF_FL_LAST_INSTALLMENT_DT IS NOT NULL, {{ ref('BCFINSG') }}.BCF_FL_LAST_INSTALLMENT_DT, '')), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_FL_LAST_INSTALLMENT_DT IS NOT NULL, {{ ref('BCFINSG') }}.BCF_FL_LAST_INSTALLMENT_DT, ''))), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_FL_LAST_INSTALLMENT_DT IS NOT NULL, {{ ref('BCFINSG') }}.BCF_FL_LAST_INSTALLMENT_DT, ''))) AS svTransformBcfFlLastInstallmentsDt,
		-- *SRC*: \(20)If IsValid('date', svTransformBcfFlLastInstallmentsDt) Then 'Y' else  if Trim(FrmSrc.BCF_FL_LAST_INSTALLMENT_DT) = '000000000.' then 'Y' Else 'N',
		IFF(ISVALID('date', svTransformBcfFlLastInstallmentsDt), 'Y', IFF(TRIM({{ ref('BCFINSG') }}.BCF_FL_LAST_INSTALLMENT_DT) = '000000000.', 'Y', 'N')) AS svIsValidBcfFlLastInstallmentsDt,
		-- *SRC*: \(20)If IsNull(FrmSrc.BCF_SCHED_PAYOFF_DT) then 'N' else  if Trim(FrmSrc.BCF_SCHED_PAYOFF_DT) = '' then 'N' else  if Trim(FrmSrc.BCF_SCHED_PAYOFF_DT) = '000000000.' then 'N' Else 'Y',
		IFF({{ ref('BCFINSG') }}.BCF_SCHED_PAYOFF_DT IS NULL, 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_SCHED_PAYOFF_DT) = '', 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_SCHED_PAYOFF_DT) = '000000000.', 'N', 'Y'))) AS svIsNullBcfSchedPayoffDt,
		-- *SRC*: Trim(( IF IsNotNull((FrmSrc.BCF_SCHED_PAYOFF_DT)) THEN (FrmSrc.BCF_SCHED_PAYOFF_DT) ELSE "")[3, 4]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_SCHED_PAYOFF_DT)) THEN (FrmSrc.BCF_SCHED_PAYOFF_DT) ELSE "")[7, 2]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_SCHED_PAYOFF_DT)) THEN (FrmSrc.BCF_SCHED_PAYOFF_DT) ELSE "")[9, 2]),
		CONCAT(CONCAT(CONCAT(CONCAT(TRIM(IFF({{ ref('BCFINSG') }}.BCF_SCHED_PAYOFF_DT IS NOT NULL, {{ ref('BCFINSG') }}.BCF_SCHED_PAYOFF_DT, '')), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_SCHED_PAYOFF_DT IS NOT NULL, {{ ref('BCFINSG') }}.BCF_SCHED_PAYOFF_DT, ''))), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_SCHED_PAYOFF_DT IS NOT NULL, {{ ref('BCFINSG') }}.BCF_SCHED_PAYOFF_DT, ''))) AS svTransformBcfSchedPayoffDt,
		-- *SRC*: \(20)If IsValid('date', svTransformBcfSchedPayoffDt) Then 'Y' else  if Trim(FrmSrc.BCF_SCHED_PAYOFF_DT) = '000000000.' then 'Y' Else 'N',
		IFF(ISVALID('date', svTransformBcfSchedPayoffDt), 'Y', IFF(TRIM({{ ref('BCFINSG') }}.BCF_SCHED_PAYOFF_DT) = '000000000.', 'Y', 'N')) AS svIsValidBcfSchedPayoffDt,
		-- *SRC*: \(20)If IsNull(FrmSrc.BCF_ACTUAL_PAYOFF_DT) then 'N' else  if Trim(FrmSrc.BCF_ACTUAL_PAYOFF_DT) = '' then 'N' else  if Trim(FrmSrc.BCF_ACTUAL_PAYOFF_DT) = '000000000.' then 'N' Else 'Y',
		IFF({{ ref('BCFINSG') }}.BCF_ACTUAL_PAYOFF_DT IS NULL, 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_ACTUAL_PAYOFF_DT) = '', 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_ACTUAL_PAYOFF_DT) = '000000000.', 'N', 'Y'))) AS svIsNullBcfActualPayoffDt,
		-- *SRC*: Trim(( IF IsNotNull((FrmSrc.BCF_ACTUAL_PAYOFF_DT)) THEN (FrmSrc.BCF_ACTUAL_PAYOFF_DT) ELSE "")[3, 4]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_ACTUAL_PAYOFF_DT)) THEN (FrmSrc.BCF_ACTUAL_PAYOFF_DT) ELSE "")[7, 2]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_ACTUAL_PAYOFF_DT)) THEN (FrmSrc.BCF_ACTUAL_PAYOFF_DT) ELSE "")[9, 2]),
		CONCAT(CONCAT(CONCAT(CONCAT(TRIM(IFF({{ ref('BCFINSG') }}.BCF_ACTUAL_PAYOFF_DT IS NOT NULL, {{ ref('BCFINSG') }}.BCF_ACTUAL_PAYOFF_DT, '')), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_ACTUAL_PAYOFF_DT IS NOT NULL, {{ ref('BCFINSG') }}.BCF_ACTUAL_PAYOFF_DT, ''))), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_ACTUAL_PAYOFF_DT IS NOT NULL, {{ ref('BCFINSG') }}.BCF_ACTUAL_PAYOFF_DT, ''))) AS svTransformBcfActualPayoffDt,
		-- *SRC*: \(20)If IsValid('date', svTransformBcfActualPayoffDt) Then 'Y' else  if Trim(FrmSrc.BCF_ACTUAL_PAYOFF_DT) = '000000000.' then 'Y' Else 'N',
		IFF(ISVALID('date', svTransformBcfActualPayoffDt), 'Y', IFF(TRIM({{ ref('BCFINSG') }}.BCF_ACTUAL_PAYOFF_DT) = '000000000.', 'Y', 'N')) AS svIsValidBcfActualPayoffDt,
		-- *SRC*: \(20)If IsNull(FrmSrc.BCF_DT_INSTALL_TERM_CHG) then 'N' else  if Trim(FrmSrc.BCF_DT_INSTALL_TERM_CHG) = '' then 'N' else  if Trim(FrmSrc.BCF_DT_INSTALL_TERM_CHG) = '000000000.' then 'N' Else 'Y',
		IFF({{ ref('BCFINSG') }}.BCF_DT_INSTALL_TERM_CHG IS NULL, 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_INSTALL_TERM_CHG) = '', 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_INSTALL_TERM_CHG) = '000000000.', 'N', 'Y'))) AS svIsNullBcfDtInstallTermChg,
		-- *SRC*: Trim(( IF IsNotNull((FrmSrc.BCF_DT_INSTALL_TERM_CHG)) THEN (FrmSrc.BCF_DT_INSTALL_TERM_CHG) ELSE "")[3, 4]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_DT_INSTALL_TERM_CHG)) THEN (FrmSrc.BCF_DT_INSTALL_TERM_CHG) ELSE "")[7, 2]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_DT_INSTALL_TERM_CHG)) THEN (FrmSrc.BCF_DT_INSTALL_TERM_CHG) ELSE "")[9, 2]),
		CONCAT(CONCAT(CONCAT(CONCAT(TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_INSTALL_TERM_CHG IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_INSTALL_TERM_CHG, '')), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_INSTALL_TERM_CHG IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_INSTALL_TERM_CHG, ''))), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_INSTALL_TERM_CHG IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_INSTALL_TERM_CHG, ''))) AS svTransformBcfDtInstallTermChg,
		-- *SRC*: \(20)If IsValid('date', svTransformBcfDtInstallTermChg) Then 'Y' else  if Trim(FrmSrc.BCF_DT_INSTALL_TERM_CHG) = '000000000.' then 'Y' Else 'N',
		IFF(ISVALID('date', svTransformBcfDtInstallTermChg), 'Y', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_INSTALL_TERM_CHG) = '000000000.', 'Y', 'N')) AS svIsValidBcfDtInstallTermChg,
		-- *SRC*: \(20)If IsNull(FrmSrc.BCF_DT_INSTALL_PAID) then 'N' else  if Trim(FrmSrc.BCF_DT_INSTALL_PAID) = '' then 'N' else  if Trim(FrmSrc.BCF_DT_INSTALL_PAID) = '000000000.' then 'N' Else 'Y',
		IFF({{ ref('BCFINSG') }}.BCF_DT_INSTALL_PAID IS NULL, 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_INSTALL_PAID) = '', 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_INSTALL_PAID) = '000000000.', 'N', 'Y'))) AS svIsNullBcfDtInstallPaid,
		-- *SRC*: Trim(( IF IsNotNull((FrmSrc.BCF_DT_INSTALL_PAID)) THEN (FrmSrc.BCF_DT_INSTALL_PAID) ELSE "")[3, 4]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_DT_INSTALL_PAID)) THEN (FrmSrc.BCF_DT_INSTALL_PAID) ELSE "")[7, 2]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_DT_INSTALL_PAID)) THEN (FrmSrc.BCF_DT_INSTALL_PAID) ELSE "")[9, 2]),
		CONCAT(CONCAT(CONCAT(CONCAT(TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_INSTALL_PAID IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_INSTALL_PAID, '')), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_INSTALL_PAID IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_INSTALL_PAID, ''))), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_INSTALL_PAID IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_INSTALL_PAID, ''))) AS svTransformBcfDtInstallPaid,
		-- *SRC*: \(20)If IsValid('date', svTransformBcfDtInstallPaid) Then 'Y' else  if Trim(FrmSrc.BCF_DT_INSTALL_PAID) = '000000000.' then 'Y' Else 'N',
		IFF(ISVALID('date', svTransformBcfDtInstallPaid), 'Y', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_INSTALL_PAID) = '000000000.', 'Y', 'N')) AS svIsValidBcfDtInstallPaid,
		-- *SRC*: \(20)If IsNull(FrmSrc.BCF_PROJECTED_PAYOFF_DT) then 'N' else  if Trim(FrmSrc.BCF_PROJECTED_PAYOFF_DT) = '' then 'N' else  if Trim(FrmSrc.BCF_PROJECTED_PAYOFF_DT) = '0000000.' then 'N' Else 'Y',
		IFF({{ ref('BCFINSG') }}.BCF_PROJECTED_PAYOFF_DT IS NULL, 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_PROJECTED_PAYOFF_DT) = '', 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_PROJECTED_PAYOFF_DT) = '0000000.', 'N', 'Y'))) AS svIsNullBcfProjectedPayoffDt,
		-- *SRC*: \(20)If svIsNullBcfProjectedPayoffDt = 'Y' Then DateFromJulianDay(FrmSrc.BCF_PROJECTED_PAYOFF_DT) Else '',
		IFF(svIsNullBcfProjectedPayoffDt = 'Y', DATEFROMJULIANDAY({{ ref('BCFINSG') }}.BCF_PROJECTED_PAYOFF_DT), '') AS svTransformBcfProjectedPayoffDt,
		-- *SRC*: \(20)If IsValid('date', svTransformBcfProjectedPayoffDt) Then 'Y' else  if Trim(FrmSrc.BCF_PROJECTED_PAYOFF_DT) = '0000000.' then 'Y' Else 'N',
		IFF(ISVALID('date', svTransformBcfProjectedPayoffDt), 'Y', IFF(TRIM({{ ref('BCFINSG') }}.BCF_PROJECTED_PAYOFF_DT) = '0000000.', 'Y', 'N')) AS svIsValidBcfProjectedPayoffDt,
		-- *SRC*: \(20)If IsNull(FrmSrc.BCF_DISPUTE_OLD_DATE) then 'N' else  if Trim(FrmSrc.BCF_DISPUTE_OLD_DATE) = '' then 'N' else  if Trim(FrmSrc.BCF_DISPUTE_OLD_DATE) = '000000000.' then 'N' Else 'Y',
		IFF({{ ref('BCFINSG') }}.BCF_DISPUTE_OLD_DATE IS NULL, 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DISPUTE_OLD_DATE) = '', 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DISPUTE_OLD_DATE) = '000000000.', 'N', 'Y'))) AS svIsNullBcfDisputeOldDt,
		-- *SRC*: Trim(( IF IsNotNull((FrmSrc.BCF_DISPUTE_OLD_DATE)) THEN (FrmSrc.BCF_DISPUTE_OLD_DATE) ELSE "")[3, 4]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_DISPUTE_OLD_DATE)) THEN (FrmSrc.BCF_DISPUTE_OLD_DATE) ELSE "")[7, 2]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_DISPUTE_OLD_DATE)) THEN (FrmSrc.BCF_DISPUTE_OLD_DATE) ELSE "")[9, 2]),
		CONCAT(CONCAT(CONCAT(CONCAT(TRIM(IFF({{ ref('BCFINSG') }}.BCF_DISPUTE_OLD_DATE IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DISPUTE_OLD_DATE, '')), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_DISPUTE_OLD_DATE IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DISPUTE_OLD_DATE, ''))), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_DISPUTE_OLD_DATE IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DISPUTE_OLD_DATE, ''))) AS svTransformBcfDisputeOldDt,
		-- *SRC*: \(20)If IsValid('date', svTransformBcfDisputeOldDt) Then 'Y' else  if Trim(FrmSrc.BCF_DISPUTE_OLD_DATE) = '000000000.' then 'Y' Else 'N',
		IFF(ISVALID('date', svTransformBcfDisputeOldDt), 'Y', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DISPUTE_OLD_DATE) = '000000000.', 'Y', 'N')) AS svIsValidBcfDisputeOldDt,
		-- *SRC*: \(20)If IsNull(FrmSrc.BCF_DT_LAST_PAYMENT) then 'N' else  if Trim(FrmSrc.BCF_DT_LAST_PAYMENT) = '' then 'N' else  if Trim(FrmSrc.BCF_DT_LAST_PAYMENT) = '000000000.' then 'N' Else 'Y',
		IFF({{ ref('BCFINSG') }}.BCF_DT_LAST_PAYMENT IS NULL, 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_LAST_PAYMENT) = '', 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_LAST_PAYMENT) = '000000000.', 'N', 'Y'))) AS svIsNullBcfDtLastPayt,
		-- *SRC*: Trim(( IF IsNotNull((FrmSrc.BCF_DT_LAST_PAYMENT)) THEN (FrmSrc.BCF_DT_LAST_PAYMENT) ELSE "")[3, 4]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_DT_LAST_PAYMENT)) THEN (FrmSrc.BCF_DT_LAST_PAYMENT) ELSE "")[7, 2]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_DT_LAST_PAYMENT)) THEN (FrmSrc.BCF_DT_LAST_PAYMENT) ELSE "")[9, 2]),
		CONCAT(CONCAT(CONCAT(CONCAT(TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_LAST_PAYMENT IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_LAST_PAYMENT, '')), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_LAST_PAYMENT IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_LAST_PAYMENT, ''))), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_LAST_PAYMENT IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_LAST_PAYMENT, ''))) AS svTransformBcfDtLastPayt,
		-- *SRC*: \(20)If IsValid('date', svTransformBcfDtLastPayt) Then 'Y' else  if Trim(FrmSrc.BCF_DT_LAST_PAYMENT) = '000000000.' then 'Y' Else 'N',
		IFF(ISVALID('date', svTransformBcfDtLastPayt), 'Y', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_LAST_PAYMENT) = '000000000.', 'Y', 'N')) AS svIsValidBcfDtLastPayt,
		-- *SRC*: \(20)If IsNull(FrmSrc.BCF_DT_LAST_MAINT) then 'N' else  if Trim(FrmSrc.BCF_DT_LAST_MAINT) = '' then 'N' else  if Trim(FrmSrc.BCF_DT_LAST_MAINT) = '000000000.' then 'N' Else 'Y',
		IFF({{ ref('BCFINSG') }}.BCF_DT_LAST_MAINT IS NULL, 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_LAST_MAINT) = '', 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_LAST_MAINT) = '000000000.', 'N', 'Y'))) AS svIsNullBcfDtLastMntn,
		-- *SRC*: Trim(( IF IsNotNull((FrmSrc.BCF_DT_LAST_MAINT)) THEN (FrmSrc.BCF_DT_LAST_MAINT) ELSE "")[3, 4]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_DT_LAST_MAINT)) THEN (FrmSrc.BCF_DT_LAST_MAINT) ELSE "")[7, 2]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_DT_LAST_MAINT)) THEN (FrmSrc.BCF_DT_LAST_MAINT) ELSE "")[9, 2]),
		CONCAT(CONCAT(CONCAT(CONCAT(TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_LAST_MAINT IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_LAST_MAINT, '')), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_LAST_MAINT IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_LAST_MAINT, ''))), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_LAST_MAINT IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_LAST_MAINT, ''))) AS svTransformBcfDtLastMntn,
		-- *SRC*: \(20)If IsValid('date', svTransformBcfDtLastMntn) Then 'Y' else  if Trim(FrmSrc.BCF_DT_LAST_MAINT) = '000000000.' then 'Y' Else 'N',
		IFF(ISVALID('date', svTransformBcfDtLastMntn), 'Y', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_LAST_MAINT) = '000000000.', 'Y', 'N')) AS svIsValidBcfDtLastMntn,
		-- *SRC*: \(20)If IsNull(FrmSrc.BCF_DT_PAID_OFF) then 'N' else  if Trim(FrmSrc.BCF_DT_PAID_OFF) = '' then 'N' else  if Trim(FrmSrc.BCF_DT_PAID_OFF) = '000000000.' then 'N' Else 'Y',
		IFF({{ ref('BCFINSG') }}.BCF_DT_PAID_OFF IS NULL, 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_PAID_OFF) = '', 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_PAID_OFF) = '000000000.', 'N', 'Y'))) AS svIsNullBcfDtPaidOff,
		-- *SRC*: Trim(( IF IsNotNull((FrmSrc.BCF_DT_PAID_OFF)) THEN (FrmSrc.BCF_DT_PAID_OFF) ELSE "")[3, 4]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_DT_PAID_OFF)) THEN (FrmSrc.BCF_DT_PAID_OFF) ELSE "")[7, 2]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_DT_PAID_OFF)) THEN (FrmSrc.BCF_DT_PAID_OFF) ELSE "")[9, 2]),
		CONCAT(CONCAT(CONCAT(CONCAT(TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_PAID_OFF IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_PAID_OFF, '')), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_PAID_OFF IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_PAID_OFF, ''))), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_PAID_OFF IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_PAID_OFF, ''))) AS svTransformBcfDtPaidOff,
		-- *SRC*: \(20)If IsValid('date', svTransformBcfDtPaidOff) Then 'Y' else  if Trim(FrmSrc.BCF_DT_PAID_OFF) = '000000000.' then 'Y' Else 'N',
		IFF(ISVALID('date', svTransformBcfDtPaidOff), 'Y', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_PAID_OFF) = '000000000.', 'Y', 'N')) AS svIsValidBcfDtPaidOff,
		-- *SRC*: \(20)If IsNull(FrmSrc.BCF_DT_FIRST_TRANS) then 'N' else  if Trim(FrmSrc.BCF_DT_FIRST_TRANS) = '' then 'N' else  if Trim(FrmSrc.BCF_DT_FIRST_TRANS) = '000000000.' then 'N' Else 'Y',
		IFF({{ ref('BCFINSG') }}.BCF_DT_FIRST_TRANS IS NULL, 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_FIRST_TRANS) = '', 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_FIRST_TRANS) = '000000000.', 'N', 'Y'))) AS svIsNullBcfDtFirstTrans,
		-- *SRC*: Trim(( IF IsNotNull((FrmSrc.BCF_DT_FIRST_TRANS)) THEN (FrmSrc.BCF_DT_FIRST_TRANS) ELSE "")[3, 4]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_DT_FIRST_TRANS)) THEN (FrmSrc.BCF_DT_FIRST_TRANS) ELSE "")[7, 2]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_DT_FIRST_TRANS)) THEN (FrmSrc.BCF_DT_FIRST_TRANS) ELSE "")[9, 2]),
		CONCAT(CONCAT(CONCAT(CONCAT(TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_FIRST_TRANS IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_FIRST_TRANS, '')), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_FIRST_TRANS IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_FIRST_TRANS, ''))), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_FIRST_TRANS IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_FIRST_TRANS, ''))) AS svTransformBcfDtFirstTrans,
		-- *SRC*: \(20)If IsValid('date', svTransformBcfDtFirstTrans) Then 'Y' else  if Trim(FrmSrc.BCF_DT_FIRST_TRANS) = '000000000.' then 'Y' Else 'N',
		IFF(ISVALID('date', svTransformBcfDtFirstTrans), 'Y', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_FIRST_TRANS) = '000000000.', 'Y', 'N')) AS svIsValidBcfDtFirstTrans,
		-- *SRC*: \(20)If IsNull(FrmSrc.BCF_DT_PAYMENT_DEFER) then 'N' else  if Trim(FrmSrc.BCF_DT_PAYMENT_DEFER) = '' then 'N' else  if Trim(FrmSrc.BCF_DT_PAYMENT_DEFER) = '000000000.' then 'N' Else 'Y',
		IFF({{ ref('BCFINSG') }}.BCF_DT_PAYMENT_DEFER IS NULL, 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_PAYMENT_DEFER) = '', 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_PAYMENT_DEFER) = '000000000.', 'N', 'Y'))) AS svIsNullBcfDtPaymentDefer,
		-- *SRC*: Trim(( IF IsNotNull((FrmSrc.BCF_DT_PAYMENT_DEFER)) THEN (FrmSrc.BCF_DT_PAYMENT_DEFER) ELSE "")[3, 4]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_DT_PAYMENT_DEFER)) THEN (FrmSrc.BCF_DT_PAYMENT_DEFER) ELSE "")[7, 2]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_DT_PAYMENT_DEFER)) THEN (FrmSrc.BCF_DT_PAYMENT_DEFER) ELSE "")[9, 2]),
		CONCAT(CONCAT(CONCAT(CONCAT(TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_PAYMENT_DEFER IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_PAYMENT_DEFER, '')), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_PAYMENT_DEFER IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_PAYMENT_DEFER, ''))), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_PAYMENT_DEFER IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_PAYMENT_DEFER, ''))) AS svTransformBcfDtPaymentDefer,
		-- *SRC*: \(20)If IsValid('date', svTransformBcfDtPaymentDefer) Then 'Y' else  if Trim(FrmSrc.BCF_DT_PAYMENT_DEFER) = '000000000.' then 'Y' Else 'N',
		IFF(ISVALID('date', svTransformBcfDtPaymentDefer), 'Y', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_PAYMENT_DEFER) = '000000000.', 'Y', 'N')) AS svIsValidBcfDtPaymentDefer,
		-- *SRC*: \(20)If IsNull(FrmSrc.BCF_DT_INTEREST_DEFER) then 'N' else  if Trim(FrmSrc.BCF_DT_INTEREST_DEFER) = '' then 'N' else  if Trim(FrmSrc.BCF_DT_INTEREST_DEFER) = '000000000.' then 'N' Else 'Y',
		IFF({{ ref('BCFINSG') }}.BCF_DT_INTEREST_DEFER IS NULL, 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_INTEREST_DEFER) = '', 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_INTEREST_DEFER) = '000000000.', 'N', 'Y'))) AS svIsNullBcfDtInterestDefer,
		-- *SRC*: Trim(( IF IsNotNull((FrmSrc.BCF_DT_INTEREST_DEFER)) THEN (FrmSrc.BCF_DT_INTEREST_DEFER) ELSE "")[3, 4]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_DT_INTEREST_DEFER)) THEN (FrmSrc.BCF_DT_INTEREST_DEFER) ELSE "")[7, 2]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_DT_INTEREST_DEFER)) THEN (FrmSrc.BCF_DT_INTEREST_DEFER) ELSE "")[9, 2]),
		CONCAT(CONCAT(CONCAT(CONCAT(TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_INTEREST_DEFER IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_INTEREST_DEFER, '')), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_INTEREST_DEFER IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_INTEREST_DEFER, ''))), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_INTEREST_DEFER IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_INTEREST_DEFER, ''))) AS svTransformBcfDtInterestDefer,
		-- *SRC*: \(20)If IsValid('date', svTransformBcfDtInterestDefer) Then 'Y' else  if Trim(FrmSrc.BCF_DT_INTEREST_DEFER) = '000000000.' then 'Y' Else 'N',
		IFF(ISVALID('date', svTransformBcfDtInterestDefer), 'Y', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_INTEREST_DEFER) = '000000000.', 'Y', 'N')) AS svIsValidBcfDtInterestDefer,
		-- *SRC*: \(20)If IsNull(FrmSrc.BCF_DT_SPEC_TERMS_END) then 'N' else  if Trim(FrmSrc.BCF_DT_SPEC_TERMS_END) = '' then 'N' else  if Trim(FrmSrc.BCF_DT_SPEC_TERMS_END) = '000000000.' then 'N' Else 'Y',
		IFF({{ ref('BCFINSG') }}.BCF_DT_SPEC_TERMS_END IS NULL, 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_SPEC_TERMS_END) = '', 'N', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_SPEC_TERMS_END) = '000000000.', 'N', 'Y'))) AS svIsNullBcfDtSpecTermsEnd,
		-- *SRC*: Trim(( IF IsNotNull((FrmSrc.BCF_DT_SPEC_TERMS_END)) THEN (FrmSrc.BCF_DT_SPEC_TERMS_END) ELSE "")[3, 4]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_DT_SPEC_TERMS_END)) THEN (FrmSrc.BCF_DT_SPEC_TERMS_END) ELSE "")[7, 2]) : '-' : Trim(( IF IsNotNull((FrmSrc.BCF_DT_SPEC_TERMS_END)) THEN (FrmSrc.BCF_DT_SPEC_TERMS_END) ELSE "")[9, 2]),
		CONCAT(CONCAT(CONCAT(CONCAT(TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_SPEC_TERMS_END IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_SPEC_TERMS_END, '')), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_SPEC_TERMS_END IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_SPEC_TERMS_END, ''))), '-'), TRIM(IFF({{ ref('BCFINSG') }}.BCF_DT_SPEC_TERMS_END IS NOT NULL, {{ ref('BCFINSG') }}.BCF_DT_SPEC_TERMS_END, ''))) AS svTransformBcfDtSpecTermsEnd,
		-- *SRC*: \(20)If IsValid('date', svTransformBcfDtSpecTermsEnd) Then 'Y' else  if Trim(FrmSrc.BCF_DT_SPEC_TERMS_END) = '000000000.' then 'Y' Else 'N',
		IFF(ISVALID('date', svTransformBcfDtSpecTermsEnd), 'Y', IFF(TRIM({{ ref('BCFINSG') }}.BCF_DT_SPEC_TERMS_END) = '000000000.', 'Y', 'N')) AS svIsValidBcfDtSpecTermsEnd,
		-- *SRC*: \(20)If IsNull(FrmSrc.BCF_CORP) then 'Y' else  if trim(FrmSrc.BCF_CORP) = '' then 'Y' else  if trim(FrmSrc.BCF_CORP) = 0 then 'Y' else  if IsNull(FrmSrc.BCF_ACCOUNT_NO1) then 'Y' else  if trim(FrmSrc.BCF_ACCOUNT_NO1) = '' then 'Y' else  if trim(FrmSrc.BCF_ACCOUNT_NO1) = 0 then 'Y' else  if IsNull(FrmSrc.BCF_PLAN_ID) then 'Y' else  if trim(FrmSrc.BCF_PLAN_ID) = '' then 'Y' else  if trim(FrmSrc.BCF_PLAN_ID) = 0 then 'Y' else 'N',
		IFF(
	    {{ ref('BCFINSG') }}.BCF_CORP IS NULL, 'Y',     
	    IFF(
	        TRIM({{ ref('BCFINSG') }}.BCF_CORP) = '', 'Y',         
	        IFF(
	            TRIM({{ ref('BCFINSG') }}.BCF_CORP) = 0, 'Y', 
	            IFF({{ ref('BCFINSG') }}.BCF_ACCOUNT_NO1 IS NULL, 'Y', IFF(TRIM({{ ref('BCFINSG') }}.BCF_ACCOUNT_NO1) = '', 'Y', IFF(TRIM({{ ref('BCFINSG') }}.BCF_ACCOUNT_NO1) = 0, 'Y', IFF({{ ref('BCFINSG') }}.BCF_PLAN_ID IS NULL, 'Y', IFF(TRIM({{ ref('BCFINSG') }}.BCF_PLAN_ID) = '', 'Y', IFF(TRIM({{ ref('BCFINSG') }}.BCF_PLAN_ID) = 0, 'Y', 'N'))))))
	        )
	    )
	) AS svIsValidRecord,
		-- *SRC*: \(20)if svRowI = 0 then @PARTITIONNUM + 1 else svRowI + @NUMPARTITIONS,
		IFF(svRowI = 0, @PARTITIONNUM + 1, svRowI + @NUMPARTITIONS) AS svRowI,
		-- *SRC*: Trim(FrmSrc.BCF_CORP) : FrmSrc.BCF_ACCOUNT_NO1 : Trim(FrmSrc.BCF_PLAN_ID),
		CONCAT(CONCAT(TRIM({{ ref('BCFINSG') }}.BCF_CORP), {{ ref('BCFINSG') }}.BCF_ACCOUNT_NO1), TRIM({{ ref('BCFINSG') }}.BCF_PLAN_ID)) AS SRCE_KEY_I,
		pODS_LOAD_USER AS CONV_M,
		'Invalid record due to date' AS CONV_MAP_RULE_M,
		'PLAN_BALN_SEGM_MSTR' AS TRSF_TABL_M,
		-- *SRC*: StringToDate(pRUN_STRM_PROS_D, "%yyyy%mm%dd"),
		STRINGTODATE(pRUN_STRM_PROS_D, '%yyyy%mm%dd') AS SRCE_EFFT_D,
		-- *SRC*: trim(FrmSrc.BCF_DATE_END_INTEREST_FREE),
		TRIM({{ ref('BCFINSG') }}.BCF_DATE_END_INTEREST_FREE) AS VALU_CHNG_BFOR_X,
		'1111-11-11' AS VALU_CHNG_AFTR_X,
		DSJobName AS TRSF_X,
		'BCF_DATE_END_INTEREST_FREE' AS TRSF_COLM_M,
		-- *SRC*: SetNull(),
		SETNULL() AS EROR_SEQN_I,
		'{{ ref('BCFINSG') }}' AS SRCE_FILE_M,
		pODS_PROS_ID AS PROS_KEY_EFFT_I,
		-- *SRC*: Trim(FrmSrc.BCF_CORP) : "CCSCC" : FrmSrc.BCF_ACCOUNT_NO1 : Trim(FrmSrc.BCF_PLAN_ID),
		CONCAT(CONCAT(CONCAT(TRIM({{ ref('BCFINSG') }}.BCF_CORP), 'CCSCC'), {{ ref('BCFINSG') }}.BCF_ACCOUNT_NO1), TRIM({{ ref('BCFINSG') }}.BCF_PLAN_ID)) AS TRSF_KEY_I
	FROM {{ ref('BCFINSG') }}
	WHERE svIsValidBcfDtEndInterestFree = 'N' AND svIsValidRecord = 'N'
)

SELECT * FROM XfmToTable__BcfDtEndIntrstFree