{{ config(materialized='view', tags=['LdREJT_CSE_COI_BUS_PROP_CLNT']) }}

WITH FunRejectsNulls AS (
	SELECT
		FA_PROPOSED_CLIENT_ID as FA_PROPOSED_CLIENT_ID,
		COIN_ENTITY_ID as COIN_ENTITY_ID,
		CLIENT_CORRELATION_ID as CLIENT_CORRELATION_ID,
		COIN_ENTITY_NAME as COIN_ENTITY_NAME,
		FA_ENTITY_CAT_ID as FA_ENTITY_CAT_ID,
		FA_UNDERTAKING_ID as FA_UNDERTAKING_ID,
		FA_PROPOSED_CLIENT_CAT_ID as FA_PROPOSED_CLIENT_CAT_ID,
		ETL_D as ETL_D,
		ORIG_ETL_D as ORIG_ETL_D,
		EROR_C as EROR_C
	FROM {{ ref('SrcIdNullsDS') }}
	UNION ALL
	SELECT
		FA_PROPOSED_CLIENT_ID,
		COIN_ENTITY_ID,
		CLIENT_CORRELATION_ID,
		COIN_ENTITY_NAME,
		FA_ENTITY_CAT_ID,
		FA_UNDERTAKING_ID,
		FA_PROPOSED_CLIENT_CAT_ID,
		ETL_D,
		ORIG_ETL_D,
		EROR_C
	FROM {{ ref('SrcFAPropClntRejectsDS') }}
)

SELECT * FROM FunRejectsNulls