{{ config(materialized='view', tags=['XfmPlIntRateAmtMarginFrmExt']) }}

WITH XfmBusinessRules__OutApptPdctFeatDS AS (
	SELECT
		-- *SRC*: \(20)If (InXfmBusinessRules.PL_INT_RATE_FOUND_FLAG = 'N' or (Len(Trim(( IF IsNotNull((InXfmBusinessRules.PL_INT_RATE_VARIANT_CAT_ID)) THEN (InXfmBusinessRules.PL_INT_RATE_VARIANT_CAT_ID) ELSE ""))) = 0) or (Len(Trim(( IF IsNotNull((InXfmBusinessRules.PL_INT_RATE_INT_RATE_FREQ_ID)) THEN (InXfmBusinessRules.PL_INT_RATE_INT_RATE_FREQ_ID) ELSE ""))) = 0)) then DEFAULT_NULL_VALUE else  if Len(Trim(( IF IsNotNull((InXfmBusinessRules.TARG_CHAR_C)) THEN (InXfmBusinessRules.TARG_CHAR_C) ELSE ""))) = 0 Then '999009' else InXfmBusinessRules.TARG_CHAR_C,
		IFF(    
	    {{ ref('ModNullHandling') }}.PL_INT_RATE_FOUND_FLAG = 'N'
	    or LEN(TRIM(IFF({{ ref('ModNullHandling') }}.PL_INT_RATE_VARIANT_CAT_ID IS NOT NULL, {{ ref('ModNullHandling') }}.PL_INT_RATE_VARIANT_CAT_ID, ''))) = 0
	    or LEN(TRIM(IFF({{ ref('ModNullHandling') }}.PL_INT_RATE_INT_RATE_FREQ_ID IS NOT NULL, {{ ref('ModNullHandling') }}.PL_INT_RATE_INT_RATE_FREQ_ID, ''))) = 0, 
	    DEFAULT_NULL_VALUE, 
	    IFF(LEN(TRIM(IFF({{ ref('ModNullHandling') }}.TARG_CHAR_C IS NOT NULL, {{ ref('ModNullHandling') }}.TARG_CHAR_C, ''))) = 0, '999009', {{ ref('ModNullHandling') }}.TARG_CHAR_C)
	) AS FeatI,
		-- *SRC*: \(20)If (InXfmBusinessRules.PL_MARGIN_FOUND_FLAG = 'N' or (Len(Trim(( IF IsNotNull((InXfmBusinessRules.PL_MARGIN_MARGIN_RESN_CAT_ID)) THEN (InXfmBusinessRules.PL_MARGIN_MARGIN_RESN_CAT_ID) ELSE ""))) = 0)) then DEFAULT_NULL_VALUE else InXfmBusinessRules.FEAT_OVRD_REAS_C,
		IFF({{ ref('ModNullHandling') }}.PL_MARGIN_FOUND_FLAG = 'N' OR LEN(TRIM(IFF({{ ref('ModNullHandling') }}.PL_MARGIN_MARGIN_RESN_CAT_ID IS NOT NULL, {{ ref('ModNullHandling') }}.PL_MARGIN_MARGIN_RESN_CAT_ID, ''))) = 0, DEFAULT_NULL_VALUE, {{ ref('ModNullHandling') }}.FEAT_OVRD_REAS_C) AS FeatOvrdReasC,
		-- *SRC*: \(20)If FeatI = '999009' then 'RPR5114' Else  If FeatOvrdReasC = '9999' then 'RPR5115' Else '',
		IFF(FeatI = '999009', 'RPR5114', IFF(FeatOvrdReasC = '9999', 'RPR5115', '')) AS ErrorCode,
		-- *SRC*: \(20)If ErrorCode <> "" Then @TRUE Else @FALSE,
		IFF(ErrorCode <> '', @TRUE, @FALSE) AS RejectFlag,
		-- *SRC*: 'CSEPL' : ( IF IsNotNull((InXfmBusinessRules.PL_INT_RATE_PL_APP_PROD_ID)) THEN (InXfmBusinessRules.PL_INT_RATE_PL_APP_PROD_ID) ELSE ""),
		CONCAT('CSEPL', IFF({{ ref('ModNullHandling') }}.PL_INT_RATE_PL_APP_PROD_ID IS NOT NULL, {{ ref('ModNullHandling') }}.PL_INT_RATE_PL_APP_PROD_ID, '')) AS APPT_PDCT_I,
		-- *SRC*: \(20)IF FeatI = DEFAULT_NULL_VALUE THEN '999009' ELSE FeatI,
		IFF(FeatI = DEFAULT_NULL_VALUE, '999009', FeatI) AS FEAT_I,
		-- *SRC*: 'PR' : ( IF IsNotNull((InXfmBusinessRules.PL_INT_RATE_ID)) THEN (InXfmBusinessRules.PL_INT_RATE_ID) ELSE ""),
		CONCAT('PR', IFF({{ ref('ModNullHandling') }}.PL_INT_RATE_ID IS NOT NULL, {{ ref('ModNullHandling') }}.PL_INT_RATE_ID, '')) AS SRCE_SYST_APPT_FEAT_I,
		-- *SRC*: StringToDate(ETL_PROCESS_DT, "%yyyy%mm%dd"),
		STRINGTODATE(ETL_PROCESS_DT, '%yyyy%mm%dd') AS EFFT_D,
		'CSE' AS SRCE_SYST_C,
		-- *SRC*: SetNull(),
		SETNULL() AS SRCE_SYST_APPT_OVRD_I,
		-- *SRC*: SetNull(),
		SETNULL() AS OVRD_FEAT_I,
		-- *SRC*: SetNull(),
		SETNULL() AS SRCE_SYST_STND_VALU_Q,
		-- *SRC*: \(20)If len(Trim(( IF IsNotNull((InXfmBusinessRules.PL_INT_RATE_AMT_INT_RATE_AMT_1)) THEN (InXfmBusinessRules.PL_INT_RATE_AMT_INT_RATE_AMT_1) ELSE ""))) > 0 Then StringToDecimal(InXfmBusinessRules.PL_INT_RATE_AMT_INT_RATE_AMT_1) Else SetNull(),
		IFF(LEN(TRIM(IFF({{ ref('ModNullHandling') }}.PL_INT_RATE_AMT_INT_RATE_AMT_1 IS NOT NULL, {{ ref('ModNullHandling') }}.PL_INT_RATE_AMT_INT_RATE_AMT_1, ''))) > 0, STRINGTODECIMAL({{ ref('ModNullHandling') }}.PL_INT_RATE_AMT_INT_RATE_AMT_1), SETNULL()) AS SRCE_SYST_STND_VALU_R,
		-- *SRC*: SetNull(),
		SETNULL() AS SRCE_SYST_STND_VALU_A,
		'AUD' AS CNCY_C,
		-- *SRC*: StringToDecimal(InXfmBusinessRules.PL_INT_RATE_INT_RATE_TERM),
		STRINGTODECIMAL({{ ref('ModNullHandling') }}.PL_INT_RATE_INT_RATE_TERM) AS ACTL_VALU_Q,
		-- *SRC*: \(20)If len(Trim(( IF IsNotNull((InXfmBusinessRules.PL_INT_RATE_AMT_INT_RTE_AMT_2)) THEN (InXfmBusinessRules.PL_INT_RATE_AMT_INT_RTE_AMT_2) ELSE ""))) > 0 Then StringToDecimal(InXfmBusinessRules.PL_INT_RATE_AMT_INT_RTE_AMT_2) Else StringToDecimal(InXfmBusinessRules.PL_INT_RATE_AMT_INT_RATE_AMT_1),
		IFF(LEN(TRIM(IFF({{ ref('ModNullHandling') }}.PL_INT_RATE_AMT_INT_RTE_AMT_2 IS NOT NULL, {{ ref('ModNullHandling') }}.PL_INT_RATE_AMT_INT_RTE_AMT_2, ''))) > 0, STRINGTODECIMAL({{ ref('ModNullHandling') }}.PL_INT_RATE_AMT_INT_RTE_AMT_2), STRINGTODECIMAL({{ ref('ModNullHandling') }}.PL_INT_RATE_AMT_INT_RATE_AMT_1)) AS ACTL_VALU_R,
		-- *SRC*: SetNull(),
		SETNULL() AS ACTL_VALU_A,
		{{ ref('ModNullHandling') }}.PL_INT_RATE_DOC_SEQ_NO AS FEAT_SEQN_N,
		-- *SRC*: SetNull(),
		SETNULL() AS FEAT_STRT_D,
		-- *SRC*: SetNull(),
		SETNULL() AS FEE_CHRG_D,
		-- *SRC*: \(20)If (Len(Trim(( IF IsNotNull((InXfmBusinessRules.PL_MARGIN_MARGIN_RESN_CAT_ID)) THEN (InXfmBusinessRules.PL_MARGIN_MARGIN_RESN_CAT_ID) ELSE ""))) = 0) Then SetNull() Else  If FeatOvrdReasC = DEFAULT_NULL_VALUE Then '9999' Else FeatOvrdReasC,
		IFF(LEN(TRIM(IFF({{ ref('ModNullHandling') }}.PL_MARGIN_MARGIN_RESN_CAT_ID IS NOT NULL, {{ ref('ModNullHandling') }}.PL_MARGIN_MARGIN_RESN_CAT_ID, ''))) = 0, SETNULL(), IFF(FeatOvrdReasC = DEFAULT_NULL_VALUE, '9999', FeatOvrdReasC)) AS OVRD_REAS_C,
		'N' AS FEE_ADD_TO_TOTL_F,
		'N' AS FEE_CAPL_F,
		-- *SRC*: StringToDate('9999-12-31', "%yyyy-%mm-%dd"),
		STRINGTODATE('9999-12-31', '%yyyy-%mm-%dd') AS EXPY_D,
		0 AS PROS_KEY_EFFT_I,
		-- *SRC*: SetNull(),
		SETNULL() AS PROS_KEY_EXPY_I,
		-- *SRC*: SetNull(),
		SETNULL() AS EROR_SEQN_I,
		RUN_STREAM AS RUN_STRM,
		PL_INT_RATE_ID,
		PL_INT_RATE_PL_INT_RATE_ID,
		PL_INT_RATE_DOC_SEQ_NO,
		PL_INT_RATE_CASS_MARGIN_AMT,
		PL_INT_RATE_INT_RATE_TERM,
		PL_INT_RATE_INT_RATE_FREQ_ID,
		PL_INT_RATE_VARIANT_CAT_ID,
		PL_INT_RATE_USAGE_CAT_ID,
		PL_INT_RATE_PL_APP_PROD_ID,
		PL_MARGIN_PL_MARGIN_ID,
		PL_MARGIN_MARGIN_AMT,
		PL_MARGIN_PL_FEE_ID,
		PL_MARGIN_PL_INT_RATE_ID,
		PL_MARGIN_MARGIN_RESN_CAT_ID,
		PL_MARGIN_PL_APP_PROD_ID,
		PL_INT_RATE_AMT_INT_RTE_AMT_2,
		PL_INT_RATE_AMT_INT_RTCT_ID2,
		PL_INT_RATE_AMT_PL_INT_RATE_ID,
		PL_INT_RATE_AMT_INT_RATE_AMT_1,
		PL_INT_RATE_AMT_INT_RTCT_ID1,
		PL_MARGIN_FOUND_FLAG,
		PL_INT_RATE_FOUND_FLAG,
		PL_INT_RATE_AMT_FOUND_FLAG,
		-- *SRC*: StringToDate(InXfmBusinessRules.ORIG_ETL_D, "%yyyy%mm%dd"),
		STRINGTODATE({{ ref('ModNullHandling') }}.ORIG_ETL_D, '%yyyy%mm%dd') AS ORIG_ETL_D
	FROM {{ ref('ModNullHandling') }}
	WHERE 
)

SELECT * FROM XfmBusinessRules__OutApptPdctFeatDS