CREATE OR REPLACE PROCEDURE PS_GDW1_BTEQ.BTEQ_SPS.DERV_ACCT_PATY_07_CRAT_DELTAS_PROC(
  EXTR_D STRING DEFAULT '2023-01-01'
)
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
  error_code INTEGER DEFAULT 0;
  row_count INTEGER DEFAULT 0;
  total_rows INTEGER DEFAULT 0;
BEGIN
  -- 1. Insert rows into PDDSTG.DERV_ACCT_PATY_ADD that exist now but didn't exist before
  DELETE FROM PS_CLD_RW.PDDSTG.DERV_ACCT_PATY_ADD;
  
  INSERT INTO PS_CLD_RW.PDDSTG.DERV_ACCT_PATY_ADD
  SELECT T1.ACCT_I,
         T1.PATY_I,
         T1.ASSC_ACCT_I,
         T1.PATY_ACCT_REL_C,
         T1.PRFR_PATY_F,
         T1.SRCE_SYST_C,
         T1.EFFT_D,
         T1.EXPY_D,
         T1.ROW_SECU_ACCS_C
  FROM PS_CLD_RW.PDDSTG.DERV_ACCT_PATY_FLAG T1
  LEFT JOIN PS_GDW1_BTEQ.PVTECH.DERV_ACCT_PATY T2
    ON T1.ACCT_I = T2.ACCT_I
   AND T1.PATY_I = T2.PATY_I
   AND T1.PATY_ACCT_REL_C = T2.PATY_ACCT_REL_C
   AND :EXTR_D BETWEEN T2.EFFT_D AND T2.EXPY_D
  WHERE :EXTR_D BETWEEN T1.EFFT_D AND T1.EXPY_D 
    AND T2.ACCT_I IS NULL
  GROUP BY 1,2,3,4,5,6,7,8,9;
  
  row_count := SQLROWCOUNT;
  total_rows := total_rows + row_count;
  
  -- 2. Insert rows into PDDSTG.DERV_ACCT_PATY_CHG that changed
  DELETE FROM PS_CLD_RW.PDDSTG.DERV_ACCT_PATY_CHG;
  
  INSERT INTO PS_CLD_RW.PDDSTG.DERV_ACCT_PATY_CHG
  SELECT T1.ACCT_I,
         T1.PATY_I,
         T1.ASSC_ACCT_I,
         T1.PATY_ACCT_REL_C,
         T1.PRFR_PATY_F,
         T1.SRCE_SYST_C,
         T1.EFFT_D,
         T1.EXPY_D,
         T1.ROW_SECU_ACCS_C
  FROM PS_CLD_RW.PDDSTG.DERV_ACCT_PATY_FLAG T1
  JOIN PS_GDW1_BTEQ.PVTECH.DERV_ACCT_PATY T2
    ON T1.ACCT_I = T2.ACCT_I
   AND T1.PATY_I = T2.PATY_I
   AND T1.PATY_ACCT_REL_C = T2.PATY_ACCT_REL_C
  WHERE (T1.ASSC_ACCT_I <> T2.ASSC_ACCT_I
      OR T1.PRFR_PATY_F <> T2.PRFR_PATY_F
      OR T1.SRCE_SYST_C <> T2.SRCE_SYST_C)
    AND :EXTR_D BETWEEN T1.EFFT_D AND T1.EXPY_D
    AND :EXTR_D BETWEEN T2.EFFT_D AND T2.EXPY_D
  GROUP BY 1,2,3,4,5,6,7,8,9;
  
  row_count := SQLROWCOUNT;
  total_rows := total_rows + row_count;
  
  -- 3. Insert rows into PDDSTG.DERV_ACCT_PATY_DEL that were effective before but not in the current table anymore
  DELETE FROM PS_CLD_RW.PDDSTG.DERV_ACCT_PATY_DEL;
  
  INSERT INTO PS_CLD_RW.PDDSTG.DERV_ACCT_PATY_DEL
  SELECT T1.ACCT_I,
         T1.PATY_I,
         T1.ASSC_ACCT_I,
         T1.PATY_ACCT_REL_C,
         T1.PRFR_PATY_F,
         T1.SRCE_SYST_C,
         T1.EFFT_D,
         T1.EXPY_D,
         T1.ROW_SECU_ACCS_C
  FROM PS_GDW1_BTEQ.PVTECH.DERV_ACCT_PATY T1
  LEFT JOIN PS_CLD_RW.PDDSTG.DERV_ACCT_PATY_FLAG T2
    ON T1.ACCT_I = T2.ACCT_I
   AND T1.PATY_I = T2.PATY_I
   AND T1.PATY_ACCT_REL_C = T2.PATY_ACCT_REL_C
   AND :EXTR_D BETWEEN T2.EFFT_D AND T2.EXPY_D
  WHERE :EXTR_D BETWEEN T1.EFFT_D AND T1.EXPY_D 
    AND T2.ACCT_I IS NULL 
  GROUP BY 1,2,3,4,5,6,7,8,9;
  
  row_count := SQLROWCOUNT;
  total_rows := total_rows + row_count;
  
  RETURN 'SUCCESS: Delta processing completed. Total rows processed: ' || :total_rows;
  
EXCEPTION
  WHEN OTHER THEN
    RETURN 'ERROR: ' || SQLERRM || ' (Code: ' || SQLCODE || ')';
END;
$$;