{{ config(materialized='view', tags=['DltASETFrmTMP_ASET1']) }}

WITH 
aset AS (
	SELECT
	*
	FROM {{ ref("aset")  }}),
cse4_tmp_aset AS (
	SELECT
	*
	FROM {{ ref("cse4_tmp_aset")  }}),
SrcTmpASETTera AS (SELECT a.ASET_I AS NEW_ASET_I, a.SECU_CODE_C AS NEW_SECU_CODE_C, a.SECU_CATG_C, a.SRCE_SYST_ASET_I, a.SRCE_SYST_C AS NEW_SRCE_SYST_C, a.ASET_C, a.ORIG_SRCE_SYST_ASET_I, a.ORIG_SRCE_SYST_C, a.ENVT_F, a.ASET_X, a.EFFT_D, a.EXPY_D, a.EROR_SEQN_I, a.ASET_LIBL_C, a.AL_CATG_C, a.DUPL_ASET_F, b.ASET_I AS OLD_ASET_I, b.SRCE_SYST_C AS OLD_SRCE_SYST_C, b.EFFT_D AS OLD_EFFT_D FROM CSE4_TMP_ASET LEFT OUTER JOIN ASET ON TRIM(a.ASET_I) = TRIM(b.ASET_I) AND b.EXPY_D = '9999-12-31' AND b.SRCE_SYST_C = 'CSE' WHERE a.RUN_STRM = '{{ var("RUN_STREAM") }}')


SELECT * FROM SrcTmpASETTera