{{ config(materialized='view', tags=['MergePlIntRatePlMargin']) }}

WITH Identify_PL_INT_RATE_ID AS (
	SELECT
		-- *SRC*: \(20)If len(Trim(( IF IsNotNull((OutJoinAll.PL_INT_RATE_AMT_PL_INT_RATE_ID)) THEN (OutJoinAll.PL_INT_RATE_AMT_PL_INT_RATE_ID) ELSE ""))) > 0 Then OutJoinAll.PL_INT_RATE_AMT_PL_INT_RATE_ID Else  If len(Trim(( IF IsNotNull((OutJoinAll.PL_MARGIN_PL_INT_RATE_ID)) THEN (OutJoinAll.PL_MARGIN_PL_INT_RATE_ID) ELSE ""))) > 0 Then OutJoinAll.PL_MARGIN_PL_INT_RATE_ID Else OutJoinAll.PL_INT_RATE_PL_INT_RATE_ID,
		IFF(
	    LEN(TRIM(IFF({{ ref('JoinAll') }}.PL_INT_RATE_AMT_PL_INT_RATE_ID IS NOT NULL, {{ ref('JoinAll') }}.PL_INT_RATE_AMT_PL_INT_RATE_ID, ''))) > 0, {{ ref('JoinAll') }}.PL_INT_RATE_AMT_PL_INT_RATE_ID, 
	    IFF(LEN(TRIM(IFF({{ ref('JoinAll') }}.PL_MARGIN_PL_INT_RATE_ID IS NOT NULL, {{ ref('JoinAll') }}.PL_MARGIN_PL_INT_RATE_ID, ''))) > 0, {{ ref('JoinAll') }}.PL_MARGIN_PL_INT_RATE_ID, {{ ref('JoinAll') }}.PL_INT_RATE_PL_INT_RATE_ID)
	) AS PL_INT_RATE_ID,
		PL_INT_RATE_PL_INT_RATE_ID,
		PL_INT_RATE_DOC_SEQ_NO,
		PL_INT_RATE_CASS_MARGIN_AMT,
		PL_INT_RATE_INT_RATE_TERM,
		PL_INT_RATE_INT_RATE_FREQUENCY_ID,
		PL_INT_RATE_VARIANT_CAT_ID,
		PL_INT_RATE_USAGE_CAT_ID,
		PL_INT_RATE_PL_APP_PROD_ID,
		PL_MARGIN_PL_MARGIN_ID,
		PL_MARGIN_MARGIN_AMT,
		PL_MARGIN_PL_FEE_ID,
		PL_MARGIN_PL_INT_RATE_ID,
		PL_MARGIN_MARGIN_REASON_CAT_ID,
		PL_MARGIN_PL_APP_PROD_ID,
		PL_INT_RATE_AMT_INT_RATE_AMT_2,
		PL_INT_RATE_AMT_PL_INT_RATE_CAT_ID_2,
		PL_INT_RATE_AMT_PL_INT_RATE_ID,
		PL_INT_RATE_AMT_INT_RATE_AMT_1,
		PL_INT_RATE_AMT_PL_INT_RATE_CAT_ID_1,
		-- *SRC*: ( IF IsNotNull((OutJoinAll.PL_MARGIN_FOUND_FLAG)) THEN (OutJoinAll.PL_MARGIN_FOUND_FLAG) ELSE ('N')),
		IFF({{ ref('JoinAll') }}.PL_MARGIN_FOUND_FLAG IS NOT NULL, {{ ref('JoinAll') }}.PL_MARGIN_FOUND_FLAG, 'N') AS PL_MARGIN_FOUND_FLAG,
		-- *SRC*: ( IF IsNotNull((OutJoinAll.PL_INT_RATE_FOUND_FLAG)) THEN (OutJoinAll.PL_INT_RATE_FOUND_FLAG) ELSE ('N')),
		IFF({{ ref('JoinAll') }}.PL_INT_RATE_FOUND_FLAG IS NOT NULL, {{ ref('JoinAll') }}.PL_INT_RATE_FOUND_FLAG, 'N') AS PL_INT_RATE_FOUND_FLAG,
		-- *SRC*: \(20)IF (Trim(( IF IsNotNull((OutJoinAll.PL_INT_RATE_AMT_FOUND_FLAG)) THEN (OutJoinAll.PL_INT_RATE_AMT_FOUND_FLAG) ELSE ""))) <= 0 THEN 'N' ELSE OutJoinAll.PL_INT_RATE_AMT_FOUND_FLAG,
		IFF(TRIM(IFF({{ ref('JoinAll') }}.PL_INT_RATE_AMT_FOUND_FLAG IS NOT NULL, {{ ref('JoinAll') }}.PL_INT_RATE_AMT_FOUND_FLAG, '')) <= 0, 'N', {{ ref('JoinAll') }}.PL_INT_RATE_AMT_FOUND_FLAG) AS PL_INT_RATE_AMT_FOUND_FLAG
	FROM {{ ref('JoinAll') }}
	WHERE 
)

SELECT * FROM Identify_PL_INT_RATE_ID