{{ config(materialized='view', tags=['XfmCC_APP_PRODFrmExt']) }}

WITH CpyRename AS (
	SELECT
		CC_APP_PROD_ID,
		REQUESTED_LIMIT_AMT,
		CC_INTEREST_OPT_CAT_ID,
		CBA_HOMELOAN_NO,
		PRE_APPRV_AMOUNT,
		ORIG_ETL_D,
		READ_COSTS_AND_RISKS_FLAG,
		ACCEPTS_COSTS_AND_RISKS_DATE
	FROM {{ ref('SrcCCAppProdPremapDS') }}
)

SELECT * FROM CpyRename