{{ config(materialized='view', tags=['ExtFaUndertaking']) }}

WITH FunMergeSourceAndRejt AS (
	SELECT
		FA_UNDERTAKING_ID as FA_UNDERTAKING_ID,
		PLANNING_GROUP_NAME as PLANNING_GROUP_NAME,
		COIN_ADVICE_GROUP_ID as COIN_ADVICE_GROUP_ID,
		ADVICE_GROUP_CORRELATION_ID as ADVICE_GROUP_CORRELATION_ID,
		CREATED_DATE as CREATED_DATE,
		CREATED_BY_STAFF_NUMBER as CREATED_BY_STAFF_NUMBER,
		SM_CASE_ID as SM_CASE_ID,
		ORIG_ETL_D as ORIG_ETL_D
	FROM {{ ref('XfmSeparateRejectWithoutSourceAndTheRest__InSourceRec') }}
	UNION ALL
	SELECT
		FA_UNDERTAKING_ID,
		PLANNING_GROUP_NAME,
		COIN_ADVICE_GROUP_ID,
		ADVICE_GROUP_CORRELATION_ID,
		CREATED_DATE,
		CREATED_BY_STAFF_NUMBER,
		SM_CASE_ID,
		ORIG_ETL_D
	FROM {{ ref('XfmSeparateRejectWithoutSourceAndTheRest__InRejectWithoutSourceRec') }}
)

SELECT * FROM FunMergeSourceAndRejt