-- FRAUMD Warehouse Analysis Queries
-- Filtered for specific FRAUMD warehouses
call pst.svcs.sp_set_account_context (50973,'AU');
USE DATABASE PST;
USE SCHEMA PST.SVCS;



WITH CTE_RAW
AS
(
SELECT 
  USAGE_DATE,
  TO_NUMBER(COMPUTE_CREDITS) AS WAREHOUSE_COMPUTE,
  TO_NUMBER(BILLABLE_CLOUD_SERVICES_CREDITS) AS CLOUD_SERVICES,
  TO_NUMBER(SNOWPIPE_CREDITS) AS SNOWPIPE,
  TO_NUMBER(RECLUSTERING_CREDITS) AS RECLUSTERING,
  TO_NUMBER(REPLICATION_CREDITS) AS REPLICATION,
  TO_NUMBER(READER_COMPUTE_CREDITS) AS READER_COMPUTE,
  TO_NUMBER(BILLABLE_CLOUD_SERVICES_READER_CREDITS) AS CLOUD_SERVICES_READER,
  TO_NUMBER(MATERIALIZED_VIEW_CREDITS) AS MATERIALIZED_VIEW,
  TO_NUMBER(SEARCH_OPTIMIZATION_CREDITS) AS SEARCH_OPTIMIZATION,
  TO_NUMBER(SERVERLESS_TASK_CREDITS) AS SERVERLESS_TASK,
  TO_NUMBER(query_acceleration_credits) AS QUERY_ACCELERATION

FROM FINANCE.CUSTOMER.USAGE_DAILY
WHERE warehouse_name IN ('WH_USR_PRD_P01_FRAUMD_001', 'WH_USR_PRD_P01_FRAUMD_LABMLFRD_001', 'WH_USR_PRD_P01_FRAUMD_LABMLFRD_002', 'WH_USR_PRD_P01_FRAUMD_LABMLFRD_003') AND USAGE_DATE >= dateadd(days, -30, current_date())
AND snowflake_account_id = @ACCOUNT_ID@
and snowflake_deployment = '@ACCOUNT_DEPLOYMENT@'
),
CTE_MATURE
AS
(
SELECT * FROM CTE_RAW
UNPIVOT(CREDITS FOR SERVICE_TYPE IN (WAREHOUSE_COMPUTE,CLOUD_SERVICES,SNOWPIPE,RECLUSTERING,REPLICATION,READER_COMPUTE,CLOUD_SERVICES_READER,MATERIALIZED_VIEW,SEARCH_OPTIMIZATION,SERVERLESS_TASK))
)
SELECT 

SERVICE_TYPE,
SUM(CREDITS) CREDITS
FROM CTE_MATURE
GROUP BY ALL
ORDER BY CREDITS DESC
;