{{ config(materialized='view', tags=['LdMAP_CSE_ENV_EVNT_ACT_TYPELkp']) }}

WITH 
,
SrcMAP_CSE_ENV_EVNT_ACT_TYPE_Tera AS (SELECT 
MAP_CSE_ENV_EVNT_ACTV_TYPE.FA_ENV_EVNT_CAT_ID,
MAP_CSE_ENV_EVNT_ACTV_TYPE.EVNT_ACTV_TYPE_C 
FROM {{ var('GDW_ACCT_VW') }}.MAP_CSE_ENV_EVNT_ACTV_TYPE as MAP_CSE_ENV_EVNT_ACTV_TYPE
WHERE MAP_CSE_ENV_EVNT_ACTV_TYPE.efft_d (date, format 'yyyymmdd') <= '{{ var('ETL_PROCESS_DT') }}' and MAP_CSE_ENV_EVNT_ACTV_TYPE.expy_d (date, format 'yyyymmdd') >= '{{ var('ETL_PROCESS_DT') }}' )


SELECT * FROM SrcMAP_CSE_ENV_EVNT_ACT_TYPE_Tera