{{ config(materialized='view', tags=['XfmChlBusFeeDiscFeeFrmExt']) }}

WITH ModNullHandling AS (
	SELECT 
	--Manual
	--TARG_CHAR_C = handle_null (TARG_CHAR_C, '999010')
	--OVRD_REAS_C = handle_null(OVRD_REAS_C,'9999')
	HL_FEE_ID, BF_HL_FEE_ID, BF_HL_APP_PROD_ID, BF_XML_CODE AS SRCE_CHAR_1_C, BF_DISPLAY_NAME, BF_CATEGORY, BF_UNIT_AMOUNT, BF_TOTAL_AMOUNT, BF_FOUND_FLAG, BFD_HL_FEE_DISCOUNT_ID, BFD_HL_FEE_ID, BFD_DISCOUNT_REASON, SRCE_CHAR_1_C AS BFD_DISCOUNT_CODE, BFD_DISCOUNT_AMT, BFD_DISCOUNT_TERM, BFD_HL_FEE_DISCOUNT_CAT_ID, BFD_FOUND_FLAG, ORIG_ETL_D, MAP_TYPE_C, TARG_CHAR_C, OVRD_REAS_C 
	FROM {{ ref('LkpReferences') }}
)

SELECT * FROM ModNullHandling