

CREATE MULTISET VOLATILE TABLE VT_ALL_CUST_BASE AS
(
	SELECT A.* FROM
	(
		SELECT DISTINCT
			A.*,
			B.PATY_IDNN_HK,
			C.REL_MNGE_EMPL_BK AS RM_EMPL_I,
			PRTF.PRTF_IDNN_BK AS PRTF_I,
			PRTF.EFFT_D AS PRTF_STRT_D
		FROM
		(
			SELECT DISTINCT
				PATY_IDNN_BK,
				REGEXP_REPLACE(PATY_IDNN_BK, 'SAP~PT~\+', 'CIFPT+') as PATY_I,
				CASE WHEN CUST_TYPE_M = 'PERSON' THEN 'P'
					WHEN CUST_TYPE_M = 'ORGANISATION' THEN 'O'
					END AS PATY_TYP_X
			FROM P_V_USR_TEC_0.DIMN_CUST  -- ALL CUSTOMER DATA
			WHERE MSTR_SRCE_SYST_C='SAP'
			AND EFFT_D <= CURRENT_DATE
			QUALIFY ROW_NUMBER() OVER ( PARTITION BY PATY_IDNN_BK ORDER BY EFFT_D DESC) = 1  -- TAKE LATEST RECORD
		) A
		LEFT JOIN
		(
			SELECT DISTINCT
				PATY_IDNN_HK,
				PATY_I
			FROM P_V_USR_TEC_0.L_PATY_IM_PATY
			WHERE RECORD_DELETED_FLAG=0
			AND EXPY_D='9999-12-31'
		) B
		ON A.PATY_I = B.PATY_I

		-- Added this join to fix multiple RM owner per customer issue. This table has only one active record per customer to pick the correct portfolio
		LEFT JOIN
		(
			SELECT
			    PATY_IDNN_HK,
				PRTF_IDNN_BK,
				EFFT_D
			FROM P_V_USR_TEC_0.S_PATY_ATTR
			WHERE EXPY_D = '9999-12-31'
			AND PRTF_IDNN_BK <> 'UNKN'
		)PRTF
		ON B.PATY_IDNN_HK = PRTF.PATY_IDNN_HK

		LEFT JOIN
		(
			--This table might have multiple RM owners for same customer. Hence we are joining with the active portfolio record from S_PATY_ATTR
			SELECT DISTINCT
				PATY_I,
				PRTF_BK,
				REL_MNGE_EMPL_BK
			FROM B_V_USR_TEC_0.BV_BPB_PATY_SEGM
			WHERE REL_MNGE_CUST_EMPL_ROLE_C='OWN'
			AND REL_MNGE_EMPL_BK IS NOT NULL
		) C
		ON A.PATY_I = C.PATY_I
		AND PRTF.PRTF_IDNN_BK= C.PRTF_BK
	)A
	WHERE RM_EMPL_I IS NOT NULL
)
WITH DATA
PRIMARY INDEX (PATY_I)
ON COMMIT PRESERVE ROWS;

--Delete existing data from the final table
DELETE U_D_DSV_001_QPD_1.BV_B360_CRM_CUST_DIMN;

--Insert data to BV_B360_CRM_CUST_DIMN
INSERT INTO U_D_DSV_001_QPD_1.BV_B360_CRM_CUST_DIMN
SELECT
    CB.PATY_I						AS PATY_I,
    TRIM(LEADING '0' FROM SUBSTRING(CB.PATY_IDNN_BK FROM POSITION('+' IN CB.PATY_IDNN_BK) + 1))   AS CIF_I,
    CB.PATY_TYP_X                    AS PATY_TYP_X,
    CB.PRTF_I						 AS PRTF_I,
    CB.RM_EMPL_I                     AS EMPL_I,
    SSUC.LONG_NAME                   AS LAN_I,
	PGD.PATY_GRUP_I                  AS SALE_GRUP_I,
    CB.PRTF_STRT_D 					 AS PRTF_STRT_D

FROM VT_ALL_CUST_BASE CB
/* PATY_GRUP DETAILS */
LEFT JOIN P_V_USR_TEC_0.S_PATY_GRUP_DETL PGD
    ON CB.PATY_IDNN_HK = PGD.PATY_IDNN_HK
	AND PGD.BUSN_END_D = '9999-12-31'
	AND PGD.EXPY_D = '9999-12-31'

/* LAN ID */
 LEFT JOIN P_V_USR_TEC_0.R_CSE_OU_TEAM_STRC SSUC
    ON CB.RM_EMPL_I = SSUC.CBA_STAFF_NUMBER
    AND SSUC.LONG_NAME NOT LIKE '%\_%' ESCAPE '\'
	AND SSUC.EXPY_D='9999-12-31'
    WHERE CB.RM_EMPL_I IS NOT NULL
	;

