{{ config(materialized='view', tags=['DltAPPT_PDCT_CPGNFrmTMP_APPT_PDCT_CPGN']) }}

WITH 
tmp_appt_pdct_cpgn AS (
	SELECT
	*
	FROM {{ ref("tmp_appt_pdct_cpgn")  }}),
appt_pdct_cpgn AS (
	SELECT
	*
	FROM {{ ref("appt_pdct_cpgn")  }}),
SrcTmpApptPdctCpgnTera AS (SELECT A.APPT_PDCT_I, A.CPGN_TYPE_C, A.CPGN_I, A.REL_C, A.SRCE_SYST_C, CASE WHEN (B.APPT_PDCT_I IS NULL AND B.CPGN_TYPE_C IS NULL AND B.SRCE_SYST_C IS NULL) THEN A.EFFT_D ELSE B.EFFT_D END AS EFFT_D, A.EXPY_D, CASE WHEN (B.APPT_PDCT_I IS NULL AND B.CPGN_TYPE_C IS NULL AND B.SRCE_SYST_C IS NULL) THEN 'I' WHEN (COALESCE(TRIM(A.CPGN_I), 'D') = COALESCE(TRIM(B.CPGN_I), 'D')) THEN 'C' ELSE 'U' END AS IND_FLAG FROM TMP_APPT_PDCT_CPGN LEFT OUTER JOIN (SELECT APPT_PDCT_I, CPGN_TYPE_C, CPGN_I, REL_C, SRCE_SYST_C, EFFT_D, EXPY_D FROM APPT_PDCT_CPGN WHERE EXPY_D = '9999-12-31') AS B ON A.APPT_PDCT_I = B.APPT_PDCT_I AND A.CPGN_TYPE_C = B.CPGN_TYPE_C AND A.SRCE_SYST_C = B.SRCE_SYST_C WHERE A.RUN_STRM = '{{ var("RUN_STREAM") }}' AND IND_FLAG <> 'C')


SELECT * FROM SrcTmpApptPdctCpgnTera