{{ config(materialized='view', tags=['DltAPPT_PDCT_FNDD_INSSFrmTMP_APPT_PDCT_FNDD_INSS']) }}

WITH ChangeCapture AS (
	SELECT
		COALESCE({{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_APPT_PDCT_I, {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_APPT_PDCT_I) AS NEW_APPT_PDCT_I,
		COALESCE({{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_APPT_PDCT_FNDD_I, {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_APPT_PDCT_FNDD_I) AS NEW_APPT_PDCT_FNDD_I,
		COALESCE({{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_APPT_PDCT_FNDD_METH_I, {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_APPT_PDCT_FNDD_METH_I) AS NEW_APPT_PDCT_FNDD_METH_I,
		COALESCE({{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_FNDD_INSS_METH_C, {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_FNDD_INSS_METH_C) AS NEW_FNDD_INSS_METH_C,
		COALESCE({{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_SRCE_SYST_FNDD_I, {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_SRCE_SYST_FNDD_I) AS NEW_SRCE_SYST_FNDD_I,
		COALESCE({{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_SRCE_SYST_FNDD_METH_I, {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_SRCE_SYST_FNDD_METH_I) AS NEW_SRCE_SYST_FNDD_METH_I,
		COALESCE({{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_SRCE_SYST_C, {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_SRCE_SYST_C) AS NEW_SRCE_SYST_C,
		COALESCE({{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_FNDD_D, {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_FNDD_D) AS NEW_FNDD_D,
		COALESCE({{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_FNDD_A, {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_FNDD_A) AS NEW_FNDD_A,
		COALESCE({{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_PDCT_SYST_ACCT_N, {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_PDCT_SYST_ACCT_N) AS NEW_PDCT_SYST_ACCT_N,
		COALESCE({{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_CMPE_I, {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_CMPE_I) AS NEW_CMPE_I,
		COALESCE({{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_CMPE_ACCT_BSB_N, {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_CMPE_ACCT_BSB_N) AS NEW_CMPE_ACCT_BSB_N,
		COALESCE({{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_CMPE_ACCT_N, {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_CMPE_ACCT_N) AS NEW_CMPE_ACCT_N,
		CASE
			WHEN {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_APPT_PDCT_I IS NULL AND {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_APPT_PDCT_FNDD_I IS NULL AND {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_APPT_PDCT_FNDD_METH_I IS NULL THEN '1'
			WHEN {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_APPT_PDCT_I IS NULL AND {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_APPT_PDCT_FNDD_I IS NULL AND {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_APPT_PDCT_FNDD_METH_I IS NULL THEN '2'
			WHEN ({{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_APPT_PDCT_I = {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_APPT_PDCT_I AND {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_APPT_PDCT_FNDD_I = {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_APPT_PDCT_FNDD_I AND {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_APPT_PDCT_FNDD_METH_I = {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_APPT_PDCT_FNDD_METH_I) AND ({{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_FNDD_INSS_METH_C <> {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_FNDD_INSS_METH_C OR {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_SRCE_SYST_FNDD_I <> {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_SRCE_SYST_FNDD_I OR {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_SRCE_SYST_FNDD_METH_I <> {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_SRCE_SYST_FNDD_METH_I OR {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_SRCE_SYST_C <> {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_SRCE_SYST_C OR {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_FNDD_D <> {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_FNDD_D OR {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_FNDD_A <> {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_FNDD_A OR {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_PDCT_SYST_ACCT_N <> {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_PDCT_SYST_ACCT_N OR {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_CMPE_I <> {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_CMPE_I OR {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_CMPE_ACCT_BSB_N <> {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_CMPE_ACCT_BSB_N OR {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_CMPE_ACCT_N <> {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_CMPE_ACCT_N) THEN '3'
			WHEN {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_APPT_PDCT_I = {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_APPT_PDCT_I AND {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_APPT_PDCT_FNDD_I = {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_APPT_PDCT_FNDD_I AND {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_APPT_PDCT_FNDD_METH_I = {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_APPT_PDCT_FNDD_METH_I AND {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_FNDD_INSS_METH_C = {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_FNDD_INSS_METH_C AND {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_SRCE_SYST_FNDD_I = {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_SRCE_SYST_FNDD_I AND {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_SRCE_SYST_FNDD_METH_I = {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_SRCE_SYST_FNDD_METH_I AND {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_SRCE_SYST_C = {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_SRCE_SYST_C AND {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_FNDD_D = {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_FNDD_D AND {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_FNDD_A = {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_FNDD_A AND {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_PDCT_SYST_ACCT_N = {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_PDCT_SYST_ACCT_N AND {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_CMPE_I = {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_CMPE_I AND {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_CMPE_ACCT_BSB_N = {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_CMPE_ACCT_BSB_N AND {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_CMPE_ACCT_N = {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_CMPE_ACCT_N THEN '0'
		END AS change_code 
	FROM {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }} 
	FULL OUTER JOIN {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }} 
	ON {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_APPT_PDCT_I = {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_APPT_PDCT_I
	AND {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_APPT_PDCT_FNDD_I = {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_APPT_PDCT_FNDD_I
	AND {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_APPT_PDCT_FNDD_METH_I = {{ ref('{{ ref('CpyApptPdctFnddInss') }}') }}.NEW_APPT_PDCT_FNDD_METH_I
	WHERE change_code = '1' OR change_code = '3'
)

SELECT * FROM ChangeCapture