{{ config(materialized='view', tags=['LdDltAPP_ANS_EVNT_EMPL']) }}

WITH 
tmp_xs_evnt_app_ans AS (
	SELECT
	*
	FROM {{ ref("tmp_xs_evnt_app_ans")  }}),
evnt_empl AS (
	SELECT
	*
	FROM {{ ref("evnt_empl")  }}),
Src_Tera_EVNT_EMPL AS (SELECT a.EVNT_I AS NEW_EVNT_I, a.EVNT_PATY_ROLE_TYPE_C_EE AS NEW_EVNT_PATY_ROLE_TYPE_C, a.EMPL_I AS NEW_EMPL_I, b.EVNT_I AS OLD_EVNT_I, b.EVNT_PATY_ROLE_TYPE_C AS OLD_EVNT_PATY_ROLE_TYPE_C, b.EMPL_I AS OLD_EMPL_I FROM TMP_XS_EVNT_APP_ANS LEFT OUTER JOIN EVNT_EMPL ON a.EVNT_I = b.EVNT_I AND a.EVNT_PATY_ROLE_TYPE_C_EE = b.EVNT_PATY_ROLE_TYPE_C AND b.EXPY_D = '9999-12-31' AND a.RUN_STRM = '{{ var("RUN_STREAM") }}' GROUP BY NEW_EVNT_I, NEW_EVNT_PATY_ROLE_TYPE_C, NEW_EMPL_I, OLD_EVNT_I, OLD_EVNT_PATY_ROLE_TYPE_C, OLD_EMPL_I)


SELECT * FROM Src_Tera_EVNT_EMPL