{{ config(materialized='incremental', alias='tmp_appt_pdct_feat_pexahm', incremental_strategy='append', tags=['LdTMP_APPT_PDCT_FEAT_PEXAHM_FrmXfm']) }}

SELECT
	APPT_PDCT_I
	FEAT_I
	SRCE_SYST_APPT_FEAT_I
	EFFT_D
	SRCE_SYST_C
	SRCE_SYST_APPT_OVRD_I
	OVRD_FEAT_I
	SRCE_SYST_STND_VALU_Q
	SRCE_SYST_STND_VALU_R
	SRCE_SYST_STND_VALU_A
	CNCY_C
	ACTL_VALU_Q
	ACTL_VALU_R
	ACTL_VALU_A
	FEAT_SEQN_N
	FEAT_STRT_D
	FEE_CHRG_D
	OVRD_REAS_C
	FEE_ADD_TO_TOTL_F
	FEE_CAPL_F
	EXPY_D
	PROS_KEY_EFFT_I
	PROS_KEY_EXPY_I
	EROR_SEQN_I
	ROW_SECU_ACCS_C
	PEXA_FLAG
	FEAT_VALU_C
	RUN_STRM 
FROM {{ ref('Copy_89') }}