{{ config(materialized='view', tags=['ExtHL_FEATURE_ATTR']) }}

WITH CpyHlFeatureAttrSeq AS (
	SELECT
		HL_FEATURE_ATTR_ID,
		HL_FEATURE_TERM,
		HL_FEATURE_AMOUNT,
		HL_FEATURE_BALANCE,
		HL_FEATURE_FEE,
		HL_FEATURE_SPEC_REPAY,
		HL_FEATURE_EST_INT_AMT,
		HL_FEATURE_DATE,
		HL_FEATURE_COMMENT,
		HL_FEATURE_CAT_ID,
		HL_APP_PROD_ID
	FROM {{ ref('SrcHlFeatureAttrSeq') }}
)

SELECT * FROM CpyHlFeatureAttrSeq