{{ config(materialized='view', tags=['ExtChlIntRateChlIntRatePercChlProdIntMarg']) }}

WITH XfmCheckNulls__OutNullsDS AS (
	SELECT
		-- *SRC*: \(20)If Len(Trim(( IF IsNotNull((XfmCheckNulls.HL_INT_RATE_ID)) THEN (XfmCheckNulls.HL_INT_RATE_ID) ELSE ""))) = 0 Then 'REJ4103' Else '',
		IFF(LEN(TRIM(IFF({{ ref('Cpy_NoOp') }}.HL_INT_RATE_ID IS NOT NULL, {{ ref('Cpy_NoOp') }}.HL_INT_RATE_ID, ''))) = 0, 'REJ4103', '') AS ErrorCode,
		HL_INT_RATE_ID,
		RATE_HL_INT_RATE_ID,
		RATE_HL_APP_PROD_ID,
		RATE_CASS_INT_RATE_TYPE_CODE,
		RATE_RATE_SEQUENCE,
		RATE_DURATION,
		PERC_HL_INT_RATE_ID,
		PERC_SCHEDULE_RATE_TYPE,
		PERC_RATE_PERCENT_1,
		PERC_RATE_PERCENT_2,
		MARG_HL_PROD_INT_MARGIN_ID,
		MARG_HL_INT_RATE_ID,
		MARG_HL_PROD_INT_MARGIN_CAT_ID,
		MARG_MARGIN_TYPE,
		MARG_MARGIN_DESC,
		MARG_MARGIN_CODE,
		MARG_MARGIN_AMOUNT,
		MARG_ADJ_AMT,
		RATE_FOUND_FLAG,
		PERC_FOUND_FLAG,
		MARG_FOUND_FLAG,
		ETL_PROCESS_DT AS ETL_D,
		ETL_PROCESS_DT AS ORIG_ETL_D,
		ErrorCode AS EROR_C
	FROM {{ ref('Cpy_NoOp') }}
	WHERE SUBSTRING(ErrorCode, 1, 3) = 'REJ'
)

SELECT * FROM XfmCheckNulls__OutNullsDS