{{ config(materialized='view', tags=['ExtHL_APP']) }}

WITH 
rejt_chl_bus_app AS (
	SELECT
	*
	FROM {{ source("cse4_stg_dsv81test","rejt_chl_bus_app")  }}),
SrcRejtHlAppRejectOra AS (SELECT HL_APP_ID, HL_PACKAGE_CAT_ID, LPC_OFFICE, STATUS_TRACKER_ID, CAST(ORIG_ETL_D AS TEXT) AS ORIG_ETL_D, HL_APP_PROD_ID, CHL_APP_PCD_EXT_SYS_CAT_ID, CHL_APP_SIMPLE_APP_FLAG, CHL_APP_ORIGINATING_AGENT_ID, CHL_APP_AGENT_NAME, CASS_WITHHOLD_RISKBANK_FLAG, CR_DATE, ASSESSMENT_DATE, NCPR_FLAG, FHB_FLAG, CAST(SETTLEMENT_DATE AS TEXT) AS SETTLEMENT_DATE, PEXA_FLAG, HSCA_FLAG, CAST(HSCA_CONVERTED_TO_FULL_AT AS TEXT) AS HSCA_CONVERTED_TO_FULL_AT FROM REJT_CHL_BUS_APP WHERE EROR_C LIKE 'RPR%')


SELECT * FROM SrcRejtHlAppRejectOra