{{ config(materialized='view', tags=['LdDelFlagREJT_RT_PERC_PROD_INT_MARGUpd']) }}

SELECT
	HL_INT_RATE_ID
	MARG_HL_PROD_INT_MARGIN_CAT_ID
	MARG_MARGIN_TYPE
	MARG_MARGIN_DESC
	MARG_MARGIN_CODE
	MARG_MARGIN_AMOUNT
	MARG_ADJ_AMT
	MARG_FOUND_FLAG
	ETL_D 
FROM {{ ref('ModConversions') }}