name: bteq_test10
version: 1.0.0
config-version: 2
profile: bteq_test10_profile
model-paths:
- models
analysis-paths:
- analyses
test-paths:
- tests
seed-paths:
- seeds
macro-paths:
- macros
snapshot-paths:
- snapshots
target-path: target
clean-targets:
- target
- dbt_packages
vars:
  CAD_PROD_DATA: REPLACE_WITH_CAD_PROD_DATA_VALUE
  CAD_PROD_MACRO: REPLACE_WITH_CAD_PROD_MACRO_VALUE
  DDSTG: PDDSTG
  DGRDDB: REPLACE_WITH_DGRDDB_VALUE
  ENV_C: PROD
  GDW_USER: PUCB2229
  INDATE: REPLACE_WITH_INDATE_VALUE
  PSST_TABLE_M: DERV_ACCT_PATY
  RSTR_F: N
  SRCE_M: DERIVED_ACCOUNT_PARTY
  SRCE_SYST_M: DERIVED_ACCOUNT_PARTY
  STARDATADB: STAR_CAD_PROD_DATA
  STARMACRDB: STAR_CAD_PROD_MACRO
  TBSHORT: ''
  UCB: PUCB
  UTILSTG: REPLACE_WITH_UTILSTG_VALUE
  VCBODS: REPLACE_WITH_VCBODS_VALUE
  VEXTR: REPLACE_WITH_VEXTR_VALUE
  VPATY: PVPATY
  VTECH: PVTECH
models:
  bteq_test10:
    staging:
      +materialized: view
      +docs:
        show: true
    intermediate:
      +materialized: table
      +docs:
        show: true
      +pre_hook: '{{ register_process_instance(this.name) }}'
      +post_hook: '{{ update_process_status(''SUCCESS'') }}'
    marts:
      +materialized: table
      +docs:
        show: true
