use role r_dev_npd_d12_gdwmig;
use database NPD_D12_DMN_GDWMIG_IBRG;
use warehouse wh_usr_npd_d12_gdwmig_001;
use schema iceberg_migrator;

--TO BE CREATED AT CBA
CREATE SCHEMA IF NOT EXISTS NPD_D12_DMN_GDWMIG_IBRG.PP01STARCADPRODDATA;
CREATE SCHEMA IF NOT EXISTS NPD_D12_DMN_GDWMIG_IBRG.PDCBSTG;
CREATE SCHEMA IF NOT EXISTS NPD_D12_DMN_GDWMIG_IBRG.PTEMP;
CREATE SCHEMA IF NOT EXISTS NPD_D12_DMN_GDWMIG_IBRG.UDTDWRK;

USE DATABASE NPD_D12_DMN_GDWMIG_IBRG;

-- drop schema if exists NPD_D12_DMN_GDWMIG_IBRG."pdgrd";
-- drop schema if exists NPD_D12_DMN_GDWMIG_IBRG.PDGRD;
CREATE SCHEMA IF NOT EXISTS NPD_D12_DMN_GDWMIG_IBRG.PDGRD;

DROP TABLE IF EXISTS NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.ACCT_BALN_ADJ;
DROP TABLE IF EXISTS NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_BALN_BKDT_ADJ_RULE;
DROP TABLE IF EXISTS NPD_D12_DMN_GDWMIG_IBRG.PDCBODS.ACCT_MSTR_CYT_DATA;
DROP TABLE IF EXISTS NPD_D12_DMN_GDWMIG_IBRG.PDCBODS.BUSN_PTNR;
DROP TABLE IF EXISTS NPD_D12_DMN_GDWMIG_IBRG.PDCBODS.CBA_FNCL_SERV_GL_DATA;
DROP TABLE IF EXISTS NPD_D12_DMN_GDWMIG_IBRG.PDCBODS.MSTR_CNCT_BALN_TRNF_PRTP;
DROP TABLE IF EXISTS NPD_D12_DMN_GDWMIG_IBRG.PDCBODS.MSTR_CNCT_MSTR_DATA_GENL;
DROP TABLE IF EXISTS NPD_D12_DMN_GDWMIG_IBRG.PDCBODS.MSTR_CNCT_PRXY_ACCT;
DROP TABLE IF EXISTS NPD_D12_DMN_GDWMIG_IBRG.PDSECURITY.ROW_LEVL_SECU_USER_PRFL;
DROP TABLE IF EXISTS NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.DERV_PRTF_PATY_PSST;
DROP TABLE IF EXISTS NPD_D12_DMN_GDWMIG_IBRG.PDGRD.GRD_RPRT_CALR_FNYR;
DROP TABLE IF EXISTS NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_SAP_INVL_PDCT;
DROP TABLE IF EXISTS NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.DERV_PRTF_ACCT_REL;
DROP TABLE IF EXISTS NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.ACCT_PDCT;
DROP TABLE IF EXISTS NPD_D12_DMN_GDWMIG_IBRG.PDPATY.ACCT_PATY;
DROP TABLE IF EXISTS NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.ACCT_OFFR;
DROP TABLE IF EXISTS NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.ACCT_BASE;

DROP TABLE IF EXISTS NPD_D12_DMN_GDWMIG_IBRG.PDGRD.GRD_PRTF_TYPE_ENHC_HIST_PSST;
DROP TABLE IF EXISTS NPD_D12_DMN_GDWMIG_IBRG.PDGRD.GRD_PRTF_TYPE_ENHC_PSST;
DROP TABLE IF EXISTS NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_BALN_BKDT_STG;
DROP TABLE IF EXISTS NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.ACCT_BALN_BKDT;
DROP TABLE IF EXISTS NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.ACCT_BALN_BKDT_RECN;
DROP TABLE IF EXISTS NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.ACCT_INT_GRUP;
DROP TABLE IF EXISTS NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.DERV_PRTF_ACCT_HIST_PSST;
DROP TABLE IF EXISTS NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.DERV_PRTF_ACCT_INT_GRUP_PSST;
DROP TABLE IF EXISTS NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.DERV_PRTF_ACCT_PSST;
DROP TABLE IF EXISTS NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.DERV_PRTF_INT_GRUP_ENHC_PSST;
DROP TABLE IF EXISTS NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.DERV_PRTF_INT_GRUP_OWN_PSST;
DROP TABLE IF EXISTS NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.DERV_PRTF_INT_HIST_PSST;
DROP TABLE IF EXISTS NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.DERV_PRTF_INT_PSST;
DROP TABLE IF EXISTS NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.DERV_PRTF_OWN_HIST_PSST;
DROP TABLE IF EXISTS NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.DERV_PRTF_OWN_PSST;
DROP TABLE IF EXISTS NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.DERV_PRTF_PATY_HIST_PSST;
DROP TABLE IF EXISTS NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.DERV_PRTF_PATY_INT_GRUP_PSST;
DROP TABLE IF EXISTS NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.ACCT_BALN_BKDT_AUDT;
DROP TABLE IF EXISTS NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.ACCT_PATY_TAX_INSS;
DROP TABLE IF EXISTS NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.DERV_PRTF_ACCT_OWN_REL;
DROP TABLE IF EXISTS NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.DERV_PRTF_PATY_OWN_REL;
drop table if exists NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_BALN_BKDT_STG1;
drop table if exists NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_BALN_BKDT_STG2;
DROP TABLE IF EXISTS NPD_D12_DMN_GDWMIG_IBRG.PDGRD.GRD_RPRT_CALR_CLYR;

DROP TABLE IF EXISTS NPD_D12_DMN_GDWMIG_IBRG.PP01STARCADPRODDATA.ACCT_INT_GRUP;
DROP TABLE IF EXISTS NPD_D12_DMN_GDWMIG_IBRG.PDCBSTG.ACCT_REL_HLS_REME;
DROP TABLE IF EXISTS NPD_D12_DMN_GDWMIG_IBRG.PDCBSTG.ACCT_REL_HLS_REME_HIST;
DROP TABLE IF EXISTS NPD_D12_DMN_GDWMIG_IBRG.PDCBSTG.UTIL_PROS_SAP_RUN;
DROP TABLE IF EXISTS NPD_D12_DMN_GDWMIG_IBRG.UDTDWRK.DERV_PRTF_ACCT_HIST_PSST;
DROP TABLE IF EXISTS NPD_D12_DMN_GDWMIG_IBRG.PTEMP.DERV_PRTF_INT_PSST;
DROP TABLE IF EXISTS NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.ACCT_BALN;

--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE NPD_D12_DMN_GDWMIG_IBRG.PDGRD.GRD_RPRT_CALR_CLYR (
 CALR_CALR_D DATE,
 CALR_DAY_SNAM_M STRING,
 CALR_DAY_LONG_M STRING,
 CALR_DAY_N INTEGER,
 CALR_DAY_SNCE_1900_N INTEGER,
 CALR_DATJ_D STRING,
 CALR_NON_WORK_DAY_F STRING,
 CALR_WKND_F STRING, --(1),
 CALR_NON_WORK_DAY_TYPE_C STRING, --(4),
 CALR_NON_WORK_DAY_M STRING, --(50),
 CALR_WEEK_N INTEGER,
 CALR_RPRT_YEAR_WEEK_N INTEGER,
 CALR_WEEK_DAY_N INTEGER,
 CALR_RPRT_WEEK_DAY_N INTEGER,
 CALR_WEEK_SNCE_1900_N INTEGER,
 CALR_WEEK_FRST_DAY_D DATE,
 CALR_WEEK_LAST_DAY_D DATE,
 CALR_WEEK_DAY_RNGE_X STRING, --(34),
 CALR_RPRT_WEEK_DAY_RNGE_X STRING, --(67),
 CLWK_RPRT_TMPD_STRT_D DATE,
 CLWK_RPRT_TMPD_END_D DATE,
 CLWK_RPRT_TMPD_LABL_M STRING, --(40),
 CLWK_RPRT_TMPD_LABL_X STRING, --(255),
 CALR_RPRT_WEEK_SNCE_1900_N INTEGER,
 CALR_MNTH_N INTEGER,
 CALR_MNTH_SNAM_M STRING, --(20),
 CALR_MNTH_LONG_M STRING, --(20),
 CALR_MNTH_YEAR_SNAM_M STRING, --(23),
 CALR_MNTH_YEAR_LONG_M STRING, --(25),
 CALR_MNTH_FRST_DAY_D DATE,
 CALR_MNTH_LAST_DAY_D DATE,
 CALR_MNTH_DAY_N INTEGER,
 CALR_MNTH_WEEK_N INTEGER,
 CALR_MNTH_SNCE_1900_N INTEGER,
 CALR_QRTR_N INTEGER,
 CALR_QRTR_MNTH_N INTEGER,
 CALR_QRTR_SNAM_M STRING, --(5),
 CALR_QRTR_LONG_M STRING, --(11),
 CALR_QRTR_SNCE_1900_N INTEGER,
 CALR_HFYR_N INTEGER,
 CALR_HFYR_SNAM_M STRING, --(7),
 CALR_HFYR_LONG_M STRING, --(11),
 CALR_HFYR_SNCE_1900_N INTEGER,
 CALR_YEAR_N INTEGER,
 CLYR_RPRT_TMPD_LABL_M STRING, --(40),
 CALR_YEAR_SNAM_M STRING, --(5),
 CALR_YEAR_LONG_M STRING, --(9),
 CLYR_RPRT_TMPD_LABL_X STRING, --(255),
 CLYR_RPRT_TMPD_STRT_D DATE,
 CLYR_RPRT_TMPD_END_D DATE,
 CALR_LEAP_YEAR_F STRING, --(1),
 CALR_YEAR_MONTH_N INTEGER,
 CALR_RPRT_MNTH_WE_STRT_D DATE,
 CALR_RPRT_MNTH_WE_END_D DATE,
 CALR_QRTR_FRST_DAY_D DATE,
 CALR_QRTR_LAST_DAY_D DATE,
 CALR_HFYR_FRST_DAY_D DATE,
 CALR_HFYR_LAST_DAY_D DATE
)
COMMENT = '{ "origin": "sf_sc", "name": "snowconvert", "version": {  "major": 1,  "minor": 16,  "patch": "1.0" }, "attributes": {  "component": "teradata",  "convertedOn": "08/22/2025",  "domain": "snowflake", "convertedToIceberg": "08/21/2025" }}'
;




/* <sc-table> STARCADPRODDATA.ACCT_BALN_ADJ </sc-table> */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.ACCT_BALN_ADJ (
 ACCT_I STRING NOT NULL COMMENT 'Account Identifier',
 SRCE_SYST_C STRING NOT NULL COMMENT 'Source System Code',
 BALN_TYPE_C STRING NOT NULL COMMENT 'Balance Type Code',
 CALC_FUNC_C STRING NOT NULL COMMENT 'Calculation Function Code',
 TIME_PERD_C STRING NOT NULL COMMENT 'Time Period Code',
 ADJ_FROM_D DATE NOT NULL COMMENT 'Adjustment From Date',
 ADJ_TO_D DATE COMMENT 'Adjustment To Date',
 ADJ_A DECIMAL(23,5) COMMENT 'Adjustment Amount',
 GL_RECN_F STRING COMMENT 'Gl Reconciliation Flag',
 EFFT_D DATE NOT NULL COMMENT 'Effective Date',
 PROS_KEY_EFFT_I DECIMAL(10,0) COMMENT 'Process Key Effective Identifier',
 EROR_SEQN_I DECIMAL(10,0) COMMENT 'Error Sequence Identifier',
 CNCY_C STRING COMMENT 'Currency Code',
 CALC_F STRING COMMENT 'Calculate Flag',
 ROW_SECU_ACCS_C INTEGER COMMENT 'Row Security Access Code'
)
COMMENT = '{ "origin": "sf_sc", "name": "snowconvert", "version": {  "major": 1,  "minor": 16,  "patch": "1.0" }, "attributes": {  "component": "teradata",  "convertedOn": "08/22/2025",  "domain": "snowflake", "convertedToIceberg": "08/21/2025" }}'
;






/* <sc-table> PDCBODS.ACCT_MSTR_CYT_DATA </sc-table> */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE NPD_D12_DMN_GDWMIG_IBRG.PDCBODS.ACCT_MSTR_CYT_DATA (
 ACCT STRING NOT NULL COMMENT 'Account',
 BUSN_PTNR_NUMB STRING NOT NULL COMMENT 'Business Partner Number',
 SRCE_SYST_ISAC_CODE STRING NOT NULL COMMENT 'Source System Instance Code',
 VALD_FROM DATE NOT NULL COMMENT 'Valid From',
 VALD_TO DATE COMMENT 'Valid To',
 USER_IN_CYT_CALC STRING COMMENT 'Usage In Cyt Calculation',
 CYT_DOCU_QOTE STRING COMMENT 'Cyt Document Quotation',
 RSDT_STUS STRING COMMENT 'Residential Status',
 UPDT_MODE STRING COMMENT 'Update Mode',
 LOAD_S TIMESTAMP(6) COMMENT 'Load Timestamp',
 PROS_KEY_EFFT_I INTEGER NOT NULL COMMENT 'Process Key Effective Identifier',
 ROW_SECU_ACCS_C INTEGER COMMENT 'Row Security Access Code',
 RECD_CNT DECIMAL(20,0) COMMENT 'Record Count',
 LAST_UPDT_ON DATE COMMENT 'Last Updated On',
 BDT_OBJC_APPT STRING COMMENT 'Bdt Object Application',
 CNCT_PART_ID STRING COMMENT 'Contract Part Id',
 OBJC_FUNC STRING COMMENT 'Object Function',
 PROS_TIME_STMP TIMESTAMP(6) COMMENT 'Processing Time Stamp',
 LAST_CHNG_BY STRING COMMENT 'Last Changed By',
 BUSN_TRAN_CATG_FOR_THE_CHNG STRING COMMENT 'Business Transaction Category For The Change',
 PDCG STRING COMMENT 'Product Category',
 CUST_ENHC_2_ID STRING COMMENT 'Customer Enhancement 2 Id',
 TIME_STMP_SHRT_FORM TIMESTAMP(6) COMMENT 'Time Stamp Short Form',
 VALD_FROM_DTTS TIMESTAMP(6) COMMENT 'Valid From Timestamp',
 VALD_TO_DTTS TIMESTAMP(6) COMMENT 'Valid To Timestamp'
)
COMMENT = '{ "origin": "sf_sc", "name": "snowconvert", "version": {  "major": 1,  "minor": 16,  "patch": "2.0" }, "attributes": {  "component": "teradata",  "convertedOn": "08/21/2025",  "domain": "snowflake", "convertedToIceberg": "08/21/2025" }}'
;


/* <sc-table> PDCBODS.BUSN_PTNR </sc-table> */
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE NPD_D12_DMN_GDWMIG_IBRG.PDCBODS.BUSN_PTNR (
 BUSN_PTNR_NUMB STRING NOT NULL COMMENT 'Business Partner Number',
 SRCE_SYST_ISAC_CODE STRING NOT NULL COMMENT 'Source System Instance Code',
 PATY_I STRING NOT NULL COMMENT 'Party Identifier',
 SAP_PATY_I STRING NOT NULL COMMENT 'SAP PATY IDENTIFIER',
 DOB DATE COMMENT 'Date of Birth',
 FRST_ACDM_TITL STRING COMMENT 'First Academic Title',
 SCND_ACDM_TITL STRING COMMENT 'Second Academic Title',
 BUSN_PTNR_NAME_AT_BRTH STRING COMMENT 'Business Partner Name At Birth',
 BUSN_PTNR_CATG STRING COMMENT 'Business Partner Category',
 BUSN_PTNR_CTCT_PMIS STRING COMMENT 'Business Partner Contact Permission',
 BUSN_PTNR_NUMB_IN_EXTL_SYST STRING COMMENT 'Business Partner Number In External System',
 BUSN_PTNR_FRST_NAME STRING COMMENT 'Business Partner First Name',
 BUSN_PTNR_GRUP STRING COMMENT 'Business Partner Grouping',
 BUSN_PTNR_NAME_1_GRUP STRING COMMENT 'Business Partner Name 1 Group',
 BUSN_PTNR_NAME_2_GRUP STRING COMMENT 'Business Partner Name 2 Group',
 BUSN_PTNR_GRUP_TYPE STRING COMMENT 'Business Partner Group Type',
 BUSN_PTNR_SRNM STRING COMMENT 'Business Partner Surname',
 BUSN_PTNR_MRST STRING COMMENT 'Business Partner Marital Status',
 BUSN_PTNR_MDLE_NAME STRING COMMENT 'Business Partner Middle Name',
 BUSN_PTNR_SCND_SRNM STRING COMMENT 'Business Partner Second Surname',
 PTNR_TYPE STRING COMMENT 'Partner Type',
 CHNG_BY STRING COMMENT 'Changed by',
 LAST_CHNG_AT TIME(6) COMMENT 'Last Change At',
 LAST_CHNG_ON DATE COMMENT 'Last changed on',
 NAME_OF_PERS_WHO_CRAT_THE_OBJC STRING COMMENT 'Name of person who created the object',
 RECD_CRAT_DATE DATE COMMENT 'Record Created Date',
 TIME_CRAT TIME(6) COMMENT 'Time Created',
 SLCT_GNDR_MALE STRING COMMENT 'Selection Gender Male',
 SLCT_GNDR_FEM STRING COMMENT 'Selection Gender Female',
 SLCT_GNDR_UNKN STRING COMMENT 'Selection Gender Unknown',
 INDC STRING COMMENT 'Industry code',
 LEGL_STUS_OF_ORGN STRING COMMENT 'Legal Status Of Organisation',
 BUSN_PTNR_ORGN_NAME_1 STRING COMMENT 'Business Partner Organisation Name 1',
 BUSN_PTNR_ORGN_NAME_2 STRING COMMENT 'Business Partner Organisation Name 2',
 BUSN_PTNR_ORGN_NAME_3 STRING COMMENT 'Business Partner Organisation Name 3',
 BUSN_PTNR_ORGN_NAME_4 STRING COMMENT 'Business Partner Organisation Name 4',
 NATY STRING COMMENT 'Nationality',
 NAME_SUPT STRING COMMENT 'Name Supplement',
 FORM_OF_ADRS_TITL STRING COMMENT 'Form of Address Title',
 CNTY_FOR_NAME_FRMT_RULE STRING COMMENT 'Country for name format rule',
 SCND_NAME_PREF STRING COMMENT 'Second name prefix',
 DATE_ORGN_FOUN DATE COMMENT 'Date organisation found',
 BUSN_PTNR_CORR_LANG STRING COMMENT 'Business Partner Correspondence Language',
 BUSN_PTNR_LANG STRING COMMENT 'Business Partner Language',
 NAME_FRMT STRING COMMENT 'Name format',
 DATE_OF_DETH DATE COMMENT 'Date of Death',
 OCCP STRING COMMENT 'Occupation',
 UPDT_MODE STRING COMMENT 'Update Mode',
 LOAD_S TIMESTAMP(6) COMMENT 'Load Timestamp',
 PROS_KEY_EFFT_I INTEGER NOT NULL COMMENT 'Process Key Effective Identifier',
 ROW_SECU_ACCS_C INTEGER NOT NULL COMMENT 'Row Security Access Code',
 RECD_CNT DECIMAL(18,0) COMMENT 'Record Count',
 ADRS_NUMB STRING COMMENT 'Address Number',
 BUSN_PTNR_BRTH_PLAC STRING COMMENT 'Business Partner Birth Place',
 SRCH_TERM_1 STRING COMMENT 'Search Term 1',
 SRCH_TERM_2 STRING COMMENT 'Search Term 2',
 CNTY_OF_ORIG STRING COMMENT 'Country Of Origin',
 CNTY_OF_TAX STRING COMMENT 'Country Of Tax',
 NAME_OF_EMPR_OF_NATU_PERS STRING COMMENT 'Name Of Employer Of Natural Person',
 MDLE_INLS STRING COMMENT 'Middle Initials',
 LENT_FOR_BUSN_PTNR STRING COMMENT 'Legal Entity For Business Partner',
 CLTL_OBJC_LIQD_DATE DATE COMMENT 'Collateral Object Liquidation Date',
 INTL_LOCN_NUMB_PART_1 DECIMAL(7,0) COMMENT 'International Location Number Part 1',
 INTL_LOCN_NUMB_PART_2 DECIMAL(7,0) COMMENT 'International Location Number Part 2',
 INTL_LOCN_NUMB_PART_3 DECIMAL(7,0) COMMENT 'International Location Number Part 3',
 SRCH_HELP_1_NAME_1_LAST_NAME STRING COMMENT 'Search Help 1 Name 1 Last Name',
 SRCH_HELP_2_NAME_2_FRST_NAME STRING COMMENT 'Search Help 2 Name 2 First Name',
 NAME STRING COMMENT 'Name',
 NAME_PART_2 STRING COMMENT 'Name Part 2',
 BUSN_PTNR_IS_A_NATU_PERS_INDA STRING COMMENT 'Business Partner Is A Natural Person Indicator',
 NCKN STRING COMMENT 'Nickname',
 GuID_OF_BUSN_PTNR STRING COMMENT 'Guid Of Business Partner',
 PERS DECIMAL(8,0) COMMENT 'Person',
 ORDR_PATY_PERS_NUMB STRING COMMENT 'Ordering Party Person Number',
 NAME_SUPT_PREF_1 STRING COMMENT 'Name Supplement Prefix 1',
 PRNT_MODE STRING COMMENT 'Print Mode',
 DATA_SRCE STRING COMMENT 'Data Source',
 PLAN_CHNG_DOCU_FOR_PTNR_CONV STRING COMMENT 'Planned Change Documents For Partner Convert',
 SALU STRING COMMENT 'Salutation',
 VALD_FROM_UTC_DTTS TIMESTAMP(6) COMMENT 'Valid From UTC Timestamp',
 VALD_TO_UTC_DTTS TIMESTAMP(6) COMMENT 'Valid To UTC Timestamp',
 BUSN_PTNR_BLOK STRING COMMENT 'Business Partner Block',
 BUSN_PTNR_DELT_FLAG STRING COMMENT 'Business Partner Delete Flag',
 UPD_LOAD_S TIMESTAMP(6) COMMENT 'Updating Load Timestamp',
 UPD_PROS_KEY_EFFT_I INTEGER COMMENT 'Updating Process Key Effective Identifier',
 IS_CURR_IND INT NOT NULL COMMENT 'IS Current Indicator',
 AUTN_GRUP STRING COMMENT 'Authorisation Group'
)
COMMENT = '{ "origin": "sf_sc", "name": "snowconvert", "version": {  "major": 1,  "minor": 16,  "patch": "2.0" }, "attributes": {  "component": "teradata",  "convertedOn": "08/21/2025",  "domain": "snowflake", "convertedToIceberg": "08/21/2025" }}'
;



/* <sc-table> PDCBODS.CBA_FNCL_SERV_GL_DATA </sc-table> */
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE NPD_D12_DMN_GDWMIG_IBRG.PDCBODS.CBA_FNCL_SERV_GL_DATA (
 RECD_CNT DECIMAL(20,0) COMMENT 'Record Count',
 INTR_CNCT_ID STRING NOT NULL COMMENT 'Internal Contract Id',
 INTR_OBJC_IDNN STRING NOT NULL COMMENT 'Internal Object Identification',
 SRCE_SYST_ISAC_CODE STRING NOT NULL COMMENT 'Source System Instance Code',
 OBJC_BDT_APPT STRING COMMENT 'Object Bdt Application',
 OBJC_FUNC STRING COMMENT 'Object Function',
 CHNG_TIME_STMP TIMESTAMP(6) COMMENT 'Change Time Stamp',
 VALD_FROM TIMESTAMP(6) COMMENT 'Valid From',
 ACTL_VALD_END TIMESTAMP(6) COMMENT 'Actual Validity End',
 LAST_CHNG_BY STRING COMMENT 'Last Changed By',
 BUSN_TRAN_CATG STRING COMMENT 'Business Transaction Category',
 SALE_PDCT STRING COMMENT 'Sales Product',
 DEPT_ID STRING COMMENT 'Department Id',
 AFLT STRING COMMENT 'Affiliate',
 ALT_PDCT_ID STRING COMMENT 'Alternate Product Id',
 SHRT_FORM_TIME_STMP TIMESTAMP(6) COMMENT 'Short Form Time Stamp',
 MIGR_GRUP STRING COMMENT 'Migration Group',
 UPDT_MODE STRING COMMENT 'Update Mode',
 LOAD_S TIMESTAMP(6) COMMENT 'Load Timestamp',
 PROS_KEY_EFFT_I INTEGER NOT NULL COMMENT 'Process Key Effective Identifier',
 ROW_SECU_ACCS_C INTEGER NOT NULL COMMENT 'Row Security Access Code',
 UPD_LOAD_S TIMESTAMP(6) COMMENT 'Update Load Timestamp (Physical Only)',
 UPD_PROS_KEY_EFFT_I INTEGER COMMENT 'Update Process Key Effective ID (Physical Only)',
 IS_CURR_IND INT NOT NULL COMMENT 'Is Current Indicator'
)
COMMENT = '{ "origin": "sf_sc", "name": "snowconvert", "version": {  "major": 1,  "minor": 16,  "patch": "2.0" }, "attributes": {  "component": "teradata",  "convertedOn": "08/21/2025",  "domain": "snowflake", "convertedToIceberg": "08/21/2025" }}'
;

/* <sc-table> PDCBODS.MSTR_CNCT_BALN_TRNF_PRTP </sc-table> */
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE NPD_D12_DMN_GDWMIG_IBRG.PDCBODS.MSTR_CNCT_BALN_TRNF_PRTP (
 RECD_CNT DECIMAL(20,0) COMMENT 'Record Count',
 INTR_CNCT_NUMB_OF_MAIN_CNCT STRING NOT NULL COMMENT 'Internal Contract Number Of Main Contract',
 ELEM_OF_A_CNCT_HIER_GRUP STRING NOT NULL COMMENT 'Element Of A Contract Hierarchy Group',
 SRCE_SYST_ISAC_CODE STRING NOT NULL COMMENT 'Source System Instance Code',
 OBJC_BDT_APPT STRING COMMENT 'Object Bdt Application',
 INTR_OBJC_IDNN STRING COMMENT 'Internal Object Identification',
 OBJC_FUNC STRING COMMENT 'Object Function',
 TREE_TYPE STRING COMMENT 'Tree Type',
 CNCT_CATG STRING COMMENT 'Contract Category',
 MAIN_CNCT_CATG STRING COMMENT 'Main Contract Category',
 VALD_FROM TIMESTAMP(6) COMMENT 'Valid From',
 ACTL_VALD_END TIMESTAMP(6) COMMENT 'Actual Validity End',
 MEMB_BDT_APPT STRING COMMENT 'Member Bdt Application',
 OBJC_FIX_PRTP_MAIN_CNCT STRING COMMENT 'Object Fixed Participant Main Contract',
 HIER_ID STRING COMMENT 'Hierarchy Id',
 BALN_TRNF_ROLE STRING COMMENT 'Balance Transfer Role',
 TSHD_AMT DECIMAL(23,5) COMMENT 'Threshold Amount',
 CNCY STRING COMMENT 'Currency',
 FUND_ACCT_RANK DECIMAL(3,0) COMMENT 'Funding Account Ranking',
 MAX_PERC_RATE DECIMAL(4,0) COMMENT 'Maximum Percentage Rate',
 BALN_TRNF_BALN_DETR_BSIS STRING COMMENT 'Balance Transfer Balance Determination Basis',
 SHRT_FORM_TIME_STMP TIMESTAMP(6) COMMENT 'Short Form Time Stamp',
 UPDT_MODE STRING COMMENT 'Update Mode',
 LOAD_S TIMESTAMP(6) COMMENT 'Load Timestamp',
 PROS_KEY_EFFT_I INTEGER NOT NULL COMMENT 'Process Key Effective Identifier',
 ROW_SECU_ACCS_C INTEGER NOT NULL COMMENT 'Row Security Access Code',
 UPD_LOAD_S TIMESTAMP(6) COMMENT 'Update Load Timestamp (Physical Only)',
 UPD_PROS_KEY_EFFT_I INTEGER COMMENT 'Update Process Key Effective Identifier',
 IS_CURR_IND INT NOT NULL COMMENT 'Is Current Indicator'
)
COMMENT = '{ "origin": "sf_sc", "name": "snowconvert", "version": {  "major": 1,  "minor": 16,  "patch": "2.0" }, "attributes": {  "component": "teradata",  "convertedOn": "08/21/2025",  "domain": "snowflake", "convertedToIceberg": "08/21/2025" }}'
;

/* <sc-table> PDCBODS.MSTR_CNCT_MSTR_DATA_GENL </sc-table> */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE NPD_D12_DMN_GDWMIG_IBRG.PDCBODS.MSTR_CNCT_MSTR_DATA_GENL (
 RECD_CNT DECIMAL(20,0) COMMENT 'Record Count',
 INTR_CNCT_NUMB_OF_MAIN_CNCT STRING NOT NULL COMMENT 'Internal Contract Number Of Main Contract',
 SRCE_SYST_ISAC_CODE STRING NOT NULL COMMENT 'Source System Instance Code',
 ACCT_I STRING COMMENT 'Account Identifier',
 OBJC_BDT_APPT STRING COMMENT 'Object Bdt Application',
 CHNG_TIME_STMP TIMESTAMP(6) COMMENT 'Change Time Stamp',
 VALD_STRT TIMESTAMP(6) COMMENT 'Validity Start',
 ACTL_VALD_END TIMESTAMP(6) COMMENT 'Actual Validity End',
 LAST_CHNG_BY STRING COMMENT 'Last Changed By',
 BUSN_TRAN_CATG_FOR_THE_CHNG STRING COMMENT 'Business Transaction Category For The Change',
 MSTR_CNCT_NUMB STRING COMMENT 'Master Contract Number',
 SHRT_FORM_TIME_STMP TIMESTAMP(6) COMMENT 'Short Form Time Stamp',
 UPDT_MODE STRING COMMENT 'Update Mode',
 LOAD_S TIMESTAMP(6) COMMENT 'Load Timestamp',
 PROS_KEY_EFFT_I INTEGER NOT NULL COMMENT 'Process Key Effective Identifier',
 ROW_SECU_ACCS_C INTEGER NOT NULL COMMENT 'Row Security Access Code',
 ORGN_UNIT DECIMAL(8,0) COMMENT 'Organization Unit',
 CNCT_CLAR_1 STRING COMMENT 'Contract Calender 1',
 CNCT_CLAR_2 STRING COMMENT 'Contract Calender 2',
 CNCT_CLAR_3 STRING COMMENT 'Contract Calender 3',
 BANK_POST_AREA STRING COMMENT 'Bank Posting Area'
)
COMMENT = '{ "origin": "sf_sc", "name": "snowconvert", "version": {  "major": 1,  "minor": 16,  "patch": "2.0" }, "attributes": {  "component": "teradata",  "convertedOn": "08/21/2025",  "domain": "snowflake", "convertedToIceberg": "08/21/2025" }}'
;

/* <sc-table> PDCBODS.MSTR_CNCT_PRXY_ACCT </sc-table> */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE NPD_D12_DMN_GDWMIG_IBRG.PDCBODS.MSTR_CNCT_PRXY_ACCT (
 RECD_CNT DECIMAL(20,0) COMMENT 'Record Count',
 ELEM_OF_A_CNCT_HIER_GRUP STRING NOT NULL COMMENT 'Element of a Contract Hierarchy Group',
 CNCT_TYPE_KEY DECIMAL(2,0) NOT NULL COMMENT 'Contract Type Key',
 SRCE_SYST_ISAC_CODE STRING NOT NULL COMMENT 'Source System Instance Code',
 EXTL_CNCT_PART_1 STRING COMMENT 'External Contract Part 1',
 EXTL_CNCT_PART_2 STRING COMMENT 'External Contract Part 2',
 EXTL_CNCT_PART_3 STRING COMMENT 'External Contract Part 3',
 ACCT_CATG STRING COMMENT 'Account Category',
 UPDT_MODE STRING COMMENT 'Update Mode',
 LOAD_S TIMESTAMP(6) COMMENT 'Load Timestamp',
 PROS_KEY_EFFT_I INTEGER NOT NULL COMMENT 'Process Key Effective Identifier',
 ROW_SECU_ACCS_C INTEGER NOT NULL COMMENT 'Row Security Access Code',
 NON_SAP_ACCT_IDNN STRING COMMENT 'Non Sap Account Identification Code',
 NON_SAP_ACCT_SALE_PDCT STRING COMMENT 'Non Sap Account Sale Product',
 NON_SAP_ACCT_NUMB STRING COMMENT 'Non Sap Account Number',
 CIF_PDCT_CODE STRING COMMENT 'Cif Product Code',
 CIF_SUB_PDCT_CODE STRING COMMENT 'Cif Sub Product Code',
 APPT_CODE STRING COMMENT 'APPT_CODE',
 SRCE_SYST STRING COMMENT 'Source System',
 CIF_PDCT_IDNN STRING COMMENT 'CIF_PDCT_IDNN',
 CRIS_PDCT_C STRING COMMENT 'CRIS_PDCT_C'
)
COMMENT = '{ "origin": "sf_sc", "name": "snowconvert", "version": {  "major": 1,  "minor": 16,  "patch": "2.0" }, "attributes": {  "component": "teradata",  "convertedOn": "08/21/2025",  "domain": "snowflake", "convertedToIceberg": "08/21/2025" }}'
;


/* <sc-table> PDSECURITY.ROW_LEVL_SECU_USER_PRFL </sc-table> */
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE NPD_D12_DMN_GDWMIG_IBRG.PDSECURITY.ROW_LEVL_SECU_USER_PRFL (
 USERNAME STRING NOT NULL COMMENT 'User Name',
 ROW_SECU_PRFL_C BINARY(130) NOT NULL COMMENT 'Row Security Profile Code',
 MY_SERVICE_NO STRING COMMENT 'MyServiceNo',
 REQ_NO STRING COMMENT 'REQNo',
 RITM_NO STRING COMMENT 'RITMNo',
 SAR_NO STRING COMMENT 'SARNo',
 CMMT STRING COMMENT 'Comments',
 UPDT_USERNAME STRING NOT NULL COMMENT 'User Name',
 UPDT_DATE DATE NOT NULL COMMENT 'Update Date',
 UPDT_DTTS TIMESTAMP(6) NOT NULL COMMENT 'Update DateTime'
)
COMMENT = '{ "origin": "sf_sc", "name": "snowconvert", "version": {  "major": 1,  "minor": 16,  "patch": "2.0" }, "attributes": {  "component": "teradata",  "convertedOn": "08/21/2025",  "domain": "snowflake", "convertedToIceberg": "08/21/2025" }}'
;

/* <sc-table> STARCADPRODDATA.DERV_PRTF_PATY_PSST </sc-table> */
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.DERV_PRTF_PATY_PSST (
 INT_GRUP_I STRING,
 PATY_I STRING,
 JOIN_FROM_D DATE,
 JOIN_TO_D DATE,
 EFFT_D DATE,
 EXPY_D DATE,
 VALD_FROM_D DATE,
 VALD_TO_D DATE,
 REL_C STRING,
 SRCE_SYST_C STRING,
 ROW_SECU_ACCS_C INTEGER,
 PROS_KEY_I DECIMAL(10,0)
)
COMMENT = '{ "origin": "sf_sc", "name": "snowconvert", "version": {  "major": 1,  "minor": 16,  "patch": "2.0" }, "attributes": {  "component": "teradata",  "convertedOn": "08/21/2025",  "domain": "snowflake", "convertedToIceberg": "08/21/2025" }}'
;

/* <sc-table> PDGRD.GRD_RPRT_CALR_FNYR </sc-table> */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE NPD_D12_DMN_GDWMIG_IBRG.PDGRD.GRD_RPRT_CALR_FNYR (
 FNCL_CALR_D DATE,
 FNCL_DAY_SNAM_M STRING,
 FNCL_DAY_LONG_M STRING,
 FNCL_DAY_N INTEGER,
 FNCL_DAY_SNCE_1900_N INTEGER,
 FNCL_DATJ_D STRING,
 FNCL_NON_WORK_DAY_F STRING,
 FNCL_WKND_F STRING,
 FNCL_NON_WORK_DAY_TYPE_C STRING,
 FNCL_NON_WORK_DAY_M STRING,
 FNCL_WEEK_N INTEGER,
 FNCL_RPRT_YEAR_WEEK_N INTEGER,
 FNCL_WEEK_DAY_N INTEGER,
 FNCL_RPRT_WEEK_DAY_N INTEGER,
 FNCL_WEEK_SNCE_1900_N INTEGER,
 FNCL_WEEK_FRST_DAY_D DATE,
 FNCL_WEEK_LAST_DAY_D DATE,
 FNCL_WEEK_DAY_RNGE_X STRING,
 FNCL_RPRT_WEEK_DAY_RNGE_X STRING,
 FNWK_RPRT_TMPD_STRT_D DATE,
 FNWK_RPRT_TMPD_END_D DATE,
 FNWK_RPRT_TMPD_LABL_M STRING,
 FNWK_RPRT_TMPD_LABL_X STRING,
 FNCL_RPRT_WEEK_SNCE_1900_N INTEGER,
 FNCL_MNTH_N INTEGER,
 FNCL_MNTH_SNAM_M STRING,
 FNCL_MNTH_LONG_M STRING,
 FNCL_MNTH_YEAR_SNAM_M STRING,
 FNCL_MNTH_YEAR_LONG_M STRING,
 FNCL_MNTH_FRST_DAY_D DATE,
 FNCL_MNTH_LAST_DAY_D DATE,
 FNCL_MNTH_DAY_N INTEGER,
 FNCL_MNTH_WEEK_N INTEGER,
 FNCL_MNTH_SNCE_1900_N INTEGER,
 FNCL_QRTR_N INTEGER,
 FNCL_QRTR_MNTH_N INTEGER,
 FNCL_QRTR_SNAM_M STRING,
 FNCL_QRTR_LONG_M STRING,
 FNCL_QRTR_SNCE_1900_N INTEGER,
 FNCL_HFYR_N INT,
 FNCL_HFYR_SNAM_M STRING,
 FNCL_HFYR_LONG_M STRING,
 FNCL_HFYR_SNCE_1900_N INTEGER,
 FNCL_YEAR_N INTEGER,
 FNYR_RPRT_TMPD_LABL_M STRING,
 FNCL_YEAR_SNAM_M STRING,
 FNCL_YEAR_LONG_M STRING,
 FNYR_RPRT_TMPD_LABL_X STRING,
 FNYR_RPRT_TMPD_STRT_D DATE,
 FNYR_RPRT_TMPD_END_D DATE,
 FNCL_LEAP_YEAR_F STRING,
 FNCL_YEAR_MONTH_N INTEGER,
 FNCL_RPRT_MNTH_WE_STRT_D DATE,
 FNCL_RPRT_MNTH_WE_END_D DATE,
 FNCL_QRTR_FRST_DAY_D DATE,
 FNCL_QRTR_LAST_DAY_D DATE,
 FNCL_HFYR_FRST_DAY_D DATE,
 FNCL_HFYR_LAST_DAY_D DATE
)
COMMENT = '{ "origin": "sf_sc", "name": "snowconvert", "version": {  "major": 1,  "minor": 16,  "patch": "2.0" }, "attributes": {  "component": "teradata",  "convertedOn": "08/21/2025",  "domain": "snowflake", "convertedToIceberg": "08/21/2025" }}'
;

/* <sc-table> STARCADPRODDATA.MAP_SAP_INVL_PDCT </sc-table> */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.MAP_SAP_INVL_PDCT (
 PDCT STRING NOT NULL COMMENT 'PRODUCT',
 PDCT_C STRING NOT NULL COMMENT 'PRODUCT CODE',
 EFFT_D DATE NOT NULL COMMENT 'Effective Date',
 EXPY_D DATE NOT NULL COMMENT 'Expiry Date'
)
COMMENT = '{ "origin": "sf_sc", "name": "snowconvert", "version": {  "major": 1,  "minor": 16,  "patch": "2.0" }, "attributes": {  "component": "teradata",  "convertedOn": "08/21/2025",  "domain": "snowflake", "convertedToIceberg": "08/21/2025" }}'
;

/* <sc-table> STARCADPRODDATA.DERV_PRTF_ACCT_REL </sc-table> */
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.DERV_PRTF_ACCT_REL (
 ACCT_I STRING NOT NULL COMMENT 'Account Identifier',
 INT_GRUP_I STRING NOT NULL COMMENT 'Interest Group Identifier',
 DERV_PRTF_CATG_C STRING COMMENT 'Derived Portfolio Category Code',
 DERV_PRTF_CLAS_C STRING COMMENT 'Derived Portfolio Class Code',
 DERV_PRTF_TYPE_C STRING COMMENT 'Derived Portfolio Type Code',
 VALD_FROM_D DATE COMMENT 'Valid From Date',
 VALD_TO_D DATE COMMENT 'Valid To Date',
 EFFT_D DATE NOT NULL COMMENT 'Effective Date',
 EXPY_D DATE NOT NULL COMMENT 'Expiry Date',
 PTCL_N INT COMMENT 'Point Of Control Number',
 REL_MNGE_I STRING COMMENT 'Relationship Manager Identifier',
 PRTF_CODE_X STRING COMMENT 'Portfolio Code Description',
 SRCE_SYST_C STRING COMMENT 'Source System Code',
 ROW_SECU_ACCS_C INTEGER NOT NULL COMMENT 'Row Secuirty Access Code'
)
COMMENT = '{ "origin": "sf_sc", "name": "snowconvert", "version": {  "major": 1,  "minor": 16,  "patch": "2.0" }, "attributes": {  "component": "teradata",  "convertedOn": "08/21/2025",  "domain": "snowflake", "convertedToIceberg": "08/21/2025" }}'
;

/* <sc-table> STARCADPRODDATA.ACCT_PDCT </sc-table> */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.ACCT_PDCT (
 ACCT_I STRING NOT NULL COMMENT 'Account Identifier',
 EFFT_D DATE NOT NULL COMMENT 'Effective Date',
 EXPY_D DATE NOT NULL COMMENT 'Expiry Date',
 PDCT_N INTEGER NOT NULL COMMENT 'Product Number',
 PROS_KEY_EFFT_I DECIMAL(10,0) COMMENT 'Process Key Effective Identifier',
 PROS_KEY_EXPY_I DECIMAL(10,0) COMMENT 'Process Key Expiry Identifier',
 EROR_SEQN_I DECIMAL(10,0) COMMENT 'Error Sequence Identifier',
 ROW_SECU_ACCS_C INTEGER NOT NULL COMMENT 'Row Security Access Code',
 MFTR_PDCT_I STRING COMMENT 'Manufacturing Product Identifier',
 SRCE_SYST_C STRING COMMENT 'Source System Code',
 RECORD_DELETED_FLAG INT NOT NULL COMMENT 'Record Deleted Flag',
 CTL_ID INT NOT NULL COMMENT 'Ctl Id',
 PROCESS_NAME STRING NOT NULL COMMENT 'Process Name',
 PROCESS_ID INTEGER NOT NULL COMMENT 'Process Id',
 UPDATE_PROCESS_NAME STRING COMMENT 'Update Process Name',
 UPDATE_PROCESS_ID INTEGER COMMENT 'Update Process Id'
)
COMMENT = '{ "origin": "sf_sc", "name": "snowconvert", "version": {  "major": 1,  "minor": 16,  "patch": "2.0" }, "attributes": {  "component": "teradata",  "convertedOn": "08/21/2025",  "domain": "snowflake", "convertedToIceberg": "08/21/2025" }}'
;

/* <sc-table> PDPATY.ACCT_PATY </sc-table> */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE NPD_D12_DMN_GDWMIG_IBRG.PDPATY.ACCT_PATY (
 PATY_I STRING NOT NULL COMMENT 'Party Identifier',
 ACCT_I STRING NOT NULL COMMENT 'Account Identifier',
 PATY_ACCT_REL_C STRING NOT NULL COMMENT 'Party Account Relationship Code',
 REL_LEVL_C STRING COMMENT 'Relation Level Code',
 REL_REAS_C STRING COMMENT 'Relation Reason Code',
 REL_STUS_C STRING COMMENT 'Relation Status Code',
 SRCE_SYST_C STRING COMMENT 'Source System Code',
 EFFT_D DATE NOT NULL COMMENT 'Effective Date',
 EXPY_D DATE NOT NULL COMMENT 'Expiry Date',
 PROS_KEY_EFFT_I INTEGER NOT NULL COMMENT 'Process Key Effective Identifier',
 PROS_KEY_EXPY_I INTEGER COMMENT 'Process Key Expiry Identifier',
 ROW_SECU_ACCS_C INTEGER NOT NULL COMMENT 'Row Security Access Code'
)
COMMENT = '{ "origin": "sf_sc", "name": "snowconvert", "version": {  "major": 1,  "minor": 16,  "patch": "2.0" }, "attributes": {  "component": "teradata",  "convertedOn": "08/21/2025",  "domain": "snowflake", "convertedToIceberg": "08/21/2025" }}'
;

/* <sc-table> STARCADPRODDATA.ACCT_OFFR </sc-table> */
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.ACCT_OFFR (
 ACCT_I STRING NOT NULL COMMENT 'Account Identifier',
 OFFR_I STRING NOT NULL COMMENT 'Offer Identifier',
 EFFT_D DATE NOT NULL COMMENT 'Effective Date',
 SRCE_SYST_C STRING NOT NULL COMMENT 'Source System Code',
 EXPY_D DATE NOT NULL COMMENT 'Expiry Date',
 PROS_KEY_EFFT_I DECIMAL(10,0) COMMENT 'Process Key Effective Identifier',
 PROS_KEY_EXPY_I DECIMAL(10,0) COMMENT 'Process Key Expiry Identifier',
 ROW_SECU_ACCS_C INTEGER NOT NULL COMMENT 'Row Security Access Code',
 ACCT_OFFR_STRT_D DATE COMMENT 'ACCOUNT OFFER START DATE',
 ACCT_OFFR_END_D DATE COMMENT 'ACCOUNT OFFER END DATE'
)
COMMENT = '{ "origin": "sf_sc", "name": "snowconvert", "version": {  "major": 1,  "minor": 16,  "patch": "2.0" }, "attributes": {  "component": "teradata",  "convertedOn": "08/21/2025",  "domain": "snowflake", "convertedToIceberg": "08/21/2025" }}'
;

/* <sc-table> STARCADPRODDATA.ACCT_BASE </sc-table> */
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.ACCT_BASE (
 ACCT_I STRING NOT NULL COMMENT 'Account Identifier',
 SRCE_SYST_ACCT_N STRING COMMENT 'Source System Account Number',
 OPEN_D DATE COMMENT 'Account Open Date',
 ACCT_CLSE_REAS_C STRING COMMENT 'Account Close Reason Code',
 CLSE_D DATE COMMENT 'Account Closed Date',
 BUSN_UNIT_BRCH_N STRING COMMENT 'Business Unit Branch Number',
 ORIG_I STRING NOT NULL COMMENT 'Origin Identifier',
 BUSN_UNIT_I STRING NOT NULL COMMENT 'Business Unit Identifier',
 SRCE_SYST_C STRING NOT NULL COMMENT 'Source System Code',
 ACCT_N STRING COMMENT 'Account Number',
 ACCT_QLFY_C STRING NOT NULL COMMENT 'Account Qualifier Code',
 CNCY_C STRING COMMENT 'Currency Code',
 ACCT_OBTN_TYPE_C STRING NOT NULL COMMENT 'Account Obtained Type Code',
 ACCT_CATG_TYPE_C STRING NOT NULL COMMENT 'Account Category Type Code',
 ACCT_CLAS_TYPE_C STRING NOT NULL COMMENT 'Account Class Type Code',
 PROS_KEY_EFFT_I DECIMAL(10,0) COMMENT 'Process Key Effective Identifier',
 PROS_KEY_EXPY_I DECIMAL(10,0) COMMENT 'Process Key Expiry Identifier',
 EROR_SEQN_I DECIMAL(10,0) COMMENT 'Error Sequence Identifier',
 ROW_SECU_ACCS_C INTEGER NOT NULL COMMENT 'Row Security Access Code',
 ISO_CNTY_C STRING COMMENT 'ISO Country Code',
 BANK_N STRING COMMENT 'Bank Number',
 EFFT_D DATE COMMENT 'Effective Date',
 EXPY_D DATE COMMENT 'Expiry Date',
 RECORD_DELETED_FLAG INT NOT NULL COMMENT 'Record Deleted Flag',
 CTL_ID INT NOT NULL COMMENT 'Ctl Id',
 PROCESS_NAME STRING NOT NULL COMMENT 'Process Name',
 PROCESS_ID INTEGER NOT NULL COMMENT 'Process Id',
 UPDATE_PROCESS_NAME STRING COMMENT 'Update Process Name',
 UPDATE_PROCESS_ID INTEGER COMMENT 'Update Process Id'
)
COMMENT = '{ "origin": "sf_sc", "name": "snowconvert", "version": {  "major": 1,  "minor": 16,  "patch": "2.0" }, "attributes": {  "component": "teradata",  "convertedOn": "08/21/2025",  "domain": "snowflake", "convertedToIceberg": "08/21/2025" }}'
; 



--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_BALN_BKDT_ADJ_RULE (
    ACCT_I STRING NOT NULL,
    SRCE_SYST_C STRING,
    BALN_TYPE_C STRING,
    CALC_FUNC_C STRING,
    TIME_PERD_C STRING,
    ADJ_FROM_D DATE NOT NULL,
    BKDT_ADJ_FROM_D DATE NOT NULL,
    ADJ_TO_D DATE NOT NULL,
    ADJ_A DECIMAL(38,2),
    EFFT_D DATE,
    Gl_RECN_F STRING,
    PROS_KEY_EFFT_I DECIMAL(10,0)
); 



------------------------ apply at cba--------------------------------

//////////////// tmp5 //////////////////////




/* DGRDDB.GRD_PRTF_TYPE_ENHC_HIST_PSST -> PDGRD.GRD_PRTF_TYPE_ENHC_HIST_PSST */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE NPD_D12_DMN_GDWMIG_IBRG.PDGRD.GRD_PRTF_TYPE_ENHC_HIST_PSST (
 PRTF_TYPE_C STRING,
 PRTF_TYPE_M STRING,
 PRTF_CLAS_C STRING,
 PRTF_CLAS_M STRING,
 PRTF_CATG_C STRING,
 PRTF_CATG_M STRING,
 VALD_FROM_D DATE,
 VALD_TO_D DATE
);

/* DGRDDB.GRD_PRTF_TYPE_ENHC_PSST -> PDGRD.GRD_PRTF_TYPE_ENHC_PSST */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE NPD_D12_DMN_GDWMIG_IBRG.PDGRD.GRD_PRTF_TYPE_ENHC_PSST (
 PERD_D DATE,
 PRTF_TYPE_C STRING,
 PRTF_TYPE_M STRING,
 PRTF_CLAS_C STRING,
 PRTF_CLAS_M STRING,
 PRTF_CATG_C STRING,
 PRTF_CATG_M STRING
);
/* PDDSTG.ACCT_BALN_BKDT_STG1 -> PDDSTG.ACCT_BALN_BKDT_STG1 */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_BALN_BKDT_STG1 (
 ACCT_I STRING NOT NULL,
 BALN_TYPE_C STRING,
 CALC_FUNC_C STRING,
 TIME_PERD_C STRING,
 BKDT_EFFT_D DATE NOT NULL,
 BKDT_EXPY_D DATE,
 BALN_A DECIMAL(15,2),
 CALC_F STRING,
 PROS_KEY_EFFT_I DECIMAL(10,0),
 PROS_KEY_EXPY_I DECIMAL(10,0),
 BKDT_PROS_KEY_I DECIMAL(10,0),
 ORIG_SRCE_SYST_C STRING,
 SRCE_SYST_C STRING,
 LOAD_D DATE
);

/* PDDSTG.ACCT_BALN_BKDT_STG2 -> PDDSTG.ACCT_BALN_BKDT_STG2 */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE NPD_D12_DMN_GDWMIG_IBRG.PDDSTG.ACCT_BALN_BKDT_STG2 (
 ACCT_I STRING NOT NULL,
 BALN_TYPE_C STRING,
 CALC_FUNC_C STRING,
 TIME_PERD_C STRING,
 BKDT_EFFT_D DATE,
 BKDT_EXPY_D DATE,
 BALN_A DECIMAL(15,2),
 CALC_F STRING,
 PROS_KEY_EFFT_I DECIMAL(10,0),
 PROS_KEY_EXPY_I DECIMAL(10,0),
 BKDT_PROS_KEY_I DECIMAL(10,0),
 ADJ_PROS_KEY_EFFT_I DECIMAL(10,0),
 ORIG_SRCE_SYST_C STRING,
 SRCE_SYST_C STRING,
 LOAD_D DATE
);


/* PVTECH.ACCT_BALN_BKDT -> STARCADPRODDATA.ACCT_BALN_BKDT */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.ACCT_BALN_BKDT (
 ACCT_I STRING NOT NULL COMMENT 'Account Identifier',
 BALN_TYPE_C STRING NOT NULL COMMENT 'Balance Type Code',
 CALC_FUNC_C STRING NOT NULL COMMENT 'Calculation Function Code',
 TIME_PERD_C STRING NOT NULL COMMENT 'Time Period Code',
 BALN_A DECIMAL(23,5) COMMENT 'Balance Amount',
 CALC_F STRING NOT NULL COMMENT 'Calculate Flag',
 SRCE_SYST_C STRING COMMENT 'Source System Code',
 ORIG_SRCE_SYST_C STRING COMMENT 'Original Source System Code',
 LOAD_D DATE COMMENT 'Load Date',
 BKDT_EFFT_D DATE NOT NULL COMMENT 'Backdate Effective Date',
 BKDT_EXPY_D DATE NOT NULL COMMENT 'Backdate Expiry Date',
 PROS_KEY_EFFT_I DECIMAL(10,0) COMMENT 'Process Key Effective Identifier',
 PROS_KEY_EXPY_I DECIMAL(10,0) COMMENT 'Process Key Expiry Identifier',
 BKDT_PROS_KEY_I DECIMAL(10,0) COMMENT 'Backdate Process Key Identifier',
 CNCY_C STRING COMMENT 'Currency Code',
 ROW_SECU_ACCS_C INTEGER COMMENT 'Row Security Access Code'
);

/* PVTECH.ACCT_BALN_BKDT_RECN -> STARCADPRODDATA.ACCT_BALN_BKDT_RECN */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.ACCT_BALN_BKDT_RECN (
 ACCT_I STRING NOT NULL COMMENT 'Account Identifier',
 BALN_A DECIMAL(15,2) COMMENT 'Balance Amount',
 BKDT_EFFT_D DATE NOT NULL COMMENT 'Backdate Effective Date',
 BKDT_EXPY_D DATE NOT NULL COMMENT 'Backdate Expiry Date',
 PROS_KEY_EFFT_I DECIMAL(10,0) COMMENT 'Process Key Effective Identifier'
);

/* STAR_CAD_PROD_DATA.ACCT_BALN_BKDT_AUDT -> STARCADPRODDATA.ACCT_BALN_BKDT_AUDT */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.ACCT_BALN_BKDT_AUDT (
 ACCT_I STRING NOT NULL COMMENT 'Account Identifier',
 BALN_TYPE_C STRING NOT NULL COMMENT 'Balance Type Code',
 CALC_FUNC_C STRING NOT NULL COMMENT 'Calculation Function Code',
 TIME_PERD_C STRING NOT NULL COMMENT 'Time Period Code',
 BALN_A DECIMAL(15,2) COMMENT 'Balance Amount',
 CALC_F STRING NOT NULL COMMENT 'Calculate Flag',
 SRCE_SYST_C STRING COMMENT 'Source System Code',
 ORIG_SRCE_SYST_C STRING COMMENT 'Original Source System Code',
 LOAD_D DATE COMMENT 'Load Date',
 BKDT_EFFT_D DATE NOT NULL COMMENT 'Backdate Effective Date',
 BKDT_EXPY_D DATE NOT NULL COMMENT 'Backdate Expiry Date',
 PROS_KEY_EFFT_I DECIMAL(10,0) COMMENT 'Process Key Effective Identifier',
 ABAL_PROS_KEY_EFFT_I DECIMAL(10,0) COMMENT 'Adjusted Balance Process Key Effective Identifier',
 ABAL_PROS_KEY_EXPY_I DECIMAL(10,0) COMMENT 'Adjusted Balance Process Key Expiry Identifier',
 ABAL_BKDT_PROS_KEY_I DECIMAL(10,0) COMMENT 'Adjusted Balance Backdate Process Key Effective Identifier',
 ADJ_PROS_KEY_EFFT_I DECIMAL(10,0) COMMENT 'Adjusted Process Key Effective Identifier'
);

/* PVTECH.ACCT_INT_GRUP -> STARCADPRODDATA.ACCT_INT_GRUP */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.ACCT_INT_GRUP (
 ACCT_I STRING NOT NULL COMMENT 'Account Identifier',
 INT_GRUP_I STRING NOT NULL COMMENT 'Interest Group Identifier',
 REL_C STRING NOT NULL COMMENT 'Relationship Code',
 SRCE_SYST_C STRING COMMENT 'Source System Code',
 VALD_FROM_D DATE COMMENT 'Valid From Date',
 VALD_TO_D DATE COMMENT 'Valid To Date',
 EFFT_D DATE NOT NULL COMMENT 'Effective Date',
 EXPY_D DATE NOT NULL COMMENT 'Expiry Date',
 PROS_KEY_EFFT_I DECIMAL(10,0) NOT NULL COMMENT 'Process Key Effective Identifier',
 PROS_KEY_EXPY_I DECIMAL(10,0) COMMENT 'Process Key Expiry Identifier',
 ROW_SECU_ACCS_C INTEGER NOT NULL COMMENT 'Row Security Access Code'
);

/* PVTECH.DERV_PRTF_ACCT_HIST_PSST -> STARCADPRODDATA.DERV_PRTF_ACCT_HIST_PSST */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.DERV_PRTF_ACCT_HIST_PSST (
 INT_GRUP_I STRING,
 ACCT_I STRING,
 REL_C STRING,
 JOIN_FROM_D DATE,
 JOIN_TO_D DATE,
 VALD_FROM_D DATE,
 VALD_TO_D DATE,
 EFFT_D DATE,
 EXPY_D DATE,
 SRCE_SYST_C STRING,
 ROW_SECU_ACCS_C INTEGER
);

/* PVTECH.DERV_PRTF_ACCT_INT_GRUP_PSST -> STARCADPRODDATA.DERV_PRTF_ACCT_INT_GRUP_PSST */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.DERV_PRTF_ACCT_INT_GRUP_PSST (
 INT_GRUP_I STRING,
 ACCT_I STRING,
 EFFT_D DATE,
 EXPY_D DATE,
 VALD_FROM_D DATE,
 VALD_TO_D DATE,
 PERD_D DATE,
 REL_C STRING,
 SRCE_SYST_C STRING,
 ROW_N DECIMAL(10,0),
 ROW_SECU_ACCS_C INTEGER,
 PROS_KEY_I DECIMAL(10,0)
);

/* PVTECH.DERV_PRTF_ACCT_PSST -> STARCADPRODDATA.DERV_PRTF_ACCT_PSST */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.DERV_PRTF_ACCT_PSST (
 INT_GRUP_I STRING,
 ACCT_I STRING,
 REL_C STRING,
 JOIN_FROM_D DATE,
 JOIN_TO_D DATE,
 VALD_FROM_D DATE,
 VALD_TO_D DATE,
 EFFT_D DATE,
 EXPY_D DATE,
 SRCE_SYST_C STRING,
 PROS_KEY_I DECIMAL(10,0),
 ROW_SECU_ACCS_C INTEGER
);

/* PVTECH.DERV_PRTF_INT_GRUP_ENHC_PSST -> STARCADPRODDATA.DERV_PRTF_INT_GRUP_ENHC_PSST */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.DERV_PRTF_INT_GRUP_ENHC_PSST (
 INT_GRUP_I STRING,
 INT_GRUP_TYPE_C STRING,
 EFFT_D DATE,
 EXPY_D DATE,
 VALD_FROM_D DATE,
 VALD_TO_D DATE,
 PERD_D DATE,
 PTCL_N STRING,
 REL_MNGE_I STRING,
 ROW_N DECIMAL(10,0),
 PROS_KEY_I DECIMAL(10,0)
);

/* PVTECH.DERV_PRTF_INT_GRUP_OWN_PSST -> STARCADPRODDATA.DERV_PRTF_INT_GRUP_OWN_PSST */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.DERV_PRTF_INT_GRUP_OWN_PSST (
 INT_GRUP_I STRING,
 ROLE_PLAY_I STRING,
 EFFT_D DATE,
 EXPY_D DATE,
 VALD_FROM_D DATE,
 VALD_TO_D DATE,
 PERD_D DATE,
 ROLE_PLAY_TYPE_X STRING,
 DERV_PRTF_ROLE_C STRING,
 SRCE_SYST_C STRING,
 ROW_N DECIMAL(10,0),
 ROW_SECU_ACCS_C INTEGER,
 PROS_KEY_I DECIMAL(10,0)
);

/* PVTECH.DERV_PRTF_INT_HIST_PSST -> STARCADPRODDATA.DERV_PRTF_INT_HIST_PSST */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.DERV_PRTF_INT_HIST_PSST (
 INT_GRUP_I STRING,
 INT_GRUP_TYPE_C STRING,
 EFFT_D DATE,
 EXPY_D DATE,
 VALD_FROM_D DATE,
 VALD_TO_D DATE,
 JOIN_FROM_D DATE,
 JOIN_TO_D DATE,
 PTCL_N STRING,
 REL_MNGE_I STRING
);

/* PVTECH.DERV_PRTF_INT_PSST -> STARCADPRODDATA.DERV_PRTF_INT_PSST */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.DERV_PRTF_INT_PSST (
 INT_GRUP_I STRING,
 INT_GRUP_TYPE_C STRING,
 JOIN_FROM_D DATE,
 JOIN_TO_D DATE,
 EFFT_D DATE,
 EXPY_D DATE,
 PTCL_N STRING,
 REL_MNGE_I STRING,
 VALD_FROM_D DATE,
 VALD_TO_D DATE,
 PROS_KEY_I DECIMAL(10,0)
);

/* PVTECH.DERV_PRTF_OWN_HIST_PSST -> STARCADPRODDATA.DERV_PRTF_OWN_HIST_PSST */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.DERV_PRTF_OWN_HIST_PSST (
 INT_GRUP_I STRING,
 ROLE_PLAY_I STRING,
 JOIN_FROM_D DATE,
 JOIN_TO_D DATE,
 EFFT_D DATE,
 EXPY_D DATE,
 VALD_FROM_D DATE,
 VALD_TO_D DATE,
 ROLE_PLAY_TYPE_X STRING,
 DERV_PRTF_ROLE_C STRING,
 SRCE_SYST_C STRING,
 ROW_SECU_ACCS_C INTEGER,
 PROS_KEY_I DECIMAL(10,0)
);

/* PVTECH.DERV_PRTF_OWN_PSST -> STARCADPRODDATA.DERV_PRTF_OWN_PSST */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.DERV_PRTF_OWN_PSST (
 INT_GRUP_I STRING,
 JOIN_FROM_D DATE,
 JOIN_TO_D DATE,
 VALD_FROM_D DATE,
 VALD_TO_D DATE,
 EFFT_D DATE,
 EXPY_D DATE,
 DERV_PRTF_ROLE_C STRING,
 ROLE_PLAY_TYPE_X STRING,
 ROLE_PLAY_I STRING,
 SRCE_SYST_C STRING,
 ROW_SECU_ACCS_C INTEGER,
 PROS_KEY_I DECIMAL(10,0)
);

/* PVTECH.DERV_PRTF_PATY_HIST_PSST -> STARCADPRODDATA.DERV_PRTF_PATY_HIST_PSST */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.DERV_PRTF_PATY_HIST_PSST (
 INT_GRUP_I STRING,
 PATY_I STRING,
 REL_C STRING,
 JOIN_FROM_D DATE,
 JOIN_TO_D DATE,
 VALD_FROM_D DATE,
 VALD_TO_D DATE,
 EFFT_D DATE,
 EXPY_D DATE,
 SRCE_SYST_C STRING,
 ROW_SECU_ACCS_C INTEGER,
 PROS_KEY_I DECIMAL(10,0)
);

/* PVTECH.DERV_PRTF_PATY_INT_GRUP_PSST -> STARCADPRODDATA.DERV_PRTF_PATY_INT_GRUP_PSST */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.DERV_PRTF_PATY_INT_GRUP_PSST (
 INT_GRUP_I STRING,
 PATY_I STRING,
 EFFT_D DATE,
 EXPY_D DATE,
 VALD_FROM_D DATE,
 VALD_TO_D DATE,
 PERD_D DATE,
 REL_C STRING,
 SRCE_SYST_C STRING,
 ROW_N DECIMAL(10,0),
 ROW_SECU_ACCS_C INTEGER,
 PROS_KEY_I DECIMAL(10,0)
);

/* STAR_CAD_PROD_DATA.DERV_PRTF_ACCT_OWN_REL -> STARCADPRODDATA.DERV_PRTF_ACCT_OWN_REL */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.DERV_PRTF_ACCT_OWN_REL (
 ACCT_I STRING NOT NULL COMMENT 'Account Identifier',
 INT_GRUP_I STRING NOT NULL COMMENT 'Interest Group Identifier',
 DERV_PRTF_CATG_C STRING COMMENT 'Derived Portfolio Catgeory Code',
 DERV_PRTF_CLAS_C STRING COMMENT 'Derived Portfolio Class Code',
 DERV_PRTF_TYPE_C STRING COMMENT 'Derived Portfolio Type Code',
 PRTF_ACCT_VALD_FROM_D DATE COMMENT 'Portfolio Account Valid From Date',
 PRTF_ACCT_VALD_TO_D DATE COMMENT 'Portfolio Account Valid To Date',
 PRTF_ACCT_EFFT_D DATE COMMENT 'Portfolio Account Effective Date',
 PRTF_ACCT_EXPY_D DATE COMMENT 'Portfolio Account Expiry Date',
 PRTF_OWN_VALD_FROM_D DATE COMMENT 'Portfolio Owner Valid From Date',
 PRTF_OWN_VALD_TO_D DATE COMMENT 'Portfolio Owner Valid To Date',
 PRTF_OWN_EFFT_D DATE COMMENT 'Portfolio Owner Effective Date',
 PRTF_OWN_EXPY_D DATE COMMENT 'Portfolio Owner Expiry Date',
 PTCL_N INT COMMENT 'Point Of Control Number',
 REL_MNGE_I STRING COMMENT 'Relationship Manager Identifier',
 PRTF_CODE_X STRING COMMENT 'Portfolio Code Description',
 DERV_PRTF_ROLE_C STRING COMMENT 'Derived Portfolio Role Code',
 ROLE_PLAY_TYPE_X STRING COMMENT 'Role Player Type Description',
 ROLE_PLAY_I STRING NOT NULL COMMENT 'Role Player Identifier',
 SRCE_SYST_C STRING COMMENT 'Source System Code',
 ROW_SECU_ACCS_C INTEGER NOT NULL COMMENT 'Row Security Access Code'
);

/* STAR_CAD_PROD_DATA.DERV_PRTF_PATY_OWN_REL -> STARCADPRODDATA.DERV_PRTF_PATY_OWN_REL */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.DERV_PRTF_PATY_OWN_REL (
 PATY_I STRING NOT NULL COMMENT 'Party Identifier',
 INT_GRUP_I STRING NOT NULL COMMENT 'Interest Group Identifier',
 DERV_PRTF_CATG_C STRING COMMENT 'Derived Portfolio Category Code',
 DERV_PRTF_CLAS_C STRING COMMENT 'Derived Portfolio Class Code',
 DERV_PRTF_TYPE_C STRING COMMENT 'Derived Portfolio Type Code',
 PRTF_PATY_VALD_FROM_D DATE COMMENT 'Portfolio Party Valid From Date',
 PRTF_PATY_VALD_TO_D DATE COMMENT 'Portfolio Party Valid To Date',
 PRTF_PATY_EFFT_D DATE COMMENT 'Portfolio Party Effective Date',
 PRTF_PATY_EXPY_D DATE COMMENT 'Portfolio Party Expiry Date',
 PRTF_OWN_VALD_FROM_D DATE COMMENT 'Portfolio Owner Valid From Date',
 PRTF_OWN_VALD_TO_D DATE COMMENT 'Portfolio Owner Valid To Date',
 PRTF_OWN_EFFT_D DATE COMMENT 'Portfolio Owner Effective Date',
 PRTF_OWN_EXPY_D DATE COMMENT 'Portfolio Owner Expiry Date',
 PTCL_N INT COMMENT 'Point Of Control Number',
 REL_MNGE_I STRING COMMENT 'Relationship Manager Identifier',
 PRTF_CODE_X STRING COMMENT 'Portfolio Code Description',
 DERV_PRTF_ROLE_C STRING COMMENT 'Derived Portfolio Role Code',
 ROLE_PLAY_TYPE_X STRING COMMENT 'Role Player Type Description',
 ROLE_PLAY_I STRING NOT NULL COMMENT 'Role Player Identifier',
 SRCE_SYST_C STRING COMMENT 'Source System Code',
 ROW_SECU_ACCS_C INTEGER NOT NULL COMMENT 'Row Security Access Code'
);




/* PVTECH.ACCT_INT_GRUP -> PP01STARCADPRODDATA.ACCT_INT_GRUP */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **

CREATE ICEBERG TABLE NPD_D12_DMN_GDWMIG_IBRG.PP01STARCADPRODDATA.ACCT_INT_GRUP (
 ACCT_I STRING NOT NULL COMMENT 'Account Identifier',
 INT_GRUP_I STRING NOT NULL COMMENT 'Interest Group Identifier',
 REL_C STRING NOT NULL COMMENT 'Relationship Code',
 SRCE_SYST_C STRING COMMENT 'Source System Code',
 VALD_FROM_D DATE COMMENT 'Valid From Date',
 VALD_TO_D DATE COMMENT 'Valid To Date',
 EFFT_D DATE NOT NULL COMMENT 'Effective Date',
 EXPY_D DATE NOT NULL COMMENT 'Expiry Date',
 PROS_KEY_EFFT_I DECIMAL(10,0) NOT NULL COMMENT 'Process Key Effective Identifier',
 PROS_KEY_EXPY_I DECIMAL(10,0) COMMENT 'Process Key Expiry Identifier',
 ROW_SECU_ACCS_C INTEGER NOT NULL COMMENT 'Row Security Access Code'
);


/* PDDSTG.ACCT_REL_HLS_REME -> PDCBSTG.ACCT_REL_HLS_REME */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE NPD_D12_DMN_GDWMIG_IBRG.PDCBSTG.ACCT_REL_HLS_REME (
 SUBJ_ACCT_I STRING,
 OBJC_ACCT_I STRING,
 OBJC_BDT_APPT STRING,
 VALD_FROM TIMESTAMP(6),
 ACTL_VALD_END TIMESTAMP(6),
 REL_C STRING,
 MIRR_REL_C STRING,
 CTCT_STUS STRING,
 INTR_CNCT_NUMB_OF_MAIN_CNCT STRING,
 HIER_ID STRING,
 CNCT_CATG STRING,
 RUN_STRM_PROS_D DATE,
 OBJC_ACCT_LEVL_N INTEGER,
 SUBJ_ACCT_LEVL_N INTEGER,
 TGT_EFFT_D DATE,
 FLG STRING
);

/* PDDSTG.ACCT_REL_HLS_REME_HIST -> PDCBSTG.ACCT_REL_HLS_REME_HIST */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE NPD_D12_DMN_GDWMIG_IBRG.PDCBSTG.ACCT_REL_HLS_REME_HIST (
 SUBJ_ACCT_I STRING,
 OBJC_ACCT_I STRING,
 OBJC_BDT_APPT STRING,
 VALD_FROM TIMESTAMP(6),
 ACTL_VALD_END TIMESTAMP(6),
 REL_C STRING,
 MIRR_REL_C STRING,
 CTCT_STUS STRING,
 INTR_CNCT_NUMB_OF_MAIN_CNCT STRING,
 HIER_ID STRING,
 CNCT_CATG STRING,
 RUN_STRM_PROS_D DATE,
 OBJC_ACCT_LEVL_N INTEGER,
 SUBJ_ACCT_LEVL_N INTEGER,
 TGT_EFFT_D DATE,
 FLG STRING,
 LOAD_DATE DATE NOT NULL
);

/* PDDSTG.UTIL_PROS_SAP_RUN -> PDCBSTG.UTIL_PROS_SAP_RUN */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE NPD_D12_DMN_GDWMIG_IBRG.PDCBSTG.UTIL_PROS_SAP_RUN (
 RUN_DATE DATE,
 PROS_KEY_EFFT_I BIGINT
 -- ,
--  (START STRING,
--  INCREMENT STRING,
--  MINVALUE STRING,
--  MAXVALUE STRING,
--  NO STRING,
--  RECD_CNT INTEGER
)
;


/* PVTECH.DERV_PRTF_ACCT_HIST_PSST -> UDTDWRK.DERV_PRTF_ACCT_HIST_PSST */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE NPD_D12_DMN_GDWMIG_IBRG.UDTDWRK.DERV_PRTF_ACCT_HIST_PSST (
 INT_GRUP_I STRING,
 ACCT_I STRING,
 REL_C STRING,
 JOIN_FROM_D DATE,
 JOIN_TO_D DATE,
 VALD_FROM_D DATE,
 VALD_TO_D DATE,
 EFFT_D DATE,
 EXPY_D DATE,
 SRCE_SYST_C STRING,
 ROW_SECU_ACCS_C INTEGER
);

/* PVTECH.DERV_PRTF_INT_PSST -> PTEMP.DERV_PRTF_INT_PSST */
--** SSC-FDM-TD0024 - SET TABLE FUNCTIONALITY NOT SUPPORTED. TABLE MIGHT HAVE DUPLICATE ROWS **
--** CONVERTED TO ICEBERG TABLE FORMAT **
CREATE ICEBERG TABLE NPD_D12_DMN_GDWMIG_IBRG.PTEMP.DERV_PRTF_INT_PSST (
 INT_GRUP_I STRING,
 INT_GRUP_TYPE_C STRING,
 JOIN_FROM_D DATE,
 JOIN_TO_D DATE,
 EFFT_D DATE,
 EXPY_D DATE,
 PTCL_N STRING,
 REL_MNGE_I STRING,
 VALD_FROM_D DATE,
 VALD_TO_D DATE,
 PROS_KEY_I DECIMAL(10,0)
);




CREATE ICEBERG TABLE NPD_D12_DMN_GDWMIG_IBRG.STARCADPRODDATA.ACCT_BALN (
ACCT_I STRING NOT NULL COMMENT 'Account Identifier',
BALN_TYPE_C STRING NOT NULL COMMENT 'Balance Type Code',
CALC_FUNC_C STRING NOT NULL COMMENT 'Calculation Function Code',
TIME_PERD_C STRING NOT NULL COMMENT 'Time Period Code',
EFFT_D DATE NOT NULL COMMENT 'Effective Date',
EXPY_D DATE NOT NULL COMMENT 'Expire Date',
BALN_A DECIMAL(23,5) COMMENT 'Balance Amount',
CALC_F STRING NOT NULL COMMENT 'Calculate Flag',
PROS_KEY_EFFT_I DECIMAL(10,0) COMMENT 'Process Key Effective Identifier',
PROS_KEY_EXPY_I DECIMAL(10,0) COMMENT 'Process Key Expire Identifier',
EROR_SEQN_I DECIMAL(10,0) COMMENT 'Error Sequence Identifier',
CNCY_C STRING COMMENT 'Currency Code',
SRCE_SYST_C STRING COMMENT 'Source System Code',
ROW_SECU_ACCS_C INTEGER NOT NULL COMMENT 'Row Security Access Code'
);