{{ config(materialized='view', tags=['LdREJT_CSE_COM_BUS_APP_PROD_CLIENT_ROLE']) }}

WITH FunJnlIdNulls AS (
	SELECT
		APP_PROD_CLIENT_ROLE_ID as APP_PROD_CLIENT_ROLE_ID,
		ROLE_CAT_ID as ROLE_CAT_ID,
		CIF_CODE as CIF_CODE,
		APP_PROD_ID as APP_PROD_ID,
		SUBTYPE_CODE as SUBTYPE_CODE,
		ETL_D as ETL_D,
		ORIG_ETL_D as ORIG_ETL_D,
		EROR_C as EROR_C
	FROM {{ ref('SrcRejJnlIdNullsDS') }}
	UNION ALL
	SELECT
		APP_PROD_CLIENT_ROLE_ID,
		ROLE_CAT_ID,
		CIF_CODE,
		APP_PROD_ID,
		SUBTYPE_CODE,
		ETL_D,
		ORIG_ETL_D,
		EROR_C
	FROM {{ ref('SrcMappingRejectsDS') }}
)

SELECT * FROM FunJnlIdNulls