{{ config(materialized='view', tags=['XfmEvntRel']) }}

WITH Funnel AS (
	SELECT
		MOD_TIMESTAMP as MOD_TIMESTAMP,
		OL_CLIENT_RM_RATING_ID as OL_CLIENT_RM_RATING_ID,
		CLIENT_ID as CLIENT_ID,
		CIF_CODE as CIF_CODE,
		OU_ID as OU_ID,
		CS_USER_ID as CS_USER_ID,
		RATING as RATING,
		WIM_PROCESS_ID as WIM_PROCESS_ID
	FROM {{ ref('REJT_EVNT_REL') }}
	UNION ALL
	SELECT
		MOD_TIMESTAMP,
		OL_CLIENT_RM_RATING_ID,
		CLIENT_ID,
		CIF_CODE,
		OU_ID,
		CS_USER_ID,
		RATING,
		WIM_PROCESS_ID
	FROM {{ ref('Copy_206') }}
)

SELECT * FROM Funnel