{{ config(materialized='view', tags=['XfmEvntRel']) }}

WITH Rem_Dup AS (
	SELECT MOD_TIMESTAMP, OL_CLIENT_RM_RATING_ID, CLIENT_ID, CIF_CODE, OU_ID, CS_USER_ID, RATING, WIM_PROCESS_ID 
	FROM (
		SELECT MOD_TIMESTAMP, OL_CLIENT_RM_RATING_ID, CLIENT_ID, CIF_CODE, OU_ID, CS_USER_ID, RATING, WIM_PROCESS_ID,
		 ROW_NUMBER() OVER (PARTITION BY OL_CLIENT_RM_RATING_ID ORDER BY 1 ASC) AS ROW_NUM 
		FROM {{ ref('Sort') }}
	) AS Rem_Dup_TEMP
	WHERE ROW_NUM = 1
)

SELECT * FROM Rem_Dup