{{ config(materialized='view', tags=['XfmHL_APPFrmExt_NEW']) }}

WITH Com_FOIN_FHB AS (
	SELECT
		APPT_I as APPT_I,
		APPT_ATTR_CLAS_C as APPT_ATTR_CLAS_C,
		APPT_ATTR_CLAS_VALU_C as APPT_ATTR_CLAS_VALU_C,
		EFFT_D as SRCE_SYST_C,
		SRCE_SYST_C as EFFT_D,
		EXPY_D as EXPY_D,
		PROS_KEY_EFFT_I as PROS_KEY_EFFT_I,
		PROS_KEY_EXPY_I as PROS_KEY_EXPY_I,
		ROW_SECU_ACCS_C as ROW_SECU_ACCS_C
	FROM {{ ref('DeDup_CseApptAttrClasAssc') }}
	UNION ALL
	SELECT
		APPT_I,
		APPT_ATTR_CLAS_C,
		APPT_ATTR_CLAS_VALU_C,
		SRCE_SYST_C,
		EFFT_D,
		EXPY_D,
		PROS_KEY_EFFT_I,
		PROS_KEY_EXPY_I,
		ROW_SECU_ACCS_C
	FROM {{ ref('DeDup_CseApptAttrClasFoin') }}
)

SELECT * FROM Com_FOIN_FHB