{{ config(materialized='view', tags=['XfmHL_APPFrmExt_NEW']) }}

WITH Com_N_Y_NULL AS (
	SELECT
		APPT_I as APPT_I,
		APPT_ATTR_CLAS_C as APPT_ATTR_CLAS_C,
		APPT_ATTR_CLAS_VALU_C as APPT_ATTR_CLAS_VALU_C,
		SRCE_SYST_C as SRCE_SYST_C,
		EFFT_D as EFFT_D,
		EXPY_D as EXPY_D,
		PROS_KEY_EFFT_I as PROS_KEY_EFFT_I,
		PROS_KEY_EXPY_I as PROS_KEY_EXPY_I,
		ROW_SECU_ACCS_C as ROW_SECU_ACCS_C
	FROM {{ ref('FOIN_NULL_N') }}
	UNION ALL
	SELECT
		APPT_I,
		APPT_ATTR_CLAS_C,
		APPT_ATTR_CLAS_VALU_C,
		SRCE_SYST_C,
		EFFT_D,
		EXPY_D,
		PROS_KEY_EFFT_I,
		PROS_KEY_EXPY_I,
		ROW_SECU_ACCS_C
	FROM {{ ref('FOIN_Y') }}
)

SELECT * FROM Com_N_Y_NULL