{{ config(materialized='view', tags=['XfmHL_APPFrmExt_NEW']) }}

WITH DeDup_CseApptAttrClasAssc AS (
	SELECT APPT_I, APPT_ATTR_CLAS_C, APPT_ATTR_CLAS_VALU_C, EFFT_D, SRCE_SYST_C, EXPY_D, PROS_KEY_EFFT_I, PROS_KEY_EXPY_I, ROW_SECU_ACCS_C 
	FROM (
		SELECT APPT_I, APPT_ATTR_CLAS_C, APPT_ATTR_CLAS_VALU_C, EFFT_D, SRCE_SYST_C, EXPY_D, PROS_KEY_EFFT_I, PROS_KEY_EXPY_I, ROW_SECU_ACCS_C,
		 ROW_NUMBER() OVER (PARTITION BY APPT_I ORDER BY 1 ASC) AS ROW_NUM 
		FROM {{ ref('XfmBusinessRules__OutTmpCseApptAttrClasAssc') }}
	) AS DeDup_CseApptAttrClasAssc_TEMP
	WHERE ROW_NUM = 1
)

SELECT * FROM DeDup_CseApptAttrClasAssc