{{ config(materialized='view', tags=['ExtCSE_CHL_BUS_TU_APP_FUND_DET']) }}

WITH FunMergeJournal AS (
	SELECT
		TU_APP_ID as TU_APP_ID,
		FUNDING_DATE as FUNDING_DATE,
		TU_APP_FUNDING_DETAIL_ID as TU_APP_FUNDING_DETAIL_ID,
		TU_APP_FUNDING_ID as TU_APP_FUNDING_ID,
		FUNDING_CBA_ACCOUNT_ID as FUNDING_CBA_ACCOUNT_ID,
		FUNDING_NONCBA_BANK_NUMBER as FUNDING_NONCBA_BANK_NUMBER,
		FUNDING_NONCBA_INST_NAME as FUNDING_NONCBA_INST_NAME,
		FUNDING_NONCBA_INST_ADDRESS as FUNDING_NONCBA_INST_ADDRESS,
		FUNDING_NONCBA_BSB as FUNDING_NONCBA_BSB,
		FUNDING_NONCBA_ACCOUNT_NUMBER as FUNDING_NONCBA_ACCOUNT_NUMBER,
		FUNDING_NONCBA_ACCOUNT_NAME as FUNDING_NONCBA_ACCOUNT_NAME,
		FUNDING_BANKCHEQUE_NUMBER as FUNDING_BANKCHEQUE_NUMBER,
		FUNDING_BANKCHEQUE_PAYEE as FUNDING_BANKCHEQUE_PAYEE,
		FUNDING_METHOD_CAT_ID as FUNDING_METHOD_CAT_ID,
		FUNDING_BANKCHEQUE_CBAACCOUNT as FUNDING_BANKCHEQUE_CBAACCOUNT,
		PROGRESSIVE_PAYMENT_AMT as PROGRESSIVE_PAYMENT_AMT,
		SBTY_CODE as SBTY_CODE,
		HL_APP_PROD_ID as HL_APP_PROD_ID,
		ORIG_ETL_D as ORIG_ETL_D
	FROM {{ ref('XfmSeparateRejectWithoutSourceAndTheRest__InSourceRec') }}
	UNION ALL
	SELECT
		TU_APP_ID,
		FUNDING_DATE,
		TU_APP_FUNDING_DETAIL_ID,
		TU_APP_FUNDING_ID,
		FUNDING_CBA_ACCOUNT_ID,
		FUNDING_NONCBA_BANK_NUMBER,
		FUNDING_NONCBA_INST_NAME,
		FUNDING_NONCBA_INST_ADDRESS,
		FUNDING_NONCBA_BSB,
		FUNDING_NONCBA_ACCOUNT_NUMBER,
		FUNDING_NONCBA_ACCOUNT_NAME,
		FUNDING_BANKCHEQUE_NUMBER,
		FUNDING_BANKCHEQUE_PAYEE,
		FUNDING_METHOD_CAT_ID,
		FUNDING_BANKCHEQUE_CBAACCOUNT,
		PROGRESSIVE_PAYMENT_AMT,
		SBTY_CODE,
		HL_APP_PROD_ID,
		ORIG_ETL_D
	FROM {{ ref('XfmSeparateRejectWithoutSourceAndTheRest__InRejectWithoutSourceRec') }}
)

SELECT * FROM FunMergeJournal