{{ config(materialized='view', tags=['ExtCSE_CHL_BUS_TU_APP_FUND_DET']) }}

WITH XfmSeparateRejectWithoutSourceAndTheRest__InSourceRec AS (
	SELECT
		-- *SRC*: \(20)If (Len(Trim(( IF IsNotNull((XfmSeparateRejects.TU_APP_FUNDING_DETAIL_ID)) THEN (XfmSeparateRejects.TU_APP_FUNDING_DETAIL_ID) ELSE ""))) = 0) Then 'R' Else 'S',
		IFF(LEN(TRIM(IFF({{ ref('JoinSrcSortReject') }}.TU_APP_FUNDING_DETAIL_ID IS NOT NULL, {{ ref('JoinSrcSortReject') }}.TU_APP_FUNDING_DETAIL_ID, ''))) = 0, 'R', 'S') AS DeltaFlag,
		TU_APP_ID,
		FUNDING_DATE,
		TU_APP_FUNDING_DETAIL_ID,
		TU_APP_FUNDING_ID,
		FUNDING_CBA_ACCOUNT_ID,
		FUNDING_NONCBA_BANK_NUMBER,
		FUNDING_NONCBA_INST_NAME,
		FUNDING_NONCBA_INST_ADDRESS,
		FUNDING_NONCBA_BSB,
		FUNDING_NONCBA_ACCOUNT_NUMBER,
		FUNDING_NONCBA_ACCOUNT_NAME,
		FUNDING_BANKCHEQUE_NUMBER,
		FUNDING_BANKCHEQUE_PAYEE,
		FUNDING_METHOD_CAT_ID,
		FUNDING_BANKCHEQUE_CBAACCOUNT,
		PROGRESSIVE_PAYMENT_AMT,
		SBTY_CODE,
		HL_APP_PROD_ID,
		ETL_PROCESS_DT AS ORIG_ETL_D
	FROM {{ ref('JoinSrcSortReject') }}
	WHERE DeltaFlag = 'S'
)

SELECT * FROM XfmSeparateRejectWithoutSourceAndTheRest__InSourceRec