{{ config(materialized='view', tags=['XfmDelFlagAPPT_PDCT_ACCT']) }}

WITH XfmProsKey AS (
	SELECT
		DELETED_TABLE_NAME,
		{{ ref('SrcAppPdctAcctDS') }}.DELETED_KEY_1_VALUE AS APP_PROD_ID,
		-- *SRC*: \(20)If OutAppPdctAcctDS.DELETED_TABLE_NAME = 'CCL_APP_PROD' Then 'CSE_CCL_BUS_APP_PROD_APPT_PDCT_ACCT' Else ( If OutAppPdctAcctDS.DELETED_TABLE_NAME = 'HL_APP_PROD' Then 'CSE_CHL_BUS_APP_PROD_APPT_PDCT_ACCT' Else ( If OutAppPdctAcctDS.DELETED_TABLE_NAME = 'PL_APP_PROD' Then 'CSE_CPL_BUS_APP_PROD_APPT_PDCT_ACCT' Else ( If OutAppPdctAcctDS.DELETED_TABLE_NAME = 'CC_APP_PROD' Then 'CSE_CCC_BUS_APP_PROD_APPT_PDCT_ACCT' Else ''))),
		IFF(
	    {{ ref('SrcAppPdctAcctDS') }}.DELETED_TABLE_NAME = 'CCL_APP_PROD', 'CSE_CCL_BUS_APP_PROD_APPT_PDCT_ACCT',     
	    IFF(
	        {{ ref('SrcAppPdctAcctDS') }}.DELETED_TABLE_NAME = 'HL_APP_PROD', 'CSE_CHL_BUS_APP_PROD_APPT_PDCT_ACCT', 
	        IFF({{ ref('SrcAppPdctAcctDS') }}.DELETED_TABLE_NAME = 'PL_APP_PROD', 'CSE_CPL_BUS_APP_PROD_APPT_PDCT_ACCT', IFF({{ ref('SrcAppPdctAcctDS') }}.DELETED_TABLE_NAME = 'CC_APP_PROD', 'CSE_CCC_BUS_APP_PROD_APPT_PDCT_ACCT', ''))
	    )
	) AS CONV_M
	FROM {{ ref('SrcAppPdctAcctDS') }}
	WHERE 
)

SELECT * FROM XfmProsKey