{{ config(materialized='view', tags=['LdREJT_CCL_APP_FEE_CCL_FEE_TYPE_CAT']) }}

WITH FunCCL_APP_FEE_IDNulls AS (
	SELECT
		CCL_APP_FEE_ID as CCL_APP_FEE_ID,
		CCL_APP_FEE_CCL_APP_ID as CCL_APP_FEE_CCL_APP_ID,
		CCL_APP_FEE_CCL_APP_PROD_ID as CCL_APP_FEE_CCL_APP_PROD_ID,
		CCL_APP_FEE_CHARGE_AMT as CCL_APP_FEE_CHARGE_AMT,
		CCL_APP_FEE_CHARGE_DATE as CCL_APP_FEE_CHARGE_DATE,
		CCL_APP_FEE_CONCESSION_FLAG as CCL_APP_FEE_CONCESSION_FLAG,
		CCL_APP_FEE_CONCESSION_REASON as CCL_APP_FEE_CONCESSION_REASON,
		CCL_APP_FEE_OVERRIDE_FEE_PCT as CCL_APP_FEE_OVRRD_FEE_PCT,
		CCL_APP_FEE_OVERRIDE_FEE_PCT_FREQ as CCL_APP_FEE_OVRRD_FEE_PCT_FREQ,
		CCL_APP_FEE_FEE_REPAYMENT_FREQ as CCL_APP_FEE_FEE_REPAYMENT_FREQ,
		CCL_APP_FEE_TYPE_CAT_ID as CCL_APP_FEE_TYPE_CAT_ID,
		CCL_APP_FEE_CHARGE_EXTERNAL_FLAG as CCL_APP_FEE_CHRGE_EXTERNL_FLAG,
		CCL_FEE_TYPE_CAT_ID as CCL_FEE_TYPE_CAT_ID,
		CCL_FEE_TYPE_CAT_DEFAULT_AMT as CCL_FEE_TYPE_CAT_DEFAULT_AMT,
		CCL_FEE_TYPE_CAT_DEFAULT_FEE_PCT as CCL_FEE_TYPE_CAT_DFLT_FEE_PCT,
		CCL_FEE_TYPE_CAT_FEE_TYPE_DESC as CCL_FEE_TYPE_CAT_FEE_TYPE_DESC,
		ETL_D as ETL_D,
		ORIG_ETL_D as ORIG_ETL_D,
		EROR_C as EROR_C
	FROM {{ ref('RejCCL_APP_FEE_IDNullsDS') }}
	UNION ALL
	SELECT
		CCL_APP_FEE_ID,
		CCL_APP_FEE_CCL_APP_ID,
		CCL_APP_FEE_CCL_APP_PROD_ID,
		CCL_APP_FEE_CHARGE_AMT,
		CCL_APP_FEE_CHARGE_DATE,
		CCL_APP_FEE_CONCESSION_FLAG,
		CCL_APP_FEE_CONCESSION_REASON,
		CCL_APP_FEE_OVERRIDE_FEE_PCT,
		CCL_APP_FEE_OVERRIDE_FEE_PCT_FREQ,
		CCL_APP_FEE_FEE_REPAYMENT_FREQ,
		CCL_APP_FEE_TYPE_CAT_ID,
		CCL_APP_FEE_CHARGE_EXTERNAL_FLAG,
		CCL_FEE_TYPE_CAT_ID,
		CCL_FEE_TYPE_CAT_DEFAULT_AMT,
		CCL_FEE_TYPE_CAT_DEFAULT_FEE_PCT,
		CCL_FEE_TYPE_CAT_FEE_TYPE_DESC,
		ETL_D,
		ORIG_ETL_D,
		EROR_C
	FROM {{ ref('SrcCCL_APP_FEE_CCL_FEE_TYPE_CATRejectsDS') }}
)

SELECT * FROM FunCCL_APP_FEE_IDNulls