{{ config(materialized='view', tags=['DltAPPT_ASET_SETL_LOCNFrmTMP_APPT_ASET_SETL_LOCN']) }}

WITH 
tmp_appt_aset_setl_locn AS (
	SELECT
	*
	FROM {{ ref("tmp_appt_aset_setl_locn")  }}),
appt_aset_setl_locn AS (
	SELECT
	*
	FROM {{ ref("appt_aset_setl_locn")  }}),
SrcTmpApptAsetSetlLocnTera AS (SELECT A.APPT_I AS NEW_APPT_I, A.ASET_I AS NEW_ASET_I, A.FRWD_DOCU_C AS NEW_FRWD_DOCU_C, A.SETL_LOCN_X AS NEW_SETL_LOCN_X, A.SETL_CMMT_X AS NEW_SETL_CMMT_X, B.APPT_I AS OLD_APPT_I, B.ASET_I AS OLD_ASET_I, B.FRWD_DOCU_C AS OLD_FRWD_DOCU_C, B.SETL_LOCN_X AS OLD_SETL_LOCN_X, B.SETL_CMMT_X AS OLD_SETL_CMMT_X, B.EFFT_D AS OLD_EFFT_D FROM TMP_APPT_ASET_SETL_LOCN LEFT OUTER JOIN APPT_ASET_SETL_LOCN ON a.APPT_I = b.APPT_I AND a.ASET_I = b.ASET_I AND b.EXPY_D = '9999-12-31' AND b.SRCE_SYST_C = 'CSE' WHERE a.RUN_STRM = '{{ var("RUN_STREAM") }}')


SELECT * FROM SrcTmpApptAsetSetlLocnTera