CREATE OR REPLACE PROCEDURE PS_GDW1_BTEQ.BTEQ_SPS.DERV_ACCT_PATY_05_SET_PRTF_PRFR_FLAG_PROC(
  EXTR_DATE STRING DEFAULT '2024-01-01'
)
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
  error_code INTEGER DEFAULT 0;
  row_count INTEGER DEFAULT 0;
  total_rows INTEGER DEFAULT 0;
BEGIN
  -- Set preferred party flag for accounts with same RM for account and party
  -- Based on portfolio management and fund holder relationships
  
  -- Step 1: Clear staging table and populate with portfolio account party data
  DELETE FROM PS_CLD_RW.PDDSTG.DERV_PRTF_ACCT_PATY_PSST;
  
  INSERT INTO PS_CLD_RW.PDDSTG.DERV_PRTF_ACCT_PATY_PSST
  SELECT 
    DAP.ASSC_ACCT_I,
    DAP.PATY_I,
    DPAS.PRTF_CODE_X AS ACCT_PRTF_C,
    NULL AS PATY_PRTF_C,
    DAP.PATY_ACCT_REL_C,
    99 AS RANK_I
  FROM PS_CLD_RW.PDDSTG.DERV_ACCT_PATY_CURR DAP
  JOIN PS_CLD_RW.PDDSTG.GRD_GNRC_MAP_DERV_PATY_HOLD AHR
    ON DAP.PATY_ACCT_REL_C = AHR.PATY_ACCT_REL_C
  JOIN PS_CLD_RW.PDDSTG.DERV_PRTF_ACCT_STAG DPAS
    ON DAP.ASSC_ACCT_I = DPAS.ACCT_I
  WHERE DPAS.PRTF_CODE_X <> 'NA'
    AND :EXTR_DATE BETWEEN DAP.EFFT_D AND DAP.EXPY_D
  GROUP BY 1,2,3,4,5,6;
  
  row_count := SQLROWCOUNT;
  total_rows := total_rows + row_count;
  
  -- Step 2: Update priority rankings for fund holder relationships
  UPDATE PS_CLD_RW.PDDSTG.DERV_PRTF_ACCT_PATY_PSST
  SET RANK_I = DRVD.PRTY
  FROM (
    SELECT DISTINCT 
      PIG.PATY_I,
      GDFVC.PRTY
    FROM PS_GDW1_BTEQ.PVDATA.PATY_INT_GRUP_CURR PIG
    INNER JOIN PS_GDW1_BTEQ.PVDATA.INT_GRUP_DEPT_CURR IGD
      ON IGD.INT_GRUP_I = PIG.INT_GRUP_I
      AND PIG.REL_C = 'RLMT'
    INNER JOIN (
      SELECT 
        GFC.DEPT_LEAF_NODE_C AS DEPT_I,
        ORU.PRTY
      FROM ps_gdw1_bteq.PVTECH.GRD_DEPT_FLAT_CURR GFC
      LEFT JOIN (
        SELECT 
          COALESCE(PRTY, 9999) AS PRTY,
          LKUP1_TEXT,
          COALESCE(UPDT_DTTS, CRAT_DTTS) AS LoadTimeStamp
        FROM ps_gdw1_bteq.PVTECH.ODS_RULE
        WHERE RULE_CODE = 'RMPOC'
          AND :EXTR_DATE BETWEEN VALD_FROM AND VALD_TO
        QUALIFY ROW_NUMBER() OVER (PARTITION BY LKUP1_TEXT, PRTY ORDER BY LoadTimeStamp DESC) = 1
      ) ORU ON GFC.DEPT_L3_NODE_C = ORU.LKUP1_TEXT
      WHERE PRTY <> 9999
    ) GDFVC ON GDFVC.DEPT_I = IGD.DEPT_I
    WHERE PIG.PATY_I IN (
      SELECT DISTINCT PATY_I 
      FROM PS_CLD_RW.PDDSTG.DERV_PRTF_ACCT_PATY_PSST
    )
    QUALIFY ROW_NUMBER() OVER (PARTITION BY PIG.PATY_I ORDER BY GDFVC.PRTY ASC) = 1
  ) DRVD
  WHERE DERV_PRTF_ACCT_PATY_PSST.PATY_I = DRVD.PATY_I
    AND DERV_PRTF_ACCT_PATY_PSST.PATY_ACCT_REL_C = 'ZINTE0';
  
  -- Step 3: Clear and populate final staging table with ranked data
  DELETE FROM PS_CLD_RW.PDDSTG.DERV_PRTF_ACCT_PATY_STAG;
  
  INSERT INTO PS_CLD_RW.PDDSTG.DERV_PRTF_ACCT_PATY_STAG
  SELECT 
    DAPP.ACCT_I,
    DAPP.PATY_I,
    DAPP.ACCT_PRTF_C,
    DPPS.PRTF_CODE_X AS PATY_PRTF_C,
    DAPP.PATY_ACCT_REL_C,
    CASE 
      WHEN DAPP.RANK_I <> 99 AND DAPP.PATY_ACCT_REL_C = 'ZINTE0' THEN DAPP.RANK_I
      WHEN DAPP.PATY_ACCT_REL_C = 'ZINTE0' THEN 98
      ELSE 99
    END AS RANK_I
  FROM PS_CLD_RW.PDDSTG.DERV_PRTF_ACCT_PATY_PSST DAPP
  JOIN PS_CLD_RW.PDDSTG.DERV_PRTF_PATY_STAG DPPS
    ON DAPP.PATY_I = DPPS.PATY_I
    AND (DPPS.PRTF_CODE_X = DAPP.ACCT_PRTF_C OR DAPP.PATY_ACCT_REL_C = 'ZINTE0')
    AND DPPS.PRTF_CODE_X <> 'NA';
  
  -- Step 4: Remove duplicate records based on ranking
  DELETE FROM PS_CLD_RW.PDDSTG.DERV_PRTF_ACCT_PATY_STAG
  WHERE (ACCT_I, RANK_I, PATY_I) IN (
    SELECT ACCT_I, RANK_I, PATY_I
    FROM (
      SELECT 
        ACCT_I,
        RANK_I,
        PATY_I
      FROM PS_CLD_RW.PDDSTG.DERV_PRTF_ACCT_PATY_STAG
      QUALIFY ROW_NUMBER() OVER (PARTITION BY ACCT_I ORDER BY RANK_I ASC, PATY_I DESC) > 1
    ) DRVD
  );
  
  -- Step 5: Populate RM working table
  DELETE FROM PS_CLD_RW.PDDSTG.DERV_ACCT_PATY_RM;
  
  INSERT INTO PS_CLD_RW.PDDSTG.DERV_ACCT_PATY_RM
  SELECT 
    DAP.ACCT_I,
    DAP.PATY_I,
    DAP.ASSC_ACCT_I,
    DAP.PATY_ACCT_REL_C,
    DAP.PRFR_PATY_F,
    DAP.SRCE_SYST_C,
    DAP.EFFT_D,
    DAP.EXPY_D,
    DAP.ROW_SECU_ACCS_C
  FROM PS_CLD_RW.PDDSTG.DERV_ACCT_PATY_CURR DAP
  JOIN PS_CLD_RW.PDDSTG.DERV_PRTF_ACCT_PATY_STAG T1
    ON DAP.ASSC_ACCT_I = T1.ACCT_I
  WHERE :EXTR_DATE BETWEEN DAP.EFFT_D AND DAP.EXPY_D;
  
  row_count := SQLROWCOUNT;
  total_rows := total_rows + row_count;
  
  -- Step 6: Set preferred party flag for identified account/party combinations
  UPDATE PS_CLD_RW.PDDSTG.DERV_ACCT_PATY_RM
  SET PRFR_PATY_F = 'Y'
  WHERE (ACCT_I, PATY_I, PATY_ACCT_REL_C, EFFT_D, EXPY_D) IN (
    SELECT 
      T1.ACCT_I,
      T1.PATY_I,
      T1.PATY_ACCT_REL_C,
      T1.EFFT_D,
      T1.EXPY_D
    FROM PS_CLD_RW.PDDSTG.DERV_ACCT_PATY_RM T1
    JOIN PS_CLD_RW.PDDSTG.GRD_GNRC_MAP_DERV_PATY_HOLD T2
      ON T1.PATY_ACCT_REL_C = T2.PATY_ACCT_REL_C
    JOIN PS_CLD_RW.PDDSTG.DERV_PRTF_ACCT_PATY_STAG T4
      ON T1.ASSC_ACCT_I = T4.ACCT_I
      AND T1.PATY_I = T4.PATY_I
      AND T1.PATY_ACCT_REL_C = T4.PATY_ACCT_REL_C
    WHERE :EXTR_DATE BETWEEN T1.EFFT_D AND T1.EXPY_D
    QUALIFY ROW_NUMBER() OVER (PARTITION BY T1.ACCT_I ORDER BY T4.RANK_I, T1.EFFT_D, T1.PATY_ACCT_REL_C, T4.PATY_I DESC) = 1
  );
  
  row_count := SQLROWCOUNT;
  total_rows := total_rows + row_count;
  
  RETURN 'SUCCESS: Portfolio preferred party flags set. Total rows processed: ' || :total_rows;
  
EXCEPTION
  WHEN OTHER THEN
    RETURN 'ERROR: ' || SQLERRM || ' (Code: ' || SQLCODE || ')';
END;
$$;