{{ config(materialized='view', tags=['XfmAppProdCclAppProdPlAppProdFrmExt']) }}

WITH ModNullHandling AS (
	SELECT 
	--Manual
	--LOAN_FNDD_METH_C: string[4]= handle_null (LOAN_FNDD_METH_C, '9999')
	--ACQR_SRCE_C:nullable string[4] = handle_null (ACQR_SRCE_C, '9999')
	--ACQR_TYPE_C: string[4]= handle_null (ACQR_TYPE_C, '9999')
	--JOB_COMM_CATG_C: string[4]= handle_null (JOB_COMM_CATG_C, '9999')
	--CLP_FOUND_FLAG : string[1]= handle_null (CLP_FOUND_FLAG , 'N')
	APP_PROD_ID, CLP_JOB_FAMILY_CAT_ID, JOB_COMM_CATG_C, CCL_APP_PROD_ID, CCL_PARENT_CCL_APP_PROD_ID, CCL_ACCOUNT_NUMBER, CCL_ACTUAL_RATE, CCL_BALLOON_PAY_AMT, CCL_BASIS_TYPE_CAT_ID, CCL_INTEREST_RATE_MARGIN, CCL_LOAN_TERM_MTH_NUM, CCL_CURRENT_LIMIT, CCL_INC_DEC_AMT, CCL_POST_APP_AMT, CCL_NEW_PROD_FLAG, CCL_INDEX_RATE, CCL_INTEREST_ADV_FLAG, CCL_INTERESTONLY_TERM_MTH_NUM, CCL_CAPPED_TERM_MTH_NUM, CCL_CAPPED_RATE, CCL_CRIS_PRODUCT_ID, CCL_CCL_LOAN_PURPOSE_ID, CCL_NEW_PROD_SUBTYPE_FLAG, CCL_TEMP_EXCESS_MTHS, CCL_LOAN_PURPOSE_CLASS_CODE, CCL_CCL_INTEREST_RATE_CAT_ID, CCL_CRR, CCL_AD_TUC_INC_AMT, CCL_CCL_RATE_TYPE_CAT_ID, CCL_LINK_CCL_APP_ID, CCL_LINK_CCL_APP_PROD_ID, CCL_CHL_LMI_AMT, CCL_USED_IN_EXPOSURE_VIEW_FLAG, CCL_CCL_APP_BROKER_CIF_CODE, CCL_APP_ID, CCL_FIXED_INT_START_DATE, CCL_CHILD_PDCT_LEVEL_CAT_ID, CCL_PARENT_PDCT_LEVEL_CAT_ID, CPL_APP_PROD_ID, PL_TARG_CAT_ID, CPL_REPAY_APPROX_AMT, CPL_REPAY_FREQUENCY_ID, CPL_PL_APP_PROD_REPAY_CAT_ID, CPL_PL_PROD_TERM_CAT_ID, PL_CMPN_CAT_ID, CPL_AD_HOC_CAMPAIGN_DESC, CPL_CAR_SEEKER_FLAG, CPL_PL_PROD_TARGET_CAT_ID, PL_MRKT_SRCE_CAT_ID, CPL_HLS_ACCT_NO, CPL_TOTAL_INTEREST_AMT, CPL_APP_PROD_AMT, CPL_TP_BROKER_ID, CPL_TP_BROKER_FIRST_NAME, CPL_TP_BROKER_LAST_NAME, CPL_TP_BROKER_GROUP_CAT_ID, COM_APP_PROD_ID, SBTY_CODE, COM_APP_ID, COM_PRODUCT_TYPE_ID, COM_SM_CASE_ID, COM_FOUND_FLAG, CPL_FOUND_FLAG, CCL_FOUND_FLAG, CLP_FOUND_FLAG, CC_FOUND_FLAG, CC_APP_PROD_ID, CCHL_APP_PROD_ID, ABN, BUSINESS_NAME, SIMPLE_APP_FLAG, CHL_FOUND_FLAG, ORIG_ETL_D, APPT_QLFY_C, LOAN_FNDD_METH_C, ACQR_SRCE_C, ACQR_TYPE_C, CHL_CR_DATE, CHL_ASSESSMENT_DATE, CHL_NCPR_FLAG 
	FROM {{ ref('LkpReferences') }}
)

SELECT * FROM ModNullHandling