{{ config(materialized='view', tags=['LdREJT_RT_PERC_PROD_INT_MARG']) }}

WITH FunRejects AS (
	SELECT
		HL_INT_RATE_ID as HL_INT_RATE_ID,
		RATE_HL_INT_RATE_ID as RATE_HL_INT_RATE_ID,
		RATE_HL_APP_PROD_ID as RATE_HL_APP_PROD_ID,
		RATE_CASS_INT_RATE_TYPE_CODE as RATE_CASS_INT_RATE_TYPE_CODE,
		RATE_RATE_SEQUENCE as RATE_RATE_SEQUENCE,
		RATE_DURATION as RATE_DURATION,
		PERC_HL_INT_RATE_ID as PERC_HL_INT_RATE_ID,
		PERC_SCHEDULE_RATE_TYPE as PERC_SCHEDULE_RATE_TYPE,
		PERC_RATE_PERCENT_1 as PERC_RATE_PERCENT_1,
		PERC_RATE_PERCENT_2 as PERC_RATE_PERCENT_2,
		MARG_HL_PROD_INT_MARGIN_ID as MARG_HL_PROD_INT_MARGIN_ID,
		MARG_HL_INT_RATE_ID as MARG_HL_INT_RATE_ID,
		MARG_HL_PROD_INT_MARGIN_CAT_ID as MARG_HL_PROD_INT_MARGIN_CAT_ID,
		MARG_MARGIN_TYPE as MARG_MARGIN_TYPE,
		MARG_MARGIN_DESC as MARG_MARGIN_DESC,
		MARG_MARGIN_CODE as MARG_MARGIN_CODE,
		MARG_MARGIN_AMOUNT as MARG_MARGIN_AMOUNT,
		MARG_ADJ_AMT as MARG_ADJ_AMT,
		RATE_FOUND_FLAG as RATE_FOUND_FLAG,
		PERC_FOUND_FLAG as PERC_FOUND_FLAG,
		MARG_FOUND_FLAG as MARG_FOUND_FLAG,
		ETL_D as ETL_D,
		ORIG_ETL_D as ORIG_ETL_D,
		EROR_C as EROR_C
	FROM {{ ref('SrcIdNullsDS') }}
	UNION ALL
	SELECT
		HL_INT_RATE_ID,
		RATE_HL_INT_RATE_ID,
		RATE_HL_APP_PROD_ID,
		RATE_CASS_INT_RATE_TYPE_CODE,
		RATE_RATE_SEQUENCE,
		RATE_DURATION,
		PERC_HL_INT_RATE_ID,
		PERC_SCHEDULE_RATE_TYPE,
		PERC_RATE_PERCENT_1,
		PERC_RATE_PERCENT_2,
		MARG_HL_PROD_INT_MARGIN_ID,
		MARG_HL_INT_RATE_ID,
		MARG_HL_PROD_INT_MARGIN_CAT_ID,
		MARG_MARGIN_TYPE,
		MARG_MARGIN_DESC,
		MARG_MARGIN_CODE,
		MARG_MARGIN_AMOUNT,
		MARG_ADJ_AMT,
		RATE_FOUND_FLAG,
		PERC_FOUND_FLAG,
		MARG_FOUND_FLAG,
		ETL_D,
		ORIG_ETL_D,
		EROR_C
	FROM {{ ref('TgtRtPercMargRejectsDS') }}
	UNION ALL
	SELECT
		HL_INT_RATE_ID,
		RATE_HL_INT_RATE_ID,
		RATE_HL_APP_PROD_ID,
		RATE_CASS_INT_RATE_TYPE_CODE,
		RATE_RATE_SEQUENCE,
		RATE_DURATION,
		PERC_HL_INT_RATE_ID,
		PERC_SCHEDULE_RATE_TYPE,
		PERC_RATE_PERCENT_1,
		PERC_RATE_PERCENT_2,
		MARG_HL_PROD_INT_MARGIN_ID,
		MARG_HL_INT_RATE_ID,
		MARG_HL_PROD_INT_MARGIN_CAT_ID,
		MARG_MARGIN_TYPE,
		MARG_MARGIN_DESC,
		MARG_MARGIN_CODE,
		MARG_MARGIN_AMOUNT,
		MARG_ADJ_AMT,
		RATE_FOUND_FLAG,
		PERC_FOUND_FLAG,
		MARG_FOUND_FLAG,
		ETL_D,
		ORIG_ETL_D,
		EROR_C
	FROM {{ ref('SrcUpdateNotfoundDS') }}
)

SELECT * FROM FunRejects