{{ config(materialized='view', tags=['DltAPPT_PDCT_FEATFrmTMP_APPT_PDCT_FEAT_2']) }}

WITH ChangeCapture AS (
	SELECT
		COALESCE({{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_APPT_PDCT_I, {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_APPT_PDCT_I) AS NEW_APPT_PDCT_I,
		COALESCE({{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_FEAT_I, {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_FEAT_I) AS NEW_FEAT_I,
		COALESCE({{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_SRCE_SYST_APPT_FEAT_I, {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_SRCE_SYST_APPT_FEAT_I) AS NEW_SRCE_SYST_APPT_FEAT_I,
		COALESCE({{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_SRCE_SYST_C, {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_SRCE_SYST_C) AS NEW_SRCE_SYST_C,
		COALESCE({{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_SRCE_SYST_APPT_OVRD_I, {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_SRCE_SYST_APPT_OVRD_I) AS NEW_SRCE_SYST_APPT_OVRD_I,
		COALESCE({{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_OVRD_FEAT_I, {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_OVRD_FEAT_I) AS NEW_OVRD_FEAT_I,
		COALESCE({{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_SRCE_SYST_STND_VALU_Q, {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_SRCE_SYST_STND_VALU_Q) AS NEW_SRCE_SYST_STND_VALU_Q,
		COALESCE({{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_SRCE_SYST_STND_VALU_R, {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_SRCE_SYST_STND_VALU_R) AS NEW_SRCE_SYST_STND_VALU_R,
		COALESCE({{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_SRCE_SYST_STND_VALU_A, {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_SRCE_SYST_STND_VALU_A) AS NEW_SRCE_SYST_STND_VALU_A,
		COALESCE({{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_CNCY_C, {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_CNCY_C) AS NEW_CNCY_C,
		COALESCE({{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_ACTL_VALU_Q, {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_ACTL_VALU_Q) AS NEW_ACTL_VALU_Q,
		COALESCE({{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_ACTL_VALU_R, {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_ACTL_VALU_R) AS NEW_ACTL_VALU_R,
		COALESCE({{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_ACTL_VALU_A, {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_ACTL_VALU_A) AS NEW_ACTL_VALU_A,
		COALESCE({{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_FEAT_SEQN_N, {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_FEAT_SEQN_N) AS NEW_FEAT_SEQN_N,
		COALESCE({{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_FEAT_STRT_D, {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_FEAT_STRT_D) AS NEW_FEAT_STRT_D,
		COALESCE({{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_FEE_CHRG_D, {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_FEE_CHRG_D) AS NEW_FEE_CHRG_D,
		COALESCE({{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_OVRD_REAS_C, {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_OVRD_REAS_C) AS NEW_OVRD_REAS_C,
		COALESCE({{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_FEE_ADD_TO_TOTL_F, {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_FEE_ADD_TO_TOTL_F) AS NEW_FEE_ADD_TO_TOTL_F,
		COALESCE({{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_FEE_CAPL_F, {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_FEE_CAPL_F) AS NEW_FEE_CAPL_F,
		CASE
			WHEN {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_APPT_PDCT_I IS NULL AND {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_FEAT_I IS NULL AND {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_SRCE_SYST_APPT_FEAT_I IS NULL THEN '1'
			WHEN {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_APPT_PDCT_I IS NULL AND {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_FEAT_I IS NULL AND {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_SRCE_SYST_APPT_FEAT_I IS NULL THEN '2'
			WHEN ({{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_APPT_PDCT_I = {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_APPT_PDCT_I AND {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_FEAT_I = {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_FEAT_I AND {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_SRCE_SYST_APPT_FEAT_I = {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_SRCE_SYST_APPT_FEAT_I) AND ({{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_SRCE_SYST_C <> {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_SRCE_SYST_C OR {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_SRCE_SYST_APPT_OVRD_I <> {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_SRCE_SYST_APPT_OVRD_I OR {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_OVRD_FEAT_I <> {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_OVRD_FEAT_I OR {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_SRCE_SYST_STND_VALU_Q <> {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_SRCE_SYST_STND_VALU_Q OR {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_SRCE_SYST_STND_VALU_R <> {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_SRCE_SYST_STND_VALU_R OR {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_SRCE_SYST_STND_VALU_A <> {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_SRCE_SYST_STND_VALU_A OR {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_CNCY_C <> {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_CNCY_C OR {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_ACTL_VALU_Q <> {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_ACTL_VALU_Q OR {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_ACTL_VALU_R <> {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_ACTL_VALU_R OR {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_ACTL_VALU_A <> {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_ACTL_VALU_A OR {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_FEAT_SEQN_N <> {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_FEAT_SEQN_N OR {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_FEAT_STRT_D <> {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_FEAT_STRT_D OR {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_FEE_CHRG_D <> {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_FEE_CHRG_D OR {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_OVRD_REAS_C <> {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_OVRD_REAS_C OR {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_FEE_ADD_TO_TOTL_F <> {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_FEE_ADD_TO_TOTL_F OR {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_FEE_CAPL_F <> {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_FEE_CAPL_F) THEN '3'
			WHEN {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_APPT_PDCT_I = {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_APPT_PDCT_I AND {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_FEAT_I = {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_FEAT_I AND {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_SRCE_SYST_APPT_FEAT_I = {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_SRCE_SYST_APPT_FEAT_I AND {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_SRCE_SYST_C = {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_SRCE_SYST_C AND {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_SRCE_SYST_APPT_OVRD_I = {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_SRCE_SYST_APPT_OVRD_I AND {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_OVRD_FEAT_I = {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_OVRD_FEAT_I AND {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_SRCE_SYST_STND_VALU_Q = {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_SRCE_SYST_STND_VALU_Q AND {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_SRCE_SYST_STND_VALU_R = {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_SRCE_SYST_STND_VALU_R AND {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_SRCE_SYST_STND_VALU_A = {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_SRCE_SYST_STND_VALU_A AND {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_CNCY_C = {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_CNCY_C AND {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_ACTL_VALU_Q = {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_ACTL_VALU_Q AND {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_ACTL_VALU_R = {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_ACTL_VALU_R AND {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_ACTL_VALU_A = {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_ACTL_VALU_A AND {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_FEAT_SEQN_N = {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_FEAT_SEQN_N AND {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_FEAT_STRT_D = {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_FEAT_STRT_D AND {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_FEE_CHRG_D = {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_FEE_CHRG_D AND {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_OVRD_REAS_C = {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_OVRD_REAS_C AND {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_FEE_ADD_TO_TOTL_F = {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_FEE_ADD_TO_TOTL_F AND {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_FEE_CAPL_F = {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_FEE_CAPL_F THEN '0'
		END AS change_code 
	FROM {{ ref('{{ ref('CpyApptPdctFeat') }}') }} 
	FULL OUTER JOIN {{ ref('{{ ref('CpyApptPdctFeat') }}') }} 
	ON {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_APPT_PDCT_I = {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_APPT_PDCT_I
	AND {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_FEAT_I = {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_FEAT_I
	AND {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_SRCE_SYST_APPT_FEAT_I = {{ ref('{{ ref('CpyApptPdctFeat') }}') }}.NEW_SRCE_SYST_APPT_FEAT_I
	WHERE change_code = '1' OR change_code = '3'
)

SELECT * FROM ChangeCapture