{{ config(materialized='view', tags=['ExtReasonSmCaseState']) }}

WITH FunMergeSmCaseState AS (
	SELECT
		SM_CASE_STATE_ID as SM_CASE_STATE_ID,
		SCS_SM_CASE_ID as SCS_SM_CASE_ID,
		SCS_SM_STATE_CAT_ID as SCS_SM_STATE_CAT_ID,
		SCS_START_DATE as SCS_START_DATE,
		SCS_END_DATE as SCS_END_DATE,
		SCS_CREATED_BY_STAFF_NUMBER as SCS_CREATED_BY_STAFF_NUMBER,
		SCS_STATE_CAUSED_BY_ACTION_ID as SCS_STATE_CAUSED_BY_ACTION_ID,
		SCSR_SM_CASE_STATE_REASON_ID as SCSR_SM_CASE_STATE_REASON_ID,
		SCSR_SM_REASON_CAT_ID as SCSR_SM_REASON_CAT_ID,
		SM_CASE_STATE_REAS_FOUND_FLAG as SM_CASE_STATE_REAS_FOUND_FLAG,
		SM_CASE_STATE_FOUND_FLAG as SM_CASE_STATE_FOUND_FLAG,
		ORIG_ETL_D as ORIG_ETL_D
	FROM {{ ref('XfmSeparateRejectWithoutSourceAndTheRest__InSourceRec') }}
	UNION ALL
	SELECT
		SM_CASE_STATE_ID,
		SCS_SM_CASE_ID,
		SCS_SM_STATE_CAT_ID,
		SCS_START_DATE,
		SCS_END_DATE,
		SCS_CREATED_BY_STAFF_NUMBER,
		SCS_STATE_CAUSED_BY_ACTION_ID,
		SCSR_SM_CASE_STATE_REASON_ID,
		SCSR_SM_REASON_CAT_ID,
		SM_CASE_STATE_REAS_FOUND_FLAG,
		SM_CASE_STATE_FOUND_FLAG,
		ORIG_ETL_D
	FROM {{ ref('XfmSeparateRejectWithoutSourceAndTheRest__InRejectWithoutSourceRec') }}
)

SELECT * FROM FunMergeSmCaseState