{{ config(materialized='view', tags=['XfmDelFlagPATY_APPT_PDCT']) }}

WITH XfmProsKey AS (
	SELECT
		DLTD_TABL_NAME,
		PATY_I,
		-- *SRC*: Trim(OutJoin.DLTD_KEY1_VALU),
		TRIM({{ ref('TMP_DELETED') }}.DLTD_KEY1_VALU) AS APP_PROD_ID,
		{{ ref('TMP_DELETED') }}.DLTD_KEY2_VALU AS CIF_CODE,
		{{ ref('TMP_DELETED') }}.DLTD_KEY3_VALU AS ROLE_CAT_ID,
		{{ ref('TMP_DELETED') }}.DLTD_KEY4_VALU AS SBTY_CODE,
		{{ ref('TMP_DELETED') }}.DLTD_KEY5_VALU AS PATY_ROLE_C,
		-- *SRC*: \(20)If OutJoin.DLTD_TABL_NAME = 'APP_PROD_CLIENT_ROLE' Then 'CSE_COM_BUS_APP_PROD_CLNT_RL_PATY_APPT_PDCT' Else ( If OutJoin.DLTD_TABL_NAME = 'CCL_APP_PROD' Then 'CSE_CCL_BUS_APP_PROD_PATY_APPT_PDCT' Else ''),
		IFF({{ ref('TMP_DELETED') }}.DLTD_TABL_NAME = 'APP_PROD_CLIENT_ROLE', 'CSE_COM_BUS_APP_PROD_CLNT_RL_PATY_APPT_PDCT', IFF({{ ref('TMP_DELETED') }}.DLTD_TABL_NAME = 'CCL_APP_PROD', 'CSE_CCL_BUS_APP_PROD_PATY_APPT_PDCT', '')) AS CONV_M
	FROM {{ ref('TMP_DELETED') }}
	WHERE 
)

SELECT * FROM XfmProsKey