{{ config(materialized='view', tags=['DltAPPT_PDCT_OFI_SETL_FrmTMP_APPT_PDCT_OFI_SETL']) }}

WITH 
tmp_cse_appt_pdct_ofi_setl AS (
	SELECT
	*
	FROM {{ ref("tmp_cse_appt_pdct_ofi_setl")  }}),
cse_appt_pdct_ofi_setl AS (
	SELECT
	*
	FROM {{ ref("cse_appt_pdct_ofi_setl")  }}),
SrcTmpCSeApptPdctOfiSetlTera AS (SELECT A.APPT_PDCT_I AS NEW_APPT_PDCT_I, A.DCHG_OFI_IDNN_X AS NEW_OFI_IDNN_X, A.DCHG_OFI_M AS NEW_OFI_M, B.EFFT_D AS OLD_EFFT_D, CASE WHEN B.OLD_FLAG IS NULL AND NOT A.DCHG_OFI_IDNN_X IS NULL THEN 'I' WHEN B.OLD_FLAG = 'Y' AND NOT A.DCHG_OFI_IDNN_X IS NULL AND (COALESCE(A.DCHG_OFI_M, '') <> COALESCE(B.DCHG_OFI_M, '') OR COALESCE(A.DCHG_OFI_IDNN_X, '') <> COALESCE(B.DCHG_OFI_IDNN_X, '')) THEN 'U' WHEN B.OLD_FLAG = 'Y' AND NOT A.DCHG_OFI_IDNN_X IS NULL AND (COALESCE(A.DCHG_OFI_M, '') = COALESCE(B.DCHG_OFI_M, '') AND COALESCE(A.DCHG_OFI_IDNN_X, '') = COALESCE(B.DCHG_OFI_IDNN_X, '')) THEN 'C' WHEN B.OLD_FLAG = 'Y' AND A.DCHG_OFI_IDNN_X IS NULL THEN 'D' ELSE 'S' END AS REC_TYPE FROM TMP_CSE_APPT_PDCT_OFI_SETL LEFT OUTER JOIN (SELECT APPT_PDCT_I, DCHG_OFI_IDNN_X, DCHG_OFI_M, EFFT_D, 'Y' AS OLD_FLAG FROM CSE_APPT_PDCT_OFI_SETL WHERE EXPY_D = '9999-12-31') AS B ON A.APPT_PDCT_I = B.APPT_PDCT_I)


SELECT * FROM SrcTmpCSeApptPdctOfiSetlTera