{{ config(materialized='view', tags=['XfmDelFlagAPPT_PDCT_PURP']) }}

WITH XfmProsKey AS (
	SELECT
		DELETED_TABLE_NAME,
		{{ ref('SrcAppPdctPurpDS') }}.DELETED_KEY_1_VALUE AS APP_PROD_ID,
		DELETED_KEY_2_VALUE,
		-- *SRC*: \(20)If OutAppPdctPurpDS.DELETED_TABLE_NAME = 'CCL_APP_PROD' Then 'CSE_CCL_BUS_APP_PROD_APPT_PDCT_PURP' Else ( If OutAppPdctPurpDS.DELETED_TABLE_NAME = 'HL_APP_PROD_PURPOSE' Then 'CSE_CHL_BUS_APP_PROD_PURP_APPT_PDCT_PURP' Else ( If OutAppPdctPurpDS.DELETED_TABLE_NAME = 'PL_APP_PROD_PURP' Then 'CSE_CPL_BUS_APP_PROD_PURP_APPT_PDCT_PURP' Else '')),
		IFF(
	    {{ ref('SrcAppPdctPurpDS') }}.DELETED_TABLE_NAME = 'CCL_APP_PROD', 'CSE_CCL_BUS_APP_PROD_APPT_PDCT_PURP', 
	    IFF({{ ref('SrcAppPdctPurpDS') }}.DELETED_TABLE_NAME = 'HL_APP_PROD_PURPOSE', 'CSE_CHL_BUS_APP_PROD_PURP_APPT_PDCT_PURP', IFF({{ ref('SrcAppPdctPurpDS') }}.DELETED_TABLE_NAME = 'PL_APP_PROD_PURP', 'CSE_CPL_BUS_APP_PROD_PURP_APPT_PDCT_PURP', ''))
	) AS CONV_M
	FROM {{ ref('SrcAppPdctPurpDS') }}
	WHERE 
)

SELECT * FROM XfmProsKey