{{ config(materialized='view', tags=['ExtCC_APP_PROD']) }}

WITH FunMergeJournal AS (
	SELECT
		CC_APP_PROD_ID as CC_APP_PROD_ID,
		REQUESTED_LIMIT_AMT as REQUESTED_LIMIT_AMT,
		CC_INTEREST_OPT_CAT_ID as CC_INTEREST_OPT_CAT_ID,
		CBA_HOMELOAN_NO as CBA_HOMELOAN_NO,
		PRE_APPRV_AMOUNT as PRE_APPRV_AMOUNT,
		ORIG_ETL_D as ORIG_ETL_D,
		READ_COSTS_AND_RISKS_FLAG as READ_COSTS_AND_RISKS_FLAG,
		ACCEPTS_COSTS_AND_RISKS_DATE as ACCEPTS_COSTS_AND_RISKS_DATE,
		NTM_CAMPAIGN_ID as NTM_CAMPAIGN_ID,
		FRIES_CAMPAIGN_CODE as FRIES_CAMPAIGN_CODE,
		OAP_CAMPAIGN_CODE as OAP_CAMPAIGN_CODE
	FROM {{ ref('XfmSeparateRejectWithoutSourceAndTheRest__InSourceRec') }}
	UNION ALL
	SELECT
		CC_APP_PROD_ID,
		REQUESTED_LIMIT_AMT,
		CC_INTEREST_OPT_CAT_ID,
		CBA_HOMELOAN_NO,
		PRE_APPRV_AMOUNT,
		ORIG_ETL_D,
		READ_COSTS_AND_RISKS_FLAG,
		ACCEPTS_COSTS_AND_RISKS_DATE,
		NTM_CAMPAIGN_ID,
		FRIES_CAMPAIGN_CODE,
		OAP_CAMPAIGN_CODE
	FROM {{ ref('XfmSeparateRejectWithoutSourceAndTheRest__InRejectWithoutSourceRec') }}
)

SELECT * FROM FunMergeJournal