{{ config(materialized='view', tags=['ExtPlFeePlMargin']) }}

WITH JoinSrcSortReject AS (
	SELECT
		{{ ref('XfmCheckPlFeeIdNulls__OutCheckPlFeeIdNullsSorted') }}.PL_FEE_ID,
		{{ ref('XfmCheckPlFeeIdNulls__OutCheckPlFeeIdNullsSorted') }}.PL_APP_PROD_ID,
		{{ ref('XfmCheckPlFeeIdNulls__OutCheckPlFeeIdNullsSorted') }}.PL_FEE_PL_FEE_ID,
		{{ ref('XfmCheckPlFeeIdNulls__OutCheckPlFeeIdNullsSorted') }}.PL_FEE_ADD_TO_TOTAL_FLAG,
		{{ ref('XfmCheckPlFeeIdNulls__OutCheckPlFeeIdNullsSorted') }}.PL_FEE_FEE_AMT,
		{{ ref('XfmCheckPlFeeIdNulls__OutCheckPlFeeIdNullsSorted') }}.PL_FEE_BASE_FEE_AMT,
		{{ ref('XfmCheckPlFeeIdNulls__OutCheckPlFeeIdNullsSorted') }}.PL_FEE_PAY_FEE_AT_FUNDING_FLAG,
		{{ ref('XfmCheckPlFeeIdNulls__OutCheckPlFeeIdNullsSorted') }}.PL_FEE_START_DATE,
		{{ ref('XfmCheckPlFeeIdNulls__OutCheckPlFeeIdNullsSorted') }}.PL_FEE_PL_CAPITALIS_FEE_CAT_ID,
		{{ ref('XfmCheckPlFeeIdNulls__OutCheckPlFeeIdNullsSorted') }}.PL_FEE_FEE_SCREEN_DESC,
		{{ ref('XfmCheckPlFeeIdNulls__OutCheckPlFeeIdNullsSorted') }}.PL_FEE_FEE_DESC,
		{{ ref('XfmCheckPlFeeIdNulls__OutCheckPlFeeIdNullsSorted') }}.PL_FEE_CASS_FEE_CODE,
		{{ ref('XfmCheckPlFeeIdNulls__OutCheckPlFeeIdNullsSorted') }}.PL_FEE_CASS_FEE_KEY,
		{{ ref('XfmCheckPlFeeIdNulls__OutCheckPlFeeIdNullsSorted') }}.PL_FEE_TOTAL_FEE_AMT,
		{{ ref('XfmCheckPlFeeIdNulls__OutCheckPlFeeIdNullsSorted') }}.PL_FEE_PL_APP_PROD_ID,
		{{ ref('XfmCheckPlFeeIdNulls__OutCheckPlFeeIdNullsSorted') }}.PL_MARGIN_PL_MARGIN_ID,
		{{ ref('XfmCheckPlFeeIdNulls__OutCheckPlFeeIdNullsSorted') }}.PL_MARGIN_MARGIN_AMT,
		{{ ref('XfmCheckPlFeeIdNulls__OutCheckPlFeeIdNullsSorted') }}.PL_MARGIN_PL_FEE_ID,
		{{ ref('XfmCheckPlFeeIdNulls__OutCheckPlFeeIdNullsSorted') }}.PL_MARGIN_PL_INT_RATE_ID,
		{{ ref('XfmCheckPlFeeIdNulls__OutCheckPlFeeIdNullsSorted') }}.PL_MARGIN_MARGIN_REASON_CAT_ID,
		{{ ref('XfmCheckPlFeeIdNulls__OutCheckPlFeeIdNullsSorted') }}.PL_MARGIN_PL_APP_PROD_ID,
		{{ ref('XfmCheckPlFeeIdNulls__OutCheckPlFeeIdNullsSorted') }}.PL_FEE_FOUND_FLAG,
		{{ ref('XfmCheckPlFeeIdNulls__OutCheckPlFeeIdNullsSorted') }}.PL_MARGIN_FOUND_FLAG,
		{{ ref('CpyRejtPlFeePlMarginRejectOra') }}.PL_FEE_ID AS PL_FEE_ID_R,
		{{ ref('CpyRejtPlFeePlMarginRejectOra') }}.PL_APP_PROD_ID_R,
		{{ ref('CpyRejtPlFeePlMarginRejectOra') }}.PL_FEE_PL_FEE_ID_R,
		{{ ref('CpyRejtPlFeePlMarginRejectOra') }}.PL_FEE_ADD_TO_TOTAL_FLAG_R,
		{{ ref('CpyRejtPlFeePlMarginRejectOra') }}.PL_FEE_FEE_AMT_R,
		{{ ref('CpyRejtPlFeePlMarginRejectOra') }}.PL_FEE_BASE_FEE_AMT_R,
		{{ ref('CpyRejtPlFeePlMarginRejectOra') }}.PL_FEE_PAY_FEE_AT_FUNDING_FLAG_R,
		{{ ref('CpyRejtPlFeePlMarginRejectOra') }}.PL_FEE_START_DATE_R,
		{{ ref('CpyRejtPlFeePlMarginRejectOra') }}.PL_FEE_PL_CAPITALIS_FEE_CAT_ID_R,
		{{ ref('CpyRejtPlFeePlMarginRejectOra') }}.PL_FEE_FEE_SCREEN_DESC_R,
		{{ ref('CpyRejtPlFeePlMarginRejectOra') }}.PL_FEE_FEE_DESC_R,
		{{ ref('CpyRejtPlFeePlMarginRejectOra') }}.PL_FEE_CASS_FEE_CODE_R,
		{{ ref('CpyRejtPlFeePlMarginRejectOra') }}.PL_FEE_CASS_FEE_KEY_R,
		{{ ref('CpyRejtPlFeePlMarginRejectOra') }}.PL_FEE_TOTAL_FEE_AMT_R,
		{{ ref('CpyRejtPlFeePlMarginRejectOra') }}.PL_FEE_PL_APP_PROD_ID_R,
		{{ ref('CpyRejtPlFeePlMarginRejectOra') }}.PL_MARGIN_PL_MARGIN_ID_R,
		{{ ref('CpyRejtPlFeePlMarginRejectOra') }}.PL_MARGIN_MARGIN_AMT_R,
		{{ ref('CpyRejtPlFeePlMarginRejectOra') }}.PL_MARGIN_PL_FEE_ID_R,
		{{ ref('CpyRejtPlFeePlMarginRejectOra') }}.PL_MARGIN_PL_INT_RATE_ID_R,
		{{ ref('CpyRejtPlFeePlMarginRejectOra') }}.PL_MARGIN_MARGIN_REASON_CAT_ID_R,
		{{ ref('CpyRejtPlFeePlMarginRejectOra') }}.PL_MARGIN_PL_APP_PROD_ID_R,
		{{ ref('CpyRejtPlFeePlMarginRejectOra') }}.PL_FEE_FOUND_FLAG_R,
		{{ ref('CpyRejtPlFeePlMarginRejectOra') }}.PL_MARGIN_FOUND_FLAG_R,
		{{ ref('CpyRejtPlFeePlMarginRejectOra') }}.ORIG_ETL_D_R
	FROM {{ ref('XfmCheckPlFeeIdNulls__OutCheckPlFeeIdNullsSorted') }}
	OUTER JOIN {{ ref('CpyRejtPlFeePlMarginRejectOra') }} ON {{ ref('XfmCheckPlFeeIdNulls__OutCheckPlFeeIdNullsSorted') }}.PL_FEE_ID = {{ ref('CpyRejtPlFeePlMarginRejectOra') }}.PL_FEE_ID
)

SELECT * FROM JoinSrcSortReject