{{ config(materialized='view', tags=['LdDltAPP_ANS_CTCT_EVNT_SURV']) }}

WITH 
tmp_xs_evnt_app_ans AS (
	SELECT
	*
	FROM {{ ref("tmp_xs_evnt_app_ans")  }}),
ctct_evnt_surv AS (
	SELECT
	*
	FROM {{ ref("ctct_evnt_surv")  }}),
Src_Tera_APPT_PDCT_COND AS (SELECT a.EVNT_I AS NEW_EVNT_I, a.QSTN_C AS NEW_QSTN_C, a.RESP_C AS NEW_RESP_C, a.RESP_CMMT_X AS NEW_RESP_CMMT_X, b.EVNT_I AS OLD_EVNT_I, b.QSTN_C AS OLD__QSTN_C, B.RESP_C AS OLD_RESP_C, B.RESP_CMMT_X AS OLD_RESP_CMMT_X FROM TMP_XS_EVNT_APP_ANS LEFT OUTER JOIN CTCT_EVNT_SURV ON a.EVNT_I = b.EVNT_I AND a.QSTN_C = b.QSTN_C AND b.EXPY_D = '9999-12-31' AND a.RUN_STRM = '{{ var("RUN_STREAM") }}' GROUP BY NEW_EVNT_I, NEW_QSTN_C, NEW_RESP_C, NEW_RESP_CMMT_X, OLD_EVNT_I, b.QSTN_C, OLD_RESP_C, OLD_RESP_CMMT_X)


SELECT * FROM Src_Tera_APPT_PDCT_COND