{{ config(materialized='view', tags=['XfmHL_APPFrmExt1']) }}

WITH RdToRqm3 AS (
	SELECT SRCE_KEY_I, CONV_M, CONV_MAP_RULE_M, TRSF_TABL_M, SRCE_EFFT_D, VALU_CHNG_BFOR_X, VALU_CHNG_AFTR_X, TRSF_X, TRSF_COLM_M, EROR_SEQN_I, SRCE_FILE_M, PROS_KEY_EFFT_I, TRSF_KEY_I 
	FROM (
		SELECT SRCE_KEY_I, CONV_M, CONV_MAP_RULE_M, TRSF_TABL_M, SRCE_EFFT_D, VALU_CHNG_BFOR_X, VALU_CHNG_AFTR_X, TRSF_X, TRSF_COLM_M, EROR_SEQN_I, SRCE_FILE_M, PROS_KEY_EFFT_I, TRSF_KEY_I,
		 ROW_NUMBER() OVER (PARTITION BY SRCE_KEY_I ORDER BY 1 ASC) AS ROW_NUM 
		FROM {{ ref('Xfm__ToErrRqm3') }}
	) AS RdToRqm3_TEMP
	WHERE ROW_NUM = 1
)

SELECT * FROM RdToRqm3