{{ config(materialized='view', tags=['XfmBusPrfBrkDataFrmExt']) }}

WITH Funnel AS (
	SELECT
		SRCE_KEY_I as SRCE_KEY_I,
		CONV_M as CONV_M,
		CONV_MAP_RULE_M as CONV_MAP_RULE_M,
		TRSF_TABL_M as TRSF_TABL_M,
		SRCE_EFFT_D as SRCE_EFFT_D,
		VALU_CHNG_BFOR_X as VALU_CHNG_BFOR_X,
		VALU_CHNG_AFTR_X as VALU_CHNG_AFTR_X,
		TRSF_X as TRSF_X,
		TRSF_COLM_M as TRSF_COLM_M,
		EROR_SEQN_I as EROR_SEQN_I,
		SRCE_FILE_M as SRCE_FILE_M,
		PROS_KEY_EFFT_I as PROS_KEY_EFFT_I,
		TRSF_KEY_I as TRSF_KEY_I
	FROM {{ ref('Xfmbrkdata__ToErrRqm3Gr') }}
	UNION ALL
	SELECT
		SRCE_KEY_I,
		CONV_M,
		CONV_MAP_RULE_M,
		TRSF_TABL_M,
		SRCE_EFFT_D,
		VALU_CHNG_BFOR_X,
		VALU_CHNG_AFTR_X,
		TRSF_X,
		TRSF_COLM_M,
		EROR_SEQN_I,
		SRCE_FILE_M,
		PROS_KEY_EFFT_I,
		TRSF_KEY_I
	FROM {{ ref('Xfmbrkdata__ToErrRqm3frSg') }}
)

SELECT * FROM Funnel