{{ config(materialized='view', tags=['XfmChlIntRateChlRatePercChlProdIntMargFrmExt']) }}

WITH ModNullHandling AS (
	SELECT 
	--Manual
	--FEAT_I: string[max=255]= handle_null (TARG_CHAR_C, '999009')
	--FEAT_OVRD_REAS_C:nullable string[4] = handle_null (FEAT_OVRD_REAS_C, '9999')
	--RATE_CASS_INT_RATE_TYPE_CODE = SRCE_CHAR_1_C
	--PERC_SCHEDULE_RATE_TYPE = SRCE_CHAR_2_C
	--MARG_HL_PROD_INT_MARGIN_CAT_ID = HL_PROD_INT_MARGIN_CAT_ID
	HL_INT_RATE_ID, RATE_HL_INT_RATE_ID, RATE_HL_APP_PROD_ID, SRCE_CHAR_1_C AS RATE_CASS_INT_RATE_TYPE_CODE, RATE_RATE_SEQUENCE, RATE_DURATION, PERC_HL_INT_RATE_ID, SRCE_CHAR_2_C AS PERC_SCHEDULE_RATE_TYPE, PERC_RATE_PERCENT AS PERC_RATE_PERCENT_1, PERC_HL_INT_RATE_PERCENT_ID AS PERC_RATE_PERCENT_2, MARG_HL_PROD_INT_MARGIN_ID, MARG_HL_INT_RATE_ID, HL_PROD_INT_MARGIN_CAT_ID AS MARG_HL_PROD_INT_MARGIN_CAT_ID, MARG_MARGIN_TYPE, MARG_MARGIN_DESC, MARG_MARGIN_CODE, MARG_MARGIN_AMOUNT, MARG_ADJ_AMT, RATE_FOUND_FLAG, PERC_FOUND_FLAG, MARG_FOUND_FLAG, ORIG_ETL_D, TARG_CHAR_C AS FEAT_I, FEAT_OVRD_REAS_C 
	FROM {{ ref('LkpReferences') }}
)

SELECT * FROM ModNullHandling