{{ config(materialized='view', tags=['XfmChlIntRateChlRatePercChlProdIntMargFrmExt']) }}

WITH XfmBusinessRules__OutApptPdctFeatDS AS (
	SELECT
		-- *SRC*: \(20)If (InXfmBusinessRules.RATE_FOUND_FLAG = 'Y' And Len(Trim(( IF IsNotNull((InXfmBusinessRules.RATE_HL_APP_PROD_ID)) THEN (InXfmBusinessRules.RATE_HL_APP_PROD_ID) ELSE ""))) = 0) then 'N' else 'Y',
		IFF({{ ref('ModNullHandling') }}.RATE_FOUND_FLAG = 'Y' AND LEN(TRIM(IFF({{ ref('ModNullHandling') }}.RATE_HL_APP_PROD_ID IS NOT NULL, {{ ref('ModNullHandling') }}.RATE_HL_APP_PROD_ID, ''))) = 0, 'N', 'Y') AS LoadApptPdctI,
		-- *SRC*: \(20)If (InXfmBusinessRules.RATE_FOUND_FLAG = 'Y' And Len(Trim(( IF IsNotNull((InXfmBusinessRules.RATE_CASS_INT_RATE_TYPE_CODE)) THEN (InXfmBusinessRules.RATE_CASS_INT_RATE_TYPE_CODE) ELSE ""))) = 0) then 'N' Else 'Y',
		IFF({{ ref('ModNullHandling') }}.RATE_FOUND_FLAG = 'Y' AND LEN(TRIM(IFF({{ ref('ModNullHandling') }}.RATE_CASS_INT_RATE_TYPE_CODE IS NOT NULL, {{ ref('ModNullHandling') }}.RATE_CASS_INT_RATE_TYPE_CODE, ''))) = 0, 'N', 'Y') AS LoadFeatI,
		-- *SRC*: \(20)If InXfmBusinessRules.RATE_FOUND_FLAG = 'N' Or InXfmBusinessRules.PERC_FOUND_FLAG = 'N' Then DEFAULT_NULL_VALUE Else InXfmBusinessRules.FEAT_I,
		IFF({{ ref('ModNullHandling') }}.RATE_FOUND_FLAG = 'N' OR {{ ref('ModNullHandling') }}.PERC_FOUND_FLAG = 'N', DEFAULT_NULL_VALUE, {{ ref('ModNullHandling') }}.FEAT_I) AS FeatI,
		-- *SRC*: \(20)If (InXfmBusinessRules.MARG_FOUND_FLAG = 'N' Or (Len(Trim(( IF IsNotNull((InXfmBusinessRules.MARG_HL_PROD_INT_MARGIN_CAT_ID)) THEN (InXfmBusinessRules.MARG_HL_PROD_INT_MARGIN_CAT_ID) ELSE ""))) = 0)) then DEFAULT_NULL_VALUE Else InXfmBusinessRules.FEAT_OVRD_REAS_C,
		IFF({{ ref('ModNullHandling') }}.MARG_FOUND_FLAG = 'N' OR LEN(TRIM(IFF({{ ref('ModNullHandling') }}.MARG_HL_PROD_INT_MARGIN_CAT_ID IS NOT NULL, {{ ref('ModNullHandling') }}.MARG_HL_PROD_INT_MARGIN_CAT_ID, ''))) = 0, DEFAULT_NULL_VALUE, {{ ref('ModNullHandling') }}.FEAT_OVRD_REAS_C) AS FeatOvrdReasC,
		-- *SRC*: \(20)If LoadApptPdctI = 'N' Then 'REJ4104' Else  If LoadFeatI = 'N' Then 'REJ4105' Else  If FeatI = '999009' then 'RPR4006' Else  If FeatOvrdReasC = '9999' then 'RPR4007' Else '',
		IFF(LoadApptPdctI = 'N', 'REJ4104', IFF(LoadFeatI = 'N', 'REJ4105', IFF(FeatI = '999009', 'RPR4006', IFF(FeatOvrdReasC = '9999', 'RPR4007', '')))) AS ErrorCode,
		-- *SRC*: \(20)If ErrorCode <> "" Then @TRUE Else @FALSE,
		IFF(ErrorCode <> '', @TRUE, @FALSE) AS RejectFlag,
		-- *SRC*: 'CSEHL' : ( IF IsNotNull((InXfmBusinessRules.RATE_HL_APP_PROD_ID)) THEN (InXfmBusinessRules.RATE_HL_APP_PROD_ID) ELSE (DEFAULT_NULL_VALUE)),
		CONCAT('CSEHL', IFF({{ ref('ModNullHandling') }}.RATE_HL_APP_PROD_ID IS NOT NULL, {{ ref('ModNullHandling') }}.RATE_HL_APP_PROD_ID, DEFAULT_NULL_VALUE)) AS APPT_PDCT_I,
		FeatI AS FEAT_I,
		-- *SRC*: 'HR' : InXfmBusinessRules.HL_INT_RATE_ID,
		CONCAT('HR', {{ ref('ModNullHandling') }}.HL_INT_RATE_ID) AS SRCE_SYST_APPT_FEAT_I,
		-- *SRC*: StringToDate(ETL_PROCESS_DT, "%yyyy%mm%dd"),
		STRINGTODATE(ETL_PROCESS_DT, '%yyyy%mm%dd') AS EFFT_D,
		'CSE' AS SRCE_SYST_C,
		-- *SRC*: SetNull(),
		SETNULL() AS SRCE_SYST_APPT_OVRD_I,
		-- *SRC*: SetNull(),
		SETNULL() AS OVRD_FEAT_I,
		{{ ref('ModNullHandling') }}.RATE_DURATION AS SRCE_SYST_STND_VALU_Q,
		{{ ref('ModNullHandling') }}.PERC_RATE_PERCENT_1 AS SRCE_SYST_STND_VALU_R,
		-- *SRC*: SetNull(),
		SETNULL() AS SRCE_SYST_STND_VALU_A,
		'AUD' AS CNCY_C,
		{{ ref('ModNullHandling') }}.RATE_DURATION AS ACTL_VALU_Q,
		-- *SRC*: \(20)If Len(Trim(( IF IsNotNull((InXfmBusinessRules.PERC_RATE_PERCENT_2)) THEN (InXfmBusinessRules.PERC_RATE_PERCENT_2) ELSE ""))) > 0 Then StringToDecimal(InXfmBusinessRules.PERC_RATE_PERCENT_2) Else StringToDecimal(InXfmBusinessRules.PERC_RATE_PERCENT_1),
		IFF(LEN(TRIM(IFF({{ ref('ModNullHandling') }}.PERC_RATE_PERCENT_2 IS NOT NULL, {{ ref('ModNullHandling') }}.PERC_RATE_PERCENT_2, ''))) > 0, STRINGTODECIMAL({{ ref('ModNullHandling') }}.PERC_RATE_PERCENT_2), STRINGTODECIMAL({{ ref('ModNullHandling') }}.PERC_RATE_PERCENT_1)) AS ACTL_VALU_R,
		-- *SRC*: SetNull(),
		SETNULL() AS ACTL_VALU_A,
		{{ ref('ModNullHandling') }}.RATE_RATE_SEQUENCE AS FEAT_SEQN_N,
		-- *SRC*: SetNull(),
		SETNULL() AS FEAT_STRT_D,
		-- *SRC*: SetNull(),
		SETNULL() AS FEE_CHRG_D,
		-- *SRC*: \(20)If FeatOvrdReasC = DEFAULT_NULL_VALUE then SetNull() Else FeatOvrdReasC,
		IFF(FeatOvrdReasC = DEFAULT_NULL_VALUE, SETNULL(), FeatOvrdReasC) AS OVRD_REAS_C,
		'N' AS FEE_ADD_TO_TOTL_F,
		'N' AS FEE_CAPL_F,
		-- *SRC*: StringToDate('9999-12-31', "%yyyy-%mm-%dd"),
		STRINGTODATE('9999-12-31', '%yyyy-%mm-%dd') AS EXPY_D,
		0 AS PROS_KEY_EFFT_I,
		-- *SRC*: SetNull(),
		SETNULL() AS PROS_KEY_EXPY_I,
		-- *SRC*: SetNull(),
		SETNULL() AS EROR_SEQN_I,
		RUN_STREAM AS RUN_STRM,
		HL_INT_RATE_ID,
		RATE_HL_INT_RATE_ID,
		RATE_HL_APP_PROD_ID,
		RATE_CASS_INT_RATE_TYPE_CODE,
		RATE_RATE_SEQUENCE,
		RATE_DURATION,
		PERC_HL_INT_RATE_ID,
		-- *SRC*: ( IF IsNotNull((InXfmBusinessRules.PERC_SCHEDULE_RATE_TYPE)) THEN (InXfmBusinessRules.PERC_SCHEDULE_RATE_TYPE) ELSE ""),
		IFF({{ ref('ModNullHandling') }}.PERC_SCHEDULE_RATE_TYPE IS NOT NULL, {{ ref('ModNullHandling') }}.PERC_SCHEDULE_RATE_TYPE, '') AS PERC_SCHEDULE_RATE_TYPE,
		PERC_RATE_PERCENT_1,
		PERC_RATE_PERCENT_2,
		MARG_HL_PROD_INT_MARGIN_ID,
		MARG_HL_INT_RATE_ID,
		MARG_HL_PROD_INT_MARGIN_CAT_ID,
		MARG_MARGIN_TYPE,
		MARG_MARGIN_DESC,
		MARG_MARGIN_CODE,
		MARG_MARGIN_AMOUNT,
		MARG_ADJ_AMT,
		RATE_FOUND_FLAG,
		PERC_FOUND_FLAG,
		MARG_FOUND_FLAG,
		ORIG_ETL_D
	FROM {{ ref('ModNullHandling') }}
	WHERE LoadApptPdctI = 'Y' AND LoadFeatI = 'Y'
)

SELECT * FROM XfmBusinessRules__OutApptPdctFeatDS