{{ config(materialized='view', tags=['REJT_COI_BUS_CLNT_UNDTAK']) }}

WITH FunRejectsNulls AS (
	SELECT
		FA_CLIENT_UNDERTAKING_ID as FA_CLIENT_UNDERTAKING_ID,
		FA_UNDERTAKING_ID as FA_UNDERTAKING_ID,
		COIN_ENTITY_ID as COIN_ENTITY_ID,
		CLIENT_CORRELATION_ID as CLIENT_CORRELATION_ID,
		FA_ENTITY_CAT_ID as FA_ENTITY_CAT_ID,
		FA_CHILD_STATUS_CAT_ID as FA_CHILD_STATUS_CAT_ID,
		CLIENT_RELATIONSHIP_TYPE_ID as CLIENT_RELATIONSHIP_TYPE_ID,
		CLIENT_POSITION as CLIENT_POSITION,
		IS_PRIMARY_FLAG as IS_PRIMARY_FLAG,
		CIF_CODE as CIF_CODE,
		ETL_D as ETL_D,
		ORIG_ETL_D as ORIG_ETL_D,
		EROR_C as EROR_C
	FROM {{ ref('SrcIdNullsDS') }}
	UNION ALL
	SELECT
		FA_CLIENT_UNDERTAKING_ID,
		FA_UNDERTAKING_ID,
		COIN_ENTITY_ID,
		CLIENT_CORRELATION_ID,
		FA_ENTITY_CAT_ID,
		FA_CHILD_STATUS_CAT_ID,
		CLIENT_RELATIONSHIP_TYPE_ID,
		CLIENT_POSITION,
		IS_PRIMARY_FLAG,
		CIF_CODE,
		ETL_D,
		ORIG_ETL_D,
		EROR_C
	FROM {{ ref('SrcMappingRejectsDS') }}
	UNION ALL
	SELECT
		FA_CLIENT_UNDERTAKING_ID,
		FA_UNDERTAKING_ID,
		COIN_ENTITY_ID,
		CLIENT_CORRELATION_ID,
		FA_ENTITY_CAT_ID,
		FA_CHILD_STATUS_CAT_ID,
		CLIENT_RELATIONSHIP_TYPE_ID,
		CLIENT_POSITION,
		IS_PRIMARY_FLAG,
		CIF_CODE,
		ETL_D,
		ORIG_ETL_D,
		EROR_C
	FROM {{ ref('SrcDeltaPrimDS') }}
	UNION ALL
	SELECT
		FA_CLIENT_UNDERTAKING_ID,
		FA_UNDERTAKING_ID,
		COIN_ENTITY_ID,
		CLIENT_CORRELATION_ID,
		FA_ENTITY_CAT_ID,
		FA_CHILD_STATUS_CAT_ID,
		CLIENT_RELATIONSHIP_TYPE_ID,
		CLIENT_POSITION,
		IS_PRIMARY_FLAG,
		CIF_CODE,
		ETL_D,
		ORIG_ETL_D,
		EROR_C
	FROM {{ ref('SrcDeltaChldDS') }}
)

SELECT * FROM FunRejectsNulls