{{ config(materialized='view', tags=['Ext_APP_ANS']) }}

WITH FunMergeJournal AS (
	SELECT
		HL_APP_ID as HL_APP_ID,
		QA_QUESTION_ID as QA_QUESTION_ID,
		QA_ANSWER_ID as QA_ANSWER_ID,
		TEXT_ANSWER as TEXT_ANSWER,
		CIF_CODE as CIF_CODE,
		CBA_STAFF_NUMBER as CBA_STAFF_NUMBER,
		LODGEMENT_BRANCH_ID as LODGEMENT_BRANCH_ID,
		SUBTYPE_CODE as SUBTYPE_CODE,
		MOD_TIMESTAMP as MOD_TIMESTAMP,
		ORIG_ETL_D as ORIG_ETL_D
	FROM {{ ref('XfmSeparateRejectWithoutSourceAndTheRest__InSourceRec') }}
	UNION ALL
	SELECT
		HL_APP_ID,
		QA_QUESTION_ID,
		QA_ANSWER_ID,
		TEXT_ANSWER,
		CIF_CODE,
		CBA_STAFF_NUMBER,
		LODGEMENT_BRANCH_ID,
		SUBTYPE_CODE,
		MOD_TIMESTAMP,
		ORIG_ETL_D
	FROM {{ ref('XfmSeparateRejectWithoutSourceAndTheRest__InRejectWithoutSourceRec') }}
)

SELECT * FROM FunMergeJournal