{{ config(materialized='view', tags=['LdMAP_CSE_APPT_PURP_CLAS_CLLkp']) }}

WITH 
,
SrcMAP_CSE_APPT_PURP_CLAS_CLTera AS (SELECT 
MAP_CSE_APPT_PURP_CLAS_CL.LOAN_PURP_CLAS_CODE,
MAP_CSE_APPT_PURP_CLAS_CL.PURP_CLAS_C,
MAP_CSE_APPT_PURP_CLAS_CL.EFFT_D,
MAP_CSE_APPT_PURP_CLAS_CL.EXPY_D
FROM  {{ var('GDW_ACCT_VW') }}.MAP_CSE_APPT_PURP_CLAS_CL as MAP_CSE_APPT_PURP_CLAS_CL
WHERE MAP_CSE_APPT_PURP_CLAS_CL.efft_d (date, format 'yyyymmdd') <= '{{ var('ETL_PROCESS_DT') }}' 
and MAP_CSE_APPT_PURP_CLAS_CL.expy_d (date, format 'yyyymmdd') >= '{{ var('ETL_PROCESS_DT') }}' )


SELECT * FROM SrcMAP_CSE_APPT_PURP_CLAS_CLTera