{{ config(materialized='view', tags=['DltAPPT_PDCT_PATYFrmTMP_APPT_PDCT_PATY']) }}

WITH 
appt_pdct_paty AS (
	SELECT
	*
	FROM {{ ref("appt_pdct_paty")  }}),
tmp_appt_pdct_paty AS (
	SELECT
	*
	FROM {{ ref("tmp_appt_pdct_paty")  }}),
SrcTmpApptPdctPatyTera AS (SELECT a.APPT_PDCT_I AS NEW_APPT_PDCT_I, a.PATY_I AS NEW_PATY_I, a.PATY_ROLE_C AS NEW_PATY_ROLE_C, a.SRCE_SYST_C AS NEW_SRCE_SYST_C, a.SRCE_SYST_APPT_PDCT_PATY_I AS NEW_SRCE_SYST_APPT_PDCT_PATY_I, b.APPT_PDCT_I AS OLD_APPT_PDCT_I, b.PATY_I AS OLD_PATY_I, b.PATY_ROLE_C AS OLD_PATY_ROLE_C, b.EFFT_D AS OLD_EFFT_D FROM TMP_APPT_PDCT_PATY LEFT OUTER JOIN APPT_PDCT_PATY ON TRIM(a.APPT_PDCT_I) = TRIM(b.APPT_PDCT_I) AND TRIM(a.PATY_ROLE_C) = TRIM(b.PATY_ROLE_C) AND b.EXPY_D = '9999-12-31' WHERE a.RUN_STRM = '{{ var("RUN_STREAM") }}')


SELECT * FROM SrcTmpApptPdctPatyTera