{{ config(materialized='view', tags=['LdUTIL_TRSF_EROR_R2_Ins']) }}

WITH Remove_Duplicates AS (
	SELECT SRCE_KEY_I, CONV_M, CONV_MAP_RULE_M, TRSF_TABL_M, SRCE_EFFT_D, VALU_CHNG_BFOR_X, VALU_CHNG_AFTR_X, TRSF_X, TRSF_COLM_M, EROR_SEQN_I, SRCE_FILE_M, PROS_KEY_EFFT_I, TRSF_KEY_I, ERORSEQ 
	FROM (
		SELECT SRCE_KEY_I, CONV_M, CONV_MAP_RULE_M, TRSF_TABL_M, SRCE_EFFT_D, VALU_CHNG_BFOR_X, VALU_CHNG_AFTR_X, TRSF_X, TRSF_COLM_M, EROR_SEQN_I, SRCE_FILE_M, PROS_KEY_EFFT_I, TRSF_KEY_I, ERORSEQ,
		 ROW_NUMBER() OVER (PARTITION BY SRCE_KEY_I, CONV_M ORDER BY 1 ASC) AS ROW_NUM 
		FROM {{ ref('Seq_Number') }}
	) AS Remove_Duplicates_TEMP
	WHERE ROW_NUM = 1
)

SELECT * FROM Remove_Duplicates