{{ config(materialized='view', tags=['LdDltAPP_ANS_EVNT']) }}

WITH CTCT_EVNT_Rm_Dup AS (
	SELECT EVNT_I, SRCE_SYST_EVNT_I, EVNT_ACTL_D, SRCE_SYST_C, PROS_KEY_EFFT_I, EROR_SEQN_I, SRCE_SYST_EVNT_TYPE_I, CTCT_EVNT_TYPE_C, EVNT_ACTL_T, ROW_SECU_ACCS_C 
	FROM (
		SELECT EVNT_I, SRCE_SYST_EVNT_I, EVNT_ACTL_D, SRCE_SYST_C, PROS_KEY_EFFT_I, EROR_SEQN_I, SRCE_SYST_EVNT_TYPE_I, CTCT_EVNT_TYPE_C, EVNT_ACTL_T, ROW_SECU_ACCS_C,
		 ROW_NUMBER() OVER (PARTITION BY EVNT_I ORDER BY 1 ASC) AS ROW_NUM 
		FROM {{ ref('XFR_DeltaCheck__CTCT_Evnt') }}
	) AS CTCT_EVNT_Rm_Dup_TEMP
	WHERE ROW_NUM = 1
)

SELECT * FROM CTCT_EVNT_Rm_Dup