{{ config(materialized='view', tags=['LdDltAPP_ANS_EVNT']) }}

WITH EVNT_Rm_Dup_HL AS (
	SELECT EVNT_I, EVNT_ACTV_TYPE_C, INVT_EVNT_F, FNCL_ACCT_EVNT_F, CTCT_EVNT_F, BUSN_EVNT_F, PROS_KEY_EFFT_I, EROR_SEQN_I, FNCL_NVAL_EVNT_F, INCD_F, INSR_EVNT_F, INSR_NVAL_EVNT_F, ROW_SECU_ACCS_C 
	FROM (
		SELECT EVNT_I, EVNT_ACTV_TYPE_C, INVT_EVNT_F, FNCL_ACCT_EVNT_F, CTCT_EVNT_F, BUSN_EVNT_F, PROS_KEY_EFFT_I, EROR_SEQN_I, FNCL_NVAL_EVNT_F, INCD_F, INSR_EVNT_F, INSR_NVAL_EVNT_F, ROW_SECU_ACCS_C,
		 ROW_NUMBER() OVER (PARTITION BY EVNT_I, EVNT_ACTV_TYPE_C ORDER BY 1 ASC) AS ROW_NUM 
		FROM {{ ref('XFR_DeltaCheck__Evnt_HL') }}
	) AS EVNT_Rm_Dup_HL_TEMP
	WHERE ROW_NUM = 1
)

SELECT * FROM EVNT_Rm_Dup_HL