{{ config(materialized='view', tags=['LdDltAPP_ANS_EVNT']) }}

WITH Remove_Duplicates_Evnt_paty AS (
	SELECT EVNT_I, SRCE_SYST_PATY_I, EVNT_PATY_ROLE_TYPE_C, EFFT_D, SRCE_SYST_C, PATY_I, EXPY_D, PROS_KEY_EFFT_I, PROS_KEY_EXPY_I, EROR_SEQN_I, ROW_SECU_ACCS_C 
	FROM (
		SELECT EVNT_I, SRCE_SYST_PATY_I, EVNT_PATY_ROLE_TYPE_C, EFFT_D, SRCE_SYST_C, PATY_I, EXPY_D, PROS_KEY_EFFT_I, PROS_KEY_EXPY_I, EROR_SEQN_I, ROW_SECU_ACCS_C,
		 ROW_NUMBER() OVER (PARTITION BY EVNT_I, PATY_I ORDER BY 1 ASC) AS ROW_NUM 
		FROM {{ ref('XFR_DeltaCheck__Evnt_paty') }}
	) AS Remove_Duplicates_Evnt_paty_TEMP
	WHERE ROW_NUM = 1
)

SELECT * FROM Remove_Duplicates_Evnt_paty