{{ config(materialized='view', tags=['LdDltAPP_ANS_EVNT']) }}

WITH 
,
Src_Tera_XS_EVNT AS (SELECT chk.SRC_EVNT_I, chk.TGT_EVNT_I, chk.APPL_ID, chk.CIF_CODE, chk.APPT_QLFY_C, chk.MOD_TIMESTAMP FROM (SELECT a.EVNT_I AS SRC_EVNT_I, COALESCE(b.EVNT_I, 'RE33') AS TGT_EVNT_I, a.srce_syst_evnt_i AS APPL_ID, a.PATY_I AS CIF_CODE, A.APPT_QLFY_C AS APPT_QLFY_C, A.MOD_TIMESTAMP AS MOD_TIMESTAMP FROM TMP_XS_EVNT_APP_ANS LEFT OUTER JOIN (SELECT * FROM EVNT WHERE SUBSTRING(evnt_i, 1, 4) = 'CSEC') AS b ON a.EVNT_I = b.EVNT_I AND A.EVNT_ACTV_TYPE_C = B.EVNT_ACTV_TYPE_C WHERE a.RUN_STRM = 'CSE_XS_CHL_CPL_BUS_APP_ANS' AND TGT_EVNT_I = 'RE33') AS chk LEFT OUTER JOIN (SELECT evnt_i FROM ctct_evnt WHERE SUBSTRING(evnt_i, 1, 4) = 'CSEC' GROUP BY 1) AS chk1 ON chk.SRC_EVNT_I = chk1.evnt_i WHERE evnt_i IS NULL GROUP BY 1, 2, 3, 4, 5, 6)


SELECT * FROM Src_Tera_XS_EVNT