{{ config(materialized='view', tags=['XfmAppt_Pdct_Feat']) }}

WITH Xfm AS (
	SELECT
		-- *SRC*: \(20)If IsNull(Src_to_Xfm.APP_PROD_ID) Then 'Y' Else  If Trim(Src_to_Xfm.APP_PROD_ID) = '' Then 'Y' Else  If Trim(Src_to_Xfm.APP_PROD_ID) = 0 Then 'Y' Else 'N',
		IFF({{ ref('CSE_CPO_BUS_APP_PROD') }}.APP_PROD_ID IS NULL, 'Y', IFF(TRIM({{ ref('CSE_CPO_BUS_APP_PROD') }}.APP_PROD_ID) = '', 'Y', IFF(TRIM({{ ref('CSE_CPO_BUS_APP_PROD') }}.APP_PROD_ID) = 0, 'Y', 'N'))) AS svIsNullAppProdId,
		-- *SRC*: \(20)If IsNull(Src_to_Xfm.TEMP_OVERDRAFT_TERM_IN_DAYS) Then 'Y' Else  if Trim(Src_to_Xfm.TEMP_OVERDRAFT_TERM_IN_DAYS) = '0' Then 'Y' Else  if Trim(( IF IsNotNull((Src_to_Xfm.TEMP_OVERDRAFT_TERM_IN_DAYS)) THEN (Src_to_Xfm.TEMP_OVERDRAFT_TERM_IN_DAYS) ELSE "")) = '' THEN 'Y' ELSE 'N',
		IFF({{ ref('CSE_CPO_BUS_APP_PROD') }}.TEMP_OVERDRAFT_TERM_IN_DAYS IS NULL, 'Y', IFF(TRIM({{ ref('CSE_CPO_BUS_APP_PROD') }}.TEMP_OVERDRAFT_TERM_IN_DAYS) = '0', 'Y', IFF(TRIM(IFF({{ ref('CSE_CPO_BUS_APP_PROD') }}.TEMP_OVERDRAFT_TERM_IN_DAYS IS NOT NULL, {{ ref('CSE_CPO_BUS_APP_PROD') }}.TEMP_OVERDRAFT_TERM_IN_DAYS, '')) = '', 'Y', 'N'))) AS svIsNullTempOverdrafttermInDays,
		-- *SRC*: 'CSEPO' : Src_to_Xfm.APP_PROD_ID,
		CONCAT('CSEPO', {{ ref('CSE_CPO_BUS_APP_PROD') }}.APP_PROD_ID) AS APPT_PDCT_I,
		'2658' AS FEAT_I,
		'NOT APPLICABLE' AS SRCE_SYST_APPT_FEAT_I,
		-- *SRC*: StringToDate(Trim(pRUN_STRM_PROS_D[1, 4]) : '-' : Trim(pRUN_STRM_PROS_D[5, 2]) : '-' : Trim(pRUN_STRM_PROS_D[7, 2]), "%yyyy-%mm-%dd"),
		STRINGTODATE(CONCAT(CONCAT(CONCAT(CONCAT(TRIM(SUBSTRING(pRUN_STRM_PROS_D, 1, 4)), '-'), TRIM(SUBSTRING(pRUN_STRM_PROS_D, 5, 2))), '-'), TRIM(SUBSTRING(pRUN_STRM_PROS_D, 7, 2))), '%yyyy-%mm-%dd') AS EFFT_D,
		'CSE' AS SRCE_SYST_C,
		-- *SRC*: SetNull(),
		SETNULL() AS SRCE_SYST_APPT_OVRD_I,
		-- *SRC*: SetNull(),
		SETNULL() AS OVRD_FEAT_I,
		-- *SRC*: SetNull(),
		SETNULL() AS SRCE_SYST_STND_VALU_Q,
		-- *SRC*: SetNull(),
		SETNULL() AS SRCE_SYST_STND_VALU_R,
		-- *SRC*: SetNull(),
		SETNULL() AS SRCE_SYST_STND_VALU_A,
		-- *SRC*: SetNull(),
		SETNULL() AS CNCY_C,
		-- *SRC*: (StringToDecimal(Trim(Src_to_Xfm.TEMP_OVERDRAFT_TERM_IN_DAYS))),
		STRINGTODECIMAL(TRIM({{ ref('CSE_CPO_BUS_APP_PROD') }}.TEMP_OVERDRAFT_TERM_IN_DAYS)) AS ACTL_VALU_Q,
		-- *SRC*: SetNull(),
		SETNULL() AS ACTL_VALU_R,
		-- *SRC*: SetNull(),
		SETNULL() AS ACTL_VALU_A,
		-- *SRC*: SetNull(),
		SETNULL() AS FEAT_SEQN_N,
		-- *SRC*: SetNull(),
		SETNULL() AS FEAT_STRT_D,
		-- *SRC*: SetNull(),
		SETNULL() AS FEE_CHRG_D,
		-- *SRC*: SetNull(),
		SETNULL() AS OVRD_REAS_C,
		-- *SRC*: SetNull(),
		SETNULL() AS FEE_ADD_TO_TOTL_F,
		-- *SRC*: SetNull(),
		SETNULL() AS FEE_CAPL_F,
		-- *SRC*: StringToDate('9999-12-31', "%yyyy-%mm-%dd"),
		STRINGTODATE('9999-12-31', '%yyyy-%mm-%dd') AS EXPY_D,
		0 AS PROS_KEY_EFFT_I,
		-- *SRC*: SetNull(),
		SETNULL() AS PROS_KEY_EXPY_I,
		-- *SRC*: SetNull(),
		SETNULL() AS EROR_SEQN_I,
		pRUN_STRM_C AS RUN_STRM,
		1 AS DLTA_VERS
	FROM {{ ref('CSE_CPO_BUS_APP_PROD') }}
	WHERE svIsNullAppProdId = 'N' AND svIsNullTempOverdrafttermInDays = 'N'
)

SELECT * FROM Xfm