{{ config(materialized='view', tags=['LdREJT_ChlBusFeeDiscFee']) }}

WITH FunJnlIdNulls AS (
	SELECT
		HL_FEE_ID as HL_FEE_ID,
		BF_HL_FEE_ID as BF_HL_FEE_ID,
		BF_HL_APP_PROD_ID as BF_HL_APP_PROD_ID,
		BF_XML_CODE as BF_XML_CODE,
		BF_DISPLAY_NAME as BF_DISPLAY_NAME,
		BF_CATEGORY as BF_CATEGORY,
		BF_UNIT_AMOUNT as BF_UNIT_AMOUNT,
		BF_TOTAL_AMOUNT as BF_TOTAL_AMOUNT,
		BFD_HL_FEE_DISCOUNT_ID as BFD_HL_FEE_DISCOUNT_ID,
		BFD_HL_FEE_ID as BFD_HL_FEE_ID,
		BFD_DISCOUNT_REASON as BFD_DISCOUNT_REASON,
		BFD_DISCOUNT_CODE as BFD_DISCOUNT_CODE,
		BFD_DISCOUNT_AMT as BFD_DISCOUNT_AMT,
		BFD_DISCOUNT_TERM as BFD_DISCOUNT_TERM,
		BFD_HL_FEE_DISCOUNT_CAT_ID as BFD_HL_FEE_DISCOUNT_CAT_ID,
		BF_FOUND_FLAG as BF_FOUND_FLAG,
		BFD_FOUND_FLAG as BFD_FOUND_FLAG,
		ETL_D as ETL_D,
		ORIG_ETL_D as ORIG_ETL_D,
		EROR_C as EROR_C
	FROM {{ ref('SrcIdNullDS') }}
	UNION ALL
	SELECT
		HL_FEE_ID,
		BF_HL_FEE_ID,
		BF_HL_APP_PROD_ID,
		BF_XML_CODE,
		BF_DISPLAY_NAME,
		BF_CATEGORY,
		BF_UNIT_AMOUNT,
		BF_TOTAL_AMOUNT,
		BFD_HL_FEE_DISCOUNT_ID,
		BFD_HL_FEE_ID,
		BFD_DISCOUNT_REASON,
		BFD_DISCOUNT_CODE,
		BFD_DISCOUNT_AMT,
		BFD_DISCOUNT_TERM,
		BFD_HL_FEE_DISCOUNT_CAT_ID,
		BF_FOUND_FLAG,
		BFD_FOUND_FLAG,
		ETL_D,
		ORIG_ETL_D,
		EROR_C
	FROM {{ ref('SrcMappingDS') }}
	UNION ALL
	SELECT
		HL_FEE_ID,
		BF_HL_FEE_ID,
		BF_HL_APP_PROD_ID,
		BF_XML_CODE,
		BF_DISPLAY_NAME,
		BF_CATEGORY,
		BF_UNIT_AMOUNT,
		BF_TOTAL_AMOUNT,
		BFD_HL_FEE_DISCOUNT_ID,
		BFD_HL_FEE_ID,
		BFD_DISCOUNT_REASON,
		BFD_DISCOUNT_CODE,
		BFD_DISCOUNT_AMT,
		BFD_DISCOUNT_TERM,
		BFD_HL_FEE_DISCOUNT_CAT_ID,
		BF_FOUND_FLAG,
		BFD_FOUND_FLAG,
		ETL_D,
		ORIG_ETL_D,
		EROR_C
	FROM {{ ref('SrcUpdateDS') }}
)

SELECT * FROM FunJnlIdNulls