{{ config(materialized='view', tags=['ExtAppProdCclAppProdPlAppProd']) }}

WITH CpyRejtRejectOra AS (
	SELECT
		APP_PROD_ID,
		{{ ref('SrcRejtRejectOra') }}.CCHL_APP_PROD_ID AS CCHL_APP_PROD_ID_R,
		{{ ref('SrcRejtRejectOra') }}.CCL_APP_PROD_ID AS CCL_APP_PROD_ID_R,
		{{ ref('SrcRejtRejectOra') }}.CCL_PARENT_CCL_APP_PROD_ID AS CCL_PARENT_CCL_APP_PROD_ID_R,
		{{ ref('SrcRejtRejectOra') }}.CCL_ACCOUNT_NUMBER AS CCL_ACCOUNT_NUMBER_R,
		{{ ref('SrcRejtRejectOra') }}.CCL_ACTUAL_RATE AS CCL_ACTUAL_RATE_R,
		{{ ref('SrcRejtRejectOra') }}.CCL_BALLOON_PAY_AMT AS CCL_BALLOON_PAY_AMT_R,
		{{ ref('SrcRejtRejectOra') }}.CCL_BASIS_TYPE_CAT_ID AS CCL_BASIS_TYPE_CAT_ID_R,
		{{ ref('SrcRejtRejectOra') }}.CCL_INTEREST_RATE_MARGIN AS CCL_INTEREST_RATE_MARGIN_R,
		{{ ref('SrcRejtRejectOra') }}.CCL_LOAN_TERM_MTH_NUM AS CCL_LOAN_TERM_MTH_NUM_R,
		{{ ref('SrcRejtRejectOra') }}.CCL_CURRENT_LIMIT AS CCL_CURRENT_LIMIT_R,
		{{ ref('SrcRejtRejectOra') }}.CCL_INC_DEC_AMT AS CCL_INC_DEC_AMT_R,
		{{ ref('SrcRejtRejectOra') }}.CCL_POST_APP_AMT AS CCL_POST_APP_AMT_R,
		{{ ref('SrcRejtRejectOra') }}.CCL_NEW_PROD_FLAG AS CCL_NEW_PROD_FLAG_R,
		{{ ref('SrcRejtRejectOra') }}.CCL_INDEX_RATE AS CCL_INDEX_RATE_R,
		{{ ref('SrcRejtRejectOra') }}.CCL_INTEREST_ADV_FLAG AS CCL_INTEREST_ADV_FLAG_R,
		{{ ref('SrcRejtRejectOra') }}.CCL_INTERESTONLY_TERM_MTH_NUM AS CCL_INTERESTONLY_TERM_MTH_NUM_R,
		{{ ref('SrcRejtRejectOra') }}.CCL_CAPPED_TERM_MTH_NUM AS CCL_CAPPED_TERM_MTH_NUM_R,
		{{ ref('SrcRejtRejectOra') }}.CCL_CAPPED_RATE AS CCL_CAPPED_RATE_R,
		{{ ref('SrcRejtRejectOra') }}.CCL_CRIS_PRODUCT_ID AS CCL_CRIS_PRODUCT_ID_R,
		{{ ref('SrcRejtRejectOra') }}.CCL_CCL_LOAN_PURPOSE_ID AS CCL_CCL_LOAN_PURPOSE_ID_R,
		{{ ref('SrcRejtRejectOra') }}.CCL_NEW_PROD_SUBTYPE_FLAG AS CCL_NEW_PROD_SUBTYPE_FLAG_R,
		{{ ref('SrcRejtRejectOra') }}.CCL_TEMP_EXCESS_MTHS AS CCL_TEMP_EXCESS_MTHS_R,
		{{ ref('SrcRejtRejectOra') }}.CCL_LOAN_PURPOSE_CLASS_CODE AS CCL_LOAN_PURPOSE_CLASS_CODE_R,
		{{ ref('SrcRejtRejectOra') }}.CCL_CCL_INTEREST_RATE_CAT_ID AS CCL_CCL_INTEREST_RATE_CAT_ID_R,
		{{ ref('SrcRejtRejectOra') }}.CCL_CRR AS CCL_CRR_R,
		{{ ref('SrcRejtRejectOra') }}.CCL_AD_TUC_INC_AMT AS CCL_AD_TUC_INC_AMT_R,
		{{ ref('SrcRejtRejectOra') }}.CCL_CCL_RATE_TYPE_CAT_ID AS CCL_CCL_RATE_TYPE_CAT_ID_R,
		{{ ref('SrcRejtRejectOra') }}.CCL_LINK_CCL_APP_ID AS CCL_LINK_CCL_APP_ID_R,
		{{ ref('SrcRejtRejectOra') }}.CCL_LINK_CCL_APP_PROD_ID AS CCL_LINK_CCL_APP_PROD_ID_R,
		{{ ref('SrcRejtRejectOra') }}.CCL_CHL_LMI_AMT AS CCL_CHL_LMI_AMT_R,
		{{ ref('SrcRejtRejectOra') }}.CCL_USED_IN_EXPOSURE_VIEW_FLAG AS CCL_USED_IN_EXPOSURE_VIEW_FLAG_R,
		{{ ref('SrcRejtRejectOra') }}.CCL_CCL_APP_BROKER_CIF_CODE AS CCL_CCL_APP_BROKER_CIF_CODE_R,
		{{ ref('SrcRejtRejectOra') }}.CCL_APP_ID AS CCL_APP_ID_R,
		{{ ref('SrcRejtRejectOra') }}.CCL_FIXED_INT_START_DATE AS CCL_FIXED_INT_START_DATE_R,
		{{ ref('SrcRejtRejectOra') }}.CCL_CHILD_PDCT_LEVEL_CAT_ID AS CCL_CHILD_PDCT_LEVEL_CAT_ID_R,
		{{ ref('SrcRejtRejectOra') }}.CCL_PARENT_PDCT_LEVEL_CAT_ID AS CCL_PARENT_PDCT_LEVEL_CAT_ID_R,
		{{ ref('SrcRejtRejectOra') }}.CPL_APP_PROD_ID AS CPL_APP_PROD_ID_R,
		{{ ref('SrcRejtRejectOra') }}.CPL_PL_TARGET_CAT_ID AS CPL_PL_TARGET_CAT_ID_R,
		{{ ref('SrcRejtRejectOra') }}.CPL_REPAY_APPROX_AMT AS CPL_REPAY_APPROX_AMT_R,
		{{ ref('SrcRejtRejectOra') }}.CPL_REPAY_FREQUENCY_ID AS CPL_REPAY_FREQUENCY_ID_R,
		{{ ref('SrcRejtRejectOra') }}.CPL_PL_APP_PROD_REPAY_CAT_ID AS CPL_PL_APP_PROD_REPAY_CAT_ID_R,
		{{ ref('SrcRejtRejectOra') }}.CPL_PL_PROD_TERM_CAT_ID AS CPL_PL_PROD_TERM_CAT_ID_R,
		{{ ref('SrcRejtRejectOra') }}.CPL_PL_CAMPAIGN_CAT_ID AS CPL_PL_CAMPAIGN_CAT_ID_R,
		{{ ref('SrcRejtRejectOra') }}.CPL_AD_HOC_CAMPAIGN_DESC AS CPL_AD_HOC_CAMPAIGN_DESC_R,
		{{ ref('SrcRejtRejectOra') }}.CPL_CAR_SEEKER_FLAG AS CPL_CAR_SEEKER_FLAG_R,
		{{ ref('SrcRejtRejectOra') }}.CPL_PL_PROD_TARGET_CAT_ID AS CPL_PL_PROD_TARGET_CAT_ID_R,
		{{ ref('SrcRejtRejectOra') }}.CPL_PL_MARKETING_SOURCE_CAT_ID AS CPL_PL_MARKETING_SOURCE_CAT_ID_R,
		{{ ref('SrcRejtRejectOra') }}.CPL_HLS_ACCT_NO AS CPL_HLS_ACCT_NO_R,
		{{ ref('SrcRejtRejectOra') }}.CPL_TOTAL_INTEREST_AMT AS CPL_TOTAL_INTEREST_AMT_R,
		{{ ref('SrcRejtRejectOra') }}.CPL_APP_PROD_AMT AS CPL_APP_PROD_AMT_R,
		{{ ref('SrcRejtRejectOra') }}.CPL_TP_BROKER_ID AS CPL_TP_BROKER_ID_R,
		{{ ref('SrcRejtRejectOra') }}.CPL_TP_BROKER_FIRST_NAME AS CPL_TP_BROKER_FIRST_NAME_R,
		{{ ref('SrcRejtRejectOra') }}.CPL_TP_BROKER_LAST_NAME AS CPL_TP_BROKER_LAST_NAME_R,
		{{ ref('SrcRejtRejectOra') }}.CPL_TP_BROKER_GROUP_CAT_ID AS CPL_TP_BROKER_GROUP_CAT_ID_R,
		{{ ref('SrcRejtRejectOra') }}.COM_APP_PROD_ID AS COM_APP_PROD_ID_R,
		{{ ref('SrcRejtRejectOra') }}.COM_SUBTYPE_CODE AS COM_SUBTYPE_CODE_R,
		{{ ref('SrcRejtRejectOra') }}.COM_APP_ID AS COM_APP_ID_R,
		{{ ref('SrcRejtRejectOra') }}.COM_PRODUCT_TYPE_ID AS COM_PRODUCT_TYPE_ID_R,
		{{ ref('SrcRejtRejectOra') }}.COM_SM_CASE_ID AS COM_SM_CASE_ID_R,
		{{ ref('SrcRejtRejectOra') }}.COM_FOUND_FLAG AS COM_FOUND_FLAG_R,
		{{ ref('SrcRejtRejectOra') }}.CPL_FOUND_FLAG AS CPL_FOUND_FLAG_R,
		{{ ref('SrcRejtRejectOra') }}.CCL_FOUND_FLAG AS CCL_FOUND_FLAG_R,
		{{ ref('SrcRejtRejectOra') }}.CC_FOUND_FLAG AS CC_FOUND_FLAG_R,
		{{ ref('SrcRejtRejectOra') }}.CC_APP_PROD_ID AS CC_APP_PROD_ID_R,
		{{ ref('SrcRejtRejectOra') }}.ABN AS ABN_R,
		{{ ref('SrcRejtRejectOra') }}.BUSINESS_NAME AS BUSINESS_NAME_R,
		{{ ref('SrcRejtRejectOra') }}.SIMPLE_APP_FLAG AS SIMPLE_APP_FLAG_R,
		{{ ref('SrcRejtRejectOra') }}.CHL_FOUND_FLAG AS CHL_FOUND_FLAG_R,
		{{ ref('SrcRejtRejectOra') }}.ORIG_ETL_D AS ORIG_ETL_D_R,
		{{ ref('SrcRejtRejectOra') }}.CHL_CR_DATE AS CHL_CR_DATE_R,
		{{ ref('SrcRejtRejectOra') }}.CHL_ASSESSMENT_DATE AS CHL_ASSESSMENT_DATE_R,
		{{ ref('SrcRejtRejectOra') }}.CHL_NCPR_FLAG AS CHL_NCPR_FLAG_R
	FROM {{ ref('SrcRejtRejectOra') }}
)

SELECT * FROM CpyRejtRejectOra