{{ config(materialized='view', tags=['ExtAppProdCclAppProdPlAppProd']) }}

WITH LuAppProdExcl AS (
	SELECT
		{{ ref('JoinSrcSortReject') }}.APP_PROD_ID,
		{{ ref('JoinSrcSortReject') }}.CCHL_APP_PROD_ID,
		{{ ref('JoinSrcSortReject') }}.CLP_JOB_FAMILY_CAT_ID,
		{{ ref('JoinSrcSortReject') }}.CCL_APP_PROD_ID,
		{{ ref('JoinSrcSortReject') }}.CCL_PARENT_CCL_APP_PROD_ID,
		{{ ref('JoinSrcSortReject') }}.CCL_ACCOUNT_NUMBER,
		{{ ref('JoinSrcSortReject') }}.CCL_ACTUAL_RATE,
		{{ ref('JoinSrcSortReject') }}.CCL_BALLOON_PAY_AMT,
		{{ ref('JoinSrcSortReject') }}.CCL_BASIS_TYPE_CAT_ID,
		{{ ref('JoinSrcSortReject') }}.CCL_INTEREST_RATE_MARGIN,
		{{ ref('JoinSrcSortReject') }}.CCL_LOAN_TERM_MTH_NUM,
		{{ ref('JoinSrcSortReject') }}.CCL_CURRENT_LIMIT,
		{{ ref('JoinSrcSortReject') }}.CCL_INC_DEC_AMT,
		{{ ref('JoinSrcSortReject') }}.CCL_POST_APP_AMT,
		{{ ref('JoinSrcSortReject') }}.CCL_NEW_PROD_FLAG,
		{{ ref('JoinSrcSortReject') }}.CCL_INDEX_RATE,
		{{ ref('JoinSrcSortReject') }}.CCL_INTEREST_ADV_FLAG,
		{{ ref('JoinSrcSortReject') }}.CCL_INTERESTONLY_TERM_MTH_NUM,
		{{ ref('JoinSrcSortReject') }}.CCL_CAPPED_TERM_MTH_NUM,
		{{ ref('JoinSrcSortReject') }}.CCL_CAPPED_RATE,
		{{ ref('JoinSrcSortReject') }}.CCL_CRIS_PRODUCT_ID,
		{{ ref('JoinSrcSortReject') }}.CCL_CCL_LOAN_PURPOSE_ID,
		{{ ref('JoinSrcSortReject') }}.CCL_NEW_PROD_SUBTYPE_FLAG,
		{{ ref('JoinSrcSortReject') }}.CCL_TEMP_EXCESS_MTHS,
		{{ ref('JoinSrcSortReject') }}.CCL_LOAN_PURPOSE_CLASS_CODE,
		{{ ref('JoinSrcSortReject') }}.CCL_CCL_INTEREST_RATE_CAT_ID,
		{{ ref('JoinSrcSortReject') }}.CCL_CRR,
		{{ ref('JoinSrcSortReject') }}.CCL_AD_TUC_INC_AMT,
		{{ ref('JoinSrcSortReject') }}.CCL_CCL_RATE_TYPE_CAT_ID,
		{{ ref('JoinSrcSortReject') }}.CCL_LINK_CCL_APP_ID,
		{{ ref('JoinSrcSortReject') }}.CCL_LINK_CCL_APP_PROD_ID,
		{{ ref('JoinSrcSortReject') }}.CCL_CHL_LMI_AMT,
		{{ ref('JoinSrcSortReject') }}.CCL_USED_IN_EXPOSURE_VIEW_FLAG,
		{{ ref('JoinSrcSortReject') }}.CCL_CCL_APP_BROKER_CIF_CODE,
		{{ ref('JoinSrcSortReject') }}.CCL_APP_ID,
		{{ ref('JoinSrcSortReject') }}.CCL_FIXED_INT_START_DATE,
		{{ ref('JoinSrcSortReject') }}.CCL_CHILD_PDCT_LEVEL_CAT_ID,
		{{ ref('JoinSrcSortReject') }}.CCL_PARENT_PDCT_LEVEL_CAT_ID,
		{{ ref('JoinSrcSortReject') }}.CPL_APP_PROD_ID,
		{{ ref('JoinSrcSortReject') }}.CPL_PL_TARGET_CAT_ID,
		{{ ref('JoinSrcSortReject') }}.CPL_REPAY_APPROX_AMT,
		{{ ref('JoinSrcSortReject') }}.CPL_REPAY_FREQUENCY_ID,
		{{ ref('JoinSrcSortReject') }}.CPL_PL_APP_PROD_REPAY_CAT_ID,
		{{ ref('JoinSrcSortReject') }}.CPL_PL_PROD_TERM_CAT_ID,
		{{ ref('JoinSrcSortReject') }}.CPL_PL_CAMPAIGN_CAT_ID,
		{{ ref('JoinSrcSortReject') }}.CPL_AD_HOC_CAMPAIGN_DESC,
		{{ ref('JoinSrcSortReject') }}.CPL_CAR_SEEKER_FLAG,
		{{ ref('JoinSrcSortReject') }}.CPL_PL_PROD_TARGET_CAT_ID,
		{{ ref('JoinSrcSortReject') }}.CPL_PL_MARKETING_SOURCE_CAT_ID,
		{{ ref('JoinSrcSortReject') }}.CPL_HLS_ACCT_NO,
		{{ ref('JoinSrcSortReject') }}.CPL_TOTAL_INTEREST_AMT,
		{{ ref('JoinSrcSortReject') }}.CPL_APP_PROD_AMT,
		{{ ref('JoinSrcSortReject') }}.CPL_TP_BROKER_ID,
		{{ ref('JoinSrcSortReject') }}.CPL_TP_BROKER_FIRST_NAME,
		{{ ref('JoinSrcSortReject') }}.CPL_TP_BROKER_LAST_NAME,
		{{ ref('JoinSrcSortReject') }}.CPL_TP_BROKER_GROUP_CAT_ID,
		{{ ref('JoinSrcSortReject') }}.COM_APP_PROD_ID,
		{{ ref('JoinSrcSortReject') }}.COM_SUBTYPE_CODE,
		{{ ref('JoinSrcSortReject') }}.COM_APP_ID,
		{{ ref('JoinSrcSortReject') }}.COM_PRODUCT_TYPE_ID,
		{{ ref('JoinSrcSortReject') }}.COM_SM_CASE_ID,
		{{ ref('JoinSrcSortReject') }}.COM_FOUND_FLAG,
		{{ ref('JoinSrcSortReject') }}.CPL_FOUND_FLAG,
		{{ ref('JoinSrcSortReject') }}.CCL_FOUND_FLAG,
		{{ ref('JoinSrcSortReject') }}.CLP_FOUND_FLAG,
		{{ ref('JoinSrcSortReject') }}.CC_FOUND_FLAG,
		{{ ref('JoinSrcSortReject') }}.CC_APP_PROD_ID,
		{{ ref('JoinSrcSortReject') }}.ABN,
		{{ ref('JoinSrcSortReject') }}.BUSINESS_NAME,
		{{ ref('JoinSrcSortReject') }}.SIMPLE_APP_FLAG,
		{{ ref('JoinSrcSortReject') }}.CHL_FOUND_FLAG,
		{{ ref('JoinSrcSortReject') }}.APP_PROD_ID_R,
		{{ ref('JoinSrcSortReject') }}.CCHL_APP_PROD_ID_R,
		{{ ref('JoinSrcSortReject') }}.CCL_APP_PROD_ID_R,
		{{ ref('JoinSrcSortReject') }}.CCL_PARENT_CCL_APP_PROD_ID_R,
		{{ ref('JoinSrcSortReject') }}.CCL_ACCOUNT_NUMBER_R,
		{{ ref('JoinSrcSortReject') }}.CCL_ACTUAL_RATE_R,
		{{ ref('JoinSrcSortReject') }}.CCL_BALLOON_PAY_AMT_R,
		{{ ref('JoinSrcSortReject') }}.CCL_BASIS_TYPE_CAT_ID_R,
		{{ ref('JoinSrcSortReject') }}.CCL_INTEREST_RATE_MARGIN_R,
		{{ ref('JoinSrcSortReject') }}.CCL_LOAN_TERM_MTH_NUM_R,
		{{ ref('JoinSrcSortReject') }}.CCL_CURRENT_LIMIT_R,
		{{ ref('JoinSrcSortReject') }}.CCL_INC_DEC_AMT_R,
		{{ ref('JoinSrcSortReject') }}.CCL_POST_APP_AMT_R,
		{{ ref('JoinSrcSortReject') }}.CCL_NEW_PROD_FLAG_R,
		{{ ref('JoinSrcSortReject') }}.CCL_INDEX_RATE_R,
		{{ ref('JoinSrcSortReject') }}.CCL_INTEREST_ADV_FLAG_R,
		{{ ref('JoinSrcSortReject') }}.CCL_INTERESTONLY_TERM_MTH_NUM_R,
		{{ ref('JoinSrcSortReject') }}.CCL_CAPPED_TERM_MTH_NUM_R,
		{{ ref('JoinSrcSortReject') }}.CCL_CAPPED_RATE_R,
		{{ ref('JoinSrcSortReject') }}.CCL_CRIS_PRODUCT_ID_R,
		{{ ref('JoinSrcSortReject') }}.CCL_CCL_LOAN_PURPOSE_ID_R,
		{{ ref('JoinSrcSortReject') }}.CCL_NEW_PROD_SUBTYPE_FLAG_R,
		{{ ref('JoinSrcSortReject') }}.CCL_TEMP_EXCESS_MTHS_R,
		{{ ref('JoinSrcSortReject') }}.CCL_LOAN_PURPOSE_CLASS_CODE_R,
		{{ ref('JoinSrcSortReject') }}.CCL_CCL_INTEREST_RATE_CAT_ID_R,
		{{ ref('JoinSrcSortReject') }}.CCL_CRR_R,
		{{ ref('JoinSrcSortReject') }}.CCL_AD_TUC_INC_AMT_R,
		{{ ref('JoinSrcSortReject') }}.CCL_CCL_RATE_TYPE_CAT_ID_R,
		{{ ref('JoinSrcSortReject') }}.CCL_LINK_CCL_APP_ID_R,
		{{ ref('JoinSrcSortReject') }}.CCL_LINK_CCL_APP_PROD_ID_R,
		{{ ref('JoinSrcSortReject') }}.CCL_CHL_LMI_AMT_R,
		{{ ref('JoinSrcSortReject') }}.CCL_USED_IN_EXPOSURE_VIEW_FLAG_R,
		{{ ref('JoinSrcSortReject') }}.CCL_CCL_APP_BROKER_CIF_CODE_R,
		{{ ref('JoinSrcSortReject') }}.CCL_APP_ID_R,
		{{ ref('JoinSrcSortReject') }}.CCL_FIXED_INT_START_DATE_R,
		{{ ref('JoinSrcSortReject') }}.CCL_CHILD_PDCT_LEVEL_CAT_ID_R,
		{{ ref('JoinSrcSortReject') }}.CCL_PARENT_PDCT_LEVEL_CAT_ID_R,
		{{ ref('JoinSrcSortReject') }}.CPL_APP_PROD_ID_R,
		{{ ref('JoinSrcSortReject') }}.CPL_PL_TARGET_CAT_ID_R,
		{{ ref('JoinSrcSortReject') }}.CPL_REPAY_APPROX_AMT_R,
		{{ ref('JoinSrcSortReject') }}.CPL_REPAY_FREQUENCY_ID_R,
		{{ ref('JoinSrcSortReject') }}.CPL_PL_APP_PROD_REPAY_CAT_ID_R,
		{{ ref('JoinSrcSortReject') }}.CPL_PL_PROD_TERM_CAT_ID_R,
		{{ ref('JoinSrcSortReject') }}.CPL_PL_CAMPAIGN_CAT_ID_R,
		{{ ref('JoinSrcSortReject') }}.CPL_AD_HOC_CAMPAIGN_DESC_R,
		{{ ref('JoinSrcSortReject') }}.CPL_CAR_SEEKER_FLAG_R,
		{{ ref('JoinSrcSortReject') }}.CPL_PL_PROD_TARGET_CAT_ID_R,
		{{ ref('JoinSrcSortReject') }}.CPL_PL_MARKETING_SOURCE_CAT_ID_R,
		{{ ref('JoinSrcSortReject') }}.CPL_HLS_ACCT_NO_R,
		{{ ref('JoinSrcSortReject') }}.CPL_TOTAL_INTEREST_AMT_R,
		{{ ref('JoinSrcSortReject') }}.CPL_APP_PROD_AMT_R,
		{{ ref('JoinSrcSortReject') }}.CPL_TP_BROKER_ID_R,
		{{ ref('JoinSrcSortReject') }}.CPL_TP_BROKER_FIRST_NAME_R,
		{{ ref('JoinSrcSortReject') }}.CPL_TP_BROKER_LAST_NAME_R,
		{{ ref('JoinSrcSortReject') }}.CPL_TP_BROKER_GROUP_CAT_ID_R,
		{{ ref('JoinSrcSortReject') }}.COM_APP_PROD_ID_R,
		{{ ref('JoinSrcSortReject') }}.COM_SUBTYPE_CODE_R,
		{{ ref('JoinSrcSortReject') }}.COM_APP_ID_R,
		{{ ref('JoinSrcSortReject') }}.COM_PRODUCT_TYPE_ID_R,
		{{ ref('JoinSrcSortReject') }}.COM_SM_CASE_ID_R,
		{{ ref('JoinSrcSortReject') }}.COM_FOUND_FLAG_R,
		{{ ref('JoinSrcSortReject') }}.CPL_FOUND_FLAG_R,
		{{ ref('JoinSrcSortReject') }}.CCL_FOUND_FLAG_R,
		{{ ref('JoinSrcSortReject') }}.CC_FOUND_FLAG_R,
		{{ ref('JoinSrcSortReject') }}.CC_APP_PROD_ID_R,
		{{ ref('JoinSrcSortReject') }}.ABN_R,
		{{ ref('JoinSrcSortReject') }}.BUSINESS_NAME_R,
		{{ ref('JoinSrcSortReject') }}.SIMPLE_APP_FLAG_R,
		{{ ref('JoinSrcSortReject') }}.CHL_FOUND_FLAG_R,
		{{ ref('JoinSrcSortReject') }}.ORIG_ETL_D_R,
		{{ ref('SrcAPP_PROD_EXCLLks') }}.DUMMY_PDCT_F,
		{{ ref('JoinSrcSortReject') }}.CHL_CR_DATE,
		{{ ref('JoinSrcSortReject') }}.CHL_ASSESSMENT_DATE,
		{{ ref('JoinSrcSortReject') }}.CHL_NCPR_FLAG,
		{{ ref('JoinSrcSortReject') }}.CHL_CR_DATE_R,
		{{ ref('JoinSrcSortReject') }}.CHL_ASSESSMENT_DATE_R,
		{{ ref('JoinSrcSortReject') }}.CHL_NCPR_FLAG_R,
		OutCheckNullsSorted.APP_PROD_ID,
		OutCheckNullsSorted.CCHL_APP_PROD_ID,
		OutCheckNullsSorted.CLP_JOB_FAMILY_CAT_ID,
		OutCheckNullsSorted.CCL_APP_PROD_ID,
		OutCheckNullsSorted.CCL_PARENT_CCL_APP_PROD_ID,
		OutCheckNullsSorted.CCL_ACCOUNT_NUMBER,
		OutCheckNullsSorted.CCL_ACTUAL_RATE,
		OutCheckNullsSorted.CCL_BALLOON_PAY_AMT,
		OutCheckNullsSorted.CCL_BASIS_TYPE_CAT_ID,
		OutCheckNullsSorted.CCL_INTEREST_RATE_MARGIN,
		OutCheckNullsSorted.CCL_LOAN_TERM_MTH_NUM,
		OutCheckNullsSorted.CCL_CURRENT_LIMIT,
		OutCheckNullsSorted.CCL_INC_DEC_AMT,
		OutCheckNullsSorted.CCL_POST_APP_AMT,
		OutCheckNullsSorted.CCL_NEW_PROD_FLAG,
		OutCheckNullsSorted.CCL_INDEX_RATE,
		OutCheckNullsSorted.CCL_INTEREST_ADV_FLAG,
		OutCheckNullsSorted.CCL_INTERESTONLY_TERM_MTH_NUM,
		OutCheckNullsSorted.CCL_CAPPED_TERM_MTH_NUM,
		OutCheckNullsSorted.CCL_CAPPED_RATE,
		OutCheckNullsSorted.CCL_CRIS_PRODUCT_ID,
		OutCheckNullsSorted.CCL_CCL_LOAN_PURPOSE_ID,
		OutCheckNullsSorted.CCL_NEW_PROD_SUBTYPE_FLAG,
		OutCheckNullsSorted.CCL_TEMP_EXCESS_MTHS,
		OutCheckNullsSorted.CCL_LOAN_PURPOSE_CLASS_CODE,
		OutCheckNullsSorted.CCL_CCL_INTEREST_RATE_CAT_ID,
		OutCheckNullsSorted.CCL_CRR,
		OutCheckNullsSorted.CCL_AD_TUC_INC_AMT,
		OutCheckNullsSorted.CCL_CCL_RATE_TYPE_CAT_ID,
		OutCheckNullsSorted.CCL_LINK_CCL_APP_ID,
		OutCheckNullsSorted.CCL_LINK_CCL_APP_PROD_ID,
		OutCheckNullsSorted.CCL_CHL_LMI_AMT,
		OutCheckNullsSorted.CCL_USED_IN_EXPOSURE_VIEW_FLAG,
		OutCheckNullsSorted.CCL_CCL_APP_BROKER_CIF_CODE,
		OutCheckNullsSorted.CCL_APP_ID,
		OutCheckNullsSorted.CCL_FIXED_INT_START_DATE,
		OutCheckNullsSorted.CCL_CHILD_PDCT_LEVEL_CAT_ID,
		OutCheckNullsSorted.CCL_PARENT_PDCT_LEVEL_CAT_ID,
		OutCheckNullsSorted.CPL_APP_PROD_ID,
		OutCheckNullsSorted.CPL_PL_TARGET_CAT_ID,
		OutCheckNullsSorted.CPL_REPAY_APPROX_AMT,
		OutCheckNullsSorted.CPL_REPAY_FREQUENCY_ID,
		OutCheckNullsSorted.CPL_PL_APP_PROD_REPAY_CAT_ID,
		OutCheckNullsSorted.CPL_PL_PROD_TERM_CAT_ID,
		OutCheckNullsSorted.CPL_PL_CAMPAIGN_CAT_ID,
		OutCheckNullsSorted.CPL_AD_HOC_CAMPAIGN_DESC,
		OutCheckNullsSorted.CPL_CAR_SEEKER_FLAG,
		OutCheckNullsSorted.CPL_PL_PROD_TARGET_CAT_ID,
		OutCheckNullsSorted.CPL_PL_MARKETING_SOURCE_CAT_ID,
		OutCheckNullsSorted.CPL_HLS_ACCT_NO,
		OutCheckNullsSorted.CPL_TOTAL_INTEREST_AMT,
		OutCheckNullsSorted.CPL_APP_PROD_AMT,
		OutCheckNullsSorted.CPL_TP_BROKER_ID,
		OutCheckNullsSorted.CPL_TP_BROKER_FIRST_NAME,
		OutCheckNullsSorted.CPL_TP_BROKER_LAST_NAME,
		OutCheckNullsSorted.CPL_TP_BROKER_GROUP_CAT_ID,
		OutCheckNullsSorted.COM_APP_PROD_ID,
		OutCheckNullsSorted.COM_SUBTYPE_CODE,
		OutCheckNullsSorted.COM_APP_ID,
		OutCheckNullsSorted.COM_PRODUCT_TYPE_ID,
		OutCheckNullsSorted.COM_SM_CASE_ID,
		OutCheckNullsSorted.COM_FOUND_FLAG,
		OutCheckNullsSorted.CPL_FOUND_FLAG,
		OutCheckNullsSorted.CCL_FOUND_FLAG,
		OutCheckNullsSorted.CLP_FOUND_FLAG,
		OutCheckNullsSorted.CC_FOUND_FLAG,
		OutCheckNullsSorted.CC_APP_PROD_ID,
		OutCheckNullsSorted.ABN,
		OutCheckNullsSorted.BUSINESS_NAME,
		OutCheckNullsSorted.SIMPLE_APP_FLAG,
		OutCheckNullsSorted.CHL_FOUND_FLAG,
		OutRejRejectSorted.APP_PROD_ID AS APP_PROD_ID_R,
		OutRejRejectSorted.CCHL_APP_PROD_ID_R,
		OutRejRejectSorted.CCL_APP_PROD_ID_R,
		OutRejRejectSorted.CCL_PARENT_CCL_APP_PROD_ID_R,
		OutRejRejectSorted.CCL_ACCOUNT_NUMBER_R,
		OutRejRejectSorted.CCL_ACTUAL_RATE_R,
		OutRejRejectSorted.CCL_BALLOON_PAY_AMT_R,
		OutRejRejectSorted.CCL_BASIS_TYPE_CAT_ID_R,
		OutRejRejectSorted.CCL_INTEREST_RATE_MARGIN_R,
		OutRejRejectSorted.CCL_LOAN_TERM_MTH_NUM_R,
		OutRejRejectSorted.CCL_CURRENT_LIMIT_R,
		OutRejRejectSorted.CCL_INC_DEC_AMT_R,
		OutRejRejectSorted.CCL_POST_APP_AMT_R,
		OutRejRejectSorted.CCL_NEW_PROD_FLAG_R,
		OutRejRejectSorted.CCL_INDEX_RATE_R,
		OutRejRejectSorted.CCL_INTEREST_ADV_FLAG_R,
		OutRejRejectSorted.CCL_INTERESTONLY_TERM_MTH_NUM_R,
		OutRejRejectSorted.CCL_CAPPED_TERM_MTH_NUM_R,
		OutRejRejectSorted.CCL_CAPPED_RATE_R,
		OutRejRejectSorted.CCL_CRIS_PRODUCT_ID_R,
		OutRejRejectSorted.CCL_CCL_LOAN_PURPOSE_ID_R,
		OutRejRejectSorted.CCL_NEW_PROD_SUBTYPE_FLAG_R,
		OutRejRejectSorted.CCL_TEMP_EXCESS_MTHS_R,
		OutRejRejectSorted.CCL_LOAN_PURPOSE_CLASS_CODE_R,
		OutRejRejectSorted.CCL_CCL_INTEREST_RATE_CAT_ID_R,
		OutRejRejectSorted.CCL_CRR_R,
		OutRejRejectSorted.CCL_AD_TUC_INC_AMT_R,
		OutRejRejectSorted.CCL_CCL_RATE_TYPE_CAT_ID_R,
		OutRejRejectSorted.CCL_LINK_CCL_APP_ID_R,
		OutRejRejectSorted.CCL_LINK_CCL_APP_PROD_ID_R,
		OutRejRejectSorted.CCL_CHL_LMI_AMT_R,
		OutRejRejectSorted.CCL_USED_IN_EXPOSURE_VIEW_FLAG_R,
		OutRejRejectSorted.CCL_CCL_APP_BROKER_CIF_CODE_R,
		OutRejRejectSorted.CCL_APP_ID_R,
		OutRejRejectSorted.CCL_FIXED_INT_START_DATE_R,
		OutRejRejectSorted.CCL_CHILD_PDCT_LEVEL_CAT_ID_R,
		OutRejRejectSorted.CCL_PARENT_PDCT_LEVEL_CAT_ID_R,
		OutRejRejectSorted.CPL_APP_PROD_ID_R,
		OutRejRejectSorted.CPL_PL_TARGET_CAT_ID_R,
		OutRejRejectSorted.CPL_REPAY_APPROX_AMT_R,
		OutRejRejectSorted.CPL_REPAY_FREQUENCY_ID_R,
		OutRejRejectSorted.CPL_PL_APP_PROD_REPAY_CAT_ID_R,
		OutRejRejectSorted.CPL_PL_PROD_TERM_CAT_ID_R,
		OutRejRejectSorted.CPL_PL_CAMPAIGN_CAT_ID_R,
		OutRejRejectSorted.CPL_AD_HOC_CAMPAIGN_DESC_R,
		OutRejRejectSorted.CPL_CAR_SEEKER_FLAG_R,
		OutRejRejectSorted.CPL_PL_PROD_TARGET_CAT_ID_R,
		OutRejRejectSorted.CPL_PL_MARKETING_SOURCE_CAT_ID_R,
		OutRejRejectSorted.CPL_HLS_ACCT_NO_R,
		OutRejRejectSorted.CPL_TOTAL_INTEREST_AMT_R,
		OutRejRejectSorted.CPL_APP_PROD_AMT_R,
		OutRejRejectSorted.CPL_TP_BROKER_ID_R,
		OutRejRejectSorted.CPL_TP_BROKER_FIRST_NAME_R,
		OutRejRejectSorted.CPL_TP_BROKER_LAST_NAME_R,
		OutRejRejectSorted.CPL_TP_BROKER_GROUP_CAT_ID_R,
		OutRejRejectSorted.COM_APP_PROD_ID_R,
		OutRejRejectSorted.COM_SUBTYPE_CODE_R,
		OutRejRejectSorted.COM_APP_ID_R,
		OutRejRejectSorted.COM_PRODUCT_TYPE_ID_R,
		OutRejRejectSorted.COM_SM_CASE_ID_R,
		OutRejRejectSorted.COM_FOUND_FLAG_R,
		OutRejRejectSorted.CPL_FOUND_FLAG_R,
		OutRejRejectSorted.CCL_FOUND_FLAG_R,
		OutRejRejectSorted.CC_FOUND_FLAG_R,
		OutRejRejectSorted.CC_APP_PROD_ID_R,
		OutRejRejectSorted.ABN_R,
		OutRejRejectSorted.BUSINESS_NAME_R,
		OutRejRejectSorted.SIMPLE_APP_FLAG_R,
		OutRejRejectSorted.CHL_FOUND_FLAG_R,
		OutRejRejectSorted.ORIG_ETL_D_R,
		OutCheckNullsSorted.CHL_CR_DATE,
		OutCheckNullsSorted.CHL_ASSESSMENT_DATE,
		OutCheckNullsSorted.CHL_NCPR_FLAG,
		OutRejRejectSorted.CHL_CR_DATE_R,
		OutRejRejectSorted.CHL_ASSESSMENT_DATE_R,
		OutRejRejectSorted.CHL_NCPR_FLAG_R
	FROM {{ ref('JoinSrcSortReject') }}
	LEFT JOIN {{ ref('SrcAPP_PROD_EXCLLks') }} ON 
)

SELECT * FROM LuAppProdExcl