WITH
tmp_appt_pdct AS (
    SELECT
    *
    FROM
        {{ cvar('stg_ctl_db') }}.{{ cvar('gdw_stg_db') }}.TMP_APPT_PDCT ),
appt_pdct AS (
    SELECT
    *
    FROM
        {{ cvar('stg_ctl_db') }}.{{ cvar('gdw_acct_vw') }}.appt_pdct
    ),
   
SrcTmpApptPdctTera AS
(SELECT
    a.APPT_PDCT_I AS NEW_APPT_PDCT_I,
    a.DEBT_ABN_X AS NEW_DEBT_ABN_X,
    a.DEBT_BUSN_M AS NEW_DEBT_BUSN_M,
    a.SMPL_APPT_F AS NEW_SMPL_APPT_F,
    a.CLP_JOB_FAMILY_CAT_ID AS NEW_JOB_COMM_CATG_C,
    a.APPT_QLFY_C AS NEW_APPT_QLFY_C,
    a.ACQR_TYPE_C AS NEW_ACQR_TYPE_C,
    a.ACQR_ADHC_X AS NEW_ACQR_ADHC_X,
    a.ACQR_SRCE_C AS NEW_ACQR_SRCE_C,
    a.PDCT_N AS NEW_PDCT_N,
    a.APPT_I AS NEW_APPT_I,
    a.SRCE_SYST_C AS NEW_SRCE_SYST_C,
    a.SRCE_SYST_APPT_PDCT_I AS NEW_SRCE_SYST_APPT_PDCT_I,
    a.LOAN_FNDD_METH_C AS NEW_LOAN_FNDD_METH_C,
    a.NEW_ACCT_F AS NEW_NEW_ACCT_F,
    a.BROK_PATY_I AS NEW_BROK_PATY_I,
    a.COPY_FROM_OTHR_APPT_F AS NEW_COPY_FROM_OTHR_APPT_F,
    a.APPT_PDCT_CATG_C AS NEW_APPT_PDCT_CATG_C,
    a.APPT_PDCT_DURT_C AS NEW_APPT_PDCT_DURT_C,
    a.ASES_D AS NEW_ASES_D,
    b.APPT_PDCT_I AS OLD_APPT_PDCT_I,
    b.DEBT_ABN_X AS OLD_DEBT_ABN_X,
    b.DEBT_BUSN_M AS OLD_DEBT_BUSN_M,
    b.JOB_COMM_CATG_C AS OLD_JOB_COMM_CATG_C,
    b.APPT_QLFY_C AS OLD_APPT_QLFY_C,
    b.ACQR_TYPE_C AS OLD_ACQR_TYPE_C,
    b.ACQR_ADHC_X AS OLD_ACQR_ADHC_X,
    b.ACQR_SRCE_C AS OLD_ACQR_SRCE_C,
    b.PDCT_N AS OLD_PDCT_N,
    b.APPT_I AS OLD_APPT_I,
    b.SRCE_SYST_C AS OLD_SRCE_SYST_C,
    b.SRCE_SYST_APPT_PDCT_I AS OLD_SRCE_SYST_APPT_PDCT_I,
    b.LOAN_FNDD_METH_C AS OLD_LOAN_FNDD_METH_C,
    b.NEW_ACCT_F AS OLD_NEW_ACCT_F,
    b.BROK_PATY_I AS OLD_BROK_PATY_I,
    b.COPY_FROM_OTHR_APPT_F AS OLD_COPY_FROM_OTHR_APPT_F,
    b.EFFT_D AS OLD_EFFT_D,
    b.SMPL_APPT_F AS OLD_SMPL_APPT_F,
    b.APPT_PDCT_CATG_C AS OLD_APPT_PDCT_CATG_C,
    b.APPT_PDCT_DURT_C AS OLD_APPT_PDCT_DURT_C,
    b.ASES_D AS OLD_ASES_D
 FROM tmp_appt_pdct a
 LEFT OUTER JOIN appt_pdct b
 ON TRIM(a.APPT_PDCT_I) = TRIM(b.APPT_PDCT_I)
 AND b.EXPY_D = '9999-12-31'
 WHERE a.RUN_STRM = '{{ cvar("run_stream") }}'

)
 
SELECT * FROM SrcTmpApptPdctTera