{{ config(materialized='view', tags=['MergeAppCclAppChlApp']) }}

WITH Identify_APP AS (
	SELECT
		{{ ref('JoinAppCclAppChlAppChlTpb') }}.APP_CCL_APP_APP_ID AS APP_ID,
		APP_APP_ID,
		APP_SUBTYPE_CODE,
		APP_APP_NO,
		APP_CREATED_DATE,
		APP_CREATED_BY_STAFF_NUMBER,
		APP_OWNED_BY_STAFF_NUMBER,
		APP_CHANNEL_CAT_ID,
		APP_LODGEMENT_BRANCH_ID,
		APP_SM_CASE_ID,
		CCL_APP_CCL_APP_ID,
		CCL_APP_CCL_APP_CAT_ID,
		CCL_APP_CCL_FORM_CAT_ID,
		CCL_APP_TOT_PERSONAL_FAC_AMT,
		CCL_APP_TOT_EQUIPFIN_FAC_AMT,
		CCL_APP_TOT_COMMERCIAL_FAC_AMT,
		CCL_APP_TOPUP_APP_ID,
		CCL_APP_AF_PRIMARY_INDUSTRY_ID,
		CCL_APP_AD_TUC_AMT,
		CCL_APP_COMMISSION_AMT,
		CCL_APP_BROKER_REFERAL_FLAG,
		CHL_APP_HL_APP_ID,
		CHL_APP_HL_PACKAGE_CAT_ID,
		CHL_APP_LPC_OFFICE,
		CHL_APP_STATUS_TRACKER_ID,
		CHL_APP_PCD_EXTERNAL_SYS_CAT_ID,
		APP_FOUND_FLAG,
		CCL_APP_FOUND_FLAG,
		CHL_APP_FOUND_FLAG,
		CHL_TPB_HL_APP_ID,
		CHL_TPB_SUBTYPE_CODE,
		REL_MANAGER_STATE_ID,
		DATE_RECEIVED,
		-- *SRC*: ( IF IsNotNull((OutDropColumns.CHL_TPB_FOUND_FLAG)) THEN (OutDropColumns.CHL_TPB_FOUND_FLAG) ELSE ('N')),
		IFF({{ ref('JoinAppCclAppChlAppChlTpb') }}.CHL_TPB_FOUND_FLAG IS NOT NULL, {{ ref('JoinAppCclAppChlAppChlTpb') }}.CHL_TPB_FOUND_FLAG, 'N') AS CHL_TPB_FOUND_FLAG,
		HL_BUSN_CHNL_CAT_I
	FROM {{ ref('JoinAppCclAppChlAppChlTpb') }}
	WHERE 
)

SELECT * FROM Identify_APP