{{ config(materialized='view', tags=['MergeAppCclAppChlApp']) }}

WITH Remove_Duplicates_38 AS (
	SELECT CHL_APP_RECORD_TYPE, CHL_APP_MOD_TIMESTAMP, CHL_APP_HL_APP_ID, CHL_APP_HL_PACKAGE_CAT_ID, CHL_APP_LPC_OFFICE, CHL_APP_STATUS_TRACKER_ID, CHL_APP_PCD_EXTERNAL_SYS_CAT_ID, CHL_APP_SIMPLE_APP_FLAG, CHL_APP_ORIGINATING_AGENT_ID, CHL_APP_AGENT_NAME, CHL_APP_DUMMY 
	FROM (
		SELECT CHL_APP_RECORD_TYPE, CHL_APP_MOD_TIMESTAMP, CHL_APP_HL_APP_ID, CHL_APP_HL_PACKAGE_CAT_ID, CHL_APP_LPC_OFFICE, CHL_APP_STATUS_TRACKER_ID, CHL_APP_PCD_EXTERNAL_SYS_CAT_ID, CHL_APP_SIMPLE_APP_FLAG, CHL_APP_ORIGINATING_AGENT_ID, CHL_APP_AGENT_NAME, CHL_APP_DUMMY,
		 ROW_NUMBER() OVER (PARTITION BY CHL_APP_HL_APP_ID ORDER BY 1 ASC) AS ROW_NUM 
		FROM {{ ref('SrcChlBusApp') }}
	) AS Remove_Duplicates_38_TEMP
	WHERE ROW_NUM = 1
)

SELECT * FROM Remove_Duplicates_38