{{ config(materialized='incremental', alias='_cba__app_csel4_dev_dataset_cse__cpl__bus__app__prod__plappprod__nulls__rejects', incremental_strategy='insert_overwrite', tags=['ExtPL_APP_PROD']) }}

SELECT
	PL_APP_PROD_ID,
	PL_TARGET_CAT_ID,
	REPAY_APPROX_AMT,
	REPAY_FREQUENCY_ID,
	PL_APP_PROD_REPAY_CAT_ID,
	PL_PROD_TERM_CAT_ID,
	PL_CAMPAIGN_CAT_ID,
	AD_HOC_CAMPAIGN_DESC,
	CAR_SEEKER_FLAG,
	PL_PROD_TARGET_CAT_ID,
	PL_MARKETING_SOURCE_CAT_ID,
	HLS_ACCT_NO,
	TOTAL_INTEREST_AMT,
	APP_PROD_AMT,
	TP_BROKER_ID,
	TP_BROKER_FIRST_NAME,
	TP_BROKER_LAST_NAME,
	TP_BROKER_GROUP_CAT_ID,
	READ_COSTS_AND_RISKS_FLAG,
	ACCEPTS_COSTS_AND_RISKS_DATE,
	ETL_D,
	ORIG_ETL_D,
	EROR_C 
FROM {{ ref('XfmCheckCCAppProdIdNulls__OutPLAppProdIdNullsDS') }}