{{ config(materialized='view', tags=['ExtPL_APP_PROD']) }}

WITH Remove_Duplicates_220 AS (
	SELECT PL_APP_PROD_ID, PL_TARGET_CAT_ID, REPAY_APPROX_AMT, REPAY_FREQUENCY_ID, PL_APP_PROD_REPAY_CAT_ID, PL_PROD_TERM_CAT_ID, PL_CAMPAIGN_CAT_ID, AD_HOC_CAMPAIGN_DESC, CAR_SEEKER_FLAG, PL_PROD_TARGET_CAT_ID, PL_MARKETING_SOURCE_CAT_ID, HLS_ACCT_NO, TOTAL_INTEREST_AMT, APP_PROD_AMT, TP_BROKER_ID, TP_BROKER_FIRST_NAME, TP_BROKER_LAST_NAME, TP_BROKER_GROUP_CAT_ID, READ_COSTS_AND_RISKS_FLAG, ACCEPTS_COSTS_AND_RISKS_DATE 
	FROM (
		SELECT PL_APP_PROD_ID, PL_TARGET_CAT_ID, REPAY_APPROX_AMT, REPAY_FREQUENCY_ID, PL_APP_PROD_REPAY_CAT_ID, PL_PROD_TERM_CAT_ID, PL_CAMPAIGN_CAT_ID, AD_HOC_CAMPAIGN_DESC, CAR_SEEKER_FLAG, PL_PROD_TARGET_CAT_ID, PL_MARKETING_SOURCE_CAT_ID, HLS_ACCT_NO, TOTAL_INTEREST_AMT, APP_PROD_AMT, TP_BROKER_ID, TP_BROKER_FIRST_NAME, TP_BROKER_LAST_NAME, TP_BROKER_GROUP_CAT_ID, READ_COSTS_AND_RISKS_FLAG, ACCEPTS_COSTS_AND_RISKS_DATE,
		 ROW_NUMBER() OVER (PARTITION BY PL_APP_PROD_ID ORDER BY 1 ASC) AS ROW_NUM 
		FROM {{ ref('CpyPLAppProdSeq') }}
	) AS Remove_Duplicates_220_TEMP
	WHERE ROW_NUM = 1
)

SELECT * FROM Remove_Duplicates_220