{{ config(materialized='view', tags=['LdREJT_APPT_QSTN']) }}

WITH FunRejectsNulls AS (
	SELECT
		APP_ID as APP_ID,
		SUBTYPE_CODE as SUBTYPE_CODE,
		QA_QUESTION_ID as QA_QUESTION_ID,
		QA_ANSWER_ID as QA_ANSWER_ID,
		TEXT_ANSWER as TEXT_ANSWER,
		CIF_CODE as CIF_CODE,
		ETL_D as ETL_D,
		ORIG_ETL_D as ORIG_ETL_D,
		EROR_C as EROR_C
	FROM {{ ref('SrcIdNullsDS') }}
	UNION ALL
	SELECT
		APP_ID,
		SUBTYPE_CODE,
		QA_QUESTION_ID,
		QA_ANSWER_ID,
		TEXT_ANSWER,
		CIF_CODE,
		ETL_D,
		ORIG_ETL_D,
		EROR_C
	FROM {{ ref('SrcAppCclAppRejectsDS') }}
)

SELECT * FROM FunRejectsNulls