-- Account Balance Insert Procedure (Converted from BTEQ)
-- Original: ACCT_BALN_BKDT_ISRT.sql
-- Description: Populate ACCTs into ACCT BALN with modified adjustments

CREATE OR REPLACE PROCEDURE ACCT_BALN_BKDT_INSERT_PROC(
    PROD_DATABASE STRING DEFAULT 'CAD_PROD_DATA',
    STAGING_DATABASE STRING DEFAULT 'DDSTG'
)
RETURNS STRING
LANGUAGE SQL
AS
$$
DECLARE
    rows_inserted INTEGER;
    result_msg STRING;
BEGIN
    INSERT INTO IDENTIFIER(PROD_DATABASE || '.ACCT_BALN_BKDT')
    (ACCT_I, BALN_TYPE_C, CALC_FUNC_C, TIME_PERD_C, BALN_A, CALC_F,
     SRCE_SYST_C, ORIG_SRCE_SYST_C, LOAD_D, BKDT_EFFT_D, BKDT_EXPY_D,
     PROS_KEY_EFFT_I, PROS_KEY_EXPY_I, BKDT_PROS_KEY_I)
    SELECT 
        ACCT_I, BALN_TYPE_C, CALC_FUNC_C, TIME_PERD_C, BALN_A, CALC_F,
        SRCE_SYST_C, ORIG_SRCE_SYST_C, LOAD_D, BKDT_EFFT_D, BKDT_EXPY_D,
        PROS_KEY_EFFT_I, PROS_KEY_EXPY_I, BKDT_PROS_KEY_I
    FROM IDENTIFIER(STAGING_DATABASE || '.ACCT_BALN_BKDT_STG2');
    
    rows_inserted := SQLROWCOUNT;
    result_msg := 'Successfully inserted ' || rows_inserted || ' records';
    RETURN result_msg;
EXCEPTION
    WHEN OTHER THEN
        RETURN 'Error: ' || SQLERRM;
END;
$$; 