{{ config(materialized='view', tags=['UtilProcessMetaDataTC']) }}

WITH 
,
SYNC_TBL AS (SELECT A.PROS_KEY_I, TRGT_M, TRLR_RECD_ISRT_Q, TRLR_RECD_UPDT_Q, TRLR_RECD_DELT_Q, INS_CNT, UPD_CNT, DEL_CNT, REJ_CNT, MIS_ROW_CNT, ERR_CNT1, ERR_CNT2, DUP_KEY_CNT, START_T, END_T FROM (SELECT PROS_KEY_I, CAST(TRGT_M AS VARCHAR(40)) AS TRGT_M, TRLR_RECD_ISRT_Q, TRLR_RECD_UPDT_Q, TRLR_RECD_DELT_Q FROM UTIL_PROS_ISAC WHERE PROS_KEY_I = {{ var("pTD_SYNC_ID") }}) AS A INNER JOIN (SELECT CAST(SYNCID AS DECIMAL(10)) AS PROS_KEY_I, SUM(INSERTCOUNT) AS INS_CNT, SUM(UPDATECOUNT) AS UPD_CNT, SUM(DELETECOUNT) AS DEL_CNT, SUM(REJECTCOUNT) AS REJ_CNT, SUM(MISSINGROWCOUNT) AS MIS_ROW_CNT, SUM(ERRORCOUNT1) AS ERR_CNT1, SUM(ERRORCOUNT2) AS ERR_CNT2, SUM(DUPLICATEKEYCOUNT) AS DUP_KEY_CNT, MIN(StartTime) AS START_T, MAX(EndTime) AS END_T FROM UNID_PATY_GNRC_SYNC WHERE SYNCID = {{ var("pTD_SYNC_ID") }} GROUP BY 1) AS B ON A.PROS_KEY_I = B.PROS_KEY_I)


SELECT * FROM SYNC_TBL