{{ config(materialized='view', tags=['ExtReasonSmCaseState']) }}

WITH 
rejt_com_bus_reas_sm_case_stat AS (
	SELECT
	*
	FROM {{ source("cse4_stg","rejt_com_bus_reas_sm_case_stat")  }}),
SrcRejtSmCaseStateReasonRejectOra AS (SELECT SM_CASE_STATE_ID, SCS_SM_CASE_ID, SCS_SM_STATE_CAT_ID, SCS_START_DATE, SCS_END_DATE, SCS_CREATED_BY_STAFF_NUMBER, SCS_STATE_CAUSED_BY_ACTION_ID, SCSR_SM_CASE_STATE_REASON_ID, SCSR_SM_REASON_CAT_ID, SM_CASE_STATE_REAS_FOUND_FLAG, SM_CASE_STATE_FOUND_FLAG, CAST(ORIG_ETL_D AS TEXT) AS ORIG_ETL_D FROM REJT_COM_BUS_REAS_SM_CASE_STAT WHERE EROR_C LIKE 'RPR%')


SELECT * FROM SrcRejtSmCaseStateReasonRejectOra