{{ config(materialized='view', tags=['DltAPPTTBPFrmTMP_APPT']) }}

WITH 
tmp_appt AS (
	SELECT
	*
	FROM {{ ref("tmp_appt")  }}),
appt AS (
	SELECT
	*
	FROM {{ ref("appt")  }}),
SrcTmpApptTera AS (SELECT a.APPT_I AS NEW_APPT_I, a.APPT_C AS NEW_APPT_C, a.APPT_FORM_C AS NEW_APPT_FORM_C, a.APPT_QLFY_C AS NEW_APPT_QLFY_C, a.STUS_TRAK_I AS NEW_STUS_TRAK_I, a.APPT_ORIG_C AS NEW_APPT_ORIG_C, a.APPT_N AS NEW_APPT_N, a.SRCE_SYST_C AS NEW_SRCE_SYST_C, a.SRCE_SYST_APPT_I AS NEW_SRCE_SYST_APPT_I, a.APPT_CRAT_D AS NEW_APPT_CRAT_D, a.RATE_SEEK_F AS NEW_RATE_SEEK_F, a.ORIG_APPT_SRCE_C AS NEW_APPT_ORIG_SYST_C, a.APPT_RECV_S AS NEW_APPT_RECV_S, a.REL_MGR_STAT_C AS NEW_REL_MGR_STAT_C, a.APPT_RECV_D AS NEW_APPT_RECV_D, CAST(a.APPT_RECV_T AS CHAR(8)) AS NEW_APPT_RECV_T, b.APPT_I AS OLD_APPT_I, b.APPT_C AS OLD_APPT_C, b.APPT_FORM_C AS OLD_APPT_FORM_C, b.STUS_TRAK_I AS OLD_STUS_TRAK_I, b.APPT_ORIG_C AS OLD_APPT_ORIG_C, b.RATE_SEEK_F AS OLD_RATE_SEEK_F, b.ORIG_APPT_SRCE_C AS OLD_APPT_ORIG_SYST_C, b.APPT_RECV_S AS OLD_APPT_RECV_S, b.REL_MGR_STAT_C AS OLD_REL_MGR_STAT_C, b.APPT_RECV_D AS OLD_APPT_RECV_D, CAST(b.APPT_RECV_T AS CHAR(8)) AS OLD_APPT_RECV_T FROM TMP_APPT LEFT OUTER JOIN APPT ON TRIM(a.APPT_I) = TRIM(b.APPT_I) WHERE a.RUN_STRM = '{{ var("RUN_STREAM") }}')


SELECT * FROM SrcTmpApptTera