{{ config(materialized='view', tags=['ExtCSE_CCL_BUS_APP_FEE']) }}

WITH XfmCheckCCL_APP_FEE_IDNulls__OutCCL_APP_FEE_IDNullsDS AS (
	SELECT
		-- *SRC*: \(20)If (Len(Trim(( IF IsNotNull((OutJoin.CCL_APP_FEE_ID)) THEN (OutJoin.CCL_APP_FEE_ID) ELSE ""))) = 0) Then 'REJ2001' Else '',
		IFF(LEN(TRIM(IFF({{ ref('JoinSources') }}.CCL_APP_FEE_ID IS NOT NULL, {{ ref('JoinSources') }}.CCL_APP_FEE_ID, ''))) = 0, 'REJ2001', '') AS ErrorCode,
		CCL_APP_FEE_ID,
		CCL_APP_FEE_CCL_APP_ID,
		CCL_APP_FEE_CCL_APP_PROD_ID,
		CCL_APP_FEE_CHARGE_AMT,
		CCL_APP_FEE_CHARGE_DATE,
		CCL_APP_FEE_CONCESSION_FLAG,
		CCL_APP_FEE_CONCESSION_REASON,
		CCL_APP_FEE_OVERRIDE_FEE_PCT,
		CCL_APP_FEE_OVERRIDE_FEE_PCT_FREQ,
		CCL_APP_FEE_FEE_REPAYMENT_FREQ,
		{{ ref('JoinSources') }}.CCL_FEE_TYPE_CAT_ID AS CCL_APP_FEE_TYPE_CAT_ID,
		CCL_APP_FEE_CHARGE_EXTERNAL_FLAG,
		CCL_FEE_TYPE_CAT_ID,
		CCL_FEE_TYPE_CAT_DEFAULT_AMT,
		CCL_FEE_TYPE_CAT_DEFAULT_FEE_PCT,
		CCL_FEE_TYPE_CAT_FEE_TYPE_DESC,
		ETL_PROCESS_DT AS ETL_D,
		ETL_PROCESS_DT AS ORIG_ETL_D,
		ErrorCode AS EROR_C
	FROM {{ ref('JoinSources') }}
	WHERE SUBSTRING(ErrorCode, 1, 3) = 'REJ'
)

SELECT * FROM XfmCheckCCL_APP_FEE_IDNulls__OutCCL_APP_FEE_IDNullsDS