{{ config(materialized='incremental', alias='tdcsdstg.tmp_fa_clnt_utak', incremental_strategy='append', tags=['LdTMP_FA_CLIENT_UNDERTAKINGFrmXfm']) }}

SELECT
	INT_GRUP_I
	REL_I
	SRCE_SYST_PATY_INT_GRUP_I
	SRCE_SYST_REL_I
	ORIG_SRCE_SYST_PATY_I
	ORIG_SRCE_SYST_PATY_TYPE_C
	PRIM_CLNT_F
	PATY_I
	SRCE_SYST_C
	PATY_INT_GRUP_F
	REL_TYPE_C_PRIM
	PATY_ROLE_C
	REL_STUS_C
	REL_EFFT_D
	REL_EXPY_D
	REL_REAS_C
	REL_LEVL_C_PRIM
	RELD_PATY_I_PRIM
	PATY_REL_PRIM_F
	REL_TYPE_C_CHLD
	REL_LEVL_C_CHLD
	RELD_PATY_I_CHILD
	PATY_REL_CHLD_F
	CSE_FA_CLNT_UNTK_ID
	CSE_FA_UNTK_ID
	CSE_COIN_ENTY_ID
	CSE_CLNT_CORR_ID
	CSE_FA_ENTY_CAT_ID
	CSE_FA_CHLD_STAT_CAT_ID
	CSE_CLNT_REL_TYPE_ID
	CSE_CLNT_POSN
	CSE_IS_PRIM_FLAG
	CSE_CIF_CODE
	CSE_ORIG_ETL_D 
FROM {{ ref('SrcFAClientUndertakingDS') }}