-- Count query for STARCADPRODDATA.ACCT_BALN_ADJ
-- Snowflake table: PS_CLD_RW.STARCADPRODDATA.ACCT_BALN_ADJ
-- Teradata counterpart: STARCADPRODDATA.ACCT_BALN_ADJ

SELECT count(1) AS record_count
FROM STARCADPRODDATA.ACCT_BALN_ADJ; 