-- Count query for PDCBODS.MSTR_CNCT_BALN_TRNF_PRTP
-- Snowflake table: PS_CLD_RW.PDCBODS.MSTR_CNCT_BALN_TRNF_PRTP
-- Teradata counterpart: PDCBODS.MSTR_CNCT_BALN_TRNF_PRTP

SELECT count(1) AS record_count
FROM PDCBODS.MSTR_CNCT_BALN_TRNF_PRTP; 