-- Count query for PDCBODS.MSTR_CNCT_MSTR_DATA_GENL
-- Snowflake table: PS_CLD_RW.PDCBODS.MSTR_CNCT_MSTR_DATA_GENL
-- Teradata counterpart: PDCBODS.MSTR_CNCT_MSTR_DATA_GENL

SELECT count(1) AS record_count
FROM PDCBODS.MSTR_CNCT_MSTR_DATA_GENL; 