-- Count query for STARCADPRODDATA.DERV_PRTF_PATY_PSST
-- Snowflake table: PS_CLD_RW.STARCADPRODDATA.DERV_PRTF_PATY_PSST
-- Teradata counterpart: STARCADPRODDATA.DERV_PRTF_PATY_PSST

SELECT count(1) AS record_count
FROM STARCADPRODDATA.DERV_PRTF_PATY_PSST; 