-- Count query for STARCADPRODDATA.DERV_PRTF_ACCT_REL
-- Snowflake table: PS_CLD_RW.STARCADPRODDATA.DERV_PRTF_ACCT_REL
-- Teradata counterpart: STARCADPRODDATA.DERV_PRTF_ACCT_REL

SELECT count(1) AS record_count
FROM STARCADPRODDATA.DERV_PRTF_ACCT_REL; 