-- Count query for PVTECH.ACCT_BALN_BKDT_RECN
-- Snowflake table: PS_CLD_RW.STARCADPRODDATA.ACCT_BALN_BKDT_RECN
-- Teradata counterpart: PVTECH.ACCT_BALN_BKDT_RECN

SELECT count(1) AS record_count
FROM PVTECH.ACCT_BALN_BKDT_RECN; 