-- Count query for STAR_CAD_PROD_DATA.ACCT_BALN_BKDT_AUDT
-- Snowflake table: PS_CLD_RW.STARCADPRODDATA.ACCT_BALN_BKDT_AUDT
-- Teradata counterpart: STAR_CAD_PROD_DATA.ACCT_BALN_BKDT_AUDT

SELECT count(1) AS record_count
FROM STAR_CAD_PROD_DATA.ACCT_BALN_BKDT_AUDT; 