-- Count query for PVTECH.ACCT_INT_GRUP (mapped to PP01STARCADPRODDATA)
-- Snowflake table: PS_CLD_RW.PP01STARCADPRODDATA.ACCT_INT_GRUP
-- Teradata counterpart: PVTECH.ACCT_INT_GRUP

SELECT count(1) AS record_count
FROM PVTECH.ACCT_INT_GRUP; 