-- Count query for STAR_CAD_PROD_DATA.DERV_PRTF_PATY_OWN_REL
-- Snowflake table: PS_CLD_RW.STARCADPRODDATA.DERV_PRTF_PATY_OWN_REL
-- Teradata counterpart: STAR_CAD_PROD_DATA.DERV_PRTF_PATY_OWN_REL

SELECT count(1) AS record_count
FROM STAR_CAD_PROD_DATA.DERV_PRTF_PATY_OWN_REL; 