{{ config(materialized='view', tags=['MergeAppProdCclAppProdPlAppProd']) }}

WITH JoinAppProd5 AS (
	SELECT
		{{ ref('OutTransforms') }}.APP_PROD_ID AS CHL_APP_PROD_ID,
		{{ ref('OutTransforms') }}.CC_APP_PROD_ID,
		{{ ref('OutTransforms') }}.ABN,
		{{ ref('OutTransforms') }}.BUSINESS_NAME,
		{{ ref('OutTransforms') }}.CLP_JOB_FAMILY_CAT_ID,
		{{ ref('OutTransforms') }}.CCL_APP_PROD_ID,
		{{ ref('OutTransforms') }}.CCL_PARENT_CCL_APP_PROD_ID,
		{{ ref('OutTransforms') }}.CCL_ACCOUNT_NUMBER,
		{{ ref('OutTransforms') }}.CCL_ACTUAL_RATE,
		{{ ref('OutTransforms') }}.CCL_BALLOON_PAY_AMT,
		{{ ref('OutTransforms') }}.CCL_BASIS_TYPE_CAT_ID,
		{{ ref('OutTransforms') }}.CCL_INTEREST_RATE_MARGIN,
		{{ ref('OutTransforms') }}.CCL_LOAN_TERM_MTH_NUM,
		{{ ref('OutTransforms') }}.CCL_CURRENT_LIMIT,
		{{ ref('OutTransforms') }}.CCL_INC_DEC_AMT,
		{{ ref('OutTransforms') }}.CCL_POST_APP_AMT,
		{{ ref('OutTransforms') }}.CCL_NEW_PROD_FLAG,
		{{ ref('OutTransforms') }}.CCL_INDEX_RATE,
		{{ ref('OutTransforms') }}.CCL_INTEREST_ADV_FLAG,
		{{ ref('OutTransforms') }}.CCL_INTERESTONLY_TERM_MTH_NUM,
		{{ ref('OutTransforms') }}.CCL_CAPPED_TERM_MTH_NUM,
		{{ ref('OutTransforms') }}.CCL_CAPPED_RATE,
		{{ ref('OutTransforms') }}.CCL_CRIS_PRODUCT_ID,
		{{ ref('OutTransforms') }}.CCL_CCL_LOAN_PURPOSE_ID,
		{{ ref('OutTransforms') }}.CCL_NEW_PROD_SUBTYPE_FLAG,
		{{ ref('OutTransforms') }}.CCL_TEMP_EXCESS_MTHS,
		{{ ref('OutTransforms') }}.CCL_LOAN_PURPOSE_CLASS_CODE,
		{{ ref('OutTransforms') }}.CCL_CCL_INTEREST_RATE_CAT_ID,
		{{ ref('OutTransforms') }}.CCL_CRR,
		{{ ref('OutTransforms') }}.CCL_AD_TUC_INC_AMT,
		{{ ref('OutTransforms') }}.CCL_CCL_RATE_TYPE_CAT_ID,
		{{ ref('OutTransforms') }}.CCL_LINK_CCL_APP_ID,
		{{ ref('OutTransforms') }}.CCL_LINK_CCL_APP_PROD_ID,
		{{ ref('OutTransforms') }}.CCL_CHL_LMI_AMT,
		{{ ref('OutTransforms') }}.CCL_USED_IN_EXPOSURE_VIEW_FLAG,
		{{ ref('OutTransforms') }}.CCL_CCL_APP_BROKER_CIF_CODE,
		{{ ref('OutTransforms') }}.CCL_APP_ID,
		{{ ref('OutTransforms') }}.CCL_FIXED_INT_START_DATE,
		{{ ref('OutTransforms') }}.CCL_CHILD_PDCT_LEVEL_CAT_ID,
		{{ ref('OutTransforms') }}.CCL_PARENT_PDCT_LEVEL_CAT_ID,
		{{ ref('OutTransforms') }}.CPL_COM_APP_PROD_ID,
		{{ ref('OutTransforms') }}.CPL_APP_PROD_ID,
		{{ ref('OutTransforms') }}.CPL_PL_TARGET_CAT_ID,
		{{ ref('OutTransforms') }}.CPL_REPAY_APPROX_AMT,
		{{ ref('OutTransforms') }}.CPL_REPAY_FREQUENCY_ID,
		{{ ref('OutTransforms') }}.CPL_PL_APP_PROD_REPAY_CAT_ID,
		{{ ref('OutTransforms') }}.CPL_PL_PROD_TERM_CAT_ID,
		{{ ref('OutTransforms') }}.CPL_PL_CAMPAIGN_CAT_ID,
		{{ ref('OutTransforms') }}.CPL_AD_HOC_CAMPAIGN_DESC,
		{{ ref('OutTransforms') }}.CPL_CAR_SEEKER_FLAG,
		{{ ref('OutTransforms') }}.CPL_PL_PROD_TARGET_CAT_ID,
		{{ ref('OutTransforms') }}.CPL_PL_MARKETING_SOURCE_CAT_ID,
		{{ ref('OutTransforms') }}.CPL_HLS_ACCT_NO,
		{{ ref('OutTransforms') }}.CPL_TOTAL_INTEREST_AMT,
		{{ ref('OutTransforms') }}.CPL_APP_PROD_AMT,
		{{ ref('OutTransforms') }}.CPL_TP_BROKER_ID,
		{{ ref('OutTransforms') }}.CPL_TP_BROKER_FIRST_NAME,
		{{ ref('OutTransforms') }}.CPL_TP_BROKER_LAST_NAME,
		{{ ref('OutTransforms') }}.CPL_TP_BROKER_GROUP_CAT_ID,
		{{ ref('OutTransforms') }}.COM_APP_PROD_ID,
		{{ ref('OutTransforms') }}.COM_SUBTYPE_CODE,
		{{ ref('OutTransforms') }}.COM_APP_ID,
		{{ ref('OutTransforms') }}.COM_PRODUCT_TYPE_ID,
		{{ ref('OutTransforms') }}.COM_SM_CASE_ID,
		{{ ref('OutTransforms') }}.COM_FOUND_FLAG,
		{{ ref('OutTransforms') }}.CPL_FOUND_FLAG,
		{{ ref('OutTransforms') }}.CCL_FOUND_FLAG,
		{{ ref('OutTransforms') }}.CLP_FOUND_FLAG,
		{{ ref('OutTransforms') }}.CC_FOUND_FLAG,
		{{ ref('CgAdd_Flag6') }}.APP_PROD_ID AS CCHL_APP_PROD_ID,
		{{ ref('CgAdd_Flag6') }}.CHL_APP_SIMPLE_APP_FLAG AS SIMPLE_APP_FLAG,
		{{ ref('CgAdd_Flag6') }}.CHL_FOUND_FLAG,
		{{ ref('CgAdd_Flag6') }}.CR_DATE AS CHL_CR_DATE,
		{{ ref('CgAdd_Flag6') }}.ASSESSMENT_DATE AS CHL_ASSESSMENT_DATE,
		{{ ref('CgAdd_Flag6') }}.NCPR_FLAG AS CHL_NCPR_FLAG
	FROM {{ ref('CgAdd_Flag6') }}
	OUTER JOIN {{ ref('OutTransforms') }} ON {{ ref('CgAdd_Flag6') }}.APP_PROD_ID = {{ ref('OutTransforms') }}.APP_PROD_ID
)

SELECT * FROM JoinAppProd5