{{ config(materialized='view', tags=['LdTmp_Appt_QstnFrmXfm']) }}

WITH Remove_Duplicates AS (
	SELECT APPT_I, QSTN_C, RESP_C, RESP_CMMT_X, PATY_I, EFFT_D, EXPY_D, ROW_SECU_ACCS_C, PROS_KEY_EFFT_I, PROS_KEY_EXPY_I, EROR_SEQN_I 
	FROM (
		SELECT APPT_I, QSTN_C, RESP_C, RESP_CMMT_X, PATY_I, EFFT_D, EXPY_D, ROW_SECU_ACCS_C, PROS_KEY_EFFT_I, PROS_KEY_EXPY_I, EROR_SEQN_I,
		 ROW_NUMBER() OVER (PARTITION BY APPT_I, EFFT_D, EROR_SEQN_I, EXPY_D, PATY_I, PROS_KEY_EFFT_I, PROS_KEY_EXPY_I, QSTN_C, RESP_C, RESP_CMMT_X, ROW_SECU_ACCS_C ORDER BY 1 ASC) AS ROW_NUM 
		FROM {{ ref('TgtAppt_Qstn') }}
	) AS Remove_Duplicates_TEMP
	WHERE ROW_NUM = 1
)

SELECT * FROM Remove_Duplicates