{{ config(materialized='view', tags=['DltASETFrmTMP_ASET']) }}

WITH 
cse4_tmp_aset AS (
	SELECT
	*
	FROM {{ ref("cse4_tmp_aset")  }}),
aset AS (
	SELECT
	*
	FROM {{ ref("aset")  }}),
SrcTmpASETTera AS (SELECT a.ASET_I, a.SECU_CODE_C, a.SECU_CATG_C, a.SRCE_SYST_ASET_I, a.SRCE_SYST_C, a.ASET_C, a.ORIG_SRCE_SYST_ASET_I, a.ORIG_SRCE_SYST_C, a.ENVT_F, a.ASET_X, a.EFFT_D, a.EXPY_D, a.EROR_SEQN_I, a.ASET_LIBL_C, a.AL_CATG_C, a.DUPL_ASET_F FROM CSE4_TMP_ASET LEFT OUTER JOIN ASET ON TRIM(a.SRCE_SYST_ASET_I) = TRIM(b.SRCE_SYST_ASET_I) AND b.EXPY_D = '9999-12-31' WHERE a.RUN_STRM = '{{ var("RUN_STREAM") }}' AND b.SRCE_SYST_ASET_I IS NULL)


SELECT * FROM SrcTmpASETTera