{{ config(materialized='view', tags=['LdREJT_COM_BUS_REAS_SM_CASE_STAT']) }}

WITH ModConversions AS (
	SELECT 
	--Manual
	--ETL_D= date_from_string[%yyyy%mm%dd] (ETL_D)
	--ORIG_ETL_D= date_from_string[%yyyy%mm%dd] (ORIG_ETL_D)
	SM_CASE_STATE_ID, SCS_SM_CASE_ID, SCS_SM_STATE_CAT_ID, SCS_START_DATE, SCS_END_DATE, SCS_CREATED_BY_STAFF_NUMBER, SCS_STATE_CAUSED_BY_ACTION_ID, SCSR_SM_CASE_STATE_REASON_ID, SCSR_SM_REASON_CAT_ID, SM_CASE_STATE_REAS_FOUND_FLAG, SM_CASE_STATE_FOUND_FLAG, ETL_D, ORIG_ETL_D, EROR_C 
	FROM {{ ref('FunRejectsNulls') }}
)

SELECT * FROM ModConversions