{{ config(materialized='view', tags=['DltAPPT_TRNF_DETLFrmTMP_APPT_TRNF_DETL']) }}

WITH 
appt_trnf_detl AS (
	SELECT
	*
	FROM {{ ref("appt_trnf_detl")  }}),
tmp_appt_trnf_detl AS (
	SELECT
	*
	FROM {{ ref("tmp_appt_trnf_detl")  }}),
SrcTmpApptTrnfDetlTera AS (SELECT a.APPT_I AS NEW_APPT_I, a.APPT_TRNF_I AS NEW_APPT_TRNF_I, a.TRNF_OPTN_C AS NEW_TRNF_OPTN_C, a.TRNF_A AS NEW_TRNF_A, a.CNCY_C AS NEW_CNCY_C, a.CMPE_I AS NEW_CMPE_I, b.APPT_TRNF_I AS OLD_APPT_TRNF_I, b.TRNF_OPTN_C AS OLD_TRNF_OPTN_C, b.TRNF_A AS OLD_TRNF_A, b.CMPE_I AS OLD_CMPE_I, b.EFFT_D AS OLD_EFFT_D, b.APPT_I AS OLD_APPT_I FROM TMP_APPT_TRNF_DETL LEFT OUTER JOIN APPT_TRNF_DETL ON TRIM(a.APPT_TRNF_I) = TRIM(b.APPT_TRNF_I) AND TRIM(a.APPT_I) = TRIM(b.APPT_I) AND b.EXPY_D = '9999-12-31' WHERE a.RUN_STRM = '{{ var("RUN_STREAM") }}')


SELECT * FROM SrcTmpApptTrnfDetlTera