CREATE OR REPLACE TASK NPD_D12_DMN_GDWMIG.TMP.T_EXECUTE_DBT_CSEL
            WAREHOUSE = wh_usr_npd_d12_gdwmig_001
            SCHEDULE = 'USING CRON 0 3 * * * Australia/Sydney'
            -- USER_TASK_TIMEOUT_MS = 7200000
            ALLOW_OVERLAPPING_EXECUTION = FALSE
AS
    CALL NPD_D12_DMN_GDWMIG.TMP.P_EXECUTE_DBT_CSEL();
 

ALTER TASK NPD_D12_DMN_GDWMIG.TMP.T_EXECUTE_DBT_CSEL RESUME;


--find return

SELECT QUERY_ID,STATE,QUERY_START_TIME,*
FROM TABLE(NPD_D12_DMN_GDWMIG.INFORMATION_SCHEMA.TASK_HISTORY(TASK_NAME => 'T_EXECUTE_DBT_CSEL')) A
WHERE SCHEMA_NAME = 'TMP'
ORDER BY A.QUERY_START_TIME DESC;

SELECT * FROM TABLE(RESULT_SCAN('01be55bb-3204-b365-0000-c7212f9b4bc2'));